/**
 * Reading and writing numbers the way the game writes them.
 *
 * The notation ladder is the game's own — K, M, B, T, then the doubled letters AA through AZ —
 * and everything here either parses that form or produces it.
 */
/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    —
 * depends    src/formatting/numbers/compute, src/formatting/numbers/types
 * used by    —
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
export * from './types'
export * from './compute'
