/**
 * The vocabulary of number formatting.
 *
 * Rule 8a: every exported type of this subject lives here, so a module that needs one imports it
 * instead of declaring a near-identical shape of its own. That is how one idea ends up with three
 * names, and this package has the scars.
 */
/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    DecimalPreference, FormatMode, SmallNumberStrategy, FormatNumberForDisplayOptions, FormatUnknownNumberForDisplayOptions, FormatDateTimeForDisplayOptions, FormatSecondsAsHoursMinutesOptions, FormatGroupedNumberOptions (+1 more)
 * depends    —
 * used by    src/formatting/numbers/compute, src/formatting/numbers/index
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */

/**
 * Which character a player reads as the decimal point.
 *
 * Exported because it is part of the signature of `formatNumberForDisplay`,
 * `parseResource` and `normalizeDecimalSeparator` — a consumer storing this preference
 * needs to be able to name its type.
 */
export type DecimalPreference = 'Period (.)' | 'Comma (,)'

export type FormatMode = 'display' | 'compact' | 'grouped'
export type SmallNumberStrategy = 'round' | 'preserve'

export interface FormatNumberForDisplayOptions {
  mode?: FormatMode
  smallNumberStrategy?: SmallNumberStrategy
  smallNumberMaxFractionDigits?: number
  notationMaxFractionDigits?: number
  useGrouping?: boolean
}

export interface FormatUnknownNumberForDisplayOptions extends FormatNumberForDisplayOptions {
  decimalPreference?: DecimalPreference
  invalidFallback?: string
  nullFallback?: string
}

export interface FormatDateTimeForDisplayOptions {
  invalidFallback?: string
}

export interface FormatSecondsAsHoursMinutesOptions {
  zeroFallback?: string
}

export interface FormatGroupedNumberOptions {
  locale?: string
  useGrouping?: boolean
  minimumFractionDigits?: number
  maximumFractionDigits?: number
  invalidFallback?: string
}

/**
 * A number and its unit, pulled out of a display string.
 *
 * `value` is ALWAYS finite. Before 2026-08-18 it was `parseFloat(...) / 1000`
 * with no guard, so any unparseable string produced NaN and handed it to the
 * caller — `parseValueWithUnit("abc")` returned `{ value: NaN, unit: "K" }`.
 *
 * `parsed` is how absence is reported. Returning 0 alone would be a silent
 * default of exactly the kind that hides here: a run with an unreadable coin
 * total would sort and average as if it were zero. Callers that care about the
 * difference between "no number" and "the number nought" must read `parsed`;
 * callers that only need arithmetic get a finite value either way.
 */
export interface ParsedValueWithUnit {
  /** Always finite. `0` when nothing could be read — check `parsed` to tell them apart. */
  value: number
  unit: string
  /** `false` when the input carried no readable number. */
  parsed: boolean
}
