/**
 * Relics, their tiers, and the bonuses each grants.
 *
 * The import catalog and the save's own description strings are the authority for a relic's bonus
 * type — both this catalog and the community sheet have been wrong about them before.
 */
/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    —
 * depends    src/data/relics/data
 * used by    —
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
export * from './data'
