/**
 * Small reference tables, and the runtime schemas that validate the public data surface.
 *
 * The schemas are here rather than beside each catalog because they describe the shape of the
 * published tables as a set — a consumer validating one is usually validating several.
 */
/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    —
 * depends    src/data/reference/data, src/data/reference/validate
 * used by    —
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
export * from './data'
export * from './validate'
