/**
 * What a Dissonant Echo lab is worth at a given level.
 *
 * The benefit is linear: half a percent per level, starting at half a percent for level 0 rather
 * than nothing. Verified against the catalog in `dissonant-echo-matches-the-catalog.test.ts` —
 * all four labs, all 21 levels, exact.
 *
 * ## Why this is a formula and not a lookup
 *
 * It was both. `internal/game-input-data/` held a catalog reader and a formula for the same fact,
 * plus a fallback that used the formula whenever the catalog answered 0 for a level above 0. That
 * fallback never fired: the catalog answers 0 for no level of any of the four labs. So the package
 * carried two sources of truth for one number and a branch reconciling a disagreement that does
 * not exist.
 *
 * Rule 8b says one of them has to be canonical, and Rule 9 says a formula may be the one where it
 * reproduces the table exactly. This does, so it is.
 */
/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    computeDissonantEchoBenefitFraction, computeDissonantEchoBenefitPct, dissonantEchoLabMaxLevel, isBcCounterResearchLabSlug, computeResearchLabMaxLevel
 * depends    src/data, src/mechanics/battle-conditions/config, src/mechanics/labs/constants
 * used by    src/mechanics/calculators/specs-generated, src/mechanics/enemies/wave-panel, src/mechanics/labs/index
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
import {
  CANONICAL_LAB_SLUG_BY_ALIAS,
  findLabResearchBySlug,
  findToolLabBySlug,
  getLabMaxLevel,
} from '../../data'
import { ENEMY_STATS_BC_COUNTER_LAB_SLUGS } from '../battle-conditions/config'
import {
  BC_GLOBAL_REDUCTION_LAB_SLUG,
  DISSONANT_ECHO_BENEFIT_STEP,
  DISSONANT_ECHO_LAB_SLUGS,
  IMPROVE_TRADE_OFF_LAB_SLUG,
  LAB_MAX_LEVEL_FALLBACK,
  MAX_BC_GLOBAL_REDUCTION_LAB_LEVEL,
  MAX_BC_SPECIFIC_LAB_LEVEL,
  MAX_IMPROVE_TRADE_OFF_LAB_LEVEL,
} from './constants'

/**
 * The fraction a Dissonant Echo lab grants at `level`.
 *
 * Level 0 is already worth a step — the lab is bought, not unlocked at zero value — which is why
 * this is `(level + 1)` rather than `level`. A negative level is not a level and returns 0.
 */
export function computeDissonantEchoBenefitFraction(level: number): number {
  if (!Number.isFinite(level) || level < 0) return 0
  return (Math.floor(level) + 1) * DISSONANT_ECHO_BENEFIT_STEP
}

/** The same benefit as a percentage, for callers that display one. */
export function computeDissonantEchoBenefitPct(level: number): number {
  return computeDissonantEchoBenefitFraction(level) * 100
}

/**
 * The highest level any Dissonant Echo lab reaches.
 *
 * Read from the catalog rather than written as 20, because the previous code wrote 20 and a lab
 * cap that moves in a patch would leave the constant behind, silently clamping levels a player can
 * actually buy.
 */
export function dissonantEchoLabMaxLevel(): number {
  let max = 0
  for (const slug of DISSONANT_ECHO_LAB_SLUGS) {
    const lab = findToolLabBySlug(slug)
    if (lab) max = Math.max(max, getLabMaxLevel(lab))
  }
  return max
}

/** Whether a slug names one of the labs that counters a specific battle condition. */
export function isBcCounterResearchLabSlug(slug: string): boolean {
  return (ENEMY_STATS_BC_COUNTER_LAB_SLUGS as readonly string[]).includes(slug)
}

/**
 * The max level the catalog knows for a lab, by either of its spellings.
 *
 * The alias is resolved once and used for both lookups. The version this replaced resolved it for
 * the research lookup and then passed the RAW slug to the tool-lab lookup, so an aliased slug took
 * a different path through the two. It happens to make no difference — all sixteen aliases return
 * the same level either way — but only by luck, and the next alias need not be so lucky.
 */
function catalogLabMaxLevel(slug: string): number {
  const canonical = CANONICAL_LAB_SLUG_BY_ALIAS[slug] ?? slug
  const labRecord = findToolLabBySlug(canonical) ?? findToolLabBySlug(slug)
  if (labRecord) return getLabMaxLevel(labRecord)
  const research = findLabResearchBySlug(canonical) ?? findLabResearchBySlug(slug)
  return research?.levelMax ?? LAB_MAX_LEVEL_FALLBACK
}

/**
 * How far a research lab goes, including the three the catalog cannot answer for.
 *
 * The battle-condition counter labs are the interesting case: they have catalog levels AND a cap
 * from the system they feed, so the answer is the lower of the two rather than either one.
 */
export function computeResearchLabMaxLevel(slug: string): number {
  if (slug === IMPROVE_TRADE_OFF_LAB_SLUG) return MAX_IMPROVE_TRADE_OFF_LAB_LEVEL
  if (slug === BC_GLOBAL_REDUCTION_LAB_SLUG) return MAX_BC_GLOBAL_REDUCTION_LAB_LEVEL
  if (isBcCounterResearchLabSlug(slug)) {
    return Math.min(catalogLabMaxLevel(slug), MAX_BC_SPECIFIC_LAB_LEVEL)
  }
  return catalogLabMaxLevel(slug)
}
