/**
 * Fixed values behind the lab formulas.
 *
 * The spelling is the game's: the labs are **Dissonant** Echo, as their slugs say
 * (`dissonant_echo_attack`) and as the catalog displays them (`Dissonant Echo - Defense`). The
 * package elsewhere calls them `DissonanceEcho`, which is a different word — dissonance is the
 * run debuff, dissonant is the lab. Rule 4 says names come from the game's vocabulary, so new
 * code uses the game's.
 */
/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    DISSONANT_ECHO_BENEFIT_STEP, DISSONANT_ECHO_LAB_SLUGS, IMPROVE_TRADE_OFF_LAB_SLUG, MAX_IMPROVE_TRADE_OFF_LAB_LEVEL, MAX_BC_GLOBAL_REDUCTION_LAB_LEVEL, MAX_BC_SPECIFIC_LAB_LEVEL, BC_GLOBAL_REDUCTION_LAB_SLUG, LAB_MAX_LEVEL_FALLBACK (+4 more)
 * depends    —
 * used by    src/internal/local-state/dissonance-calcs, src/internal/shared-tool-inputs/from-research, src/mechanics/enemies/wave-panel, src/mechanics/labs/bc-counter-labs, src/mechanics/labs/compute, src/mechanics/labs/index (+3 more)
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */

/** How much benefit one Dissonant Echo lab level is worth, as a fraction. */
export const DISSONANT_ECHO_BENEFIT_STEP = 0.005

/** The four Dissonant Echo labs, by catalog slug. */
export const DISSONANT_ECHO_LAB_SLUGS = [
  'dissonant_echo_attack',
  'dissonant_echo_defense',
  'dissonant_echo_utility',
  'dissonant_echo_ultimate_weapons',
] as const

/** The perk trade-off research lab, which is capped separately from the catalog. */
export const IMPROVE_TRADE_OFF_LAB_SLUG = 'improve_trade_off_perks'

/**
 * Caps that the catalog does not carry.
 *
 * These three labs are bounded by the systems they feed rather than by their own level tables, so
 * the number cannot be read from the catalog the way every other lab's can. They are stated here
 * and the reason is stated with them, because an unexplained constant is the thing that later gets
 * "simplified" into a catalog lookup that returns something else.
 */
export const MAX_IMPROVE_TRADE_OFF_LAB_LEVEL = 10
export const MAX_BC_GLOBAL_REDUCTION_LAB_LEVEL = 10
export const MAX_BC_SPECIFIC_LAB_LEVEL = 20

/** The lab whose level caps the global battle-condition reduction. */
export const BC_GLOBAL_REDUCTION_LAB_SLUG = 'battle_condition_reduction'

/** A lab whose max level the catalog does not know, and what it is instead. */
export const LAB_MAX_LEVEL_FALLBACK = 30

/**
 * Which Dissonant Echo lab answers which dissonance type.
 *
 * The pairing is game vocabulary — `attack` is countered by `dissonant_echo_attack` — and it lived
 * in a dropdown module until that module left for the platform layer. A consumer holding a
 * dissonance type and wanting its lab needs this, and so does anything reading echo levels out of
 * a set of research levels.
 *
 * Keyed by the type's own name rather than by an index, because the dissonance enum is 1-based and
 * a positional map would put every entry on the wrong lab.
 */
/**
 * The four dissonance types, in the order the game lists them.
 *
 * These were declared in a calculator's form-state module, which meant the save reader, the import
 * counter and the lab map each depended on a widget's settings file to know what the game's four
 * types are called. The map below is keyed by exactly these, so they belong together: one list,
 * and a type that keeps the map honest if it ever changes.
 */
export const DISSONANCE_TYPE_KEYS = ['attack', 'defense', 'utility', 'uw'] as const
export type DissonanceTypeKey = typeof DISSONANCE_TYPE_KEYS[number]

/**
 * Dissonance stops accruing benefit past this wave.
 */
export const DISSONANCE_MAX_EFFECTIVE_WAVE = 5000

export const DISSONANT_ECHO_LAB_SLUG_BY_TYPE: Record<DissonanceTypeKey, string> = {
  attack: 'dissonant_echo_attack',
  defense: 'dissonant_echo_defense',
  utility: 'dissonant_echo_utility',
  uw: 'dissonant_echo_ultimate_weapons',
}
