/**
 * Which cosmetic themes have been collected.
 *
 * Stored as a `collectedThemes` map keyed by the catalog's own label, so a name that has been
 * re-spelled in the catalog stops matching what older saves hold.
 */
/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    —
 * depends    src/save/themes/read
 * used by    —
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
export * from './read'
