/**
 * The chart catalog — every chart this game data supports, and what it is.
 *
 * ## Why it lives here
 *
 * A chart is a view over game data, so the catalog of charts is game data. It
 * was previously the only such catalog outside this package, which is why an
 * agent looking for what the SDK knows about Ultimate Weapon Enhancements found
 * nothing: the chart documenting them lived somewhere else entirely.
 *
 * ## What this is NOT
 *
 * Not rendering. Nothing here draws, styles, lays out or localises. `title` and
 * `description` are canonical English; a consumer that needs another language
 * wraps them. The render engine, the studio and the spreadsheet layer all stay
 * with the application.
 *
 * ## pathId
 *
 * The stable address of a chart, `category:subcategory:item`. Several paths may
 * share one `rendererKey` where the same chart is reachable from more than one
 * place in the tree — Golden Bot vs Death Wave Uptime appears under both Bots
 * and Ultimate Weapons. So `pathId` is unique; `rendererKey` is not.
 */
/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    SharedChartRendererKey, SharedChartDefinition, SHARED_CHART_REGISTRY, findChartByPathId, findChartsByRendererKey, listChartRendererKeys
 * depends    —
 * used by    src/charts/index, src/charts/registry/calculator-links, src/charts/registry/index, src/charts/registry/mechanic-links, src/charts/tables/lookup, src/mechanics/calculators/specs-generated
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */

/** Which renderer draws a chart. One renderer may serve several paths. */
export type SharedChartRendererKey =
  | 'avg-bullets-to-stack-shock'
  | 'bonus-multipliers'
  | 'bot-upgrades'
  | 'card-mastery-cost-bonuses'
  | 'cfplus-rotation-rates'
  | 'cfplus-speed-rates'
  | 'chain-thunder-dmg-reduction'
  | 'elite-spawn-chance'
  | 'enemy-balance-mastery'
  | 'enemy-resistances'
  | 'eo-vs-sla-breakpoints'
  | 'gold-bot-vs-death-wave-uptime'
  | 'gt-combo-relative-income'
  | 'gt-combo-uptime-income'
  | 'gt-lab-milestones'
  | 'guild-box-rewards'
  | 'harmony-tree-upgrades'
  | 'lab-speed-multiplier'
  | 'module-substat-values'
  | 'perma-swamp-stone-costs'
  | 'power-tree-upgrades'
  | 'recovery-package-drop-rates'
  | 'uw-plus-upgrades'
  | 'uw-stone-costs'
  | 'wave-accelerator-spawn-rates'
  | 'wave-skip-coin-boost'
  | 'wave-skip-multi-skip-chances'

export interface SharedChartDefinition {
  /** Stable address: `category:subcategory:item`. Unique. */
  pathId: string
  /** Which renderer draws it. NOT unique — several paths may share one. */
  rendererKey: SharedChartRendererKey
  /** Canonical English title. Localisation is the consumer's job. */
  title: string
  /** Canonical English description. */
  description: string
  /** Exported image filename, for consumers that publish stills. */
  fileName: string
  /** Accent colour used when the chart is rendered. */
  colorHex: string
  /** Attribution, where a community member produced the chart. */
  creatorCredit?: string
}

export const SHARED_CHART_REGISTRY: readonly SharedChartDefinition[] = [
  {
    pathId: "vault:upgrades-and-cost:harmony-tree",
    rendererKey: "harmony-tree-upgrades",
    title: "Harmony Tree Upgrades & Costs",
    description: "All upgrades and key costs in the Harmony tech tree.",
    fileName: "harmony-tree-upgrades-costs.png",
    colorHex: "#3ec6ff",
  },
  {
    pathId: "vault:upgrades-and-cost:power-tree",
    rendererKey: "power-tree-upgrades",
    title: "Power Tree Upgrades & Costs",
    description: "All upgrades and key costs in the Power tech tree.",
    fileName: "power-tree-upgrades-costs.png",
    colorHex: "#f7b731",
  },
  {
    pathId: "ultimate-weapons:ultimate-weapons:upgrades-and-costs",
    rendererKey: "uw-plus-upgrades",
    title: "Ultimate Weapons+ Upgrades and Costs",
    description: "All upgrade costs and effects for Ultimate Weapons+ (UW+).",
    fileName: "uw-plus-upgrades-costs.png",
    colorHex: "#b6fcd5",
    creatorCredit: "@kosmirionepos",
  },
  {
    pathId: "ultimate-weapons:stone-costs:chain-lightning",
    rendererKey: "uw-stone-costs",
    title: "Ultimate Weapon Stone Costs: Chain Lightning",
    description: "Stone costs by level for Chain Lightning ultimate weapon upgrades.",
    fileName: "uw-stone-costs-chain-lightning.png",
    colorHex: "#4dd0e1",
  },
  {
    pathId: "ultimate-weapons:stone-costs:chronofield",
    rendererKey: "uw-stone-costs",
    title: "Ultimate Weapon Stone Costs: Chronofield",
    description: "Stone costs by level for Chronofield ultimate weapon upgrades.",
    fileName: "uw-stone-costs-chronofield.png",
    colorHex: "#4dd0e1",
  },
  {
    pathId: "ultimate-weapons:stone-costs:death-wave",
    rendererKey: "uw-stone-costs",
    title: "Ultimate Weapon Stone Costs: Death Wave",
    description: "Stone costs by level for Death Wave ultimate weapon upgrades.",
    fileName: "uw-stone-costs-death-wave.png",
    colorHex: "#4dd0e1",
  },
  {
    pathId: "ultimate-weapons:stone-costs:golden-tower",
    rendererKey: "uw-stone-costs",
    title: "Ultimate Weapon Stone Costs: Golden Tower",
    description: "Stone costs by level for Golden Tower ultimate weapon upgrades.",
    fileName: "uw-stone-costs-golden-tower.png",
    colorHex: "#4dd0e1",
  },
  {
    pathId: "ultimate-weapons:stone-costs:inner-land-mines",
    rendererKey: "uw-stone-costs",
    title: "Ultimate Weapon Stone Costs: Inner Land Mines",
    description: "Stone costs by level for Inner Land Mines ultimate weapon upgrades.",
    fileName: "uw-stone-costs-inner-land-mines.png",
    colorHex: "#4dd0e1",
  },
  {
    pathId: "ultimate-weapons:stone-costs:poison-swamp",
    rendererKey: "uw-stone-costs",
    title: "Ultimate Weapon Stone Costs: Poison Swamp",
    description: "Stone costs by level for Poison Swamp ultimate weapon upgrades.",
    fileName: "uw-stone-costs-poison-swamp.png",
    colorHex: "#4dd0e1",
  },
  {
    pathId: "ultimate-weapons:stone-costs:smart-missiles",
    rendererKey: "uw-stone-costs",
    title: "Ultimate Weapon Stone Costs: Smart Missiles",
    description: "Stone costs by level for Smart Missiles ultimate weapon upgrades.",
    fileName: "uw-stone-costs-smart-missiles.png",
    colorHex: "#4dd0e1",
  },
  {
    pathId: "ultimate-weapons:stone-costs:spotlight",
    rendererKey: "uw-stone-costs",
    title: "Ultimate Weapon Stone Costs: Spotlight",
    description: "Stone costs by level for Spotlight ultimate weapon upgrades.",
    fileName: "uw-stone-costs-spotlight.png",
    colorHex: "#4dd0e1",
  },
  {
    pathId: "ultimate-weapons:stone-costs:black-hole",
    rendererKey: "uw-stone-costs",
    title: "Ultimate Weapon Stone Costs: Black Hole",
    description: "Stone costs by level for Black Hole ultimate weapon upgrades.",
    fileName: "uw-stone-costs-black-hole.png",
    colorHex: "#4dd0e1",
  },
  {
    pathId: "ultimate-weapons:golden-tower:golden-combo-relative-income",
    rendererKey: "gt-combo-relative-income",
    title: "Golden Combo Relative Income",
    description: "Relative income comparison across Golden Combo levels and Golden Tower durations.",
    fileName: "golden-combo-relative-income.png",
    colorHex: "#f4d35e",
  },
  {
    pathId: "ultimate-weapons:golden-tower:golden-combo-relative-income-100-gt-uptime",
    rendererKey: "gt-combo-uptime-income",
    title: "Golden Combo Relative Income (100% GT Uptime)",
    description: "Relative income comparison across Golden Combo levels and Golden Tower durations once GT already has full uptime.",
    fileName: "golden-combo-relative-income-100-uptime.png",
    colorHex: "#f6bd60",
  },
  {
    pathId: "milestones:ultimate-weapons:golden-tower-lab-unlocks",
    rendererKey: "gt-lab-milestones",
    title: "Golden Tower Lab Unlock Milestones",
    description: "Milestone unlock requirements for Golden Tower Bonus and Golden Tower Duration labs.",
    fileName: "golden-tower-lab-unlock-milestones.png",
    colorHex: "#84a59d",
  },
  {
    pathId: "ultimate-weapons:chain-lightning:avg-bullets-to-stack-shock",
    rendererKey: "avg-bullets-to-stack-shock",
    title: "Avg Bullets to Stack 5 Shocks",
    description: "Average number of bullets required to stack 5 shocks at different proc chances.",
    fileName: "avg-bullets-to-stack-shock.png",
    colorHex: "#3ec6ff",
  },
  {
    pathId: "modules:substats:cannon",
    rendererKey: "module-substat-values",
    title: "Module Substat Values: Cannon",
    description: "All substat value tiers for Cannon modules.",
    fileName: "module-substat-values-cannon.png",
    colorHex: "#a5d6a7",
  },
  {
    pathId: "modules:substats:defense",
    rendererKey: "module-substat-values",
    title: "Module Substat Values: Defense",
    description: "All substat value tiers for Defense modules.",
    fileName: "module-substat-values-defense.png",
    colorHex: "#a5d6a7",
  },
  {
    pathId: "modules:substats:generator",
    rendererKey: "module-substat-values",
    title: "Module Substat Values: Generator",
    description: "All substat value tiers for Generator modules.",
    fileName: "module-substat-values-generator.png",
    colorHex: "#a5d6a7",
  },
  {
    pathId: "modules:substats:core",
    rendererKey: "module-substat-values",
    title: "Module Substat Values: Core",
    description: "All substat value tiers for Core modules.",
    fileName: "module-substat-values-core.png",
    colorHex: "#a5d6a7",
  },
  {
    pathId: "modules:project-funding:bonus-multipliers",
    rendererKey: "bonus-multipliers",
    title: "Bonus Multipliers",
    description: "All bonus multipliers for Project Funding module.",
    fileName: "bonus-multipliers.png",
    colorHex: "#b6fcd5",
  },
  {
    pathId: "modules:blackhole-digester-bhd:wave-skip-coin-boost",
    rendererKey: "wave-skip-coin-boost",
    title: "BHD Coin Boost Chart",
    description: "Average expected CPK increase from BHD based on Wave Skip mastery and Free-up chance.",
    fileName: "wave-skip-coin-boost.png",
    colorHex: "#00cc99",
  },
  {
    pathId: "bots:upgrades-and-costs:flame-bot",
    rendererKey: "bot-upgrades",
    title: "Bot Upgrades: Flame Bot",
    description: "Upgrade values and costs for Flame Bot.",
    fileName: "bot-upgrades-flame-bot.png",
    colorHex: "#ffcc80",
  },
  {
    pathId: "bots:upgrades-and-costs:golden-bot",
    rendererKey: "bot-upgrades",
    title: "Bot Upgrades: Golden Bot",
    description: "Upgrade values and costs for Golden Bot.",
    fileName: "bot-upgrades-golden-bot.png",
    colorHex: "#ffcc80",
  },
  {
    pathId: "bots:upgrades-and-costs:thunder-bot",
    rendererKey: "bot-upgrades",
    title: "Bot Upgrades: Thunder Bot",
    description: "Upgrade values and costs for Thunder Bot.",
    fileName: "bot-upgrades-thunder-bot.png",
    colorHex: "#ffcc80",
  },
  {
    pathId: "bots:upgrades-and-costs:amplify-bot",
    rendererKey: "bot-upgrades",
    title: "Bot Upgrades: Amplify Bot",
    description: "Upgrade values and costs for Amplify Bot.",
    fileName: "bot-upgrades-amplify-bot.png",
    colorHex: "#ffcc80",
  },
  {
    pathId: "labs:cells:most-efficient-speed-multipliers",
    rendererKey: "lab-speed-multiplier",
    title: "Most Efficient Lab Speed Multiplier",
    description: "Shows the most efficient speed multiplier combinations for labs.",
    fileName: "lab-speed-multiplier.png",
    colorHex: "#fcd5b6",
  },
  {
    pathId: "cards:masteries:all-bonuses",
    rendererKey: "card-mastery-cost-bonuses",
    title: "Card Mastery Cost and Bonuses",
    description: "See cost and bonus values for all card masteries at each level.",
    fileName: "card-mastery-cost-bonuses.png",
    colorHex: "#b6fcd5",
  },
  {
    pathId: "masteries:bonuses-and-costs:all-bonuses",
    rendererKey: "card-mastery-cost-bonuses",
    title: "Card Mastery Cost and Bonuses",
    description: "See cost and bonus values for all card masteries at each level.",
    fileName: "card-mastery-cost-bonuses.png",
    colorHex: "#b6fcd5",
  },
  {
    pathId: "enemies:elites:elite-spawn-chance",
    rendererKey: "elite-spawn-chance",
    title: "Elite Enemy Spawn Chance Increase Per Wave and Tier",
    description: "Shows what waves single/double elite spawn chance values change per-tier.",
    fileName: "elite-spawn-chance.png",
    colorHex: "#e86e1c",
  },
  {
    pathId: "masteries:wave-accelerator:spawn-rates",
    rendererKey: "wave-accelerator-spawn-rates",
    title: "Wave Accelerator Mastery: Spawn Rates",
    description: "Spawn count for each normal value and spawn rate reduction.",
    fileName: "wave-accelerator-spawn-rates.png",
    colorHex: "#00cc99",
  },
  {
    pathId: "masteries:recovery-package-chance-care-package:drop-rates",
    rendererKey: "recovery-package-drop-rates",
    title: "Recovery Package Chance Mastery: Drop Rates",
    description: "Shards per day for each Shatter Lab and RPC+ mastery level.",
    fileName: "recovery-package-drop-rates.png",
    colorHex: "#00cc99",
  },
  {
    pathId: "masteries:enemy-balance:enemy-balance-mastery",
    rendererKey: "enemy-balance-mastery",
    title: "Enemy Balance Mastery",
    description: "Chance of x2 elite spawns and average elite kills per wave by mastery level.",
    fileName: "enemy-balance-mastery.png",
    colorHex: "#e86e1c",
  },
  {
    pathId: "ultimate-weapons:poison-swamp:perma-swamp-stone-costs",
    rendererKey: "perma-swamp-stone-costs",
    title: "Perma Swamp Stone Costs",
    description: "Stone costs to achieve perma Poison Swamp and efficient upgrade paths.",
    fileName: "perma-swamp-stone-costs.png",
    colorHex: "#8bc47f",
  },
  {
    pathId: "cards:wave-skip:multi-skip-chances",
    rendererKey: "wave-skip-multi-skip-chances",
    title: "Wave Skip Multi-Skip Chances",
    description: "Probability of multi-skips with maxed Wave Skip assumptions.",
    fileName: "wave-skip-multiskip-chances.png",
    colorHex: "#b6fcd5",
  },
  {
    pathId: "masteries:wave-skip:multi-skip-chances",
    rendererKey: "wave-skip-multi-skip-chances",
    title: "Wave Skip Multi-Skip Chances",
    description: "Probability of multi-skips with maxed Wave Skip assumptions.",
    fileName: "wave-skip-multiskip-chances.png",
    colorHex: "#b6fcd5",
  },
  {
    pathId: "enemies:resistances:enemy-resistances",
    rendererKey: "enemy-resistances",
    title: "Enemy Resistances",
    description: "Breakdown of enemy resistance effectiveness by type.",
    fileName: "enemy-resistances.png",
    colorHex: "#e74c3c",
    creatorCredit: "<@703724472204525578>",
  },
  {
    pathId: "ultimate-weapons:chronofield:cf-speed-rates",
    rendererKey: "cfplus-speed-rates",
    title: "CF+ Speed Rates",
    description: "Hidden slow% and enemy speed rates for CF+ upgrades.",
    fileName: "cfplus-speed-rates.png",
    colorHex: "#00cc99",
    creatorCredit: "@priesten / @yournicknm",
  },
  {
    pathId: "ultimate-weapons:chronofield:cf-rotation-rates",
    rendererKey: "cfplus-rotation-rates",
    title: "CF+ Rotation Rates",
    description: "Rotation/orbit timing for CF+ upgrade levels.",
    fileName: "cfplus-rotation-rates.png",
    colorHex: "#00cc99",
    creatorCredit: "@priesten / @yournicknm",
  },
  {
    pathId: "masteries:extra-orb:eo-vs-sla-breakpoints",
    rendererKey: "eo-vs-sla-breakpoints",
    title: "EO vs SLA Breakpoints",
    description: "Coin-efficiency breakpoints for SLA and EO setups.",
    fileName: "eo-vs-sla-breakpoints.png",
    colorHex: "#ffe066",
  },
  {
    pathId: "ultimate-weapons:spotlight:eo-vs-sla-breakpoints",
    rendererKey: "eo-vs-sla-breakpoints",
    title: "EO vs SLA Breakpoints",
    description: "Coin-efficiency breakpoints for SLA and EO setups.",
    fileName: "eo-vs-sla-breakpoints.png",
    colorHex: "#ffe066",
  },
  {
    pathId: "ultimate-weapons:death-wave:gold-bot-vs-death-wave-uptime",
    rendererKey: "gold-bot-vs-death-wave-uptime",
    title: "Golden Bot vs Death Wave Uptime",
    description: "Average DW uptime compared to GB at 48s and 50s sync.",
    fileName: "gold-bot-vs-death-wave-uptime.png",
    colorHex: "#ffe066",
  },
  {
    pathId: "bots:gold-bot:gold-bot-vs-death-wave-uptime",
    rendererKey: "gold-bot-vs-death-wave-uptime",
    title: "Golden Bot vs Death Wave Uptime",
    description: "Average DW uptime compared to GB at 48s and 50s sync.",
    fileName: "gold-bot-vs-death-wave-uptime.png",
    colorHex: "#ffe066",
  },
  {
    pathId: "ultimate-weapons:chain-lightning:chain-thunder-dmg-reduction",
    rendererKey: "chain-thunder-dmg-reduction",
    title: "Chain Thunder Dmg Reduction",
    description: "CT lab reduction values and CL+ requirements.",
    fileName: "chain-thunder-dmg-reduction.png",
    colorHex: "#00ffff",
  },
  {
    pathId: "labs:ultimate-weapons:chain-thunder-dmg-reduction",
    rendererKey: "chain-thunder-dmg-reduction",
    title: "Chain Thunder Dmg Reduction",
    description: "CT lab reduction values and CL+ requirements.",
    fileName: "chain-thunder-dmg-reduction.png",
    colorHex: "#00ffff",
  },
  {
    pathId: "guilds:rewards:guild-box-rewards",
    rendererKey: "guild-box-rewards",
    title: "Guild Box Rewards",
    description: "Guild box reward values by box tier and totals.",
    fileName: "guild-box-rewards.png",
    colorHex: "#7fff7f",
  },
]

/** One chart by its stable address. */
export function findChartByPathId(pathId: string): SharedChartDefinition | null {
  return SHARED_CHART_REGISTRY.find(entry => entry.pathId === pathId) ?? null
}

/**
 * Every chart drawn by a given renderer.
 *
 * Returns an array because `rendererKey` is not unique — asking for one and
 * getting the first would silently hide the others.
 */
export function findChartsByRendererKey(
  rendererKey: SharedChartRendererKey,
): readonly SharedChartDefinition[] {
  return SHARED_CHART_REGISTRY.filter(entry => entry.rendererKey === rendererKey)
}

/** Every distinct renderer in the catalog. */
export function listChartRendererKeys(): readonly SharedChartRendererKey[] {
  return [...new Set(SHARED_CHART_REGISTRY.map(entry => entry.rendererKey))].sort()
}
