/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    CHART_MECHANIC_LINKS
 * depends    src/charts/registry/data
 * used by    src/charts/index, src/charts/registry/index
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
import type { SharedChartRendererKey } from './data'

/**
 * Which oracle entities each chart documents.
 *
 * ## Why this exists
 *
 * The chart registry says what a chart is *called*. It does not say what it is
 * *about* in terms anything else understands, so two questions had no answer:
 *
 *  - "Which chart covers assist efficiency?" — an agent had to guess from
 *    titles, and titles are written for humans browsing, not for lookup.
 *  - "Is there a chart for a mechanic the graph does not model?" — a chart is
 *    validated data, so one covering an unmodelled mechanic is a *free gap
 *    report*. That is how the UW+ family was found: a chart existed, the graph
 *    had nothing.
 *
 * Linking them makes the catalog navigable in both directions and turns the
 * charts into a coverage check on the knowledge graph.
 *
 * ## The rule
 *
 * Every id here must resolve in `thetowersdk/knowledge`. A chart pointing at a
 * mechanic the oracle does not know is either a naming drift or a genuine gap,
 * and `chart-mechanic-links.parity.test.ts` fails on both.
 */
export const CHART_MECHANIC_LINKS: Readonly<
  Partial<Record<SharedChartRendererKey, readonly string[]>>
> = {
  'harmony-tree-upgrades': ['vault.harmonyTree', 'vault', 'currency.key'],
  'power-tree-upgrades': ['vault.powerTree', 'vault', 'currency.key'],

  'uw-plus-upgrades': ['ultimateWeaponPlus', 'ultimateWeapon'],
  'uw-stone-costs': ['ultimateWeapon', 'ultimateWeaponPlus'],

  'gt-combo-relative-income': ['ultimateWeaponPlus.goldenCombo', 'coinsPerKill'],
  'gt-combo-uptime-income': ['ultimateWeaponPlus.goldenCombo', 'coinsPerKill'],
  'gt-lab-milestones': ['ultimateWeapon.stat', 'lab', 'milestone'],

  'avg-bullets-to-stack-shock': ['attackSpeed', 'multishot'],
  'chain-thunder-dmg-reduction': ['ultimateWeaponPlus.Smite', 'damage'],

  'module-substat-values': ['module.subEffect', 'module.rarity'],
  'bonus-multipliers': ['module.mainEffect', 'module.rarity'],

  'wave-skip-coin-boost': ['waveSkip', 'coinsPerWave'],
  'wave-skip-multi-skip-chances': ['waveSkip', 'cardMastery.WaveSkip'],

  'bot-upgrades': ['bot', 'bot.cooldown', 'bot.bonus'],
  'gold-bot-vs-death-wave-uptime': ['bot.cooldown', 'cooldownSync', 'ultimateWeapon.stat'],

  'lab-speed-multiplier': ['lab.speed', 'lab.boost'],

  'card-mastery-cost-bonuses': ['cardMastery', 'cardMastery.lab'],
  'enemy-balance-mastery': ['cardMastery.EnemyBalance', 'enemy'],

  'elite-spawn-chance': ['enemy'],
  'enemy-resistances': ['tier.battleCondition', 'enemy'],

  'wave-accelerator-spawn-rates': ['cardMastery.WaveAccelerator', 'enemy'],
  'recovery-package-drop-rates': ['recoveryPackage'],

  'perma-swamp-stone-costs': ['buildTarget.perma', 'ultimateWeapon.stat'],
  'cfplus-speed-rates': ['ultimateWeaponPlus.ChronoLoop', 'buildTarget.slowThreshold'],
  'cfplus-rotation-rates': ['ultimateWeaponPlus.ChronoLoop'],

  'eo-vs-sla-breakpoints': ['orb', 'cardMastery.ExtraOrb', 'slowAura'],

  'guild-box-rewards': ['guardian'],
}
