/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    GuardianDefinition, getGuardianStatNames, getGuardianStatValues, getGuardianCostValues, getGuardianBaseValues, getGuardianStatBounds, getGuardianStatValueAt, getGuardianStatCostAt (+1 more)
 * depends    src/data/guardians/upgrades
 * used by    src/data/guardians/index, src/internal/uptime/shared-inputs, src/mechanics/calculators/run, src/mechanics/calculators/specs-generated, src/save/guardians/read, src/save/import/counts
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
import { guardianUpgrades } from './upgrades'

function getNormalizedGuardianLevelInfo(upgrades: Array<{ level?: number | null }>): { sourceMinLevel: number; normalizedMaxLevel: number } {
  const sourceLevels = upgrades
    .map(upgrade => Number(upgrade.level))
    .filter(level => Number.isFinite(level))

  if (sourceLevels.length === 0) {
    return { sourceMinLevel: 0, normalizedMaxLevel: 0 }
  }

  const sourceMinLevel = Math.min(...sourceLevels)
  const sourceMaxLevel = Math.max(...sourceLevels)

  return {
    sourceMinLevel,
    normalizedMaxLevel: Math.max(0, sourceMaxLevel - sourceMinLevel),
  }
}

export interface GuardianDefinition {
  key: string
  label: string
  statOrder: string[]
  stats: Record<string, { base: string | number | null; levels: Record<number, { value: string | number | null; cost: number | null }> }>
}

export function getGuardianStatNames(guardian: GuardianDefinition): string[] {
  return guardian.statOrder
}

function getGuardianLevelKeys(guardian: GuardianDefinition, statName: string): number[] {
  const stat = guardian.stats[statName]
  if (!stat) return []

  return Object.keys(stat.levels)
    .map(level => Number(level))
    .filter(level => Number.isFinite(level))
    .sort((a, b) => a - b)
}

export function getGuardianStatValues(guardian: GuardianDefinition): (string | number | null)[][] {
  return guardian.statOrder.map(statName => {
    const stat = guardian.stats[statName]
    if (!stat) return []

    const levelKeys = getGuardianLevelKeys(guardian, statName)
    const maxLevel = levelKeys.length > 0 ? Math.max(...levelKeys) : 0
    return Array.from({ length: maxLevel + 1 }, (_, level) => stat.levels[level]?.value ?? null)
  })
}

export function getGuardianCostValues(guardian: GuardianDefinition): (number | null)[][] {
  return guardian.statOrder.map(statName => {
    const stat = guardian.stats[statName]
    if (!stat) return []

    const levelKeys = getGuardianLevelKeys(guardian, statName)
    const maxLevel = levelKeys.length > 0 ? Math.max(...levelKeys) : 0
    return Array.from({ length: maxLevel + 1 }, (_, level) => stat.levels[level]?.cost ?? null)
  })
}

export function getGuardianBaseValues(guardian: GuardianDefinition): (string | number | null)[] {
  return guardian.statOrder.map(statName => guardian.stats[statName]?.base ?? null)
}

export function getGuardianStatBounds(guardian: GuardianDefinition, statIndex: number): { min: number; max: number } {
  const statName = guardian.statOrder[statIndex]
  if (!statName) return { min: 0, max: 0 }

  const stat = guardian.stats[statName]
  if (!stat) return { min: 0, max: 0 }

  const validLevels = Object.entries(stat.levels)
    .map(([level, entry]) => ({ level: Number(level), value: String(entry.value || '').trim() }))
    .filter(item => Number.isFinite(item.level) && item.value.length > 0)
    .map(item => item.level)

  if (validLevels.length === 0) return { min: 0, max: 0 }
  return { min: Math.min(...validLevels), max: Math.max(...validLevels) }
}

export function getGuardianStatValueAt(guardian: GuardianDefinition, statIndex: number, level: number): string | number | null {
  const statName = guardian.statOrder[statIndex]
  if (!statName) return null
  return guardian.stats[statName]?.levels[level]?.value ?? null
}

export function getGuardianStatCostAt(guardian: GuardianDefinition, statIndex: number, level: number): number | null {
  const statName = guardian.statOrder[statIndex]
  if (!statName) return null
  return guardian.stats[statName]?.levels[level]?.cost ?? null
}

const SPECIAL_STAT_COST_KEY_MAP: Record<string, Record<string, string>> = {
  attack: { percentage: 'attackCost' },
  ally: { recoveryAmount: 'recoveryCost' },
}

function formatGuardianStatName(name: string): string {
  return name.charAt(0).toUpperCase() + name.slice(1).replace(/([A-Z])/g, ' $1')
}

function formatGuardianLabel(key: string): string {
  return key.charAt(0).toUpperCase() + key.slice(1)
}

export function buildGuardianDefinitions(): GuardianDefinition[] {
  return Object.keys(guardianUpgrades).map(key => {
    const upgrades = guardianUpgrades[key as keyof typeof guardianUpgrades]
    const allKeys = Object.keys(upgrades[0])
    const statNames = allKeys.filter(name => name !== 'level' && !name.endsWith('Cost'))
    const specialMap = SPECIAL_STAT_COST_KEY_MAP[key] || {}
    const statToCostMap = Object.fromEntries(
      statNames.map(stat => [stat, specialMap[stat] || `${stat}Cost`]),
    )

    const { sourceMinLevel, normalizedMaxLevel } = getNormalizedGuardianLevelInfo(upgrades)
    const normalizedStatNames = statNames.map(formatGuardianStatName)
    const stats: Record<string, { base: string | number | null; levels: Record<number, { value: string | number | null; cost: number | null }> }> = {}

    statNames.forEach((rawStatName, index) => {
      const normalizedName = normalizedStatNames[index]
      const costKey = statToCostMap[rawStatName]
      const levels: Record<number, { value: string | number | null; cost: number | null }> = {}

      for (let level = 0; level <= normalizedMaxLevel; level += 1) {
        const sourceLevel = level + sourceMinLevel
        const upgrade = upgrades.find(item => item.level === sourceLevel)
        const value = upgrade ? (upgrade[rawStatName as keyof typeof upgrade] as string | number | null) : null
        const cost = upgrade ? (upgrade[costKey as keyof typeof upgrade] as number | null) : null
        levels[level] = { value, cost }
      }

      stats[normalizedName] = {
        base: levels[0]?.value ?? null,
        levels,
      }
    })

    return {
      key,
      label: formatGuardianLabel(key),
      statOrder: normalizedStatNames,
      stats,
    }
  })
}
