/**
 * Cards, their level values, and their mastery values.
 *
 * Level and mastery are separate ladders on the same card, and a card contributes nothing at all
 * unless it is equipped — owning it is not enough.
 */
/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    —
 * depends    src/data/cards/data
 * used by    —
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
export * from './data'
