/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    GoldenTowerIncomeComparisonRow, goldenTowerRelativeIncomeDescriptionLines, goldenTowerRelativeIncomeFooterLines, goldenTowerRelativeIncomeData, goldenTowerUptimeIncomeDescriptionLines, goldenTowerUptimeIncomeFooterLines, goldenTowerUptimeIncomeData, GoldenTowerMilestoneUnlockRow (+3 more)
 * depends    src/charts/chart-data, src/data/milestones
 * used by    src/charts/chart-data-lookup, src/charts/index
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
import type { SharedChartTableDataset } from './chart-data'
import { MILESTONE_REWARD_ROWS, type MilestoneRewardRow } from '../data/milestones'

export interface GoldenTowerIncomeComparisonRow {
  duration: number
  gtPlus1: string
  gtPlus2: string
  gtPlus3: string
  gtPlus4: string
  gtPlus5: string
  gtPlus6: string
  gtPlus7: string
  gtPlus8: string
  gtPlus9: string
  gtPlus10: string
}

function buildGoldenTowerIncomeRow(duration: number, values: readonly string[]): GoldenTowerIncomeComparisonRow {
  return {
    duration,
    gtPlus1: values[0] ?? '',
    gtPlus2: values[1] ?? '',
    gtPlus3: values[2] ?? '',
    gtPlus4: values[3] ?? '',
    gtPlus5: values[4] ?? '',
    gtPlus6: values[5] ?? '',
    gtPlus7: values[6] ?? '',
    gtPlus8: values[7] ?? '',
    gtPlus9: values[8] ?? '',
    gtPlus10: values[9] ?? '',
  }
}

const goldenTowerIncomeColumns = [
  { key: 'duration', label: 'Duration (s)' },
  { key: 'gtPlus1', label: 'GT+1' },
  { key: 'gtPlus2', label: 'GT+2' },
  { key: 'gtPlus3', label: 'GT+3' },
  { key: 'gtPlus4', label: 'GT+4' },
  { key: 'gtPlus5', label: 'GT+5' },
  { key: 'gtPlus6', label: 'GT+6' },
  { key: 'gtPlus7', label: 'GT+7' },
  { key: 'gtPlus8', label: 'GT+8' },
  { key: 'gtPlus9', label: 'GT+9' },
  { key: 'gtPlus10', label: 'GT+10' },
] as const

const goldenTowerRelativeIncomeRows: readonly GoldenTowerIncomeComparisonRow[] = [
  buildGoldenTowerIncomeRow(40, ['0.177', '0.192', '0.209', '0.227', '0.247', '0.269', '0.292', '0.318', '0.345', '0.376']),
  buildGoldenTowerIncomeRow(41, ['0.183', '0.199', '0.217', '0.237', '0.258', '0.281', '0.306', '0.334', '0.364', '0.397']),
  buildGoldenTowerIncomeRow(42, ['0.189', '0.206', '0.225', '0.246', '0.269', '0.294', '0.321', '0.351', '0.383', '0.419']),
  buildGoldenTowerIncomeRow(43, ['0.195', '0.213', '0.233', '0.256', '0.280', '0.307', '0.336', '0.368', '0.403', '0.441']),
  buildGoldenTowerIncomeRow(44, ['0.201', '0.220', '0.242', '0.266', '0.292', '0.320', '0.352', '0.386', '0.424', '0.465']),
  buildGoldenTowerIncomeRow(45, ['0.207', '0.228', '0.251', '0.276', '0.303', '0.334', '0.368', '0.404', '0.445', '0.490']),
  buildGoldenTowerIncomeRow(46, ['0.213', '0.235', '0.259', '0.286', '0.316', '0.348', '0.384', '0.424', '0.467', '0.515']),
  buildGoldenTowerIncomeRow(47, ['0.219', '0.242', '0.268', '0.297', '0.328', '0.363', '0.401', '0.443', '0.490', '0.542']),
  buildGoldenTowerIncomeRow(48, ['0.226', '0.250', '0.277', '0.307', '0.341', '0.378', '0.418', '0.464', '0.514', '0.570']),
  buildGoldenTowerIncomeRow(49, ['0.232', '0.258', '0.286', '0.318', '0.354', '0.393', '0.437', '0.485', '0.539', '0.599']),
  buildGoldenTowerIncomeRow(50, ['0.238', '0.265', '0.296', '0.329', '0.367', '0.409', '0.455', '0.507', '0.564', '0.629']),
  buildGoldenTowerIncomeRow(51, ['0.245', '0.273', '0.305', '0.341', '0.380', '0.425', '0.474', '0.529', '0.591', '0.660']),
  buildGoldenTowerIncomeRow(52, ['0.251', '0.281', '0.315', '0.352', '0.394', '0.441', '0.494', '0.553', '0.618', '0.692']),
  buildGoldenTowerIncomeRow(53, ['0.258', '0.289', '0.325', '0.364', '0.409', '0.458', '0.514', '0.577', '0.647', '0.726']),
  buildGoldenTowerIncomeRow(54, ['0.264', '0.297', '0.335', '0.376', '0.423', '0.476', '0.535', '0.602', '0.676', '0.761']),
  buildGoldenTowerIncomeRow(55, ['0.271', '0.306', '0.345', '0.389', '0.438', '0.494', '0.557', '0.627', '0.707', '0.797']),
  buildGoldenTowerIncomeRow(56, ['0.278', '0.314', '0.355', '0.401', '0.453', '0.512', '0.579', '0.654', '0.739', '0.834']),
  buildGoldenTowerIncomeRow(57, ['0.285', '0.323', '0.365', '0.414', '0.469', '0.531', '0.601', '0.681', '0.771', '0.874']),
  buildGoldenTowerIncomeRow(58, ['0.292', '0.331', '0.376', '0.427', '0.485', '0.550', '0.625', '0.709', '0.805', '0.914']),
  buildGoldenTowerIncomeRow(59, ['0.299', '0.340', '0.387', '0.440', '0.501', '0.570', '0.649', '0.739', '0.840', '0.956']),
  buildGoldenTowerIncomeRow(60, ['0.306', '0.349', '0.398', '0.454', '0.518', '0.591', '0.674', '0.769', '0.877', '1.000']),
  buildGoldenTowerIncomeRow(61, ['0.313', '0.358', '0.409', '0.468', '0.535', '0.612', '0.699', '0.800', '0.914', '1.045']),
  buildGoldenTowerIncomeRow(62, ['0.320', '0.367', '0.420', '0.482', '0.552', '0.633', '0.726', '0.832', '0.953', '1.092']),
  buildGoldenTowerIncomeRow(63, ['0.327', '0.376', '0.432', '0.496', '0.570', '0.655', '0.753', '0.865', '0.993', '1.141']),
  buildGoldenTowerIncomeRow(64, ['0.334', '0.385', '0.443', '0.511', '0.588', '0.678', '0.780', '0.899', '1.035', '1.192']),
  buildGoldenTowerIncomeRow(65, ['0.341', '0.394', '0.455', '0.526', '0.607', '0.701', '0.809', '0.934', '1.078', '1.245']),
  buildGoldenTowerIncomeRow(66, ['0.349', '0.404', '0.467', '0.541', '0.626', '0.724', '0.838', '0.970', '1.123', '1.299']),
  buildGoldenTowerIncomeRow(67, ['0.356', '0.413', '0.480', '0.556', '0.645', '0.749', '0.869', '1.008', '1.169', '1.356']),
  buildGoldenTowerIncomeRow(68, ['0.364', '0.423', '0.492', '0.572', '0.665', '0.774', '0.900', '1.046', '1.216', '1.414']),
  buildGoldenTowerIncomeRow(69, ['0.371', '0.433', '0.505', '0.588', '0.686', '0.799', '0.932', '1.086', '1.266', '1.475']),
  buildGoldenTowerIncomeRow(70, ['0.379', '0.443', '0.517', '0.605', '0.707', '0.826', '0.965', '1.127', '1.317', '1.538']),
  buildGoldenTowerIncomeRow(71, ['0.387', '0.453', '0.530', '0.621', '0.728', '0.852', '0.998', '1.169', '1.369', '1.604']),
  buildGoldenTowerIncomeRow(72, ['0.394', '0.463', '0.544', '0.638', '0.750', '0.880', '1.033', '1.213', '1.424', '1.671']),
  buildGoldenTowerIncomeRow(73, ['0.402', '0.473', '0.557', '0.656', '0.772', '0.908', '1.069', '1.258', '1.480', '1.742']),
  buildGoldenTowerIncomeRow(74, ['0.410', '0.484', '0.571', '0.673', '0.794', '0.937', '1.106', '1.304', '1.538', '1.814']),
  buildGoldenTowerIncomeRow(75, ['0.418', '0.494', '0.585', '0.691', '0.818', '0.967', '1.143', '1.352', '1.598', '1.890']),
  buildGoldenTowerIncomeRow(76, ['0.426', '0.505', '0.599', '0.710', '0.841', '0.997', '1.182', '1.401', '1.661', '1.968']),
  buildGoldenTowerIncomeRow(77, ['0.434', '0.516', '0.613', '0.728', '0.866', '1.028', '1.222', '1.452', '1.725', '2.049']),
  buildGoldenTowerIncomeRow(78, ['0.442', '0.527', '0.627', '0.747', '0.890', '1.060', '1.263', '1.504', '1.791', '2.133']),
  buildGoldenTowerIncomeRow(79, ['0.450', '0.538', '0.642', '0.767', '0.916', '1.093', '1.305', '1.558', '1.860', '2.220']),
  buildGoldenTowerIncomeRow(80, ['0.459', '0.549', '0.657', '0.787', '0.941', '1.127', '1.348', '1.613', '1.931', '2.310']),
] as const

const goldenTowerUptimeIncomeRows: readonly GoldenTowerIncomeComparisonRow[] = [
  buildGoldenTowerIncomeRow(60, ['0.306', '0.349', '0.398', '0.454', '0.518', '0.591', '0.674', '0.769', '0.877', '1.000']),
  buildGoldenTowerIncomeRow(61, ['0.307', '0.351', '0.402', '0.459', '0.525', '0.601', '0.687', '0.785', '0.898', '1.027']),
  buildGoldenTowerIncomeRow(62, ['0.308', '0.354', '0.405', '0.465', '0.533', '0.611', '0.700', '0.802', '0.920', '1.054']),
  buildGoldenTowerIncomeRow(63, ['0.310', '0.356', '0.409', '0.470', '0.541', '0.621', '0.714', '0.820', '0.942', '1.082']),
  buildGoldenTowerIncomeRow(64, ['0.311', '0.359', '0.413', '0.476', '0.548', '0.632', '0.727', '0.838', '0.965', '1.111']),
  buildGoldenTowerIncomeRow(65, ['0.313', '0.361', '0.417', '0.482', '0.556', '0.642', '0.742', '0.856', '0.988', '1.141']),
  buildGoldenTowerIncomeRow(66, ['0.314', '0.364', '0.421', '0.488', '0.564', '0.653', '0.756', '0.875', '1.012', '1.171']),
  buildGoldenTowerIncomeRow(67, ['0.316', '0.367', '0.425', '0.494', '0.573', '0.664', '0.771', '0.894', '1.037', '1.203']),
  buildGoldenTowerIncomeRow(68, ['0.317', '0.369', '0.429', '0.499', '0.581', '0.675', '0.785', '0.913', '1.062', '1.235']),
  buildGoldenTowerIncomeRow(69, ['0.319', '0.372', '0.434', '0.506', '0.589', '0.687', '0.801', '0.933', '1.088', '1.268']),
  buildGoldenTowerIncomeRow(70, ['0.321', '0.375', '0.438', '0.512', '0.598', '0.699', '0.816', '0.954', '1.114', '1.302']),
  buildGoldenTowerIncomeRow(71, ['0.322', '0.377', '0.442', '0.518', '0.606', '0.710', '0.832', '0.974', '1.141', '1.336']),
  buildGoldenTowerIncomeRow(72, ['0.324', '0.380', '0.446', '0.524', '0.615', '0.722', '0.848', '0.996', '1.169', '1.372']),
  buildGoldenTowerIncomeRow(73, ['0.325', '0.383', '0.451', '0.530', '0.624', '0.735', '0.865', '1.017', '1.197', '1.409']),
  buildGoldenTowerIncomeRow(74, ['0.327', '0.386', '0.455', '0.537', '0.633', '0.747', '0.881', '1.040', '1.226', '1.446']),
  buildGoldenTowerIncomeRow(75, ['0.328', '0.388', '0.459', '0.543', '0.642', '0.760', '0.898', '1.062', '1.256', '1.485']),
  buildGoldenTowerIncomeRow(76, ['0.330', '0.391', '0.464', '0.550', '0.652', '0.773', '0.916', '1.085', '1.286', '1.525']),
  buildGoldenTowerIncomeRow(77, ['0.332', '0.394', '0.468', '0.556', '0.661', '0.786', '0.933', '1.109', '1.318', '1.565']),
  buildGoldenTowerIncomeRow(78, ['0.333', '0.397', '0.473', '0.563', '0.671', '0.799', '0.952', '1.133', '1.350', '1.607']),
  buildGoldenTowerIncomeRow(79, ['0.335', '0.400', '0.477', '0.570', '0.680', '0.812', '0.970', '1.158', '1.382', '1.650']),
  buildGoldenTowerIncomeRow(80, ['0.336', '0.403', '0.482', '0.577', '0.690', '0.826', '0.989', '1.183', '1.416', '1.694']),
] as const

export const goldenTowerRelativeIncomeDescriptionLines = [
  'Relative income when comparing Golden Combo levels and Golden Tower duration.',
  'Assumes 5 seconds of early-wave mobs are not included in the Golden Combo bonus and uses Kps = 8.',
] as const

export const goldenTowerRelativeIncomeFooterLines = [
  'Values are relative to GT+10 at 60 seconds.',
  'At 40 seconds duration, GT+10 is 213% better than GT+1. At 80 seconds, it is 504% better.',
  'At GT+10, 80 seconds duration is 231% better than 60 seconds.',
] as const

export const goldenTowerRelativeIncomeData: SharedChartTableDataset<GoldenTowerIncomeComparisonRow> = {
  title: 'Golden Combo Relative Income',
  columns: goldenTowerIncomeColumns,
  rows: goldenTowerRelativeIncomeRows,
}

export const goldenTowerUptimeIncomeDescriptionLines = [
  'Relative income when Golden Tower already has 100% uptime, such as MVN or Galaxy Compressor-assisted always-on windows.',
  'Assumes 5 seconds of early-wave mobs are not included in the Golden Combo bonus and uses Kps = 8.',
] as const

export const goldenTowerUptimeIncomeFooterLines = [
  'Values are relative to GT+10 at 60 seconds.',
  'Do not compare this table directly against the non-uptime table because the premises are different.',
  'GT+ level scaling remains the same, but extra duration loses some efficacy once uptime is already permanent.',
] as const

export const goldenTowerUptimeIncomeData: SharedChartTableDataset<GoldenTowerIncomeComparisonRow> = {
  title: 'Golden Combo Relative Income (100% GT Uptime)',
  columns: goldenTowerIncomeColumns,
  rows: goldenTowerUptimeIncomeRows,
}

export interface GoldenTowerMilestoneUnlockRow {
  tier: string
  track: string
  wave: number
  reward: string
  kind: string
}

function toGoldenTowerMilestoneUnlockRow(row: MilestoneRewardRow): GoldenTowerMilestoneUnlockRow {
  return {
    tier: `Tier ${row.tier}`,
    track: row.track === 'standard' ? 'Standard' : 'Premium',
    wave: row.wave,
    reward: row.reward,
    kind: row.kind,
  }
}

const goldenTowerMilestoneUnlockRows = MILESTONE_REWARD_ROWS
  .filter(row => row.reward === 'Golden Tower Bonus' || row.reward === 'Golden Tower Duration')
  .map(toGoldenTowerMilestoneUnlockRow)

export const goldenTowerMilestoneUnlockData: SharedChartTableDataset<GoldenTowerMilestoneUnlockRow> = {
  title: 'Golden Tower Lab Unlock Milestones',
  columns: [
    { key: 'tier', label: 'Tier' },
    { key: 'track', label: 'Track' },
    { key: 'wave', label: 'Wave' },
    { key: 'reward', label: 'Unlock' },
    { key: 'kind', label: 'Kind' },
  ],
  rows: goldenTowerMilestoneUnlockRows,
}

export const goldenTowerMilestoneUnlockDescriptionLines = [
  'Golden Tower lab support unlocks through milestone progression rather than the Ultimate Weapon stone menu itself.',
  'Both Golden Tower Bonus and Golden Tower Duration unlock at Tier 4 Wave 200 on the standard milestone track.',
] as const

export const goldenTowerMilestoneUnlockFooterLines = [
  'These milestone unlocks gate the lab rows that raise Golden Tower base bonus and duration outside stone upgrades.',
] as const
