/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    GoldBotDeathWaveRow, computeGoldBotDeathWaveRows
 * depends    —
 * used by    src/charts/chart-data-lookup, src/charts/index, src/mechanics/calculators/specs-generated
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
const DW_OFFSETS = [2, 3, 4, 5, 6, 7, 8] as const

export interface GoldBotDeathWaveRow {
  gbCooldownSec: number
  deathWaveOffsetSec: number
  syncPercent: number
}

export function computeGoldBotDeathWaveRows(): GoldBotDeathWaveRow[] {
  const rows: GoldBotDeathWaveRow[] = []

  for (let gbCooldownSec = 38; gbCooldownSec <= 65; gbCooldownSec += 1) {
    for (const deathWaveOffsetSec of DW_OFFSETS) {
      const syncPercent = computeSyncPercent(gbCooldownSec, deathWaveOffsetSec)
      rows.push({ gbCooldownSec, deathWaveOffsetSec, syncPercent })
    }
  }

  return rows
}

function computeSyncPercent(gbCooldownSec: number, deathWaveOffsetSec: number): number {
  const cycleWindowSec = 600
  const gbTriggers = buildTriggerTimes(gbCooldownSec, cycleWindowSec)
  const dwTriggers = buildTriggerTimes(120 + deathWaveOffsetSec, cycleWindowSec)

  let synced = 0
  for (const gbTrigger of gbTriggers) {
    if (dwTriggers.some(dwTrigger => Math.abs(dwTrigger - gbTrigger) <= 1)) {
      synced += 1
    }
  }

  if (gbTriggers.length === 0) {
    return 0
  }

  return Math.round((synced / gbTriggers.length) * 100)
}

function buildTriggerTimes(intervalSec: number, horizonSec: number): number[] {
  const values: number[] = []
  for (let t = intervalSec; t <= horizonSec; t += intervalSec) {
    values.push(t)
  }
  return values
}
