/**
 * The column-and-row machinery every chart renders through.
 *
 * A chart is a table before it is a picture: named columns, typed cells, and a lookup that answers
 * what a given row holds. Keeping that separate from the datasets means a new chart supplies rows
 * and inherits everything about how they are described.
 */
/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    —
 * depends    src/charts/tables/data, src/charts/tables/lookup
 * used by    —
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
export * from './data'
export * from './lookup'
