/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    getSharedToolInputs, compactSharedToolInputsForStorage, mergeSparseSharedToolInputs, compactRecordIfNonEmpty
 * depends    src/internal/shared-tool-inputs/extended, src/internal/shared-tool-inputs/hub-merge, src/internal/shared-tool-inputs/shared-tool-inputs, src/internal/uptime/shared-inputs
 * used by    src/internal/shared-tool-inputs/shared-tool-inputs, src/mechanics/calculators/specs-generated
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
import {
  defaultExtendedSharedToolInputs,
  defaultSharedEnemyStatsCore,
  normalizeExtendedSharedToolInputs,
} from './extended'
import {
  defaultSharedToolInputs,
  normalizeSharedToolInputs,
  type SharedToolInputs,
} from './shared-tool-inputs'
import { pickNonDefaultRecordFields } from './hub-merge'
import { readSharedUptimeInputs } from '../uptime/shared-inputs'

/**
 * Expand sparse persisted hub state into a fully resolved payload for UI and simulation.
 * Missing keys receive site defaults only at read time.
 */
export function getSharedToolInputs(stored: Record<string, unknown>): SharedToolInputs {
  const { enemyStatsCore: _ec, perkPreferences: _pp, uptimeInputs: _ui, ...restDefaults } = defaultSharedToolInputs
  const { enemyStatsCore: _ecExt, ...extendedRest } = normalizeExtendedSharedToolInputs({
    ...defaultExtendedSharedToolInputs,
    ...stored,
  })
  return normalizeSharedToolInputs({
    ...restDefaults,
    ...stored,
    perkPreferences: {
      ...defaultSharedToolInputs.perkPreferences,
      ...(isPlainObject(stored.perkPreferences) ? stored.perkPreferences : {}),
    },
    uptimeInputs: readSharedUptimeInputs(
      isPlainObject(stored.uptimeInputs) ? stored.uptimeInputs : {},
    ),
    ...extendedRest,
    enemyStatsCore: {
      ...defaultSharedEnemyStatsCore,
      ...(isPlainObject(stored.enemyStatsCore) ? stored.enemyStatsCore : {}),
    },
  })
}

function isPlainObject(value: unknown): value is Record<string, unknown> {
  return Boolean(value) && typeof value === 'object' && !Array.isArray(value)
}

function compactRecordIfNonEmpty(record: Record<string, number> | undefined): Record<string, number> | undefined {
  if (!record || !Object.keys(record).length) return undefined
  return record
}

/**
 * Strip site-default fields before persistence so unset hub keys stay absent (null semantics).
 */
export function compactSharedToolInputsForStorage(resolved: SharedToolInputs): Record<string, unknown> {
  const normalized = normalizeSharedToolInputs(resolved)
  const out: Record<string, unknown> = {}

  const enemyStatsCore = pickNonDefaultRecordFields(
    normalized.enemyStatsCore as unknown as Record<string, unknown>,
    defaultSharedEnemyStatsCore as unknown as Record<string, unknown>,
  )
  if (Object.keys(enemyStatsCore).length) out.enemyStatsCore = enemyStatsCore

  const uptimeResolved = readSharedUptimeInputs({})
  const uptimeStored = pickNonDefaultRecordFields(
    normalized.uptimeInputs as unknown as Record<string, unknown>,
    uptimeResolved as unknown as Record<string, unknown>,
  )
  if (Object.keys(uptimeStored).length) out.uptimeInputs = uptimeStored

  const recordGroups = [
    'researchLabLevels',
    'enemyStatLabLevels',
    'bcCounterLabLevels',
    'botLevels',
    'botTargets',
    'botPlusLevels',
    'botPlusTargets',
    'botLabLevels',
    'guardianLevels',
    'guardianTargets',
    'uwProgressLevels',
    'labsCalcByLab',
    'uwCalcProgress',
  ] as const

  for (const key of recordGroups) {
    const value = normalized[key]
    if (value && typeof value === 'object' && Object.keys(value as object).length) {
      out[key] = value
    }
  }

  if (normalized.towerRange) out.towerRange = normalized.towerRange

  const economy = pickNonDefaultRecordFields(
    normalized.labsEconomy as unknown as Record<string, unknown>,
    defaultSharedToolInputs.labsEconomy as unknown as Record<string, unknown>,
  )
  if (Object.keys(economy).length) out.labsEconomy = economy

  const enemyDrops = pickNonDefaultRecordFields(
    normalized.enemyDropsInputs as unknown as Record<string, unknown>,
    defaultExtendedSharedToolInputs.enemyDropsInputs as unknown as Record<string, unknown>,
  )
  if (Object.keys(enemyDrops).length) out.enemyDropsInputs = enemyDrops

  const cardsProgress = pickNonDefaultRecordFields(
    normalized.cardsProgressInputs as unknown as Record<string, unknown>,
    defaultExtendedSharedToolInputs.cardsProgressInputs as unknown as Record<string, unknown>,
  )
  if (Object.keys(cardsProgress).length) out.cardsProgressInputs = cardsProgress

  const workshopStatLevels = normalized.workshopStatLevels
  const hasWorkshopLevels = Object.values(workshopStatLevels).some(record => Object.keys(record).length)
  if (hasWorkshopLevels) out.workshopStatLevels = workshopStatLevels

  const tradeOffPerks = pickNonDefaultRecordFields(
    normalized.tradeOffPerks as unknown as Record<string, unknown>,
    defaultSharedToolInputs.tradeOffPerks as unknown as Record<string, unknown>,
  )
  if (Object.keys(tradeOffPerks).length) out.tradeOffPerks = tradeOffPerks

  const workshopDiscounts = pickNonDefaultRecordFields(
    normalized.workshopDiscounts as unknown as Record<string, unknown>,
    defaultSharedToolInputs.workshopDiscounts as unknown as Record<string, unknown>,
  )
  if (Object.keys(workshopDiscounts).length) out.workshopDiscounts = workshopDiscounts

  const moduleDiscounts = pickNonDefaultRecordFields(
    normalized.moduleDiscounts as unknown as Record<string, unknown>,
    defaultSharedToolInputs.moduleDiscounts as unknown as Record<string, unknown>,
  )
  if (Object.keys(moduleDiscounts).length) out.moduleDiscounts = moduleDiscounts

  const moduleEfficiencyLabs = normalized.moduleEfficiencyLabs
  const moduleEfficiencyStored = {
    ...pickNonDefaultRecordFields(
      moduleEfficiencyLabs as unknown as Record<string, unknown>,
      defaultSharedToolInputs.moduleEfficiencyLabs as unknown as Record<string, unknown>,
    ),
  }
  if (Object.keys(moduleEfficiencyStored).length) out.moduleEfficiencyLabs = moduleEfficiencyStored

  const namedCalculatorLabs = normalized.namedCalculatorLabs
  if (Object.keys(namedCalculatorLabs.echoLabLevels).length
    || Object.entries(namedCalculatorLabs).some(([key, value]) => key !== 'echoLabLevels' && value)) {
    out.namedCalculatorLabs = namedCalculatorLabs
  }

  const perkPreferences = normalized.perkPreferences
  const hasPerkPreferenceData = perkPreferences && (
    perkPreferences.bannedIndices?.length
    || perkPreferences.unbannedIndices?.length
    || perkPreferences.bannedPerkNames?.length
    || perkPreferences.unbannedPerkNames?.length
    || perkPreferences.autoPickPerk
    || perkPreferences.autoPickOrder?.length
    || perkPreferences.firstPerkIndex != null
    || perkPreferences.firstTradeOffPerkIndex != null
  )
  if (hasPerkPreferenceData) {
    out.perkPreferences = perkPreferences
  }

  const extendedGroups = [
    'elsPlannerInputs',
    'vaultLevels',
    'moduleProgressInputs',
    'shardSplitterInputs',
    'thornsCalculatorSettings',
    'damageReduxCalculatorSettings',
    'dissonanceCalculatorState',
    'botMedalSplitterPlanner',
    'botsSynchronicity',
  ] as const

  for (const key of extendedGroups) {
    const value = normalized[key]
    const defaultValue = defaultExtendedSharedToolInputs[key]
    if (!value || typeof value !== 'object') continue
    const compact = pickNonDefaultRecordFields(
      value as unknown as Record<string, unknown>,
      defaultValue as unknown as Record<string, unknown>,
    )
    if (Object.keys(compact).length) out[key] = compact
  }

  return out
}

export function mergeSparseSharedToolInputs(
  stored: Record<string, unknown>,
  patch: Record<string, unknown>,
): Record<string, unknown> {
  const out: Record<string, unknown> = { ...stored }

  for (const [key, value] of Object.entries(patch)) {
    if (value === undefined) continue
    if (isPlainObject(value) && isPlainObject(out[key])) {
      out[key] = { ...out[key], ...value }
      continue
    }
    out[key] = value
  }

  return out
}

export { compactRecordIfNonEmpty }
