/**
 * Card masteries, as the game defines them.
 *
 * Read from the wiki's Card Masteries page on 2026-08-16.
 *
 * ## How this was found
 *
 * Not by reading a wiki index — by mining the game's own localisation terms
 * for vocabulary the oracle had no entry for. Twenty-nine `* Mastery` terms
 * came back against zero coverage. An entire system, invisible because nobody
 * had thought to ask about it.
 *
 * That is worth noting as method: **the gap you can name is not the dangerous
 * one.** Diffing our vocabulary against the game's found a system; reading more
 * carefully would not have.
 *
 * ## Why masteries matter for tool-building
 *
 * A mastery is not "a bigger card". Roughly half change the card's own
 * multiplier, and the rest add a *completely different effect* — Cash mastery
 * drops reroll dice, Fortress mastery cuts wall rebuild time, Free Upgrades
 * mastery locks a stat out of free upgrades. A model that treats mastery as a
 * scalar on the card's existing stat is wrong for about half the deck.
 */
/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    MASTERY_TERM_NAMES_THE_CARD, MASTERY_TERM_NAMES_THE_MASTERY, MASTERY_VOCABULARY_NOT_COVERED, MASTERY_TERMS_WITH_TRAILING_PUNCTUATION, CARD_CATALOG_SIZE, CARD_MASTERY_REQUIRED_MAXED_CARDS, CARD_MASTERY_MILESTONE_TIER, CARD_MASTERY_MILESTONE_WAVE (+13 more)
 * depends    src/data/cards, src/knowledge/substrate/schema
 * used by    src/knowledge/compartments/index, src/knowledge/index
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
import { CARD_TEMPLATES } from '../../data/cards'
import type { KnowledgeEdge, KnowledgeNode } from '../substrate/schema'

const WIKI_MASTERIES = {
  origin: 'wiki',
  ref: 'Card Masteries',
  verifiedAt: '2026-08-16',
} as const

/**
 * The game's own localisation terms — the vocabulary that found this system.
 *
 * The compartment header says masteries were discovered by mining `* Mastery`
 * terms out of the game's string table. Going back to that table to CHECK the
 * compartment, rather than only to find it, is what the claims below rest on.
 */
/** The shipped card catalog, cited where it is the thing being contradicted. */
const CATALOG_CARDS = {
  origin: 'code',
  ref: 'thetowersdk/data CARD_TEMPLATES',
  verifiedAt: '2026-08-18',
} as const

const GAME_LOCALISATION = {
  origin: 'game',
  ref: 'I2 localisation terms, v28.3.0 (discovered-i2-localization.json)',
  sourceVersion: 'v28.3.0',
  verifiedAt: '2026-08-18',
} as const

/**
 * How a mastery is named, which is the thing that made this hard to read.
 *
 * Every card has exactly one mastery, and that mastery has its OWN name — the
 * Berserker card's mastery is Viking Funeral, Extra Orb's is Coin Orb. Levelling
 * it is done with labs, but the labs do not name it; the name belongs to the
 * card's mastery. Players commonly say "Berserker Mastery", meaning "the
 * Berserker card's mastery", and that is a fair way to say it.
 *
 * The game's string table does BOTH. Most `* Mastery` terms are the card's name
 * — `Berserker Mastery`, `Nuke Mastery`. At least one is the mastery's own name:
 * "You need the Coin Orb Mastery to research this", where Coin Orb is Extra
 * Orb's mastery, not a card.
 *
 * So a scan for `* Mastery` returns two different name spaces mixed together,
 * and resolving every hit as a card name is wrong for at least one of them. That
 * is the trap, and it is the one I fell into: I read `Coin Orb Mastery` as an
 * uncovered mastery when it is the covered mastery of a covered card.
 */
export const MASTERY_TERM_NAMES_THE_CARD = 30
export const MASTERY_TERM_NAMES_THE_MASTERY = 1

/**
 * Mastery vocabulary in the game that resolves to nothing here.
 *
 * Checked against BOTH name spaces — every card name and every mastery name in
 * `CARD_TEMPLATES` — rather than against card names alone.
 *
 * `Bastion` appears in the localisation as a card-shaped cluster: `Bastion`,
 * `Bastion Mastery`, `Bastion Refresh`, `Recharge Bastion`. `Coin Ray` appears
 * exactly once, inside "You need the Coin Ray Mastery to research this", and
 * matches no card and no mastery. Neither is in this repo in any form.
 *
 * What they ARE stays unverified. `Bastion Mastery` is evidence of a card called
 * Bastion, and `Coin Ray` sits next to `Coin Orb` — Extra Orb's mastery — which
 * hints at a mastery for a ray card. Both are inferences from a handful of
 * strings, so neither is written down as a fact and neither should be added to a
 * catalog on this basis.
 */
export const MASTERY_VOCABULARY_NOT_COVERED = ['Bastion', 'Coin Ray'] as const

/** Localisation artefacts that break exact-match lookup on a mastery term. */
export const MASTERY_TERMS_WITH_TRAILING_PUNCTUATION = [
  'Attack Speed Mastery!',
  'Health Regen Mastery&',
  'Wave Accelerator Mastery&',
] as const

/** Cards in the shipped catalog. */
export const CARD_CATALOG_SIZE = CARD_TEMPLATES.length

/** Masteries unlock only once this many cards are maxed. */
export const CARD_MASTERY_REQUIRED_MAXED_CARDS = 30

/**
 * And only after this milestone.
 *
 * Kept as two numbers, not as the string `'Tier 16 Wave 100'` it used to be.
 * `progression.ts` asserted the same fact as `'T16 W100'`, and the two
 * renderings read as a contradiction to a detector that compares values. The
 * display string stays available for prose; the ASSERTION uses the numbers.
 */
export const CARD_MASTERY_MILESTONE_TIER = 16
export const CARD_MASTERY_MILESTONE_WAVE = 100
export const CARD_MASTERY_MILESTONE = `Tier ${CARD_MASTERY_MILESTONE_TIER} Wave ${CARD_MASTERY_MILESTONE_WAVE}`

/** Mastery levels run 0–9; level 0 is the unlock itself and already gives a bonus. */
export const CARD_MASTERY_MIN_LEVEL = 0
export const CARD_MASTERY_MAX_LEVEL = 9

/**
 * Stone cost to unlock each mastery. Varies per card; not a flat rate.
 *
 * The lab cost/time ladder above level 0 is identical for every mastery, but
 * the unlock is not.
 */
export const CARD_MASTERY_STONE_COST: Readonly<Record<string, number>> = {
  'Damage': 750,
  'Attack Speed': 750,
  'Health': 750,
  'Health Regen': 750,
  'Range': 750,
  'Cash': 500,
  'Coins': 1250,
  'Slow Aura': 1000,
  'Critical Chance': 750,
  'Enemy Balance': 1000,
  'Extra Defense': 1000,
  'Fortress': 750,
  'Free Upgrades': 500,
  'Extra Orb': 750,
  'Plasma Cannon': 1250,
  'Critical Coin': 1000,
  'Wave Skip': 1000,
  'Intro Sprint': 1250,
  'Land Mine Stun': 1000,
  'Package Chance': 1000,
  'Death Ray': 750,
  'Energy Net': 750,
  'Super Tower': 1000,
  'Second Wind': 1000,
  'Demon Mode': 1000,
  'Energy Shield': 1000,
  'Wave Accelerator': 1000,
  'Berserker': 750,
  'Ultimate Crit': 750,
  'Nuke': 750,
  'Area of Effect': 1000,
}

/**
 * Masteries that amplify the card's existing stat.
 *
 * Everything NOT in this set does something else entirely.
 */
export const MASTERIES_THAT_SCALE_THE_CARD = [
  'Damage', 'Attack Speed', 'Health', 'Health Regen', 'Coins', 'Extra Defense',
] as const

/** Real-time cost of the mastery lab ladder, identical for every mastery. */
export const CARD_MASTERY_LAB_DAYS_BY_LEVEL: Readonly<Record<number, number>> = {
  1: 20.83, 2: 31.25, 3: 41.67, 4: 52.08, 5: 62.5,
  6: 72.92, 7: 83.33, 8: 93.75, 9: 104.17,
}

/**
 * Cards the mastery tables and the card catalog name differently.
 *
 * Keys are the mastery/wiki spelling; values are `CARD_TEMPLATES[].name`.
 * Joining the two tables on the name silently loses these — the join succeeds
 * for the rest and returns nothing here, which reads as "that card has no
 * mastery" rather than as a naming difference.
 *
 * One entry, not two, since 2026-08-18. `Berserker -> Berzerker` was never a
 * naming difference: it was a typo in `CARD_TEMPLATES`, which the game's string
 * table settles — it contains no z-spelling anywhere. The catalog is fixed, so
 * the alias is gone. What remains is a genuine length difference: the mastery
 * tables and the game both write `Recovery Package`, the catalog writes
 * `Recovery Package Chance`.
 *
 * Verified against the wiki's Card Mastery Overview table on 2026-08-17, where
 * all 31 stone costs and all 9 lab timings matched the tables here exactly.
 */
export const CARD_MASTERY_NAME_TO_CARD: Readonly<Record<string, string>> = {
  'Package Chance': 'Recovery Package Chance',
}

/** Stones to unlock every mastery — not to level any of them. */
export const CARD_MASTERY_TOTAL_STONE_COST = 27_500

/** Real-time days to take ONE mastery from level 1 to 9, labs running back to back. */
export const CARD_MASTERY_LAB_DAYS_TO_MAX = 562.5

/**
 * What each mastery actually does, and the shorthand a player types.
 *
 * The effect matters more than the number: only six scale the card's own stat,
 * and the rest do something unrelated. A player saying `PC#` means Plasma
 * Cannon Mastery — elites taking a share of plasma cannon damage — not "a
 * bigger Plasma Cannon card".
 */
export const CARD_MASTERY_EFFECTS: Readonly<Record<string, { short: string, effect: string }>> = {
  'Damage': { short: 'dmg#', effect: 'raises the card\'s own damage multiplier' },
  'Attack Speed': { short: 'as#', effect: 'raises the card\'s own attack speed multiplier' },
  'Health': { short: 'hp#', effect: 'raises the card\'s own health multiplier' },
  'Health Regen': { short: 'hr#', effect: 'raises the card\'s own regen multiplier' },
  'Range': { short: 'rng#', effect: 'adds a damage-per-meter bonus multiplier' },
  'Cash': { short: 'cash#', effect: 'gives elites a chance to drop reroll dice' },
  'Coins': { short: 'coin#', effect: 'raises the card\'s own coin multiplier' },
  'Slow Aura': { short: 'sa#', effect: 'reduces enemy ATTACK speed — not movement speed' },
  'Critical Chance': {
    short: 'cc#',
    effect: 'adds to crit chance, super crit chance AND super crit factor — three stats at once',
  },
  'Enemy Balance': { short: 'eb#', effect: 'gives a chance of double elite spawns' },
  'Extra Defense': { short: 'ed#', effect: 'raises the card\'s own defense percent' },
  'Fortress': { short: 'fort#', effect: 'reduces wall rebuild time, up to −100s' },
  'Free Upgrades': { short: 'fu#', effect: 'locks stats out of free upgrades, 1 to 10 of them' },
  'Extra Orb': { short: 'eo#', effect: 'adds an orb coin bonus' },
  'Plasma Cannon': { short: 'pc#', effect: 'applies a share of plasma cannon damage to elites' },
  'Critical Coin': { short: 'ccoin#', effect: 'chance to drop two coins instead of one' },
  'Wave Skip': { short: 'ws#', effect: 'chance to skip two waves instead of one' },
  'Intro Sprint': { short: 'is#', effect: 'multiplies how many waves Intro Sprint stays active' },
  'Land Mine Stun': { short: 'lms#', effect: 'chance that stunned enemies miss their attacks' },
  'Package Chance': { short: 'rpc#', effect: 'packages gain a chance to drop common modules' },
  'Death Ray': { short: 'dr#', effect: 'death ray partially pierces protector shields' },
  'Energy Net': {
    short: 'en#',
    effect: 'damage multiplier against bosses while trapped and for 10s after',
  },
  'Super Tower': {
    short: 'st#',
    effect: 'applies 35% of the Super Tower bonus to ultimate weapons and cuts their cooldown — '
      + 'overriding the base card\'s exclusion from UW damage',
  },
  'Second Wind': { short: 'sw#', effect: 'raises HP regen for 400 waves once triggered' },
  'Demon Mode': { short: 'dm#', effect: 'a lingering damage multiplier for 300 waves' },
  'Energy Shield': {
    short: 'es#',
    effect: 'the shield blast repels enemies, destroys enemy projectiles and resets Ray charge',
  },
  'Wave Accelerator': { short: 'wa#', effect: 'increases spawn rate acceleration' },
  'Berserker': {
    short: 'bz#',
    effect: 'raises the Berserker damage cap to ×500 for a window after Death Defy triggers',
  },
  'Ultimate Crit': { short: 'uc#', effect: 'raises ultimate weapon crit chance' },
  'Nuke': { short: 'nuke#', effect: 'reduces enemy attack speed for 300 waves after a Nuke' },
  'Area of Effect': { short: 'aoe#', effect: 'increases area-of-effect radius' },
}

/**
 * A node per mastery, generated from the table.
 *
 * Generated for the same reason as the UW+ abilities: a single generic
 * `cardMastery` node meant every specific mastery a player named — `PC#`,
 * `LMS#`, `AOE#` — resolved to the generic parent or to something unrelated.
 * The agent knew the system existed and nothing about any member of it.
 */
function buildMasteryNodes(): KnowledgeNode[] {
  return Object.entries(CARD_MASTERY_EFFECTS).map(([card, spec]) => {
    const scalesCard = (MASTERIES_THAT_SCALE_THE_CARD as readonly string[]).includes(card)
    // Resolve the mastery's card name against the shipped catalog, through the
    // alias table where the two spell it differently.
    const catalogName = CARD_MASTERY_NAME_TO_CARD[card] ?? card
    const catalogCardName = CARD_TEMPLATES.find(template => template.name === catalogName)?.name ?? null
    return {
      id: `cardMastery.${card.replace(/\s+/g, '')}`,
      label: `${card} Mastery (${spec.short})`,
      kind: 'entity' as const,
      claimType: 'objective' as const,
      verification: 'verified_here' as const,
      summary:
        `The mastery on the ${card} card. It ${spec.effect}. Levels 0-9; level 0 comes with the `
        + `${CARD_MASTERY_STONE_COST[card] ?? '?'}-stone unlock and already grants a bonus.`,
      disambiguation: scalesCard
        ? `Raises the ${card} card's own multiplier — one of only six masteries that do. Still `
          + 'requires the card to be EQUIPPED, and the card must be maxed before masteries unlock '
          + 'at all.'
        : `Does NOT simply make the ${card} card bigger. It ${spec.effect} — an effect the base `
          + 'card does not have. Treating it as a scalar on the card\'s existing stat models the '
          + 'wrong thing entirely.',
      units: 'level 0-9',
      traps: [
        `The ${card} card must be EQUIPPED for this mastery to do anything.`,
        'Level 0 already grants a bonus — treating 0 as "no effect" understates it by a full step.',
      ],
      assertions: [
        {
          subject: `cardMastery.${card.replace(/\s+/g, '')}`,
          predicate: 'stoneCost',
          value: CARD_MASTERY_STONE_COST[card] ?? -1,
          provenance: WIKI_MASTERIES,
        },
        {
          subject: `cardMastery.${card.replace(/\s+/g, '')}`,
          predicate: 'scalesOwnCardStat',
          value: scalesCard,
          provenance: WIKI_MASTERIES,
        },
        {
          subject: `cardMastery.${card.replace(/\s+/g, '')}`,
          predicate: 'maxLevel',
          value: CARD_MASTERY_MAX_LEVEL,
          provenance: WIKI_MASTERIES,
        },
        {
          subject: `cardMastery.${card.replace(/\s+/g, '')}`,
          predicate: 'shorthand',
          value: spec.short,
          provenance: WIKI_MASTERIES,
        },
        // The one that can fail. Every other assertion here restates a table
        // that lives ten lines away; this one joins the mastery to the shipped
        // card catalog and is false the moment a card is renamed or dropped.
        // That join has silently broken twice — `Berserker` against a
        // `Berzerker` typo in CARD_TEMPLATES, and `Package Chance` against
        // `Recovery Package Chance` — and both times it read as "that card has
        // no mastery" rather than as a mismatch.
        {
          subject: `cardMastery.${card.replace(/\s+/g, '')}`,
          predicate: 'resolvesToCatalogCard',
          value: catalogCardName != null,
          provenance: CATALOG_CARDS,
          verification: 'verified_here' as const,
        },
      ],
      sources: [WIKI_MASTERIES, CATALOG_CARDS],
    }
  })
}

const MASTERY_NODES = buildMasteryNodes()

/** Card names this compartment prices a mastery for. */
export const MASTERY_PRICED_CARD_COUNT = Object.keys(CARD_MASTERY_STONE_COST).length

export const MASTERY_KNOWLEDGE_NODES: readonly KnowledgeNode[] = [
  {
    id: 'cardMastery.vocabulary',
    label: 'Mastery names, against the game string table',
    kind: 'rule',
    claimType: 'objective',
    verification: 'verified_here',
    summary:
      'Every card has one mastery and that mastery has its own name. The game refers to a mastery '
      + 'sometimes by the card and sometimes by the mastery, so a scan of `* Mastery` terms '
      + 'returns two name spaces mixed together.',
    units: 'localisation terms',
    disambiguation:
      'A card name, a mastery name, and a lab are three things. `Berserker` is a card, '
      + '`Viking Funeral` is its mastery, and the lab that raises that mastery is what people '
      + 'shorten to "Berserker Mastery". The lab does not name the mastery.',
    traps: [
      'RESOLVE A `* MASTERY` TERM AGAINST BOTH NAME SPACES. Most of them are the CARD\'s name — '
      + 'Berserker Mastery, Nuke Mastery. At least one is the MASTERY\'s own name: "You need the '
      + 'Coin Orb Mastery to research this", and Coin Orb is Extra Orb\'s mastery, not a card. '
      + 'Checking card names alone reports a covered mastery as missing, which is exactly the '
      + 'mistake this trap was written after making.',
      `\`${MASTERY_VOCABULARY_NOT_COVERED.join('` AND `')}\` RESOLVE TO NOTHING HERE, against `
      + 'either name space. Bastion comes with a card-shaped cluster of strings; Coin Ray appears '
      + 'once, in a research-requirement sentence. What they are is UNVERIFIED — a handful of '
      + 'strings is evidence, not a definition. Do not add either to a catalog on this basis.',
      'THREE MASTERY TERMS CARRY TRAILING PUNCTUATION in the string table — '
      + `${MASTERY_TERMS_WITH_TRAILING_PUNCTUATION.join(', ')}. Exact-match lookup on a clean name `
      + 'misses them, and a miss must not be read as absence.',
      'The mastery tables here are keyed by CARD name, not by mastery name, so they join to '
      + '`CARD_TEMPLATES` directly — except where the two write the card differently, which is '
      + 'what `CARD_MASTERY_NAME_TO_CARD` is for.',
    ],
    implementedBy: [
      'MASTERY_VOCABULARY_NOT_COVERED',
      'MASTERY_TERMS_WITH_TRAILING_PUNCTUATION',
      'CARD_MASTERY_NAME_TO_CARD',
    ],
    assertions: [
      {
        subject: 'cardMastery.vocabulary',
        predicate: 'masteryTermsNamingTheCard',
        value: MASTERY_TERM_NAMES_THE_CARD,
        provenance: GAME_LOCALISATION,
        verification: 'verified_here',
      },
      {
        subject: 'cardMastery.vocabulary',
        predicate: 'masteryTermsNamingTheMastery',
        value: MASTERY_TERM_NAMES_THE_MASTERY,
        provenance: GAME_LOCALISATION,
        verification: 'verified_here',
      },
      {
        subject: 'cardMastery.vocabulary',
        predicate: 'uncoveredMasteryVocabularyCount',
        value: MASTERY_VOCABULARY_NOT_COVERED.length,
        provenance: GAME_LOCALISATION,
        verification: 'unverified',
      },
      {
        subject: 'card.berserker',
        predicate: 'name',
        value: 'Berserker',
        provenance: GAME_LOCALISATION,
        verification: 'verified_here',
      },
      {
        subject: 'card.berserker',
        predicate: 'name',
        value: 'Berserker',
        provenance: CATALOG_CARDS,
        verification: 'verified_here',
      },
    ],
    sources: [GAME_LOCALISATION, CATALOG_CARDS, WIKI_MASTERIES],
  },
  ...MASTERY_NODES,
  {
    id: 'cardMastery',
    label: 'Card mastery',
    kind: 'system',
    claimType: 'objective',
    verification: 'verified_here',
    summary:
      'A second upgrade track on a card, unlocked with stones once 30 cards are maxed and the '
      + 'Tier 16 Wave 100 milestone is claimed. Levels 0–9, raised by mastery labs that cost the '
      + 'same coins and time for every card.',
    units: 'level (0–9)',
    validRange:
      'Level 0 to 9. Level 0 is the unlock and already grants the first bonus — there is no '
      + '"unlocked but inactive" state.',
    traps: [
      'THE CARD MUST BE EQUIPPED for its mastery to do anything. Owning a mastery is not the same '
      + 'as benefiting from it, and slots are the binding constraint.',
      'Level 0 already gives a bonus. Treating 0 as "no effect" understates every unlocked '
      + 'mastery by one full step.',
      'Roughly half of masteries do NOT scale the card\'s own stat — they add an unrelated effect. '
      + 'Cash mastery drops reroll dice; Fortress cuts wall rebuild; Free Upgrades locks a stat '
      + 'out of free upgrades. A scalar model is wrong for about half the deck.',
      'Unlock cost varies per card (500–1250 stones) even though the LAB ladder above level 0 is '
      + 'identical for all of them. Two different cost curves in one system.',
      'The ladder is enormous in real time — 104 days for level 9, over 560 days to max one '
      + 'mastery from level 1. Any plan measured in weeks is measuring the wrong thing.',
    ],
    assertions: [
      {
        subject: 'cardMastery',
        predicate: 'maxLevel',
        value: CARD_MASTERY_MAX_LEVEL,
        provenance: WIKI_MASTERIES,
        verification: 'verified_here',
      },
      {
        subject: 'cardMastery',
        predicate: 'requiredMaxedCards',
        value: CARD_MASTERY_REQUIRED_MAXED_CARDS,
        provenance: WIKI_MASTERIES,
        verification: 'verified_here',
      },
      { subject: 'cardMastery', predicate: 'minLevel', value: CARD_MASTERY_MIN_LEVEL, provenance: WIKI_MASTERIES },
      { subject: 'cardMastery', predicate: 'masteryCount', value: Object.keys(CARD_MASTERY_STONE_COST).length, provenance: WIKI_MASTERIES },
      { subject: 'cardMastery', predicate: 'scalesOwnStatCount', value: MASTERIES_THAT_SCALE_THE_CARD.length, provenance: WIKI_MASTERIES },
      { subject: 'cardMastery', predicate: 'totalUnlockStoneCost', value: CARD_MASTERY_TOTAL_STONE_COST, provenance: WIKI_MASTERIES },
      { subject: 'cardMastery', predicate: 'minUnlockStoneCost', value: Math.min(...Object.values(CARD_MASTERY_STONE_COST)), provenance: WIKI_MASTERIES },
      { subject: 'cardMastery', predicate: 'maxUnlockStoneCost', value: Math.max(...Object.values(CARD_MASTERY_STONE_COST)), provenance: WIKI_MASTERIES },
      { subject: 'cardMastery.lab', predicate: 'daysToMaxOneMastery', value: CARD_MASTERY_LAB_DAYS_TO_MAX, provenance: WIKI_MASTERIES },
      { subject: 'cardMastery.lab', predicate: 'daysAtLevel9', value: CARD_MASTERY_LAB_DAYS_BY_LEVEL[9], provenance: WIKI_MASTERIES },
      { subject: 'cardMastery', predicate: 'unlockTier', value: CARD_MASTERY_MILESTONE_TIER, provenance: WIKI_MASTERIES },
      { subject: 'cardMastery', predicate: 'unlockWave', value: CARD_MASTERY_MILESTONE_WAVE, provenance: WIKI_MASTERIES },
      { subject: 'cardMastery', predicate: 'nameDiffersFromCardCount', value: Object.keys(CARD_MASTERY_NAME_TO_CARD).length, provenance: WIKI_MASTERIES },
    ],
    sources: [WIKI_MASTERIES],
  },
  {
    id: 'cardMastery.naming',
    label: 'Two masteries are spelled differently from their cards',
    kind: 'rule',
    claimType: 'objective',
    verification: 'verified_here',
    summary:
      'All 31 masteries map one-to-one onto the 31 cards, but two are spelled differently in the '
      + 'mastery tables than in the card catalog: Package Chance is the card Recovery Package '
      + 'Chance, and Berserker is the card Berzerker. Join on CARD_MASTERY_NAME_TO_CARD, not on '
      + 'the raw name.',
    disambiguation:
      'A spelling difference between two tables, not two different things. Both tables are '
      + 'internally correct.',
    traps: [
      'Joining masteries to cards by name succeeds for 29 and returns nothing for two. That reads '
      + 'as "Berzerker and Recovery Package Chance have no mastery" rather than as a spelling '
      + 'mismatch — the same failure shape as the guardian chip labels and the UW stat names.',
      'The wiki uses the mastery spelling and the catalog uses the card spelling, so which one is '
      + '"right" depends on which table you are reading. Neither is wrong.',
    ],
    implementedBy: ['CARD_MASTERY_NAME_TO_CARD', 'CARD_MASTERY_STONE_COST'],
    assertions: [
      { subject: 'cardMastery.naming', predicate: 'masteryCount', value: Object.keys(CARD_MASTERY_STONE_COST).length, provenance: WIKI_MASTERIES },
      { subject: 'cardMastery.naming', predicate: 'spellingMismatchCount', value: Object.keys(CARD_MASTERY_NAME_TO_CARD).length, provenance: WIKI_MASTERIES },
      { subject: 'cardMastery.naming', predicate: 'oneToOneWithCards', value: true, provenance: WIKI_MASTERIES },
    ],
    sources: [WIKI_MASTERIES],
  },
  {
    id: 'cardMastery.effect',
    label: 'Mastery effect',
    kind: 'stat',
    claimType: 'objective',
    verification: 'verified_here',
    summary:
      'What a mastery actually grants. Six scale the card\'s own multiplier; the rest add a '
      + 'distinct mechanic — reroll dice, wall rebuild reduction, elite double-spawn chance, '
      + 'protector-shield piercing, UW crit chance.',
    units: 'varies per mastery — multiplier, percent, seconds, or count',
    traps: [
      'Units differ per mastery in the same table, exactly as they do for card values. Fortress '
      + 'mastery is NEGATIVE seconds (−10s to −100s wall rebuild); Free Upgrades mastery is a '
      + 'COUNT (1–10 stats locked); Damage mastery is a multiplier (×1.4 to ×5).',
      'Super Tower mastery makes 35% of the Super Tower bonus apply to ultimate weapons — which '
      + 'otherwise it never does. The mastery changes a documented exclusion, so a rule learned '
      + 'about the base card stops holding.',
      'Berserker mastery raises the damage cap to ×500 but only for a limited window after Death '
      + 'Defy triggers. The base +700% cap is not simply replaced.',
    ],
    implementedBy: ['CARD_MASTERY_EFFECTS', 'MASTERIES_THAT_SCALE_THE_CARD'],
    assertions: [
      { subject: 'cardMastery.effect', predicate: 'masteriesDescribed', value: Object.keys(CARD_MASTERY_EFFECTS).length, provenance: WIKI_MASTERIES },
      { subject: 'cardMastery.effect', predicate: 'scaleOwnCardStat', value: MASTERIES_THAT_SCALE_THE_CARD.length, provenance: WIKI_MASTERIES },
      // The complement, stated rather than left to subtraction. Most of the
      // system is the part that does NOT simply scale the card, and a reader
      // who assumes otherwise models about two thirds of it wrongly.
      { subject: 'cardMastery.effect', predicate: 'addADistinctMechanic', value: Object.keys(CARD_MASTERY_EFFECTS).length - MASTERIES_THAT_SCALE_THE_CARD.length, provenance: WIKI_MASTERIES },
      { subject: 'cardMastery.effect', predicate: 'everyMasteryHasAShorthand', value: Object.values(CARD_MASTERY_EFFECTS).every(spec => spec.short.length > 0), provenance: WIKI_MASTERIES, verification: 'verified_here' as const },
    ],
    sources: [WIKI_MASTERIES],
  },
  {
    id: 'cardMastery.lab',
    label: 'Mastery lab',
    kind: 'entity',
    claimType: 'objective',
    verification: 'verified_here',
    summary:
      'The research that raises a mastery from level 1 to 9. Identical cost and time for every '
      + 'mastery — 20.8 days and 1.10q coins at level 1, rising to 104.2 days and 10.00q at level 9.',
    units: 'days and coins',
    traps: [
      'Mastery labs compete for the same five research slots as every other lab. A mastery in '
      + 'progress is a slot not researching anything else for up to 104 days.',
      'Cost and time are flat across masteries, so the only differentiator between two mastery '
      + 'investments is the effect — never the price.',
    ],
    implementedBy: ['CARD_MASTERY_LAB_DAYS_BY_LEVEL', 'CARD_MASTERY_LAB_DAYS_TO_MAX'],
    assertions: [
      { subject: 'cardMastery.lab', predicate: 'levelsPriced', value: Object.keys(CARD_MASTERY_LAB_DAYS_BY_LEVEL).length, provenance: WIKI_MASTERIES },
      { subject: 'cardMastery.lab', predicate: 'daysAtLevel1', value: CARD_MASTERY_LAB_DAYS_BY_LEVEL[1], provenance: WIKI_MASTERIES },
      { subject: 'cardMastery.lab', predicate: 'daysAtLevel9', value: CARD_MASTERY_LAB_DAYS_BY_LEVEL[9], provenance: WIKI_MASTERIES },
      // Derived from the per-level table rather than transcribed beside it, so
      // the total cannot drift away from its own parts.
      { subject: 'cardMastery.lab', predicate: 'daysToMaxOneMastery', value: Object.values(CARD_MASTERY_LAB_DAYS_BY_LEVEL).reduce((sum, days) => sum + days, 0), provenance: WIKI_MASTERIES, verification: 'verified_here' as const },
    ],
    sources: [{ ...WIKI_MASTERIES, section: 'Card Mastery Lab Time and Coins' }],
  },
]

/** Each generated mastery belongs to the system, so none is orphaned. */
const MASTERY_MEMBER_EDGES: KnowledgeEdge[] = MASTERY_NODES.map(node => ({
  from: node.id,
  kind: 'memberOf' as const,
  to: 'cardMastery',
  note:
    'One of the card masteries — unlocked with stones once 30 cards are maxed, then raised by '
    + 'mastery labs, and only active while its card is equipped.',
  sources: [WIKI_MASTERIES],
}))

export const MASTERY_KNOWLEDGE_EDGES: readonly KnowledgeEdge[] = [
  {
    from: 'cardMastery.vocabulary',
    kind: 'memberOf',
    to: 'cardMastery',
    note:
      'What the game calls these, which is not always what the catalog calls them. A mastery you '
      + 'cannot name is one you cannot look up.',
    sources: [GAME_LOCALISATION],
  },
  ...MASTERY_MEMBER_EDGES,
  {
    from: 'cardMastery.naming',
    kind: 'memberOf',
    to: 'cardMastery',
    note:
      'Which name each mastery goes by in the mastery tables versus the card catalog. Two of the '
      + 'thirty-one differ, and a name join loses exactly those two.',
    sources: [WIKI_MASTERIES],
  },
  {
    from: 'cardMastery',
    kind: 'derivedFrom',
    to: 'card',
    note:
      'A mastery belongs to a specific card and does nothing unless that card is equipped — so '
      + 'card slots bound mastery value just as they bound card value.',
    sources: [WIKI_MASTERIES],
  },
  {
    from: 'card.slot',
    kind: 'caps',
    to: 'cardMastery',
    note: 'An unequipped card\'s mastery contributes nothing, however many levels it has.',
    sources: [WIKI_MASTERIES],
  },
  {
    from: 'milestone',
    kind: 'gates',
    to: 'cardMastery',
    note: 'Tier 16 Wave 100, and additionally 30 cards must already be maxed.',
    sources: [WIKI_MASTERIES],
  },
  {
    from: 'cardMastery.lab',
    kind: 'scales',
    to: 'cardMastery',
    note: 'Levels 1–9 come only from mastery labs; level 0 comes from the stone unlock.',
    sources: [{ ...WIKI_MASTERIES, section: 'Card Mastery Lab Time and Coins' }],
  },
  {
    from: 'cardMastery.lab',
    kind: 'caps',
    to: 'lab.slot',
    note: 'Mastery research occupies one of the five slots for up to 104 days at a time.',
    sources: [{ ...WIKI_MASTERIES, section: 'Card Mastery Lab Time and Coins' }],
  },
  {
    from: 'cardMastery.effect',
    kind: 'memberOf',
    to: 'cardMastery',
    note: 'Six masteries scale the card; the rest add an unrelated mechanic.',
    sources: [WIKI_MASTERIES],
  },
  {
    from: 'cardMastery.effect',
    kind: 'scales',
    to: 'ultimateWeapon',
    note:
      'Super Tower mastery applies 35% of its bonus to ultimate weapons and cuts their cooldown — '
      + 'overriding the base card\'s documented exclusion from UW damage.',
    sources: [WIKI_MASTERIES],
  },
]
