/**
 * Tournaments and events — the sources of stones, medals and keys.
 *
 * Read off the wiki on 2026-08-16.
 *
 * This is where the game's currencies actually come from, and it is routinely
 * modelled backwards. Ultimate weapons cost stones; stones come almost entirely
 * from tournaments. Bots cost medals; medals come only from events. A plan that
 * recommends buying either without accounting for its source is recommending a
 * purchase the player has no route to afford.
 */
/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    TOURNAMENT_LEAGUE_NAMES, TOURNAMENT_PROTECTED_LEAGUES, TOURNAMENT_PLAYER_COUNT, TOURNAMENT_RANDOM_BATTLE_CONDITIONS, TOURNAMENT_BOSS_WAVE_INTERVAL, TOURNAMENT_ENEMY_LEVEL_SKIP, EVENT_CYCLE_DAYS, EVENT_MISSION_DAYS (+2 more)
 * depends    src/data/generated, src/data/tournaments/data, src/knowledge/community-guides, src/knowledge/substrate/schema, src/mechanics/battle-conditions/tournament-heat-bc
 * used by    src/knowledge/compartments/index, src/knowledge/index
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
import { V283_HEAT_BC_INDEX } from '../../data/generated'
import {
  TOURNAMENT_HEAT_PROFILES,
  TOURNAMENT_LEAGUES as TOURNAMENT_LEAGUE_ROWS,
} from '../../data/tournaments/data'
import {
  CAMPAIGN_ELS_REDUCTION_HEAT_WAVES_PER_LEVEL,
  computeElsReductionHeatLevel,
  getHeatRampPercent,
  GUARANTEED_ELS_REDUCTION_MAX,
  TOURNAMENT_HEAT_WAVE_TABLE,
} from '../../mechanics/battle-conditions/tournament-heat-bc'
import type { KnowledgeEdge, KnowledgeNode } from '../substrate/schema'
import { communityGuideSource } from '../community-guides'

const WIKI_TOURNAMENTS = { origin: 'wiki', ref: 'Tournaments', verifiedAt: '2026-08-16' } as const
const WIKI_EVENTS = { origin: 'wiki', ref: 'Events', verifiedAt: '2026-08-16' } as const

/** Read from the shipped catalog rather than transcribed, so it cannot drift. */
const CATALOG_TOURNAMENTS = {
  origin: 'code',
  ref: 'thetowersdk/data tournaments',
  verifiedAt: '2026-08-17',
} as const

/**
 * Leagues in promotion order, read from the catalog rather than typed out again.
 *
 * This was its own list of six strings sitting directly beneath the import of the catalog rows it
 * duplicates. The two agreed, and nothing checked that they did — and because both are exported
 * under the same name from different entry points, `TOURNAMENT_LEAGUES` meant a list of names
 * through `thetowersdk/knowledge` and a list of league objects through `thetowersdk/data`.
 *
 * Sorted by the catalog's own `order`, so promotion order comes from the data too.
 */
export const TOURNAMENT_LEAGUE_NAMES = [...TOURNAMENT_LEAGUE_ROWS]
  .sort((left, right) => left.order - right.order)
  .map(row => row.league)


/** Leagues you cannot be demoted back into once left. */
export const TOURNAMENT_PROTECTED_LEAGUES = ['Copper', 'Silver', 'Gold'] as const

/** Players per tournament. */
export const TOURNAMENT_PLAYER_COUNT = 30

/** Extra battle conditions rolled per league, beyond the guaranteed ones. */
export const TOURNAMENT_RANDOM_BATTLE_CONDITIONS: Readonly<Record<string, number>> = {
  Copper: 0, Silver: 1, Gold: 2, Platinum: 3, Champion: 4, Legend: 5,
}

/** Waves between bosses per league — an "overheat" condition that does not ramp. */
export const TOURNAMENT_BOSS_WAVE_INTERVAL: Readonly<Record<string, number>> = {
  Copper: 10, Silver: 9, Gold: 8, Platinum: 7, Champion: 6, Legend: 5,
}

/**
 * Guaranteed Enemy Level Skip Reduction per tournament league (heatLevel[22] cap).
 *
 * ## Read the units before using this
 *
 * Values are BC **levels** (integers), not fractions. v29 binary: **every** league
 * is 0 — no TournamentHeatDataByLeague conditionIndex 22; FixedHeat empty when
 * isTournament. Prior 10/20/30/50 entries were SDK inventions (misread Create
 * levels for Skip Decay / Health Decay). Campaign ELS subtract is a separate path.
 *
 * Every league has an entry, including zeroes. Copper returning `undefined` is
 * indistinguishable, to a caller, from "not a league".
 */
export const TOURNAMENT_ENEMY_LEVEL_SKIP: Readonly<Record<string, number>>
  = GUARANTEED_ELS_REDUCTION_MAX

/** Event cycle: two weeks, with new missions only in the first eight days. */
export const EVENT_CYCLE_DAYS = 14
export const EVENT_MISSION_DAYS = 8

export const META_GAME_KNOWLEDGE_NODES: readonly KnowledgeNode[] = [
  {
    id: 'tournament',
    label: 'Tournament',
    kind: 'system',
    summary:
      'A 30-player ranked run held every Wednesday and Saturday at 00:00 UTC, across six leagues '
      + 'from Copper to Legend. The main source of power stones, and the only source of keys.',
    traps: [
      'One ticket, one run, and only the HIGHEST WAVE of that run is submitted. Total damage, '
      + 'coins and time are irrelevant to placement.',
      'A tournament cannot be joined during an active run.',
      'Tickets: one free per tournament, then 10 gems for the next and +10 gems for each after — '
      + 'the cost escalates rather than staying flat.',
      'Tied players all receive the reward of the LOWEST rank among them, not the highest.',
    ],
    implementedBy: ['TOURNAMENT_LEAGUE_NAMES', 'TOURNAMENT_PROTECTED_LEAGUES'],
    assertions: [
      { subject: 'tournament', predicate: 'leagueCount', value: TOURNAMENT_LEAGUE_NAMES.length, provenance: WIKI_TOURNAMENTS, verification: 'verified_here' as const },
      { subject: 'tournament', predicate: 'protectedLeagueCount', value: TOURNAMENT_PROTECTED_LEAGUES.length, provenance: WIKI_TOURNAMENTS, verification: 'verified_here' as const },
      { subject: 'tournament', predicate: 'playersPerBracket', value: TOURNAMENT_PLAYER_COUNT, provenance: WIKI_TOURNAMENTS },
      // Per league, not per tournament. These three vary by league, so a single
      // figure for "the tournament" would be right for one league and wrong for
      // five -- and the per-league subjects let a reader ask about their own.
      ...TOURNAMENT_LEAGUE_NAMES.map(league => ({
        subject: `tournament.${league}`,
        predicate: 'randomBattleConditions',
        value: TOURNAMENT_RANDOM_BATTLE_CONDITIONS[league] ?? -1,
        provenance: WIKI_TOURNAMENTS,
        verification: 'verified_here' as const,
      })),
      ...TOURNAMENT_LEAGUE_NAMES.map(league => ({
        subject: `tournament.${league}`,
        predicate: 'bossWaveInterval',
        value: TOURNAMENT_BOSS_WAVE_INTERVAL[league] ?? -1,
        provenance: WIKI_TOURNAMENTS,
        verification: 'verified_here' as const,
      })),
      // Protection is a property of SOME leagues, not all. Stating both counts
      // means a change to either shows up as a disagreement rather than as one
      // number quietly moving.
      { subject: 'tournament', predicate: 'unprotectedLeagueCount', value: TOURNAMENT_LEAGUE_NAMES.length - TOURNAMENT_PROTECTED_LEAGUES.length, provenance: WIKI_TOURNAMENTS, verification: 'verified_here' as const },
    ],
    sources: [WIKI_TOURNAMENTS, communityGuideSource('evan-legend-tournament')],
  },
  {
    id: 'tournament.league',
    label: 'Tournament league',
    kind: 'tier',
    summary:
      'Copper, Silver, Gold, Platinum, Champion, Legend. The top 4 promote; from Platinum down, '
      + 'the bottom 6 demote. Copper, Silver and Gold are protected — once left, never returned to.',
    units: 'league',
    traps: [
      'League difficulty is expressed as "tier +", meaning enemy stats scale FASTER than the '
      + 'nominal tier. Copper sits between tiers 1 and 2; Champion between 11 and 12. Equating a '
      + 'league to a plain tier understates it.',
      'Only Legend awards keys. A key-based plan is unreachable below it.',
      'Copper, Silver, Gold, Platinum, Champion, Legend, and Mythic all have tournament '
      + 'Enemy Level Skip Reduction (heatLevel[22]) of ZERO in v29 — a value, not an absence. '
      + '`TOURNAMENT_ENEMY_LEVEL_SKIP` must keep every league key so a lookup never returns '
      + '`undefined` for a real league name.',
    ],
    claimType: 'objective',
    verification: 'verified_here',
    disambiguation:
      'Every league has the same player count. What changes with league is difficulty, battle '
      + 'conditions, level skip and which currencies the rewards include.',
    implementedBy: ['TOURNAMENT_LEAGUE_NAMES', 'TOURNAMENT_ENEMY_LEVEL_SKIP', 'TOURNAMENT_LEAGUE_TIER_BASES'],
    assertions: [
      { subject: 'tournament.league', predicate: 'leagueCount', value: TOURNAMENT_LEAGUE_ROWS.length, provenance: CATALOG_TOURNAMENTS },
      { subject: 'tournament.league', predicate: 'playersPerTournament', value: TOURNAMENT_PLAYER_COUNT, provenance: CATALOG_TOURNAMENTS },
      { subject: 'tournament.league', predicate: 'levelSkipEntryCount', value: Object.keys(TOURNAMENT_ENEMY_LEVEL_SKIP).length, provenance: CATALOG_TOURNAMENTS },
      { subject: 'tournament.league', predicate: 'protectedLeagueCount', value: TOURNAMENT_PROTECTED_LEAGUES.length, provenance: WIKI_TOURNAMENTS },
      { subject: 'tournament.league.Copper', predicate: 'enemyLevelSkip', value: TOURNAMENT_ENEMY_LEVEL_SKIP.Copper, provenance: CATALOG_TOURNAMENTS },
      { subject: 'tournament.league.Legend', predicate: 'enemyLevelSkip', value: TOURNAMENT_ENEMY_LEVEL_SKIP.Legend, provenance: CATALOG_TOURNAMENTS },
      { subject: 'tournament.league.Legend', predicate: 'awardsKeys', value: true, provenance: CATALOG_TOURNAMENTS },
    ],
    sources: [{ ...WIKI_TOURNAMENTS, section: 'Promoting' }, CATALOG_TOURNAMENTS],
  },
  {
    id: 'tournament.heat',
    label: 'Heat (tournament battle conditions)',
    kind: 'rule',
    claimType: 'objective',
    verification: 'verified_here',
    summary:
      'The battle-condition pressure applied in every league above Copper. It RAMPS with wave '
      + `count, from ${getHeatRampPercent(0, 'Legend')}% at the start of a run to `
      + `${getHeatRampPercent(1000, 'Legend')}% at wave 1000. Silver rolls one extra random `
      + 'condition, Gold two, up to six at Mythic, on top of the guaranteed ones.',
    units: 'BC level; the ramp is a percentage of the league cap',
    disambiguation:
      'Not a tier battle condition. Tier conditions are static and identical every run; heat is '
      + 'per-league, ramps with wave, and its random component is re-rolled per tournament seed. '
      + 'They share the definitions table and several names, which is why they get conflated. '
      + 'Also not the same as OVERHEAT: More Bosses is overheat, fixed by league, no ramp.',
    implementedBy: [
      'TOURNAMENT_HEAT_PROFILES',
      'getHeatRampPercent',
      'getHeatEffectivenessPercent',
      'computeElsReductionHeatLevel',
      'computeRandomHeatBcLevel',
    ],
    assertions: [
      {
        subject: 'tournament.heat',
        predicate: 'leaguesWithHeat',
        value: TOURNAMENT_HEAT_PROFILES.filter(profile => profile.hasHeat).length,
        provenance: CATALOG_TOURNAMENTS,
      },
      {
        subject: 'tournament.heat',
        predicate: 'rampPercentAtWave1000',
        value: getHeatRampPercent(1000, 'Legend'),
        provenance: CATALOG_TOURNAMENTS,
      },
      {
        subject: 'tournament.heat',
        predicate: 'rampPercentAtWave0',
        value: getHeatRampPercent(0, 'Legend'),
        provenance: CATALOG_TOURNAMENTS,
      },
      {
        subject: 'tournament.heat',
        predicate: 'waveBreakpointCount',
        value: TOURNAMENT_HEAT_WAVE_TABLE.length,
        provenance: CATALOG_TOURNAMENTS,
      },
      ...TOURNAMENT_HEAT_PROFILES.map(profile => ({
        subject: `tournament.league.${profile.league}`,
        predicate: 'guaranteedElsReductionMax',
        value: GUARANTEED_ELS_REDUCTION_MAX[profile.league],
        provenance: CATALOG_TOURNAMENTS,
      })),
    ],
    traps: [
      'THE RAMP TABLE IS INVERTED FROM WHAT ITS NAME SUGGESTS. `TOURNAMENT_HEAT_WAVE_TABLE` holds '
      + 'how effective your RESISTANCE stays: 95 at wave 0, falling to 5 by wave 1000. Heat '
      + 'strength is its complement, `getHeatRampPercent`. Reading the table as heat gives every '
      + 'answer backwards, and both readings produce a plausible curve.',
      'The two columns are named `t11` and `t14`, which reads as tiers 11 and 14. They are not '
      + 'tiers. The column is chosen by LEAGUE: Silver uses `t11`, Gold and above use `t14`. A '
      + 'tier-based selection is wrong for every tournament run.',
      'Copper has no heat at all, so every heat function returns its neutral value there, and the '
      + 'neutral value is not the same everywhere. `computeElsReductionHeatLevel` returns 0 but '
      + '`computeBossUltimateHeatFactor` returns 1, because one is additive and the other a '
      + 'multiplier. Defaulting both to 0 removes all boss health.',
      'More Bosses is an OVERHEAT condition: static across waves, set by league, no ramp. '
      + 'Applying the wave ramp to it is wrong at every wave except the ends.',
      'From Platinum up, Death Defy Down or Energy Shields Down is always active. One of the two, '
      + 'not both, and which one is not knowable in advance. A plan that assumes the survivable '
      + 'one is planning on a coin flip.',
      'The guaranteed Enemy Level Skip Reduction is a CAP, not the value in effect — and in v29 '
      + 'every tournament league cap is 0, so `computeElsReductionHeatLevel` is always 0. Campaign '
      + 'ELS subtract is a different formula (`computeCampaignElsReductionHeatLevel`).',
      `The resistance-effectiveness ramp still applies to other heat BCs: wave 0 is already `
      + `${getHeatRampPercent(0, 'Legend')}% heat strength for those, because the table starts at 95.`,
    ],
    sources: [{ ...WIKI_TOURNAMENTS, section: 'Battle Conditions' }, CATALOG_TOURNAMENTS],
  },
  {
    id: 'tournament.heat.elsReduction',
    label: 'Enemy Level Skip Reduction (tournament)',
    kind: 'stat',
    claimType: 'objective',
    verification: 'verified_here',
    summary:
      'Skip Reduction - Subtract is a **campaign/tier** battle condition. In v29 tournaments '
      + 'heatLevel[22] is never authored (no TournamentHeatDataByLeague index 22; FixedHeat '
      + 'empty when isTournament), so every league cap is 0 — including Gold…Legend. Prior SDK '
      + `${10}/${20}/${30}/${50} values were inventions. Mythic Create(70) is multiply index 28.`,
    units: 'BC level (integer), NOT a fraction',
    validRange:
      '0 for every tournament league at every wave. Campaign uses '
      + `computeCampaignElsReductionHeatLevel (tier cap + 1 per `
      + `${CAMPAIGN_ELS_REDUCTION_HEAT_WAVES_PER_LEVEL} waves).`,
    disambiguation:
      'The same condition as the campaign tier one - see [[battleCondition.elsReduction]] - but '
      + 'tournaments do not set it in v29. Do not confuse with Skip Reduction Multiply '
      + `(heatLevel index ${V283_HEAT_BC_INDEX.elsReductionMultiply}), which Gold+ do set.`,
    implementedBy: [
      'GUARANTEED_ELS_REDUCTION_MAX',
      'computeElsReductionHeatLevel',
      'computeCampaignElsReductionHeatLevel',
    ],
    assertions: [
      {
        subject: 'tournament.heat.elsReduction',
        predicate: 'heatIndex',
        value: V283_HEAT_BC_INDEX.elsReduction,
        provenance: CATALOG_TOURNAMENTS,
      },
      {
        subject: 'tournament.heat.elsReduction',
        predicate: 'levelAtLegendWave1000',
        value: computeElsReductionHeatLevel('Legend', 1000),
        provenance: CATALOG_TOURNAMENTS,
      },
      {
        subject: 'tournament.heat.elsReduction',
        predicate: 'levelAtLegendWave1',
        value: computeElsReductionHeatLevel('Legend', 1),
        provenance: CATALOG_TOURNAMENTS,
      },
      {
        subject: 'tournament.heat.elsReduction',
        predicate: 'campaignWavesPerExtraLevel',
        value: CAMPAIGN_ELS_REDUCTION_HEAT_WAVES_PER_LEVEL,
        provenance: CATALOG_TOURNAMENTS,
      },
    ],
    traps: [
      'ELS means Enemy Level Skip here. It does NOT mean Energy Shield, which is what `ELS` means '
      + 'everywhere else in this monorepo. `Energy Shields Down` is a separate condition that '
      + 'also appears in tournaments from Platinum up, so both can be active in one run under '
      + 'names one letter apart.',
      'v29 tournaments do NOT apply Skip Reduction - Subtract. Do not restore Gold…Legend caps '
      + 'of 10/20/30/50 — those misread Skip Decay / Health Decay CreateConstantLevels.',
      'Campaign and tournament use the same save slot and different formulas. A helper that takes '
      + 'a wave and returns a level has to know which one it is in; there is no shared function.',
    ],
    sources: [CATALOG_TOURNAMENTS],
  },
  {
    id: 'event',
    label: 'Event',
    kind: 'system',
    summary:
      'A two-week cycle of tiered missions rewarding medals, unlocked at tier 1 wave 70. Seven '
      + 'missions open on day one and two more each day for a week; all remain until the event ends.',
    traps: [
      'Medals come from events and nothing else, and bots are bought with medals. Bot progression '
      + 'is therefore paced by the event calendar, not by in-run performance.',
      'Every mission has three tiers with escalating requirements — completing "a mission" is not '
      + 'a single event.',
      'New missions stop after day 8, but the event runs 14 days. The last six days add nothing.',
      'Some missions auto-complete when the underlying system is maxed (buy cards when all cards '
      + 'are maxed; buy workshop upgrades when the workshop is maxed).',
    ],
    implementedBy: ['EVENT_CYCLE_DAYS', 'EVENT_MISSION_DAYS'],
    assertions: [
      { subject: 'event', predicate: 'cycleDays', value: EVENT_CYCLE_DAYS, provenance: WIKI_EVENTS },
      { subject: 'event', predicate: 'missionDays', value: EVENT_MISSION_DAYS, provenance: WIKI_EVENTS },
      // The mission window is shorter than the cycle, so an event being live is
      // not the same as its missions being available.
      { subject: 'event', predicate: 'missionWindowIsShorterThanCycle', value: EVENT_MISSION_DAYS < EVENT_CYCLE_DAYS, provenance: WIKI_EVENTS, verification: 'verified_here' as const },
    ],
    sources: [WIKI_EVENTS],
  },
  {
    id: 'eventShop',
    label: 'Event shop',
    kind: 'system',
    summary:
      'Where medals are spent — bots, bot unlocks, Bot+ abilities, themes, relics and songs. Bot '
      + 'unlock cost depends on how many bots are already owned.',
    traps: [
      'Event-store relics are only obtainable on event RE-RUNS. Missing an event can put a relic '
      + 'out of reach indefinitely.',
    ],
    assertions: [
      { subject: 'eventShop', predicate: 'stockIsPerEvent', value: true, provenance: WIKI_EVENTS },
      { subject: 'eventShop', predicate: 'currencyExpiresWithTheEvent', value: true, provenance: WIKI_EVENTS },
    ],
    sources: [{ ...WIKI_EVENTS, section: 'Event Shop' }],
  },
]

export const META_GAME_KNOWLEDGE_EDGES: readonly KnowledgeEdge[] = [
  {
    from: 'tournament.heat',
    kind: 'scales',
    to: 'tournament.heat.elsReduction',
    note:
      'The league sets the ceiling; the wave ramp sets what fraction of it is in effect. Neither '
      + 'alone gives the level, which is why reading the league number as the value is wrong for '
      + 'most of a run.',
    sources: [CATALOG_TOURNAMENTS],
  },
  {
    from: 'tournament.heat.elsReduction',
    kind: 'derivedFrom',
    to: 'battleCondition.elsReduction',
    note:
      'Same condition, same save slot, different formula. Campaign scales it by wave without '
      + 'bound; a tournament caps it at the league maximum.',
    sources: [CATALOG_TOURNAMENTS],
  },
  {
    from: 'tournament.heat.elsReduction',
    kind: 'scales',
    to: 'enemyLevelSkip',
    note:
      'It subtracts from enemy level skip chance — the thing the abbreviation is named after, and '
      + 'the reason mistaking ELS for Energy Shield changes which stat a plan defends.',
    sources: [CATALOG_TOURNAMENTS],
  },
  {
    from: 'tournament.heat',
    kind: 'independentOf',
    to: 'tier.battleCondition',
    note:
      'Stated because they share a definitions table and several names. A tier condition does not '
      + 'change in a tournament and heat does not apply outside one; a model that adds them '
      + 'together double-counts.',
    sources: [CATALOG_TOURNAMENTS],
  },
  {
    from: 'tournament',
    kind: 'gates',
    to: 'ultimateWeapon',
    note:
      'Tournaments are the main source of power stones, and power stones are what ultimate weapons '
      + 'cost — so UW progression is paced by tournament placement, not by runs.',
    sources: [WIKI_TOURNAMENTS],
  },
  {
    from: 'tournament.league',
    kind: 'scales',
    to: 'tournament',
    note: 'League sets enemy scaling, how many heat conditions apply, and the reward table.',
    sources: [{ ...WIKI_TOURNAMENTS, section: 'Tournament Difficulty' }],
  },
  {
    from: 'tournament.heat',
    kind: 'caps',
    to: 'tournament.league',
    note: 'Every league above Copper carries heat, ramping to full strength at wave 1000.',
    sources: [{ ...WIKI_TOURNAMENTS, section: 'Battle Conditions' }],
  },
  {
    from: 'tournament.league',
    kind: 'gates',
    to: 'relic',
    note: 'Tournament placement is one of the six relic sources.',
    sources: [{ ...WIKI_TOURNAMENTS, section: 'Rewards' }],
  },
  {
    from: 'event',
    kind: 'gates',
    to: 'bot',
    note: 'Bots cost medals, medals come only from events — bot progress is paced by the calendar.',
    sources: [WIKI_EVENTS],
  },
  {
    from: 'eventShop',
    kind: 'gates',
    to: 'botPlus',
    note: 'Bot+ abilities are bought in the event shop once every bot is owned.',
    sources: [{ ...WIKI_EVENTS, section: 'Bot+' }],
  },
  {
    from: 'eventShop',
    kind: 'memberOf',
    to: 'event',
    note: 'The shop is where event medals are spent, on bots, themes, relics and songs.',
    sources: [{ ...WIKI_EVENTS, section: 'Event Shop' }],
  },
  {
    from: 'milestone',
    kind: 'gates',
    to: 'tournament',
    note: 'Tournaments unlock at the tier 1 wave 60 milestone; events at tier 1 wave 70.',
    sources: [{ ...WIKI_TOURNAMENTS, section: 'Entering A Tournament' }],
  },
]
