/**
 * Reading and writing Google Sheets, generalised.
 *
 * Community Tower spreadsheets are a primary source — planner workbooks, tier lists, guild
 * rosters — and every tool that has read one here has hit the same handful of things. None
 * of them raise an error. Each one returns a value that looks like data and is not, which
 * is why they belong in the oracle rather than in a comment somewhere.
 *
 * Nothing in this compartment is about a particular workbook. It is about the API and the
 * shape of the answers it gives, so it holds for any sheet a tool is pointed at.
 */
/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    SHEETS_KNOWLEDGE_NODES, SHEETS_KNOWLEDGE_EDGES
 * depends    src/knowledge/substrate/schema
 * used by    src/knowledge/compartments/index
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
import type { KnowledgeEdge, KnowledgeNode } from '../substrate/schema'

/** Learned the hard way against live community workbooks, over many sessions. */
const EPATHS_ORACLE = {
  origin: 'code',
  ref: 'tools/effective-paths-oracle/server.mjs — the read/write surface used against live workbooks',
  verifiedAt: '2026-08-25',
} as const

const SDK_SHEETS = {
  origin: 'code',
  ref: 'thetowersdk/sheets TowerSheets, packages/sdk/src/sheets/sheets.test.ts',
  verifiedAt: '2026-08-25',
} as const

const GOOGLE_DOCS = {
  origin: 'code',
  ref: 'Google Sheets API v4 — spreadsheets.values.get / update, valueRenderOption',
  verifiedAt: '2026-08-25',
} as const

export const SHEETS_KNOWLEDGE_NODES: readonly KnowledgeNode[] = [
  {
    id: 'sheets.access',
    label: 'Getting a program access to a spreadsheet',
    kind: 'rule',
    claimType: 'objective',
    verification: 'verified_here',
    summary:
      'Access comes from a SERVICE ACCOUNT — a Google account belonging to a program, with its '
      + 'own email address and its own JSON key. You enable the Sheets API on a cloud project, '
      + 'create the account, download a key, and share the spreadsheet with that email exactly '
      + 'as you would with a person. Viewer to read, Editor to write.',
    disambiguation:
      'Project-level IAM roles do NOT grant access to a spreadsheet. Sharing the document does. '
      + 'Granting roles at the project instead is the usual wrong turn, and it over-permissions '
      + 'the account while still failing to open the sheet.',
    traps: [
      'ENABLING THE API IS A SEPARATE STEP FROM CREATING THE ACCOUNT, and skipping it fails as a '
      + '403 that names a project NUMBER rather than saying the API is off. Freshly enabling it '
      + 'is not instant either, so an immediate retry can fail the same way.',
      'A 404 ON A SPREADSHEET ID USUALLY MEANS "NOT SHARED", NOT "NOT FOUND". The API does not '
      + 'distinguish a document that does not exist from one the caller cannot see, so a correct '
      + 'id that nobody shared reads as a typo.',
      'SHARED AS VIEWER READS FINE AND FAILS ONLY ON WRITE. The failure therefore appears the '
      + 'first time a write is attempted, which is often long after the integration looked done.',
      'THE KEY FILE IS A PASSWORD TO EVERY SHEET THE ACCOUNT CAN SEE. Rotating the file on disk '
      + 'does nothing on its own — the old key stays valid until it is DELETED in the console.',
      'ASK FOR THE READ-ONLY SCOPE UNLESS THE PROCESS WRITES. A token that cannot write cannot be '
      + 'made to write by a bug or a bad range.',
    ],
    assertions: [
      {
        subject: 'sheets.access',
        predicate: 'readOnlyScope',
        value: 'https://www.googleapis.com/auth/spreadsheets.readonly',
        provenance: GOOGLE_DOCS,
      },
      {
        subject: 'sheets.access',
        predicate: 'readWriteScope',
        value: 'https://www.googleapis.com/auth/spreadsheets',
        provenance: GOOGLE_DOCS,
      },
      {
        subject: 'sheets.access',
        predicate: 'credentialsEnvVar',
        value: 'GOOGLE_APPLICATION_CREDENTIALS',
        provenance: EPATHS_ORACLE,
      },
    ],
    sources: [GOOGLE_DOCS, EPATHS_ORACLE],
  },

  {
    id: 'sheets.spilledCells',
    label: 'A spilled cell carries no formula',
    kind: 'rule',
    claimType: 'objective',
    verification: 'verified_here',
    summary:
      'An ARRAYFORMULA, SEQUENCE or any other spilling function writes ONE formula and fills many '
      + 'cells. Reading the range with valueRenderOption FORMULA returns the formula for the '
      + 'anchor and an empty string for every cell it spilled into.',
    disambiguation:
      'Reading formulas to learn how a range is computed is the correct instinct and is exactly '
      + 'where this misleads. The empty cells are not literals and are not blank; they are '
      + 'mirrors of a formula stored elsewhere.',
    traps: [
      'A MOSTLY-EMPTY FORMULA READ IS THE SIGNATURE OF A SPILL, NOT OF PLAIN DATA. Concluding '
      + '"this range is typed values" from it is concluding the opposite of the truth.',
      'THE ANCHOR IS NOT ALWAYS AT THE TOP LEFT OF THE RANGE YOU ASKED FOR. It sits wherever the '
      + 'formula was written, which may be above or to the left of your range entirely — so a '
      + 'narrow read can contain no anchor at all.',
      'COMPARE VALUE COUNT AGAINST FORMULA COUNT BEFORE TRUSTING EITHER. Many values and few '
      + 'formulas is the tell; `TowerSheets.readFormulas` reports it rather than leaving it to be '
      + 'noticed.',
    ],
    assertions: [
      {
        subject: 'sheets.spilledCells',
        predicate: 'formulaReadReturnsEmptyForSpillTargets',
        value: true,
        provenance: SDK_SHEETS,
      },
    ],
    implementedBy: ['TowerSheets'],
    sources: [EPATHS_ORACLE, SDK_SHEETS],
  },

  {
    id: 'sheets.blankIsNotMissing',
    label: 'Blank, absent and truncated all read the same',
    kind: 'rule',
    claimType: 'objective',
    verification: 'verified_here',
    summary:
      'The API drops trailing empty cells and trailing empty rows. A request for a 50x3 block on '
      + 'a sheet with two filled rows returns two rows, one of which may be two cells wide — so '
      + 'the returned shape does not match the shape that was asked for.',
    disambiguation:
      'This is not an error condition and there is no flag to turn it off. It is how the values '
      + 'endpoint always behaves, on every read.',
    traps: [
      'AN EMPTY CELL AND AN ABSENT COLUMN BECOME THE SAME `undefined`. Code that indexes the '
      + 'ragged rows cannot tell "this cell is blank" from "this column does not exist", and the '
      + 'second is a schema change worth noticing.',
      'AN EMPTY RESULT AND A MISTYPED TAB NAME ARE INDISTINGUISHABLE. Both come back as no rows '
      + 'and no error. Count what is actually populated before concluding a range is empty.',
      'PAD TO THE REQUESTED RECTANGLE BEFORE READING BY INDEX. `TowerSheets.readGrid` does this; '
      + '`readValues` deliberately does not, because sometimes the raggedness is the signal.',
    ],
    assertions: [
      {
        subject: 'sheets.blankIsNotMissing',
        predicate: 'trailingEmptyCellsAreTruncated',
        value: true,
        provenance: GOOGLE_DOCS,
      },
    ],
    implementedBy: ['TowerSheets'],
    sources: [GOOGLE_DOCS, SDK_SHEETS],
  },

  {
    id: 'sheets.rangeNaming',
    label: 'A1 ranges, tab names and the quoting that fails silently',
    kind: 'rule',
    claimType: 'objective',
    verification: 'verified_here',
    summary:
      'A range is `Tab!A1:C10`. A tab name that is not a bare identifier must be quoted, and an '
      + 'apostrophe inside it doubles: `Player\'s Data` becomes `\'Player\'\'s Data\'`. Columns are '
      + 'bijective base-26 — A..Z, AA..AZ, BA.. — with no zero digit.',
    traps: [
      'A WRONGLY QUOTED TAB NAME DOES NOT ERROR. The API looks for a tab that does not exist and '
      + 'returns an empty result, which is identical to reading an empty range.',
      'BIJECTIVE BASE-26 IS NOT ORDINARY BASE-26. Converting an index to a column label with a '
      + 'plain division produces `A@` where it should produce `Z`; the carry needs a decrement.',
      'AN OPEN-ENDED RANGE (`A:C`, `A1:C`) HAS NO ROW BOUND IN THE STRING. Only the sheet knows '
      + 'where its data stops, so a parser that resolves one to a last row has invented it.',
      'A TAB NAME FROM A DOCUMENT IS AN UNTRUSTED KEY. Indexing a record with it resolves '
      + '`constructor` and `toString` to Object.prototype members — and `??` cannot reject a '
      + 'function. Use own-key access.',
    ],
    assertions: [
      {
        subject: 'sheets.rangeNaming',
        predicate: 'apostropheInTabNameDoubles',
        value: "'Player''s Data'",
        provenance: SDK_SHEETS,
      },
      { subject: 'sheets.rangeNaming', predicate: 'columnLabelAtIndex25', value: 'Z', provenance: SDK_SHEETS },
      { subject: 'sheets.rangeNaming', predicate: 'columnLabelAtIndex26', value: 'AA', provenance: SDK_SHEETS },
      { subject: 'sheets.rangeNaming', predicate: 'columnLabelAtIndex701', value: 'ZZ', provenance: SDK_SHEETS },
    ],
    implementedBy: ['quoteSheetName', 'columnIndexToLabel', 'parseA1RangeToCoordinates'],
    sources: [SDK_SHEETS],
  },

  {
    id: 'sheets.writing',
    label: 'Writing to a sheet, and to the wrong sheet',
    kind: 'rule',
    claimType: 'objective',
    verification: 'verified_here',
    summary:
      'Writes go through `spreadsheets.values.update` with a valueInputOption: RAW stores exactly '
      + 'what is sent, USER_ENTERED parses it the way typing would — so formulas evaluate, and '
      + 'strings that look like numbers or dates are converted.',
    disambiguation:
      'RAW and USER_ENTERED are not a formatting preference. They decide whether `=SUM(A1:A2)` is '
      + 'stored as text or becomes a live formula, and whether `1/2` stays a string or becomes a '
      + 'date.',
    traps: [
      'A WRITE TO A COMMUNITY WORKBOOK IS IMMEDIATE AND IS NOT UNDONE BY NOTICING QUICKLY. Name '
      + 'the ids a tool must never write to and refuse them; copy the sheet and write to the copy.',
      'REFUSE LOUDLY, NOT QUIETLY. A silent skip has the caller report success while nothing '
      + 'changed, which is worse than a failure — the sheet and the log disagree and only the '
      + 'sheet is right.',
      'USER_ENTERED WILL REWRITE VALUES YOU DID NOT MEAN TO CHANGE — a leading `+` or `=` becomes '
      + 'a formula, and a bare `1/2` becomes a date. Use RAW unless formulas are the point.',
      'WRITE TO A SCRATCH TAB WHEN EVALUATING FORMULAS. Landing a probe formula on real data is a '
      + 'one-keystroke mistake with no undo for anyone but the owner.',
    ],
    assertions: [
      { subject: 'sheets.writing', predicate: 'rawInputOption', value: 'RAW', provenance: GOOGLE_DOCS },
      { subject: 'sheets.writing', predicate: 'parsingInputOption', value: 'USER_ENTERED', provenance: GOOGLE_DOCS },
      {
        subject: 'sheets.writing',
        predicate: 'protectedWriteThrowsRatherThanSkipping',
        value: true,
        provenance: SDK_SHEETS,
      },
    ],
    implementedBy: ['TowerSheets'],
    sources: [GOOGLE_DOCS, EPATHS_ORACLE],
  },

  {
    id: 'sheets.readingEfficiently',
    label: 'Reading a lot without being rate-limited',
    kind: 'rule',
    claimType: 'objective',
    verification: 'verified_here',
    summary:
      'The API rejects a single range that is too large and rate-limits a caller that asks too '
      + 'often. One wide read beats many narrow ones, and an oversized range should be split into '
      + 'row-aligned rectangles that reassemble by concatenation.',
    traps: [
      'MANY SMALL READS COST FAR MORE THAN ONE LARGE ONE. The per-request overhead dominates, so '
      + 'a loop that reads a cell at a time is orders of magnitude slower than reading the block.',
      'SPLITTING BY COLUMN BREAKS REASSEMBLY. Chunks must keep the full width or the pieces no '
      + 'longer concatenate into the original block.',
      'THE WORKBOOK\'S OWN RECALCULATION IS OFTEN THE SLOW PART, NOT THE NETWORK. A heavy planner '
      + 'sheet can take seconds to settle after a write, and a read taken too soon returns the '
      + 'previous values with no indication that it did.',
    ],
    assertions: [
      {
        subject: 'sheets.readingEfficiently',
        predicate: 'chunksPreserveFullWidth',
        value: true,
        provenance: SDK_SHEETS,
      },
    ],
    implementedBy: ['splitA1Range', 'TowerSheets'],
    sources: [EPATHS_ORACLE, SDK_SHEETS],
  },
]

export const SHEETS_KNOWLEDGE_EDGES: readonly KnowledgeEdge[] = [
  {
    from: 'sheets.spilledCells',
    kind: 'memberOf',
    to: 'sheets.access',
    note: 'What a read returns, once you can read at all.',
    sources: [SDK_SHEETS],
  },
  {
    from: 'sheets.blankIsNotMissing',
    kind: 'memberOf',
    to: 'sheets.access',
    note: 'The other way a successful read misleads.',
    sources: [SDK_SHEETS],
  },
  {
    from: 'sheets.rangeNaming',
    kind: 'gates',
    to: 'sheets.blankIsNotMissing',
    note: 'A mis-quoted tab returns the same empty result as an empty range, so naming has to be '
      + 'ruled out before absence is believed.',
    sources: [SDK_SHEETS],
  },
  {
    from: 'sheets.writing',
    kind: 'memberOf',
    to: 'sheets.access',
    note: 'Writing needs Editor on the document, not merely a wider scope on the token.',
    sources: [GOOGLE_DOCS],
  },
  {
    from: 'sheets.readingEfficiently',
    kind: 'memberOf',
    to: 'sheets.access',
    note: 'How to read a lot of it once access works.',
    sources: [SDK_SHEETS],
  },
]
