/**
 * Themes, as an economy input rather than a cosmetic one.
 *
 * Owning a theme pays a passive coin bonus whether or not it is equipped, so a
 * theme count is a number that belongs in a coin calculation. That is the only
 * reason this compartment exists — the menu, the songs and the browsing are
 * presentation and are not modelled here.
 *
 * Everything below is derived from the shipped catalogs rather than
 * transcribed, so the graph cannot drift from them. Where the two catalogs
 * disagree, the disagreement is recorded as a disagreement.
 */
/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    THEME_GROUP_SIZE, THEME_CATALOG_TOTAL, THEME_FORMULA_CATEGORIES, THEME_GROUPS_WITHOUT_FORMULA_TERM, THEME_GROUPS_UNRECONCILED, THEME_UNRECONCILED_BONUS_POINTS, THEME_MILESTONE_COUNTS_AS_TOWER, THEME_TOWER_QUANTITY_SHORTFALL_POINTS (+4 more)
 * depends    src/data/themes/bonus-catalog, src/data/themes/catalog, src/knowledge/substrate/schema
 * used by    src/knowledge/compartments/index, src/knowledge/index
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
import {
  listThemeBonusCatalogEntries,
  THEME_CATEGORY_BONUS,
  THEMES,
} from '../../data/themes/bonus-catalog'
import {
  THEME_CATEGORY_DEFINITIONS,
  THEME_PASSIVE_FORMULA,
} from '../../data/themes/catalog'
import type { KnowledgeEdge, KnowledgeNode } from '../substrate/schema'

const CATALOG_THEME_BONUS = {
  origin: 'code',
  ref: 'thetowersdk/data THEMES, THEME_CATEGORY_BONUS',
  verifiedAt: '2026-08-18',
} as const

const CATALOG_THEME_FORMULA = {
  origin: 'code',
  ref: 'thetowersdk/data THEME_CATEGORY_DEFINITIONS, computeThemePassiveCoinBonus',
  verifiedAt: '2026-08-18',
} as const

const WIKI_MILESTONE_THEMES = {
  origin: 'wiki',
  ref: 'Themes/Milestones',
  verifiedAt: '2026-08-18',
} as const

/** The seven groups the bonus catalog lists themes under, with their counts. */
export const THEME_GROUP_SIZE: Readonly<Record<string, number>> = Object.fromEntries(
  Object.entries(THEMES).map(([group, items]) => [group, items.length]),
)

export const THEME_CATALOG_TOTAL = Object.values(THEME_GROUP_SIZE)
  .reduce((sum, count) => sum + count, 0)

/** The four categories the coin formula actually multiplies over. */
export const THEME_FORMULA_CATEGORIES: readonly string[] = THEME_CATEGORY_DEFINITIONS
  .map(category => category.key)

/**
 * Groups the bonus catalog prices but the coin formula has no term for.
 *
 * `MILESTONE` is explained — those themes pay the tower rate and are counted as
 * tower. `SONGS` and `PROFILE_BANNER` are not: each carries a stated rate in
 * `THEME_CATEGORY_BONUS` and there is no corresponding coefficient anywhere in
 * `computeThemePassiveCoinBonus`. Either the formula is short two terms or the
 * catalog prices things that do not pay, and the two shipped tables cannot both
 * be right.
 */
export const THEME_GROUPS_WITHOUT_FORMULA_TERM: readonly string[] = Object.keys(THEMES)
  .filter(group => !THEME_FORMULA_CATEGORIES.includes(group.toLowerCase()))

/** The unexplained ones — the milestone group has a documented home, these do not. */
export const THEME_GROUPS_UNRECONCILED: readonly string[] = THEME_GROUPS_WITHOUT_FORMULA_TERM
  .filter(group => group !== 'MILESTONE')

/** Percentage points of coin bonus the unreconciled groups would be worth if they pay. */
export const THEME_UNRECONCILED_BONUS_POINTS = THEME_GROUPS_UNRECONCILED
  .reduce((sum, group) => {
    const rate = Number.parseFloat(
      String(THEME_CATEGORY_BONUS[group as keyof typeof THEME_CATEGORY_BONUS] ?? '0').replace(/[+%]/g, ''),
    )
    return sum + rate * (THEME_GROUP_SIZE[group] ?? 0)
  }, 0)

/**
 * Milestone themes are a DISJOINT list from tower themes, and pay the tower rate.
 *
 * There is no overlap at all between the two groups by name, so the tower
 * quantity the coin formula wants is `TOWER + MILESTONE`, not the length of the
 * tower group. Feeding it the tower group alone loses every milestone theme —
 * currently 21 of them at 0.4 points each.
 */
export const THEME_MILESTONE_COUNTS_AS_TOWER = true

export const THEME_TOWER_QUANTITY_SHORTFALL_POINTS
  = (THEME_GROUP_SIZE.MILESTONE ?? 0) * 0.4

/**
 * Theme names are not unique across groups.
 *
 * Ten names appear in two groups each — a tower theme and a profile banner of
 * the same name, most of them. `listThemeBonusCatalogEntries()` returns one row
 * per (name, group), so resolving a theme by name alone picks whichever row
 * happens to come first and silently prices it at the wrong rate.
 */
export const THEME_AMBIGUOUS_NAMES: readonly string[] = (() => {
  const seen = new Map<string, number>()
  for (const entry of listThemeBonusCatalogEntries()) {
    seen.set(entry.name, (seen.get(entry.name) ?? 0) + 1)
  }
  return [...seen.entries()].filter(([, count]) => count > 1).map(([name]) => name).sort()
})()

/** Resolve a theme by this pair, never by name alone. */
export const THEME_LOOKUP_KEY = 'name + category' as const

export const THEME_KNOWLEDGE_NODES: readonly KnowledgeNode[] = [
  {
    id: 'theme',
    label: 'Theme',
    kind: 'system',
    claimType: 'objective',
    verification: 'verified_here',
    summary:
      'A cosmetic that pays a passive coin bonus for being OWNED, not for being equipped. The '
      + `catalog holds ${THEME_CATALOG_TOTAL} of them across `
      + `${Object.keys(THEME_GROUP_SIZE).length} groups.`,
    units: 'percentage points of coin bonus per theme owned',
    validRange: THEME_PASSIVE_FORMULA,
    traps: [
      'OWNED, NOT EQUIPPED. Only one theme is displayed at a time and every owned theme still '
      + 'pays. A model that reads the equipped theme and stops has found a cosmetic setting, not '
      + 'the economy input.',
      'The category bonuses are additive with one another and then applied as a SINGLE '
      + 'multiplier. Multiplying the categories together instead compounds a bonus the game adds.',
      'This is a coin bonus, not a coin source. It scales what a run already earns, so it is '
      + 'worth nothing on its own and worth a great deal next to a strong coin build.',
    ],
    implementedBy: [
      'THEME_CATEGORY_DEFINITIONS',
      'computeThemePassiveCoinBonus',
      'THEME_PASSIVE_FORMULA',
      'THEME_GROUP_SIZE',
    ],
    assertions: [
      {
        subject: 'theme',
        predicate: 'catalogTotal',
        value: THEME_CATALOG_TOTAL,
        provenance: CATALOG_THEME_BONUS,
        verification: 'verified_here',
      },
      {
        subject: 'theme',
        predicate: 'paysWhileUnequipped',
        value: true,
        provenance: CATALOG_THEME_FORMULA,
        verification: 'verified_here',
      },
      ...THEME_CATEGORY_DEFINITIONS.map(category => ({
        subject: `theme.${category.key}`,
        predicate: 'coinBonusPointsPerOwned',
        value: category.passiveCoinBonusPerOwnedPercent,
        provenance: CATALOG_THEME_FORMULA,
        verification: 'verified_here' as const,
      })),
    ],
    sources: [CATALOG_THEME_FORMULA, CATALOG_THEME_BONUS],
  },
  {
    id: 'theme.taxonomy',
    label: 'Which theme grouping you are holding',
    kind: 'rule',
    claimType: 'objective',
    verification: 'verified_here',
    summary:
      'Three different groupings of the same themes ship in this package. The bonus catalog has '
      + `${Object.keys(THEME_GROUP_SIZE).length} groups, the coin formula multiplies over `
      + `${THEME_FORMULA_CATEGORIES.length}, and the save stores its own set including songs and `
      + 'profile banners. They are not interchangeable.',
    disambiguation:
      '`ThemeBonusGroup` is the catalog grouping and includes MILESTONE. `ThemeCategoryKey` is the '
      + 'coin formula and does not. `ThemeCatalogCategory` in `save/catalogs/themes.ts` is what a '
      + 'save file stores unlocks under. Counting themes in one and pricing them with another is '
      + 'the mistake this node exists to prevent.',
    traps: [
      'MILESTONE THEMES ARE NOT IN THE TOWER GROUP. The two lists share no name at all, yet '
      + 'milestone themes pay the tower rate and are meant to be counted as tower. So the tower '
      + 'quantity the formula wants is TOWER + MILESTONE. Passing the tower group alone drops '
      + `${THEME_GROUP_SIZE.MILESTONE} themes and ${THEME_TOWER_QUANTITY_SHORTFALL_POINTS} points `
      + 'of coin bonus, and nothing reports the loss.',
      `THEME NAMES REPEAT ACROSS GROUPS. ${THEME_AMBIGUOUS_NAMES.length} names appear twice — `
      + `${THEME_AMBIGUOUS_NAMES.join(', ')} — mostly a tower theme and a profile banner sharing a `
      + `name. Resolve by ${THEME_LOOKUP_KEY}; a name-only lookup takes whichever row is first and `
      + 'prices it at the wrong rate.',
      'The flat list from `listThemeBonusCatalogEntries()` is one row per (name, group), so its '
      + 'length is not a count of distinct themes.',
    ],
    implementedBy: [
      'THEME_GROUP_SIZE',
      'THEME_AMBIGUOUS_NAMES',
      'THEME_MILESTONE_COUNTS_AS_TOWER',
      'THEME_LOOKUP_KEY',
    ],
    assertions: [
      {
        subject: 'theme.taxonomy',
        predicate: 'groupCount',
        value: Object.keys(THEME_GROUP_SIZE).length,
        provenance: CATALOG_THEME_BONUS,
        verification: 'verified_here',
      },
      {
        subject: 'theme.taxonomy',
        predicate: 'formulaCategoryCount',
        value: THEME_FORMULA_CATEGORIES.length,
        provenance: CATALOG_THEME_FORMULA,
        verification: 'verified_here',
      },
      {
        subject: 'theme.taxonomy',
        predicate: 'ambiguousNameCount',
        value: THEME_AMBIGUOUS_NAMES.length,
        provenance: CATALOG_THEME_BONUS,
        verification: 'verified_here',
      },
      {
        subject: 'theme.milestone',
        predicate: 'themeCount',
        value: THEME_GROUP_SIZE.MILESTONE ?? 0,
        provenance: WIKI_MILESTONE_THEMES,
        verification: 'verified_here',
      },
    ],
    sources: [CATALOG_THEME_BONUS, CATALOG_THEME_FORMULA, WIKI_MILESTONE_THEMES],
  },
  {
    id: 'theme.unpricedGroups',
    label: 'Theme groups the coin formula ignores',
    kind: 'rule',
    claimType: 'objective',
    verification: 'unverified',
    summary:
      `${THEME_GROUPS_UNRECONCILED.join(' and ')} carry a stated coin rate in the bonus catalog `
      + 'and have no term in the coin formula. The two shipped tables disagree and this is not '
      + 'resolved.',
    units: 'percentage points of coin bonus',
    disambiguation:
      'Distinct from MILESTONE, which is also absent from the formula but has a documented home: '
      + 'those themes pay the tower rate and count as tower. These two have no such account.',
    traps: [
      `UNRESOLVED, NOT SETTLED. ${THEME_GROUPS_UNRECONCILED.join(' and ')} together are `
      + `${THEME_GROUPS_UNRECONCILED.reduce((sum, group) => sum + (THEME_GROUP_SIZE[group] ?? 0), 0)} `
      + `items at 0.6 points each — up to ${THEME_UNRECONCILED_BONUS_POINTS} points of coin bonus `
      + 'either missing from the formula or wrongly priced in the catalog. Do not quietly pick a '
      + 'side; a tool that adds them overstates by that much if the catalog is wrong, and one '
      + 'that omits them understates by the same if the formula is.',
      'Settling it needs the game or a save with a known song count and an observed coin '
      + 'multiplier. The wiki does not carry theme coin rates at all, so it cannot decide this.',
    ],
    implementedBy: ['THEME_GROUPS_UNRECONCILED', 'THEME_UNRECONCILED_BONUS_POINTS'],
    assertions: [
      {
        subject: 'theme.unpricedGroups',
        predicate: 'unreconciledGroupCount',
        value: THEME_GROUPS_UNRECONCILED.length,
        provenance: CATALOG_THEME_BONUS,
        verification: 'unverified',
      },
      {
        subject: 'theme.unpricedGroups',
        predicate: 'unreconciledBonusPoints',
        value: THEME_UNRECONCILED_BONUS_POINTS,
        provenance: CATALOG_THEME_BONUS,
        verification: 'unverified',
      },
    ],
    sources: [CATALOG_THEME_BONUS, CATALOG_THEME_FORMULA],
  },
]

export const THEME_KNOWLEDGE_EDGES: readonly KnowledgeEdge[] = [
  {
    from: 'theme',
    kind: 'scales',
    to: 'coinsPerKill',
    note:
      'A flat multiplier on coins earned, paid for owning rather than equipping. It multiplies an '
      + 'existing coin build and does nothing without one.',
    sources: [CATALOG_THEME_FORMULA],
  },
  {
    from: 'theme.taxonomy',
    kind: 'memberOf',
    to: 'theme',
    note:
      'Which grouping a theme count came from decides whether the coin formula can use it at all.',
    sources: [CATALOG_THEME_BONUS],
  },
  {
    from: 'theme.unpricedGroups',
    kind: 'memberOf',
    to: 'theme.taxonomy',
    note: 'The part of the taxonomy split that is a disagreement rather than a mapping.',
    sources: [CATALOG_THEME_BONUS],
  },
]
