/**
 * Ultimate Weapon Enhancements (UW+).
 *
 * Every ultimate weapon has a second, named ability bought separately with
 * stones. The community writes them as `GT+`, `BH+`, `DW+` and so on, and an
 * agent that reads `GT+` as "a bigger Golden Tower" will model it wrongly —
 * these are distinct mechanics, and several of them do something the base
 * weapon does not do at all.
 *
 * The clearest example, and one this repo has already got wrong: **GT+ is
 * Golden Combo, an economy mechanic.** It counts kills during Golden Tower and
 * pays extra cash and coins when the window ends, scaled by a POWER of the combo
 * count rather than a flat percent per combo. Nothing about it
 * is damage, duration or cooldown. A resource calculation that treats it as a
 * generic Golden Tower multiplier misses both the kill-count dependency and
 * the fact that it pays out at the END of the window.
 */
/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    UW_PLUS_ABILITIES, UW_PLUS_SHORTHAND, UW_PLUS_UNLOCK_STONE_COST, UW_PLUS_UNLOCK_TOTAL_STONES, UW_PLUS_MAX_TIER, UW_PLUS_KNOWLEDGE_NODES, UW_PLUS_KNOWLEDGE_EDGES
 * depends    src/knowledge/compartments/ultimate-weapons, src/knowledge/substrate/schema, src/mechanics/golden-combo
 * used by    src/knowledge/compartments/index, src/knowledge/index
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
import { ULTIMATE_WEAPON_STATS } from './ultimate-weapons'
import type { KnowledgeEdge, KnowledgeNode } from '../substrate/schema'
import {
  GOLDEN_COMBO_BENEFIT_INDEX,
  GOLDEN_COMBO_MIN_BENEFIT_LENGTH,
  goldenComboMultiplier,
} from '../../mechanics/golden-combo'

/**
 * What corrected Golden Combo from linear to exponential.
 *
 * The reward compounds per stack rather than adding a fixed amount, which a
 * linear model understates badly at high stack counts.
 */
const GAME_GOLDEN_COMBO = {
  origin: 'game',
  ref: 'Observed in game',
  sourceVersion: 'v28.3.0',
  verifiedAt: '2026-08-18',
} as const

const SITE_DATA = {
  origin: 'code',
  ref: 'UW+ upgrade tables',
  sourceVersion: 'v28.3',
  verifiedAt: '2026-08-17',
} as const

/**
 * The named enhancement for each weapon, and what it actually does.
 *
 * The name is not decorative — `GT+` and `Golden Combo` are the same thing and
 * a player will use either.
 */
export const UW_PLUS_ABILITIES: Readonly<Record<string, { name: string, effect: string }>> = {
  'Chain Lightning': {
    name: 'Smite',
    effect: 'each hit has a chance to deal extra damage as a % of current wave HP, capped at '
      + '100 hits per enemy',
  },
  'Smart Missiles': {
    name: 'Cover Fire',
    effect: 'launches an additional Smart Missile every X seconds',
  },
  'Poison Swamp': {
    name: 'Death Creep',
    effect: 'a damage multiplier on the swamp',
  },
  'Golden Tower': {
    name: 'Golden Combo',
    effect: 'a combo counter runs while Golden Tower is active, +1 per enemy kill; when the '
      + 'window ends it pays extra cash and coins of X% PER COMBO',
  },
  'Inner Land Mines': {
    name: 'Charged Mines',
    effect: 'mines charge over time at a rate per second',
  },
  'Death Wave': {
    name: 'Kill Wall',
    effect: 'each Effect Wave hit amplifies the Death Wave damage store ADDITIVELY',
  },
  'Black Hole': {
    name: 'Consume',
    effect: 'deals a % of current wave HP to every affected enemy at the END of its activation',
  },
  'Chrono Field': {
    name: 'Chrono Loop',
    effect: 'affected enemies spiral toward the tower at a rotation rate',
  },
  'Spotlight': {
    name: 'Light Range',
    effect: 'the spotlight damage bonus is boosted by a multiple of damage/meter',
  },
}

/** Community shorthand → weapon. `GT+` is what a player will actually type. */
export const UW_PLUS_SHORTHAND: Readonly<Record<string, string>> = {
  'cl+': 'Chain Lightning',
  'sm+': 'Smart Missiles',
  'ps+': 'Poison Swamp',
  'gt+': 'Golden Tower',
  'ilm+': 'Inner Land Mines',
  'dw+': 'Death Wave',
  'bh+': 'Black Hole',
  'cf+': 'Chrono Field',
  'sl+': 'Spotlight',
}

/**
 * Stone cost to unlock the Nth enhancement, indexed by how many are already
 * owned. Positional, exactly like the weapons themselves.
 */
export const UW_PLUS_UNLOCK_STONE_COST = [500, 625, 750, 975, 1250, 1650, 2200, 2900, 3800] as const

/** Unlocking all nine. */
export const UW_PLUS_UNLOCK_TOTAL_STONES = 14_650

/** Each enhancement then upgrades across 15 tiers above its unlock tier. */
export const UW_PLUS_MAX_TIER = 15

/** The weapon names the ultimate-weapon compartment ships, for the join below. */
const CATALOG_UW_NAMES = {
  origin: 'code',
  ref: 'thetowersdk/knowledge ULTIMATE_WEAPON_STATS',
  verifiedAt: '2026-08-18',
} as const

const UW_CATALOG_WEAPON_NAMES = new Set(Object.keys(ULTIMATE_WEAPON_STATS))

/**
 * A node per enhancement, generated from the table above.
 *
 * Generated rather than hand-written for a reason discovered the hard way:
 * `GT+` was wired by hand and resolved correctly, while every other `X+`
 * resolved to something unrelated — `DW+` to the wall, `BH+` to a sub-module
 * effect, `SM+` to a milestone. One correct entry hid eight wrong ones,
 * because the resolver always returns its best guess and never admits it is
 * guessing.
 *
 * Generating them means the graph cannot know one member of a family and be
 * blind to the rest.
 */
function buildAbilityNodes(): KnowledgeNode[] {
  const shorthandFor = (weapon: string) =>
    Object.entries(UW_PLUS_SHORTHAND).find(([, w]) => w === weapon)?.[0] ?? ''

  return Object.entries(UW_PLUS_ABILITIES)
    // Golden Combo is written out in full below; it is the one with a history.
    .filter(([weapon]) => weapon !== 'Golden Tower')
    .map(([weapon, ability]) => {
      const short = shorthandFor(weapon)
      const id = `ultimateWeaponPlus.${ability.name.replace(/\s+/g, '')}`
      return {
        id: id.charAt(0).toLowerCase() + id.slice(1),
        /*
         * Weapon first, deliberately. `scoreNode` matches a label against the
         * query by containment and scores by label length, so "Smite (CL+)"
         * (bare label "smite") loses to a node labelled "Chain Lightning" for
         * the query "Chain Lightning - Smite (UW+)" — which is exactly what
         * happened when the per-weapon nodes were first added.
         *
         * Naming the weapon here makes the ability's label the LONGER and more
         * specific of the two, so it wins the compound query while the weapon
         * still wins its own bare name. The label also matches how the community
         * writes it.
         */
        label: `${weapon} - ${ability.name} (${short.toUpperCase()})`,
        kind: 'entity' as const,
        claimType: 'objective' as const,
        verification: 'verified_here' as const,
        summary:
          `${weapon}'s enhancement, called ${ability.name}. It ${ability.effect}. Unlocked and `
          + 'upgraded with stones separately from the weapon itself, across 15 tiers.',
        disambiguation:
          `NOT a stronger ${weapon}. \`${short.toUpperCase()}\` means ${ability.name} — a `
          + `distinct mechanic — not "${weapon}, upgraded". ${weapon}'s own three stats are a `
          + 'different purchase on a different ladder.',
        units: 'stones; tier 0-15',
        traps: [
          `A player writing \`${short.toUpperCase()}\` means ${ability.name}, not the weapon. `
          + 'Resolve the shorthand before assuming which mechanic is meant.',
          'Bought from the same stone pool as weapons, assist rarity and assist efficiency — so '
          + 'it competes with all of them.',
          'THE UNLOCK COST IS POSITIONAL, not per-ability. The ladder runs '
          + `${UW_PLUS_UNLOCK_STONE_COST[0]} to `
          + `${UW_PLUS_UNLOCK_STONE_COST[UW_PLUS_UNLOCK_STONE_COST.length - 1]} stones by how many `
          + `you already own, so ${ability.name} has no fixed price — quoting one is quoting the `
          + 'order it was bought in.',
        ],
        implementedBy: ['UW_PLUS_ABILITIES', 'UW_PLUS_SHORTHAND'],
        assertions: [
          { subject: id.charAt(0).toLowerCase() + id.slice(1), predicate: 'weapon', value: weapon, provenance: SITE_DATA },
          { subject: id.charAt(0).toLowerCase() + id.slice(1), predicate: 'shorthand', value: short.toUpperCase(), provenance: SITE_DATA },
          { subject: id.charAt(0).toLowerCase() + id.slice(1), predicate: 'maxTier', value: UW_PLUS_MAX_TIER, provenance: SITE_DATA },
          // The join. Every ability must name a weapon the UW compartment also
          // knows, or the two halves of the same system describe different sets
          // and nothing says so.
          { subject: id.charAt(0).toLowerCase() + id.slice(1), predicate: 'weaponIsInTheUltimateWeaponCatalog', value: UW_CATALOG_WEAPON_NAMES.has(weapon), provenance: CATALOG_UW_NAMES, verification: 'verified_here' as const },
        ],
        sources: [SITE_DATA, CATALOG_UW_NAMES],
      }
    })
}

const ABILITY_NODES = buildAbilityNodes()

export const UW_PLUS_KNOWLEDGE_NODES: readonly KnowledgeNode[] = [
  ...ABILITY_NODES,
  {
    id: 'ultimateWeaponPlus',
    label: 'Ultimate Weapon Enhancement (UW+)',
    kind: 'system',
    claimType: 'objective',
    verification: 'verified_here',
    summary:
      'A second named ability attached to each ultimate weapon, unlocked and upgraded with '
      + 'stones separately from the weapon itself. Nine exist, one per weapon, each with 15 '
      + 'upgrade tiers above its unlock.',
    disambiguation:
      'NOT a stronger version of the weapon. Each is a distinct mechanic with its own name — '
      + 'Golden Combo, Smite, Kill Wall, Consume — and several do something the base weapon does '
      + 'not do at all. `GT+` does not make Golden Tower bigger; it adds a kill-combo payout. '
      + 'Also not the same as a weapon\'s three upgradable stats, which are bought on a different '
      + 'ladder.',
    units: 'stones to unlock and upgrade; tier 0-15',
    validRange:
      'Nine enhancements, one per weapon. Unlock cost is positional (500 → 3,800 by how many are '
      + 'already owned, 14,650 for all nine). Tiers 0-15 per enhancement.',
    implementedBy: ['UW_PLUS_ABILITIES', 'UW_PLUS_SHORTHAND', 'UW_PLUS_UNLOCK_STONE_COST'],
    traps: [
      'The community shorthand is `GT+`, `BH+`, `DW+`. Anyone saying "GT+" means Golden Combo, '
      + 'not "Golden Tower, upgraded". Resolve the shorthand before assuming a stat.',
      'Unlock cost is POSITIONAL — it depends on how many enhancements are already owned, not on '
      + 'which weapon. Same shape as ultimate weapon purchases.',
      'These compete for the SAME stone pool as ultimate weapons, assist rarity and assist '
      + 'efficiency. 14,650 stones for the unlocks alone, before a single upgrade tier.',
      'They are separate from the weapon\'s own three stats. A weapon can be fully upgraded with '
      + 'its enhancement unbought, and vice versa.',
    ],
    assertions: [
      {
        subject: 'ultimateWeaponPlus',
        predicate: 'unlockTotalStones',
        value: UW_PLUS_UNLOCK_TOTAL_STONES,
        provenance: SITE_DATA,
        verification: 'verified_here',
      },
      {
        subject: 'ultimateWeaponPlus',
        predicate: 'count',
        value: 9,
        provenance: SITE_DATA,
        verification: 'verified_here',
      },
      { subject: 'ultimateWeaponPlus', predicate: 'maxTier', value: UW_PLUS_MAX_TIER, provenance: SITE_DATA },
      { subject: 'ultimateWeaponPlus', predicate: 'minTier', value: 0, provenance: SITE_DATA },
      { subject: 'ultimateWeaponPlus', predicate: 'firstUnlockStoneCost', value: UW_PLUS_UNLOCK_STONE_COST[0], provenance: SITE_DATA },
      { subject: 'ultimateWeaponPlus', predicate: 'ninthUnlockStoneCost', value: UW_PLUS_UNLOCK_STONE_COST[8], provenance: SITE_DATA },
      { subject: 'ultimateWeaponPlus', predicate: 'unlockCostIsPositional', value: true, provenance: SITE_DATA },
      { subject: 'ultimateWeaponPlus', predicate: 'shorthandCount', value: Object.keys(UW_PLUS_SHORTHAND).length, provenance: SITE_DATA },
      { subject: 'ultimateWeaponPlus', predicate: 'abilityCount', value: Object.keys(UW_PLUS_ABILITIES).length, provenance: SITE_DATA },
      {
        subject: 'ultimateWeaponPlus',
        predicate: 'unlockCostRelativeToWeapons',
        value: Number((UW_PLUS_UNLOCK_TOTAL_STONES / 9705).toFixed(2)),
        provenance: SITE_DATA,
      },
    ],
    sources: [SITE_DATA],
  },
  {
    id: 'ultimateWeaponPlus.naming',
    label: 'A UW+ shorthand names the weapon, not the ability',
    kind: 'rule',
    claimType: 'objective',
    verification: 'verified_here',
    summary:
      'The nine shorthands — `gt+`, `bh+`, `dw+` and the rest — are keyed by WEAPON name, while '
      + 'the thing they refer to is the ability: `gt+` is Golden Tower\'s enhancement, whose name '
      + 'is Golden Combo. Two vocabularies, one for each end of the same relation.',
    disambiguation:
      'UW_PLUS_SHORTHAND maps shorthand to weapon. UW_PLUS_ABILITIES and ULTIMATE_WEAPON_PLUS_STAT '
      + 'map to the ability. Neither maps shorthand directly to ability — that needs both.',
    traps: [
      'Resolving `gt+` gives you "Golden Tower", which is a weapon that also exists in its own '
      + 'right. Using that answer directly attaches the query to the base weapon and loses the '
      + 'enhancement entirely — the exact mis-resolution oracle-vocabulary.parity.test.ts pins.',
      'The ability names appear in two tables — UW_PLUS_ABILITIES here and ULTIMATE_WEAPON_PLUS_STAT '
      + 'in the ultimate-weapons compartment. Verified identical as sets on 2026-08-17; if they '
      + 'ever diverge, one of them is describing a weapon the game no longer has.',
      'A weapon has three upgradable stats AND an enhancement. The catalog lists four stats per '
      + 'weapon because the fourth IS the enhancement, so counting catalog stats to count '
      + 'upgradable stats overcounts by exactly one on every weapon.',
    ],
    implementedBy: ['UW_PLUS_SHORTHAND', 'UW_PLUS_ABILITIES', 'ULTIMATE_WEAPON_PLUS_STAT'],
    assertions: [
      { subject: 'ultimateWeaponPlus.naming', predicate: 'shorthandKeyedBy', value: 'weapon', provenance: SITE_DATA },
      { subject: 'ultimateWeaponPlus.naming', predicate: 'abilityTableCount', value: 2, provenance: SITE_DATA },
      { subject: 'ultimateWeaponPlus.naming', predicate: 'abilityTablesAgree', value: true, provenance: SITE_DATA },
      { subject: 'ultimateWeaponPlus.naming', predicate: 'catalogStatsPerWeapon', value: 4, provenance: SITE_DATA },
      { subject: 'ultimateWeaponPlus.naming', predicate: 'upgradableStatsPerWeapon', value: 3, provenance: SITE_DATA },
    ],
    sources: [SITE_DATA],
  },
  {
    id: 'ultimateWeaponPlus.goldenCombo',
    label: 'Golden Tower - Golden Combo (GT+)',
    kind: 'entity',
    claimType: 'objective',
    verification: 'verified_here',
    summary:
      'Golden Tower\'s enhancement. While Golden Tower is active a combo counter increments by 1 '
      + 'per enemy killed; when the window ends it pays extra cash and coins scaled by '
      + '`ultimateWeaponPlusBenefit[5] ^ combo - 1` — a POWER of the combo count, not a flat '
      + 'percent per combo.',
    disambiguation:
      'An ECONOMY mechanic, not a damage or duration one. It does not extend Golden Tower, raise '
      + 'its bonus multiplier, or change its cooldown. It converts KILLS DURING the window into '
      + 'extra payout AFTER it. Modelling it as another Golden Tower coin multiplier loses both '
      + 'the kill-count dependency and the timing.',
    units: 'multiplier, exponential in the combo count',
    validRange:
      'Combo 0 pays nothing (the formula subtracts 1); the multiplier then grows as a power of '
      + 'the combo count. 15 upgrade tiers raise the base.',
    traps: [
      'IT SCALES WITH KILL COUNT, not with time or with Golden Tower\'s own bonus. A build that '
      + 'kills faster during the window earns more from it — so it interacts with damage, attack '
      + 'speed and enemy density rather than with coin bonuses.',
      'The payout lands when the window ENDS, not continuously. Anything modelling coins per '
      + 'second during Golden Tower will place this income in the wrong place.',
      'This repo has already modelled it wrongly once, in a resource-drops calculation. Check '
      + 'what GT+ is before using it in any coin maths.',
      'IT IS EXPONENTIAL IN THE COMBO, NOT LINEAR. `HandleGoldenTowerPlusReward` computes '
      + '`powf(ultimateWeaponPlusBenefit[5], combo) - 1` and multiplies the cash and coin bonuses '
      + 'by that. The "percent per combo" reading this node carried until 2026-08-18 agrees '
      + 'closely at low combos and diverges badly at high ones — at base 1.05 and combo 50 the '
      + 'true multiplier is about 10.5x where linear gives 2.5x. The two agreeing early is exactly '
      + 'why the wrong reading survived.',
      'THE POWER IS COMPUTED IN FLOAT32 while every accumulator it feeds is a double: the code '
      + 'converts down, calls `powf`, and converts back up. A float64 model drifts from the game '
      + 'at large combos, in the last digits where nobody looks.',
      'CASH AND COINS SHARE THE MULTIPLIER BUT NOT THE BONUS. `goldenTowerPlusCashBonus` and '
      + '`goldenTowerPlusCoinsBonus` are separate fields, so the two payouts are not a fixed ratio '
      + 'of each other and neither can be derived from the other.',
      'THE PAYOUT IS SKIPPED ENTIRELY IF `ultimateWeaponPlusBenefit` HAS SIX OR FEWER ENTRIES. '
      + 'The method length-checks the array before reading index 5 and returns. An account without '
      + 'that benefit populated earns nothing here, which reads as "GT+ is weak" rather than as '
      + '"GT+ never fired".',
      'IT IS THE ONLY UW+ ABILITY THAT PAYS CURRENCY. The other '
      + `${Object.keys(UW_PLUS_ABILITIES).length - 1} change combat behaviour, so a rule learned `
      + 'from any of them — "UW+ makes the weapon hit harder" — is false for exactly this one, and '
      + 'this one is the one that matters to an economy model.',
    ],
    implementedBy: ['UW_PLUS_ABILITIES', 'UW_PLUS_SHORTHAND', 'goldenComboPayout'],
    assertions: [
      { subject: 'ultimateWeaponPlus.goldenCombo', predicate: 'weapon', value: 'Golden Tower', provenance: SITE_DATA },
      { subject: 'ultimateWeaponPlus.goldenCombo', predicate: 'shorthand', value: 'GT+', provenance: SITE_DATA },
      { subject: 'ultimateWeaponPlus.goldenCombo', predicate: 'maxTier', value: UW_PLUS_MAX_TIER, provenance: SITE_DATA },
      { subject: 'ultimateWeaponPlus.goldenCombo', predicate: 'benefitArrayIndex', value: GOLDEN_COMBO_BENEFIT_INDEX, provenance: GAME_GOLDEN_COMBO, verification: 'verified_here' as const },
      { subject: 'ultimateWeaponPlus.goldenCombo', predicate: 'minBenefitArrayLength', value: GOLDEN_COMBO_MIN_BENEFIT_LENGTH, provenance: GAME_GOLDEN_COMBO, verification: 'verified_here' as const },
      { subject: 'ultimateWeaponPlus.goldenCombo', predicate: 'multiplierIsExponentialInCombo', value: true, provenance: GAME_GOLDEN_COMBO, verification: 'verified_here' as const },
      { subject: 'ultimateWeaponPlus.goldenCombo', predicate: 'multiplierComputedInFloat32', value: true, provenance: GAME_GOLDEN_COMBO, verification: 'verified_here' as const },
      { subject: 'ultimateWeaponPlus.goldenCombo', predicate: 'cashAndCoinsUseSeparateBonusFields', value: true, provenance: GAME_GOLDEN_COMBO, verification: 'verified_here' as const },
      { subject: 'ultimateWeaponPlus.goldenCombo', predicate: 'multiplierAtComboZero', value: goldenComboMultiplier(1.05, 0), provenance: GAME_GOLDEN_COMBO, verification: 'verified_here' as const },
      { subject: 'ultimateWeaponPlus.goldenCombo', predicate: 'scalesWithKillCount', value: true, provenance: SITE_DATA },
      { subject: 'ultimateWeaponPlus.goldenCombo', predicate: 'paysOnWindowEnd', value: true, provenance: SITE_DATA },
      { subject: 'ultimateWeaponPlus.goldenCombo', predicate: 'weaponIsInTheUltimateWeaponCatalog', value: UW_CATALOG_WEAPON_NAMES.has('Golden Tower'), provenance: CATALOG_UW_NAMES, verification: 'verified_here' as const },
    ],
    sources: [SITE_DATA, CATALOG_UW_NAMES, GAME_GOLDEN_COMBO],
  },
]

/** Every generated ability belongs to the family, so none is left an orphan. */
const ABILITY_EDGES: KnowledgeEdge[] = ABILITY_NODES.map(node => ({
  from: node.id,
  kind: 'memberOf' as const,
  to: 'ultimateWeaponPlus',
  note:
    'One of the nine ultimate weapon enhancements — a distinct named mechanic, not an upgrade '
    + 'to the weapon it attaches to.',
  sources: [SITE_DATA],
}))

export const UW_PLUS_KNOWLEDGE_EDGES: readonly KnowledgeEdge[] = [
  ...ABILITY_EDGES,
  {
    from: 'ultimateWeaponPlus.naming',
    kind: 'memberOf',
    to: 'ultimateWeaponPlus',
    note:
      'Which vocabulary names which end: the shorthand keys the weapon, the ability tables key '
      + 'the enhancement, and resolving one to the other needs both.',
    sources: [SITE_DATA],
  },
  {
    from: 'ultimateWeaponPlus',
    kind: 'derivedFrom',
    to: 'ultimateWeapon',
    note:
      'One enhancement per weapon, bought separately — a weapon can be maxed with its '
      + 'enhancement unbought and vice versa.',
    sources: [SITE_DATA],
  },
  {
    from: 'ultimateWeaponPlus.goldenCombo',
    kind: 'memberOf',
    to: 'ultimateWeaponPlus',
    note: 'Golden Tower\'s enhancement, and the one most often misread as a damage upgrade.',
    sources: [SITE_DATA],
  },
  {
    from: 'ultimateWeaponPlus.goldenCombo',
    kind: 'scales',
    to: 'coinsPerKill',
    note:
      'Pays extra cash and coins as a POWER of the combo, where combo counts kills during the '
      + 'Golden Tower window — so it belongs in coin income, not in weapon damage, and its share '
      + 'of income grows faster than kill count does.',
    sources: [SITE_DATA, GAME_GOLDEN_COMBO],
  },
  {
    from: 'ultimateWeaponPlus',
    kind: 'separatePurchaseFrom',
    to: 'assistModule.efficiency',
    note:
      'Both draw on the same stone pool. 14,650 stones for UW+ unlocks alone competes directly '
      + 'with assist efficiency ladders and weapon purchases.',
    sources: [SITE_DATA],
  },
]
