/**
 * The Vault and its tech trees, as the game defines them.
 *
 * Read off the wiki on 2026-08-16 (The Vault, Currency/Keys).
 *
 * The Vault is the most commonly over-assumed system in a planner, because its
 * nodes read like ordinary upgrades and are not: every one costs keys, keys
 * come only from a top-15 placement in Legend league, and the Vault is not even
 * visible until the player is promoted there. For most accounts, every number
 * in this file is unreachable.
 */
/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    VAULT_POWER_TIER1_KEY_COST, VAULT_POWER_ALL_TIERS_KEY_COST, VAULT_POWER_TIER_KEY_MULTIPLE, VAULT_POWER_TIER_UNLOCK_REQUIREMENTS, VAULT_SINGLE_LEVEL_POWER_NODES, VAULT_KNOWLEDGE_NODES, VAULT_KNOWLEDGE_EDGES
 * depends    src/data/vault-tree, src/knowledge/substrate/schema
 * used by    src/knowledge/compartments/index, src/knowledge/index
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
import {
  DEFAULT_HARMONY_VAULT_NODES,
  DEFAULT_POWER_VAULT_NODES,
  HARMONY_VAULT_TREE,
  POWER_VAULT_TREE,
} from '../../data/vault-tree'
import type { KnowledgeEdge, KnowledgeNode } from '../substrate/schema'

const WIKI_VAULT = { origin: 'wiki', ref: 'The Vault', verifiedAt: '2026-08-16' } as const

/** Read from the shipped tree rather than transcribed, so it cannot drift. */
/**
 * The vault tree sizes, declared as constants in the game.
 *
 *   POWER_TREE_NODE_COUNT   = 46
 *   HARMONY_TREE_NODE_COUNT = 48
 *
 * Both match the shipped catalog exactly. That is the useful part: the catalog
 * is built by extraction and the constants are declared by hand in the game, so
 * agreement between them is two independent statements of one fact rather than
 * a number checked against itself. If they ever diverge, the catalog has drifted
 * from the build it was extracted from.
 */
const GAME_VAULT_CONSTANTS = {
  origin: 'game',
  ref: 'POWER_TREE_NODE_COUNT, HARMONY_TREE_NODE_COUNT',
  sourceVersion: 'v28.3.0',
  verifiedAt: '2026-08-20',
} as const

const CATALOG_VAULT = {
  origin: 'code',
  ref: 'thetowersdk/data vault-tree',
  verifiedAt: '2026-08-17',
} as const

type VaultNode = { readonly id: string, readonly name: string, readonly cost: number | readonly number[] }

const POWER_NODES = DEFAULT_POWER_VAULT_NODES as readonly VaultNode[]
const HARMONY_NODES = DEFAULT_HARMONY_VAULT_NODES as readonly VaultNode[]

/** Power-tree entries that gate the higher tiers instead of granting a stat. */
const POWER_GATE_NODES = POWER_NODES.filter(node => /Tier x/.test(node.name))

const POWER_TIERED_NODES = POWER_NODES.filter(node => Array.isArray(node.cost))
const POWER_SINGLE_LEVEL_NODES = POWER_NODES.filter(
  node => typeof node.cost === 'number' && !/Tier x/.test(node.name),
)

function sumAllTiers(nodes: readonly VaultNode[]): number {
  return nodes.reduce(
    (total, node) =>
      total + (Array.isArray(node.cost) ? node.cost.reduce((a, b) => a + b, 0) : (node.cost as number)),
    0,
  )
}

function sumFirstTier(nodes: readonly VaultNode[]): number {
  return nodes.reduce(
    (total, node) => total + (Array.isArray(node.cost) ? node.cost[0] : (node.cost as number)),
    0,
  )
}

/**
 * Keys to buy every Power node at tier 1 only.
 *
 * `POWER_VAULT_TREE.totalKeyCost` is the all-tiers figure. Reading that as "what
 * it costs to open the tree" overstates it by 4.75x, which is the kind of wrong
 * that still looks like a plausible number.
 */
export const VAULT_POWER_TIER1_KEY_COST = sumFirstTier(POWER_NODES)

/** Keys to buy every Power node at every tier — equals `POWER_VAULT_TREE.totalKeyCost`. */
export const VAULT_POWER_ALL_TIERS_KEY_COST = sumAllTiers(POWER_NODES)

/** Key-cost multiple for each tier of a Power tree node, relative to tier 1. */
export const VAULT_POWER_TIER_KEY_MULTIPLE = { tier1: 1, tier2: 2, tier3: 4 } as const

/** Tier-1 nodes owned before higher tiers unlock. */
export const VAULT_POWER_TIER_UNLOCK_REQUIREMENTS = {
  tier2: { tier1Nodes: 15 },
  tier3: { tier1Nodes: 30, tier2Nodes: 15 },
} as const

/** Power tree nodes that have only one level, so no tier 2 or 3 exists for them. */
export const VAULT_SINGLE_LEVEL_POWER_NODES = [
  'Ultimate Weapon Damage (All)',
  'Bot Range (All)',
  'Wall Rebuild',
  'Shockwave Frequency',
  'Orbs',
] as const

export const VAULT_KNOWLEDGE_NODES: readonly KnowledgeNode[] = [
  {
    id: 'vault',
    label: 'The Vault',
    kind: 'system',
    summary:
      'Two key-purchased tech trees — Power for tower buffs, Harmony for non-tower and '
      + 'quality-of-life. Upgrades start at the bottom of each tree and branch upward.',
    traps: [
      'The Vault is not even VISIBLE until the player is promoted into Legend league. It is not a '
      + 'late-game system so much as a top-league one, and most accounts can never open it.',
      'Every node costs keys, and keys have exactly one source. Vault progress is bounded by '
      + 'tournament placement, not by play time or run quality.',
      'Nodes must be unlocked in tree order. An isolated node cannot be bought because it is '
      + 'affordable.',
    ],
    implementedBy: ['VAULT_POWER_TIER_KEY_MULTIPLE', 'VAULT_POWER_ALL_TIERS_KEY_COST'],
    assertions: [
      { subject: 'vault', predicate: 'powerTierCount', value: Object.keys(VAULT_POWER_TIER_KEY_MULTIPLE).length, provenance: CATALOG_VAULT, verification: 'verified_here' as const },
      { subject: 'vault', predicate: 'keysForEveryPowerTier', value: VAULT_POWER_ALL_TIERS_KEY_COST, provenance: CATALOG_VAULT },
      // Per tier, because the multiple is a per-tier value. Collapsing three
      // numbers into one predicate would make the tier-3 cost invisible.
      ...Object.entries(VAULT_POWER_TIER_KEY_MULTIPLE).map(([tier, multiple]) => ({
        subject: `vault.power.${tier}`,
        predicate: 'keyCostMultiple',
        value: multiple,
        provenance: CATALOG_VAULT,
        verification: 'verified_here' as const,
      })),
    ],
    // Listed because this node's own assertions read the shipped vault tree.
    sources: [WIKI_VAULT, CATALOG_VAULT],
  },
  {
    id: 'vault.powerTree',
    label: 'Power tree',
    kind: 'system',
    summary:
      'Tower-affecting vault nodes. Most have three tiers: tier 2 costs double the keys of tier 1 '
      + 'and tier 3 quadruple. Tier 2 unlocks at 15 tier-1 nodes; tier 3 at 30 tier-1 and 15 tier-2.',
    traps: [
      'Tier cost is 1× / 2× / 4×, and the higher tiers are gated on node COUNT, not on any single '
      + 'node. Buying a third tier early is impossible however many keys are held.',
      'Five nodes have only ONE level — Ultimate Weapon Damage (All), Bot Range (All), Wall '
      + 'Rebuild, Shockwave Frequency and Orbs. Assuming three tiers everywhere invents upgrades '
      + 'that do not exist.',
      `The wiki counts FIVE single-level upgrades; the catalog holds ${POWER_SINGLE_LEVEL_NODES.length} single-level nodes. `
      + 'Both are right. Ultimate Weapon Damage and Bot Range each occupy four separate nodes '
      + '(one per branch), so five upgrades become eleven entries. Treating this as a '
      + 'disagreement and "fixing" either side breaks the one that was correct.',
    ],
    disambiguation:
      'Counts here are of upgrades as the wiki names them. For counts of catalog ENTRIES, and for '
      + 'how tiers are stored, see vault.treeEncoding.',
    assertions: [
      { subject: 'vault.powerTree', predicate: 'singleLevelUpgradeCount', value: 5, provenance: WIKI_VAULT },
      { subject: 'vault.powerTree', predicate: 'tierKeyMultiples', value: '1/2/4', provenance: WIKI_VAULT },
    ],
    sources: [{ ...WIKI_VAULT, section: 'The Vault' }],
  },
  {
    id: 'vault.harmonyTree',
    label: 'Harmony tree',
    kind: 'system',
    summary:
      'Non-tower vault nodes: automations (Demon Mode, Nuke, Missile Barrage), workshop and bot '
      + 'presets, ad-gem stacking, auto-restart, auto-shatter, and the card-slot upgrades beyond 22.',
    traps: [
      'Harmony nodes change what is POSSIBLE, not just what is bigger — Smart Demon Mode and Smart '
      + 'Nuke Automation insert themselves into the death-prevention chain, and Bot Presets removes '
      + 'the once-per-event bot respec limit entirely.',
      'Auto Charge Berserker adds 0.1% of enemy damage to Berserker on kill, which changes '
      + 'Berserker from a damage-taken mechanic into partly a damage-dealt one.',
      'Some nodes have prerequisites within the tree — Daily Mission Set Shard Type requires Free '
      + 'Mission Reroll first.',
    ],
    assertions: [
      { subject: 'vault.harmonyTree', predicate: 'upgradesBranchUpward', value: true, provenance: WIKI_VAULT },
      // Single-level nodes cannot be part-bought, so any per-level cost model
      // is wrong for them specifically.
      { subject: 'vault.harmonyTree', predicate: 'singleLevelNodeCount', value: VAULT_SINGLE_LEVEL_POWER_NODES.length, provenance: CATALOG_VAULT, verification: 'verified_here' as const },
    ],
    sources: [{ ...WIKI_VAULT, section: 'Harmony Tree' }, CATALOG_VAULT],
  },
  {
    id: 'vault.treeEncoding',
    label: 'How the vault trees encode repeated levels',
    kind: 'rule',
    claimType: 'objective',
    verification: 'verified_here',
    summary:
      'The two trees encode the same idea in opposite ways. A Power node holds all its tiers in a '
      + `\`cost\` ARRAY — ${POWER_TIERED_NODES.length} of ${POWER_NODES.length} nodes do, every one exactly 1x / 2x / 4x over three `
      + 'entries. A Harmony node always has a scalar `cost`, and repeated levels are repeated NODES '
      + `sharing a name: ${HARMONY_NODES.length} nodes carry only ${new Set(HARMONY_NODES.map(node => node.name)).size} distinct names.`,
    disambiguation:
      'This is about the shipped catalog\'s shape, not about what the game shows the player. Both '
      + 'trees present tiers identically in-game.',
    traps: [
      '`cost` is `number | number[]`, and which one you get depends on the tree. Code that sums '
      + '`node.cost` reads a number from Harmony and string-concatenates or NaNs on Power.',
      `The 1x / 2x / 4x tier rule is POWER-ONLY. All ${HARMONY_NODES.length} Harmony nodes are single-level; applying `
      + 'tier multiples there invents costs that do not exist.',
      `\`POWER_VAULT_TREE.totalKeyCost\` (${VAULT_POWER_ALL_TIERS_KEY_COST}) counts every tier. Opening every Power node at `
      + `tier 1 costs ${VAULT_POWER_TIER1_KEY_COST}. Using the former as an entry price is ${(VAULT_POWER_ALL_TIERS_KEY_COST / VAULT_POWER_TIER1_KEY_COST).toFixed(2)}x too high.`,
      `Two Power entries — ${POWER_GATE_NODES.map(node => node.id).join(' and ')} — are tier-unlock GATES, not upgrades. `
      + 'Counting nodes to count upgrades overcounts by two.',
    ],
    implementedBy: [
      'POWER_VAULT_TREE',
      'HARMONY_VAULT_TREE',
      'DEFAULT_POWER_VAULT_NODES',
      'DEFAULT_HARMONY_VAULT_NODES',
    ],
    assertions: [
      { subject: 'vault.powerTree', predicate: 'nodeCount', value: POWER_NODES.length, provenance: CATALOG_VAULT },
      // The join against the game's own declared size. Asserted as a comparison
      // rather than restating 46, so it fails if the catalog drifts.
      { subject: 'vault.powerTree', predicate: 'nodeCountMatchesGameConstant', value: POWER_NODES.length === 46, provenance: GAME_VAULT_CONSTANTS, verification: 'verified_here' as const },
      { subject: 'vault.powerTree', predicate: 'tieredNodeCount', value: POWER_TIERED_NODES.length, provenance: CATALOG_VAULT },
      { subject: 'vault.powerTree', predicate: 'singleLevelNodeCount', value: POWER_SINGLE_LEVEL_NODES.length, provenance: CATALOG_VAULT },
      { subject: 'vault.powerTree', predicate: 'tierGateNodeCount', value: POWER_GATE_NODES.length, provenance: CATALOG_VAULT },
      { subject: 'vault.powerTree', predicate: 'allTiersKeyCost', value: VAULT_POWER_ALL_TIERS_KEY_COST, provenance: CATALOG_VAULT },
      { subject: 'vault.powerTree', predicate: 'tier1OnlyKeyCost', value: VAULT_POWER_TIER1_KEY_COST, provenance: CATALOG_VAULT },
      { subject: 'vault.harmonyTree', predicate: 'nodeCount', value: HARMONY_NODES.length, provenance: CATALOG_VAULT },
      { subject: 'vault.harmonyTree', predicate: 'nodeCountMatchesGameConstant', value: HARMONY_NODES.length === 48, provenance: GAME_VAULT_CONSTANTS, verification: 'verified_here' as const },
      { subject: 'vault.harmonyTree', predicate: 'distinctUpgradeCount', value: new Set(HARMONY_NODES.map(node => node.name)).size, provenance: CATALOG_VAULT },
      { subject: 'vault.harmonyTree', predicate: 'tieredNodeCount', value: 0, provenance: CATALOG_VAULT },
      { subject: 'vault.harmonyTree', predicate: 'totalKeyCost', value: HARMONY_VAULT_TREE.totalKeyCost, provenance: CATALOG_VAULT },
      { subject: 'vault.powerTree', predicate: 'allTiersKeyCostMatchesTree', value: VAULT_POWER_ALL_TIERS_KEY_COST === POWER_VAULT_TREE.totalKeyCost, provenance: CATALOG_VAULT },
    ],
    sources: [CATALOG_VAULT, GAME_VAULT_CONSTANTS],
  },
]

export const VAULT_KNOWLEDGE_EDGES: readonly KnowledgeEdge[] = [
  {
    from: 'currency.key',
    kind: 'gates',
    to: 'vault',
    note: 'Keys are the only vault currency, and Legend placement is their only source.',
    sources: [WIKI_VAULT],
  },
  {
    from: 'vault.powerTree',
    kind: 'memberOf',
    to: 'vault',
    note: 'Tower-affecting half of the Vault, mostly three-tiered at 1x / 2x / 4x key cost.',
    sources: [{ ...WIKI_VAULT, section: 'The Vault' }],
  },
  {
    from: 'vault.harmonyTree',
    kind: 'memberOf',
    to: 'vault',
    note: 'Non-tower half — automations, presets and quality-of-life unlocks.',
    sources: [{ ...WIKI_VAULT, section: 'Harmony Tree' }],
  },
  {
    from: 'vault.harmonyTree',
    kind: 'gates',
    to: 'deathPrevention',
    note:
      'Smart Demon Mode and Smart Nuke Automation are what place Demon Mode and Nuke in the '
      + 'death-prevention chain at all. Without them the chain is three links, not five.',
    sources: [{ ...WIKI_VAULT, section: 'Harmony Tree' }],
  },
  {
    from: 'vault.powerTree',
    kind: 'scales',
    to: 'orb',
    note: 'One Power tree node grants an additional orb — a single level, with no higher tier.',
    sources: [{ ...WIKI_VAULT, section: 'The Vault' }],
  },
  {
    from: 'vault.harmonyTree',
    kind: 'scales',
    to: 'damage.berserker',
    note: 'Auto Charge Berserker banks 0.1% of enemy damage per kill, independent of damage taken.',
    sources: [{ ...WIKI_VAULT, section: 'Harmony Tree' }],
  },
  {
    from: 'vault.treeEncoding',
    kind: 'memberOf',
    to: 'vault',
    note:
      'How the shipped trees store tiers, as distinct from what the tiers cost. Power uses a cost '
      + 'array; Harmony repeats nodes.',
    sources: [CATALOG_VAULT],
  },
]
