/**
 * Which relics a player owns, and how many.
 *
 * The save carries owned counts rather than per-relic records, so a reader wanting "which relics"
 * gets a tally and has to resolve it against the catalog.
 */
/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    —
 * depends    src/save/relics/read
 * used by    —
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
export * from './read'
