/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    unitMultipliers, DecimalPreference, FormatNumberForDisplayOptions, FormatUnknownNumberForDisplayOptions, FormatDateTimeForDisplayOptions, FormatSecondsAsHoursMinutesOptions, FormatGroupedNumberOptions, SITE_MAX_DISPLAY_DECIMALS (+26 more)
 * depends    —
 * used by    src/formatting/index, src/formatting/tool-formatting, src/mechanics/calculators/run, src/mechanics/calculators/specs-generated, src/mechanics/effective-paths-lab-costs, src/save/shared-tool-inputs-from-save
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
/**
 * In-game suffix ladder after D: AA … AZ (1e36 … 1e111, ×1000 per letter).
 * Values that do not fit az use `toExponential(2)` — no BA/BB tier in the game UI.
 */
const TOWER_DOUBLE_LETTER_NOTATION_BASE_EXPONENT = 36
const TOWER_MAX_DOUBLE_LETTER_TIER = 25 // AZ

function buildTowerInGameDoubleLetterNotations(): Record<string, number> {
  const out: Record<string, number> = {}
  for (let tier = 0; tier <= TOWER_MAX_DOUBLE_LETTER_TIER; tier += 1) {
    const suffix = String.fromCharCode(65 + tier)
    const multiplier = 10 ** (TOWER_DOUBLE_LETTER_NOTATION_BASE_EXPONENT + tier * 3)
    out[`A${suffix}`] = multiplier
  }
  return out
}

function buildTowerInGameDoubleLetterUnitMultipliers(): Record<string, number> {
  const out: Record<string, number> = {}
  for (const [suffix, multiplier] of Object.entries(buildTowerInGameDoubleLetterNotations())) {
    out[suffix] = multiplier
    out[suffix.toLowerCase()] = multiplier
  }
  return out
}

export const unitMultipliers: Record<string, number> = {
  '': 1,
  k: 1e3,
  K: 1e3,
  m: 1e6,
  M: 1e6,
  b: 1e9,
  B: 1e9,
  t: 1e12,
  T: 1e12,
  q: 1e15,
  Q: 1e18,
  s: 1e21,
  S: 1e24,
  o: 1e27,
  O: 1e27,
  n: 1e30,
  N: 1e30,
  d: 1e33,
  D: 1e33,
  ...buildTowerInGameDoubleLetterUnitMultipliers(),
}

/** Matches in-game `formatValue`: divide by 1000 per suffix until coefficient < 1000. */
const COMPACT_NUMBER_SUFFIX_ORDER = [
  'K',
  'M',
  'B',
  'T',
  'q',
  'Q',
  's',
  'S',
  'O',
  'N',
  'D',
  ...Array.from({ length: 26 }, (_, tier) => `A${String.fromCharCode(65 + tier)}`),
] as const

/**
 * Which character a player reads as the decimal point.
 *
 * Exported because it is part of the signature of `formatNumberForDisplay`,
 * `parseResource` and `normalizeDecimalSeparator` — a consumer storing this preference
 * needs to be able to name its type.
 */
export type DecimalPreference = 'Period (.)' | 'Comma (,)'

type FormatMode = 'display' | 'compact' | 'grouped'
type SmallNumberStrategy = 'round' | 'preserve'

export interface FormatNumberForDisplayOptions {
  mode?: FormatMode
  smallNumberStrategy?: SmallNumberStrategy
  smallNumberMaxFractionDigits?: number
  notationMaxFractionDigits?: number
  useGrouping?: boolean
}

export interface FormatUnknownNumberForDisplayOptions extends FormatNumberForDisplayOptions {
  decimalPreference?: DecimalPreference
  invalidFallback?: string
  nullFallback?: string
}

export interface FormatDateTimeForDisplayOptions {
  invalidFallback?: string
}

export interface FormatSecondsAsHoursMinutesOptions {
  zeroFallback?: string
}

export interface FormatGroupedNumberOptions {
  locale?: string
  useGrouping?: boolean
  minimumFractionDigits?: number
  maximumFractionDigits?: number
  invalidFallback?: string
}

export const SITE_MAX_DISPLAY_DECIMALS = 3

export function roundToDisplayPrecision(
  value: number,
  maxDecimals: number = SITE_MAX_DISPLAY_DECIMALS,
): number {
  if (!Number.isFinite(value)) return 0
  const safeDecimals = Math.max(0, Math.min(maxDecimals, 12))
  const factor = 10 ** safeDecimals
  return Math.round((value + Number.EPSILON) * factor) / factor
}

export function stripInsignificantDecimalZeros(value: string): string {
  if (!value.includes('.')) return value
  return value
    .replace(/(\.\d*?[1-9])0+$/u, '$1')
    .replace(/\.0+$/u, '')
    .replace(/\.$/u, '')
}

export function formatDecimalForDisplay(
  value: number | string | null | undefined,
  options: { maxDecimals?: number; invalidFallback?: string } = {},
): string {
  const maxDecimals = options.maxDecimals ?? SITE_MAX_DISPLAY_DECIMALS
  const invalidFallback = options.invalidFallback ?? ''
  if (value === null || value === undefined || value === '') return invalidFallback

  const numeric = typeof value === 'number'
    ? value
    : Number(normalizeDecimalSeparator(value))
  if (!Number.isFinite(numeric)) return invalidFallback

  const rounded = roundToDisplayPrecision(numeric, maxDecimals)
  const formatted = rounded.toLocaleString('en-US', {
    maximumFractionDigits: maxDecimals,
    minimumFractionDigits: 0,
    useGrouping: false,
  })
  return stripInsignificantDecimalZeros(formatted)
}

export const normalizeNumericValue = (value: string) => value.replace(',', '.').replace('k', 'K')

/**
 * Bring a typed or pasted number to a period-decimal, no-grouping form.
 *
 * **A period is the decimal point; a comma groups thousands.** That is the project's
 * policy and the default of `decimalSeparatorPreference`, and it is what the display side
 * already does — `formatNumberForDisplay(1234567)` renders `1,234,567`. Parsing used to
 * disagree with it: every comma became a period, so the number this package printed did
 * not survive being pasted back in. `1,234,567` read as `1.234567`.
 *
 * A comma is only removed where it actually groups three digits. `"1,5"` is left exactly
 * as it came in, so a validator rejects it rather than this function silently choosing
 * between 1.5 (read as a European decimal) and 15 (read as a stripped group) — both of
 * which are a wrong answer presented as a right one.
 *
 * Pass `'Comma (,)'` to mirror the whole thing for a caller whose user set that.
 */
export function normalizeDecimalSeparator(
  value: string | number | null | undefined,
  decimalPreference: DecimalPreference = 'Period (.)',
): string {
  if (value === null || value === undefined) return ''
  const text = String(value).trim().replace(/\s+/g, '')
  if (!text) return ''

  if (decimalPreference === 'Comma (,)') {
    // Mirrored: periods group, a comma is the decimal point.
    const grouped = /^[+-]?\d{1,3}(\.\d{3})+(,\d+)?$/
    const base = grouped.test(text) ? text.replace(/\./g, '') : text
    return base.replace(/,/g, '.')
  }

  const grouped = /^[+-]?\d{1,3}(,\d{3})+(\.\d+)?$/
  return grouped.test(text) ? text.replace(/,/g, '') : text
}

export function standardizeNotation(
  value: string,
  decimalPreference: DecimalPreference = 'Period (.)',
): string {
  if (!value) return value
  const normalizedValue = normalizeDecimalSeparator(value, decimalPreference)
  const match = normalizedValue.match(/^([\d.]+)([a-zA-Z]*)$/)
  if (!match) return normalizedValue
  const number = match[1]
  let notation = match[2]
  if (notation) {
    notation = notation
      .split('')
      .map(c => (c === 'q' || c === 'Q' || c === 's' || c === 'S' ? c : c.toUpperCase()))
      .join('')
    return number + notation
  }
  return number
}

export function parseNumberInput(input: string): number {
  const normalized = normalizeDecimalSeparator(input)
  const match = normalized.match(/^(\d+|\d*\.\d+)([KMBTqQsSOND]|A[A-Z])?$/i)
  if (!match) {
    const fallback = parseFloat(normalized)
    return Number.isFinite(fallback) ? fallback : 0
  }
  const numberPart = parseFloat(match[1])
  const notationRaw = match[2]
  if (!notationRaw) return numberPart

  const notation = notationRaw.length === 1 && (notationRaw === 'q' || notationRaw === 'Q' || notationRaw === 's' || notationRaw === 'S')
    ? notationRaw
    : notationRaw.toUpperCase()

  const multiplier = unitMultipliers[notation] ?? unitMultipliers[notationRaw]
  return multiplier ? numberPart * multiplier : numberPart
}

/**
 * A number and its unit, pulled out of a display string.
 *
 * `value` is ALWAYS finite. Before 2026-08-18 it was `parseFloat(...) / 1000`
 * with no guard, so any unparseable string produced NaN and handed it to the
 * caller — `parseValueWithUnit("abc")` returned `{ value: NaN, unit: "K" }`.
 *
 * `parsed` is how absence is reported. Returning 0 alone would be a silent
 * default of exactly the kind that hides here: a run with an unreadable coin
 * total would sort and average as if it were zero. Callers that care about the
 * difference between "no number" and "the number nought" must read `parsed`;
 * callers that only need arithmetic get a finite value either way.
 */
export interface ParsedValueWithUnit {
  /** Always finite. `0` when nothing could be read — check `parsed` to tell them apart. */
  value: number
  unit: string
  /** `false` when the input carried no readable number. */
  parsed: boolean
}

const UNPARSEABLE: ParsedValueWithUnit = { value: 0, unit: '', parsed: false }

export const parseValueWithUnit = (value: string | undefined | null): ParsedValueWithUnit => {
  if (value == null) return UNPARSEABLE

  const cleanedValue = value.replace(/^\$/, '')
  const match = cleanedValue.match(/^([\d,.]+)([a-zA-Z]+)?$/)
  if (match) {
    const numericPart = match[1].replace(',', '.')
    const unitPart = match[2] || ''
    const numericValue = parseFloat(numericPart)
    if (!Number.isFinite(numericValue)) return UNPARSEABLE
    if (unitPart) return { value: numericValue, unit: unitPart, parsed: true }
  }

  // No unit: the bare number is read as thousands, which is what the tracker
  // writes. "1500" is 1.5K.
  const bare = parseFloat(cleanedValue.replace(',', '.'))
  if (!Number.isFinite(bare)) return UNPARSEABLE
  return { value: bare / 1000, unit: 'K', parsed: true }
}

export const convertToNumericValue = (value: number, unit: string): number => {
  return value * (unitMultipliers[unit] || 1)
}

export function parseDurationToHours(duration: string | number | null | undefined): number {
  if (duration === null || duration === undefined || duration === 'Unknown') return 0
  if (typeof duration === 'number' && Number.isFinite(duration)) return duration

  const normalized = String(duration).trim().replace(/,/g, '.').replace(/\s+/g, ' ').toLowerCase()
  if (!normalized) return 0

  const clock = normalized.match(/(\d+:\d{1,2}(?::\d{1,2}){0,2})/)
  if (clock) {
    const parts = clock[1].split(':').map(p => parseInt(p, 10) || 0)
    if (parts.length >= 4) {
      const len = parts.length
      const days = parts[len - 4]
      const hours = parts[len - 3]
      const minutes = parts[len - 2]
      const seconds = parts[len - 1]
      return (days * 24) + hours + minutes / 60 + seconds / 3600
    }
    if (parts.length === 3) return parts[0] + parts[1] / 60 + parts[2] / 3600
    if (parts.length === 2) return parts[0] + parts[1] / 60
  }

  let years = 0
  let days = 0
  let hours = 0
  let minutes = 0
  let seconds = 0
  let matched = false

  const tokenRegex = /(\d+(?:\.\d+)?)\s*(y|yr|yrs|year|years|d|day|days|h|hr|hrs|hour|hours|m|min|mins|minute|minutes|s|sec|secs|second|seconds)/gi
  let tokenMatch: RegExpExecArray | null
  while ((tokenMatch = tokenRegex.exec(normalized)) !== null) {
    matched = true
    const value = parseFloat(tokenMatch[1])
    const unit = tokenMatch[2][0]
    if (unit === 'y') years += value
    else if (unit === 'd') days += value
    else if (unit === 'h') hours += value
    else if (unit === 'm') minutes += value
    else if (unit === 's') seconds += value
  }

  if (!matched) {
    const compactRegex = /(\d+(?:\.\d+)?)([ydhms])/gi
    let compact: RegExpExecArray | null
    while ((compact = compactRegex.exec(normalized)) !== null) {
      matched = true
      const value = parseFloat(compact[1])
      const unit = compact[2]
      if (unit === 'y') years += value
      else if (unit === 'd') days += value
      else if (unit === 'h') hours += value
      else if (unit === 'm') minutes += value
      else if (unit === 's') seconds += value
    }
  }

  if (!matched) {
    const numeric = parseFloat(normalized)
    if (Number.isFinite(numeric)) return numeric
    return 0
  }

  const total = years * 24 * 365 + days * 24 + hours + minutes / 60 + seconds / 3600
  return Number.isFinite(total) ? total : 0
}

export function parseDuration(duration: string): number {
  return parseDurationToHours(duration) * 3600
}

/**
 * Compare two unit-suffixed display strings. A TOTAL order, and never NaN.
 *
 * The previous version subtracted two `parseValueWithUnit` results directly, so
 * one unreadable cell made the comparator return NaN. `Array.prototype.sort`
 * with a NaN-returning comparator leaves the order implementation-defined — in
 * practice, on the runs table, the column simply did not sort and said nothing
 * about it. This is the comparator behind nine columns of the runs table, so a
 * single malformed value silently disabled sorting for the whole column.
 *
 * Unreadable values sort together at the end, below every real number, rather
 * than being treated as zero and interleaved with genuine zeroes.
 */
export const sortByUnit = (left: string, right: string): number => {
  const leftParsed = parseValueWithUnit(left)
  const rightParsed = parseValueWithUnit(right)

  if (!leftParsed.parsed || !rightParsed.parsed) {
    if (leftParsed.parsed === rightParsed.parsed) return 0
    return leftParsed.parsed ? -1 : 1
  }

  const leftMultiplier = unitMultipliers[leftParsed.unit] || 1
  const rightMultiplier = unitMultipliers[rightParsed.unit] || 1
  const difference = (leftParsed.value * leftMultiplier) - (rightParsed.value * rightMultiplier)
  return Number.isFinite(difference) ? difference : 0
}

export const sortByConvertedDuration = (left: string, right: string) =>
  parseDuration(left) - parseDuration(right)

/**
 * Render a grouped number in the comma convention.
 *
 * Both separators swap, in one pass. Replacing only `.` with `,` leaves the comma group
 * separators where they are, so `1,234.5` came out as `1,234,5` — which is ambiguous to a
 * reader and unparseable by `parseResource`, breaking the round-trip in the one direction
 * that exists for the players who need it. The correct form is `1.234,5`.
 *
 * This was invisible for as long as nothing passed `'Comma (,)'`.
 */
function applyDecimalPreference(value: string, decimalPreference: DecimalPreference): string {
  if (decimalPreference !== 'Comma (,)') return value
  return value.replace(/[.,]/g, match => (match === '.' ? ',' : '.'))
}

function parseDisplayNumericValue(value: number | string): number | string {
  if (typeof value === 'string') {
    const parsed = parseFloat(value.replace(/,/g, ''))
    return Number.isNaN(parsed) ? value : parsed
  }
  return value
}

function formatGroupedValue(numericValue: number, maxFractionDigits: number, useGrouping: boolean, decimalPreference: DecimalPreference): string {
  const output = numericValue.toLocaleString('en-US', {
    maximumFractionDigits: maxFractionDigits,
    useGrouping,
  })
  return applyDecimalPreference(output, decimalPreference)
}

function formatSmallValue(
  numericValue: number,
  strategy: SmallNumberStrategy,
  maxFractionDigits: number,
  useGrouping: boolean,
  decimalPreference: DecimalPreference,
): string {
  if (strategy === 'round') {
    return applyDecimalPreference(Math.round(numericValue).toString(), decimalPreference)
  }

  const cappedFractionDigits = Math.min(maxFractionDigits, SITE_MAX_DISPLAY_DECIMALS)
  const rounded = roundToDisplayPrecision(numericValue, cappedFractionDigits)
  const formatted = rounded.toLocaleString('en-US', {
    maximumFractionDigits: cappedFractionDigits,
    minimumFractionDigits: 0,
    useGrouping,
  })

  return applyDecimalPreference(stripInsignificantDecimalZeros(formatted), decimalPreference)
}

function formatNotationValue(numericValue: number, notationMaxFractionDigits: number, decimalPreference: DecimalPreference): string {
  const maxFractionDigits = Math.min(notationMaxFractionDigits, SITE_MAX_DISPLAY_DECIMALS)
  let workingValue = Math.abs(numericValue)

  for (const notation of COMPACT_NUMBER_SUFFIX_ORDER) {
    workingValue /= 1000
    if (workingValue < 1000) {
      const signedValue = numericValue < 0 ? -workingValue : workingValue
      const output = formatDecimalForDisplay(signedValue, { maxDecimals: maxFractionDigits })
      return applyDecimalPreference(`${output}${notation}`, decimalPreference)
    }
  }

  return applyDecimalPreference(numericValue.toExponential(2), decimalPreference)
}

export function formatNumberForDisplay(
  value: number | string,
  decimalPreference: DecimalPreference = 'Period (.)',
  options: FormatNumberForDisplayOptions = {},
): string {
  if (value === null || value === undefined || value === 'N/A') return 'N/A'
  if (typeof value === 'string' && value.trim() === '') return ''
  const mode = options.mode ?? 'display'
  const smallNumberStrategy = options.smallNumberStrategy ?? (mode === 'compact' || mode === 'grouped' ? 'preserve' : 'preserve')
  const smallNumberMaxFractionDigits = options.smallNumberMaxFractionDigits ?? SITE_MAX_DISPLAY_DECIMALS
  const notationMaxFractionDigits = options.notationMaxFractionDigits ?? SITE_MAX_DISPLAY_DECIMALS
  const useGrouping = options.useGrouping ?? (mode === 'compact' || mode === 'grouped')

  const numericValue = parseDisplayNumericValue(value)
  if (typeof numericValue !== 'number' || isNaN(numericValue)) return String(value)

  if (mode === 'grouped') {
    return formatGroupedValue(numericValue, smallNumberMaxFractionDigits, useGrouping, decimalPreference)
  }

  if (Math.abs(numericValue) < 1000) {
    return formatSmallValue(
      numericValue,
      smallNumberStrategy,
      smallNumberMaxFractionDigits,
      useGrouping,
      decimalPreference,
    )
  }

  return formatNotationValue(numericValue, notationMaxFractionDigits, decimalPreference)
}

export function formatUnknownNumberForDisplay(
  value: unknown,
  options: FormatUnknownNumberForDisplayOptions = {},
): string {
  const decimalPreference = options.decimalPreference ?? 'Period (.)'
  const invalidFallback = options.invalidFallback ?? 'N/A'
  const nullFallback = options.nullFallback ?? invalidFallback

  if (value === null || value === undefined || value === '') return nullFallback

  if (typeof value === 'number') {
    if (!Number.isFinite(value)) return invalidFallback
    return formatNumberForDisplay(value, decimalPreference, options)
  }

  if (typeof value === 'string') {
    const trimmed = value.trim()
    if (!trimmed) return nullFallback
    const numeric = Number(trimmed)
    if (!Number.isFinite(numeric)) return invalidFallback
    return formatNumberForDisplay(numeric, decimalPreference, options)
  }

  return invalidFallback
}

const DOTNET_EPOCH_TICKS = 621355968000000000n
const DOTNET_TICKS_MASK = 0x3FFFFFFFFFFFFFFFn

function dotnetTicksToMs(ticks: bigint): number | null {
  const normalized = (ticks & DOTNET_TICKS_MASK) - DOTNET_EPOCH_TICKS
  if (normalized < 0n) return null
  const ms = Number(normalized / 10000n)
  return Number.isFinite(ms) ? ms : null
}

function parseNumericSaveDateTime(value: number): number | null {
  if (!Number.isFinite(value) || value <= 0) return null
  if (value >= 1e14) {
    try {
      return dotnetTicksToMs(BigInt(Math.trunc(value)))
    } catch {
      return null
    }
  }
  if (value < 10_000_000_000) return value * 1000
  return value
}

/** Parse save-file date/time values (ISO, unix ms/s, .NET ticks, `{ __value }` wrappers) to epoch ms. */
export function parseSaveDateTimeToMs(value: unknown): number | null {
  if (value == null) return null
  if (value instanceof Date) {
    const ms = value.getTime()
    return Number.isFinite(ms) ? ms : null
  }
  if (typeof value === 'object') {
    const record = value as Record<string, unknown>
    if ('__value' in record) return parseSaveDateTimeToMs(record.__value)
    if ('__ticks' in record) return parseSaveDateTimeToMs(record.__ticks)
  }
  if (typeof value === 'number') return parseNumericSaveDateTime(value)
  if (typeof value === 'bigint') return dotnetTicksToMs(value)
  if (typeof value === 'string') {
    const trimmed = value.trim()
    if (!trimmed) return null
    if (/^\d+$/.test(trimmed)) {
      try {
        if (trimmed.length >= 16) return dotnetTicksToMs(BigInt(trimmed))
        return parseNumericSaveDateTime(Number(trimmed))
      } catch {
        return null
      }
    }
    const parsed = Date.parse(trimmed)
    return Number.isFinite(parsed) ? parsed : null
  }
  return null
}

export function formatDateTimeForDisplay(
  value: unknown,
  options: FormatDateTimeForDisplayOptions = {},
): string {
  const invalidFallback = options.invalidFallback ?? 'N/A'
  if (value == null || value === '') return invalidFallback
  const ms = parseSaveDateTimeToMs(value)
  if (ms == null) return invalidFallback
  return new Date(ms).toLocaleString()
}

export function formatSecondsAsHoursMinutes(
  seconds: number | undefined | null,
  options: FormatSecondsAsHoursMinutesOptions = {},
): string {
  const zeroFallback = options.zeroFallback ?? '0m'
  if (seconds == null || !Number.isFinite(seconds) || seconds <= 0) return zeroFallback
  const hours = Math.floor(seconds / 3600)
  const minutes = Math.floor((seconds % 3600) / 60)
  if (hours > 0) return `${hours}h ${minutes}m`
  return `${minutes}m`
}

export function formatGroupedNumber(
  value: unknown,
  options: FormatGroupedNumberOptions = {},
): string {
  const invalidFallback = options.invalidFallback ?? '0'
  const numeric = typeof value === 'number' ? value : Number(value)
  if (!Number.isFinite(numeric)) return invalidFallback
  return numeric.toLocaleString(options.locale, {
    useGrouping: options.useGrouping,
    minimumFractionDigits: options.minimumFractionDigits,
    maximumFractionDigits: options.maximumFractionDigits,
  })
}

export function formatRateWithNotation(amount: number, hours: number): string {
  if (!Number.isFinite(amount) || hours <= 0) return '0'
  const rate = amount / hours
  if (Math.abs(rate) < 1000) return formatNumberForDisplay(rate)

  let workingValue = Math.abs(rate)
  for (const notation of COMPACT_NUMBER_SUFFIX_ORDER) {
    workingValue /= 1000
    if (workingValue < 1000) {
      const signedRate = rate < 0 ? -workingValue : workingValue
      const output = formatDecimalForDisplay(signedRate, { maxDecimals: SITE_MAX_DISPLAY_DECIMALS })
      if (output.startsWith('0.')) {
        return `${formatDecimalForDisplay(rate * 1000, { maxDecimals: SITE_MAX_DISPLAY_DECIMALS })}K`
      }
      return `${output}${notation}`
    }
  }

  return rate.toExponential(2)
}

/**
 * A well-formed resource amount: digits, an optional decimal part, and either an exponent
 * or one of the game's magnitude suffixes — nothing else.
 *
 * `parseNumberInput` falls back to `parseFloat` when its own pattern misses, and `parseFloat`
 * takes a leading number and discards whatever follows. That turned `"12abc"` into `12` and
 * `"abc"` into `0`, both reported as successes — a pasted value with a stray character became
 * a confidently wrong number, and garbage became a zero indistinguishable from a real one.
 * `parseResource` has an error channel, so it checks the shape before trusting the number.
 */
const RESOURCE_INPUT_PATTERN = /^(?:\d+|\d*\.\d+)(?:[eE][+-]?\d+|[KMBTQSOND]|A[A-Z])?$/i

export function parseResource(
  raw: string | null | undefined,
  decimalPreference: DecimalPreference = 'Period (.)',
): { error?: true; value?: number } {
  if (!raw) return { error: true }
  /*
   * Normalise ONCE. `standardizeNotation` normalises internally, so passing it an already
   * normalised string ran the grouping rules twice — and under the comma convention that
   * turned "1,234" (one point two three four) into 1234, a thousandfold error of exactly
   * the kind this preference exists to prevent.
   */
  const standardized = standardizeNotation(String(raw), decimalPreference)
  if (!standardized) return { error: true }
  if (!RESOURCE_INPUT_PATTERN.test(standardized.trim())) return { error: true }
  const value = parseNumberInput(standardized)
  if (!Number.isFinite(value) || value < 0) return { error: true }
  return { value }
}

export function computeHourlyRate(value: unknown, duration?: string | null): string | null {
  const hours = parseDurationToHours(duration)
  if (!hours || hours <= 0) return null
  const numeric = parseNumberInput(standardizeNotation(String(value ?? '0')))
  if (numeric === undefined || numeric === null || Number.isNaN(Number(numeric))) return null
  return formatNumberForDisplay(Number(numeric) / hours)
}

export function formatDateToISO(dateStr?: string | null): string {
  const today = new Date().toISOString().split('T')[0]
  if (!dateStr || typeof dateStr !== 'string') return today
  if (/^\d{4}-\d{2}-\d{2}$/.test(dateStr)) return dateStr
  const parts = dateStr.split(/[/-]/)
  if (parts.length === 3) {
    const [firstPart, secondPart, yearPart] = parts
    if (yearPart.length === 4) {
      const first = parseInt(firstPart, 10)
      const second = parseInt(secondPart, 10)
      const month = first > 12 ? second : first
      const day = first > 12 ? first : second
      return `${yearPart}-${String(month).padStart(2, '0')}-${String(day).padStart(2, '0')}`
    }
    const year = `20${yearPart}`
    const first = parseInt(firstPart, 10)
    const second = parseInt(secondPart, 10)
    const month = first > 12 ? second : first
    const day = first > 12 ? first : second
    return `${year}-${String(month).padStart(2, '0')}-${String(day).padStart(2, '0')}`
  }
  return dateStr
}

export function formatTimeTo24h(timeStr?: string | null): string {
  const now = new Date().toISOString().split('T')[1]?.slice(0, 8) ?? '00:00:00'
  if (!timeStr || typeof timeStr !== 'string') return now
  if (/^\d{2}:\d{2}:\d{2}$/.test(timeStr)) return timeStr
  const match = timeStr.match(/(\d{1,2}):(\d{2})(?::(\d{2}))?\s*([AP]M)/i)
  if (match) {
    let hour = parseInt(match[1], 10)
    const minute = match[2]
    const second = match[3] || '00'
    const ampm = match[4].toUpperCase()
    if (ampm === 'PM' && hour < 12) hour += 12
    if (ampm === 'AM' && hour === 12) hour = 0
    return `${hour.toString().padStart(2, '0')}:${minute}:${second}`
  }
  return timeStr
}

export function normalizeDecimalSeparators<T>(data: T): T {
  const normalizeValue = (value: unknown, key?: string): unknown => {
    if (value === null || value === undefined) return value

    if (typeof value === 'string') {
      const lowerKey = key?.toLowerCase() ?? ''
      if (lowerKey.includes('date') || lowerKey.includes('time')) return value.trim()
      let normalizedValue = value.replace(/(\d),(\d)/g, '$1.$2')
      normalizedValue = standardizeNotation(normalizedValue)
      return normalizedValue
    }

    if (Array.isArray(value)) return value.map(entry => normalizeValue(entry))

    if (typeof value === 'object') {
      const output: Record<string, unknown> = {}
      for (const [entryKey, entryValue] of Object.entries(value)) {
        output[entryKey] = normalizeValue(entryValue, entryKey)
      }
      return output
    }

    return value
  }

  return normalizeValue(data) as T
}
