/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    GlossaryKind, GlossaryDomain, GlossaryEntry
 * depends    —
 * used by    src/data/generated/glossary-names.generated, src/data/glossary/concepts, src/data/glossary/glossary
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
/** Shared shape for glossary entries, so the generated and curated halves agree. */

export type GlossaryKind = 'name' | 'acronym' | 'concept'

export type GlossaryDomain =
  | 'ultimate-weapon'
  | 'bot'
  | 'module'
  | 'card'
  | 'workshop'
  | 'lab'
  | 'guardian'
  | 'currency'
  | 'enemy'
  | 'tournament'
  | 'run'
  | 'sdk'

export interface GlossaryEntry {
  /** The term as it is written. */
  term: string
  kind: GlossaryKind
  domain: GlossaryDomain
  /**
   * What an acronym stands for. Must match a name that exists in the catalogs —
   * `glossary.test.ts` fails the build otherwise, which is what stops a plausible
   * expansion from being invented.
   */
  expansion?: string
  definition: string
  /** Set when the same term means more than one thing; check `domain` before using it. */
  ambiguous?: true
  /**
   * Where the term comes from, and how far to trust its expansion.
   *
   * - `catalog` — the expansion names something in the shipped data, and
   *   `glossary.test.ts` fails the build if it stops resolving.
   * - `community` — shorthand players actually type that the catalogs have no
   *   entry for: enhancement suffixes like `dmg+`, spelling variants like
   *   `zerk`, and concepts the game never named. Curated by hand, so it is
   *   authored rather than invented, but it is not a fact about the data and is
   *   marked so it cannot be mistaken for one.
   */
  source?: 'catalog' | 'community'
}
