/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    normalizeRunDateText, normalizeRunTimeText, RUN_NON_ATTRIBUTE_KEYS, RUN_OPTIONAL_STRING_FIELDS, RUN_MAIN_COLLECTION_OPTIONAL_FIELDS, RUN_EXTENDED_FIELDS, isScalarRunFieldValue, pickString (+2 more)
 * depends    src/formatting
 * used by    src/mechanics/calculators/run, src/mechanics/calculators/specs-generated, src/save/battle/report-fields, src/save/battle/reports, src/save/runs/index, src/save/runs/lifetime-fields
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
import { parseSaveDateTimeToMs } from '../../formatting'

/**
 * The shape of a stored run record, and how its text fields normalise.
 *
 * Field lists, date and time normalisers, and the scalar collector. None of it
 * knows about a database: it describes what a run HOLDS, which is why the save
 * readers and the calculator runner need it.
 *
 * It used to live beside the cloud document schemas, alongside the
 * wrappers -- so reading a battle report out of a save pulled in cloud schemas.
 * That module now imports these instead of owning them.
 */

export function normalizeRunDateText(value: unknown): string {
  const raw = String(value ?? '').trim()
  if (!raw) return ''
  if (/^\d{4}-\d{2}-\d{2}$/.test(raw)) return raw

  const parsedMs = parseSaveDateTimeToMs(raw)
  if (parsedMs != null && /^\d+$/.test(raw)) {
    const date = new Date(parsedMs)
    const year = date.getFullYear()
    const month = String(date.getMonth() + 1).padStart(2, '0')
    const day = String(date.getDate()).padStart(2, '0')
    return `${year}-${month}-${day}`
  }

  const parts = raw.split(/[./-]/).map(part => part.trim())
  if (parts.length !== 3) return raw

  const [firstPart, secondPart, thirdPart] = parts
  if (!/^\d{1,4}$/.test(firstPart) || !/^\d{1,2}$/.test(secondPart) || !/^\d{1,4}$/.test(thirdPart)) {
    return raw
  }

  if (firstPart.length === 4) {
    return `${firstPart.padStart(4, '0')}-${secondPart.padStart(2, '0')}-${thirdPart.padStart(2, '0')}`
  }

  const monthOrDayA = Number(firstPart)
  const monthOrDayB = Number(secondPart)
  const year = thirdPart.length === 2 ? `20${thirdPart}` : thirdPart.padStart(4, '0')
  const month = monthOrDayA > 12 ? monthOrDayB : monthOrDayA
  const day = monthOrDayA > 12 ? monthOrDayA : monthOrDayB

  if (!Number.isFinite(month) || !Number.isFinite(day)) return raw
  return `${year}-${String(month).padStart(2, '0')}-${String(day).padStart(2, '0')}`
}

export function normalizeRunTimeText(value: unknown): string {
  const raw = String(value ?? '').trim()
  if (!raw) return ''
  if (/^\d{2}:\d{2}:\d{2}$/.test(raw)) return raw
  if (/^\d{2}:\d{2}$/.test(raw)) return `${raw}:00`

  const shortTimeMatch = raw.match(/^(\d{1,2}):(\d{2})(?::(\d{2}))?\s*([AP]M)$/i)
  if (shortTimeMatch) {
    let hour = Number(shortTimeMatch[1])
    const minute = shortTimeMatch[2]
    const second = shortTimeMatch[3] ?? '00'
    const suffix = shortTimeMatch[4].toUpperCase()
    if (suffix === 'PM' && hour < 12) hour += 12
    if (suffix === 'AM' && hour === 12) hour = 0
    return `${String(hour).padStart(2, '0')}:${minute}:${second}`
  }

  const compactTimeMatch = raw.match(/^(\d{1,2}):(\d{2})(?::(\d{2}))?$/)
  if (compactTimeMatch) {
    const hour = compactTimeMatch[1]
    const minute = compactTimeMatch[2]
    const second = compactTimeMatch[3] ?? '00'
    return `${hour.padStart(2, '0')}:${minute}:${second}`
  }

  return raw
}

export const RUN_NON_ATTRIBUTE_KEYS = new Set([
  'fullRunData',
  'localId',
  'localScreenshotPath',
  'localScreenshotName',
])

export const RUN_OPTIONAL_STRING_FIELDS = [
  'username',
  'note',
  'gameTime',
  'coinsPerHour',
  'cellsPerHour',
  'rerollShardsPerHour',
  'cashEarned',
  'interestEarned',
  'gemBlocksTapped',
  'damageTaken',
  'damageTakenWall',
  'damageTakenWhileBerserked',
  'damageGainFromBerserk',
  'deathDefy',
  'damageDealt',
  'projectilesDamage',
  'rendArmorDamage',
  'projectilesCount',
  'lifesteal',
  'thornDamage',
  'orbDamage',
  'enemiesHitByOrbs',
  'landMineDamage',
  'landMinesSpawned',
  'deathRayDamage',
  'smartMissileDamage',
  'innerLandMineDamage',
  'chainLightningDamage',
  'deathWaveDamage',
  'taggedByDeathWave',
  'swampDamage',
  'blackHoleDamage',
  'spotlightDamage',
  'electronsDamage',
  'wavesSkipped',
  'recoveryPackages',
  'healthFromRecoveryPackages',
  'freeAttackUpgrade',
  'freeDefenseUpgrade',
  'freeUtilityUpgrade',
  'hpFromDeathWave',
  'coinsFromDeathWave',
  'cashFromGoldenTower',
  'coinsFromGoldenTower',
  'coinsFromBlackhole',
  'coinsFromSpotlight',
  'coinsFromOrbs',
  'coinsFromCoinUpgrade',
  'coinsFromCoinBonuses',
  'totalEnemies',
  'basic',
  'fast',
  'tank',
  'ranged',
  'boss',
  'protector',
  'totalElites',
  'vampires',
  'rays',
  'scatters',
  'saboteurs',
  'commanders',
  'overcharges',
  'destroyedByOrbs',
  'destroyedByThorns',
  'destroyedByDeathRay',
  'destroyedByLandMine',
  'destroyedInSpotlight',
  'flameBotDamage',
  'thunderBotStuns',
  'goldenBotCoinsEarned',
  'destroyedInGoldenBot',
  'guardianDamage',
  'guardianSummonedEnemies',
  'guardianCatches',
  'guardianCoinsStolen',
  'coinsFetched',
  'gemsFetched',
  'medalsFetched',
  'rerollShardsFetched',
  'cannonShardsFetched',
  'armorShardsFetched',
  'generatorShardsFetched',
  'coreShardsFetched',
  'commonModulesFetched',
  'rareModulesFetched',
  'highestCoinsPerMinute',
  'largestWaveSkip',
  'mostCoinsFromWaveSkip',
  'mostCellsFromWaveSkip',
  'largestSmartMissileStack',
  'largestGoldenCombo',
  'mostCoinsFromGoldenCombo',
  'largestInnerLandmineCharge',
  'attackChipDamage',
  'towerHealthRegen',
  'wallHealthRegen',
  'defensePercentBlocked',
  'defenseAbsoluteBlocked',
  'chronoFieldBlocked',
  'chainThunderBlocked',
  'flameBotBlocked',
  'primordialCollapseBlocked',
  'negativeMassProjectorBlocked',
  'enemyAttackLevelsSkipped',
  'enemyHealthLevelsSkipped',
  'hitsAbsorbedByEnergyShield',
  'nukeCount',
  'secondWindCount',
  'demonModeCount',
  'enemiesHitByProjectiles',
  'enemiesHitByThorns',
  'enemiesHitByDeathRay',
  'enemiesHitByChainLightning',
  'enemiesHitBySmartMissiles',
  'enemiesHitByInnerLandMines',
  'enemiesHitByPoisonSwamp',
  'enemiesHitByBlackHole',
  'enemiesHitByChronoField',
  'enemiesHitByLandMines',
  'enemiesHitByThunderBot',
  'enemiesHitByFlameBot',
  'enemiesHitByAttackChip',
  'enemiesHitByOrbitalAugment',
  'killsWithGoldenTower',
  'killsWithDeathWave',
  'killsWithAmplifyBot',
  'killsWithDeathPenalty',
  'killsWithBlackHole',
  'killsWithOrbs',
  'criticalCoinCoins',
  'coinsPerKill',
  'coinsFromGoldenCombo',
  'coinsFromWaveSkip',
  'coinsPerWave',
  'bountyCoins',
  'gemsEarned',
  'adGemsEarned',
  'fetchGems',
  'medalsEarned',
  'destroyedByProjectiles',
  'destroyedByChainLightning',
  'destroyedBySmartMissiles',
  'destroyedByInnerLandMines',
  'destroyedByPoisonSwamp',
  'destroyedByBlackHole',
  'destroyedByFlameBot',
  'destroyedByOther',
] as const

export const RUN_MAIN_COLLECTION_OPTIONAL_FIELDS = [
  'note',
  'gameTime',
  'coinsPerHour',
  'cellsPerHour',
  'rerollShardsPerHour',
  'cashEarned',
  'interestEarned',
  'gemBlocksTapped',
  'damageTaken',
  'damageTakenWall',
  'damageTakenWhileBerserked',
  'damageGainFromBerserk',
  'deathDefy',
  'damageDealt',
  'projectilesDamage',
  'rendArmorDamage',
  'projectilesCount',
  'lifesteal',
  'thornDamage',
  'orbDamage',
  'enemiesHitByOrbs',
  'landMineDamage',
  'landMinesSpawned',
  'deathRayDamage',
  'smartMissileDamage',
  'innerLandMineDamage',
  'chainLightningDamage',
  'deathWaveDamage',
  'taggedByDeathWave',
  'swampDamage',
  'blackHoleDamage',
  'electronsDamage',
  'wavesSkipped',
  'recoveryPackages',
  'freeAttackUpgrade',
  'freeDefenseUpgrade',
  'freeUtilityUpgrade',
  'hpFromDeathWave',
  'coinsFromDeathWave',
  'cashFromGoldenTower',
  'coinsFromGoldenTower',
  'coinsFromBlackhole',
  'coinsFromSpotlight',
  'coinsFromOrbs',
  'coinsFromCoinUpgrade',
  'coinsFromCoinBonuses',
  'totalEnemies',
  'basic',
  'fast',
  'tank',
  'ranged',
  'boss',
  'protector',
  'totalElites',
  'vampires',
  'rays',
  'scatters',
  'saboteurs',
  'commanders',
  'overcharges',
  'destroyedByOrbs',
  'destroyedByThorns',
  'destroyedByDeathRay',
  'destroyedByLandMine',
  'destroyedInSpotlight',
  'flameBotDamage',
  'thunderBotStuns',
  'goldenBotCoinsEarned',
  'destroyedInGoldenBot',
  'guardianDamage',
  'guardianSummonedEnemies',
  'guardianCoinsStolen',
  'coinsFetched',
  'gemsFetched',
  'medalsFetched',
  'rerollShardsFetched',
  'cannonShardsFetched',
  'armorShardsFetched',
  'generatorShardsFetched',
  'coreShardsFetched',
  'commonModulesFetched',
  'rareModulesFetched',
] as const

export const RUN_EXTENDED_FIELDS = RUN_OPTIONAL_STRING_FIELDS.filter(key => (
  key !== 'username'
  && key !== 'note'
  && !RUN_MAIN_COLLECTION_OPTIONAL_FIELDS.includes(key as (typeof RUN_MAIN_COLLECTION_OPTIONAL_FIELDS)[number])
))

export function isScalarRunFieldValue(value: unknown): value is string | number | boolean | null {
  return value === null || typeof value === 'string' || typeof value === 'number' || typeof value === 'boolean'
}

export function pickString(value: unknown): string | undefined {
  if (value === null || value === undefined) return undefined
  const text = String(value).trim()
  return text.length > 0 ? text : undefined
}

export function pickRunField(run: Record<string, unknown>, keys: string[]): string | undefined {
  for (const key of keys) {
    const value = run[key]
    if (value === null || value === undefined) continue
    const text = String(value).trim()
    if (text.length > 0) return text
  }
  return undefined
}

export function collectRunScalarFields(
  ...sources: Array<Record<string, unknown> | null | undefined>
): Record<string, unknown> {
  const payload: Record<string, unknown> = {}
  for (const source of sources) {
    if (!source || typeof source !== 'object') continue
    for (const [key, value] of Object.entries(source)) {
      if (value === undefined) continue
      if (RUN_NON_ATTRIBUTE_KEYS.has(key)) continue
      if (!isScalarRunFieldValue(value)) continue
      payload[key] = value
    }
  }
  return payload
}
