/**
 * What a lifetime-stats record holds, and how its values normalise.
 *
 * Field lists and normalisers. Nothing here knows about a database -- the save
 * reader needs these to turn a decoded save into a lifetime record, which is
 * why they sit beside it rather than beside the cloud write builders they were
 * filed with.
 */
/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    LIFETIME_NUMERIC_FIELDS, LIFETIME_REQUIRED_KEYS, LIFETIME_OPTIONAL_KEYS, normalizeLifetimeDateText, normalizeLifetimeDate, normalizeLifetimeEntryValues
 * depends    src/save/runs/fields
 * used by    src/mechanics/calculators/specs-generated, src/save/lifetime/read, src/save/runs/index
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
import { normalizeRunDateText } from './fields'

export const LIFETIME_NUMERIC_FIELDS = [
  'coinsEarned',
  'recentCoinsPerHour',
  'cashEarned',
  'stonesEarned',
  'keysEarned',
  'cellsEarned',
  'rerollShardsEarned',
  'damageDealt',
  'enemiesDestroyed',
  'wavesCompleted',
  'upgradesBought',
  'workshopUpgrades',
  'workshopCoinsSpent',
  'researchCompleted',
  'labCoinsSpent',
  'freeUpgrades',
  'interestEarned',
  'orbKills',
  'deathRayKills',
  'thornDamage',
  'wavesSkipped',
] as const

export const LIFETIME_REQUIRED_KEYS = [
  'coinsEarned',
  'cashEarned',
  'stonesEarned',
  'keysEarned',
  'damageDealt',
  'enemiesDestroyed',
  'wavesCompleted',
  'upgradesBought',
  'workshopUpgrades',
  'workshopCoinsSpent',
  'researchCompleted',
  'labCoinsSpent',
  'freeUpgrades',
  'interestEarned',
  'orbKills',
  'deathRayKills',
  'thornDamage',
  'wavesSkipped',
  'userId',
  'date',
  'gameStarted',
] as const

export const LIFETIME_OPTIONAL_KEYS = [
  'username',
  'screenshotUrl',
  'verified',
  'blocked',
  'recentCoinsPerHour',
  'cellsEarned',
  'rerollShardsEarned',
] as const

export function normalizeLifetimeDateText(value: unknown): string {
  const raw = String(value ?? '').trim()
  if (!raw) return ''

  const isoTimestampMatch = raw.match(/^(\d{4}-\d{2}-\d{2})(?:[T\s].*)?$/)
  if (isoTimestampMatch) {
    return isoTimestampMatch[1]
  }

  const normalized = normalizeRunDateText(raw)
  if (/^\d{4}-\d{2}-\d{2}$/.test(normalized)) {
    return normalized
  }

  return raw
}

export function normalizeLifetimeDate(value: unknown): string {
  const normalized = normalizeLifetimeDateText(value)
  if (/^\d{4}-\d{2}-\d{2}$/.test(normalized)) {
    return normalized
  }
  return new Date().toISOString().split('T')[0]
}

export function normalizeLifetimeEntryValues(
  entry: Record<string, unknown>,
  options?: {
    numericFields?: readonly string[]
    normalizeNumericValue?: (value: string) => string
  },
): Record<string, unknown> {
  const normalized: Record<string, unknown> = { ...entry }
  const numericFields = options?.numericFields ?? LIFETIME_NUMERIC_FIELDS
  const normalizeNumericValue = options?.normalizeNumericValue ?? ((value: string) => value.replace(',', '.'))

  for (const field of numericFields) {
    const value = normalized[field]
    if (value === undefined || value === null) {
      normalized[field] = '0'
      continue
    }
    normalized[field] = normalizeNumericValue(String(value))
  }

  return normalized
}
