/**
 * How the calculators relate, so "what feeds this number?" is a lookup.
 *
 * Two kinds of edge, and they answer different questions:
 *
 *   - **calls** — `epaths.effectiveDamage` calls `spotlight.coverage`. Declared
 *     in `dependsOn`, and a test asserts the caller's module really references
 *     the callee's symbol, so this cannot drift into wishful thinking.
 *   - **concept** — `spotlight.coverage` produces `spotlight.coverage`, which
 *     `epaths.effectiveDamage` reads. Derived from `reads`/`produces` rather
 *     than declared, which is what lets a value be traced back to the formulas
 *     behind it without anyone maintaining a second list.
 *
 * The concept edges are the useful half for an agent. Asking "what moves
 * `damage.effective`?" walks backwards through them and lands on the lab levels
 * and the module rarities, which is the question people actually have.
 */
/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    CalculatorEdge, CalculatorGraph, calculatorGraph, upstreamOf, calculatorsProducing, calculatorsReading
 * depends    src/mechanics/calculators/registry
 * used by    src/mechanics/calculators/index
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */

import { CALCULATORS } from './registry'
import type { CalculatorSpec } from './registry'

export interface CalculatorEdge {
  from: string
  to: string
  kind: 'calls' | 'concept'
  /** For a concept edge, the concept that connects them. */
  via?: string
}

export interface CalculatorGraph {
  nodes: readonly { id: string, title: string, reads: readonly string[], produces: readonly string[] }[]
  edges: readonly CalculatorEdge[]
  /** Every concept named by any calculator, and who touches it. */
  concepts: readonly {
    name: string
    producedBy: readonly string[]
    readBy: readonly string[]
  }[]
}

export function calculatorGraph(): CalculatorGraph {
  const edges: CalculatorEdge[] = []

  for (const spec of CALCULATORS) {
    for (const to of spec.dependsOn) edges.push({ from: spec.id, to, kind: 'calls' })
  }

  const conceptNames = [...new Set(CALCULATORS.flatMap(c => [...c.reads, ...c.produces]))].sort()
  const concepts = conceptNames.map(name => ({
    name,
    producedBy: CALCULATORS.filter(c => c.produces.includes(name)).map(c => c.id),
    readBy: CALCULATORS.filter(c => c.reads.includes(name)).map(c => c.id),
  }))

  for (const concept of concepts) {
    for (const producer of concept.producedBy) {
      for (const reader of concept.readBy) {
        // A calculator that reads what it produces is a fixed point, not an
        // edge — `lab.speedTotal` both reads and produces `lab.speed`.
        if (producer === reader) continue
        edges.push({ from: reader, to: producer, kind: 'concept', via: concept.name })
      }
    }
  }

  return {
    nodes: CALCULATORS.map(c => ({
      id: c.id, title: c.title, reads: c.reads, produces: c.produces,
    })),
    edges,
    concepts,
  }
}

/**
 * Everything that feeds `id`, transitively.
 *
 * Breadth-first and cycle-safe: the concept edges can form one honestly —
 * two calculators that each read something the other produces is a real
 * relationship, not a mistake — so a visited set is load-bearing rather than
 * defensive.
 */
export function upstreamOf(id: string): readonly string[] {
  const { edges } = calculatorGraph()
  const seen = new Set<string>()
  const queue = [id]
  while (queue.length) {
    const current = queue.shift() as string
    for (const edge of edges) {
      if (edge.from !== current || seen.has(edge.to) || edge.to === id) continue
      seen.add(edge.to)
      queue.push(edge.to)
    }
  }
  return [...seen].sort()
}

/** Which calculators produce a named concept — "where does this value come from?" */
export function calculatorsProducing(concept: string): readonly CalculatorSpec[] {
  return CALCULATORS.filter(c => c.produces.includes(concept))
}

/** Which calculators read a named concept — "what breaks if this changes?" */
export function calculatorsReading(concept: string): readonly CalculatorSpec[] {
  return CALCULATORS.filter(c => c.reads.includes(concept))
}
