/**
 * The shape of a declared calculator.
 *
 * Split out from the registry so the spec lists can grow into separate files
 * without a cycle — the lists import the type, the registry imports the lists.
 */
/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    CalculatorParam, CalculatorSpec
 * depends    —
 * used by    src/mechanics/calculators/index, src/mechanics/calculators/registry, src/mechanics/calculators/run, src/mechanics/calculators/specs-catalog, src/mechanics/calculators/specs-formatting, src/mechanics/calculators/specs-generated (+3 more)
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */

/**
 * What a parameter is, in enough detail to call the function blind.
 *
 * `kind` is enforced by `runCalculator` before the call, because a missing or
 * mistyped argument arrives inside the formula as `undefined` and comes back as
 * `NaN` or a fallback — a value, which reads as an answer.
 */
export interface CalculatorParam {
  name: string
  /**
   * `numberOrString` and `unknown` are real cases, not laziness:
   * `formatNumberForDisplay` genuinely takes either, and
   * `formatGroupedNumber` takes whatever a save row held. Forcing them to one
   * kind would make the declaration lie about the function.
   */
  kind: 'number' | 'string' | 'boolean' | 'object' | 'numberOrString' | 'unknown'
  /** Absent means required. */
  optional?: boolean
  describes: string
  /** `days`, `coins`, `stones`, `percent`, `fraction`, `seconds`, `waves`… */
  unit?: string
}

export interface CalculatorSpec {
  /** Stable, dotted, and the handle an agent calls. */
  id: string
  title: string
  /** Which SDK entry point exports it, for `list_exports` to agree with. */
  entry: 'mechanics' | 'data' | 'formatting'
  /** Source module, repo-relative, so a reader can go and look. */
  module: string
  symbol: string
  because: string
  params: readonly CalculatorParam[]
  returns: {
    kind: 'number' | 'string' | 'object' | 'boolean'
    unit?: string
    nullable?: boolean
    describes: string
  }
  /** Prose claims about the range. */
  invariants: readonly string[]
  /** Domain concepts consumed, for the dependency graph. */
  reads: readonly string[]
  /** Domain concepts produced. */
  produces: readonly string[]
  /** Other calculator ids this one calls. VERIFIED against the source. */
  dependsOn: readonly string[]
  /**
   * Whether a human wrote this entry or a generator did.
   *
   * `curated` (the default when absent) means the `because` says what the
   * formula decides and the invariants were CHECKED against the function.
   * `generated` means the parameters were derived from the real signature --
   * so they are accurate -- and the prose is a placeholder, so it is not a
   * claim. Reading the second as the first is the failure the registry exists
   * to prevent, which is why the tier is on the row rather than implied by
   * which file it lives in.
   */
  tier?: 'curated' | 'generated'

  /**
   * Whether it returns a promise.
   *
   * Worth declaring rather than discovering: an async calculator called without
   * its arguments rejects rather than throwing, and a rejection nobody awaited
   * is an unhandled rejection that can take a process down. The registry's own
   * smoke test produced two before this field existed.
   */
  isAsync?: boolean

  /** The Effective Paths cell or lambda it ports, when it ports one. */
  sheet?: string
}
