/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    FAVORITE_LABS_SAVE_FIELD, readFavoriteLabSlugsFromSaveRoot, saveHasFavoriteLabs
 * depends    src/data/labs/research, src/save/access/values
 * used by    src/mechanics/calculators/specs-generated, src/save/labs/index, src/save/labs/read
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
import { findLabResearchByIndex } from '../../data/labs/research'
import { readSaveIntList } from '../access/values'

/**
 * The labs a player has starred in game.
 *
 * The save stores `favoriteLabs` as a Unity `List<int>` of research indices --
 * confirmed against the v28.3.0 dump, where `TowerData.favoriteLabs` is a
 * `List<int>` sitting beside `favoriteLabsPrevious` and
 * `favoriteLabsPositionPrevious`. Indices, not names, so they are resolved
 * through the research catalog rather than matched on text.
 *
 * Returns slugs, which is what the stored `labsFavorites` holds.
 */
export const FAVORITE_LABS_SAVE_FIELD = 'favoriteLabs'

export function readFavoriteLabSlugsFromSaveRoot(
  root: Record<string, unknown> | null | undefined,
): string[] {
  if (!root) return []

  const indices = readSaveIntList(root[FAVORITE_LABS_SAVE_FIELD])
  if (indices.length === 0) return []

  const slugs: string[] = []
  for (const index of indices) {
    // An index the catalog does not know is a save from a newer game build than
    // this catalog. Skipping it is right; inventing a name for it is not.
    const record = findLabResearchByIndex(index)
    if (record?.slug) slugs.push(record.slug)
  }

  return [...new Set(slugs)]
}

/** True when the save carries a favourites list at all, empty or not. */
export function saveHasFavoriteLabs(
  root: Record<string, unknown> | null | undefined,
): boolean {
  return Boolean(root) && root![FAVORITE_LABS_SAVE_FIELD] != null
}
