/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    getStaticLabWorkingLevelDurationHours, estimateLabLevelRemainingSeconds
 * depends    src/data/labs/catalog, src/formatting
 * used by    src/mechanics/calculators/specs-generated, src/save/labs/index, src/save/labs/read
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
import { parseDurationToHours } from '../../formatting'
import { LAB_CATALOG } from '../../data/labs/catalog'

export function getStaticLabWorkingLevelDurationHours(
  displayName: string | null | undefined,
  completedLevel: number,
  labSpeedLevel = 0,
): number | null {
  if (!displayName) return null
  const lab = LAB_CATALOG.find(entry => entry.name === displayName || entry.slug === displayName)
  if (!lab?.levels?.length) return null

  const workingLevel = Math.max(1, Math.floor(Number(completedLevel) || 0) + 1)
  const levelData = lab.levels.find(entry => entry.level === workingLevel)
    ?? lab.levels.find(entry => entry.level === completedLevel)
  if (!levelData) return null

  const baseHours = parseDurationToHours(levelData.duration)
  if (!Number.isFinite(baseHours) || baseHours <= 0) return null

  const normalized = displayName.toLowerCase()
  const isSpeedLab = normalized.includes('lab speed') || normalized.includes('labs speed')
  const speedMultiplier = isSpeedLab ? 1 : 1 + Math.max(0, Number(labSpeedLevel) || 0) * 0.02
  return baseHours / speedMultiplier
}

export function estimateLabLevelRemainingSeconds(
  displayName: string | null | undefined,
  completedLevel: number,
  percentComplete: number | null | undefined,
  labSpeedLevel = 0,
): number | null {
  const durationHours = getStaticLabWorkingLevelDurationHours(displayName, completedLevel, labSpeedLevel)
  if (durationHours == null) return null

  const progress = Math.max(0, Math.min(1, Number(percentComplete) || 0))
  const remainingHours = durationHours * (1 - progress)
  return Math.max(0, Math.round(remainingHours * 3600))
}
