/**
 * Tower premade builders — thin wrappers over existing SDK factories.
 * Do not re-implement formulas; call the canonical exports.
 * Domain-settings factory lives in platform — documented by path only (no sdk→platform import).
 */
/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    TOWER_PREMADE_BUILDER_IDS, applySdkGraphMutate, applyEpGraphMutate, runPlannerCodegen, runPlannerCodegenEmit, runMechanicsDocsGen, listSaveImportPayloadBuilders, describeDomainSettingsBundlePath (+3 more)
 * depends    src/mechanics/ep-graph/mutate, src/mechanics/ep-graph/schema, tooling/planner-engine/codegen, tooling/sdk-graph/mutate, tooling/sdk-graph/schema
 * used by    —
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
import { applySdkGraphMutations, type SdkMutateResult } from '../sdk-graph/mutate'
import type { SdkGraph } from '../sdk-graph/schema'
import { applyEpGraphMutations, type EpMutateResult } from '../../src/mechanics/ep-graph/mutate'
import type { EpGraph } from '../../src/mechanics/ep-graph/schema'
import {
  collectPlannerCitations,
  emitPlannerCodegen,
  type PlannerCitation,
} from '../planner-engine/codegen'

export const TOWER_PREMADE_BUILDER_IDS = [
  'tower.builder.sdk-graph-mutate',
  'tower.builder.ep-graph-mutate',
  'tower.builder.planner-codegen',
  'tower.builder.mechanics-docs',
  'tower.builder.save-import-payload',
  'tower.builder.domain-settings-bundle',
] as const

export function applySdkGraphMutate(graph: SdkGraph, ops: readonly unknown[]): SdkMutateResult {
  return applySdkGraphMutations(graph, ops)
}

export function applyEpGraphMutate(graph: EpGraph, ops: readonly unknown[]): EpMutateResult {
  return applyEpGraphMutations(graph, ops)
}

export function runPlannerCodegen(opts: { family: string }): {
  family: string
  citations: PlannerCitation[]
} {
  return {
    family: opts.family,
    citations: collectPlannerCitations(opts.family),
  }
}

export function runPlannerCodegenEmit(opts: { family: string; repoRoot?: string }) {
  return emitPlannerCodegen(opts.family, { repoRoot: opts.repoRoot })
}

/**
 * Docs generation lives in monorepo-only `docs-gen` (needs governance/doctor).
 * Call via `packages/sdk/src/mechanics/docs-gen` or the mechanics-trust CLI — not the published barrel.
 */
export function runMechanicsDocsGen(): never {
  throw new Error(
    'runMechanicsDocsGen is monorepo-only — import generateMechanicsDocs from packages/sdk/tooling/docs-gen',
  )
}

/** Catalog of known save → tracker payload builder export names (documentation SoT). */
export function listSaveImportPayloadBuilders(): Array<{ exportName: string; module: string }> {
  return [
    { exportName: 'buildVaultImportPayload', module: 'packages/sdk/src/save/vault.ts' },
    { exportName: 'buildGuardiansImportPayload', module: 'packages/sdk/src/save/guardians.ts' },
    { exportName: 'buildWorkshopImportPayload', module: 'packages/sdk/src/save/workshop.ts' },
    { exportName: 'buildLifetimeImportPayload', module: 'packages/sdk/src/save/lifetime.ts' },
    { exportName: 'buildLabsImportPayload', module: 'packages/sdk/src/save/labs.ts' },
    { exportName: 'buildCardsImportPayload', module: 'packages/sdk/src/save/cards.ts' },
    { exportName: 'buildModulesImportPayload', module: 'packages/sdk/src/save/modules.ts' },
    { exportName: 'buildBotsImportPayload', module: 'packages/sdk/src/save/bots.ts' },
    { exportName: 'buildRelicsImportPayload', module: 'packages/sdk/src/save/relics.ts' },
    { exportName: 'buildUltimateWeaponsImportPayload', module: 'packages/sdk/src/save/ultimate-weapons.ts' },
  ]
}

/**
 * Points agents at the canonical domain-settings factory — does not invent bridges.
 * Implementation lives in platform (sdk must not import platform).
 */
export function describeDomainSettingsBundlePath(domainId: string): {
  domainId: string
  platformFactory: string
  wrapsExport: string
  siteBundleDir: string
} {
  return {
    domainId,
    platformFactory: 'packages/platform/src/tools/revisioned-domain-settings-factory.ts',
    wrapsExport: 'buildRevisionedDomainSettingsModule',
    siteBundleDir: 'src/services/domain-settings/',
  }
}

export {
  applySdkGraphMutations,
  applyEpGraphMutations,
  collectPlannerCitations,
}
