/**
 * The account state a calculator takes.
 *
 * A plan needs two things: the numbers a player has bought, and the account
 * around them — which weapons are unlocked, what the labs are set to, which
 * modules are equipped. These are the schemas for that state, with their
 * defaults, normalisers and merge helpers.
 *
 * They already existed, under `internal/`, because the SDK's own calculators
 * consume them. But anything building a tracker on this package needs the same
 * shapes, and `internal/*` is explicitly unstable — so the only way to hold a
 * player's state in the shape the planners accept was to import a path the
 * package reserves the right to move. This is the door.
 *
 * Normalising is the point of every schema here: pass whatever you have stored,
 * get back a complete record with the sheet's own defaults filled in. A field
 * that does not parse is dropped rather than coerced.
 */

/*
 * Exported by name, not with `export *`.
 *
 * These shapes live under `internal/`, and a blanket re-export published everything those
 * modules happened to contain — including this project's own storage layout: RxDB
 * collection names, record ids and the local-persistence schemas its pages validate
 * against. None of that is game data and none of it is useful to anyone building on this
 * package, but all of it was public API, so any of it moving was a breaking change.
 *
 * Naming each export makes the public surface a decision instead of a side effect. Adding
 * one here is deliberate; adding one to an internal module no longer leaks.
 */

export {
  applySharedElsPlannerToEnemyStats,
  applySharedEnemyStatsCore,
  applySharedShardSplitterInputs,
  cardsProgressInputsToLinkedProgress,
  compactSharedToolInputsForStorage,
  computeUnbannedPerkIndices,
  defaultExtendedSharedToolInputs,
  defaultSharedCardsProgressInputs,
  defaultSharedEchoLabLevels,
  defaultSharedEnemyDropsInputs,
  defaultSharedModuleDiscounts,
  defaultSharedModuleEfficiencyLabs,
  defaultSharedNamedCalculatorLabs,
  defaultSharedPerkPreferences,
  defaultSharedToolInputs,
  defaultSharedTradeOffPerks,
  defaultSharedWorkshopDiscounts,
  diffChangedHubKeys,
  enrichElsPlannerFromLinkedSources,
  getSharedToolInputs,
  mergeEnemyStatsCoreHub,
  mergeExtendedSharedToolInputs,
  mergeHubField,
  mergeNestedNumberRecords,
  mergeNumberArrayRecords,
  mergeNumberRecords,
  mergeSharedUptimeInputsHub,
  mergeSparseSharedToolInputs,
  normalizeExtendedSharedToolInputs,
  normalizeSharedCardsProgressInputs,
  normalizeSharedEnemyDropsInputs,
  normalizeSharedPerkPreferences,
  normalizeSharedToolInputs,
  overlaySharedToolInputs,
  readElsPlannerLevels,
  readElsVaultStarsFromVaultLevels,
  readPerkPreferencesFromSaveRoot,
  readSharedBotMedalSplitterPlanner,
  readSharedDamageReduxCalculatorSettings,
  readSharedDissonanceCalculatorState,
  readSharedElsPlannerInputs,
  readSharedEnemyStatsCore,
  readSharedThornsCalculatorSettings,
  sharedEchoLabLevelsSchema,
  sharedModuleDiscountsSchema,
  sharedModuleEfficiencyLabsSchema,
  sharedNamedCalculatorLabsSchema,
  sharedToolInputsSchema,
  sharedTradeOffPerksSchema,
  sharedWorkshopDiscountsSchema,
  syncVaultLevelsFromElsPlanner,
  syncWorkshopStatsFromElsPlanner,
  type SharedEchoLabLevels,
  type SharedModuleDiscounts,
  type SharedModuleEfficiencyLabs,
  type SharedNamedCalculatorLabs,
  type SharedToolInputs,
  type SharedTradeOffPerks,
  type SharedWorkshopDiscounts,
} from '../internal/shared-tool-inputs'

export {
  defaultSharedBotMedalSplitterPlanner,
  defaultSharedBotsSynchronicity,
  defaultSharedDamageReduxCalculatorSettings,
  defaultSharedDissonanceCalculatorState,
  defaultSharedElsPlannerInputs,
  defaultSharedEnemyStatsCore,
  defaultSharedModuleProgressInputs,
  defaultSharedShardSplitterInputs,
  defaultSharedThornsCalculatorSettings,
  defaultSharedVaultLevels,
  defaultSharedWorkshopStatLevels,
  extendedSharedToolInputsSchema,
  mergeShardSplitterInputs,
  sharedBotMedalSplitterPlannerSchema,
  sharedBotsSynchronicitySchema,
  sharedDamageReduxCalculatorSettingsSchema,
  sharedDissonanceCalculatorStateSchema,
  sharedElsPlannerInputsSchema,
  sharedEnemyStatsCoreSchema,
  sharedLabsCalcByLabSchema,
  sharedModuleProgressInputsSchema,
  sharedShardSplitterInputsSchema,
  sharedThornsCalculatorSettingsSchema,
  sharedVaultLevelsSchema,
  sharedWorkshopStatLevelsSchema,
  type SharedBotMedalSplitterPlanner,
  type SharedBotsSynchronicity,
  type SharedDamageReduxCalculatorSettings,
  type SharedDissonanceCalculatorState,
  type SharedElsPlannerInputs,
  type SharedEnemyStatsCore,
  type SharedLabsCalcByLab,
  type SharedModuleProgressInputs,
  type SharedShardSplitterInputs,
  type SharedThornsCalculatorSettings,
  type SharedToolInputsExtended,
  type SharedVaultLevels,
  type SharedWorkshopStatLevels,
} from '../internal/shared-tool-inputs-extended'

export {
  applySharedUptimeInputs,
  buildSharedUptimeInputsFromSources,
  collectUwProgressLevelsFromUptime,
  defaultSharedUptimeInputs,
  getUptimeCoreStateFromSharedInputs,
  isUptimeBotLinkedInputField,
  isUptimeGuardianLinkedInputField,
  isUptimeTrackerLinkedLevelField,
  isUptimeUwLinkedInputField,
  mergeSharedUptimeInputs,
  migrateLegacyUptimeLabLevels,
  overlaySharedUptimeInputsFromTracker,
  readSharedUptimeInputs,
  readUwProgressLevels,
  sharedUptimeInputsSchema,
  syncTrackerBotsFromUptime,
  syncTrackerGuardiansFromUptime,
  syncTrackerUwFromUptime,
  syncUptimeBotsFromTracker,
  syncUptimeFromUwProgressLevels,
  syncUptimeGuardiansFromTracker,
  syncUptimeUwFromTracker,
  type SharedUptimeInputs,
  type SharedUptimeRarityPick,
  type UptimeBotFieldMap,
  type UptimeGuardianFieldMap,
  type UptimeUwFieldMap,
  type UwProgressLevels,
  UPTIME_BOT_FIELD_MAP,
  UPTIME_GUARDIAN_FIELD_MAP,
  UPTIME_RESEARCH_LAB_FIELD_KEYS,
  UPTIME_UW_FIELD_MAP,
  uptimeCompressorSchema,
  uptimeMvnModeSchema,
  uptimeRarityPickSchema,
  uwProgressLevelsSchema,
} from '../internal/shared-uptime-inputs'

export {
  computeResearchLabLevel,
  enrichSharedToolInputs,
  readEchoLabLevelsFromResearchLevels,
  readLabsEconomyFromResearchLevels,
  readModuleEconomyFromResearchLevels,
  readNamedCalculatorLabs,
  readWorkshopDiscounts,
  syncUptimeResearchLabsFromTracker,
  type EnrichSharedToolInputsFromResearchOptions,
} from '../internal/shared-tool-inputs-from-research'

export {
  buildResearchHubLevels,
  buildTrackerCurrentLabLevels,
  coerceLabsTrackerLabLevel,
  defaultSharedLabsSettings,
  findCanonicalLabResearchSlug,
  labsTrackerLabLevelMapsEqual,
  normalizeLabsTrackerLabLevelMap,
  normalizeSharedLabLevelRange,
  normalizeSharedLabsSettings,
  sharedLabLevelRangeSchema,
  sharedLabsSettingsSchema,
  type SharedLabLevelRange,
  type SharedLabsSettings,
} from '../internal/labs-persistence'

export {
  sharedCardsProgressInputsSchema,
  type CardsLinkedProgress,
  type SharedCardsProgressInputs,
} from '../internal/cards-progress-inputs'

export {
  allBotPlusUnlockedForSync,
  BOT_MEDAL_PLANNER_FOCUS_GOALS,
  BOT_MEDAL_SPLITTER_PRESET_COUNT,
  BOT_PLUS_LEVEL_LOCKED,
  botMedalPlannerFocusGoalLabel,
  BOTS_MEDAL_SPLITTER_TAB,
  buildBotMedalSplitterBaseLocks,
  buildBotMedalSplitterPlusLocks,
  buildDefaultBotMedalSplitterLevels,
  buildDefaultBotMedalSplitterPlusLevels,
  buildDefaultBotMedalSplitterPreset,
  buildDefaultBotMedalSplitterPresets,
  clampBotMedalSplitterBudget,
  clampBotMedalSplitterInt,
  clampDissonanceInt,
  DEFAULT_BOT_MEDAL_SPLITTER_TOWER_RANGE,
  DEFAULT_DAMAGE_REDUX_COLUMN_ORDER,
  DEFAULT_DAMAGE_REDUX_SELECTED_COLUMNS,
  DEFAULT_MODULES_COSTS_ASSIST_COLUMNS,
  DEFAULT_MODULES_COSTS_PRIMARY_COLUMNS,
  DEFAULT_UPTIME_CHART_ORDER,
  defaultBotMedalSplitterLocalState,
  defaultBotsCalcsLocalState,
  defaultDamageReduxCalcsLocalState,
  defaultDissonanceCalcsLocalState,
  defaultDissonanceMaxFlags,
  defaultDissonanceWaveInputs,
  defaultEnemyDropsCalcsLocalState,
  defaultEnemyStatsCalcsLocalState,
  defaultGuardiansCalcsLocalState,
  defaultLabsCalcsLocalState,
  defaultModulesCalcsLocalState,
  defaultShardSplitterLocalState,
  defaultThornsCalcsSettings,
  defaultTournamentPerformanceLocalState,
  defaultUptimeChartLocalState,
  defaultWorkshopCalcsLocalState,
  DISSONANCE_COLUMN_KEYS,
  DISSONANCE_MAX_EFFECTIVE_WAVE,
  DISSONANCE_TYPE_KEYS,
  ENEMY_DROPS_CALCULATOR_PATHS_TABS,
  ENEMY_DROPS_CALCULATOR_TABS,
  ENEMY_STATS_CALCS_RESEARCH_LAB_SLUGS,
  ensureThornsCalcsSettingsRules,
  getBotMedalPlannerFocusWeights,
  isBotPlusLevelLocked,
  labsCalcsLocalStateSchema,
  LEGACY_ENEMY_DROPS_CALCULATOR_TABS,
  migrateLegacyEnemyDropsActiveTab,
  normalizeBotMedalPlannerFocusOrder,
  normalizeBotMedalSplitterLocalState,
  normalizeBotMedalSplitterShRarity,
  normalizeBotMedalSplitterSynced,
  normalizeBotMedalSplitterTargetOrder,
  normalizeBotsCalcsLocalState,
  normalizeDamageReduxCalcsLocalState,
  normalizeDissonanceCalcsLocalState,
  normalizeEnemyDropsCalcsLocalState,
  normalizeEnemyStatsCalcsLocalState,
  normalizeGuardiansCalcsLocalState,
  normalizeLabsCalcsLocalState,
  normalizeModulesCalcsLocalState,
  normalizePlannerPlusLevel,
  normalizeShardSplitterLocalState,
  normalizeThornsCalcsLocalState,
  normalizeThornsCalcsSettings,
  normalizeTournamentPerformanceLocalState,
  normalizeUptimeChartLocalState,
  normalizeWorkshopCalcsLocalState,
  sharedEnemyDropsInputsSchema,
  targetBotMedalSplitterBotLabels,
  type BotMedalPlannerFocusGoal,
  type BotMedalPlannerFocusWeights,
  type BotMedalSplitterLocalState,
  type BotMedalSplitterPreset,
  type BotMedalSplitterShRarity,
  type BotMedalSplitterTargetConfig,
  type BotsCalcsLocalState,
  type DamagePathColumnKey,
  type DamageReduxCalcsLocalState,
  type DamageReduxColumnKey,
  type DissonanceCalcsLocalState,
  type DissonanceColumnKey,
  type DissonanceMaxFlags,
  type DissonanceTypeKey,
  type DissonanceWaveInputs,
  type EnemyDropsCalcsLocalState,
  type EnemyDropsCalculatorPathsTab,
  type EnemyDropsCalculatorTab,
  type EnemyStatsCalcsElsFocus,
  type EnemyStatsCalcsLabLevels,
  type EnemyStatsCalcsLocalState,
  type EnemyStatsCalcsMode,
  type EnemyStatsCalcsResearchLabSlug,
  type EnemyStatsCalcsTierSelection,
  type EnhancementDiscountsLocalState,
  type GuardiansCalcsLocalState,
  type GuardiansCalcsMainTab,
  type LabCalcRange,
  type LabsCalcsLocalState,
  type LegacyEnemyDropsCalculatorTab,
  type ModulesCalcsLocalState,
  type ShardSplitterColumns,
  type ShardSplitterLocalState,
  type SharedEnemyDropsInputs,
  type SplitColumnKey,
  type ThornsCalcsLocalState,
  type ThornsCalcsSettings,
  type ThornsCalcsTournamentTier,
  type TournamentPerformanceLocalState,
  type UptimeChartLocalState,
  type UptimeChartOrientation,
  type UptimeChartView,
  type WorkshopCalcsLocalState,
  type WorkshopDiscountsLocalState,
  type WorkshopFormLocalState,
} from '../internal/calculator-local-state-schemas'

export {
  buildDefaultShardSplitterSnapshot,
  moduleTypes,
  moduleTypeSchema,
  normalizeShardSplitterSnapshot,
  shardSplitterSnapshotSchema,
  splitterByTypeSchema,
  splitterDataSchema,
  type ModuleType,
  type ShardSplitterSnapshot,
  type SplitterByType,
  type SplitterData,
} from '../internal/shard-splitter-schema'

export {
  ASSIST_EFFICIENCY_SELECTABLE_MAX,
  assistPctItems,
  discountItems,
  getStoneCostOptions,
  getStoneTargetOptions,
  MODULE_RARITY_STEP_COSTS,
  moduleTypeItems,
  type ModuleSelectItem,
  type NumericSelectItem,
  type StoneCostOption,
} from '../internal/module-calculator-options'

export {
  advanceRetryScheduleState,
  applyRetryFailureState,
  buildRetryScheduleState,
  computeCloudStateDirection,
  computeExponentialBackoffMs,
  enqueueUniqueItemsByKey,
  getRetryQueueDisposition,
  hasReachedRetryLimit,
  isRetryScheduleReady,
  normalizeRetryAttemptCount,
  parseIsoTimestampToMillis,
  parseRetryScheduleState,
  partitionRetryQueueItems,
  replaceOrInsertMatchingItem,
  settleRetryQueueItems,
  stableEquals,
  stableSerialize,
  toObjectRecord,
  type CloudStateDirection,
  type ReplaceOrInsertQueueItemResult,
  type RetryQueueDisposition,
  type RetryQueueFailedItem,
  type RetryQueuePartition,
  type RetryQueueProcessResult,
  type RetryQueueSettlement,
  type RetryScheduleState,
  type RetryScheduleUpdateOptions,
  type UniqueQueueEnqueueResult,
} from '../internal/persistence-primitives'

export {
  normalizeUptimePersistedPayload,
  type UptimePersistedPayload,
  uptimeColumnsStateSchema,
  uptimePersistedPayloadSchema,
  uptimeTableSettingsSchema,
  uptimeUiStateSchema,
} from '../internal/uptime-persistence'
