/**
 * Which enemy ended a run.
 *
 * The save writes an internal name; the display name differs for several enemies, and the two are
 * mapped rather than assumed equal.
 */
/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    —
 * depends    src/save/killed-by/read
 * used by    —
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
export * from './read'
