/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    SAVE_FILE_KILLED_BY_ENEMY_NAMES, SAVE_FILE_KILLED_BY_EXTRA_INDEX_NAMES, SAVE_FILE_KILLED_BY_APATHY_INDICES, SAVE_FILE_KILLED_BY_OVERCHARGE_INDICES, normalizeKilledByDisplayLabel, readKilledByEnumIndex, enemyDisplayNameFromSaveEnumIndex, getKilledByFromSave
 * depends    src/support/own-lookup
 * used by    src/mechanics/calculators/specs-generated, src/save/battle/reports, src/save/index, src/save/killed-by/index
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
import { ownLookup } from '../../support/own-lookup'
/**
 * NRBF stores enums as `{ typeName, value__ }`. When the game serializes the member
 * name, `typeName` looks like `…EnemyType+Ray` and we prefer that over the numeric
 * index; otherwise only `value__` is available and the table below resolves it.
 */
/**
 * Enemy index -> display name, in save-file order:
 *
 *   Basic 0, Fast 1, Tank 2, Boss 3, Ranged 4, Protector 5, Vampire 6,
 *   ScatterMain 7, ScatterChild 8, Ray 9, Saboteur 10, Commander 11,
 *   Overcharge 12
 *
 * `ScatterMain` and `ScatterChild` are a single enemy to the player and both
 * display as "Scatter"; they occupy two indices regardless.
 *
 * This order is not the order enemies appear in the game's UI, in an
 * encyclopedia, or in kill-counter columns — those differ. Collapsing the two
 * scatter entries into one, or sorting to match the UI, shifts every index from
 * 7 onward and silently misreports deaths (a Ray kill reads as Saboteur, a
 * Saboteur kill as Commander). Change this table only alongside a save file
 * that proves the new order.
 */
export const SAVE_FILE_KILLED_BY_ENEMY_NAMES: readonly string[] = [
  'Basic', // 0
  'Fast', // 1
  'Tank', // 2
  'Boss', // 3
  'Ranged', // 4
  'Protector', // 5
  'Vampire', // 6
  'Scatter', // 7 — ScatterMain
  'Scatter', // 8 — ScatterChild
  'Ray', // 9
  'Saboteur', // 10
  'Commander', // 11
  'Overcharge', // 12
] as const

/** Indices outside the enum above that need a name. None are currently known. */
export const SAVE_FILE_KILLED_BY_EXTRA_INDEX_NAMES: Readonly<Record<number, string>> = {}

/** Sentinel `value__` values meaning Apathy / no enemy killer. */
export const SAVE_FILE_KILLED_BY_APATHY_INDICES: ReadonlySet<number> = new Set([-1, 99, 255])

/**
 * Overcharge is index 12. Names resolve from the table above; this set exists
 * for callers that need to test for Overcharge specifically.
 */
export const SAVE_FILE_KILLED_BY_OVERCHARGE_INDICES: ReadonlySet<number> = new Set([12])

const KILLED_BY_LABEL_ALIASES: Readonly<Record<string, string>> = {
  apathy: 'Apathy',
  none: 'Apathy',
  unknown: 'Apathy',
  range: 'Ranged',
  ranges: 'Ranged',
  vampires: 'Vampire',
  vampire: 'Vampire',
  rays: 'Ray',
  ray: 'Ray',
  scatters: 'Scatter',
  scatter: 'Scatter',
  // The engine splits scatter into two enum members; both are one enemy to the
  // player. Matching them explicitly rather than by substring keeps resolution
  // from depending on ordering inside TYPE_NAME_EMBEDDED_NAMES.
  scattermain: 'Scatter',
  scatterchild: 'Scatter',
  saboteurs: 'Saboteur',
  saboteur: 'Saboteur',
  commanders: 'Commander',
  commander: 'Commander',
  overcharges: 'Overcharge',
  overcharge: 'Overcharge',
}

const CANONICAL_NAME_LOOKUP: ReadonlyMap<string, string> = new Map(
  [
    'Apathy',
    ...SAVE_FILE_KILLED_BY_ENEMY_NAMES,
  ].map(name => [name.toLowerCase(), name]),
)

/** Longest-first so `Overcharge` wins over shorter partial matches. */
const TYPE_NAME_EMBEDDED_NAMES: readonly string[] = [
  'ScatterMain',
  'ScatterChild',
  'Overcharge',
  'Commander',
  'Saboteur',
  'Protector',
  'Scatter',
  'Vampire',
  'Apathy',
  'Ranged',
  'Basic',
  'Fast',
  'Tank',
  'Boss',
  'Ray',
]

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value)
}

function readFiniteInt(value: unknown): number | null {
  if (typeof value === 'number' && Number.isFinite(value)) {
    return Number.isInteger(value) ? value : Math.trunc(value)
  }
  if (typeof value === 'string' && value.trim() !== '') {
    const parsed = Number(value.trim())
    if (Number.isFinite(parsed) && Number.isInteger(parsed)) {
      return parsed
    }
  }
  return null
}

/**
 * Normalizes a display or serialized enemy label to the canonical English name
 * used by OCR parsing and run storage.
 */
export function normalizeKilledByDisplayLabel(label: string): string {
  const trimmed = label.trim()
  if (!trimmed) {
    return 'Apathy'
  }

  // Own keys only — this label comes straight out of a save file.
  const alias = ownLookup(KILLED_BY_LABEL_ALIASES, trimmed.toLowerCase())
  if (alias) {
    return alias
  }

  const canonical = CANONICAL_NAME_LOOKUP.get(trimmed.toLowerCase())
  return canonical ?? trimmed
}

function tryParseEnumMemberFromTypeName(typeName: string): string | null {
  const plusIndex = typeName.lastIndexOf('+')
  if (plusIndex >= 0) {
    const member = typeName.slice(plusIndex + 1).trim()
    if (member && member !== 'value__') {
      const normalized = normalizeKilledByDisplayLabel(member)
      if (
        normalized !== member
        || CANONICAL_NAME_LOOKUP.has(member.toLowerCase())
        || member === 'Apathy'
      ) {
        return normalized
      }
    }
  }

  const commaIndex = typeName.lastIndexOf(',')
  if (commaIndex >= 0) {
    const member = typeName.slice(commaIndex + 1).trim()
    if (member) {
      const normalized = normalizeKilledByDisplayLabel(member)
      if (
        normalized !== member
        || CANONICAL_NAME_LOOKUP.has(member.toLowerCase())
        || member === 'Apathy'
      ) {
        return normalized
      }
    }
  }

  for (const name of TYPE_NAME_EMBEDDED_NAMES) {
    if (typeName.includes(name)) {
      return normalizeKilledByDisplayLabel(name)
    }
  }

  return null
}

/**
 * Reads the integer enum index from a battle-history `killedBy` field.
 * Returns null when the value is missing or not a recognized shape.
 */
export function readKilledByEnumIndex(raw: unknown): number | null {
  if (raw === null || raw === undefined) {
    return null
  }

  const direct = readFiniteInt(raw)
  if (direct !== null) {
    return direct
  }

  if (!isRecord(raw)) {
    return null
  }

  if ('value__' in raw) {
    return readFiniteInt(raw.value__)
  }

  if ('value' in raw) {
    return readFiniteInt(raw.value)
  }

  return null
}

/**
 * Maps a save-file enemy enum index to the canonical English display name.
 */
export function enemyDisplayNameFromSaveEnumIndex(index: number): string {
  if (SAVE_FILE_KILLED_BY_APATHY_INDICES.has(index)) {
    return 'Apathy'
  }

  if (SAVE_FILE_KILLED_BY_OVERCHARGE_INDICES.has(index)) {
    return 'Overcharge'
  }

  const extra = ownLookup(SAVE_FILE_KILLED_BY_EXTRA_INDEX_NAMES, index)
  if (extra) {
    return extra
  }

  /*
   * An array, not a record, so an explicit bounds check rather than an own-key one — and
   * an integer check with it, because `names[1.5]` and `names['constructor']` both miss
   * the elements and reach for a property instead.
   */
  const name = Number.isInteger(index) && index >= 0 && index < SAVE_FILE_KILLED_BY_ENEMY_NAMES.length
    ? SAVE_FILE_KILLED_BY_ENEMY_NAMES[index]
    : undefined
  if (name) {
    return name
  }

  return `Enemy Type ${index}`
}

/**
 * Resolves a battle-history `killedBy` value (enum object, index, or string) to the
 * canonical display name used elsewhere. Does not affect OCR parsing.
 */
export function getKilledByFromSave(raw: unknown, fallback = 'Apathy'): string {
  if (typeof raw === 'string') {
    const trimmed = raw.trim()
    return trimmed ? normalizeKilledByDisplayLabel(trimmed) : fallback
  }

  if (isRecord(raw) && typeof raw.typeName === 'string') {
    const fromTypeName = tryParseEnumMemberFromTypeName(raw.typeName)
    if (fromTypeName) {
      return fromTypeName
    }
  }

  const index = readKilledByEnumIndex(raw)
  if (index === null) {
    return fallback
  }

  return enemyDisplayNameFromSaveEnumIndex(index)
}
