/**
 * Utilities with no domain of their own.
 *
 * This domain is flat: Rule 1 defines it that way — utilities with no domain of their own,
 * capped at ten files. Anything here that earned a subfolder would have earned a domain.
 *
 * Rule 1 of the organization contract: this folder is NOT exported, holds only framework-free
 * helpers that know nothing about The Tower and nothing about any application, and is capped at
 * ten files. Past ten, something in here has a domain and belongs in it.
 */
/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    —
 * depends    src/support/own-lookup
 * used by    —
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
export * from './own-lookup'
