/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    GameDropdownHubContext, getGameDataHubGroups, GAME_DATA_HUB_GROUPS, buildGameDropdownHubContext, computeBotGameInputLab, computeGoldenBotCooldownLab
 * depends    src/internal/cards-progress-inputs, src/internal/game-input-data/bot-dropdown-math, src/internal/game-input-data/bot-game-input-keys, src/internal/game-input-data/dissonance-echo-lab-keys, src/internal/game-input-data/game-data-registry, src/internal/game-input-data/guardian-game-input-keys (+4 more)
 * used by    src/internal/game-input-data/dropdown-evaluator, src/internal/game-input-data/extended-dropdown-evaluators, src/internal/game-input-data/index, src/mechanics/calculators/specs-generated
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
import type { SharedCardsProgressInputs } from '../cards-progress-inputs'
import type { SharedInputGroupId } from './shared-input-groups'
import type { SharedToolInputs } from '../shared-tool-inputs'
import type { SharedUptimeInputs } from '../shared-uptime-inputs'
import {
  BOT_GAME_INPUT_SPEC_BY_KEY,
  type BotGameDataKey,
  normalizeGameDataKey,
} from './bot-game-input-keys'
import {
  GUARDIAN_GAME_INPUT_SPEC_BY_KEY,
  type GuardianGameDataKey,
} from './guardian-game-input-keys'
import {
  UPTIME_RESEARCH_LAB_SPEC_BY_KEY,
  type UptimeResearchLabDataKey,
} from './uptime-research-lab-keys'
import {
  DISSONANCE_ECHO_LAB_SPEC_BY_KEY,
  type DissonanceEchoLabDataKey,
} from './dissonance-echo-lab-keys'
import {
  type BotGameInputKind,
  findBotLabStatName,
  findUptimeLabFieldName,
} from './bot-dropdown-math'
import { findRegistryGameDataKey, type GameDataKey } from './game-data-registry'

export interface GameDropdownHubContext {
  uptimeInputs?: Partial<SharedUptimeInputs>
  botLabLevels?: Record<string, Record<string, number | undefined>>
  cardsProgressInputs?: Partial<SharedCardsProgressInputs>
  guardianLevels?: Record<string, number[]>
  researchLabLevels?: Record<string, number>
  /** Parametric slug for `research_lab_level` dropdown evaluation. */
  researchLabSlug?: string
  /** Parametric enhancement key for `workshop_enhancement_level` dropdown evaluation. */
  workshopEnhancementKey?: string
  /** Parametric guardian stat for `guardian_stat_level` dropdown evaluation. */
  guardianStatSpec?: { guardianKey: string; statField: string }
  /** Parametric UW stat for `uw_stat_level` dropdown evaluation. */
  uwStatSpec?: { weaponKey: string; statName: string }
  /** Parametric workshop stat for `workshop_stat_level` / tier dropdown evaluation. */
  workshopStatKey?: string
  /** Coin/cash tier kind for `workshop_tier_level`. */
  workshopTierKind?: 'coin' | 'cash'
  /** Minimum tier level when building cash tier options. */
  workshopTierMinimumLevel?: number
  /** Module template id for `module_rarity` dropdown evaluation. */
  moduleTemplateId?: string
  /** Module rarity label for `module_level` dropdown evaluation. */
  moduleRarity?: string
  /** Max module rarity for filtering `module_substat_rarity` options. */
  moduleMaxRarity?: string
  /** Uptime module substat pick kind for `uptime_substat_pick`. */
  uptimeSubstatPickKind?: string
  /** Primary vs assist labels for `uptime_substat_pick`. */
  uptimeSubstatPickRole?: 'primary' | 'assist'
  /** Assist efficiency percent for uptime assist substat labels. */
  uptimeAssistEffPct?: number
  /** Minimum assist efficiency percent for `uptime_assist_efficiency`. */
  uptimeAssistMinPct?: number
  /** ELS module substat label for `els_module_substat_rarity`. */
  elsModuleSubstatLabel?: string
  /** Unique module id for `ilm_unique_module_rarity`. */
  ilmUniqueModuleId?: string
  /** Workshop calculator tab for section/stat pickers. */
  workshopCalcTab?: 'workshop' | 'enhancements'
  /** Workshop calculator section slug. */
  workshopCalcSection?: string
  /** Workshop calculator discount profile. */
  workshopDiscountProfile?: 'workshop' | 'enhancement' | 'vault'
  /** Module stone cost profile for assist-module-cost. */
  moduleStoneCostProfile?: 'current' | 'target'
  /** Max level for generic lab level dropdowns. */
  genericLabLevelMax?: number
  /** Thorns tournament tier for heat wave labels. */
  thornsTournamentTier?: string
  /** Bot-bot bonus multiplier for flame bot effective labels. */
  botBotBonusMultiplier?: number
  /** Max card copies for `card_copies_owned`. */
  cardCopiesMax?: number
  /** Max equipped card slots for `card_equipped_slots`. */
  cardEquippedSlotsMax?: number
  /** Module type filter for `module_template_picker` (`All` or category). */
  moduleTypeFilter?: string
  /** Include `custom` entry for tracker sort dropdowns. */
  includeCustomSortOption?: boolean
  /** Workshop tracker sort profile. */
  workshopTrackerSortProfile?: 'workshop' | 'enhancements'
  /** Equipped module slot category for `module_equipped_picker`. */
  moduleEquippedCategory?: string
  /** Template ids to exclude from equipped module picker. */
  moduleEquippedExcludeTemplateIds?: string[]
  /** Module category for `module_substat_type_picker`. */
  moduleSubstatCategory?: string
  /** Substat ids already equipped in slot. */
  moduleSubstatExcludeIds?: string[]
  /** Filter substat types by selected rarity. */
  moduleSubstatFilterRarity?: string | null
  /** Max substat rarity from equipped module. */
  moduleSubstatMaxRarity?: string | null
  /** Card template ids to exclude from card picker. */
  cardTemplateExcludeIds?: string[]
  /** Dynamic lab type labels for `labs_type_filter`. */
  labsTypeFilterOptions?: string[]
  /** Preset labels for `bots_tracker_preset`. */
  trackerPresetLabels?: string[]
  /** Active type filter for `labs_name_picker`. */
  labsTypeFilter?: string
  /** Lab names to keep visible when filtered out of `labs_name_picker`. */
  labsNamePickerIncludeNames?: string[]
  /** Runtime lab entries for `labs_name_picker` (falls back to platform labs). */
  labsNamePickerRuntimeEntries?: Array<{ name: string; label: string; type: string }>
  /** Prefix lab type in `labs_name_picker` labels when filter is All. */
  labsNamePickerShowTypePrefix?: boolean
  /** Selected lab name for `labs_tracker_level`. */
  labsTrackerLabName?: string
  /** Level range mode for `labs_tracker_level`. */
  labsTrackerLevelMode?: 'current' | 'next' | 'target'
  /** Minimum level override for `labs_tracker_level`. */
  labsTrackerLevelMin?: number
  /** Maximum level override for `labs_tracker_level`. */
  labsTrackerLevelMax?: number
  /** Dynamic string options for `ui_dynamic_dropdown`. */
  uiDynamicDropdownOptions?: Array<{ value: string; label: string; subtitle?: string }>
}

const CARD_GAME_DATA_HUB_GROUPS: Partial<Record<GameDataKey, readonly SharedInputGroupId[]>> = {
  wave_accelerator_level: ['cardsProgressInputs', 'uptimeInputs'],
  card_game_level: ['cardsProgressInputs'],
  card_mastery: ['cardsProgressInputs'],
  card_mastery_select: ['cardsProgressInputs'],
  uptime_wa_level: ['uptimeInputs', 'cardsProgressInputs'],
  gold_bot_cooldown: ['uptimeInputs', 'botLabLevels'],
}

function isBotGameDataKey(key: string): key is BotGameDataKey {
  return key in BOT_GAME_INPUT_SPEC_BY_KEY
}

function isGuardianGameDataKey(key: string): key is GuardianGameDataKey {
  return key in GUARDIAN_GAME_INPUT_SPEC_BY_KEY
}

function isUptimeResearchLabGameDataKey(key: string): key is UptimeResearchLabDataKey {
  return key in UPTIME_RESEARCH_LAB_SPEC_BY_KEY
}

function isDissonanceEchoLabGameDataKey(key: string): key is DissonanceEchoLabDataKey {
  return key in DISSONANCE_ECHO_LAB_SPEC_BY_KEY
}

/**
 * Keys whose hub groups follow from the family they belong to rather than from
 * the key itself. Order matters: the first match wins, as it did when this was
 * a chain of `if`s.
 */
const HUB_GROUPS_BY_FAMILY: ReadonlyArray<{
  matches: (key: GameDataKey) => boolean
  groups: readonly SharedInputGroupId[]
}> = [
  {
    matches: key => isBotGameDataKey(key) || key === 'gold_bot_cooldown',
    groups: ['uptimeInputs', 'botLabLevels'],
  },
  { matches: isGuardianGameDataKey, groups: ['guardianLevels', 'uptimeInputs'] },
  { matches: isUptimeResearchLabGameDataKey, groups: ['researchLabLevels', 'uptimeInputs'] },
  { matches: isDissonanceEchoLabGameDataKey, groups: ['researchLabLevels'] },
]

/** Keys that name their own groups. */
const HUB_GROUPS_BY_KEY: Partial<Record<GameDataKey, readonly SharedInputGroupId[]>> = {
  research_lab_level: ['researchLabLevels'],
  guardian_stat_level: ['guardianLevels'],
  uw_stat_level: ['uwProgressLevels', 'uptimeInputs'],
  workshop_stat_level: ['workshopStatLevels'],
  workshop_tier_level: ['workshopStatLevels'],
}

/**
 * Keys that feed no hub group at all — inputs local to the tool that shows
 * them, so nothing else needs to hear about a change.
 */
const HUB_GROUPLESS_KEYS: ReadonlySet<string> = new Set([
  'module_rarity',
  'module_level',
  'module_quantity',
  'module_substat_rarity',
  'module_discount_pct',
  'module_assist_efficiency',
  'uptime_substat_pick',
  'uptime_mvn_mode',
  'uptime_compressor',
  'uptime_waves_per_boss',
  'uptime_assist_efficiency',
  'els_module_substat_rarity',
  'ilm_module_substat_rarity',
  'ilm_unique_module_rarity',
  'els_workshop_utility_discount',
  'els_workshop_enhancement_discount',
  'els_workshop_vault_discount',
  'els_vault_star_level',
  'els_assist_substat_efficiency',
  'enemy_tier_selection',
  'els_focus',
  'module_type_category',
  'module_lab_efficiency_level',
  'module_stone_cost_level',
  'generic_lab_level',
  'card_copies_owned',
  'card_equipped_slots',
  'module_tracker_type_filter',
  'module_tracker_rarity_filter',
  'module_tracker_sort',
  'card_tracker_sort',
  'labs_tracker_sort',
  'module_template_picker',
  'card_template_picker',
  'module_equipped_picker',
  'module_substat_type_picker',
  'workshop_tracker_category_filter',
  'workshop_tracker_sort',
  'workshop_overview_layout',
  'bots_tracker_sort',
  'bots_tracker_preset',
  'guardians_tracker_sort',
  'uw_tracker_sort',
  'uw_overview_view',
  'relics_bonus_sort',
  'relics_themes_sort',
  'labs_speedup_multiplier',
  'labs_type_filter',
  'workshop_enhancement_level',
])

/** The same, for families of keys named by prefix. */
const HUB_GROUPLESS_PREFIXES = ['damage_reduction_', 'thorns_', 'workshop_calc_'] as const

export function getGameDataHubGroups(key: GameDataKey): readonly SharedInputGroupId[] {
  for (const family of HUB_GROUPS_BY_FAMILY) {
    if (family.matches(key)) return family.groups
  }

  const named = HUB_GROUPS_BY_KEY[key]
  if (named) return named

  if (HUB_GROUPLESS_KEYS.has(key)) return []
  if (HUB_GROUPLESS_PREFIXES.some(prefix => key.startsWith(prefix))) return []

  return CARD_GAME_DATA_HUB_GROUPS[key] ?? []
}

/** @deprecated Use getGameDataHubGroups(key) */
export const GAME_DATA_HUB_GROUPS = new Proxy({} as Record<GameDataKey, readonly SharedInputGroupId[]>, {
  get(_target, prop: string) {
    const key = findRegistryGameDataKey(prop)
    return key ? getGameDataHubGroups(key) : []
  },
})

export function buildGameDropdownHubContext(
  key: GameDataKey | string,
  inputs: SharedToolInputs | GameDropdownHubContext,
): GameDropdownHubContext {
  const resolvedKey = findRegistryGameDataKey(String(key))
  if (!resolvedKey) return {}

  const groups = getGameDataHubGroups(resolvedKey)
  const context: GameDropdownHubContext = {}

  for (const groupId of groups) {
    switch (groupId) {
      case 'uptimeInputs':
        context.uptimeInputs = inputs.uptimeInputs
        break
      case 'botLabLevels':
        context.botLabLevels = inputs.botLabLevels
        break
      case 'cardsProgressInputs':
        context.cardsProgressInputs = inputs.cardsProgressInputs
        break
      case 'guardianLevels':
        context.guardianLevels = inputs.guardianLevels
        break
      case 'researchLabLevels':
        context.researchLabLevels = inputs.researchLabLevels
        break
      default:
        break
    }
  }

  return context
}

function readNumericField(record: Record<string, unknown> | undefined, field: string): number | null {
  if (!record) return null
  const value = Number(record[field])
  return Number.isFinite(value) ? Math.floor(value) : null
}

function resolveBotLabLevelForKind(
  context: GameDropdownHubContext,
  botLabel: string,
  labStatName: string,
  uptimeField: string | null,
  cap: number,
): number {
  const uptimeLab = uptimeField ? readNumericField(context.uptimeInputs as Record<string, unknown> | undefined, uptimeField) : null
  const botLab = readNumericField(context.botLabLevels?.[botLabel], labStatName)
  const resolved = Math.max(uptimeLab ?? 0, botLab ?? 0)
  return Math.min(cap, Math.max(0, resolved))
}

export function computeBotGameInputLab(
  context: GameDropdownHubContext,
  key: BotGameDataKey | 'gold_bot_cooldown',
  kind?: BotGameInputKind,
): number {
  const normalized = normalizeGameDataKey(String(key)) as BotGameDataKey
  const spec = BOT_GAME_INPUT_SPEC_BY_KEY[normalized]
  if (!spec) return 0

  const resolvedKind = kind ?? spec.kind
  if (resolvedKind === 'cd_lab' || resolvedKind === 'dur_lab') {
    return 0
  }

  const labStatName = findBotLabStatName(spec.mapping, resolvedKind === 'cd_level' ? 'cd_level' : 'dur_level')
  const uptimeField = findUptimeLabFieldName(spec.mapping, resolvedKind === 'cd_level' ? 'cd_level' : 'dur_level')
  if (!labStatName) return 0

  const cap = resolvedKind === 'cd_level' ? 25 : 20
  return resolveBotLabLevelForKind(context, spec.mapping.botLabel, labStatName, uptimeField, cap)
}

/** @deprecated Use computeBotGameInputLab(context, 'gb_cd_level') */
export function computeGoldenBotCooldownLab(context: GameDropdownHubContext): number {
  return computeBotGameInputLab(context, 'gb_cd_level', 'cd_level')
}
