/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    MODULE_TRACKER_CATEGORIES, MODULE_TRACKER_TYPE_FILTER_VALUES, ModuleTrackerTypeFilter, MODULE_TRACKER_RARITY_FILTER_VALUES, ModuleTrackerRarityFilter, MODULE_TRACKER_SORT_VALUES, ModuleTrackerSortKey, CARD_TRACKER_SORT_VALUES (+90 more)
 * depends    src/data/index, src/internal/game-input-data/types
 * used by    src/internal/game-input-data/extended-dropdown-evaluators, src/internal/game-input-data/index, src/internal/game-input-data/module-template-dropdown-math, src/mechanics/calculators/specs-generated
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
import { MODULE_RARITIES } from '../../data/index'
import { TOOL_LAB_SPEEDUP_OPTIONS } from '../../data/index'
import type { ModuleCategory } from '../../data/index'
import type { GameDropdownOptionEntry } from './types'

export const MODULE_TRACKER_CATEGORIES = ['Cannon', 'Armor', 'Generator', 'Core'] as const satisfies readonly ModuleCategory[]

export const MODULE_TRACKER_TYPE_FILTER_VALUES = ['All', ...MODULE_TRACKER_CATEGORIES] as const
export type ModuleTrackerTypeFilter = (typeof MODULE_TRACKER_TYPE_FILTER_VALUES)[number]

export const MODULE_TRACKER_RARITY_FILTER_VALUES = ['All', ...MODULE_RARITIES] as const
export type ModuleTrackerRarityFilter = (typeof MODULE_TRACKER_RARITY_FILTER_VALUES)[number]

export const MODULE_TRACKER_SORT_VALUES = ['name', 'type', 'rarity', 'progress', 'custom'] as const
export type ModuleTrackerSortKey = (typeof MODULE_TRACKER_SORT_VALUES)[number]

export const CARD_TRACKER_SORT_VALUES = [
  'name',
  'level',
  'mastery',
  'quantity',
  'completed',
  'remaining',
  'progress',
  'percentTotal',
  'levelValue',
  'masteryValue',
  'gemsSpent',
  'gemsRemaining',
  'timeToNext',
  'timeToMax',
  'rarity',
  'custom',
] as const
export type CardTrackerSortKey = (typeof CARD_TRACKER_SORT_VALUES)[number]

export const LABS_TRACKER_SORT_VALUES = [
  'order',
  'label',
  'progressTarget',
  'progressMax',
  'maxed',
  'timeSpent',
  'timeRemainingTarget',
  'timeRemainingMax',
  'timeTotal',
  'timeToNext',
  'gemsSpent',
  'gemsRemainingTarget',
  'gemsRemainingMax',
  'gemsTotal',
  'gemsToNext',
  'coinsSpent',
  'coinsRemainingTarget',
  'coinsRemainingMax',
  'coinsTotal',
  'coinsToNext',
  'dateCreated',
  'dateUpdated',
] as const
export type LabsTrackerSortKey = (typeof LABS_TRACKER_SORT_VALUES)[number]

const MODULE_TRACKER_TYPE_FILTER_LABELS: Record<ModuleTrackerTypeFilter, string> = {
  All: 'All',
  Cannon: 'Cannon',
  Armor: 'Armor',
  Generator: 'Generator',
  Core: 'Core',
}

const MODULE_TRACKER_SORT_LABELS: Record<ModuleTrackerSortKey, string> = {
  name: 'Name',
  type: 'Type',
  rarity: 'Rarity',
  progress: 'Progress',
  custom: 'Custom Order',
}

const CARD_TRACKER_SORT_LABELS: Record<CardTrackerSortKey, string> = {
  name: 'Name',
  level: 'Level',
  mastery: 'Mastery',
  quantity: 'Copies',
  completed: 'Completed',
  remaining: 'Remaining',
  progress: 'Progress',
  percentTotal: '% Total',
  levelValue: 'Level Value',
  masteryValue: 'Mastery Value',
  gemsSpent: 'Gems Spent',
  gemsRemaining: 'Gems Remaining',
  timeToNext: 'Time to Next',
  timeToMax: 'Time to Max',
  rarity: 'Rarity',
  custom: 'Custom Order',
}

const LABS_TRACKER_SORT_LABELS: Record<LabsTrackerSortKey, string> = {
  order: 'Custom',
  label: 'Label (A→Z)',
  progressTarget: 'Target Progress %',
  progressMax: 'Max Progress %',
  maxed: 'Maxed',
  timeSpent: 'Time Spent',
  timeRemainingTarget: 'Remaining Target Time',
  timeRemainingMax: 'Remaining Max Time',
  timeTotal: 'Total Time',
  timeToNext: 'Time to Next',
  gemsSpent: 'Gems Spent',
  gemsRemainingTarget: 'Gems Remaining to Target',
  gemsRemainingMax: 'Gems Remaining to Max',
  gemsTotal: 'Total Gems',
  gemsToNext: 'Gems to Next',
  coinsSpent: 'Coins Spent',
  coinsRemainingTarget: 'Coins Remaining to Target',
  coinsRemainingMax: 'Coins Remaining to Max',
  coinsTotal: 'Total Coins',
  coinsToNext: 'Coins to Next',
  dateCreated: 'Recently Added',
  dateUpdated: 'Recently Updated',
}

function buildIndexedStringEntries<T extends string>(
  values: readonly T[],
  labelFor: (value: T) => string,
): readonly GameDropdownOptionEntry[] {
  return values.map((value, index) => ({
    value: index,
    baseValue: index,
    meta: { stringValue: value, label: labelFor(value) },
  }))
}

export function buildModuleTrackerTypeFilterEntries(): readonly GameDropdownOptionEntry[] {
  return buildIndexedStringEntries(MODULE_TRACKER_TYPE_FILTER_VALUES, value => MODULE_TRACKER_TYPE_FILTER_LABELS[value])
}

export function buildModuleTrackerRarityFilterEntries(): readonly GameDropdownOptionEntry[] {
  return buildIndexedStringEntries(MODULE_TRACKER_RARITY_FILTER_VALUES, value => value)
}

export function buildModuleTrackerSortEntries(): readonly GameDropdownOptionEntry[] {
  return buildIndexedStringEntries(MODULE_TRACKER_SORT_VALUES, value => MODULE_TRACKER_SORT_LABELS[value])
}

export function buildCardTrackerSortEntries(): readonly GameDropdownOptionEntry[] {
  return buildIndexedStringEntries(CARD_TRACKER_SORT_VALUES, value => CARD_TRACKER_SORT_LABELS[value])
}

export function buildLabsTrackerSortEntries(): readonly GameDropdownOptionEntry[] {
  return buildIndexedStringEntries(LABS_TRACKER_SORT_VALUES, value => LABS_TRACKER_SORT_LABELS[value])
}

function resolveStringIndex<T extends string>(values: readonly T[], value: unknown, fallback = 0): number {
  const idx = values.indexOf(String(value) as T)
  return idx >= 0 ? idx : fallback
}

function resolveStringByIndex<T extends string>(values: readonly T[], index: number, fallback: T): T {
  const clamped = Math.max(0, Math.min(values.length - 1, Math.floor(Number(index) || 0)))
  return values[clamped] ?? fallback
}

export function computeModuleTrackerTypeFilterIndex(value: unknown): number {
  return resolveStringIndex(MODULE_TRACKER_TYPE_FILTER_VALUES, value)
}

export function getModuleTrackerTypeFilterByIndex(index: number): ModuleTrackerTypeFilter {
  return resolveStringByIndex(MODULE_TRACKER_TYPE_FILTER_VALUES, index, 'All')
}

export function computeModuleTrackerRarityFilterIndex(value: unknown): number {
  return resolveStringIndex(MODULE_TRACKER_RARITY_FILTER_VALUES, value)
}

export function getModuleTrackerRarityFilterByIndex(index: number): ModuleTrackerRarityFilter {
  return resolveStringByIndex(MODULE_TRACKER_RARITY_FILTER_VALUES, index, 'All')
}

export function computeModuleTrackerSortIndex(value: unknown): number {
  return resolveStringIndex(MODULE_TRACKER_SORT_VALUES, value)
}

export function getModuleTrackerSortByIndex(index: number): ModuleTrackerSortKey {
  return resolveStringByIndex(MODULE_TRACKER_SORT_VALUES, index, 'name')
}

export function computeCardTrackerSortIndex(value: unknown): number {
  return resolveStringIndex(CARD_TRACKER_SORT_VALUES, value)
}

export function getCardTrackerSortByIndex(index: number): CardTrackerSortKey {
  return resolveStringByIndex(CARD_TRACKER_SORT_VALUES, index, 'name')
}

export function computeLabsTrackerSortIndex(value: unknown): number {
  return resolveStringIndex(LABS_TRACKER_SORT_VALUES, value)
}

export function getLabsTrackerSortByIndex(index: number): LabsTrackerSortKey {
  return resolveStringByIndex(LABS_TRACKER_SORT_VALUES, index, 'order')
}

export function formatModuleTrackerTypeFilterOptionLabel(index: number): string {
  return MODULE_TRACKER_TYPE_FILTER_LABELS[getModuleTrackerTypeFilterByIndex(index)]
}

export function formatModuleTrackerRarityFilterOptionLabel(index: number): string {
  return getModuleTrackerRarityFilterByIndex(index)
}

export function formatModuleTrackerSortOptionLabel(index: number): string {
  return MODULE_TRACKER_SORT_LABELS[getModuleTrackerSortByIndex(index)]
}

export function formatCardTrackerSortOptionLabel(index: number): string {
  return CARD_TRACKER_SORT_LABELS[getCardTrackerSortByIndex(index)]
}

export function formatLabsTrackerSortOptionLabel(index: number): string {
  return LABS_TRACKER_SORT_LABELS[getLabsTrackerSortByIndex(index)]
}

export const WORKSHOP_TRACKER_CATEGORY_FILTER_VALUES = ['all', 'attack', 'defense', 'utility'] as const
export type WorkshopTrackerCategoryFilter = (typeof WORKSHOP_TRACKER_CATEGORY_FILTER_VALUES)[number]

export const WORKSHOP_OVERVIEW_LAYOUT_VALUES = ['auto', '1', '2', '3', '4'] as const
export type WorkshopOverviewLayoutMode = (typeof WORKSHOP_OVERVIEW_LAYOUT_VALUES)[number]

export const UW_OVERVIEW_VIEW_VALUES = ['auto', 'list', '2', '3'] as const
export type UwOverviewViewMode = (typeof UW_OVERVIEW_VIEW_VALUES)[number]

export const RELICS_BONUS_SORT_VALUES = ['name', 'bonusType', 'value', 'rarity', 'event', 'type'] as const
export const RELICS_THEMES_SORT_VALUES = ['name', 'event'] as const

const RELICS_BONUS_SORT_LABELS: SortLabelMap = {
  name: 'Name',
  bonusType: 'Bonus Type',
  value: 'Value',
  rarity: 'Rarity',
  event: 'Event',
  type: 'Type',
}

const RELICS_THEMES_SORT_LABELS: SortLabelMap = { name: 'Name', event: 'Event' }

export const BOTS_TRACKER_PRESET_VALUES = [0, 1, 2] as const

const WORKSHOP_CATEGORY_LABELS: Record<WorkshopTrackerCategoryFilter, string> = {
  all: 'All',
  attack: 'Attack',
  defense: 'Defense',
  utility: 'Utility',
}

const WORKSHOP_OVERVIEW_LAYOUT_LABELS: Record<WorkshopOverviewLayoutMode, string> = {
  auto: 'Auto',
  '1': '1 Column',
  '2': '2 Columns',
  '3': '3 Columns',
  '4': '4 Columns',
}

const UW_OVERVIEW_VIEW_LABELS: Record<UwOverviewViewMode, string> = {
  auto: 'Auto',
  list: 'List',
  '2': '2 per row',
  '3': '3 per row',
}

const WORKSHOP_TRACKER_SORT_WORKSHOP_VALUES = [
  'default', 'custom', 'progressTarget', 'progressMax', 'currentCoin', 'currentCash',
  'targetCoin', 'targetCash', 'maxLevelCoin', 'maxLevelCash', 'coinsRemainingTarget',
  'timeCoinsTarget', 'cashRemainingTarget', 'coinsRemainingMax', 'timeCoinsMax', 'cashRemainingMax',
] as const

const WORKSHOP_TRACKER_SORT_ENHANCEMENTS_VALUES = [
  'default', 'custom', 'progressTarget', 'progressMax', 'current', 'target', 'maxLevel',
  'coinsRemainingTarget', 'timeCoinsTarget', 'coinsRemainingMax', 'timeCoinsMax',
] as const

const BOTS_TRACKER_SORT_BASE_VALUES = [
  'default', 'custom', 'medalsRemainingTarget', 'finishDateTarget', 'timeToTarget', 'progressTarget',
  'medalsRemainingMax', 'finishDateMax', 'progressMax', 'medalsSpent', 'medalsTotal',
  'eventsTarget', 'eventsMax', 'current', 'target',
] as const

const GUARDIANS_TRACKER_SORT_BASE_VALUES = [
  'default', 'custom', 'costRemainingTarget', 'finishDateTarget', 'timeToTarget', 'progressTarget',
  'costRemainingMax', 'finishDateMax', 'progressMax', 'costSpent', 'costTotal',
  'gainsTarget', 'gainsMax', 'current', 'target',
] as const

const UW_TRACKER_SORT_BASE_VALUES = [
  'default', 'custom', 'stonesRemainingTarget', 'finishDateTarget', 'timeToTarget', 'progressTarget',
  'stonesRemainingMax', 'finishDateMax', 'progressMax', 'stonesSpent', 'stonesTotal', 'current', 'target',
] as const

type SortLabelMap = Record<string, string>

const WORKSHOP_SORT_WORKSHOP_LABELS: SortLabelMap = {
  default: 'Default', custom: 'Custom', progressTarget: 'Progress (to Target)', progressMax: 'Progress (to Max)',
  currentCoin: 'Current Coin Level', currentCash: 'Current Cash Level', targetCoin: 'Target Coin Level',
  targetCash: 'Target Cash Level', maxLevelCoin: 'Max Coin Level', maxLevelCash: 'Max Cash Level',
  coinsRemainingTarget: 'Coins Remaining (Target)', timeCoinsTarget: 'Time (Coins to Target)',
  cashRemainingTarget: 'Cash Remaining (Target)', coinsRemainingMax: 'Coins Remaining (Max)',
  timeCoinsMax: 'Time (Coins to Max)', cashRemainingMax: 'Cash Remaining (Max)',
}

const WORKSHOP_SORT_ENHANCEMENTS_LABELS: SortLabelMap = {
  default: 'Default', custom: 'Custom', progressTarget: 'Progress (to Target)', progressMax: 'Progress (to Max)',
  current: 'Current Level', target: 'Target Level', maxLevel: 'Max Level',
  coinsRemainingTarget: 'Coins Remaining (Target)', timeCoinsTarget: 'Time (Coins to Target)',
  coinsRemainingMax: 'Coins Remaining (Max)', timeCoinsMax: 'Time (Coins to Max)',
}

const BOTS_SORT_LABELS: SortLabelMap = {
  default: 'Default', custom: 'Custom', medalsRemainingTarget: 'Remaining (to Target)',
  finishDateTarget: 'Finish Date (to Target)', timeToTarget: 'Time (to Target)', progressTarget: 'Progress (to Target)',
  medalsRemainingMax: 'Remaining (to Max)', finishDateMax: 'Finish Date (to Max)', progressMax: 'Progress (to Max)',
  medalsSpent: 'Medals Spent', medalsTotal: 'Total Medals', eventsTarget: 'Events (to Target)',
  eventsMax: 'Events (to Max)', current: 'Current Levels', target: 'Target Levels',
}

const GUARDIANS_SORT_LABELS: SortLabelMap = {
  default: 'Default', custom: 'Custom', costRemainingTarget: 'Remaining (to Target)',
  finishDateTarget: 'Finish Date (to Target)', timeToTarget: 'Time (to Target)', progressTarget: 'Progress (to Target)',
  costRemainingMax: 'Remaining (to Max)', finishDateMax: 'Finish Date (to Max)', progressMax: 'Progress (to Max)',
  costSpent: 'Bits Spent', costTotal: 'Total Bits', gainsTarget: 'Weeks (to Target)', gainsMax: 'Weeks (to Max)',
  current: 'Current Levels', target: 'Target Levels',
}

const UW_SORT_LABELS: SortLabelMap = {
  default: 'Default', custom: 'Custom', stonesRemainingTarget: 'Remaining (to Target)',
  finishDateTarget: 'Finish Date (to Target)', timeToTarget: 'Time (to Target)', progressTarget: 'Progress (to Target)',
  stonesRemainingMax: 'Remaining (to Max)', finishDateMax: 'Finish Date (to Max)', progressMax: 'Progress (to Max)',
  stonesSpent: 'Stones Spent', stonesTotal: 'Total Stones', current: 'Current Levels', target: 'Target Levels',
}

function buildSortEntries(values: readonly string[], labels: SortLabelMap, includeCustom: boolean): readonly GameDropdownOptionEntry[] {
  const filtered = values.filter(value => value !== 'custom' || includeCustom)
  return filtered.map((value, index) => ({
    value: index,
    baseValue: index,
    meta: { stringValue: value, label: labels[value] ?? value },
  }))
}

function resolveSortIndex(values: readonly string[], value: unknown, includeCustom: boolean): number {
  const filtered = values.filter(item => item !== 'custom' || includeCustom)
  return resolveStringIndex(filtered, value)
}

function resolveSortByIndex(values: readonly string[], index: number, includeCustom: boolean, fallback: string): string {
  const filtered = values.filter(item => item !== 'custom' || includeCustom)
  return resolveStringByIndex(filtered, index, fallback)
}

export function buildWorkshopTrackerCategoryFilterEntries(): readonly GameDropdownOptionEntry[] {
  return buildIndexedStringEntries(WORKSHOP_TRACKER_CATEGORY_FILTER_VALUES, value => WORKSHOP_CATEGORY_LABELS[value])
}

export function buildWorkshopOverviewLayoutEntries(): readonly GameDropdownOptionEntry[] {
  return buildIndexedStringEntries(WORKSHOP_OVERVIEW_LAYOUT_VALUES, value => WORKSHOP_OVERVIEW_LAYOUT_LABELS[value])
}

export function buildUwOverviewViewEntries(): readonly GameDropdownOptionEntry[] {
  return buildIndexedStringEntries(UW_OVERVIEW_VIEW_VALUES, value => UW_OVERVIEW_VIEW_LABELS[value])
}

export function buildWorkshopTrackerSortEntries(profile: 'workshop' | 'enhancements', includeCustom: boolean): readonly GameDropdownOptionEntry[] {
  const values = profile === 'enhancements' ? WORKSHOP_TRACKER_SORT_ENHANCEMENTS_VALUES : WORKSHOP_TRACKER_SORT_WORKSHOP_VALUES
  const labels = profile === 'enhancements' ? WORKSHOP_SORT_ENHANCEMENTS_LABELS : WORKSHOP_SORT_WORKSHOP_LABELS
  return buildSortEntries(values, labels, includeCustom)
}

export function buildBotsTrackerSortEntries(includeCustom: boolean): readonly GameDropdownOptionEntry[] {
  return buildSortEntries(BOTS_TRACKER_SORT_BASE_VALUES, BOTS_SORT_LABELS, includeCustom)
}

export function buildGuardiansTrackerSortEntries(includeCustom: boolean): readonly GameDropdownOptionEntry[] {
  return buildSortEntries(GUARDIANS_TRACKER_SORT_BASE_VALUES, GUARDIANS_SORT_LABELS, includeCustom)
}

export function buildUwTrackerSortEntries(includeCustom: boolean): readonly GameDropdownOptionEntry[] {
  return buildSortEntries(UW_TRACKER_SORT_BASE_VALUES, UW_SORT_LABELS, includeCustom)
}

export function buildRelicsBonusSortEntries(): readonly GameDropdownOptionEntry[] {
  return buildIndexedStringEntries(RELICS_BONUS_SORT_VALUES, value => RELICS_BONUS_SORT_LABELS[value])
}

export function buildRelicsThemesSortEntries(): readonly GameDropdownOptionEntry[] {
  return buildIndexedStringEntries(RELICS_THEMES_SORT_VALUES, value => RELICS_THEMES_SORT_LABELS[value])
}

export function buildBotsTrackerPresetEntries(labels?: readonly string[]): readonly GameDropdownOptionEntry[] {
  return BOTS_TRACKER_PRESET_VALUES.map((value, index) => ({
    value: index,
    baseValue: index,
    meta: { numericValue: value, label: labels?.[index] ?? `Preset ${index + 1}` },
  }))
}

export function buildLabsSpeedupEntries(): readonly GameDropdownOptionEntry[] {
  return TOOL_LAB_SPEEDUP_OPTIONS.map((multiplier, index) => ({
    value: index,
    baseValue: index,
    meta: { numericValue: multiplier, label: `${multiplier}x` },
  }))
}

export function buildLabsTypeFilterEntries(typeOptions: readonly string[]): readonly GameDropdownOptionEntry[] {
  const values = typeOptions.length > 0 ? typeOptions : ['All']
  return values.map((value, index) => ({ value: index, baseValue: index, meta: { stringValue: value, label: value } }))
}

export function computeWorkshopTrackerCategoryFilterIndex(value: unknown): number {
  return resolveStringIndex(WORKSHOP_TRACKER_CATEGORY_FILTER_VALUES, value)
}

export function getWorkshopTrackerCategoryFilterByIndex(index: number): WorkshopTrackerCategoryFilter {
  return resolveStringByIndex(WORKSHOP_TRACKER_CATEGORY_FILTER_VALUES, index, 'all')
}

export function computeWorkshopOverviewLayoutIndex(value: unknown): number {
  return resolveStringIndex(WORKSHOP_OVERVIEW_LAYOUT_VALUES, String(value))
}

export function getWorkshopOverviewLayoutByIndex(index: number): WorkshopOverviewLayoutMode | number {
  const resolved = resolveStringByIndex(WORKSHOP_OVERVIEW_LAYOUT_VALUES, index, 'auto')
  return resolved === 'auto' ? 'auto' : Number(resolved)
}

export function computeUwOverviewViewIndex(value: unknown): number {
  return resolveStringIndex(UW_OVERVIEW_VIEW_VALUES, String(value))
}

export function getUwOverviewViewByIndex(index: number): UwOverviewViewMode {
  return resolveStringByIndex(UW_OVERVIEW_VIEW_VALUES, index, 'auto')
}

export function computeWorkshopTrackerSortIndex(value: unknown, profile: 'workshop' | 'enhancements', includeCustom: boolean): number {
  const values = profile === 'enhancements' ? WORKSHOP_TRACKER_SORT_ENHANCEMENTS_VALUES : WORKSHOP_TRACKER_SORT_WORKSHOP_VALUES
  return resolveSortIndex(values, value, includeCustom)
}

export function getWorkshopTrackerSortByIndex(index: number, profile: 'workshop' | 'enhancements', includeCustom: boolean): string {
  const values = profile === 'enhancements' ? WORKSHOP_TRACKER_SORT_ENHANCEMENTS_VALUES : WORKSHOP_TRACKER_SORT_WORKSHOP_VALUES
  return resolveSortByIndex(values, index, includeCustom, 'default')
}

export function computeBotsTrackerSortIndex(value: unknown, includeCustom: boolean): number {
  return resolveSortIndex(BOTS_TRACKER_SORT_BASE_VALUES, value, includeCustom)
}

export function getBotsTrackerSortByIndex(index: number, includeCustom: boolean): string {
  return resolveSortByIndex(BOTS_TRACKER_SORT_BASE_VALUES, index, includeCustom, 'default')
}

export function computeGuardiansTrackerSortIndex(value: unknown, includeCustom: boolean): number {
  return resolveSortIndex(GUARDIANS_TRACKER_SORT_BASE_VALUES, value, includeCustom)
}

export function getGuardiansTrackerSortByIndex(index: number, includeCustom: boolean): string {
  return resolveSortByIndex(GUARDIANS_TRACKER_SORT_BASE_VALUES, index, includeCustom, 'default')
}

export function computeUwTrackerSortIndex(value: unknown, includeCustom: boolean): number {
  return resolveSortIndex(UW_TRACKER_SORT_BASE_VALUES, value, includeCustom)
}

export function getUwTrackerSortByIndex(index: number, includeCustom: boolean): string {
  return resolveSortByIndex(UW_TRACKER_SORT_BASE_VALUES, index, includeCustom, 'default')
}

export function computeRelicsBonusSortIndex(value: unknown): number {
  return resolveStringIndex(RELICS_BONUS_SORT_VALUES, value)
}

export function getRelicsBonusSortByIndex(index: number): string {
  return resolveStringByIndex(RELICS_BONUS_SORT_VALUES, index, 'name')
}

export function computeRelicsThemesSortIndex(value: unknown): number {
  return resolveStringIndex(RELICS_THEMES_SORT_VALUES, value)
}

export function getRelicsThemesSortByIndex(index: number): string {
  return resolveStringByIndex(RELICS_THEMES_SORT_VALUES, index, 'name')
}

export function computeLabsSpeedupIndex(value: unknown): number {
  const numeric = Number(value)
  const idx = TOOL_LAB_SPEEDUP_OPTIONS.indexOf(numeric as (typeof TOOL_LAB_SPEEDUP_OPTIONS)[number])
  return idx >= 0 ? idx : 0
}

export function computeLabsSpeedupByIndex(index: number): number {
  const clamped = Math.max(0, Math.min(TOOL_LAB_SPEEDUP_OPTIONS.length - 1, Math.floor(Number(index) || 0)))
  return TOOL_LAB_SPEEDUP_OPTIONS[clamped] ?? 1
}

export function computeLabsTypeFilterIndex(value: unknown, typeOptions: readonly string[]): number {
  return resolveStringIndex(typeOptions.length > 0 ? typeOptions : ['All'], value)
}

export function getLabsTypeFilterByIndex(index: number, typeOptions: readonly string[]): string {
  const values = typeOptions.length > 0 ? typeOptions : ['All']
  return resolveStringByIndex(values, index, 'All')
}

export function formatWorkshopTrackerCategoryFilterOptionLabel(index: number): string {
  return WORKSHOP_CATEGORY_LABELS[getWorkshopTrackerCategoryFilterByIndex(index)]
}

export function formatWorkshopOverviewLayoutOptionLabel(index: number): string {
  return WORKSHOP_OVERVIEW_LAYOUT_LABELS[resolveStringByIndex(WORKSHOP_OVERVIEW_LAYOUT_VALUES, index, 'auto')]
}

export function buildWorkshopTrackerSortOptionLabel(index: number, profile: 'workshop' | 'enhancements', includeCustom: boolean): string {
  const value = getWorkshopTrackerSortByIndex(index, profile, includeCustom)
  const labels = profile === 'enhancements' ? WORKSHOP_SORT_ENHANCEMENTS_LABELS : WORKSHOP_SORT_WORKSHOP_LABELS
  return labels[value] ?? value
}

export function buildBotsTrackerSortOptionLabel(index: number, includeCustom: boolean): string {
  return BOTS_SORT_LABELS[getBotsTrackerSortByIndex(index, includeCustom)] ?? String(index)
}

export function buildGuardiansTrackerSortOptionLabel(index: number, includeCustom: boolean): string {
  return GUARDIANS_SORT_LABELS[getGuardiansTrackerSortByIndex(index, includeCustom)] ?? String(index)
}

export function buildUwTrackerSortOptionLabel(index: number, includeCustom: boolean): string {
  return UW_SORT_LABELS[getUwTrackerSortByIndex(index, includeCustom)] ?? String(index)
}

export function formatRelicsBonusSortOptionLabel(index: number): string {
  return RELICS_BONUS_SORT_LABELS[getRelicsBonusSortByIndex(index)]
}

export function formatRelicsThemesSortOptionLabel(index: number): string {
  return RELICS_THEMES_SORT_LABELS[getRelicsThemesSortByIndex(index)]
}

export function buildBotsTrackerPresetOptionLabel(index: number, labels?: readonly string[]): string {
  const clamped = Math.max(0, Math.min(BOTS_TRACKER_PRESET_VALUES.length - 1, Math.floor(Number(index) || 0)))
  return labels?.[clamped] ?? `Preset ${clamped + 1}`
}

export function formatLabsSpeedupOptionLabel(index: number): string {
  return `${computeLabsSpeedupByIndex(index)}x`
}

export function buildLabsTypeFilterOptionLabel(index: number, typeOptions: readonly string[]): string {
  return getLabsTypeFilterByIndex(index, typeOptions)
}

export function formatUwOverviewViewOptionLabel(index: number): string {
  return UW_OVERVIEW_VIEW_LABELS[getUwOverviewViewByIndex(index)]
}

export const LIFETIME_AVERAGE_PERIOD_VALUES = [
  'minute',
  'hour',
  'day',
  'week',
  'month',
  '3months',
  '6months',
  'year',
] as const
export type LifetimeAveragePeriod = (typeof LIFETIME_AVERAGE_PERIOD_VALUES)[number]

export const LIFETIME_CHART_LINE_TYPE_VALUES = [
  'solid',
  'dashed',
  'dotted',
  'long-dashed',
  'short-dashed',
  'dash-dot',
  'dash-dot-dot',
  'long-short-dash',
] as const
export type LifetimeChartLineType = (typeof LIFETIME_CHART_LINE_TYPE_VALUES)[number]

const LIFETIME_AVERAGE_PERIOD_LABELS: Record<LifetimeAveragePeriod, string> = {
  minute: 'Per Minute',
  hour: 'Per Hour',
  day: 'Per Day',
  week: 'Per Week',
  month: 'Per Month',
  '3months': 'Per 3 Months',
  '6months': 'Per 6 Months',
  year: 'Per Year',
}

const LIFETIME_CHART_LINE_TYPE_LABELS: Record<LifetimeChartLineType, string> = {
  solid: 'Solid',
  dashed: 'Dashed',
  dotted: 'Dotted',
  'long-dashed': 'Long Dashed',
  'short-dashed': 'Short Dashed',
  'dash-dot': 'Dash-Dot',
  'dash-dot-dot': 'Dash-Dot-Dot',
  'long-short-dash': 'Long Dash-Short Dash',
}

export function buildLifetimeAveragePeriodEntries(): readonly GameDropdownOptionEntry[] {
  return buildIndexedStringEntries(LIFETIME_AVERAGE_PERIOD_VALUES, value => LIFETIME_AVERAGE_PERIOD_LABELS[value])
}

export function buildLifetimeChartLineTypeEntries(): readonly GameDropdownOptionEntry[] {
  return buildIndexedStringEntries(LIFETIME_CHART_LINE_TYPE_VALUES, value => LIFETIME_CHART_LINE_TYPE_LABELS[value])
}

export function computeLifetimeAveragePeriodIndex(value: unknown): number {
  return resolveStringIndex(LIFETIME_AVERAGE_PERIOD_VALUES, value)
}

export function getLifetimeAveragePeriodByIndex(index: number): LifetimeAveragePeriod {
  return resolveStringByIndex(LIFETIME_AVERAGE_PERIOD_VALUES, index, 'day')
}

export function computeLifetimeChartLineTypeIndex(value: unknown): number {
  return resolveStringIndex(LIFETIME_CHART_LINE_TYPE_VALUES, value)
}

export function getLifetimeChartLineTypeByIndex(index: number): LifetimeChartLineType {
  return resolveStringByIndex(LIFETIME_CHART_LINE_TYPE_VALUES, index, 'solid')
}

export function formatLifetimeAveragePeriodOptionLabel(index: number): string {
  return LIFETIME_AVERAGE_PERIOD_LABELS[getLifetimeAveragePeriodByIndex(index)]
}

export function formatLifetimeChartLineTypeOptionLabel(index: number): string {
  return LIFETIME_CHART_LINE_TYPE_LABELS[getLifetimeChartLineTypeByIndex(index)]
}
