/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    gameDropdownOptionEntrySchema, GameDropdownOptionEntry, StandardDropdownOption, GameDataRegistryItem
 * depends    —
 * used by    src/internal/game-input-data/card-template-dropdown-math, src/internal/game-input-data/cards-dropdown-math, src/internal/game-input-data/damage-reduction-dropdown-math, src/internal/game-input-data/dissonance-echo-lab-dropdown-math, src/internal/game-input-data/dropdown-evaluator, src/internal/game-input-data/els-dropdown-math (+26 more)
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
import { z } from 'zod'

export const gameDropdownOptionEntrySchema = z.object({
  value: z.number(),
  baseValue: z.number(),
})

export type GameDropdownOptionEntry = z.infer<typeof gameDropdownOptionEntrySchema>

export interface StandardDropdownOption {
  value: number
  label: string
  subtitle?: string
}

export interface GameDataRegistryItem {
  schema: typeof gameDropdownOptionEntrySchema
  data: readonly GameDropdownOptionEntry[]
}
