/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    UwStatDropdownBinding, findUwStatDropdownBinding, evaluateUwStatDropdownOptions, buildUwStatFieldLabel, computeDefaultUwStatStoneLevel, findUwStatSpec, UwStatSpec
 * depends    src/internal/game-input-data/dropdown-evaluator, src/internal/game-input-data/types, src/internal/game-input-data/uw-stat-dropdown-math, src/mechanics/uw-stat-values
 * used by    src/internal/game-input-data/index, src/mechanics/calculators/specs-generated
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
import { evaluateDropdownOptions } from './dropdown-evaluator'
import type { StandardDropdownOption } from './types'
import {
  buildUwStatFieldLabel,
} from './uw-stat-dropdown-math'
import {
  computeDefaultUwStatStoneLevel,
  findUwStatSpec,
  type UwStatSpec,
} from '../../mechanics/uw-stat-values'

export type UwStatDropdownBinding = {
  dataKey: 'uw_stat_level'
  uwStatSpec: UwStatSpec
}

export function findUwStatDropdownBinding(
  weaponName: string,
  statDisplayName: string,
): UwStatDropdownBinding | null {
  const spec = findUwStatSpec(weaponName, statDisplayName)
  if (!spec) return null
  return { dataKey: 'uw_stat_level', uwStatSpec: spec }
}

/** Same options every UW stat dropdown uses (`GameSelect` / `UwStatLevelSelect`). */
export function evaluateUwStatDropdownOptions(
  weaponName: string,
  statDisplayName: string,
): StandardDropdownOption[] {
  const binding = findUwStatDropdownBinding(weaponName, statDisplayName)
  if (!binding) return []
  return evaluateDropdownOptions(binding.dataKey, { uwStatSpec: binding.uwStatSpec })
}

export {
  buildUwStatFieldLabel,
  computeDefaultUwStatStoneLevel,
  findUwStatSpec,
  type UwStatSpec,
}
