/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    buildUwStatFieldLabel, buildUwStatOptionLabel, buildUwStatLevelEntries
 * depends    src/data/ultimate-weapon-stones, src/internal/game-input-data/types, src/mechanics/uw-stat-values
 * used by    src/internal/game-input-data/dropdown-evaluator, src/internal/game-input-data/index, src/internal/game-input-data/uw-game-input-keys, src/mechanics/calculators/specs-generated, src/mechanics/resource-drops-coin-simulation
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
import { uwStoneChartData } from '../../data/ultimate-weapon-stones'
import type { GameDropdownOptionEntry } from './types'
import { buildUwStatLevelEntries, findUwStatSpec, type UwStatSpec } from '../../mechanics/uw-stat-values'

export { buildUwStatLevelEntries }

export function buildUwStatFieldLabel(weaponName: string, statDisplayName: string): string {
  const spec = findUwStatSpec(weaponName, statDisplayName)
  if (!spec) return `${weaponName} - ${statDisplayName}`
  return `${weaponName} - ${spec.statName}`
}
export function buildUwStatOptionLabel(spec: UwStatSpec, level: number): string {
  const weapon = uwStoneChartData[spec.weaponKey]
  const stat = weapon?.stats.find(entry => entry.name === spec.statName)
  const row = stat?.levels.find(entry => entry.level === level)
  if (!row) return String(level)
  return String(row.value).trim()
}
