/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    TowerVmRequest, TowerVmResult, runTowerVm
 * depends    src/mechanics/doctor/diagnose, src/mechanics/doctor/prescribe, src/mechanics/kernel, src/mechanics/planner-engine
 * used by    src/mechanics/sandbox/index
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
import fs from 'node:fs'
import path from 'node:path'
import { diagnoseDoctor } from '../doctor/diagnose'
import { prescribeDoctor } from '../doctor/prescribe'
import {
  loadMechanicsKernel,
  resolveMechanicsRepoRoot,
  type LoadMechanicsKernelOptions,
} from '../kernel'
import {
  compilePlannerPipeline,
  evaluatePlannerCitation,
  listPlannerEvaluatorBindings,
} from '../planner-engine'

export interface TowerVmRequest {
  family?: string
  planFamily?: 'economy' | 'damage' | 'health' | 'regen'
  planVariant?: string
  savePath?: string
  utilityLevels?: Record<string, number>
}

export interface TowerVmResult {
  ok: boolean
  traces: Array<{ step: string; ok: boolean; detail?: unknown }>
  errors: string[]
}

/**
 * Light Tower VM — kernel + fixture decode + planner citation eval + doctor-dry.
 * Not a combat simulator. Never invents formulas.
 */
export function runTowerVm(
  opts: LoadMechanicsKernelOptions & { request?: TowerVmRequest } = {},
): TowerVmResult {
  const repoRoot = resolveMechanicsRepoRoot(opts.repoRoot)
  const req = opts.request ?? {}
  const family = req.family ?? 'eEcon'
  const traces: TowerVmResult['traces'] = []
  const errors: string[] = []

  const step = (name: string, fn: () => unknown) => {
    try {
      const detail = fn()
      traces.push({ step: name, ok: true, detail })
      return detail
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err)
      errors.push(`${name}: ${message}`)
      traces.push({ step: name, ok: false, detail: { error: message } })
      return null
    }
  }

  step('vm.kernel', () => {
    const ctx = loadMechanicsKernel({ ...opts, repoRoot, includeDoctor: true }).context
    return { ok: ctx.ok, doctorStatus: ctx.doctorStatus, saveNodes: ctx.graphs.save.nodeCount }
  })

  step('vm.decode-fixture', () => {
    const rel = req.savePath ?? 'packages/sdk/src/save/fixtures/perk-preferences.sample.json'
    const abs = path.isAbsolute(rel) ? rel : path.join(repoRoot, rel)
    const json = JSON.parse(fs.readFileSync(abs, 'utf8'))
    return {
      path: abs,
      topLevelKeys: Object.keys(json).filter(k => !k.startsWith('_')),
    }
  })

  step('vm.planner.compile', () => {
    const pipe = compilePlannerPipeline(family)
    return { family: pipe.family, codegen: pipe.codegen, steps: pipe.steps.map(s => s.id) }
  })

  step('vm.planner.eval-bindings', () => {
    const bindings = listPlannerEvaluatorBindings()
    const evals = bindings.map(b =>
      evaluatePlannerCitation(family, {
        nodeId: b.nodeId,
        utilityLevels: req.utilityLevels ?? { 'Cash Bonus': 10 },
      }),
    )
    return {
      bindingCount: bindings.length,
      results: evals.map(e => ({
        nodeId: e.nodeId,
        ok: e.ok,
        value: e.value,
        error: e.error,
      })),
    }
  })

  step('vm.doctor-dry', () => {
    const report = diagnoseDoctor({ repoRoot })
    const plan = prescribeDoctor(report)
    return {
      status: report.status,
      autoCount: plan.autoCount,
      humanCount: plan.humanCount,
      repairSkipped: true,
    }
  })

  if (req.planFamily && req.planVariant) {
    step('vm.plan-effective-path', () => ({
      deferredToMcp: true,
      note: 'Use MCP plan_effective_path for full path planning; VM records intent only',
      planFamily: req.planFamily,
      planVariant: req.planVariant,
    }))
  }

  return { ok: errors.length === 0, traces, errors }
}
