/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    DiagnoseDoctorOptions, diagnoseDoctor
 * depends    src/mechanics/doctor/schema, src/mechanics/doctor/tower-probes, src/mechanics/sdk-graph
 * used by    src/mechanics/doctor/index, src/mechanics/doctor/validate, src/mechanics/kernel/load, src/mechanics/lsp/index, src/mechanics/sandbox/index, src/mechanics/sandbox/vm
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
import fs from 'node:fs'
import path from 'node:path'
import {
  createPluginHost,
  runDoctorCore,
  type GovernanceDoctorIssue,
} from '@tmrxjd/governance-engine'
import {
  DoctorIssueCategorySchema,
  DoctorIssueSchema,
  DoctorReportSchema,
  summarizeDoctorStatus,
  type DoctorIssue,
  type DoctorReport,
} from './schema'
import { createTowerDoctorSession, type TowerDoctorPluginOptions } from './tower-probes'

export type DiagnoseDoctorOptions = TowerDoctorPluginOptions

function resolveRepoRoot(explicit?: string): string {
  if (explicit) return explicit
  if (process.env.TOWER_MONOREPO_ROOT) return process.env.TOWER_MONOREPO_ROOT
  let dir = __dirname
  for (let i = 0; i < 10; i++) {
    if (fs.existsSync(path.join(dir, 'scripts', 'mechanics-trust', 'check.mjs'))) return dir
    const parent = path.dirname(dir)
    if (parent === dir) break
    dir = parent
  }
  return path.join(__dirname, '../../../..')
}

function mapGovIssue(issue: GovernanceDoctorIssue): DoctorIssue {
  const cat = DoctorIssueCategorySchema.safeParse(issue.category)
  return DoctorIssueSchema.parse({
    id: issue.id,
    category: cat.success ? cat.data : 'commit',
    severity: issue.severity,
    message: issue.message,
    evidence: issue.evidence,
    nodeIds: issue.nodeIds,
    paths: issue.paths,
    surfaceIds: issue.surfaceIds,
  })
}

/**
 * Full SDK Doctor diagnosis via PluginHost + Tower doctor probes + governance commit probes.
 */
export function diagnoseDoctor(opts: DiagnoseDoctorOptions = {}): DoctorReport {
  const repoRoot = resolveRepoRoot(opts.repoRoot)
  const generatedAt = new Date().toISOString()
  const session = createTowerDoctorSession({ ...opts, repoRoot })

  const host = createPluginHost({
    repoRoot,
    domains: ['universal', 'tower'],
    plugins: [session.plugin],
    skipManifest: true,
  })
  const gov = runDoctorCore(host)
  const issues: DoctorIssue[] = []
  for (const issue of gov.issues) {
    if (issue.id === 'tower-adapter:info') continue
    issues.push(mapGovIssue(issue))
  }

  const rank = { error: 3, warning: 2, info: 1 }
  const byId = new Map<string, DoctorIssue>()
  for (const issue of issues) {
    const prev = byId.get(issue.id)
    if (!prev || rank[issue.severity] > rank[prev.severity]) byId.set(issue.id, issue)
  }
  const deduped = [...byId.values()].map(i => DoctorIssueSchema.parse(i))

  const errorCount = deduped.filter(i => i.severity === 'error').length
  const warningCount = deduped.filter(i => i.severity === 'warning').length
  const infoCount = deduped.filter(i => i.severity === 'info').length

  const meta = session.getMeta()
  let status = summarizeDoctorStatus(deduped)
  if (!meta.trust.ok) status = 'broken'
  else if (status === 'healthy' && warningCount > 0) status = 'degraded'

  return DoctorReportSchema.parse({
    status,
    generatedAt,
    issues: deduped,
    recommendedPatches: [],
    trust: meta.trust,
    drift: meta.drift,
    summary: {
      errorCount,
      warningCount,
      infoCount,
      nodeCount: Object.keys(meta.graph.nodes).length,
      debugNodeCount: meta.debugNodeCount,
    },
  })
}

export type { TrustReport } from '../sdk-graph'
