/**
 * Tower domain doctor probes for PluginHost.
 * Keeps Tower trust/debug/coverage/drift logic out of governance-engine core.
 */
/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    TowerDoctorPluginOptions, TowerDoctorSessionMeta, createTowerDoctorSession, createTowerDoctorPlugin
 * depends    src/mechanics/coverage/schema, src/mechanics/debug-graph, src/mechanics/doctor/schema, src/mechanics/doctor/tower-gates, src/mechanics/sdk-graph
 * used by    src/mechanics/doctor/diagnose, src/mechanics/doctor/index, src/mechanics/governance-adapter
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
import fs from 'node:fs'
import path from 'node:path'
import type { Plugin, ProbeIssue } from '@tmrxjd/governance-engine'
import { loadSdkGraphWithTrust, type TrustReport } from '../sdk-graph'
import { loadDebugGraphDegraded } from '../debug-graph'
import {
  CoverageInventorySchema,
  findSilentGaps,
  type CoverageInventory,
} from '../coverage/schema'
import type { DoctorReport } from './schema'
import { registerTowerGateRules } from './tower-gates'

export interface TowerDoctorPluginOptions {
  repoRoot?: string
  skipDriftFiles?: boolean
  strictTests?: boolean
}

export interface TowerDoctorSessionMeta {
  trust: TrustReport
  graph: ReturnType<typeof loadSdkGraphWithTrust>['graph']
  debugNodeCount: number
  drift?: DoctorReport['drift']
}

function walkTsFiles(dir: string, acc: string[] = [], skip = new Set(['data', 'node_modules'])): string[] {
  if (!fs.existsSync(dir)) return acc
  for (const name of fs.readdirSync(dir)) {
    const full = path.join(dir, name)
    const st = fs.statSync(full)
    if (st.isDirectory()) {
      if (skip.has(name) || name.startsWith('.')) continue
      walkTsFiles(full, acc, skip)
      continue
    }
    if (!/\.tsx?$/.test(name) || name.endsWith('.d.ts')) continue
    acc.push(full)
  }
  return acc
}

function loadInventory(filePath: string): CoverageInventory | null {
  if (!fs.existsSync(filePath)) return null
  try {
    return CoverageInventorySchema.parse(JSON.parse(fs.readFileSync(filePath, 'utf8')))
  } catch {
    return null
  }
}

function readJsonIfExists(filePath: string): unknown | null {
  if (!fs.existsSync(filePath)) return null
  try {
    return JSON.parse(fs.readFileSync(filePath, 'utf8'))
  } catch {
    return null
  }
}

/**
 * Factory: one Tower doctor plugin + getMeta() for DoctorReport shell fields.
 */
export function createTowerDoctorSession(opts: TowerDoctorPluginOptions = {}): {
  plugin: Plugin
  getMeta: () => TowerDoctorSessionMeta
} {
  let meta: TowerDoctorSessionMeta | null = null
  let driftBlock: DoctorReport['drift']

  const plugin: Plugin = {
    id: 'tower.doctor',
    capabilities: { domain: 'tower', tags: ['doctor'] },
    register(api) {
      api.commitScopes.add('tower')
      registerTowerGateRules(api)

      api.probes.add({
        id: 'probe.tower-builder-premades',
        diagnose(ctx) {
          const catalog = path.join(ctx.repoRoot, 'docs/builder-map/tower-premade.v1.json')
          if (!ctx.fs.existsSync(catalog)) {
            return [{
              id: 'tower.builders.missing-catalog',
              category: 'governance',
              severity: 'warning',
              message: 'Tower premade builder catalog missing (docs/builder-map/tower-premade.v1.json)',
              paths: ['docs/builder-map/tower-premade.v1.json'],
              probeId: 'probe.tower-builder-premades',
            }]
          }
          try {
            const raw = JSON.parse(ctx.fs.readFileSync(catalog, 'utf8')) as { definitions?: unknown[] }
            const n = raw.definitions?.length ?? 0
            return [{
              id: 'tower.builders.catalog',
              category: 'governance',
              severity: 'info',
              message: `Tower premade builders catalog present (${n} definitions)`,
              probeId: 'probe.tower-builder-premades',
            }]
          } catch (e) {
            return [{
              id: 'tower.builders.catalog-parse',
              category: 'governance',
              severity: 'error',
              message: `Failed to parse tower-premade catalog: ${e instanceof Error ? e.message : String(e)}`,
              paths: ['docs/builder-map/tower-premade.v1.json'],
              probeId: 'probe.tower-builder-premades',
            }]
          }
        },
      })

      api.probes.add({
        id: 'probe.tower-trust',
        diagnose(_ctx) {
          const issues: ProbeIssue[] = []
          const { graph, report: trust } = loadSdkGraphWithTrust({
            mode: 'degraded',
            scanPlannerCitations: true,
            checkDebugGraph: true,
          })
          const dbg = loadDebugGraphDegraded()
          meta = {
            trust,
            graph,
            debugNodeCount: Object.keys(dbg.graph.nodes).length,
            drift: driftBlock,
          }

          for (const err of trust.structural.errors) {
            issues.push({
              id: `structural:${err.slice(0, 80)}`,
              category: 'mechanicsGraph',
              severity: 'error',
              message: err,
              probeId: 'probe.tower-trust',
            })
          }
          for (const warn of trust.structural.warnings) {
            issues.push({
              id: `structural-warn:${warn.slice(0, 80)}`,
              category: 'mechanicsGraph',
              severity: 'warning',
              message: warn,
              probeId: 'probe.tower-trust',
            })
          }
          for (const inv of trust.invariants) {
            const category =
              inv.id.includes('debug') ? 'debugGraph'
                : inv.id.includes('planner') || inv.id.includes('cell') ? 'planner'
                  : inv.id.includes('verified') || inv.id.includes('provenance') ? 'provenance'
                    : inv.id.includes('silent') ? 'planner'
                      : 'mechanicsGraph'
            issues.push({
              id: inv.id,
              category,
              severity: inv.severity,
              message: inv.message,
              nodeIds: inv.nodeIds,
              surfaceIds: inv.surfaceIds,
              probeId: 'probe.tower-trust',
            })
          }
          for (const gap of trust.coverage.silentGaps) {
            issues.push({
              id: `silent-gap:${gap}`,
              category: 'planner',
              severity: 'error',
              message: `Silent coverage gap: ${gap}`,
              surfaceIds: [gap],
              probeId: 'probe.tower-trust',
            })
          }
          return issues
        },
      })

      api.probes.add({
        id: 'probe.tower-debug',
        diagnose(ctx) {
          const issues: ProbeIssue[] = []
          const dbg = loadDebugGraphDegraded()
          for (const err of dbg.errors) {
            issues.push({
              id: `debug-structural:${err.slice(0, 80)}`,
              category: 'debugGraph',
              severity: 'error',
              message: err,
              probeId: 'probe.tower-debug',
            })
          }
          for (const warn of dbg.warnings) {
            issues.push({
              id: `debug-warn:${warn.slice(0, 80)}`,
              category: 'debugGraph',
              severity: 'warning',
              message: warn,
              probeId: 'probe.tower-debug',
            })
          }
          for (const node of Object.values(dbg.graph.nodes)) {
            if (node.type !== 'runtime.path' || !node.path) continue
            const abs = path.join(ctx.repoRoot, node.path)
            if (!ctx.fs.existsSync(abs)) {
              issues.push({
                id: `fs:missing-path:${node.id}`,
                category: 'fs',
                severity: 'error',
                message: `Debug graph path missing on disk: ${node.path}`,
                paths: [node.path],
                probeId: 'probe.tower-debug',
              })
            }
          }
          return issues
        },
      })

      api.probes.add({
        id: 'probe.tower-symbols',
        diagnose() {
          const issues: ProbeIssue[] = []
          const { graph } = loadSdkGraphWithTrust({
            mode: 'degraded',
            scanPlannerCitations: true,
            checkDebugGraph: true,
          })
          const dbg = loadDebugGraphDegraded()
          const debugExportNames = new Set(
            Object.values(dbg.graph.nodes)
              .filter(n => n.type === 'runtime.symbol' && n.exportName)
              .map(n => n.exportName as string),
          )
          for (const node of Object.values(graph.nodes)) {
            for (const sym of node.codeSymbols ?? []) {
              if (!debugExportNames.has(sym)) {
                issues.push({
                  id: `symbols:missing-debug:${sym}`,
                  category: 'symbols',
                  severity: 'error',
                  message: `Mechanics codeSymbol "${sym}" has no debug runtime.symbol (node ${node.id})`,
                  nodeIds: [node.id],
                  probeId: 'probe.tower-symbols',
                })
              }
            }
          }
          return issues
        },
      })

      api.probes.add({
        id: 'probe.tower-coverage',
        diagnose(ctx) {
          const issues: ProbeIssue[] = []
          const dataDir = path.join(ctx.repoRoot, 'packages/sdk/src/mechanics/coverage/data')
          for (const file of ['sheets.v1.json', 'sdk-modules.v1.json', 'wiki.v1.json', 'save-schema.v1.json']) {
            const inv = loadInventory(path.join(dataDir, file))
            if (!inv) {
              issues.push({
                id: `coverage:missing-inventory:${file}`,
                category: file.startsWith('wiki') ? 'wiki' : file.startsWith('save') ? 'save' : 'planner',
                severity: 'error',
                message: `Missing coverage inventory ${file}`,
                paths: [`packages/sdk/src/mechanics/coverage/data/${file}`],
                probeId: 'probe.tower-coverage',
              })
              continue
            }
            for (const gap of findSilentGaps(inv)) {
              issues.push({
                id: `coverage:silent:${gap.id}`,
                category: inv.surface === 'wiki' ? 'wiki' : inv.surface === 'save' ? 'save' : 'planner',
                severity: 'error',
                message: `Silent gap in ${file}: ${gap.id}`,
                surfaceIds: [gap.id],
                probeId: 'probe.tower-coverage',
              })
            }
          }
          return issues
        },
      })

      api.probes.add({
        id: 'probe.tower-drift',
        diagnose(ctx) {
          const issues: ProbeIssue[] = []
          if (opts.skipDriftFiles) {
            driftBlock = { ok: true, skipped: true }
            if (meta) meta.drift = driftBlock
            return issues
          }
          const driftLatest = path.join(ctx.repoRoot, 'docs/mechanics-map/drift/latest.json')
          const drift = readJsonIfExists(driftLatest) as {
            ok?: boolean
            children?: Array<{ id: string; ok?: boolean; skipped?: boolean }>
          } | null
          if (!drift) {
            issues.push({
              id: 'drift:no-latest',
              category: 'drift',
              severity: 'info',
              message: 'No docs/mechanics-map/drift/latest.json — run pnpm mechanics-trust:drift',
              paths: ['docs/mechanics-map/drift/latest.json'],
              probeId: 'probe.tower-drift',
            })
            driftBlock = { ok: true, skipped: true, path: driftLatest }
          } else {
            driftBlock = {
              ok: drift.ok !== false,
              skipped: Boolean(drift.children?.every(c => c.skipped)),
              children: drift.children,
              path: driftLatest,
            }
            if (drift.ok === false) {
              issues.push({
                id: 'drift:latest-failed',
                category: 'drift',
                severity: 'error',
                message: 'Latest aggregate drift report is not ok',
                evidence: drift.children,
                probeId: 'probe.tower-drift',
              })
            }
            for (const child of drift.children ?? []) {
              if (child.skipped) continue
              if (child.ok === false) {
                issues.push({
                  id: `drift:child:${child.id}`,
                  category: 'drift',
                  severity: 'error',
                  message: `Drift child "${child.id}" failed`,
                  evidence: child,
                  probeId: 'probe.tower-drift',
                })
              }
            }
            const sheets = readJsonIfExists(
              path.join(ctx.repoRoot, 'docs/mechanics-map/drift/sheets-latest.json'),
            ) as { mismatches?: Array<{ nodeId?: string; cell?: string }> } | null
            for (const m of sheets?.mismatches ?? []) {
              if (!m.nodeId) continue
              issues.push({
                id: `drift:formula:${m.nodeId}`,
                category: 'drift',
                severity: 'error',
                message: `Sheet formula drift for ${m.nodeId}${m.cell ? ` (${m.cell})` : ''}`,
                nodeIds: [m.nodeId],
                evidence: m,
                probeId: 'probe.tower-drift',
              })
            }
          }
          if (meta) meta.drift = driftBlock
          return issues
        },
      })

      api.probes.add({
        id: 'probe.tower-tests',
        diagnose(ctx) {
          const issues: ProbeIssue[] = []
          const mechanicsDir = path.join(ctx.repoRoot, 'packages/sdk/src/mechanics')
          const allTs = walkTsFiles(mechanicsDir)
          const sources = allTs.filter(f => !f.endsWith('.test.ts') && path.basename(f) !== 'index.ts')
          const testSet = new Set(allTs.filter(f => f.endsWith('.test.ts')))
          for (const src of sources) {
            const testPath = src.replace(/\.tsx?$/, '.test.ts')
            if (testSet.has(testPath)) continue
            const severity = opts.strictTests ? 'warning' : 'info'
            const rel = path.relative(ctx.repoRoot, src).split(path.sep).join('/')
            issues.push({
              id: `tests:no-adjacent:${rel}`,
              category: 'tests',
              severity,
              message: `No adjacent test file for ${rel}`,
              paths: [rel],
              probeId: 'probe.tower-tests',
            })
          }
          return issues
        },
      })
    },
  }

  return {
    plugin,
    getMeta() {
      if (!meta) {
        const { graph, report: trust } = loadSdkGraphWithTrust({
          mode: 'degraded',
          scanPlannerCitations: true,
          checkDebugGraph: true,
        })
        const dbg = loadDebugGraphDegraded()
        meta = {
          trust,
          graph,
          debugNodeCount: Object.keys(dbg.graph.nodes).length,
          drift: driftBlock,
        }
      }
      return { ...meta, drift: driftBlock ?? meta.drift }
    },
  }
}

/** Default plugin for manifest / host info (full tower doctor probes). */
export function createTowerDoctorPlugin(opts: TowerDoctorPluginOptions = {}): Plugin {
  return createTowerDoctorSession(opts).plugin
}
