/**
 * Reading what the community wiki returns.
 *
 * Fandom serves wikitext, not data: tables written as markup, media as templates, and infoboxes
 * whose fields are positional. Everything here turns that into something typed, and it is a
 * subject of its own because the markup changes on Fandom's schedule rather than the game's.
 */
/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    —
 * depends    src/wiki/fandom/media, src/wiki/fandom/raw-tables, src/wiki/fandom/wikitext, src/wiki/fandom/wikitext-table
 * used by    —
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
export * from './media'
export * from './raw-tables'
export * from './wikitext'
export * from './wikitext-table'
