/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    isFandomWikiImageUrl, buildFandomFileRedirectUrl, fandomFileWikilinkToMarkdown, readFandomFileNamesFromMarkdown, applyFandomImageUrlMap, resolveFandomFileImages, fetchFandomImageUrlMap, resolveFandomFileImagesToCdn (+3 more)
 * depends    —
 * used by    src/mechanics/calculators/specs-generated, src/wiki/fandom/index, src/wiki/fandom/wikitext, src/wiki/index
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
const FANDOM_WIKI_HOST = 'the-tower-idle-tower-defense.fandom.com'
const FANDOM_API = `https://${FANDOM_WIKI_HOST}/api.php`

const REDIRECT_FILE_PATTERN = new RegExp(
  `https://${FANDOM_WIKI_HOST.replace(/\./g, '\\.')}/wiki/Special:Redirect/file/([^)\\s]+)`,
  'gi',
)

const FANDOM_WIKI_IMAGE_HOSTS = new Set([
  'static.wikia.nocookie.net',
  'vignette.wikia.nocookie.net',
  'images.wikia.nocookie.net',
  'the-tower-idle-tower-defense.fandom.com',
])

export function isFandomWikiImageUrl(value: unknown): boolean {
  const normalized = typeof value === 'string' ? value.trim() : ''
  if (!normalized) return false

  try {
    const parsed = new URL(normalized)
    return FANDOM_WIKI_IMAGE_HOSTS.has(parsed.hostname.toLowerCase())
  } catch {
    return false
  }
}

/** Redirect URL — blocked (403) as hotlinked `<img src>`; use CDN URLs from {@link fetchFandomImageUrlMap}. */
export function buildFandomFileRedirectUrl(fileName: string): string {
  const trimmed = fileName.trim()
  return `https://${FANDOM_WIKI_HOST}/wiki/Special:Redirect/file/${encodeURIComponent(trimmed)}`
}

function normalizeFileReference(value: string): string {
  return value.trim().replace(/^File:/i, '')
}

function normalizeFandomImageAlt(rawAlt: string, fileName: string): string {
  const alt = rawAlt.trim()
  if (!alt || alt.toLowerCase() === 'thumb') {
    return normalizeFileReference(fileName)
  }

  const altMatch = alt.match(/(?:^|\|)alt=([^|]+)$/i)
  if (altMatch?.[1]) return altMatch[1].trim()

  const parts = alt.split('|').map(part => part.trim()).filter(Boolean)
  const candidate = parts[parts.length - 1] ?? alt
  if (candidate && candidate.toLowerCase() !== 'thumb' && !/^\d+x\d+px$/i.test(candidate)) {
    return candidate
  }

  return normalizeFileReference(fileName)
}

/** Resolve Fandom `File:` references to markdown images. */
export function fandomFileWikilinkToMarkdown(fileName: string, options?: string): string {
  const alt = normalizeFandomImageAlt(options ?? fileName, fileName)
  return `![${alt}](${buildFandomFileRedirectUrl(normalizeFileReference(fileName))})`
}

function decodeRedirectFileToken(encoded: string): string {
  try {
    return decodeURIComponent(encoded)
  } catch {
    return encoded
  }
}

/** Collect unique Fandom file names referenced in markdown (redirect URLs and File: syntax). */
export function readFandomFileNamesFromMarkdown(markdown: string): string[] {
  const names = new Set<string>()

  for (const match of markdown.matchAll(REDIRECT_FILE_PATTERN)) {
    const fileName = decodeRedirectFileToken(match[1] ?? '')
    if (fileName) names.add(fileName)
  }

  for (const match of markdown.matchAll(/!\[[^\]]*\]\(File:([^)]+)\)/gi)) {
    const fileName = normalizeFileReference(match[1] ?? '')
    if (fileName) names.add(fileName)
  }

  for (const match of markdown.matchAll(/\[\[File:([^|\]]+)/gi)) {
    const fileName = normalizeFileReference(match[1] ?? '')
    if (fileName) names.add(fileName)
  }

  return [...names]
}

function lookupImageUrl(fileName: string, urlMap: Readonly<Record<string, string>>): string | null {
  const direct = urlMap[fileName]
  if (direct) return direct

  const lower = fileName.toLowerCase()
  for (const [key, url] of Object.entries(urlMap)) {
    if (key.toLowerCase() === lower) return url
  }

  return null
}

/** Replace hotlink-blocked redirect URLs with direct CDN URLs from a prebuilt map. */
export function applyFandomImageUrlMap(
  markdown: string,
  urlMap: Readonly<Record<string, string>>,
): string {
  return markdown.replace(REDIRECT_FILE_PATTERN, (match, encoded: string) => {
    const fileName = decodeRedirectFileToken(encoded)
    return lookupImageUrl(fileName, urlMap) ?? match
  })
}

/** Resolve Fandom `File:` references to markdown images. */
export function resolveFandomFileImages(markdown: string): string {
  let text = markdown.replace(/\r/g, '')

  text = text.replace(/!\[([^\]]*)\]\(([^)]+)\)/gi, (_match, rawAlt: string, target: string) => {
    if (/^https?:\/\//i.test(target.trim())) {
      const label = normalizeFandomImageAlt(rawAlt, target)
      return `![${label}](${target.trim()})`
    }
    const label = normalizeFandomImageAlt(rawAlt, target)
    return `![${label}](${buildFandomFileRedirectUrl(normalizeFileReference(target))})`
  })

  text = text.replace(/!\[([^\]]*)\]\(File:([^)]+)\)/gi, (_match, rawAlt: string, file: string) => {
    const label = normalizeFandomImageAlt(rawAlt, file)
    return `![${label}](${buildFandomFileRedirectUrl(normalizeFileReference(file))})`
  })

  text = text.replace(/\[([^\]]*)\]\(File:([^)]+)\)/gi, (_match, label: string, file: string) => {
    const alt = normalizeFandomImageAlt(label, file)
    return `![${alt}](${buildFandomFileRedirectUrl(normalizeFileReference(file))})`
  })

  text = text.replace(/\[\[File:([^|\]]+)(?:\|([^\]]+))?\]\]/gi, (_match, file: string, label?: string) => {
    const alt = normalizeFandomImageAlt(label ?? file, file)
    return `![${alt}](${buildFandomFileRedirectUrl(normalizeFileReference(file))})`
  })

  return text
}

async function fetchImageUrlBatch(fileNames: readonly string[]): Promise<Record<string, string>> {
  if (fileNames.length === 0) return {}

  const titles = fileNames.map(fileName => `File:${fileName}`).join('|')
  const params = new URLSearchParams({
    action: 'query',
    format: 'json',
    titles,
    prop: 'imageinfo',
    iiprop: 'url',
  })

  const response = await fetch(`${FANDOM_API}?${params.toString()}`)
  if (!response.ok) {
    throw new Error(`Fandom image API HTTP ${response.status}`)
  }

  const payload = await response.json()
  const pages = payload?.query?.pages ?? {}
  const map: Record<string, string> = {}

  for (const page of Object.values(pages) as Array<{ title?: string; missing?: string; imageinfo?: Array<{ url?: string }> }>) {
    if (page.missing !== undefined) continue
    const url = page.imageinfo?.[0]?.url
    const title = page.title?.replace(/^File:/i, '').trim()
    if (url && title) map[title] = url
  }

  return map
}

/** Resolve file names to direct static.wikia.nocookie.net URLs (safe for `<img src>`). */
export async function fetchFandomImageUrlMap(fileNames: readonly string[]): Promise<Record<string, string>> {
  const unique = [...new Set(fileNames.map(name => name.trim()).filter(Boolean))]
  const map: Record<string, string> = {}

  for (let index = 0; index < unique.length; index += 40) {
    const batch = unique.slice(index, index + 40)
    const batchMap = await fetchImageUrlBatch(batch)
    Object.assign(map, batchMap)
  }

  return map
}

/** Resolve all Fandom image references in markdown to CDN URLs via the Fandom API. */
export async function resolveFandomFileImagesToCdn(markdown: string): Promise<string> {
  const fileNames = readFandomFileNamesFromMarkdown(markdown)
  if (fileNames.length === 0) return markdown
  const urlMap = await fetchFandomImageUrlMap(fileNames)
  return applyFandomImageUrlMap(markdown, urlMap)
}

const WIKIA_CDN_URL_PATTERN = /https:\/\/(?:static|vignette|images)\.wikia\.nocookie\.net[^\s)]+/gi

/** Collect unique Wikia CDN image URLs already present in markdown. */
export function readWikiaCdnImageUrlsFromMarkdown(markdown: string): string[] {
  return [...new Set([...markdown.matchAll(WIKIA_CDN_URL_PATTERN)].map(match => match[0]?.trim()).filter(Boolean))]
}

export function wikiLocalAssetPathFromCdnUrl(cdnUrl: string): string {
  const parsed = new URL(cdnUrl)
  const pathMatch = parsed.pathname.match(/\/images\/(.+?)(?:\/revision|$)/i)
  const slug = (pathMatch?.[1] ?? parsed.pathname).replace(/\//g, '-').replace(/[^a-zA-Z0-9._-]+/g, '_')
  const extMatch = slug.match(/(\.[a-z0-9]+)$/i)
  const fileName = extMatch ? slug : `${slug}.png`
  return `/wiki-assets/${fileName}`
}

/** Replace Wikia CDN image URLs with same-origin static asset paths. */
export function applyWikiLocalAssetUrlMap(
  markdown: string,
  urlMap: Readonly<Record<string, string>>,
): string {
  return markdown.replace(WIKIA_CDN_URL_PATTERN, match => urlMap[match] ?? match)
}
