/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    FandomWikitextContext, convertFandomWikitextToMarkdown, scoreFandomMarkdownQuality
 * depends    src/wiki/fandom/media, src/wiki/fandom/wikitext-table
 * used by    src/mechanics/calculators/specs-generated, src/wiki/fandom/index, src/wiki/index, src/wiki/sources
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
import { fandomFileWikilinkToMarkdown, resolveFandomFileImages } from './media'
import { renderVerticalWikitableBlock } from './wikitext-table'

const STRIP_TEMPLATES = new Set([
  'Workshop',
  'DEFAULTSORT',
  'Clear',
  'TOC',
  'toc',
])

export interface FandomWikitextContext {
  pageTitle: string
  templates?: Readonly<Record<string, string>>
  transclusions?: Readonly<Record<string, string>>
}

function stripWikiNoise(text: string): string {
  return text
    .replace(/\r/g, '')
    .replace(/<!--[\s\S]*?-->/g, '')
    .replace(/<ref[^>]*\/>/g, '')
    .replace(/<ref[^>]*>[\s\S]*?<\/ref>/g, '')
}

function expandTemplateAndTransclusionSyntax(text: string, context: FandomWikitextContext): string {
  let result = text
  let changed = true
  let guard = 0

  while (changed && guard < 12) {
    changed = false
    guard += 1

    result = result.replace(/\{\{([^}{}]+)\}\}/g, (match, rawExpression: string) => {
      const expression = rawExpression.trim()
      if (expression.startsWith(':')) {
        const title = expression.slice(1).trim()
        const body = context.transclusions?.[title]
        if (body) {
          changed = true
          return body
        }
        return ''
      }

      const templateName = expression.split('|')[0]?.trim() ?? ''
      if (!templateName || STRIP_TEMPLATES.has(templateName)) {
        changed = true
        return ''
      }

      const templateBody = context.templates?.[templateName]
      if (templateBody) {
        changed = true
        return templateBody
      }

      return ''
    })
  }

  return result
}

const TABBER_PANEL_DELIMITER = /\|-\||-\|/

function stripTabberPanelPrefix(value: string): string {
  return value.trim().replace(new RegExp(`^\\s*${TABBER_PANEL_DELIMITER.source}`), '')
}

function splitTabberPanels(tabberInner: string): Array<{ title: string; body: string }> {
  const panels: Array<{ title: string; body: string }> = []
  const normalized = stripTabberPanelPrefix(tabberInner)
  const parts = normalized
    .split(new RegExp(`\\n\\s*${TABBER_PANEL_DELIMITER.source}`, 'g'))
    .map(part => stripTabberPanelPrefix(part))
    .filter(Boolean)

  for (const part of parts) {
    const equalsIndex = part.indexOf('=')
    if (equalsIndex === -1) {
      panels.push({ title: 'Section', body: part })
      continue
    }

    panels.push({
      title: part.slice(0, equalsIndex).trim(),
      body: part.slice(equalsIndex + 1).trim(),
    })
  }

  return panels
}

const WIKI_TAB_MARKER_PATTERN = /<!--\s*wiki-tab:[\s\S]+?\s*-->/gi

function hasLeadingWikiSectionHeading(body: string): boolean {
  return /^={2,6}\s*.+?\s*={2,6}\s*(?:\n|$)/m.test(body.trim())
}

/** Each tab panel needs a section heading so markdown split can attach body content. */
function ensurePanelSectionHeading(body: string, title: string): string {
  const trimmed = body.trim()
  if (!trimmed) return `== ${title} ==\n\n`
  if (hasLeadingWikiSectionHeading(trimmed)) return trimmed
  return `== ${title} ==\n\n${trimmed}`
}

function expandTabberToHeadings(text: string, context: FandomWikitextContext): string {
  return text.replace(/<tabber>\s*([\s\S]*?)\s*<\/tabber>/gi, (_match, inner: string) => {
    const panels = splitTabberPanels(inner.trim())
    return panels
      .map(panel => {
        let body = expandTemplateAndTransclusionSyntax(panel.body.trim(), context)
        body = ensurePanelSectionHeading(body, panel.title)
        return `<!-- wiki-tab:${panel.title} -->\n\n${body}`
      })
      .join('\n\n')
  })
}

function convertWikiHeadingLine(line: string): string | null {
  const match = line.trim().match(/^(={1,6})\s*(.+?)\s*\1$/)
  if (!match) return null

  const level = match[1].length
  const title = match[2]?.trim() ?? ''
  if (!title) return null

  const markdownLevel = Math.min(Math.max(level, 2), 6)
  return `${'#'.repeat(markdownLevel)} ${title}`
}

function convertParagraphLine(line: string): string {
  let text = line.trim()
  text = text.replace(/'''\s*(.*?)\s*'''/g, (_match, inner: string) => {
    const normalized = inner.replace(/<u>\s*(.*?)\s*<\/u>/gi, '**$1**').trim()
    if (/\*\*/.test(normalized)) return normalized
    return `**${normalized}**`
  })
  text = text.replace(/''\s*(.*?)\s*''/g, '*$1*')
  text = text.replace(/<u>\s*(.*?)\s*<\/u>/gi, '**$1**')
  text = text.replace(/\*{3,}/g, '**')
  text = text.replace(/\[\[File:([^|\]]+)\|([^\]]+)\]\]/gi, (_match, file: string, options: string) =>
    fandomFileWikilinkToMarkdown(file, options),
  )
  text = text.replace(/\[\[File:([^|\]]+)\]\]/gi, (_match, file: string) =>
    fandomFileWikilinkToMarkdown(file),
  )
  text = text.replace(/\[\[([^|\]]+)\|([^\]]+)\]\]/g, '[$2]($1)')
  text = text.replace(/\[\[([^\]]+)\]\]/g, '[$1]($1)')
  return text
}

function isBlankLine(line: string): boolean {
  return line.trim() === ''
}

function emitWikiTabMarkersFromLine(line: string, output: string[]): string {
  let remainder = line
  WIKI_TAB_MARKER_PATTERN.lastIndex = 0
  let match = WIKI_TAB_MARKER_PATTERN.exec(line)
  while (match) {
    const before = remainder.slice(0, match.index).trim()
    if (before) output.push(before)
    output.push(match[0].trim())
    output.push('')
    remainder = remainder.slice(match.index + match[0].length)
    WIKI_TAB_MARKER_PATTERN.lastIndex = 0
    match = WIKI_TAB_MARKER_PATTERN.exec(remainder)
  }
  return remainder.trim()
}

function convertDocumentBody(text: string): string {
  const lines = text.replace(/\r/g, '').split('\n')
  const output: string[] = []
  let index = 0

  while (index < lines.length) {
    const line = lines[index] ?? ''
    const trimmed = line.trim()

    if (isBlankLine(trimmed)) {
      index += 1
      continue
    }

    if (WIKI_TAB_MARKER_PATTERN.test(trimmed)) {
      WIKI_TAB_MARKER_PATTERN.lastIndex = 0
      const tail = emitWikiTabMarkersFromLine(trimmed, output)
      if (tail) {
        output.push(tail)
        output.push('')
      }
      index += 1
      continue
    }

    if (trimmed.startsWith('{|')) {
      const table = renderVerticalWikitableBlock(lines, index)
      if (table) {
        output.push(...table.markdown)
        index = table.nextIndex
        continue
      }
    }

    const heading = convertWikiHeadingLine(line)
    if (heading) {
      output.push(heading)
      output.push('')
      index += 1
      continue
    }

    if (trimmed.startsWith('* ') || trimmed.startsWith('# ')) {
      output.push(convertParagraphLine(line))
      index += 1
      continue
    }

    const paragraph: string[] = [convertParagraphLine(line)]
    index += 1
    while (index < lines.length) {
      const candidate = lines[index] ?? ''
      const candidateTrimmed = candidate.trim()
      if (!candidateTrimmed) break
      if (candidateTrimmed.startsWith('{|')) break
      if (convertWikiHeadingLine(candidate)) break
      WIKI_TAB_MARKER_PATTERN.lastIndex = 0
      if (WIKI_TAB_MARKER_PATTERN.test(candidateTrimmed)) break
      paragraph.push(convertParagraphLine(candidate))
      index += 1
    }

    output.push(paragraph.join(' '))
    output.push('')
  }

  return output.join('\n').trim()
}

/** Canonical MediaWiki wikitext → markdown for Fandom game wiki pages. */
export function convertFandomWikitextToMarkdown(
  wikitext: string,
  context: FandomWikitextContext,
): string {
  let text = stripWikiNoise(wikitext)
  text = expandTabberToHeadings(text, context)
  text = expandTemplateAndTransclusionSyntax(text, context)
  text = convertDocumentBody(text)
  return resolveFandomFileImages(text)
}

export function scoreFandomMarkdownQuality(content: string): number {
  const tableRows = (content.match(/^\|[^\n]+\|$/gm) ?? []).length
  const headings = (content.match(/^#{2,6}\s+/gm) ?? []).length
  const dotFallback = /(?:^|\n)[A-Za-z][^\n]{0,48} · (?:\d|[x\d.%])/m.test(content) ? -40 : 0
  const rawHtml = /<tabber|<\/tabber>|class="fandom-table"|\{\{[^}]+\}\}/i.test(content) ? -50 : 0
  return content.length + tableRows * 120 + headings * 40 + dotFallback + rawHtml
}
