/**
 * What a workshop upgrade is worth at a given level.
 *
 * This is a question about the game, and it lived in `internal/game-input-data/
 * workshop-stat-dropdown-math.ts` — a module named for a widget — because a dropdown was the first
 * thing that needed it. Nothing about it is a dropdown: given a stat and a level it returns the
 * stat's value, and `mechanics/modules/ilm-charge.ts` calls it to price Attack Damage.
 *
 * That misfiling is the shape the whole `internal/` folder took. A game fact needed by a control
 * ends up stored next to the control, and then the package cannot tell its own knowledge from its
 * consumer's plumbing.
 */
/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    computeWorkshopStatNumericValueAtLevel, WORKSHOP_ENHANCEMENT_KEY_ALIASES, getWorkshopEnhancementDataKey, computeWorkshopEnhancementMaxLevel
 * depends    src/data/workshop/costs, src/data/workshop/progress-definitions, src/support/own-lookup
 * used by    src/data/workshop/index, src/mechanics/calculators/specs-generated
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
import { getWorkshopMaxLevelByKey } from './costs'
import { getWorkshopStatDefinitionByKey } from './progress-definitions'
import { ownLookupOr } from '../../support/own-lookup'

/**
 * The stat's value at `level`, clamped into the levels the upgrade actually has.
 *
 * Returns 0 for an unknown stat rather than throwing, and falls back to the minimum level's row
 * when the clamped level has none — a gap in a curve is a data problem for the catalog tests to
 * report, not a reason for a caller pricing an upgrade to crash.
 *
 * Note that `level` is clamped rather than rejected: callers pass user-entered numbers, and the
 * value at a level above the cap is the value at the cap.
 */
export function computeWorkshopStatNumericValueAtLevel(statKey: string, level: number): number {
  const stat = getWorkshopStatDefinitionByKey(statKey)
  if (!stat) return 0

  const clamped = Math.max(stat.minLevel, Math.min(stat.maxLevel, Math.floor(level)))
  const row = stat.levels.find(entry => entry.level === clamped)
    ?? stat.levels.find(entry => entry.level === stat.minLevel)
  return row?.value ?? 0
}

/**
 * Enhancement keys that arrive under a second spelling.
 *
 * One entry, and it earns its place: `cells_per_kill_bonus` is how the key reaches this package
 * from elsewhere, while the cost tables file it as `WSP_CELLS_PER_KILL_BONUS`.
 */
export const WORKSHOP_ENHANCEMENT_KEY_ALIASES: Readonly<Record<string, string>> = {
  cells_per_kill_bonus: 'WSP_CELLS_PER_KILL_BONUS',
}

/** The key the cost tables file an enhancement under, given either of its spellings. */
export function getWorkshopEnhancementDataKey(enhancementKey: string): string {
  return ownLookupOr(WORKSHOP_ENHANCEMENT_KEY_ALIASES, enhancementKey, enhancementKey)
}

/**
 * How many levels an enhancement has.
 *
 * The `+ 1` is not an off-by-one: cost tables are indexed from 0, so a table whose last index is
 * 74 prices 75 levels. `oracle_traps('workshop')` is emphatic that this number is not uniform —
 * eleven of the eighteen run to 400, but Cash Bonus stops at 300, Orb Size, Coin Bonus and Cells
 * per Kill at 200, Free Upgrades at 100, Attack Speed at 75 and Enemy Level Skip at 60. Pricing
 * every enhancement on the Damage ladder overstates seven of them badly.
 * `enhancement-ladders.test.ts` pins all eighteen against the oracle's figures.
 *
 * The 200 for an unknown key is inherited and is a guess — 200 is the right answer for three of
 * the eighteen and wrong for the other fifteen. It is preserved rather than corrected because
 * callers price upgrades against it, but a caller passing a key this package does not know gets a
 * plausible number rather than an error, which is the shape of defect this repository keeps
 * finding. Worth revisiting deliberately.
 */
export function computeWorkshopEnhancementMaxLevel(enhancementKey: string): number {
  const costMax = getWorkshopMaxLevelByKey(getWorkshopEnhancementDataKey(enhancementKey))
  if (costMax == null) return 200
  return costMax + 1
}
