/**
 * Ultimate weapon unlocks and upgrade levels.
 *
 * Levels are stored as stone-chart indices rather than as the stat value they buy, so a reader that
 * treats one as the other is off by an entire lookup.
 */
/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    —
 * depends    src/save/ultimate-weapons/read
 * used by    —
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
export * from './read'
