/**
 * The arithmetic and the fixed values every other mechanic is built on.
 *
 * `math` is deliberately small and deliberately not lodash: `clamp`, `lerp`, `inverseLerp`,
 * `safeMul` and `uniformRoll` are the operations the game's own formulas are written in, and
 * having them in one place is what lets a port be checked against the game's own behaviour.
 *
 * `unity-random` mirrors Unity's PRNG rather than wrapping `Math.random`. It is here because it
 * is a primitive of the engine the game runs on, and because its seed advances — the one piece of
 * state in this domain.
 */
/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    —
 * depends    src/mechanics/primitives/constants, src/mechanics/primitives/math, src/mechanics/primitives/units, src/mechanics/primitives/unity-random
 * used by    —
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
export * from './math'
export * from './units'
export * from './constants'
export * from './unity-random'
