/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    UnityRandomState, initUnityRandom, cloneUnityRandomState, UnityRandom
 * depends    —
 * used by    src/mechanics/bots/medal-simulation, src/mechanics/bots/movement, src/mechanics/calculators/specs-generated, src/mechanics/index, src/mechanics/primitives/index
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
/**
 * `UnityEngine.Random` — xorshift128, as the engine actually implements it.
 *
 * Matches Unity's persisted `moduleRandom` field: four 32-bit integers, stored signed.
 * Seed a stream with `initUnityRandom(seed)`, or resume one from a saved
 * `{ s0, s1, s2, s3 }` state.
 *
 * ## Every line here is load-bearing
 *
 * This reproduces Unity's generator exactly, and each of the following was wrong at some
 * point in a way that still produced a perfectly plausible stream. None of them broke a
 * bound, so no bounds check caught any of them. `tests/mechanics/unity-random.test.ts`
 * pins the exact outputs; treat a change that moves them as a defect until proven
 * otherwise.
 *
 * 1. **Seeding must use `Math.imul`.** A 32x32-bit product reaches ~10^19, far past 2^53,
 *    so evaluating it as an ordinary float64 multiply loses the low bits before the int32
 *    truncation ever runs — the wrong result for 99.5% of seeds.
 * 2. **The three seed words chain a single constant** through one another, rather than
 *    each deriving independently from the seed.
 * 3. **`value()` is closed at both ends.** It takes 23 bits and scales by a constant just
 *    above 2^-23 (`VALUE_SCALE`), so 1.0 is attainable. Scaling 31 bits by 2^-31 gives a
 *    half-open range and a different distribution.
 * 4. **`rangeInt` is a modulus, not `floor(value() * n)`.** That form also returns `n`
 *    itself once `value()` can reach 1.0, so the two defects were masking each other and
 *    fixing either alone would have exposed an out-of-range index.
 *
 * The step function in `nextUint` looks unlike the usual formulation because XOR is
 * associative, not because it disagrees. It is correct. Leave it alone.
 */

export interface UnityRandomState {
  s0: number
  s1: number
  s2: number
  s3: number
}

/** Mersenne Twister's initialisation multiplier — the seeding recurrence, not the step. */
const MT19937 = 1_812_433_253

/**
 * `Random.value`'s multiplier: 1/8388607 rounded to single precision.
 *
 * Very slightly LARGER than 2^-23, and that is not a rounding artefact — it is the reason
 * `value()` can return exactly 1.0. Scaling by 2^-23 instead tops out at 0.99999988 and
 * never reaches the top of the range.
 */
const VALUE_SCALE = 1.1920930376163597e-7

function toUint32(value: number): number {
  return value >>> 0
}

function toInt32(value: number): number {
  const u = value >>> 0
  return u > 0x7fffffff ? u - 0x1_0000_0000 : u
}

/**
 * Expand a single seed into Unity's `InitState` quadruple.
 *
 * `x` IS the seed — there is no non-zero fallback for seed 0. Substituting one looks
 * defensive (an all-zero state is absorbing for xorshift) but silently changes every draw,
 * and Unity does not do it.
 */
export function initUnityRandom(seed: number): UnityRandomState {
  const x = toUint32(seed)
  const y = toUint32(Math.imul(MT19937, x) + 1)
  const z = toUint32(Math.imul(MT19937, y) + 1)
  const w = toUint32(Math.imul(MT19937, z) + 1)
  return { s0: toInt32(x), s1: toInt32(y), s2: toInt32(z), s3: toInt32(w) }
}

export function cloneUnityRandomState(state: UnityRandomState): UnityRandomState {
  return { s0: state.s0, s1: state.s1, s2: state.s2, s3: state.s3 }
}

export class UnityRandom {
  private s0: number
  private s1: number
  private s2: number
  private s3: number

  constructor(state: UnityRandomState) {
    this.s0 = state.s0
    this.s1 = state.s1
    this.s2 = state.s2
    this.s3 = state.s3
  }

  static fromSeed(seed: number): UnityRandom {
    return new UnityRandom(initUnityRandom(seed))
  }

  getState(): UnityRandomState {
    return { s0: this.s0, s1: this.s1, s2: this.s2, s3: this.s3 }
  }

  setState(state: UnityRandomState): void {
    this.s0 = state.s0
    this.s1 = state.s1
    this.s2 = state.s2
    this.s3 = state.s3
  }

  /** Raw 32-bit step (Unity internal PRNG). Verified equivalent to the engine's. */
  nextUint(): number {
    let t = toUint32(this.s0)
    t ^= t << 11
    t ^= t >>> 8
    this.s0 = this.s1
    this.s1 = this.s2
    this.s2 = this.s3
    let w = toUint32(this.s3)
    w ^= w >>> 19
    w ^= t
    this.s3 = toInt32(w)
    return toUint32(w)
  }

  /**
   * Unity `Random.value` — float in [0, 1], and **both** ends are attainable.
   *
   * 23 mantissa bits scaled by `VALUE_SCALE`, so the maximum draw lands on exactly 1.0.
   * `Math.fround` is not decoration: Unity computes this in single precision, and the whole
   * point of the constant is a last-bit match.
   */
  value(): number {
    return Math.fround((this.nextUint() & 0x7fffff) * VALUE_SCALE)
  }

  /**
   * Unity `Random.Range(float, float)` — min inclusive, max INCLUSIVE.
   *
   * The evaluation order `min * t + (1 - t) * max` is load-bearing. The algebraically
   * identical `(min - max) * t + max` rounds differently on 38% of `Range(0, 100)` draws
   * and 55% of `Range(-3.5, 7.25)`. Each step is rounded to single precision because
   * Unity's is.
   */
  rangeFloat(min: number, max: number): number {
    const t = this.value()
    return Math.fround(Math.fround(min * t) + Math.fround(Math.fround(1 - t) * max))
  }

  /**
   * Unity `Random.Range(min, max)` for integers — max is EXCLUSIVE.
   *
   * A modulus, not `floor(value() * n)`. Computed in JS numbers rather than int32 for the
   * same reason the C# does it in Int64: `min + r % (max - min)` overflows 32 bits for wide
   * ranges. Every intermediate here stays under 2^53, so float64 holds them exactly.
   *
   * JS `%` takes the sign of the dividend, which is what C# does too, so the inverted-range
   * branch needs no correction. (Python's takes the sign of the divisor — the same
   * transcription there returned a value outside the range entirely.)
   */
  rangeInt(minInclusive: number, maxExclusive: number): number {
    const min = Math.floor(minInclusive)
    const max = Math.floor(maxExclusive)
    if (max - min === 0) return min
    const r = this.nextUint()
    return max < min ? min - (r % (max - min)) : min + (r % (max - min))
  }

  /** Pick uniform index in `[0, length)`. */
  pickIndex(length: number): number {
    if (length <= 0) return 0
    return this.rangeInt(0, length)
  }
}
