/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    readDurationSecondsFromSave, formatBattleDurationFromSaveSeconds
 * depends    —
 * used by    src/mechanics/calculators/specs-generated, src/save/battle-report-fields, src/save/battle-reports, src/save/index
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
const TICKS_PER_SECOND = 10_000_000
/** Values at or above this are treated as .NET TimeSpan ticks. */
const MIN_TICKS_MAGNITUDE = 1_000_000_000
/** NRBF TimeSpan primitives are often stored at millisecond scale once decoded. */
const MIN_DECODER_MILLISECONDS_MAGNITUDE = 1_000_000
/** Up to ~35 days of wall-clock seconds. */
const MAX_PLAUSIBLE_SECONDS = 86_400 * 35
const ONE_DAY_SECONDS = 86_400
const ONE_HOUR_SECONDS = 3_600

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value)
}

function isTimeSpanRecord(raw: Record<string, unknown>): boolean {
  return typeof raw.typeName === 'string' && raw.typeName.toLowerCase().includes('timespan')
}

type DurationCandidate = { seconds: number; kind: 'ticks' | 'ms' | 'raw' }

function buildDurationCandidates(abs: number): DurationCandidate[] {
  const candidates: DurationCandidate[] = [{ seconds: abs, kind: 'raw' }]

  if (abs >= MIN_TICKS_MAGNITUDE) {
    candidates.push({ seconds: abs / TICKS_PER_SECOND, kind: 'ticks' })
  }

  candidates.push({ seconds: abs / 1000, kind: 'ms' })

  return candidates
}

/** True when the save integer is a whole millisecond count (e.g. 180000 -> 180s). */
function isMillisecondEncodedInteger(abs: number, msSeconds: number): boolean {
  if (!Number.isInteger(abs) || abs % 1000 !== 0) {
    return false
  }
  return Math.abs(msSeconds * 1000 - abs) <= 1
}

function pickBestDurationSeconds(abs: number): number {
  const plausible = buildDurationCandidates(abs).filter(
    candidate => candidate.seconds > 0 && candidate.seconds <= MAX_PLAUSIBLE_SECONDS,
  )

  if (plausible.length === 0) {
    if (abs >= MIN_TICKS_MAGNITUDE) {
      return abs / TICKS_PER_SECOND
    }
    if (abs >= MIN_DECODER_MILLISECONDS_MAGNITUDE) {
      return abs / 1000
    }
    return abs
  }

  const raw = plausible.find(candidate => candidate.kind === 'raw')
  const ms = plausible.find(candidate => candidate.kind === 'ms')
  const ticks = plausible.find(candidate => candidate.kind === 'ticks')

  if (ticks && (!raw || ticks.seconds >= raw.seconds / 10)) {
    return ticks.seconds
  }

  if (raw && ms) {
    if (isMillisecondEncodedInteger(abs, ms.seconds)) {
      return ms.seconds
    }

    if (
      raw.seconds >= ONE_DAY_SECONDS
      && ms.seconds < ONE_HOUR_SECONDS
      && abs < MIN_DECODER_MILLISECONDS_MAGNITUDE
    ) {
      return raw.seconds
    }

    if (
      raw.seconds < ONE_DAY_SECONDS
      && ms.seconds < ONE_HOUR_SECONDS
      && raw.seconds > ms.seconds * 10
    ) {
      return raw.seconds
    }
  }

  return Math.max(...plausible.map(candidate => candidate.seconds))
}

function normalizeDurationMagnitude(value: number, options?: { forceTicks?: boolean }): number {
  const abs = Math.abs(value)
  if (abs === 0) {
    return 0
  }

  if (options?.forceTicks && abs >= 1) {
    return abs / TICKS_PER_SECOND
  }

  return pickBestDurationSeconds(abs)
}

/**
 * Reads battle-history duration fields (`gameTime`, `realTime`, etc.) from NRBF JSON shapes.
 */
export function readDurationSecondsFromSave(raw: unknown): number | null {
  if (raw === null || raw === undefined) {
    return null
  }

  if (typeof raw === 'number' && Number.isFinite(raw)) {
    return normalizeDurationMagnitude(raw)
  }

  if (typeof raw === 'string' && raw.trim() !== '') {
    const parsed = Number(raw.trim())
    if (Number.isFinite(parsed)) {
      return normalizeDurationMagnitude(parsed)
    }
    return null
  }

  if (!isRecord(raw)) {
    return null
  }

  if (raw.__type === 'BigInt' && raw.__value != null) {
    const ticks = Number(raw.__value)
    if (Number.isFinite(ticks)) {
      return normalizeDurationMagnitude(ticks, { forceTicks: true })
    }
  }

  if ('value__' in raw) {
    const inner = raw.value__
    const numericInner = typeof inner === 'number' && Number.isFinite(inner)
      ? inner
      : typeof inner === 'string' && inner.trim() !== ''
        ? Number(inner.trim())
        : NaN
    if (Number.isFinite(numericInner)) {
      const forceTicks = isTimeSpanRecord(raw) && Math.abs(numericInner) >= MIN_TICKS_MAGNITUDE
      return normalizeDurationMagnitude(numericInner, { forceTicks })
    }
  }

  if (typeof raw.totalSeconds === 'number' && Number.isFinite(raw.totalSeconds)) {
    return normalizeDurationMagnitude(raw.totalSeconds)
  }

  if (typeof raw.seconds === 'number' && Number.isFinite(raw.seconds)) {
    return normalizeDurationMagnitude(raw.seconds)
  }

  return null
}

/** Formats seconds into tracker-style `XhYmZs` duration strings. */
export function formatBattleDurationFromSaveSeconds(seconds: number): string {
  const totalSeconds = Math.max(0, Math.round(seconds))
  const hours = Math.floor(totalSeconds / 3600)
  const minutes = Math.floor((totalSeconds % 3600) / 60)
  const secs = totalSeconds % 60
  return `${hours}h${minutes}m${secs}s`
}
