/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    findBattleHistoryItems, looksLikeBattleRun, countImportableBattleRuns, listImportableBattleRuns, COINS_PER_HOUR_RUN_SAMPLE, computeCoinsPerHourFromSaveRoot
 * depends    src/save/read-values
 * used by    src/mechanics/calculators/specs-generated, src/node/decode-save, src/save/battle-reports, src/save/import-counts, src/save/import-discovery, src/save/index (+1 more)
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
import { readSaveListItems } from './read-values'

/** Locate battle history array inside NRBF-parsed save root (case-insensitive key). */
export function findBattleHistoryItems(parsedRoot: unknown): unknown[] | null {
  if (!parsedRoot || typeof parsedRoot !== 'object') {
    return null
  }

  const root = parsedRoot as Record<string, unknown>
  for (const key of Object.keys(root)) {
    if (!/battlehistory/i.test(key)) {
      continue
    }
    const history = root[key]
    if (!history || typeof history !== 'object') {
      continue
    }
    /*
     * `_size`, not the capacity. `battleHistory` is 30 live runs in a 32-slot
     * array here, and a stale entry past the end carries every field
     * `looksLikeBattleRun` checks for -- so it would import as a run the player
     * never played.
     */
    if (Array.isArray((history as { _items?: unknown })._items)) {
      return readSaveListItems(history)
    }
  }

  return null
}

export function looksLikeBattleRun(run: unknown): boolean {
  if (!run || typeof run !== 'object') {
    return false
  }
  const entry = run as Record<string, unknown>
  return (
    'tier' in entry
    || 'wave' in entry
    || 'battleDate' in entry
    || 'isTournament' in entry
    || 'killedBy' in entry
    || 'coinsEarned' in entry
  )
}

export function countImportableBattleRuns(parsedRoot: unknown): number {
  const items = findBattleHistoryItems(parsedRoot)
  if (!items) {
    return 0
  }
  return items.filter(looksLikeBattleRun).length
}

export function listImportableBattleRuns(parsedRoot: unknown): Record<string, unknown>[] {
  const items = findBattleHistoryItems(parsedRoot)
  if (!items) {
    return []
  }
  return items.filter(looksLikeBattleRun) as Record<string, unknown>[]
}

/** How many of a player's best runs the game averages for its coins/hour stat. */
export const COINS_PER_HOUR_RUN_SAMPLE = 3

const SECONDS_PER_HOUR = 3600

function finitePositive(value: unknown): number | null {
  const numeric = typeof value === 'number' ? value : Number(value)
  return Number.isFinite(numeric) && numeric > 0 ? numeric : null
}

/**
 * The player's coins per hour, as the game's own stat panel derives it.
 *
 * Mean of the **three best** runs in battle history, where a run's rate is
 * `coinsEarned / (realTime / 3600)`. Runs missing either field are dropped,
 * the rates are sorted descending, and the top three — or fewer, if that is
 * all there is — are averaged. `null` when no run qualifies.
 *
 * Worth having because it is an *input*, not a readout: Effective Paths prices
 * the time path partly in coin-farming days, so without a real rate a caller
 * has to ask the player to type one or fall back to a default that makes every
 * cost on a developed account look astronomical.
 *
 * **It is a peak, not a sustained rate.** Averaging the best three runs is what
 * the game's own stat panel does, and it will read higher than what a player
 * actually earns per hour over a week. Offer it as a starting value rather than
 * substituting it for a figure the player has given you.
 *
 * @example
 * const rate = computeCoinsPerHourFromSaveRoot(parsedRoot)
 * planEffectiveEconomyPath({ …, coinsPerHour: rate ?? undefined })
 */
export function computeCoinsPerHourFromSaveRoot(parsedRoot: unknown): number | null {
  const rates: number[] = []

  for (const run of listImportableBattleRuns(parsedRoot)) {
    const coins = finitePositive(run.coinsEarned)
    const seconds = finitePositive(run.realTime)
    if (coins === null || seconds === null) continue
    rates.push(coins / (seconds / SECONDS_PER_HOUR))
  }

  if (rates.length === 0) return null

  const best = rates.sort((a, b) => b - a).slice(0, COINS_PER_HOUR_RUN_SAMPLE)
  return best.reduce((total, rate) => total + rate, 0) / best.length
}
