/**

 * IDS import: card presets, relics, perks, and the capture safety net.
 *
 * Split out of `ids-import-domains.ts` along that file's own section banners when it passed
 * the 1,200-line limit. A strict move — not one reader was edited.
 */
/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    IdsCardPresetSlot, IdsCardPresetsExtract, readIdsCardPresets, IdsCapturedRow, IdsCapturedBlock, readIdsCapturedBlocks, findIdsUncapturedCells, readIdsAssistCaps (+9 more)
 * depends    src/data/assets, src/data/player-stats, src/data/workshop-enhancement-tracker-definitions, src/data/workshop-tracker-definitions, src/save/cards, src/save/catalogs/guardians (+9 more)
 * used by    src/mechanics/calculators/specs-generated, src/save/index
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */

/**
 * The IDS blocks beyond Labs, turned into save-shaped fields.
 *
 * Same contract as `ids-import.ts`: read the player's IDS Master, emit a
 * `parsedRoot`-shaped object, and let the existing save readers, import
 * composables and `finishTrackerImportPersistence` do their own jobs unchanged.
 * Nothing here writes anything.
 *
 * ## Not every block is importable, and saying so is part of the job
 *
 * The IDS is the EP sheet's input layer, not a copy of the save. Some blocks
 * hold what a tracker needs (Cards levels, Workshop levels); others hold EP's
 * DERIVED aggregates -- the Vault block carries "Total Bonuses" per stat rather
 * than per-node levels, and the Relics block carries owned COUNTS and summed
 * bonuses rather than which relics a player owns. Neither can reconstruct the
 * array its tracker stores, so neither is mapped. `idsDomainCoverage()` reports
 * that rather than leaving it to be discovered as an empty tracker.
 */
import { aliasFor, asNumber, asText, cell, type Grid, normalizeName } from './ids-grid'
import { findPerkNameByIndex, listActivePerkIndices } from './catalogs/perks'
import { GUARDIANS_ASSET_TABLE } from '../data/assets'
import { CARD_IMPORT_CATALOG } from '../data/player-stats'
import { getWorkshopEnhancementDefinitions } from '../data/workshop-enhancement-tracker-definitions'
import { getWorkshopStatDefinitions } from '../data/workshop-tracker-definitions'
import { findCardCatalogFromSaveIndex } from './cards'
import { listGuardianChipSlotCatalogRows } from './catalogs/guardians'
import { HARMONY_VAULT_TRACKER_SLOT_BINDINGS } from './catalogs/vault'
import { listUltimateWeaponCatalogRows } from './catalogs/ultimate-weapons'
import {
  asLevel,
  type IdsBlock,
  readIdsBlocks,
} from './ids-import'
import {
  findIdsModuleGroupColumns,
  type IdsModuleCategory,
} from './ids-import-modules'
import {
  findBlock,
} from './ids-import-blocks'
import {
  parseIdsDisplayLevel,
  resolveIdsCardSaveIndex,
} from './ids-import-domains'
import {
  readIdsVaultUnlocks,
} from './ids-import-progression'


/* ---------------------------------------------------------- card presets */

export interface IdsCardPresetSlot {
  presetIndex: number
  presetName: string
  slotIndex: number
  cardName: string
  saveIndex: number | null
}

export interface IdsCardPresetsExtract {
  presetNames: string[]
  slots: IdsCardPresetSlot[]
  unmatchedNames: string[]
  warnings: string[]
}

/**
 * The `Cards Presets` block: one ordered column per preset.
 *
 * The save stores this as `slotPresetCardInt[preset][slot] = cardIndex`, with a
 * parallel `slotPresetCardAssignedBool` saying which slots are filled -- so the
 * sheet's column IS the preset and the row order IS the slot order. Both are
 * positional and neither needs a name join; only the card in each cell does.
 *
 * Slot ORDER is real data, not presentation: the first row of a preset column
 * is slot 0. Sorting or de-duplicating the column would silently rearrange a
 * player's loadout.
 */
export function readIdsCardPresets(grid: Grid): IdsCardPresetsExtract {
  const block = findBlock(grid, 'Cards Presets')
  if (!block) {
    return { presetNames: [], slots: [], unmatchedNames: [], warnings: ['No "Cards Presets" block on _IDS.'] }
  }

  /*
   * The preset names sit on the first row under the heading that has a name in
   * the block's own first column. Found rather than fixed, because the heading
   * row also carries a version string and a slot count in the columns beside
   * it, and those move between releases.
   */
  let nameRow = -1
  for (let row = 1; row < Math.min(grid.length, 5); row += 1) {
    if (asText(cell(grid, row, block.fromColumn))) {
      nameRow = row
      break
    }
  }
  if (nameRow < 0) {
    return { presetNames: [], slots: [], unmatchedNames: [], warnings: ['The "Cards Presets" block has no preset row.'] }
  }

  const presetNames: string[] = []
  for (let col = block.fromColumn; col <= block.toColumn; col += 1) {
    presetNames.push(asText(cell(grid, nameRow, col)))
  }

  const slots: IdsCardPresetSlot[] = []
  const unmatchedNames: string[] = []
  for (let col = block.fromColumn; col <= block.toColumn; col += 1) {
    const presetIndex = col - block.fromColumn
    const presetName = presetNames[presetIndex] ?? ''
    if (!presetName) continue
    let slotIndex = 0
    for (let row = nameRow + 1; row < grid.length; row += 1) {
      const cardName = asText(cell(grid, row, col))
      if (!cardName) continue
      const saveIndex = resolveIdsCardSaveIndex(cardName)
      if (saveIndex === null) unmatchedNames.push(cardName)
      slots.push({ presetIndex, presetName, slotIndex, cardName, saveIndex })
      slotIndex += 1
    }
  }

  return { presetNames, slots, unmatchedNames: [...new Set(unmatchedNames)], warnings: [] }
}



/* ------------------------------------------------ the capture safety net */

export interface IdsCapturedRow {
  /** Row in the `_IDS` grid, so a captured value can be traced back. */
  rowIndex: number
  values: unknown[]
}

export interface IdsCapturedBlock {
  heading: string
  fromColumn: number
  toColumn: number
  rows: IdsCapturedRow[]
  filledCells: number
}

/**
 * Every block, captured verbatim, whether an adapter models it or not.
 *
 * The structured adapters above are the primary path: they turn a block into
 * the exact array a tracker reads. This is the guarantee underneath them --
 * that a value the adapters do NOT model still has somewhere to live, instead
 * of being dropped because the site has no store for it yet.
 *
 * It matters most for the blocks with no tracker at all. `Perks Preset` holds a
 * player's perk picks per preset and their banned perks; `Preset Preset` and
 * `Preset Usage` hold which preset each domain uses. None of those has a home
 * on the site today, and all of them are real choices somebody made.
 *
 * It also catches the parts of a block its adapter leaves behind: the Vault's
 * summed power bonuses, the Relics block's owned counts, the lifetime stats
 * beside the dissonance table. Those are reported by their own readers and not
 * written to a tracker, and they are here too, so the raw value survives either
 * way.
 *
 * Deliberately captured for EVERY block rather than only the unmodelled ones.
 * A list of "which blocks are unmodelled" is a list that goes stale the moment
 * a release adds one, and the failure would be silent -- the new block simply
 * would not appear anywhere. Capturing everything cannot go stale, and
 * `ids-import-domains.test.ts` holds it to the stronger claim: no non-empty
 * cell in the sheet is missing from the capture.
 */
export function readIdsCapturedBlocks(grid: Grid): IdsCapturedBlock[] {
  const captured: IdsCapturedBlock[] = []
  for (const block of readIdsBlocks(grid)) {
    const rows: IdsCapturedRow[] = []
    let filledCells = 0
    for (let row = 0; row < grid.length; row += 1) {
      const values: unknown[] = []
      let hasValue = false
      for (let col = block.fromColumn; col <= block.toColumn; col += 1) {
        const value = cell(grid, row, col)
        const empty = value === '' || value === null || value === undefined
        values.push(empty ? null : value)
        if (!empty) {
          hasValue = true
          filledCells += 1
        }
      }
      if (hasValue) rows.push({ rowIndex: row, values })
    }
    captured.push({
      heading: block.heading,
      fromColumn: block.fromColumn,
      toColumn: block.toColumn,
      rows,
      filledCells,
    })
  }
  return captured
}

/**
 * Every non-empty cell the block spans do NOT cover.
 *
 * A block runs from its heading to the column before the next one, so the spans
 * tile the sheet from the first heading rightwards -- but only from the FIRST
 * heading. Anything to the left of it, or past the last block's end, would be
 * captured by nothing. This reports those cells rather than assuming there are
 * none.
 */
export function findIdsUncapturedCells(grid: Grid): Array<{ row: number, column: number, value: unknown }> {
  const blocks = readIdsBlocks(grid)
  const covered = new Set<number>()
  for (const block of blocks) {
    for (let col = block.fromColumn; col <= block.toColumn; col += 1) covered.add(col)
  }
  const stray: Array<{ row: number, column: number, value: unknown }> = []
  for (let row = 0; row < grid.length; row += 1) {
    const width = grid[row]?.length ?? 0
    for (let col = 0; col < width; col += 1) {
      if (covered.has(col)) continue
      const value = cell(grid, row, col)
      if (value === '' || value === null || value === undefined) continue
      stray.push({ row, column: col, value })
    }
  }
  return stray
}


/**
 * The assist multiplier and substat caps, per module category.
 *
 * They sit two columns right of each category's own column group and two rows
 * apart, as rendered display strings whose leading token is the level. The
 * group columns are discovered, so this follows the region when a release
 * moves it -- reading them at a fixed column is what returned zero caps on
 * every older master.
 */
export function readIdsAssistCaps(grid: Grid): Record<string, { multiplier: number, substat: number }> {
  const categories: IdsModuleCategory[] = ['Cannon', 'Armor', 'Generator', 'Core']
  const groups = findIdsModuleGroupColumns(grid)
  const caps: Record<string, { multiplier: number, substat: number }> = {}

  for (const [index, category] of categories.entries()) {
    const base = groups[index]
    if (base === undefined) continue
    const levelAt = (label: string): number => {
      for (let row = 1; row < Math.min(grid.length, 12); row += 1) {
        if (asText(cell(grid, row, base)) !== label) continue
        for (let col = base + 1; col <= base + 4; col += 1) {
          const level = parseIdsDisplayLevel(cell(grid, row, col))
          if (level !== null) return level
        }
      }
      return 0
    }
    caps[category] = {
      multiplier: levelAt('Multiplier Cap'),
      substat: levelAt('Substat Cap'),
    }
  }
  return caps
}

/* ------------------------------------------- relics, and the vault totals */

export interface IdsBonusRow {
  /** The sub-heading the row sits under -- `Attack`, `Defense`, `Utility`, `Misc.` */
  section: string
  label: string
  value: number
}

export interface IdsRelicsExtract {
  /** `Event Relics`, `Guild Relics`, `Other Relics`, `Total Relics`. */
  counts: Record<string, number>
  bonuses: IdsBonusRow[]
  warnings: string[]
}

/**
 * A label/value block that is grouped by bare sub-headings.
 *
 * Both the Relics and Vault blocks lay their totals out the same way: a row
 * with a name and no value opens a section, and the rows under it are that
 * section's stats. Read generically so the two share one implementation and
 * neither drifts from the other.
 */
function readSectionedBonuses(
  grid: Grid,
  block: IdsBlock,
  stopAt?: RegExp,
): IdsBonusRow[] {
  const rows: IdsBonusRow[] = []
  let section = ''
  for (let row = 1; row < grid.length; row += 1) {
    const label = asText(cell(grid, row, block.fromColumn))
    if (!label) continue
    if (stopAt?.test(label)) break
    const value = asNumber(cell(grid, row, block.fromColumn + 1))
    if (value === null) {
      // A name with no number beside it is a heading, not a stat worth zero.
      section = label
      continue
    }
    rows.push({ section, label, value })
  }
  return rows
}

/**
 * The `Themes, Songs & Relics` block.
 *
 * This cannot rebuild `relicsUnlocked[]` -- the sheet never says WHICH relics a
 * player owns, only how many of each kind and what they add up to. So what it
 * does carry is surfaced in the shape it actually has, counts and totals, for a
 * tracker to store or adapt to, rather than being forced into an array it has
 * no data for.
 */
export function readIdsRelics(grid: Grid): IdsRelicsExtract {
  const block = findBlock(grid, 'Themes, Songs & Relics') ?? findBlock(grid, 'Relics')
  if (!block) {
    return { counts: {}, bonuses: [], warnings: ['No relics block on _IDS.'] }
  }
  const counts: Record<string, number> = {}
  for (let row = 1; row < grid.length; row += 1) {
    const label = asText(cell(grid, row, block.fromColumn))
    if (!/Relics$/.test(label)) continue
    const value = asNumber(cell(grid, row, block.fromColumn + 1))
    if (value !== null) counts[label] = value
  }
  /*
   * Older releases keep the theme-and-song coin bonus in its OWN `Themes &
   * Songs` block instead of as a `TS Coin Bonus` row inside this one. Same
   * quantity, different home, so it is picked up either way rather than being
   * present on six sheets and missing on three.
   */
  const bonuses = readSectionedBonuses(grid, block)
  const themesBlock = findBlock(grid, 'Themes & Songs')
  if (themesBlock) {
    for (let row = 1; row < grid.length; row += 1) {
      const value = asNumber(cell(grid, row, themesBlock.fromColumn))
      if (value === null) continue
      bonuses.push({ section: 'Theme & Song', label: 'TS Coin Bonus', value })
      break
    }
  }

  return { counts, bonuses, warnings: [] }
}

/**
 * The Vault's summed bonuses, which the Power tree cannot be reconstructed from.
 *
 * `Discount Enhancements 0.225` is nine separate nodes added together, so there
 * is no way back to any one node's tier. The totals are real numbers a player
 * owns, though, so they get a home of their own instead of being dropped for
 * not fitting `powerNodesLevel[]`.
 */
export function readIdsVaultBonuses(grid: Grid): IdsBonusRow[] {
  const block = findBlock(grid, 'Vault')
  if (!block) return []
  // Stop at `Unlocks`: everything below it is the boolean harmony section,
  // which `readIdsVaultUnlocks` already models properly.
  return readSectionedBonuses(grid, block, /^Unlocks$/)
}


/* ------------------------------------------------------------------ perks */

export interface IdsPerkPresetColumn {
  presetIndex: number
  presetName: string
  /** Perk names in the order the sheet lists them: the autopick priority. */
  order: string[]
  banned: string[]
  orderIndices: number[]
  bannedIndices: number[]
}

export interface IdsPerksExtract {
  presets: IdsPerkPresetColumn[]
  unmatchedNames: string[]
  warnings: string[]
}

/**
 * The sheet's perk name, to the catalog's.
 *
 * The two vocabularies describe the same 34 perks and share almost no strings.
 * The catalog embeds the magnitude -- `x1.20 Max Health`, `Interest x1.50`,
 * `Bounce Shot +2` -- where the sheet writes the bare effect. And the ten
 * trade-off perks are phrased completely differently on each side:
 * `x1.50 Tower Damage, but Bosses Have 8x Health` against `Damage / Boss
 * Health`. No amount of token-stripping bridges that, so the pairs are written
 * out.
 *
 * They are safe to write out because the correspondence is a COMPLETE
 * BIJECTION, established by listing both vocabularies in full rather than by
 * matching them one at a time: the catalog has exactly 34 active perks (15
 * standard, 9 ultimate weapon, 10 trade-off) and the sheet uses exactly 34
 * names once its preset headings and the `Banned` label are set aside. Every
 * one pairs, with nothing left over on either side, and
 * `ids-import-domains.test.ts` asserts that -- so a release that adds a perk
 * breaks the count and says so, rather than quietly dropping it.
 *
 * Keyed to catalog NAMES, not indices, so the join keeps working if the
 * catalog's numbering ever shifts.
 */
const IDS_PERK_NAME_TO_CATALOG: Readonly<Record<string, string>> = {
  // Standard pool.
  'Max Health': 'x1.20 Max Health',
  'Damage': 'x1.15 Damage',
  'Health Regen': 'x1.75 Health Regen',
  'All Coin Bonus': 'x1.15 All Coin Bonuses',
  'Bounce Shot': 'Bounce Shot +2',
  'Interest': 'Interest x1.50',
  'Land Mine Damage': 'Land Mine Damage x3.50',
  'Orbs': 'Orbs +1',
  'Free Upgrade Chance for all': 'Free Upgrade Chance for All +5.0%',
  'Defense %': 'Defense Percent +4.00',
  'Perk Wave Requirement': 'Perk Wave Requirement -20.00%',
  'Unlock a random Ultimate Weapon': 'Unlock a Random Ultimate Weapon',
  'Increase Max Game Speed': 'Increase Max Game Speed by +1.00',
  'Cash Bonus': 'x1.15 Cash Bonus',
  'Defense Absolute': 'x1.15 Defense Absolute',
  // Ultimate weapon pool.
  'More Smart Missiles': '4 More Smart Missiles',
  'Swamp Radius': 'Swamp Radius x1.5',
  'Wave on Death Wave (Effect Wave)': '+1 Wave on Death Wave',
  'Extra Set of Inner Mines': 'Extra Set of Inner Mines',
  'Golden Tower Bonus': 'Golden Tower Bonus x1.5',
  'Chain Lightning Damage': 'Chain Lightning Damage x2',
  'Chrono Field Duration': 'Chrono Field Duration +5s',
  'Black Hole Duration': 'Black Hole Duration +12.0s',
  'Spotlight Damage Bonus': 'Spotlight Damage Bonus x1.5',
  // Trade-off pool, where the two phrasings share nothing.
  'Damage / Boss Health': 'x1.50 Tower Damage, but Bosses Have 8x Health',
  'Coins / - Health': 'x1.80 Coins, but Tower Max Health -70%',
  '- Enemies Health / - Regen and Lifesteal':
    'Enemies Have -50% Health, but Tower Health Regen and Lifesteal -90%',
  '- Enemies Damage / - Damage': 'Enemies Damage -50%, but Tower Damage -50%',
  'Ranged Distance reduced / Ranged Damage':
    'Ranged Enemies Attack Distance Reduced, but Tower Ranged Enemies Damage x3',
  '- Enemies Speed / Enemies Damage': 'Enemies Speed -40%, but Enemies Damage x2.5',
  'Cash per Wave / No Cash per Kill': "x12.00 Cash Per Wave, but Enemy Kills Don't Give Cash",
  'Health Regen / - Health': 'Tower Health Regen x8.00, but Tower Max Health -60%',
  '- Boss Health / Boss Speed': 'Boss Health -70%, but Boss Speed +50%',
  'Lifesteal / - Knockback Force': 'Lifesteal x2.50, but Knockback Force -70%',
}

/** Catalog perk name to index, derived from the catalog rather than listed. */
let perkIndexByName: Map<string, number> | null = null
function perkIndexLookup(): Map<string, number> {
  if (perkIndexByName) return perkIndexByName
  const map = new Map<string, number>()
  for (const index of listActivePerkIndices()) {
    const name = findPerkNameByIndex(index)
    if (!name) continue
    const key = normalizeName(name)
    if (!map.has(key)) map.set(key, index)
  }
  perkIndexByName = map
  return map
}

export function resolveIdsPerkIndex(name: string): number | null {
  const lookup = perkIndexLookup()
  const direct = lookup.get(normalizeName(name))
  if (direct !== undefined) return direct
  const catalogName = aliasFor(IDS_PERK_NAME_TO_CATALOG, name.trim())
  if (!catalogName) return null
  return lookup.get(normalizeName(catalogName)) ?? null
}

/** The sheet-side names, so a test can hold every pair to the catalog. */
export function idsPerkNameAliases(): Readonly<Record<string, string>> {
  return IDS_PERK_NAME_TO_CATALOG
}

/**
 * The `Perks Preset` block: an ordered perk list and a banned list, per preset.
 *
 * This block was written off in an earlier pass as "no store on the site". That
 * was wrong, and wrong for a familiar reason -- the conclusion came from
 * scanning the import-composables directory, not from looking for a perk
 * schema. `sharedPerkPreferencesSchema` has existed the whole time, and
 * `readPerkPreferencesFromSaveRoot` reads `bannedPerksIndex` and
 * `autoPickOrder`, which is exactly what these two lists are.
 *
 * The block's own shape: preset names on one row, then the ordered perks, then
 * a `Banned` row and the banned perks under it. The order is the data -- it is
 * the autopick priority -- so it is preserved as listed.
 */
export function readIdsPerks(grid: Grid): IdsPerksExtract {
  const block = findBlock(grid, 'Perks Preset')
  if (!block) {
    return { presets: [], unmatchedNames: [], warnings: ['No "Perks Preset" block on _IDS.'] }
  }

  // The preset names are the first row under the heading with a name in the
  // block's first column; `Banned` later splits the two lists.
  let nameRow = -1
  for (let row = 1; row < Math.min(grid.length, 4); row += 1) {
    if (asText(cell(grid, row, block.fromColumn))) {
      nameRow = row
      break
    }
  }
  if (nameRow < 0) {
    return { presets: [], unmatchedNames: [], warnings: ['The "Perks Preset" block has no preset row.'] }
  }

  let bannedRow = -1
  for (let row = nameRow + 1; row < grid.length; row += 1) {
    if (asText(cell(grid, row, block.fromColumn)) === 'Banned') {
      bannedRow = row
      break
    }
  }

  const unmatchedNames: string[] = []
  const presets: IdsPerkPresetColumn[] = []
  for (let col = block.fromColumn; col <= block.toColumn; col += 1) {
    const presetName = asText(cell(grid, nameRow, col))
    if (!presetName) continue

    const collect = (from: number, to: number): string[] => {
      const names: string[] = []
      for (let row = from; row < to; row += 1) {
        const raw = cell(grid, row, col)
        /*
         * Perk names are strings. The row of counts above the list (`9` per
         * preset) would otherwise stringify into a perk called "9".
         */
        if (typeof raw !== 'string') continue
        const name = raw.trim()
        if (!name) continue
        if (name === 'Banned') continue
        if (resolveIdsPerkIndex(name) === null) {
          unmatchedNames.push(name)
          continue
        }
        names.push(name)
      }
      return names
    }

    const orderEnd = bannedRow >= 0 ? bannedRow : grid.length
    const order = collect(nameRow + 1, orderEnd)
    const banned = bannedRow >= 0 ? collect(bannedRow + 1, grid.length) : []

    presets.push({
      presetIndex: col - block.fromColumn,
      presetName,
      order,
      banned,
      orderIndices: order.map(name => resolveIdsPerkIndex(name) as number),
      bannedIndices: banned.map(name => resolveIdsPerkIndex(name) as number),
    })
  }

  return { presets, unmatchedNames: [...new Set(unmatchedNames)], warnings: [] }
}




