/**
 * The IDS `Modules` region, turned into save-shaped module records.
 *
 * This is the richest block on the sheet and the only one that carries whole
 * ITEMS rather than levels: per module, its rarity, its level and every substat
 * with that substat's own rarity, in slot order. The tracker stores all of it,
 * so all of it is mapped.
 *
 * ## The layout, which is not what it first looks like
 *
 * The region is four column groups five columns wide, and a group is a module
 * CATEGORY -- Cannon, Armor, Generator, Core, matching `moduleTypeEnum` 0..3 --
 * not a preset. The tell is the substats: group one offers Attack Speed and
 * Super Crit Multi, group two Land Mine Chance and Wall Rebuild. Reading them
 * as presets would put every Armor module's data on a Cannon module.
 *
 * Inside a group, each module is a 13-row detail block:
 *
 *     +0   module name
 *     +1   "Rarity" | "Level" | "Stat"
 *     +2   Ancestral 5* | 216 | 23.128
 *     +3   (blank)
 *     +4.. eight substat rows: label | rarity | display | value
 *
 * Group columns are DISCOVERED from those `Rarity | Level | Stat` headers
 * rather than fixed: v5.08 puts the block one column left of v5.09, and the
 * Bots and Guardians blocks both moved between the same releases.
 *
 * ## What is equipped
 *
 * There are EIGHT equipped slots, not one: a primary and an assist per
 * category. `moduleEquipped` is an array of four indexed by category in the
 * order Cannon, Armor, Generator, Core, and `assistModuleSlots` is four slot
 * objects carrying the same order in their `type`.
 *
 * That is worth stating because the game's own save-format note describes
 * `moduleEquipped` as "a single ModuleItem ... equipped on the tower", which
 * reads like one primary for the whole account. The real save disagrees: it
 * holds four, one per category, and `readModulesFromSaveRoot` iterates them
 * against `MODULE_SAVE_PRIMARY_CATEGORY_ORDER`. Taking the prose at its word is
 * what made an earlier pass leave `moduleEquipped` null and call the sheet
 * ambiguous -- the sheet lists a Primary Slot per category per preset, which is
 * exactly the shape the save wants, not four candidates for one slot.
 *
 * Every detail block still goes to `inventory[]` as well, which is where a
 * module with full metadata belongs.
 */
/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    IDS_MODULE_SUBSTAT_SLOTS, IdsModuleCategory, IdsModuleSubstat, IdsModuleRow, IdsModulePresetSlot, IdsModulesExtract, resolveIdsModuleRarityEnum, resolveIdsModuleIdentity (+3 more)
 * depends    src/data/module-info-catalog, src/data/module-levels, src/save/ids-grid, src/save/module-effects-registry
 * used by    src/mechanics/calculators/specs-generated, src/save/ids-import-blocks, src/save/ids-import-collections, src/save/ids-import-domains, src/save/ids-import-progression, src/save/index
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
import {
  MODULE_RARITIES,
  type ModuleRarity,
} from '../data/module-levels'
import { aliasFor, asNumber, asText, cell, type Grid, normalizeName } from './ids-grid'
import { findModuleInfoIdentity, listModuleInfoCatalogRows } from '../data/module-info-catalog'
import { MODULE_SAVE_EFFECT_ID_LABELS } from './module-effects-registry'


/** Rows from a detail block's name row to the first substat row. */
const SUBSTAT_ROW_OFFSET = 4

/** Slots the game stores per module, even when the player has filled fewer. */
export const IDS_MODULE_SUBSTAT_SLOTS = 8

/**
 * The sheet's own placeholder rows, which are not anybody's modules.
 *
 * `Any Other` and `Any Other 2` are generic `Epic 60` stand-ins the sheet uses
 * for "some module of this category". Importing them would invent modules the
 * player does not own.
 */
const IDS_MODULE_PLACEHOLDER_NAMES = /^any other(\s*\d+)?$/i

export type IdsModuleCategory = 'Cannon' | 'Armor' | 'Generator' | 'Core'

export interface IdsModuleSubstat {
  slotIndex: number
  label: string
  rarity: string
  /** The sheet's rendered value, e.g. `"+15x"`, kept for reporting. */
  display: string
  value: number | null
  /** Resolved `effects[]` entry, or null when the pair does not resolve. */
  effectId: number | null
}

export interface IdsModuleRow {
  name: string
  category: IdsModuleCategory | null
  infoIndex: number | null
  rarityLabel: string
  /** 1..15, matching the game's `currentRarity`. */
  rarityEnum: number | null
  level: number | null
  substats: IdsModuleSubstat[]
  /** `effects[]` as the save stores it: eight entries, 0 where unfilled. */
  effects: number[]
}

export interface IdsModulePresetSlot {
  preset: string
  category: IdsModuleCategory | null
  role: 'primary' | 'assist'
  moduleName: string
}

export interface IdsModulesExtract {
  modules: IdsModuleRow[]
  /** Listed by the sheet with no rarity, i.e. the player does not own one. */
  notOwned: string[]
  presetSlots: IdsModulePresetSlot[]
  /** Module names the catalog does not know, placeholders excluded. */
  unmatchedNames: string[]
  /** Substat (label, rarity) pairs that resolved to no effect id. */
  unresolvedSubstats: string[]
  warnings: string[]
}


/**
 * Module rarity as the sheet spells it, to the game's 1..15 enum.
 *
 * The two vocabularies differ in punctuation only -- the sheet writes
 * `Ancestral 5*` and `Rare+` where `MODULE_RARITIES` has `Ancestral 5` and
 * `Rare +` -- so both sides are stripped to letters and digits rather than
 * aliased entry by entry.
 */
function rarityKey(value: string): string {
  /*
   * The `+` is SIGNIFICANT and must survive: `Rare` and `Rare +` are two
   * different rarities, two enum values apart. Stripping all punctuation
   * collapsed them onto one key, and the first one written won -- so every
   * `Rare+` module imported as plain `Rare`. Only the sheet's `*` and the
   * spacing are noise.
   */
  return value.toLowerCase().replace(/\*/g, '').replace(/[^a-z0-9+]+/g, '')
}

let rarityEnumByKey: Map<string, number> | null = null
function rarityLookup(): Map<string, number> {
  if (rarityEnumByKey) return rarityEnumByKey
  const map = new Map<string, number>()
  MODULE_RARITIES.forEach((rarity: ModuleRarity, index: number) => {
    map.set(rarityKey(rarity), index + 1)
  })
  rarityEnumByKey = map
  return map
}

export function resolveIdsModuleRarityEnum(label: string): number | null {
  return rarityLookup().get(rarityKey(label)) ?? null
}

/** Module display name to its catalog identity. */
let moduleIdentityByName: Map<string, { infoIndex: number, category: IdsModuleCategory }> | null = null
function moduleIdentityLookup(): NonNullable<typeof moduleIdentityByName> {
  if (moduleIdentityByName) return moduleIdentityByName
  const map = new Map<string, { infoIndex: number, category: IdsModuleCategory }>()
  for (const row of listModuleInfoCatalogRows()) {
    const infoIndex = Number((row as { infoIndex?: unknown }).infoIndex)
    if (!Number.isFinite(infoIndex)) continue
    // Through the identity resolver, so the catalog's own overrides apply and
    // the name this matches is the name the save reader would report back.
    const identity = findModuleInfoIdentity(infoIndex)
    if (!identity?.name || !identity.category) continue
    const key = normalizeName(identity.name)
    if (!map.has(key)) {
      map.set(key, { infoIndex, category: identity.category as IdsModuleCategory })
    }
  }
  moduleIdentityByName = map
  return map
}

/**
 * `Spare Dimension Core` is a SECOND Dimension Core, not a module of its own.
 *
 * The sheet writes a spare copy as "Spare " plus the module's name, and puts it
 * in the row other categories fill with `Any Other`. It is not in the game's
 * module catalog, and it should not be: a player owning two Dimension Cores is
 * two instances of infoIndex 38, which is exactly what `inventory[]` holds.
 * Sheet-18 proves they are distinct instances -- its Dimension Core is
 * Ancestral 4* and its spare is Ancestral 3*, with their own substats each.
 */
const IDS_SPARE_MODULE_PREFIX = /^spare\s+/i

export function resolveIdsModuleIdentity(
  name: string,
): { infoIndex: number, category: IdsModuleCategory } | null {
  const lookup = moduleIdentityLookup()
  const direct = lookup.get(normalizeName(name))
  if (direct) return direct
  const bare = name.trim().replace(IDS_SPARE_MODULE_PREFIX, '')
  if (bare === name.trim()) return null
  return lookup.get(normalizeName(bare)) ?? null
}

/**
 * A substat's effect id, from its label and its own rarity.
 *
 * `effects[]` holds one effectID per slot, and an effectID encodes BOTH which
 * substat it is and at what rarity. The game's format documents this as
 * `effectID = cluster.effectIDFirst + rarityPosition`, with `rarityPosition`
 * counted from the lowest rarity that substat can roll.
 *
 * Derived here rather than transcribed: `MODULE_SAVE_EFFECT_ID_LABELS` already
 * maps every effect id to its label per category, so a label's ids form one
 * contiguous ascending run, one entry per rarity it can roll. The run's LENGTH
 * gives the starting rarity -- a run of six starts at Common, of five at Rare,
 * and so on down the shared ladder -- so the position is just an index into the
 * run. A transcribed table of 331 ids would drift from the registry the first
 * time a substat is added; this cannot.
 */
const SUBSTAT_RARITY_LADDER = ['Common', 'Rare', 'Epic', 'Legendary', 'Mythic', 'Ancestral'] as const

let effectIdRuns: Map<string, number[]> | null = null
function effectIdRunLookup(): Map<string, number[]> {
  if (effectIdRuns) return effectIdRuns
  const map = new Map<string, number[]>()
  const table = MODULE_SAVE_EFFECT_ID_LABELS as Record<string, Record<string, string>>
  for (const [category, labels] of Object.entries(table)) {
    for (const [effectId, label] of Object.entries(labels)) {
      const key = `${category}::${normalizeName(label)}`
      const run = map.get(key) ?? []
      run.push(Number(effectId))
      map.set(key, run)
    }
  }
  for (const run of map.values()) run.sort((a, b) => a - b)
  effectIdRuns = map
  return map
}

/**
 * Where the sheet spells a substat differently from the effect registry.
 *
 * Both were settled by ELIMINATION, category by category, not by nearest
 * string. Across the nine sheets each category has exactly one registry label
 * that no sheet ever uses and one sheet label the registry does not have:
 *
 *   Cannon   free: "Rend Armor Mult"   sheet-only: "Rend Armor Multi"
 *   Armor    free: "Defense"           sheet-only: "Defense %"
 *
 * The Cannon pair is why this matters. The registry ALSO has "Max Rend Armor
 * Multi", which is the closer string to "Rend Armor Multi" -- and the sheets
 * already use it under its own name, so it is taken and the only free slot is
 * "Rend Armor Mult". Nearest-string would have put every Rend Armor Mult roll
 * onto the Max Rend cap.
 *
 * Case and spacing need no entry here: the join normalises both, which is why
 * the sheet's "MultiShot Chance" resolves against "Multishot Chance" already.
 */
const IDS_SUBSTAT_LABEL_ALIASES: Readonly<Record<string, Readonly<Record<string, string>>>> = {
  Cannon: { 'Rend Armor Multi': 'Rend Armor Mult' },
  Armor: { 'Defense %': 'Defense' },
}

export function resolveIdsSubstatEffectId(
  category: IdsModuleCategory,
  label: string,
  rarity: string,
): number | null {
  const runs = effectIdRunLookup()
  // Same prototype trap as every other alias table here: a substat labelled
  // `toString` would resolve to a native function and crash `normalizeName`.
  const table = IDS_SUBSTAT_LABEL_ALIASES[category]
  const alias = table ? aliasFor(table, label.trim()) : null
  const run = runs.get(`${category}::${normalizeName(label)}`)
    ?? (alias ? runs.get(`${category}::${normalizeName(alias)}`) : undefined)
  if (!run || run.length === 0) return null
  const ladderIndex = SUBSTAT_RARITY_LADDER.findIndex(
    entry => rarityKey(entry) === rarityKey(rarity),
  )
  if (ladderIndex < 0) return null
  // A run of n rarities occupies the TOP n rungs of the shared ladder.
  const position = ladderIndex - (SUBSTAT_RARITY_LADDER.length - run.length)
  if (position < 0 || position >= run.length) return null
  return run[position]
}

/**
 * The category column groups, discovered from their own `Rarity | Level | Stat`
 * headers rather than assumed.
 *
 * Returned left to right, which is the game's category order.
 */
export function findIdsModuleGroupColumns(grid: Grid): number[] {
  const columns = new Set<number>()
  for (let row = 0; row < grid.length; row += 1) {
    const width = grid[row]?.length ?? 0
    for (let col = 0; col + 2 < width; col += 1) {
      if (asText(cell(grid, row, col)) !== 'Rarity') continue
      if (asText(cell(grid, row, col + 1)) !== 'Level') continue
      if (asText(cell(grid, row, col + 2)) !== 'Stat') continue
      columns.add(col)
    }
  }
  return [...columns].sort((a, b) => a - b)
}

/**
 * The `Primary Slot` / `Assist Slot` rows, per preset, per category group.
 *
 * Two things here were wrong on first writing and are worth naming, because
 * both failed silently on a subset of sheets rather than throwing:
 *
 *  - It looked the region up by a block called `Modules`. Four of the nine
 *    sheets call it **`Modules Presets`**, and those four returned no slots at
 *    all -- which read as "this player equips nothing", not as a parsing miss.
 *    The group columns are already known by the caller, so no lookup is needed.
 *  - It required the literal labels. The first three presets carry
 *    `Primary Slot` / `Assist Slot`, but the later ones drop the label and
 *    leave just the module name, so those presets were skipped entirely.
 *    Within a preset the rows are primary then assist in order, which is what
 *    the unlabelled ones fall back to.
 */
function readPresetSlots(grid: Grid, groupColumns: number[]): IdsModulePresetSlot[] {
  const slots: IdsModulePresetSlot[] = []
  /* Header rows above the presets that must not be read as one. */
  const HEADER_LABELS = /^(Assist Slot|Primary Slot|Rarity Cap|Multiplier Cap|Substat Cap)$/

  for (const [groupIndex, column] of groupColumns.entries()) {
    const category = categoryForGroup(groupIndex)
    let preset = ''
    let roleOrdinal = 0

    for (let row = 1; row < grid.length; row += 1) {
      // The detail blocks start here; everything below is module metadata.
      if (asText(cell(grid, row + 1, column)) === 'Rarity') break

      const label = asText(cell(grid, row, column))
      const rawValue = cell(grid, row, column + 1)
      const value = asText(rawValue)

      // A lone name opens a preset section.
      if (label && !value && !HEADER_LABELS.test(label)) {
        preset = label
        roleOrdinal = 0
        continue
      }
      if (!preset || !value) continue
      // `Assist Slot | true | 210` in the header is a flag, not a module.
      if (typeof rawValue === 'boolean') continue
      if (IDS_MODULE_PLACEHOLDER_NAMES.test(value)) {
        roleOrdinal += 1
        continue
      }

      let role: 'primary' | 'assist' | null = null
      if (label === 'Primary Slot') role = 'primary'
      else if (label === 'Assist Slot') role = 'assist'
      else if (!label) role = roleOrdinal === 0 ? 'primary' : 'assist'
      if (!role) continue

      slots.push({ preset, category, role, moduleName: value })
      roleOrdinal += 1
    }
  }
  return slots
}

function categoryForGroup(groupIndex: number): IdsModuleCategory | null {
  const order: IdsModuleCategory[] = ['Cannon', 'Armor', 'Generator', 'Core']
  return order[groupIndex] ?? null
}

/** Read every module detail block in the `Modules` region. */
export function readIdsModules(grid: Grid): IdsModulesExtract {
  const groupColumns = findIdsModuleGroupColumns(grid)
  if (groupColumns.length === 0) {
    return {
      modules: [],
      presetSlots: [],
      notOwned: [],
      unmatchedNames: [],
      unresolvedSubstats: [],
      warnings: ['No module detail blocks found on _IDS.'],
    }
  }

  const modules: IdsModuleRow[] = []
  const notOwned: string[] = []
  const unmatchedNames: string[] = []
  const unresolvedSubstats: string[] = []
  const warnings: string[] = []

  for (const [groupIndex, column] of groupColumns.entries()) {
    const groupCategory = categoryForGroup(groupIndex)
    for (let row = 1; row < grid.length; row += 1) {
      if (asText(cell(grid, row + 1, column)) !== 'Rarity') continue
      const name = asText(cell(grid, row, column))
      if (!name) continue
      if (IDS_MODULE_PLACEHOLDER_NAMES.test(name)) continue

      const identity = resolveIdsModuleIdentity(name)
      if (!identity) unmatchedNames.push(name)
      /*
       * The name is authoritative for the category and the column group only
       * corroborates it. If they disagree, the region's shape has moved and a
       * module's substats are about to be read from another category's list.
       */
      if (identity && groupCategory && identity.category !== groupCategory) {
        warnings.push(
          `"${name}" is a ${identity.category} module but sits in the ${groupCategory} column group.`,
        )
      }

      const rarityLabel = asText(cell(grid, row + 2, column))
      /*
       * A tracked module the player does not own is still listed, with its
       * rarity written as `None`. Importing it would invent a module; dropping
       * it silently would hide that the sheet mentioned it. So it is skipped
       * and named.
       */
      if (!rarityLabel || /^none$/i.test(rarityLabel)) {
        notOwned.push(name)
        continue
      }
      const level = asNumber(cell(grid, row + 2, column + 1))
      const category = identity?.category ?? groupCategory

      const substats: IdsModuleSubstat[] = []
      const effects = new Array<number>(IDS_MODULE_SUBSTAT_SLOTS).fill(0)
      for (let slotIndex = 0; slotIndex < IDS_MODULE_SUBSTAT_SLOTS; slotIndex += 1) {
        const substatRow = row + SUBSTAT_ROW_OFFSET + slotIndex
        const label = asText(cell(grid, substatRow, column))
        if (!label) continue
        const substatRarity = asText(cell(grid, substatRow, column + 1))
        const effectId = category
          ? resolveIdsSubstatEffectId(category, label, substatRarity)
          : null
        if (effectId === null) unresolvedSubstats.push(`${category ?? '?'} :: ${label} :: ${substatRarity}`)
        else effects[slotIndex] = effectId
        substats.push({
          slotIndex,
          label,
          rarity: substatRarity,
          display: asText(cell(grid, substatRow, column + 2)),
          value: asNumber(cell(grid, substatRow, column + 3)),
          effectId,
        })
      }

      modules.push({
        name,
        category,
        infoIndex: identity?.infoIndex ?? null,
        rarityLabel,
        rarityEnum: resolveIdsModuleRarityEnum(rarityLabel),
        level,
        substats,
        effects,
      })
    }
  }

  return {
    modules,
    notOwned: [...new Set(notOwned)],
    presetSlots: readPresetSlots(grid, groupColumns),
    unmatchedNames: [...new Set(unmatchedNames)],
    unresolvedSubstats: [...new Set(unresolvedSubstats)],
    warnings,
  }
}

