/**
 * Grid and block primitives shared by every IDS domain reader.
 *
 * Split out of `ids-import-domains.ts` when it passed the 1,200-line limit. These locate a
 * block by heading, find the column a stat lives in, and read a rendered upgrade cell — the
 * parts every domain needs and none of them owns.
 *
 * Not re-exported from `save/index.ts`: they describe the layout of one spreadsheet, which is
 * not something a consumer of this package should be able to depend on.
 */
/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    findBlock, IdsDomainExtract, findPresetLevelColumns, readPresetNames, findStatColumnByContent, findStatBlock, IDS_DISPLAY_CELL, findAttributeColumn (+2 more)
 * depends    src/data/assets, src/data/player-stats, src/data/workshop-enhancement-tracker-definitions, src/data/workshop-tracker-definitions, src/save/cards, src/save/catalogs/guardians (+6 more)
 * used by    src/mechanics/calculators/specs-generated, src/save/ids-import-collections, src/save/ids-import-domains, src/save/ids-import-progression
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */

/**
 * The IDS blocks beyond Labs, turned into save-shaped fields.
 *
 * Same contract as `ids-import.ts`: read the player's IDS Master, emit a
 * `parsedRoot`-shaped object, and let the existing save readers, import
 * composables and `finishTrackerImportPersistence` do their own jobs unchanged.
 * Nothing here writes anything.
 *
 * ## Not every block is importable, and saying so is part of the job
 *
 * The IDS is the EP sheet's input layer, not a copy of the save. Some blocks
 * hold what a tracker needs (Cards levels, Workshop levels); others hold EP's
 * DERIVED aggregates -- the Vault block carries "Total Bonuses" per stat rather
 * than per-node levels, and the Relics block carries owned COUNTS and summed
 * bonuses rather than which relics a player owns. Neither can reconstruct the
 * array its tracker stores, so neither is mapped. `idsDomainCoverage()` reports
 * that rather than leaving it to be discovered as an empty tracker.
 */
import { aliasFor, asNumber, asText, cell, type Grid, normalizeName } from './ids-grid'
import { findPerkNameByIndex, listActivePerkIndices } from './catalogs/perks'
import { GUARDIANS_ASSET_TABLE } from '../data/assets'
import { CARD_IMPORT_CATALOG } from '../data/player-stats'
import { getWorkshopEnhancementDefinitions } from '../data/workshop-enhancement-tracker-definitions'
import { getWorkshopStatDefinitions } from '../data/workshop-tracker-definitions'
import { findCardCatalogFromSaveIndex } from './cards'
import { listGuardianChipSlotCatalogRows } from './catalogs/guardians'
import { HARMONY_VAULT_TRACKER_SLOT_BINDINGS } from './catalogs/vault'
import { listUltimateWeaponCatalogRows } from './catalogs/ultimate-weapons'
import {
  asLevel,
  type IdsBlock,
  readIdsBlocks,
} from './ids-import'
import {
  findIdsModuleGroupColumns,
  type IdsModuleCategory,
} from './ids-import-modules'

export function findBlock(grid: Grid, heading: string): IdsBlock | null {
  return readIdsBlocks(grid).find(block => block.heading === heading) ?? null
}

/** Names are compared case- and spacing-insensitively, as the labs join does. */

export interface IdsDomainExtract<Row> {
  rows: Row[]
  unmatchedNames: string[]
  missingFromSheet: string[]
  warnings: string[]
}


/**
 * The columns a per-preset block keeps its levels in, found from its header.
 *
 * The `WS` block labels them `¢ Level`, one per preset, and puts a `$ Level`
 * beside each. Those are NOT the same number -- they differ on five of the nine
 * captured sheets, and on three others the `$` column is empty entirely -- so
 * the pair cannot be treated as one value or read by a fixed stride. Only the
 * `¢ Level` columns are the workshop levels this tracker stores; the `$ Level`
 * column is a different quantity and is left to the capture net rather than
 * guessed at.
 *
 * `WS+` marks its preset columns `WS+` in the same header row.
 */
export function findPresetLevelColumns(grid: Grid, block: IdsBlock, marker: string): number[] {
  for (let row = 0; row < Math.min(grid.length, 5); row += 1) {
    const columns: number[] = []
    for (let col = block.fromColumn; col <= block.toColumn; col += 1) {
      if (asText(cell(grid, row, col)) === marker) columns.push(col)
    }
    if (columns.length > 1) return columns
  }
  return []
}

/**
 * The preset NAMES above a block's level columns.
 *
 * The names sit one row above the `¢ Level` / `WS+` markers, aligned to the
 * same columns, so they are read from those column positions rather than by
 * taking every string on the row -- the row also carries the block's own
 * headings (`U`, `Workshop Upgrade`) to the left of the first preset.
 */
export function readPresetNames(grid: Grid, block: IdsBlock, levelColumns: number[]): string[] {
  if (levelColumns.length === 0) return []
  for (let row = 0; row < Math.min(grid.length, 5); row += 1) {
    const names = levelColumns.map(col => asText(cell(grid, row, col)))
    if (names.filter(Boolean).length >= 2 && !names.includes('¢ Level') && !names.includes('WS+')) {
      return names
    }
  }
  return []
}

/**
 * Find a stat block by its CONTENT, for a grid with no headings.
 *
 * The heading is the better signal and is tried first. But a slice of the sheet
 * -- a fixture, or a range copied without the top row -- still has the stat
 * names running down a column, and refusing to read that turns a perfectly
 * recoverable shape into no data at all.
 *
 * The winning column is the one carrying the most names the catalog knows, so a
 * single coincidental match cannot claim it.
 */
export function findStatColumnByContent(grid: Grid, knows: (name: string) => boolean): number | null {
  const width = grid.reduce((widest, row) => Math.max(widest, row?.length ?? 0), 0)
  let bestColumn: number | null = null
  let bestHits = 1
  for (let col = 0; col < width; col += 1) {
    let hits = 0
    for (let row = 0; row < grid.length; row += 1) {
      const name = asText(cell(grid, row, col))
      if (name && knows(name)) hits += 1
    }
    if (hits > bestHits) {
      bestHits = hits
      bestColumn = col
    }
  }
  return bestColumn
}

/** A stat block located by heading, or by content when the sheet has none. */
export function findStatBlock(
  grid: Grid,
  heading: string,
  knows: (name: string) => boolean,
  nameOffset: number,
): { nameColumn: number, blockEnd: number } | null {
  const block = findBlock(grid, heading)
  if (block) return { nameColumn: block.fromColumn + nameOffset, blockEnd: block.toColumn }
  const column = findStatColumnByContent(grid, knows)
  if (column === null) return null
  const width = grid.reduce((widest, row) => Math.max(widest, row?.length ?? 0), 0)
  return { nameColumn: column, blockEnd: width - 1 }
}

/** A rendered upgrade cell: `"12 | 84s | Cost ..."`, or `"Lo | Locked"`. */
export const IDS_DISPLAY_CELL = /^\s*(?:\d+|Lo)\s*\|/

/**
 * Where a block keeps its `Attribute` column, read off the sheet rather than fixed.
 *
 * The per-preset blocks moved between releases. v5.09.03 lays a bot row out as
 * `[name, attribute, display, flag, ...]`; v5.08.05 inserts two columns and
 * makes it `[name, "", attribute, rawValue, display, flag, ...]`. A fixed offset
 * reads the older sheet's raw VALUE where the level should be, and finds one
 * upgrade row per bot instead of four.
 *
 * So the column is discovered from the sheet's own header label, the same way
 * the parity capture discovers its layout from the formula a cell actually
 * passes rather than from a version string.
 */
export function findAttributeColumn(grid: Grid, block: IdsBlock): number | null {
  for (let row = 0; row < Math.min(grid.length, 4); row += 1) {
    for (let col = block.fromColumn; col <= block.toColumn; col += 1) {
      if (asText(cell(grid, row, col)) === 'Attribute') return col
    }
  }
  /*
   * Some copies have no header row at all -- sheet-13's Guardians block starts
   * straight in on the data -- so the label cannot always be found. Fall back
   * to the shape of a data row: locate the first rendered display cell and walk
   * LEFT to the nearest text cell. That skips the raw numeric column older
   * releases put in between, and lands on the attribute name in every layout
   * seen across the nine captured sheets.
   */
  for (let row = 0; row < grid.length; row += 1) {
    let displayCol = -1
    for (let col = block.fromColumn; col <= block.toColumn; col += 1) {
      const value = cell(grid, row, col)
      if (typeof value === 'string' && IDS_DISPLAY_CELL.test(value)) {
        displayCol = col
        break
      }
    }
    if (displayCol < 0) continue
    for (let col = displayCol - 1; col > block.fromColumn; col -= 1) {
      const value = cell(grid, row, col)
      if (typeof value === 'string' && value.trim() !== '') return col
    }
  }
  return null
}

/**
 * The first rendered display cell to the right of the attribute name.
 *
 * Content-based on purpose. The two blocks that carry presets disagree about
 * what sits directly under the preset heading -- Bots puts the display there
 * and the toggle after it, Guardians puts the toggle there and the display
 * after it -- and older releases add a raw numeric column in between. Scanning
 * for the first cell that is actually a rendered upgrade handles all of that
 * without a table of per-version offsets.
 */
/** Column index of the first rendered upgrade cell, or -1. */
export function findFirstDisplayColumn(grid: Grid, row: number, fromColumn: number, toColumn: number): number {
  for (let col = fromColumn; col <= toColumn; col += 1) {
    const value = cell(grid, row, col)
    if (typeof value === 'string' && IDS_DISPLAY_CELL.test(value)) return col
  }
  return -1
}

export function firstDisplayCell(grid: Grid, row: number, fromColumn: number, toColumn: number): unknown {
  for (let col = fromColumn; col <= toColumn; col += 1) {
    const value = cell(grid, row, col)
    if (typeof value === 'string' && IDS_DISPLAY_CELL.test(value)) return value
  }
  return null
}
