/**
 * Reading a player's save file.
 *
 * Two steps: decode `playerInfo.dat` into a save root, then pull typed data out
 * of that root. Decoding needs gzip and lives in `thetowersdk/node`; everything
 * here is pure and runs in a browser too.
 *
 * Every `extract*FromSaveRoot` returns `null` when the save has no data for that
 * feature, so older saves degrade to "this section is absent" instead of failing.
 *
 * @example
 * import { decodePlayerInfoSaveBytes } from 'thetowersdk/node'
 * import { readLabsFromSaveRoot } from 'thetowersdk/save'
 *
 * const { parsedRoot } = decodePlayerInfoSaveBytes(bytes)
 * const labs = readLabsFromSaveRoot(parsedRoot)
 */
/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    —
 * depends    src/save/access/path, src/save/access/values, src/save/battle, src/save/bots/read, src/save/cards/read, src/save/catalogs (+17 more)
 * used by    —
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */

// Reading raw values out of a save root, for fields the SDK does not model yet
export * from './access/values'
export * from './access/path'

// Per-feature extractors
export * from './labs'
export * from './workshop/read'
export * from './modules'
export * from './cards/read'
export * from './perks/read'
export * from './relics/read'
export * from './guardians/read'
export * from './bots/read'
export * from './ultimate-weapons/read'
export * from './vault/read'
// A save straight to Effective Paths planner inputs — levels, config, and an
// explicit list of what the save could not answer.
export * from './effective-paths'
export * from './themes/read'
export * from './dissonance/read'
export * from './ids'
export * from './runs'
export * from './lifetime/read'
export * from './killed-by/read'

// Run history and battle reports
export * from './battle'

// Module effect decoding

// What is in this save? Inspect before importing anything.
export * from './import'

// Mapping save indices onto the named entities in `thetowersdk/data`
export * from './catalogs'
export * from './shared-tool-inputs'
