/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    ModuleSaveSlotCategory, MODULE_SAVE_EFFECT_ID_LABELS, findModuleSaveEffectLabel, getModuleSaveEffectTier, findModuleSaveEffectCategory, isKnownModuleSaveEffectId
 * depends    src/data/assets, src/data/module-effect-resolver, src/data/module-enums, src/data/module-substats
 * used by    src/mechanics/calculators/specs-generated, src/save/ids-import-modules, src/save/index, src/save/module-effects-decode, src/save/module-effects-display, src/save/module-effects-ids
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
import {
  isModuleEffectsTablePopulated,
  MODULE_EFFECTS_TABLE,
} from '../data/assets'
import { MODULE_TYPE_ROWS } from '../data/module-enums'
import { findModuleEffect } from '../data/module-effect-resolver'
import type { ModuleSubstatCanonicalRarity } from '../data/module-substats'

export type ModuleSaveSlotCategory = 'Cannon' | 'Armor' | 'Generator' | 'Core'

const TYPE_TO_CATEGORY: Record<number, ModuleSaveSlotCategory> = {
  0: 'Cannon',
  1: 'Armor',
  2: 'Generator',
  3: 'Core',
}

function categoryForModuleType(moduleType: number): ModuleSaveSlotCategory | null {
  return TYPE_TO_CATEGORY[moduleType] ?? MODULE_TYPE_ROWS.find(entry => entry.value === moduleType)?.name ?? null
}

function buildCategoryLabelMaps(): Record<ModuleSaveSlotCategory, Record<number, string>> {
  const result: Record<ModuleSaveSlotCategory, Record<number, string>> = {
    Cannon: {},
    Armor: {},
    Generator: {},
    Core: {},
  }

  if (!isModuleEffectsTablePopulated()) return result

  for (const [effectId, row] of Object.entries(MODULE_EFFECTS_TABLE)) {
    if (!row) continue
    const resolved = findModuleEffect(Number(effectId))
    if (!resolved?.label) continue
    const category = categoryForModuleType(row.type)
    if (!category) continue
    result[category][Number(effectId)] = resolved.label
  }

  return result
}

export const MODULE_SAVE_EFFECT_ID_LABELS = buildCategoryLabelMaps()

export function findModuleSaveEffectLabel(
  effectId: number,
  category: ModuleSaveSlotCategory,
): string | null {
  void category
  if (!effectId) return null
  return findModuleEffect(effectId)?.label ?? null
}

export function getModuleSaveEffectTier(effectId: number): ModuleSubstatCanonicalRarity | string {
  const resolved = findModuleEffect(effectId)
  if (!resolved) return 'Unknown'
  return resolved.rarityName
}

export function findModuleSaveEffectCategory(effectId: number): ModuleSaveSlotCategory | null {
  const row = MODULE_EFFECTS_TABLE[String(effectId)]
  if (!row) return null
  return categoryForModuleType(row.type)
}

export function isKnownModuleSaveEffectId(effectId: number, category: ModuleSaveSlotCategory): boolean {
  if (!effectId) return false
  return findModuleSaveEffectCategory(effectId) === category
    && Boolean(findModuleSaveEffectLabel(effectId, category))
}
