/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    formatModuleSaveEffectDisplayValue
 * depends    src/data/module-substats, src/save/module-effects-registry
 * used by    src/mechanics/calculators/specs-generated, src/save/index, src/save/module-effects-decode
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
import {
  MODULE_SUBSTAT_BASE_RARITIES,
  MODULE_SUBSTAT_CANONICAL_DATA,
  type ModuleSubstatCanonicalRarity,
} from '../data/module-substats'
import type { ModuleSaveSlotCategory } from './module-effects-registry'

type CanonicalCategory = keyof typeof MODULE_SUBSTAT_CANONICAL_DATA

const CATEGORY_TO_CANONICAL: Record<ModuleSaveSlotCategory, CanonicalCategory> = {
  Cannon: 'Cannon',
  Armor: 'Defense',
  Generator: 'Generator',
  Core: 'Core',
}

const CANONICAL_LABEL_ALIASES: Record<string, string> = {
  'Rend Armor Mult': 'Rend Armor Multi',
}

function getCanonicalDefinition(category: ModuleSaveSlotCategory, label: string) {
  const canonical = CATEGORY_TO_CANONICAL[category]
  const canonicalLabel = CANONICAL_LABEL_ALIASES[label] ?? label
  if (canonicalLabel === 'Death Wave - Quantity') {
    return {
      label,
      valuesByRarity: { Epic: '+1', Legendary: '+2', Mythic: '+3', Ancestral: '+4' } as const,
      availableRarities: ['Epic', 'Legendary', 'Mythic', 'Ancestral'] as const,
    }
  }
  return MODULE_SUBSTAT_CANONICAL_DATA[canonical].substats.find(definition => definition.label === canonicalLabel)
}

function parseCanonicalSubstatValue(raw: string): number | null {
  const cleaned = raw
    .trim()
    .replace(/^\+/, '')
    .replace(/%$/, '')
    .replace(/x$/i, '')
    .replace(/s$/i, '')
    .replace(/m$/i, '')
    .replace(/°$/, '')
  const match = cleaned.match(/-?\d+(?:\.\d+)?/)
  if (!match) return null
  const parsed = Number(match[0])
  return Number.isFinite(parsed) ? parsed : null
}

function formatBenefitFallback(benefitValue: number): string {
  if (Number.isInteger(benefitValue)) return `+${benefitValue}`
  return `+${benefitValue}`
}

/**
 * Format the in-game substat value for a decoded save effect.
 * Prefers the canonical value chart; falls back to the raw benefit value.
 */
export function formatModuleSaveEffectDisplayValue(
  label: string,
  category: ModuleSaveSlotCategory,
  tier: string,
  benefitValue: number,
): string | null {
  const definition = getCanonicalDefinition(category, label)
  if (!definition) return benefitValue ? formatBenefitFallback(benefitValue) : null

  if (MODULE_SUBSTAT_BASE_RARITIES.includes(tier as ModuleSubstatCanonicalRarity)) {
    const valuesByRarity = definition.valuesByRarity as Partial<Record<ModuleSubstatCanonicalRarity, string>>
    const canonical = valuesByRarity[tier as ModuleSubstatCanonicalRarity]
    if (canonical) return canonical
  }

  if (!benefitValue) return null

  let best: { value: string; delta: number } | null = null
  const valuesByRarity = definition.valuesByRarity as Partial<Record<ModuleSubstatCanonicalRarity, string>>
  for (const rarity of MODULE_SUBSTAT_BASE_RARITIES) {
    const canonicalRaw = valuesByRarity[rarity]
    if (!canonicalRaw) continue
    const canonical = parseCanonicalSubstatValue(canonicalRaw)
    if (canonical === null) continue
    const delta = Math.abs(Math.abs(benefitValue) - Math.abs(canonical))
    if (!best || delta < best.delta) {
      best = { value: canonicalRaw, delta }
    }
  }

  return best?.value ?? formatBenefitFallback(benefitValue)
}
