/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    BuildRegistryOptions, buildMechanicsRegistryFromHandle, buildMechanicsRegistry
 * depends    src/mechanics/coverage/schema, src/mechanics/debug-graph/schema, src/mechanics/kernel/load, src/mechanics/kernel/schema, src/mechanics/mcp-contract, src/mechanics/mcp-contract/catalog (+2 more)
 * used by    src/mechanics/docs-gen/index, src/mechanics/registry/index, src/mechanics/registry/write
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
import { createHash } from 'node:crypto'
import type { CoverageInventory } from '../coverage/schema'
import type { DebugGraph } from '../debug-graph/schema'
import type { MechanicsKernelHandle } from '../kernel/schema'
import { loadMechanicsKernel, type LoadMechanicsKernelOptions } from '../kernel/load'
import { MCP_TOOL_CATALOG } from '../mcp-contract/catalog'
import { TRUST_INVARIANT_IDS } from '../mcp-contract'
import type { SdkGraph } from '../sdk-graph/schema'
import {
  MechanicsRegistrySchema,
  type MechanicsRegistry,
  type RegistryEntry,
} from './schema'

const DOC_CONTRACTS: Array<{ id: string; label: string; path: string }> = [
  { id: 'doc.constitution', label: 'Mechanics Constitution', path: 'docs/AGENT_MECHANICS_CONSTITUTION.md' },
  { id: 'doc.game-mechanics', label: 'Game mechanics contract', path: 'docs/AGENT_GAME_MECHANICS_CONTRACT.md' },
  { id: 'doc.trust', label: 'Mechanics trust contract', path: 'docs/AGENT_MECHANICS_TRUST_CONTRACT.md' },
  { id: 'doc.kernel', label: 'Mechanics kernel protocol', path: 'docs/AGENT_MECHANICS_KERNEL_PROTOCOL.md' },
  { id: 'doc.mcp', label: 'Unified MCP contract', path: 'docs/AGENT_MCP_CONTRACT.md' },
  { id: 'doc.sdk-graph', label: 'SDK graph protocol', path: 'docs/AGENT_SDK_GRAPH_PROTOCOL.md' },
  { id: 'doc.ep-graph', label: 'EP graph protocol', path: 'docs/AGENT_EP_GRAPH_PROTOCOL.md' },
  { id: 'doc.debug', label: 'Debug graph protocol', path: 'docs/AGENT_DEBUG_GRAPH_PROTOCOL.md' },
  { id: 'doc.doctor', label: 'SDK Doctor protocol', path: 'docs/AGENT_SDK_DOCTOR_PROTOCOL.md' },
  { id: 'doc.save-graph', label: 'Save schema graph protocol', path: 'docs/AGENT_SAVE_GRAPH_PROTOCOL.md' },
  { id: 'doc.sandbox', label: 'Sandbox protocol', path: 'docs/AGENT_SANDBOX_PROTOCOL.md' },
  { id: 'doc.commit-cap', label: 'Commit Authorization Protocol', path: 'docs/AGENT_COMMIT_AUTHORIZATION.md' },
  { id: 'doc.commit-schema', label: 'Agent commit schema', path: 'docs/AGENT_COMMIT_SCHEMA.md' },
  { id: 'doc.governance-engine', label: 'Governance engine boundary', path: 'docs/AGENT_GOVERNANCE_ENGINE.md' },
]

function countByKind(entries: RegistryEntry[]): Record<string, number> {
  const counts: Record<string, number> = {}
  for (const e of entries) {
    counts[e.kind] = (counts[e.kind] ?? 0) + 1
  }
  return counts
}

export interface BuildRegistryOptions {
  /** Cap entries per kind for MCP responses (full write uses unlimited). */
  maxPerKind?: number
  kind?: RegistryEntry['kind']
  includeDoctorIssues?: boolean
}

/**
 * Build the mechanics registry TOC from a kernel handle.
 * Registry is discoverability only — graphs remain relationship SoT.
 */
export function buildMechanicsRegistryFromHandle(
  handle: MechanicsKernelHandle,
  opts: BuildRegistryOptions = {},
): MechanicsRegistry {
  const entries: RegistryEntry[] = []
  const max = opts.maxPerKind
  const kindFilter = opts.kind

  const push = (entry: RegistryEntry) => {
    if (kindFilter && entry.kind !== kindFilter) return
    if (max != null) {
      const n = entries.filter(e => e.kind === entry.kind).length
      if (n >= max) return
    }
    entries.push(entry)
  }

  const sdk = handle.sdkGraph as SdkGraph
  for (const [id, node] of Object.entries(sdk.nodes)) {
    push({
      id: `node:${id}`,
      kind: 'mechanicNode',
      label: node.label,
      family: node.family,
      status: node.status,
      refs: [id],
    })
  }
  for (const edge of sdk.edges) {
    push({
      id: `edge:sdk:${edge.id}`,
      kind: 'graphEdge',
      label: `${edge.kind} ${edge.from}→${edge.to}`,
      refs: [edge.from, edge.to],
    })
  }

  // EP graph is merged into sdk for relationships; keep epGraph on handle for callers.

  const dbg = handle.debugGraph as DebugGraph
  for (const [id, node] of Object.entries(dbg.nodes)) {
    if (node.type === 'runtime.symbol') {
      push({
        id: `debug:${id}`,
        kind: 'debugSymbol',
        label: node.exportName ?? node.label ?? id,
        path: node.path,
        refs: [id],
      })
    } else if (node.type === 'runtime.module') {
      push({
        id: `debug:${id}`,
        kind: 'debugModule',
        label: node.label ?? id,
        path: node.path,
        refs: [id],
      })
    } else if (node.type === 'runtime.test') {
      push({
        id: `debug:${id}`,
        kind: 'debugTest',
        label: node.label ?? id,
        path: node.path,
        refs: [id],
      })
    }
  }

  const saveGraph = handle.saveGraph as { nodes?: Record<string, { id: string; type: string; label: string; path?: string; status?: string; mechanicNodeIds?: string[] }> } | undefined
  if (saveGraph?.nodes) {
    for (const [id, node] of Object.entries(saveGraph.nodes)) {
      if (node.type === 'save.module') {
        push({
          id: `save:${id}`,
          kind: 'saveModule',
          label: node.label,
          path: node.path,
          status: node.status,
          refs: node.mechanicNodeIds ?? [],
        })
      } else if (node.type === 'save.field') {
        push({
          id: `save:${id}`,
          kind: 'saveField',
          label: node.label,
          path: node.path,
          status: node.status,
          refs: node.mechanicNodeIds ?? [],
        })
      }
    }
  }

  for (const [surface, raw] of Object.entries(handle.inventories)) {
    const inv = raw as CoverageInventory | null
    if (!inv?.entries) continue
    for (const entry of inv.entries) {
      push({
        id: `coverage:${surface}:${entry.id}`,
        kind: 'coverageEntry',
        label: entry.label,
        status: entry.coverageStatus,
        refs: entry.graphNodeIds ?? [],
      })
    }
  }

  for (const id of TRUST_INVARIANT_IDS) {
    push({
      id: `invariant:def:${id}`,
      kind: 'invariant',
      label: id,
      status: 'definition',
      refs: [],
    })
  }
  for (const hit of handle.trust.invariants) {
    push({
      id: `invariant:hit:${hit.id}:${hit.nodeIds?.[0] ?? hit.surfaceIds?.[0] ?? 'global'}`,
      kind: 'invariant',
      label: hit.message,
      status: hit.severity,
      refs: [...(hit.nodeIds ?? []), ...(hit.surfaceIds ?? [])],
    })
  }

  // Only include live doctor issue ids when diagnosis was run and we re-diagnose lightly via status
  if (opts.includeDoctorIssues && handle.doctorStatus && handle.doctorStatus !== 'healthy') {
    push({
      id: `doctor:status:${handle.doctorStatus}`,
      kind: 'doctorIssue',
      label: `Doctor status ${handle.doctorStatus}`,
      status: handle.doctorStatus,
      refs: [],
    })
  }

  for (const doc of DOC_CONTRACTS) {
    push({
      id: doc.id,
      kind: 'docContract',
      label: doc.label,
      path: doc.path,
      refs: [],
    })
  }

  for (const tool of MCP_TOOL_CATALOG) {
    push({
      id: `mcp:${tool.name}`,
      kind: 'mcpTool',
      label: tool.name,
      family: tool.category,
      status: tool.module,
      refs: [],
    })
  }

  const countsByKind = countByKind(entries)

  return MechanicsRegistrySchema.parse({
    version: 1,
    contentHash: createHash('sha256')
      .update(JSON.stringify({ countsByKind, entries }))
      .digest('hex')
      .slice(0, 16),
    constitution: 'docs/AGENT_MECHANICS_CONSTITUTION.md',
    countsByKind,
    entries,
  })
}

export function buildMechanicsRegistry(
  opts: LoadMechanicsKernelOptions & BuildRegistryOptions = {},
): MechanicsRegistry {
  const handle = loadMechanicsKernel(opts)
  return buildMechanicsRegistryFromHandle(handle, opts)
}
