/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    RegistryEntryKindSchema, RegistryEntryKind, RegistryEntrySchema, RegistryEntry, MechanicsRegistrySchema, MechanicsRegistry
 * depends    —
 * used by    src/mechanics/registry/build, src/mechanics/registry/index, src/mechanics/registry/write
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
import { z } from 'zod'

export const RegistryEntryKindSchema = z.enum([
  'mechanicNode',
  'graphEdge',
  'debugSymbol',
  'debugModule',
  'debugTest',
  'saveModule',
  'saveField',
  'coverageEntry',
  'invariant',
  'doctorIssue',
  'docContract',
  'mcpTool',
])
export type RegistryEntryKind = z.infer<typeof RegistryEntryKindSchema>

export const RegistryEntrySchema = z.object({
  id: z.string().min(1),
  kind: RegistryEntryKindSchema,
  label: z.string().min(1),
  family: z.string().optional(),
  path: z.string().optional(),
  status: z.string().optional(),
  refs: z.array(z.string()).default([]),
})
export type RegistryEntry = z.infer<typeof RegistryEntrySchema>

export const MechanicsRegistrySchema = z.object({
  version: z.literal(1),
  /**
   * What is in this registry, not when it was written.
   *
   * `latest.json` is committed, so a wall-clock stamp meant every build produced a diff carrying no
   * information — and the choice between committing noise or living with a permanently dirty tree.
   * A hash of the entries answers the question a reader of a generated file actually has: is this
   * the same registry I saw before?
   */
  contentHash: z.string(),
  constitution: z.literal('docs/AGENT_MECHANICS_CONSTITUTION.md'),
  countsByKind: z.record(z.string(), z.number()),
  entries: z.array(RegistryEntrySchema),
})
export type MechanicsRegistry = z.infer<typeof MechanicsRegistrySchema>
