/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    writeMechanicsRegistry, buildAndWriteMechanicsRegistry
 * depends    src/mechanics/kernel, src/mechanics/registry/build, src/mechanics/registry/schema
 * used by    src/mechanics/registry/index
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
import fs from 'node:fs'
import path from 'node:path'
import {
  loadMechanicsKernel,
  resolveMechanicsRepoRoot,
  type LoadMechanicsKernelOptions,
} from '../kernel'
import {
  buildMechanicsRegistryFromHandle,
  type BuildRegistryOptions,
} from './build'
import type { MechanicsRegistry } from './schema'

export function writeMechanicsRegistry(
  registry: MechanicsRegistry,
  repoRoot?: string,
): string {
  const root = resolveMechanicsRepoRoot(repoRoot)
  const dir = path.join(root, 'docs/mechanics-map/registry')
  fs.mkdirSync(dir, { recursive: true })
  const outPath = path.join(dir, 'latest.json')
  fs.writeFileSync(outPath, `${JSON.stringify(registry, null, 2)}\n`, 'utf8')
  return outPath
}

export function buildAndWriteMechanicsRegistry(
  opts: LoadMechanicsKernelOptions & BuildRegistryOptions = {},
): { registry: MechanicsRegistry; wrote: string } {
  const handle = loadMechanicsKernel(opts)
  const registry = buildMechanicsRegistryFromHandle(handle, opts)
  const wrote = writeMechanicsRegistry(registry, opts.repoRoot)
  return { registry, wrote }
}
