/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    DocsGenOptions, DocsGenResult, generateMechanicsDocs, generateMechanicsDocsFromHandle
 * depends    src/mechanics/kernel, src/mechanics/kernel/schema, src/mechanics/mcp-contract, src/mechanics/registry/build, src/mechanics/save-graph
 * used by    —
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
import fs from 'node:fs'
import path from 'node:path'
import type { MechanicsKernelHandle } from '../kernel/schema'
import { loadMechanicsKernel, resolveMechanicsRepoRoot, type LoadMechanicsKernelOptions } from '../kernel'
import { getMcpContract } from '../mcp-contract'
import { buildMechanicsRegistryFromHandle } from '../registry/build'
import { loadSaveGraphDegraded } from '../save-graph'

export interface DocsGenOptions extends LoadMechanicsKernelOptions {
  outDir?: string
}

export interface DocsGenResult {
  ok: boolean
  wrote: string[]
  outDir: string
}

function mdEscape(s: string): string {
  return s.replace(/\|/g, '\\|')
}

/**
 * Emit canonical substrate docs from Kernel / Registry / graphs / MCP contract.
 * Does not invent mechanic formulas — only reports what graphs already contain.
 */
export function generateMechanicsDocs(opts: DocsGenOptions = {}): DocsGenResult {
  const repoRoot = resolveMechanicsRepoRoot(opts.repoRoot)
  const outDir = opts.outDir
    ?? path.join(repoRoot, 'docs/mechanics-map/generated')
  fs.mkdirSync(outDir, { recursive: true })

  const handle = loadMechanicsKernel({ ...opts, includeDoctor: opts.includeDoctor !== false })
  const registry = buildMechanicsRegistryFromHandle(handle, { includeDoctorIssues: true })
  const contract = getMcpContract()
  const save = loadSaveGraphDegraded()
  const wrote: string[] = []

  const overview = [
    '# Mechanics substrate (generated)',
    '',
    `Generated from SDK graph \`${handle.context.graphs.sdk.contentVersion}\`, sheet \`${handle.context.graphs.sdk.sheetVersion}\`.`,
    '',
    'Law: [`AGENT_MECHANICS_CONSTITUTION.md`](../../AGENT_MECHANICS_CONSTITUTION.md)',
    '',
    '## Health',
    '',
    `- trustOk: \`${handle.context.trustOk}\``,
    `- doctorStatus: \`${handle.context.doctorStatus ?? 'n/a'}\``,
    `- ok: \`${handle.context.ok}\``,
    '',
    '## Graphs',
    '',
    `| Graph | Nodes | Edges |`,
    `|---|---:|---:|`,
    `| SDK | ${handle.context.graphs.sdk.nodeCount} | ${handle.context.graphs.sdk.edgeCount} |`,
    `| EP | ${handle.context.graphs.ep.nodeCount} | ${handle.context.graphs.ep.edgeCount} |`,
    `| Debug | ${handle.context.graphs.debug.nodeCount} | ${handle.context.graphs.debug.edgeCount} |`,
    `| Save | ${Object.keys(save.graph.nodes).length} | ${save.graph.edges.length} |`,
    '',
    '## Coverage surfaces',
    '',
    ...Object.entries(handle.context.coverage.surfaces).flatMap(([name, s]) => [
      `- **${name}**: ${s.entryCount} entries, ${s.silentGapCount} silent gaps`,
    ]),
    '',
    '## Registry counts',
    '',
    ...Object.entries(registry.countsByKind).map(([k, n]) => `- ${k}: ${n}`),
    '',
    '## MCP contract',
    '',
    `- tools: ${contract.tools.length}`,
    `- categories: ${contract.categories.join(', ')}`,
    '',
    'This file is generated by `pnpm mechanics-docs`. Do not hand-edit.',
    '',
  ].join('\n')
  const overviewPath = path.join(outDir, 'overview.md')
  fs.writeFileSync(overviewPath, overview, 'utf8')
  wrote.push(overviewPath)

  const invariantsPath = path.join(outDir, 'invariants.md')
  fs.writeFileSync(
    invariantsPath,
    [
      '# Trust invariants (generated)',
      '',
      ...handle.trust.invariants.map(i => `- **${i.id}** (${i.severity}): ${mdEscape(i.message)}`),
      handle.trust.invariants.length === 0 ? '_No invariant hits on current load._' : '',
      '',
    ].join('\n'),
    'utf8',
  )
  wrote.push(invariantsPath)

  const mcpPath = path.join(outDir, 'mcp-tools.md')
  fs.writeFileSync(
    mcpPath,
    [
      '# MCP tools (generated)',
      '',
      '| Tool | Category | Module |',
      '|---|---|---|',
      ...contract.tools.map(t => `| \`${t.name}\` | ${t.category} | ${t.module} |`),
      '',
    ].join('\n'),
    'utf8',
  )
  wrote.push(mcpPath)

  const savePath = path.join(outDir, 'save-schema.md')
  const byType: Record<string, number> = {}
  for (const n of Object.values(save.graph.nodes)) {
    byType[n.type] = (byType[n.type] ?? 0) + 1
  }
  fs.writeFileSync(
    savePath,
    [
      '# Save schema graph (generated)',
      '',
      `- nodes: ${Object.keys(save.graph.nodes).length}`,
      `- edges: ${save.graph.edges.length}`,
      `- validate errors: ${save.errors.length}`,
      `- byType: ${JSON.stringify(byType)}`,
      `- verified fields: ${Object.values(save.graph.nodes).filter(n => n.type === 'save.field' && n.status === 'verified').length}`,
      '',
      'Fixture-backed keys are verified; others remain researching/unmodeled.',
      '',
    ].join('\n'),
    'utf8',
  )
  wrote.push(savePath)

  // Per-family mechanic pages from SDK graph
  const familiesDir = path.join(outDir, 'families')
  fs.mkdirSync(familiesDir, { recursive: true })
  const sdk = handle.sdkGraph as {
    nodes: Record<string, {
      id: string
      family: string
      type: string
      label: string
      status: string
      formula?: string
      formulaSource?: string
      sourceCells?: Array<{ sheet: string; cell: string }>
      wikiPages?: string[]
      codeSymbols?: string[]
    }>
  }
  const byFamily = new Map<string, typeof sdk.nodes[string][]>()
  for (const node of Object.values(sdk.nodes ?? {})) {
    const list = byFamily.get(node.family) ?? []
    list.push(node)
    byFamily.set(node.family, list)
  }
  const familyIndex: string[] = [
    '# Mechanic families (generated)',
    '',
  ]
  for (const family of [...byFamily.keys()].sort()) {
    const nodes = byFamily.get(family) ?? []
    const slug = family.replace(/[^A-Za-z0-9._-]/g, '_')
    const page = path.join(familiesDir, `${slug}.md`)
    fs.writeFileSync(
      page,
      [
        `# Family \`${family}\``,
        '',
        `Nodes: **${nodes.length}**`,
        '',
        '| Id | Type | Status | Label | Provenance |',
        '|---|---|---|---|---|',
        ...nodes.map(n => {
          const prov = [
            ...(n.sourceCells ?? []).map(c => `${c.sheet}!${c.cell}`),
            ...(n.wikiPages ?? []),
            ...(n.codeSymbols ?? []),
            n.formulaSource ? `formula:${n.formulaSource}` : '',
          ].filter(Boolean).join(', ')
          return `| \`${n.id}\` | ${n.type} | ${n.status} | ${mdEscape(n.label)} | ${mdEscape(prov) || '—'} |`
        }),
        '',
        ...nodes.filter(n => n.formula).flatMap(n => [
          `## Formula — \`${n.id}\``,
          '',
          `Source: \`${n.formulaSource}\``,
          '',
          '```',
          n.formula!,
          '```',
          '',
        ]),
      ].join('\n'),
      'utf8',
    )
    wrote.push(page)
    familyIndex.push(`- [\`${family}\`](./families/${slug}.md) — ${nodes.length} nodes`)
  }
  familyIndex.push('')
  const familyIndexPath = path.join(outDir, 'families.md')
  fs.writeFileSync(familyIndexPath, familyIndex.join('\n'), 'utf8')
  wrote.push(familyIndexPath)

  const indexJson = path.join(outDir, 'index.json')
  fs.writeFileSync(
    indexJson,
    `${JSON.stringify({
      /*
       * No wall-clock stamp.
       *
       * These files are committed, so a timestamp made every build produce a diff that said
       * nothing: two lines changed, no information in either. The content and sheet versions
       * inside `context.graphs` already identify which data this was emitted from, which is the
       * question a reader of a generated file actually has.
       */
      ok: handle.context.ok && save.errors.length === 0,
      wrote: wrote.map(p => path.relative(repoRoot, p).split(path.sep).join('/')),
      context: { ...handle.context, generatedAt: undefined },
      registryCounts: registry.countsByKind,
      saveGraph: {
        nodeCount: Object.keys(save.graph.nodes).length,
        edgeCount: save.graph.edges.length,
        errors: save.errors,
      },
      mcpToolCount: contract.tools.length,
    }, null, 2)}\n`,
    'utf8',
  )
  wrote.push(indexJson)

  return {
    ok: handle.context.ok && save.errors.length === 0,
    wrote,
    outDir,
  }
}

/** @deprecated alias for callers that already hold a kernel handle */
export function generateMechanicsDocsFromHandle(
  handle: MechanicsKernelHandle,
  opts: DocsGenOptions = {},
): DocsGenResult {
  void handle
  return generateMechanicsDocs(opts)
}
