/**
 * Lifetime totals — the running counts a save carries across every run.
 *
 * Twenty-two fields, and only a handful appear anywhere else, so this is usually the only source
 * for them.
 */
/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    —
 * depends    src/save/lifetime/read
 * used by    —
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
export * from './read'
