/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    LifetimeImportEntryFields, LifetimeStoredEntry, LIFETIME_STARTED_AT_KEY, LIFETIME_SAVE_ORB_KILLS_KEY, LIFETIME_SAVE_ORB_KILLS_FIELD_BEFORE_V29, LIFETIME_SAVE_CELLS_EARNED_KEY, LIFETIME_SAVE_CELLS_EARNED_FIELD_BEFORE_V2, LifetimeSaveFieldRow (+14 more)
 * depends    src/formatting, src/save/access/values, src/save/battle/history, src/save/runs/lifetime-fields
 * used by    src/mechanics/calculators/specs-generated, src/save/import/counts, src/save/import/planner, src/save/index, src/save/lifetime/index
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
import { formatNumberForDisplay, normalizeNumericValue } from '../../formatting'
import { parseSaveDateTimeToMs } from '../../formatting'
import { coerceSaveNumber } from '../access/values'
import { computeCoinsPerHourFromSaveRoot } from '../battle/history'
import { normalizeLifetimeDate } from '../runs/lifetime-fields'

export interface LifetimeImportEntryFields {
  date: string
  gameStarted: string
  coinsEarned: string
  cashEarned: string
  stonesEarned: string
  keysEarned: string
  cellsEarned?: string
  rerollShardsEarned?: string
  recentCoinsPerHour?: string
  damageDealt: string
  enemiesDestroyed: string
  wavesCompleted: string
  upgradesBought: string
  workshopUpgrades: string
  workshopCoinsSpent: string
  researchCompleted: string
  labCoinsSpent: string
  freeUpgrades: string
  interestEarned: string
  orbKills: string
  deathRayKills: string
  thornDamage: string
  wavesSkipped: string
}

export interface LifetimeStoredEntry extends LifetimeImportEntryFields {
  id: string
  screenshotUrl?: string
  verified?: boolean | null
  blocked?: boolean
}

export const LIFETIME_STARTED_AT_KEY = 'gameStartedDate'
/**
 * Orb kills, as v29 spells it.
 *
 * Up to v28.3 the game's own field was `totalEnemiesDestryoedByOrbs` -- "Destryoed", a typo it
 * carried for years, and only on the two ORB counters; every other `totalEnemiesDestroyedBy*`
 * was spelled correctly beside them. v29 fixed it, which moved the field and renamed it.
 *
 * Both spellings have to be read, because saves outlive versions: a save written by v28 will
 * never contain the new name and a v29 save will never contain the old one. Reading only one
 * returns nothing for half the saves in existence, and "nothing" here looks exactly like a
 * player who has never used orbs.
 */
export const LIFETIME_SAVE_ORB_KILLS_KEY = 'totalEnemiesDestroyedByOrbs'

/** The pre-v29 spelling of {@link LIFETIME_SAVE_ORB_KILLS_KEY}. Present in every older save. */
export const LIFETIME_SAVE_ORB_KILLS_FIELD_BEFORE_V29 = 'totalEnemiesDestryoedByOrbs'

/**
 * Lifetime cells, as current builds spell it.
 *
 * `totalCellsEarned` was an int; once totals grew past that range the game added
 * `totalCellsEarned_v2` (double) and stopped treating the int as authoritative.
 * Prefer the v2 field, then fall back so older saves still import.
 */
export const LIFETIME_SAVE_CELLS_EARNED_KEY = 'totalCellsEarned_v2'

/** Pre-v2 lifetime cells field. Kept as a rename fallback for older saves. */
export const LIFETIME_SAVE_CELLS_EARNED_FIELD_BEFORE_V2 = 'totalCellsEarned'

export interface LifetimeSaveFieldRow {
  targetKey: keyof LifetimeImportEntryFields
  saveKey: string | readonly string[]
  /**
   * Spellings this field used to have, tried in order and only when `saveKey` is absent.
   *
   * NOT the same as giving `saveKey` an array: that form SUMS its keys, which is right for a
   * value split across three fields and wrong for a rename, where matching two spellings at once
   * would silently double the number.
   */
  renamedFrom?: readonly string[]
  label: string
  optional?: boolean
}

export const LIFETIME_SAVE_FIELD_ROWS: readonly LifetimeSaveFieldRow[] = [
  { targetKey: 'gameStarted', saveKey: LIFETIME_STARTED_AT_KEY, label: 'Game Started' },
  { targetKey: 'coinsEarned', saveKey: 'totalCoinsEarned', label: 'Coins Earned' },
  { targetKey: 'cashEarned', saveKey: 'totalCashEarned', label: 'Cash Earned' },
  { targetKey: 'stonesEarned', saveKey: 'totalStonesEarned', label: 'Stones Earned' },
  { targetKey: 'keysEarned', saveKey: 'totalKeysEarned', label: 'Keys Earned' },
  { targetKey: 'cellsEarned', saveKey: LIFETIME_SAVE_CELLS_EARNED_KEY, renamedFrom: [LIFETIME_SAVE_CELLS_EARNED_FIELD_BEFORE_V2], label: 'Cells Earned', optional: true },
  { targetKey: 'rerollShardsEarned', saveKey: 'moduleRerollCurrencyLifetime', label: 'Dice Earned', optional: true },
  { targetKey: 'damageDealt', saveKey: 'totalDamageDealt', label: 'Damage Dealt' },
  { targetKey: 'enemiesDestroyed', saveKey: 'totalEnemiesDestroyed', label: 'Enemies Destroyed' },
  { targetKey: 'wavesCompleted', saveKey: 'totalWavesCompleted', label: 'Waves Completed' },
  { targetKey: 'upgradesBought', saveKey: 'totalUpgradesBought', label: 'Upgrades Bought' },
  { targetKey: 'workshopUpgrades', saveKey: 'totalWorkshopUpgradesBought', label: 'Workshop Upgrades' },
  { targetKey: 'workshopCoinsSpent', saveKey: 'totalCoinsSpentWorkshop', label: 'Workshop Coins Spent' },
  { targetKey: 'researchCompleted', saveKey: 'researchesComplete', label: 'Research Completed' },
  { targetKey: 'labCoinsSpent', saveKey: 'totalCoinsSpentOnResearch', label: 'Lab Coins Spent' },
  { targetKey: 'freeUpgrades', saveKey: ['totalFreeAttackUpgrades', 'totalFreeDefenseUpgrades', 'totalFreeUtilityUpgrades'], label: 'Free Upgrades' },
  { targetKey: 'interestEarned', saveKey: 'totalCashEarnedFromInterest', label: 'Interest Earned' },
  { targetKey: 'orbKills', saveKey: LIFETIME_SAVE_ORB_KILLS_KEY, renamedFrom: [LIFETIME_SAVE_ORB_KILLS_FIELD_BEFORE_V29], label: 'Orb Kills' },
  { targetKey: 'deathRayKills', saveKey: 'totalEnemiesDestroyedByDeathRay', label: 'Death Ray Kills' },
  { targetKey: 'thornDamage', saveKey: 'totalDamageByThorn', label: 'Thorn Damage' },
  { targetKey: 'wavesSkipped', saveKey: 'totalWavesSkipped', label: 'Waves Skipped' },
  { targetKey: 'recentCoinsPerHour', saveKey: 'recentCoinsPerHour', label: 'Recent Coins Per Hour', optional: true },
] as const

export interface LifetimeSaveExtract {
  values: Record<string, string>
  warnings: string[]
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return !!value && typeof value === 'object' && !Array.isArray(value)
}

function readSaveField(root: Record<string, unknown>, key: string): unknown {
  return root[key] ?? null
}

function parseSaveNumericMagnitude(value: unknown): number | null {
  if (value === null || value === undefined) return null
  if (typeof value === 'number' && Number.isFinite(value)) return value

  if (typeof value === 'string' && value.trim() !== '') {
    const parsed = Number(value.trim().replace(/,/g, ''))
    return Number.isFinite(parsed) ? parsed : null
  }

  if (!isRecord(value)) return null

  if (value.__type === 'BigInt' && value.__value != null) {
    const parsed = Number(String(value.__value).replace(/,/g, ''))
    return Number.isFinite(parsed) ? parsed : null
  }

  if (typeof value.mantissa === 'number' && typeof value.exponent === 'number') {
    const magnitude = value.mantissa * (10 ** value.exponent)
    return Number.isFinite(magnitude) ? magnitude : null
  }

  if ('__value' in value) {
    return parseSaveNumericMagnitude(value.__value)
  }

  return coerceSaveNumber(value)
}

export function saveValueToNumericString(value: unknown): string {
  const magnitude = parseSaveNumericMagnitude(value)
  if (magnitude === null) return '0'
  if (Math.abs(magnitude) < 1000) {
    return normalizeNumericValue(String(Math.round(magnitude)))
  }
  return normalizeNumericValue(formatNumberForDisplay(magnitude))
}

function saveDateToIsoDay(value: unknown): string {
  const ms = parseSaveDateTimeToMs(value)
  if (ms == null) return ''
  const date = new Date(ms)
  const year = date.getFullYear()
  const month = String(date.getMonth() + 1).padStart(2, '0')
  const day = String(date.getDate()).padStart(2, '0')
  return normalizeLifetimeDate(`${year}-${month}-${day}`)
}

function readSaveValue(root: Record<string, unknown>, saveKey: string | readonly string[]): unknown {
  if (typeof saveKey === 'string') {
    return readSaveField(root, saveKey)
  }

  const parts = saveKey
    .map(key => coerceSaveNumber(readSaveField(root, key)))
    .filter((value): value is number => value !== null)

  if (!parts.length) return null
  return parts.reduce((sum, value) => sum + value, 0)
}

export function readLifetimeFromSaveRoot(parsedRoot: unknown): LifetimeSaveExtract | null {
  if (!parsedRoot || typeof parsedRoot !== 'object') return null

  const root = parsedRoot as Record<string, unknown>
  const warnings: string[] = []
  const values: Record<string, string> = {
    date: new Date().toISOString().split('T')[0],
  }

  let mappedCount = 0

  for (const row of LIFETIME_SAVE_FIELD_ROWS) {
    let raw = readSaveValue(root, row.saveKey)
    for (const older of row.renamedFrom ?? []) {
      if (raw !== null && raw !== undefined && raw !== '') break
      raw = readSaveValue(root, older)
    }
    if (raw === null || raw === undefined || raw === '') {
      if (!row.optional) {
        warnings.push(`Missing save field for ${row.label}.`)
      }
      continue
    }

    if (row.targetKey === 'gameStarted') {
      const isoDay = saveDateToIsoDay(raw)
      if (!isoDay) {
        warnings.push('Could not parse game started date from save.')
        continue
      }
      values.gameStarted = isoDay
      mappedCount += 1
      continue
    }

    values[row.targetKey] = saveValueToNumericString(raw)
    mappedCount += 1
  }

  // Not a root field — the game's own panel derives it from battle history
  // (mean of the three best run rates). Prefer that over a silent zero.
  if (!values.recentCoinsPerHour) {
    const inferred = computeCoinsPerHourFromSaveRoot(root)
    values.recentCoinsPerHour = inferred != null && inferred > 0
      ? saveValueToNumericString(inferred)
      : '0'
  }

  if (mappedCount === 0) return null

  return { values, warnings }
}

export function buildLifetimeImportPayload(
  extract: LifetimeSaveExtract,
): LifetimeImportEntryFields {
  return {
    date: extract.values.date || new Date().toISOString().split('T')[0],
    gameStarted: extract.values.gameStarted || '',
    coinsEarned: extract.values.coinsEarned || '0',
    recentCoinsPerHour: extract.values.recentCoinsPerHour || '0',
    cashEarned: extract.values.cashEarned || '0',
    stonesEarned: extract.values.stonesEarned || '0',
    keysEarned: extract.values.keysEarned || '0',
    cellsEarned: extract.values.cellsEarned || '0',
    rerollShardsEarned: extract.values.rerollShardsEarned || '0',
    damageDealt: extract.values.damageDealt || '0',
    enemiesDestroyed: extract.values.enemiesDestroyed || '0',
    wavesCompleted: extract.values.wavesCompleted || '0',
    upgradesBought: extract.values.upgradesBought || '0',
    workshopUpgrades: extract.values.workshopUpgrades || '0',
    workshopCoinsSpent: extract.values.workshopCoinsSpent || '0',
    researchCompleted: extract.values.researchCompleted || '0',
    labCoinsSpent: extract.values.labCoinsSpent || '0',
    freeUpgrades: extract.values.freeUpgrades || '0',
    interestEarned: extract.values.interestEarned || '0',
    orbKills: extract.values.orbKills || '0',
    deathRayKills: extract.values.deathRayKills || '0',
    thornDamage: extract.values.thornDamage || '0',
    wavesSkipped: extract.values.wavesSkipped || '0',
  }
}

export function normalizeLifetimeImportFields(
  entry: LifetimeImportEntryFields,
): LifetimeImportEntryFields {
  return {
    ...entry,
    date: entry.date || new Date().toISOString().split('T')[0],
    gameStarted: normalizeLifetimeDate(entry.gameStarted),
    coinsEarned: normalizeNumericValue(entry.coinsEarned),
    recentCoinsPerHour: normalizeNumericValue(entry.recentCoinsPerHour || '0'),
    cashEarned: normalizeNumericValue(entry.cashEarned),
    stonesEarned: normalizeNumericValue(entry.stonesEarned),
    keysEarned: normalizeNumericValue(entry.keysEarned),
    cellsEarned: normalizeNumericValue(entry.cellsEarned || '0'),
    rerollShardsEarned: normalizeNumericValue(entry.rerollShardsEarned || '0'),
    damageDealt: normalizeNumericValue(entry.damageDealt),
    enemiesDestroyed: normalizeNumericValue(entry.enemiesDestroyed),
    wavesCompleted: normalizeNumericValue(entry.wavesCompleted),
    upgradesBought: normalizeNumericValue(entry.upgradesBought),
    workshopUpgrades: normalizeNumericValue(entry.workshopUpgrades),
    workshopCoinsSpent: normalizeNumericValue(entry.workshopCoinsSpent),
    researchCompleted: normalizeNumericValue(entry.researchCompleted),
    labCoinsSpent: normalizeNumericValue(entry.labCoinsSpent),
    freeUpgrades: normalizeNumericValue(entry.freeUpgrades),
    interestEarned: normalizeNumericValue(entry.interestEarned),
    orbKills: normalizeNumericValue(entry.orbKills),
    deathRayKills: normalizeNumericValue(entry.deathRayKills),
    thornDamage: normalizeNumericValue(entry.thornDamage),
    wavesSkipped: normalizeNumericValue(entry.wavesSkipped),
  }
}

export const LIFETIME_MIN_IMPORT_DIFF_COUNT = 3

export const LIFETIME_IMPORT_COMPARABLE_KEYS = [
  'coinsEarned',
  'recentCoinsPerHour',
  'cashEarned',
  'stonesEarned',
  'keysEarned',
  'cellsEarned',
  'rerollShardsEarned',
  'damageDealt',
  'enemiesDestroyed',
  'wavesCompleted',
  'upgradesBought',
  'workshopUpgrades',
  'workshopCoinsSpent',
  'researchCompleted',
  'labCoinsSpent',
  'freeUpgrades',
  'interestEarned',
  'orbKills',
  'deathRayKills',
  'thornDamage',
  'wavesSkipped',
] as const satisfies readonly (keyof LifetimeImportEntryFields)[]

function lifetimeImportValuesMatch(left: unknown, right: unknown): boolean {
  if (left == null && right == null) return true
  if (left == null || right == null) return false
  const a = String(left).trim().replace(/,/g, '')
  const b = String(right).trim().replace(/,/g, '')
  if (!a || !b) return a === b
  const numA = Number(a)
  const numB = Number(b)
  if (Number.isFinite(numA) && Number.isFinite(numB)) {
    return Math.floor(numA) === Math.floor(numB)
  }
  return a === b
}

export function countLifetimeImportFieldDifferences(
  importFields: LifetimeImportEntryFields,
  stored: LifetimeImportEntryFields,
): number {
  let diffCount = 0
  for (const key of LIFETIME_IMPORT_COMPARABLE_KEYS) {
    if (!lifetimeImportValuesMatch(importFields[key], stored[key])) {
      diffCount += 1
    }
  }
  return diffCount
}

export function findBestMatchingLifetimeEntryIndex(
  entries: readonly LifetimeStoredEntry[],
  fields: LifetimeImportEntryFields,
): { index: number; diffCount: number } {
  if (entries.length === 0) {
    return { index: -1, diffCount: LIFETIME_IMPORT_COMPARABLE_KEYS.length }
  }

  let bestIndex = 0
  let bestDiff = countLifetimeImportFieldDifferences(fields, entries[0]!)
  for (let index = 1; index < entries.length; index += 1) {
    const diffCount = countLifetimeImportFieldDifferences(fields, entries[index]!)
    if (diffCount < bestDiff) {
      bestDiff = diffCount
      bestIndex = index
    }
  }
  return { index: bestIndex, diffCount: bestDiff }
}

export function shouldApplyLifetimeImport(
  entries: readonly LifetimeStoredEntry[],
  fields: LifetimeImportEntryFields,
): boolean {
  if (entries.length === 0) return true
  const { diffCount } = findBestMatchingLifetimeEntryIndex(entries, fields)
  return diffCount >= LIFETIME_MIN_IMPORT_DIFF_COUNT
}

export function findLifetimeEntryIndexByGameStarted(
  entries: readonly LifetimeStoredEntry[],
  gameStarted: string,
): number {
  const key = normalizeLifetimeDate(gameStarted)
  if (!key) return -1
  return entries.findIndex(
    entry => normalizeLifetimeDate(entry.gameStarted) === key,
  )
}

export function upsertLifetimeImportEntry(
  entries: LifetimeStoredEntry[],
  fields: LifetimeImportEntryFields,
  createId: () => string,
): { nextEntries: LifetimeStoredEntry[]; entryId: string; created: boolean } {
  const normalized = normalizeLifetimeImportFields(fields)

  // Lifetime entries are time-series snapshots, so several legitimately share a
  // gameStarted date — it is not a unique key. Identity is therefore fuzzy: an
  // import that differs in fewer than LIFETIME_MIN_IMPORT_DIFF_COUNT stats is
  // treated as a re-import of an existing snapshot and skipped, while a
  // meaningfully different one becomes a new row.
  const { index, diffCount } = findBestMatchingLifetimeEntryIndex(entries, normalized)

  if (entries.length > 0 && diffCount < LIFETIME_MIN_IMPORT_DIFF_COUNT) {
    const existing = entries[index >= 0 ? index : 0]!
    return { nextEntries: entries.slice(), entryId: existing.id, created: false }
  }

  const entryId = createId()
  const nextEntry: LifetimeStoredEntry = {
    ...normalized,
    id: entryId,
    verified: false,
    blocked: false,
  }
  return { nextEntries: [nextEntry, ...entries], entryId, created: true }
}

export function canImportLifetimeFromSave(extract: LifetimeSaveExtract | null): boolean {
  if (!extract) return false
  return Boolean(extract.values.gameStarted)
    && Boolean(extract.values.coinsEarned || extract.values.cashEarned || extract.values.wavesCompleted)
}
