/**
 * The names battle conditions carry, as the game writes them.
 *
 * Only the vocabulary lives here. What a condition DOES, and which lab counters it, is a mechanic
 * and lives in `mechanics/battle-conditions`.
 */
/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    —
 * depends    src/data/battle-conditions/names
 * used by    —
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
export * from './names'
