/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    MODULE_COST_TABLE_LENGTH, MODULE_REROLL_COSTS_BY_LOCKED_SUBSTATS, ASSIST_MODULE_STONE_COSTS, getModuleCoinUpgradeCost, getModuleShardUpgradeCost, getModuleRerollCost, MODULE_SHARD_COSTS, MODULE_COIN_COSTS (+11 more)
 * depends    —
 * used by    src/data/modules/index, src/internal/module-calculator-options, src/knowledge/compartments/modules, src/mechanics/calculators/specs-generated
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
/** Cost to reach `targetLevel` from `targetLevel − 1` (matches game index: level 2 → index 0). */
export const MODULE_COST_TABLE_LENGTH = 300

/** Reroll Dice cost to reroll a module's substats, by how many are locked (0–7). Index 7 is unused. */
export const MODULE_REROLL_COSTS_BY_LOCKED_SUBSTATS: readonly number[] = [
  40, 160, 500, 1000, 1600, 2250, 3000, 0,
]

/**
 * Stone cost per level for an assist module's Multiplier Stone and Substat Stone
 * tracks — both use this same curve. Index 0 is the unlock (15 stones, 1%), and
 * each level after costs 3 more than the last, up to 70%.
 */
export const ASSIST_MODULE_STONE_COSTS: readonly number[] = Array.from({ length: 69 }, (_, i) => 15 + i * 3)

const COIN_COST_TIER_PAIRS: ReadonlyArray<readonly [number, number]> = [
  [10_000, 25_000], // levels 2–5 vs 6–10
  [45_000, 60_000], // levels 11–15 vs 16–20
  [120_000, 180_000], // levels 21–25 vs 26–30
  [350_000, 500_000], // levels 31–35 vs 36–40
  [1_000_000, 3_000_000], // levels 41–50 vs 51–60
  [25_000_000, 100_000_000], // levels 61–70 vs 71–80
  [350_000_000, 8_000_000_000], // levels 81–100 vs 101–120
  [32_000_000_000, 500_000_000_000], // levels 121–140 vs 141–160
]

const COIN_HIGH_POLY_SCALE = 5e17

function coinPair(index: number, targetLevel: number, threshold: number): number {
  const [low, high] = COIN_COST_TIER_PAIRS[index]
  return targetLevel > threshold ? high : low
}

function coinHighLinear(targetLevel: number): number {
  const slope = 50_000_000_000_000n
  const intercept = 10_000_000_000_000n
  const offset = BigInt(targetLevel - 161)
  return Number(BigInt.asIntN(64, offset * slope + intercept))
}

function coinHighQuadratic(targetLevel: number): number {
  const a = targetLevel - 200
  const b = targetLevel - 201
  let product = a * b
  if (product < 0) product += 1
  product = (product >> 1) + 2
  const multiplier = 1_250_000_000_000_000n
  return Number(BigInt.asIntN(64, BigInt(product) * multiplier))
}

function coinHighPolynomial(targetLevel: number): number {
  const a = targetLevel - 240
  const b = targetLevel - 241
  return ((b * a * 0.5) + 2.0) * COIN_HIGH_POLY_SCALE
}

/** Coin cost to upgrade a module to `targetLevel` (discount 0). */
export function getModuleCoinUpgradeCost(targetLevel: number): number {
  const level = Math.max(1, Math.floor(Number(targetLevel) || 1))

  if (level >= 161) {
    if (level > 240) return coinHighPolynomial(level)
    if (level > 200) return coinHighQuadratic(level)
    return coinHighLinear(level)
  }
  if (level >= 121) return coinPair(7, level, 140)
  if (level >= 81) return coinPair(6, level, 100)
  if (level >= 61) return coinPair(5, level, 70)
  if (level >= 41) return coinPair(4, level, 50)
  if (level >= 31) return coinPair(3, level, 35)
  if (level >= 21) return coinPair(2, level, 25)
  if (level >= 11) return coinPair(1, level, 15)
  return coinPair(0, level, 5)
}

function shardBucket(targetLevel: number): number {
  const level = Math.max(1, Math.floor(Number(targetLevel) || 1))

  if (level >= 41) {
    if (level >= 121) {
      if (level >= 161) {
        if (level > 240) return level * 500 - 100_500
        if (level > 200) return level * 250 - 40_250
        return level * 125 - 15_125
      }
      if (level >= 141) return level > 150 ? 4000 : 3000
      return level > 130 ? 2500 : 1800
    }
    if (level >= 81) {
      if (level >= 101) return level > 110 ? 1300 : 1000
      return level > 90 ? 700 : 500
    }
    if (level >= 61) return level > 70 ? 350 : 250
    return level > 50 ? 180 : 120
  }
  if (level >= 21) {
    if (level >= 31) return level > 35 ? 90 : 75
    return level > 25 ? 50 : 40
  }
  if (level >= 11) return level > 15 ? 25 : 20
  return level > 5 ? 12 : 7
}

/** Shard cost to upgrade a module to `targetLevel` (discount 0). */
export function getModuleShardUpgradeCost(targetLevel: number): number {
  return shardBucket(targetLevel)
}

/** Reroll currency cost from locked-substat count (discount 0). */
export function getModuleRerollCost(lockedSubstats: number): number {
  const index = Math.max(0, Math.min(7, Math.floor(Number(lockedSubstats) || 0)))
  return MODULE_REROLL_COSTS_BY_LOCKED_SUBSTATS[index] ?? 0
}

export const MODULE_SHARD_COSTS: number[] = Array.from(
  { length: MODULE_COST_TABLE_LENGTH - 1 },
  (_, index) => getModuleShardUpgradeCost(index + 2),
)

export const MODULE_COIN_COSTS: number[] = Array.from(
  { length: MODULE_COST_TABLE_LENGTH - 1 },
  (_, index) => getModuleCoinUpgradeCost(index + 2),
)

export type ModuleCostRoundingMode = 'round' | 'ceil' | 'floor'

function clampDiscountPercent(value: number): number {
  if (!Number.isFinite(value)) return 0
  return Math.max(0, Math.min(100, Math.floor(value)))
}

function applyRounding(value: number, roundingMode: ModuleCostRoundingMode): number {
  if (roundingMode === 'ceil') return Math.ceil(value)
  if (roundingMode === 'floor') return Math.floor(value)
  return Math.round(value)
}

export function buildDiscountedModuleCosts(
  costs: readonly number[],
  discountPercent: number,
  roundingMode: ModuleCostRoundingMode = 'round',
): number[] {
  const mult = 1 - (clampDiscountPercent(discountPercent) / 100)
  return costs.map(cost => Math.max(0, applyRounding(Number(cost || 0) * mult, roundingMode)))
}

export function buildModuleCostPrefix(costs: readonly number[]): number[] {
  const prefix: number[] = []
  let acc = 0
  for (let index = 0; index < costs.length; index += 1) {
    acc += Number(costs[index] || 0)
    prefix.push(acc)
  }
  return prefix
}

export function sumModuleCostsBetweenWithRounding(
  costs: readonly number[],
  fromLevel: number,
  toLevel: number,
  discountPercent: number,
  roundingMode: ModuleCostRoundingMode = 'round',
): number {
  const from = Math.max(1, Math.floor(Number(fromLevel) || 1))
  const to = Math.max(1, Math.floor(Number(toLevel) || 1))
  if (to <= from) return 0

  const discounted = buildDiscountedModuleCosts(costs, discountPercent, roundingMode)
  const prefix = buildModuleCostPrefix(discounted)
  const leftIndex = from - 2
  const rightIndex = to - 2
  const left = leftIndex >= 0 ? (prefix[leftIndex] || 0) : 0
  const right = rightIndex >= 0 ? (prefix[rightIndex] || 0) : 0
  return Math.max(0, right - left)
}

export function sumModuleCostsBetween(
  costs: readonly number[],
  fromLevel: number,
  toLevel: number,
  discountPercent: number,
): number {
  return sumModuleCostsBetweenWithRounding(costs, fromLevel, toLevel, discountPercent, 'round')
}

export function sumModuleShardCostsBetween(fromLevel: number, toLevel: number, discountPercent: number): number {
  return sumModuleCostsBetween(MODULE_SHARD_COSTS, fromLevel, toLevel, discountPercent)
}

export function sumModuleCoinCostsBetween(fromLevel: number, toLevel: number, discountPercent: number): number {
  return sumModuleCostsBetween(MODULE_COIN_COSTS, fromLevel, toLevel, discountPercent)
}

export interface ModuleCostRow {
  level: number
  baseCost: number
  discountedCost: number
  cumulativeCost: number
}

/**
 * The highest level a module cost table prices.
 *
 * Buying level L reads entry `L - 2` — module levels start at 1 and the first purchase is
 * level 2 — so a 299-entry table prices levels up to 300, which is the rarity cap.
 */
export function moduleCostMaxLevel(costs: readonly number[]): number {
  return costs.length + 1
}

/**
 * Per-level costs between two module levels, stopping at the last level the table prices.
 *
 * Both bounds matter. Without the cap, `costs[index]` past the end read as `undefined` and
 * `|| 0` turned it into a free level, so a plan running past 300 came back too cheap while
 * looking entirely normal. Without the ceiling on `to`, an unbounded target allocated a row
 * per level — two million rows from a single call.
 *
 * Totals are unchanged: the rows this drops all cost 0.
 */
export function buildModuleCostRows(
  costs: readonly number[],
  fromLevel: number,
  toLevel: number,
  discountPercent: number,
): ModuleCostRow[] {
  const from = Math.max(1, Math.floor(Number(fromLevel) || 1))
  const requestedTo = Math.max(from, Math.floor(Number(toLevel) || from))
  const to = Math.min(requestedTo, moduleCostMaxLevel(costs))
  if (to <= from) return []

  const mult = 1 - (clampDiscountPercent(discountPercent) / 100)
  const rows: ModuleCostRow[] = []
  let cumulative = 0

  for (let level = from + 1; level <= to; level += 1) {
    const index = level - 2
    const baseCost = Number(costs[index] || 0)
    const discountedCost = Math.round(baseCost * mult)
    cumulative += discountedCost
    rows.push({
      level,
      baseCost,
      discountedCost,
      cumulativeCost: cumulative,
    })
  }

  return rows
}


/**
 * Shards to raise a module one rarity step.
 *
 * Three steps, so three costs. This was declared in a module that otherwise builds select
 * options -- a price the game charges, living in a file about dropdowns, which is why two
 * calculator pages imported a UI module to find out what an upgrade costs.
 */
export const MODULE_RARITY_STEP_COSTS = [1000, 1200, 1400] as const
