/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    computeBossWaveInterval, BOSS_WAVE_INTERVAL_BY_TIER, EnemyDropsRoiBuildContext, FetchResourceBreakdown, EnemyDropsRoiRow, EnemyDropsSimulationResult, computeEnemyDropsNormalizedRoiPct, fetchUpgradeAtLevel (+15 more)
 * depends    src/data, src/data/currency/data, src/data/enemies/data, src/mechanics/enemies/drops-context, src/mechanics/enemies/drops-game-data, src/mechanics/enemies/drops-shared (+3 more)
 * used by    src/mechanics/calculators/specs-generated, src/mechanics/enemies/elite-spawn-chance, src/mechanics/enemies/index, src/mechanics/resource-drops/coin-fetch, src/mechanics/resource-drops/coin-simulation-types, src/mechanics/resource-drops/enemy-drop-roi (+2 more)
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
import { MAX_CAMPAIGN_TIER } from '../../data'
import { ELITE_CELL_TIER_FACTS } from '../../data/currency/data'
import { type FetchUpgrade, guardianUpgrades } from '../../data'
import {
  FETCH_LOOT_OUTCOME_WEIGHTS,
  getEnemyDropsLabBenefits,
  getFetchRerollShardCount,
  getShatterShards,
} from './drops-game-data'
import {
  type LabProgressModifiers,
} from '../../data'
import { DEFAULT_BOSS_WAVE_INTERVAL } from '../../data/enemies/data'
import { clamp } from '../primitives/math'
import {
  computeBossWaveIntervalFromTier,
  type EnemyDropsSimulationInput,
  type EnemyDropsWaveContext,
  type EnemyDropsYieldBreakdown,
} from './drops-shared'
import { computeEconomyScaledRoiPct } from '../planning/roi-scaling'
import { buildWaveContext } from './drops-wave-context'

export { DEFAULT_BOSS_WAVE_INTERVAL } from '../../data/enemies/data'

export {
  WAVE_SKIP_SKIPPED_WAVE_MULT,
  waveSkipExpectedSkipsPerProc,
  averageEliteCellsPerKill,
  avgEliteKillsPerWaveFromMastery,
  cellsPerKillBonusMult,
  waveSkipResourceMultiplier,
  buildWaveContext,
} from './drops-wave-context'

export function computeBossWaveInterval(wavesPerBoss: number | null | undefined): number {
  const parsed = Math.floor(Number(wavesPerBoss))
  if (!Number.isFinite(parsed) || parsed <= 0) return DEFAULT_BOSS_WAVE_INTERVAL
  return clamp(parsed, 1, 10)
}

// computeBossWaveIntervalFromTier now lives in ./drops-shared (leaf); re-exported
// for external consumers that import it from here.
export { computeBossWaveIntervalFromTier } from './drops-shared'

/** Boss spawn interval (waves per boss) for tiers 1–24. */
export const BOSS_WAVE_INTERVAL_BY_TIER: readonly number[] = Array.from({ length: MAX_CAMPAIGN_TIER + 1 }, (_, tier) =>
  tier < 1 ? 0 : computeBossWaveIntervalFromTier(tier),
)

// EnemyDropsSimulationInput / EnemyDropsWaveContext now live in ./drops-shared
// (leaf) so the drops trio no longer imports each other; re-exported for external
// consumers that import them from here.
export type { EnemyDropsSimulationInput, EnemyDropsWaveContext, EnemyDropsYieldBreakdown } from './drops-shared'

export interface EnemyDropsRoiBuildContext {
  labsEconomy?: LabProgressModifiers
  workshopUtilityDiscountPct?: number
  workshopVaultDiscountPct?: number
}

export interface FetchResourceBreakdown {
  expectedProcs: number
  gems: number
  medals: number
  rerollShards: number
  moduleShards: number
  cannonShards: number
  armorShards: number
  generatorShards: number
  coreShards: number
  commonModules: number
  rareModules: number
}

export interface EnemyDropsRoiRow {
  id: string
  label: string
  category: string
  level: number
  nextLevel: number
  costLabel: string
  marginalGain: number
  roi: number
  totalYieldAtLevel: number
}

export interface EnemyDropsSimulationResult {
  context: EnemyDropsWaveContext
  cells: EnemyDropsYieldBreakdown
  shards: EnemyDropsYieldBreakdown
  fetch: FetchResourceBreakdown
}

/** Normalized ROI % — relative yield gain per unit cost, economy-scaled by reference cost. */
export function computeEnemyDropsNormalizedRoiPct(
  marginalGain: number,
  currentTotal: number,
  cost: number,
  referenceCost: number,
): number {
  if (!Number.isFinite(marginalGain) || marginalGain <= 0) return 0
  const relativeImprovement = currentTotal > 0 ? marginalGain / currentTotal : marginalGain
  if (!Number.isFinite(cost) || cost <= 0) return relativeImprovement * 100
  return computeEconomyScaledRoiPct(relativeImprovement, cost, referenceCost)
}

function parsePercent(value: string | null | undefined): number {
  if (!value) return 0
  const match = value.match(/([\d.]+)\s*%/)
  if (!match) return 0
  return Number.parseFloat(match[1]) / 100
}

function parseCooldownSeconds(value: string | null | undefined): number {
  if (!value) return 120
  const match = value.match(/([\d.]+)\s*s/)
  if (!match) return 120
  return Number.parseFloat(match[1])
}

export function fetchUpgradeAtLevel(level: number): FetchUpgrade {
  const rows = guardianUpgrades.fetch
  const idx = clamp(Math.floor(level), 1, rows.length) - 1
  return rows[idx] ?? rows[0]
}

/** Fetch find-chance proc model — each proc rolls one loot table entry. */
export function simulateFetchDrops(input: EnemyDropsSimulationInput): FetchResourceBreakdown {
  const ctx = buildWaveContext(input)
  const labs = getEnemyDropsLabBenefits(input)

  const cdRow = fetchUpgradeAtLevel(input.fetchCooldownLevel)
  const findRow = fetchUpgradeAtLevel(input.fetchFindChanceLevel)
  const doubleRow = fetchUpgradeAtLevel(input.fetchDoubleFindLevel)

  const cooldownSec = parseCooldownSeconds(cdRow.cooldown)
  const findChance = parsePercent(findRow.findChance)
  const doubleChance = parsePercent(doubleRow.doubleFindChance)

  const attempts = ctx.targetWave * clamp(input.averageWaveSeconds, 1, 600) / Math.max(1, cooldownSec)
  const expectedProcs = attempts * findChance * (1 + doubleChance)

  const commonModules = expectedProcs * FETCH_LOOT_OUTCOME_WEIGHTS.commonModule
  const rareModules = expectedProcs * FETCH_LOOT_OUTCOME_WEIGHTS.rareModule
  const cannonShards = expectedProcs * FETCH_LOOT_OUTCOME_WEIGHTS.cannonShard
  const armorShards = expectedProcs * FETCH_LOOT_OUTCOME_WEIGHTS.armorShard
  const generatorShards = expectedProcs * FETCH_LOOT_OUTCOME_WEIGHTS.generatorShard
  const coreShards = expectedProcs * FETCH_LOOT_OUTCOME_WEIGHTS.coreShard
  const directModuleShards = cannonShards + armorShards + generatorShards + coreShards

  const commonShatterYield = getShatterShards('common', labs.shatterBenefit)
  const rareShatterYield = getShatterShards('rare', labs.shatterBenefit)

  let moduleShards = directModuleShards
  if (input.shatterCommonModules) moduleShards += commonModules * commonShatterYield
  if (input.shatterRareModules) moduleShards += rareModules * rareShatterYield

  const fetchRerollPerProc = getFetchRerollShardCount(ctx.tier, labs.rerollShardsBenefit)

  return {
    expectedProcs,
    gems: expectedProcs * FETCH_LOOT_OUTCOME_WEIGHTS.gems,
    medals: expectedProcs * FETCH_LOOT_OUTCOME_WEIGHTS.medals,
    rerollShards: expectedProcs * FETCH_LOOT_OUTCOME_WEIGHTS.rerollShards * fetchRerollPerProc,
    moduleShards,
    cannonShards,
    armorShards,
    generatorShards,
    coreShards,
    commonModules,
    rareModules,
  }
}

export const ENEMY_DROPS_MECHANICS_NOTES = [
  ...ELITE_CELL_TIER_FACTS,
  'Module drop chances: common/rare drop formulas (labBenefit × 0.01 + base).',
  'Boss reroll shards: 15% proc × (tier table + round(reroll_shards lab)) reroll shard drop rules.',
  'Shatter yields: floor(shatter_shards lab / 100 × scale) + constant per GetShatterShards rarity branch.',
  'Wave Skip grants skipped-wave enemy value at ×1.10; multi-skip distribution from community chart data.',
  'Fetch loot weights from in-game Drop Table UI (GiveFetchReward); daily caps not modeled in EV sim yet.',
] as const


export {
  getShatterShards,
  getCommonModuleDropChance,
  getRareModuleDropChance,
} from './drops-game-data'

export { computeTierNumber } from './drops-context'
