/**
 * Leaf module for symbols shared across the enemy-drops trio
 * (`drops-simulation`, `drops-context`, `drops-wave-context`). Keeping these
 * here — rather than in any one of the three — is what stops them importing
 * each other in a cycle. Nothing here may import from those three modules.
 */
/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    clampCardGameLevel, clampCardMasteryLevel, computeBossWaveIntervalFromTier, EnemyDropsSimulationInput, EnemyDropsWaveContext, EnemyDropsYieldBreakdown
 * depends    src/data/enemies/data
 * used by    src/mechanics/calculators/specs-generated, src/mechanics/enemies/drops-context, src/mechanics/enemies/drops-simulation, src/mechanics/enemies/drops-wave-context, src/mechanics/resource-drops/accumulate-wave-econ, src/mechanics/resource-drops/enemy-drop-roi
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
import { bossWaveIntervalForTier } from '../../data/enemies/data'

/** Clamp a game card level to its valid 1–7 range. */
export function clampCardGameLevel(level: number | undefined, fallback = 1): number {
  const parsed = Number.isFinite(level) ? Math.floor(Number(level)) : fallback
  if (parsed <= 0) return 1
  return Math.min(7, Math.max(1, parsed))
}

/** Clamp a card mastery level to its valid 0–9 range. */
export function clampCardMasteryLevel(level: number | undefined, fallback = 0): number {
  const parsed = Number.isFinite(level) ? Math.floor(Number(level)) : fallback
  return Math.min(9, Math.max(0, parsed))
}

/** Boss spawn interval (every N waves) for a campaign tier. */
export function computeBossWaveIntervalFromTier(tier: number): number {
  return bossWaveIntervalForTier(tier)
}

export interface EnemyDropsSimulationInput {
  tier: number
  targetWave: number
  /** Game card levels 1–7. */
  enemyBalanceCardLevel: number
  enemyBalanceMasteryLevel: number
  waveSkipCardLevel: number
  waveSkipMasteryLevel: number
  commonDropLabLevel: number
  rareDropLabLevel: number
  rerollShardsLabLevel: number
  shatterShardsLabLevel: number
  deathWaveCellsBonusLevel: number
  cellsPerKillBonusLevel: number
  shatterCommonModules: boolean
  shatterRareModules: boolean
  fetchCooldownLevel: number
  fetchFindChanceLevel: number
  fetchDoubleFindLevel: number
  /** Boss spawn interval (every N waves) — affects boss module/reroll yields only. */
  wavesPerBoss: number
  averageWaveSeconds: number
}

export interface EnemyDropsWaveContext {
  tier: number
  targetWave: number
  enemyBalanceMult: number
  waveSkipSkipChance: number
  waveSkipExpectedSkipsPerProc: number
  waveSkipMasteryDoubleChance: number
  avgEliteCellDropsPerKill: number
  avgEliteKillsPerWave: number
  cellsPerKillMult: number
  bossCount: number
  waveSkipResourceMult: number
}

export interface EnemyDropsYieldBreakdown {
  cellsFromElites: number
  cellsFromWaveSkip: number
  totalCells: number
  moduleShardsFromDrops: number
  moduleShardsFromShatter: number
  totalModuleShards: number
  rerollShardsFromBosses: number
  commonModulesDropped: number
  rareModulesDropped: number
}
