/**
 * v29 fleet research labs - effects on wave/econ simulation inputs.
 *
 * HP/damage reduction labs (242-245) wire through `wave-info-labs.ts`.
 * These three labs modify fleet *behavior* (exponent, aura radius, saboteur speed).
 *
 * Benefit curves (owner-verified percentage points; catalog base/value):
 * - overcharge_exponent_reducer: 40 - 0.5*level -> exponent = 1 + benefit/100 (L0 -> 1.4)
 * - commander_radius: 0 + 1*level -> radius scale *= (1 + benefit/100)
 * - saboteur_attack_speed: 0 + 2*level -> speed mult *= (1 + benefit/100)
 */
/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    OVERCHARGE_EXPONENT_REDUCER_BASE_PCT, OVERCHARGE_EXPONENT_REDUCER_PER_LEVEL_PCT, COMMANDER_RADIUS_BASE_PCT, COMMANDER_RADIUS_PER_LEVEL_PCT, SABOTEUR_ATTACK_SPEED_BASE_PCT, SABOTEUR_ATTACK_SPEED_PER_LEVEL_PCT, FLEET_ENEMY_LAB_BENEFIT_PER_LEVEL, WAVE_INFO_FLEET_ENEMY_LAB_SLUGS (+6 more)
 * depends    src/data/enemies/data
 * used by    src/mechanics/calculators/specs-generated, src/mechanics/enemies/index
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
import {
  COMMANDER_BUFF_RADIUS_BASE_SCALE,
  OVERCHARGE_ATTACK_EXPONENT_BASE,
} from '../../data/enemies/data'

export const OVERCHARGE_EXPONENT_REDUCER_BASE_PCT = 40 as const
export const OVERCHARGE_EXPONENT_REDUCER_PER_LEVEL_PCT = -0.5 as const
export const COMMANDER_RADIUS_BASE_PCT = 0 as const
export const COMMANDER_RADIUS_PER_LEVEL_PCT = 1 as const
export const SABOTEUR_ATTACK_SPEED_BASE_PCT = 0 as const
export const SABOTEUR_ATTACK_SPEED_PER_LEVEL_PCT = 2 as const

/** @deprecated Use OVERCHARGE_EXPONENT_REDUCER_PER_LEVEL_PCT; was a placeholder -0.4. */
export const FLEET_ENEMY_LAB_BENEFIT_PER_LEVEL = 0.4 as const

export const WAVE_INFO_FLEET_ENEMY_LAB_SLUGS = {
  Overcharge: { health: 'overcharge_enemy_health', attack: 'overcharge_enemy_damage' },
  Commander: { health: 'commander_enemy_health' },
  Saboteur: { health: 'saboteur_enemy_health' },
} as const

export function overchargeExponentReducerBenefitPct(reducerLabLevel: number): number {
  const level = Math.max(0, Math.floor(Number(reducerLabLevel) || 0))
  return OVERCHARGE_EXPONENT_REDUCER_BASE_PCT + OVERCHARGE_EXPONENT_REDUCER_PER_LEVEL_PCT * level
}

/**
 * Overcharge volley exponent after `overcharge_exponent_reducer` lab levels.
 * L0 = OVERCHARGE_ATTACK_EXPONENT_BASE (1.4); each level -0.5pp on the 40% addend.
 */
export function overchargeAttackExponentAfterLab(reducerLabLevel: number): number {
  const benefitPct = overchargeExponentReducerBenefitPct(reducerLabLevel)
  return Math.max(1, 1 + benefitPct / 100)
}

export function commanderRadiusBenefitPct(radiusLabLevel: number): number {
  const level = Math.max(0, Math.floor(Number(radiusLabLevel) || 0))
  return COMMANDER_RADIUS_BASE_PCT + COMMANDER_RADIUS_PER_LEVEL_PCT * level
}

export function commanderBuffRadiusScaleAfterLab(radiusLabLevel: number): number {
  return COMMANDER_BUFF_RADIUS_BASE_SCALE * (1 + commanderRadiusBenefitPct(radiusLabLevel) / 100)
}

export function saboteurAttackSpeedBenefitPct(attackSpeedLabLevel: number): number {
  const level = Math.max(0, Math.floor(Number(attackSpeedLabLevel) || 0))
  return SABOTEUR_ATTACK_SPEED_BASE_PCT + SABOTEUR_ATTACK_SPEED_PER_LEVEL_PCT * level
}

export function saboteurSpeedMultAfterLab(attackSpeedLabLevel: number): number {
  const baseSaboteurSpeedMult = 2
  return baseSaboteurSpeedMult * (1 + saboteurAttackSpeedBenefitPct(attackSpeedLabLevel) / 100)
}

