/**
 * Run-header enemy HP/damage display modifiers from trade-off perks and labs.
 *
 * Wave Info page perks are applied in `enemy-wave-info-pipeline.ts`.
 */
/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    ENEMY_HEADER_PERK_INDICES, IMPROVE_TRADE_OFF_PERKS_LAB_INDEX, TRADE_OFF_ENEMY_HP_BENEFIT_BASE, TRADE_OFF_ENEMY_DMG_BENEFIT_BASE, TRADE_OFF_SPEED_DMG_MULTIPLIER, TRADE_OFF_RANGED_DMG_MULTIPLIER, TRADE_OFF_BOSS_HP_DOWN_MULT, TRADE_OFF_BOSS_HP_X8_UP_BASE (+25 more)
 * depends    src/mechanics/enemies/wave-stats, src/mechanics/primitives/math
 * used by    src/mechanics/calculators/specs-generated, src/mechanics/enemies/index, src/mechanics/enemies/stats-simplified, src/mechanics/enemies/wave-info-pipeline, src/mechanics/enemies/wave-panel
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */

import type { EnemyWaveEnemyType } from './wave-stats'
import { clamp } from '../primitives/math'

/** Trade-off perk indices for common enemy header stats. */
export const ENEMY_HEADER_PERK_INDICES = {
  enemyHpTradeOff: 42,
  enemyAttackTradeOffUp: 43,
  rangedAttackTradeOffDown: 44,
  enemyAttackTradeOffDown: 45,
  bossHpTradeOffDown: 40,
  bossHpTradeOffUp: 48,
} as const

/** Improve Trade-off Perks lab — `Lab.researchBenefit[88]` scales `PerkBenefitUp`. */
export const IMPROVE_TRADE_OFF_PERKS_LAB_INDEX = 88

/** `perkBenefitUpBase` @ improve-lab 0 for trade-off perks scaled by improve lab. */
export const TRADE_OFF_ENEMY_HP_BENEFIT_BASE = 0.5
export const TRADE_OFF_ENEMY_DMG_BENEFIT_BASE = 0.5
export const TRADE_OFF_SPEED_DMG_MULTIPLIER = 2.5
export const TRADE_OFF_RANGED_DMG_MULTIPLIER = 3
export const TRADE_OFF_BOSS_HP_DOWN_MULT = 0.3
/** Boss HP ×8 perk base — `1 − (−7) = 8`. */
export const TRADE_OFF_BOSS_HP_X8_UP_BASE = -7

/** Pre-perk wave base damage on the run-header path. */
export function waveBaseDamageForHeader(getWaveBaseDamage: number): number {
  if (!Number.isFinite(getWaveBaseDamage) || getWaveBaseDamage <= 0) return 0
  return Math.floor(getWaveBaseDamage)
}

/** Known gaps vs full in-run spawn paths. */
export const ENEMY_STAT_DISPLAY_GAPS = [
  'Ranged ×3 on spawn path, not Basic run-header damage',
  'Boss ×8 simplified as flat ×8 when toggle on',
  'Perk benefit tables not fully modeled from static perk init data',
] as const

/** Common trade-off loadout: all perks on except Enemies/Tower −50% damage. */
export function tradeOffPresetAllExceptEnemyDmgMinus50(): EnemyHeaderPerkToggles {
  return {
    perkEnemyHpMinus50: true,
    perkBossHpX8: true,
    perkBossHpMinus70: true,
    perkEnemyDmgMinus50: false,
    perkEnemyDmgX25: true,
    perkRangedDmgX3: true,
  }
}

export interface PerkBenefitTables {
  upBase: readonly number[]
  upIncrease: readonly number[]
  down: readonly number[]
  perkLevel: readonly number[]
}

export interface PerkBenefitUpInput {
  index: number
  tables: PerkBenefitTables
  /** `1 + Lab.researchBenefit[IMPROVE_TRADE_OFF_PERKS_LAB_INDEX]` (default 1). */
  tradeOffImproveMult?: number
  /** `PerkBenefitUp(index, onlyOneLevel)` — header uses `false`. */
  onlyOneLevel?: boolean
}

/**
 * `Perks.PerkBenefitUp` (default header path, `onlyOneLevel = false`).
 *
 *   sum = (upBase[i] + upIncrease[i] × perkLevel[i]) × tradeOffImproveMult
 *   return 1 − sum
 */
export function perkBenefitUp(input: PerkBenefitUpInput): number {
  const { index, tables, tradeOffImproveMult = 1, onlyOneLevel = false } = input
  const level = Math.max(0, Math.floor(tables.perkLevel[index] ?? 0))
  if (level < 1) return 1

  const base = tables.upBase[index]
  if (!Number.isFinite(base)) return 1
  const increase = tables.upIncrease[index] ?? 0

  const levelFactor = onlyOneLevel ? 1 : level
  const sum = (base + increase * levelFactor) * tradeOffImproveMult
  return clamp(1 - sum, 0, Number.MAX_SAFE_INTEGER)
}

/** `Perks.PerkBenefitDown` — returns the stored down benefit directly. */
export function perkBenefitDown(index: number, tables: Pick<PerkBenefitTables, 'down' | 'perkLevel'>): number {
  const level = Math.max(0, Math.floor(tables.perkLevel[index] ?? 0))
  if (level < 1) return 1

  const value = tables.down[index]
  return Number.isFinite(value) ? value : 1
}

/** UI toggle → active trade-off perk level (0 or 1). */
export interface EnemyHeaderPerkToggles {
  perkEnemyHpMinus50: boolean
  perkBossHpX8: boolean
  perkBossHpMinus70: boolean
  perkEnemyDmgMinus50: boolean
  perkEnemyDmgX25: boolean
  perkRangedDmgX3: boolean
}

/** Wave Info boss HP divisor improve rate — `Lab.researchBenefitIncrease[88]` f32 per level. */
export const WAVE_INFO_BOSS_HP_DIVISOR_IMPROVE_RATE_PER_LEVEL = Math.fround(0.0119794)

/** @deprecated Use {@link WAVE_INFO_BOSS_HP_DIVISOR_IMPROVE_RATE_PER_LEVEL} with `F32(rate)×F32(labLevel)`. */
export const WAVE_INFO_BOSS_HP_TRADE_OFF_DIVISOR_IMPROVE_SCALE =
  WAVE_INFO_BOSS_HP_DIVISOR_IMPROVE_RATE_PER_LEVEL / 0.01

/** Boss HP Enemy HP −50% divisor — `0.5 × (1 + F32(scaledPct)/100)`. */
export function waveInfoBossTradeOffDivisorBenefit(baseBenefit: number, improveLabLevel: number): number {
  const F32 = Math.fround
  const level = Math.max(0, improveLabLevel)
  const scale = F32(WAVE_INFO_BOSS_HP_DIVISOR_IMPROVE_RATE_PER_LEVEL / 0.01)
  const scaledPct = F32(F32(level) * scale)
  const improveMult = F32(F32(1) + F32(F32(scaledPct) / F32(100)))
  return F32(F32(baseBenefit) * improveMult)
}

/** Boss Wave Info HP page-perk mult — f32 chain (HP up → boss down → boss up perks). */
export function waveInfoBossHpPagePerkMultiplier(input: {
  toggles: EnemyHeaderPerkToggles
  improveTradeOffLabPct?: number
  tables: PerkBenefitTables
  /** Boss workshop mult already applied in type rules — for boss-trade-off + HP perk alignment. */
  bossWorkshopMult?: number
}): number {
  const improvePct = Math.max(0, input.improveTradeOffLabPct ?? 0)
  const improveMult = tradeOffImproveMultFromLabPercent(improvePct)
  const F32 = Math.fround
  let hp = F32(1)

  if (input.toggles.perkEnemyHpMinus50) {
    hp = F32(hp * F32(perkBenefitUp({
      index: ENEMY_HEADER_PERK_INDICES.enemyHpTradeOff,
      tables: input.tables,
      tradeOffImproveMult: improveMult,
    })))
  }
  if (input.toggles.perkBossHpMinus70) {
    hp = F32(hp * F32(perkBenefitDown(ENEMY_HEADER_PERK_INDICES.bossHpTradeOffDown, input.tables)))
  }
  if (input.toggles.perkBossHpX8) {
    hp = F32(hp * F32(perkBenefitUp({
      index: ENEMY_HEADER_PERK_INDICES.bossHpTradeOffUp,
      tables: input.tables,
    })))
  }

  // Boss HP trade-offs pair with Enemy HP −% via improve-lab scaled divisor.
  if (input.toggles.perkBossHpX8 || input.toggles.perkBossHpMinus70) {
    const divisor = waveInfoBossTradeOffDivisorBenefit(TRADE_OFF_ENEMY_HP_BENEFIT_BASE, improvePct)
    if (divisor > 0) {
      hp = F32(hp / F32(divisor))
    }
    // Game boss/sab with boss trade-offs + Enemy HP −% uses hp perk on ×20 (Sab path), not wm×hp on body.
    if (input.toggles.perkEnemyHpMinus50 && input.bossWorkshopMult != null && input.bossWorkshopMult > 0) {
      const hpPerk = F32(perkBenefitUp({
        index: ENEMY_HEADER_PERK_INDICES.enemyHpTradeOff,
        tables: input.tables,
        tradeOffImproveMult: improveMult,
      }))
      hp = F32(hp * F32(F32(hpPerk) / F32(input.bossWorkshopMult)))
    }
  }

  return hp
}

/** `1 + Lab.researchBenefit[88]` from improve trade-off perks lab. */
export function tradeOffImproveMultFromLabPercent(improveTradeOffPct: number): number {
  return 1 + Math.max(0, improveTradeOffPct) / 100
}

/** `PerkBenefitUp` benefit fraction after improve lab — HP/damage trade-off perks only. */
export function tradeOffUpBenefitAtLab(baseBenefit: number, improveLabPct: number): number {
  return baseBenefit * tradeOffImproveMultFromLabPercent(improveLabPct)
}

export function formatHeaderPerkMultiplier(mult: number): string {
  if (!Number.isFinite(mult) || Math.abs(mult - 1) < 0.0005) return '1.00'
  return mult.toFixed(2)
}

export interface TradeOffPerkLabels {
  enemyHpMinus50: string
  enemyDmgMinus50: string
  enemyDmgX25: string
  rangedDmgX3: string
  bossHpX8: string
  bossHpMinus70: string
}

/** Switch labels — only PerkBenefitUp perks (HP/dmg −%) scale with improve lab. */
export function enemyHeaderTradeOffLabels(improveLabPct: number): TradeOffPerkLabels {
  const fmtPct = (n: number) => (Math.round(n * 10) / 10).toFixed(1)
  const hpPct = tradeOffUpBenefitAtLab(TRADE_OFF_ENEMY_HP_BENEFIT_BASE, improveLabPct) * 100
  const dmgPct = tradeOffUpBenefitAtLab(TRADE_OFF_ENEMY_DMG_BENEFIT_BASE, improveLabPct) * 100
  return {
    enemyHpMinus50: `Enemy HP −${fmtPct(hpPct)}%`,
    enemyDmgMinus50: `Enemies Damage −${fmtPct(dmgPct)}%`,
    enemyDmgX25: `Enemies Damage ×${TRADE_OFF_SPEED_DMG_MULTIPLIER.toFixed(2)}`,
    rangedDmgX3: `Ranged Damage ×${TRADE_OFF_RANGED_DMG_MULTIPLIER.toFixed(2)}`,
    bossHpX8: 'Boss HP ×8.00',
    bossHpMinus70: `Boss HP −${((1 - TRADE_OFF_BOSS_HP_DOWN_MULT) * 100).toFixed(0)}%`,
  }
}

export function buildHeaderPerkTablesFromToggles(
  toggles: EnemyHeaderPerkToggles,
): PerkBenefitTables {
  const upBase: number[] = []
  const upIncrease: number[] = []
  const down: number[] = []
  const perkLevel: number[] = []

  const setPerk = (index: number, base: number, increase = 0, downValue = 0, active = false) => {
    upBase[index] = base
    upIncrease[index] = increase
    down[index] = downValue
    perkLevel[index] = active ? 1 : 0
  }

  setPerk(ENEMY_HEADER_PERK_INDICES.enemyHpTradeOff, TRADE_OFF_ENEMY_HP_BENEFIT_BASE, 0, 0, toggles.perkEnemyHpMinus50)
  setPerk(ENEMY_HEADER_PERK_INDICES.enemyAttackTradeOffUp, TRADE_OFF_ENEMY_DMG_BENEFIT_BASE, 0, 0, toggles.perkEnemyDmgMinus50)
  setPerk(ENEMY_HEADER_PERK_INDICES.enemyAttackTradeOffDown, 0, 0, TRADE_OFF_SPEED_DMG_MULTIPLIER, toggles.perkEnemyDmgX25)
  setPerk(ENEMY_HEADER_PERK_INDICES.bossHpTradeOffDown, 0, 0, TRADE_OFF_BOSS_HP_DOWN_MULT, toggles.perkBossHpMinus70)
  setPerk(
    ENEMY_HEADER_PERK_INDICES.bossHpTradeOffUp,
    TRADE_OFF_BOSS_HP_X8_UP_BASE,
    0,
    0,
    toggles.perkBossHpX8,
  )
  setPerk(ENEMY_HEADER_PERK_INDICES.rangedAttackTradeOffDown, 0, 0, TRADE_OFF_RANGED_DMG_MULTIPLIER, toggles.perkRangedDmgX3)

  return { upBase, upIncrease, down, perkLevel }
}

export interface EnemyHeaderDisplayInput {
  enemyType: string
  toggles: EnemyHeaderPerkToggles
  improveTradeOffLabPct?: number
  /** @deprecated Prefer `improveTradeOffLabPct`. */
  tradeOffImproveMult?: number
}

function resolveTradeOffImprove(input: EnemyHeaderDisplayInput): number {
  if (input.improveTradeOffLabPct != null && Number.isFinite(input.improveTradeOffLabPct)) {
    return tradeOffImproveMultFromLabPercent(Math.max(0, input.improveTradeOffLabPct))
  }
  return input.tradeOffImproveMult ?? 1
}

export interface EnemyHeaderDisplayMultipliers {
  hp: number
  damage: number
}

function anyTradeOffPerkEnabled(toggles: EnemyHeaderPerkToggles): boolean {
  return toggles.perkEnemyHpMinus50
    || toggles.perkBossHpX8
    || toggles.perkBossHpMinus70
    || toggles.perkEnemyDmgMinus50
    || toggles.perkEnemyDmgX25
    || toggles.perkRangedDmgX3
}

/** Boss / Ranged trade-offs are applied per enemy row, not on the Wave Base row. */
export function stripEnemySpecificPerkToggles(
  toggles: EnemyHeaderPerkToggles,
): EnemyHeaderPerkToggles {
  return {
    ...toggles,
    perkBossHpX8: false,
    perkBossHpMinus70: false,
    perkRangedDmgX3: false,
  }
}

/** Global Wave Info page perks (Enemy HP −%, Enemies Damage −%, ×2.5) — Wave Base row. */
export function waveInfoGlobalPagePerkMultipliers(input: {
  toggles: EnemyHeaderPerkToggles
  improveTradeOffLabPct?: number
}): EnemyHeaderDisplayMultipliers {
  return waveInfoPagePerkMultipliers({
    enemyType: 'Basic',
    toggles: stripEnemySpecificPerkToggles(input.toggles),
    improveTradeOffLabPct: input.improveTradeOffLabPct,
  })
}

export function waveInfoPagePerkMultipliers(input: {
  enemyType: EnemyWaveEnemyType
  toggles: EnemyHeaderPerkToggles
  improveTradeOffLabPct?: number
  bossWorkshopMult?: number
}): EnemyHeaderDisplayMultipliers {
  const improvePct = Math.max(0, input.improveTradeOffLabPct ?? 0)
  const improveMult = tradeOffImproveMultFromLabPercent(improvePct)
  const tables = buildHeaderPerkTablesFromToggles(input.toggles)

  let hp = 1
  let damage = 1

  if (input.enemyType === 'Boss') {
    hp = waveInfoBossHpPagePerkMultiplier({
      toggles: input.toggles,
      improveTradeOffLabPct: improvePct,
      tables,
      bossWorkshopMult: input.bossWorkshopMult,
    })
  } else if (input.toggles.perkEnemyHpMinus50) {
    hp = perkBenefitUp({
      index: ENEMY_HEADER_PERK_INDICES.enemyHpTradeOff,
      tables,
      tradeOffImproveMult: improveMult,
    })
  } else if (anyTradeOffPerkEnabled(input.toggles)) {
    const activeReduction = perkBenefitUp({
      index: ENEMY_HEADER_PERK_INDICES.enemyHpTradeOff,
      tables: buildHeaderPerkTablesFromToggles({
        ...input.toggles,
        perkEnemyHpMinus50: true,
      }),
      tradeOffImproveMult: 1,
    })
    hp = 1 / activeReduction
  }

  const type = input.enemyType
  const usesPlainVampireDamage = type === 'Vampire'
  const usesWorkshopDamage =
    type === 'Basic'
    || type === 'Fast'
    || type === 'Tank'
    || type === 'Ranged'
    || type === 'Boss'
    || type === 'Scatter'
    || type === 'Overcharge'
    || type === 'Protector'
    || type === 'Ray'

  // Workshop damage uses table mult, then trade-off chain.
  // Enemies Damage −% is not applied on Wave Info rows (see mechanics.test).
  // When Enemy HP −% is active, the paired ×2.5 speed/damage trade-off applies even if the
  // Enemies Damage ×2.5 toggle is off — matches in-game panel (e.g. T20/W3766 Basic 376.48s).
  if (!usesPlainVampireDamage && usesWorkshopDamage && type !== 'Ranged') {
    if (input.toggles.perkEnemyHpMinus50) {
      damage *= TRADE_OFF_SPEED_DMG_MULTIPLIER
    } else if (input.toggles.perkEnemyDmgX25) {
      damage *= perkBenefitDown(ENEMY_HEADER_PERK_INDICES.enemyAttackTradeOffDown, tables)
    }
  }

  if (type === 'Ranged' && input.toggles.perkRangedDmgX3) {
    damage *= perkBenefitDown(ENEMY_HEADER_PERK_INDICES.rangedAttackTradeOffDown, tables)
  }

  return { hp, damage }
}

export function waveInfoDisplayMultipliers(
  input: EnemyHeaderDisplayInput,
): EnemyHeaderDisplayMultipliers {
  return waveInfoPagePerkMultipliers({
    enemyType: input.enemyType as EnemyWaveEnemyType,
    toggles: input.toggles,
    improveTradeOffLabPct: input.improveTradeOffLabPct,
  })
}

/**
 * Multipliers applied to wave base HP/damage for run-header display.
 */
export function enemyHeaderDisplayMultipliers(
  input: EnemyHeaderDisplayInput,
): EnemyHeaderDisplayMultipliers {
  const tables = buildHeaderPerkTablesFromToggles(input.toggles)
  const tradeOffImproveMult = resolveTradeOffImprove(input)

  let hp = perkBenefitUp({
    index: ENEMY_HEADER_PERK_INDICES.enemyHpTradeOff,
    tables,
    tradeOffImproveMult,
  })

  let damage = perkBenefitUp({
    index: ENEMY_HEADER_PERK_INDICES.enemyAttackTradeOffUp,
    tables,
    tradeOffImproveMult,
  })
  damage *= perkBenefitDown(ENEMY_HEADER_PERK_INDICES.enemyAttackTradeOffDown, tables)

  if (input.enemyType === 'Boss') {
    hp *= perkBenefitDown(ENEMY_HEADER_PERK_INDICES.bossHpTradeOffDown, tables)
    if (input.toggles.perkBossHpX8) {
      hp *= perkBenefitUp({
        index: ENEMY_HEADER_PERK_INDICES.bossHpTradeOffUp,
        tables,
      })
    }
  }

  if (input.enemyType === 'Ranged' && input.toggles.perkRangedDmgX3) {
    damage *= perkBenefitDown(ENEMY_HEADER_PERK_INDICES.rangedAttackTradeOffDown, tables)
  }

  return { hp, damage }
}
