/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    MermaidSlice, renderEpGraphMermaidSlices
 * depends    src/mechanics/ep-graph/schema
 * used by    src/mechanics/calculators/specs-generated, src/mechanics/ep-graph/index
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
import type { EpGraph, EpGraphFamily, EpGraphNodeType } from './schema'

function mermaidId(id: string): string {
  return id.replace(/[^A-Za-z0-9_]/g, '_')
}

function escapeLabel(label: string): string {
  return label.replace(/"/g, "'")
}

export interface MermaidSlice {
  name: string
  family: EpGraphFamily
  types?: EpGraphNodeType[]
  mermaid: string
}

function renderSlice(
  graph: EpGraph,
  family: EpGraphFamily,
  types: EpGraphNodeType[] | null,
  title: string,
): string {
  const nodes = Object.values(graph.nodes).filter(n => {
    if (n.family !== family) return false
    if (types && !types.includes(n.type)) return false
    return true
  })
  const ids = new Set(nodes.map(n => n.id))
  const edges = graph.edges.filter(e => ids.has(e.from) || ids.has(e.to))

  const byType = new Map<string, typeof nodes>()
  for (const n of nodes) {
    const list = byType.get(n.type) ?? []
    list.push(n)
    byType.set(n.type, list)
  }

  // Stable order: controls → hides → candidates → ids → rest
  const order: EpGraphNodeType[] = [
    'control', 'hide', 'candidate', 'ids', 'lambda', 'stat', 'display', 'path',
  ]

  const lines: string[] = [
    'flowchart LR',
    `%% ${title} · contentVersion ${graph.contentVersion} · ${graph.sheetVersion}`,
  ]

  for (const type of order) {
    const group = byType.get(type)
    if (!group?.length) continue
    lines.push(`  subgraph ${type}_${family} ["${type}"]`)
    for (const n of group.sort((a, b) => a.id.localeCompare(b.id))) {
      lines.push(`    ${mermaidId(n.id)}["${escapeLabel(n.label)}"]`)
    }
    lines.push('  end')
  }

  for (const e of edges.sort((a, b) => a.id.localeCompare(b.id))) {
    if (!ids.has(e.from) || !ids.has(e.to)) continue
    lines.push(`  ${mermaidId(e.from)} -->|${e.kind}| ${mermaidId(e.to)}`)
  }

  return `${lines.join('\n')}\n`
}

export function renderEpGraphMermaidSlices(graph: EpGraph): MermaidSlice[] {
  const families = [...new Set(Object.values(graph.nodes).map(n => n.family))]
    .sort() as EpGraphFamily[]
  const slices: MermaidSlice[] = []
  for (const family of families) {
    slices.push({
      name: family,
      family,
      mermaid: renderSlice(graph, family, null, `${family} overview`),
    })
    for (const [name, types] of [
      ['controls', ['control', 'display'] as EpGraphNodeType[]],
      ['hides', ['hide'] as EpGraphNodeType[]],
      ['candidates', ['candidate'] as EpGraphNodeType[]],
      ['ids', ['ids', 'lambda'] as EpGraphNodeType[]],
    ] as const) {
      const mermaid = renderSlice(graph, family, [...types], `${family} ${name}`)
      if (mermaid.includes('["')) {
        slices.push({ name: `${family}.${name}`, family, types: [...types], mermaid })
      }
    }
  }
  return slices
}
