/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    EpGraphValidation, validateEpGraph, collectGraphCells, isHistoricallyAllowed
 * depends    src/mechanics/ep-graph/schema
 * used by    src/mechanics/calculators/specs-generated, src/mechanics/ep-graph/build-index, src/mechanics/ep-graph/index, src/mechanics/ep-graph/mutate
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
import { cellKey, type EpGraph, type EpSourceCell } from './schema'

export interface EpGraphValidation {
  errors: string[]
  warnings: string[]
}

/** Structural validation (orphans, provenance already in Zod). */
export function validateEpGraph(graph: EpGraph): EpGraphValidation {
  const errors: string[] = []
  const warnings: string[] = []
  const nodeIds = new Set(Object.keys(graph.nodes))

  for (const [id, node] of Object.entries(graph.nodes)) {
    if (node.id !== id) {
      errors.push(`node key ${id} !== node.id ${node.id}`)
    }
  }

  const edgeIds = new Set<string>()
  for (const edge of graph.edges) {
    if (edgeIds.has(edge.id)) errors.push(`duplicate edge id ${edge.id}`)
    edgeIds.add(edge.id)
    if (!nodeIds.has(edge.from)) errors.push(`edge ${edge.id} from missing ${edge.from}`)
    if (!nodeIds.has(edge.to)) errors.push(`edge ${edge.id} to missing ${edge.to}`)
  }

  // Mild cycle report (not an error — sheet graphs can loop via display).
  // Skip ControlRelation overlays that deliberately reverse or annotate the
  // formula DAG (`feeds` / `dependsOn` / `affectsPath`) and cosmetic `displays`.
  const CYCLE_SKIP = new Set(['displays', 'feeds', 'dependsOn', 'affectsPath'])
  const adj = new Map<string, string[]>()
  for (const e of graph.edges) {
    if (CYCLE_SKIP.has(e.kind)) continue
    const list = adj.get(e.from) ?? []
    list.push(e.to)
    adj.set(e.from, list)
  }
  const visiting = new Set<string>()
  const visited = new Set<string>()
  const stack: string[] = []
  const dfs = (n: string) => {
    if (visiting.has(n)) {
      warnings.push(`cycle involving ${[...stack, n].join(' -> ')}`)
      return
    }
    if (visited.has(n)) return
    visiting.add(n)
    stack.push(n)
    for (const t of adj.get(n) ?? []) dfs(t)
    stack.pop()
    visiting.delete(n)
    visited.add(n)
  }
  for (const id of nodeIds) dfs(id)

  return { errors, warnings }
}

export function collectGraphCells(graph: EpGraph): Map<string, string[]> {
  const byCell = new Map<string, string[]>()
  const add = (cell: EpSourceCell, nodeId: string) => {
    const key = cellKey(cell)
    const list = byCell.get(key) ?? []
    if (!list.includes(nodeId)) list.push(nodeId)
    byCell.set(key, list)
  }
  for (const node of Object.values(graph.nodes)) {
    for (const c of node.sourceCells ?? []) add(c, node.id)
  }
  for (const edge of graph.edges) {
    for (const c of edge.evidence.sourceCells ?? []) add(c, edge.id)
  }
  return byCell
}

export function isHistoricallyAllowed(
  graph: EpGraph,
  sheet: string,
  cell: string,
): boolean {
  return (graph.historicalAllowlist ?? []).some(
    e => e.sheet === sheet && e.cell === cell,
  )
}
