/**
 * Tables that exist to be charted.
 *
 * Rows the game publishes as a table rather than a formula — accelerator spawn rates, enemy
 * balance mastery — kept here because they are game data, while everything about DRAWING them is
 * in the `charts` domain.
 */
/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    —
 * depends    src/data/charts/data
 * used by    —
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
export * from './data'
