/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    UwLevelValue, UwStatValue, UwWeaponValue, UwStatCostRow, UwCalculatorChartRow, findUwWeaponByName, findUwStatByName, getUwStatMaxLevel (+4 more)
 * depends    —
 * used by    src/data/ultimate-weapons/index, src/data/ultimate-weapons/stones, src/internal/uptime/shared-inputs, src/mechanics/calculators/specs-generated, src/save/ultimate-weapons/read
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
export interface UwLevelValue {
  level: number
  levels?: number
  value: string | number
  cost: number | string
}

export interface UwStatValue {
  name: string
  levels: UwLevelValue[]
}

export interface UwWeaponValue {
  name: string
  stats: UwStatValue[]
  label?: string
}

export interface UwStatCostRow {
  level: number
  value: string | number
  cost: number
  cumulativeCost: number
}

export interface UwCalculatorChartRow {
  level: number
  stats: Array<string | number | ''>
  costs: number[]
  totalCost: number
}

function normalizeText(value: string): string {
  return value.trim().toLowerCase()
}

function toCost(value: number | string): number {
  const numeric = Number(value)
  if (!Number.isFinite(numeric)) return 0
  return Math.max(0, Math.floor(numeric))
}

function toLevel(value: UwLevelValue): number {
  const raw = value.level ?? value.levels
  return Math.max(0, Math.floor(Number(raw) || 0))
}

export function findUwWeaponByName(
  weapons: Record<string, UwWeaponValue> | UwWeaponValue[],
  input: string,
): UwWeaponValue | null {
  const needle = normalizeText(input)
  const list = Array.isArray(weapons) ? weapons : Object.values(weapons)

  for (const weapon of list) {
    if (!weapon?.name) continue
    const name = normalizeText(weapon.name)
    const label = normalizeText(String(weapon.label || ''))
    if (name === needle || label === needle || name.includes(needle) || (label && label.includes(needle))) {
      return weapon
    }
  }

  return null
}

export function findUwStatByName(weapon: UwWeaponValue, input: string): UwStatValue | null {
  const needle = normalizeText(input)
  for (const stat of weapon.stats || []) {
    const name = normalizeText(stat.name)
    if (name === needle || name.includes(needle)) return stat
  }
  return null
}

export function getUwStatMaxLevel(stat: UwStatValue): number {
  return (stat.levels || []).reduce((max, level) => Math.max(max, toLevel(level)), 0)
}

export function sumUwStatCostsBetween(stat: UwStatValue, startLevel: number, targetLevel: number): number {
  const from = Math.max(0, Math.floor(startLevel))
  const to = Math.max(from, Math.floor(targetLevel))
  return (stat.levels || []).reduce((sum, level) => {
    const lvl = toLevel(level)
    if (lvl > from && lvl <= to) return sum + toCost(level.cost)
    return sum
  }, 0)
}

export function sumUwAllStatCostsFromLevel(weapon: UwWeaponValue, startLevel: number): number {
  return (weapon.stats || []).reduce((sum, stat) => sum + sumUwStatCostsBetween(stat, startLevel, getUwStatMaxLevel(stat)), 0)
}

export function buildUwStatCostRows(stat: UwStatValue, startLevel: number, targetLevel: number): UwStatCostRow[] {
  const from = Math.max(0, Math.floor(startLevel))
  const to = Math.max(from, Math.floor(targetLevel))
  let cumulative = 0

  return (stat.levels || [])
    .map(level => ({
      level: toLevel(level),
      value: level.value,
      cost: toCost(level.cost),
    }))
    .filter(level => level.level > from && level.level <= to)
    .sort((left, right) => left.level - right.level)
    .map(level => {
      cumulative += level.cost
      return {
        level: level.level,
        value: level.value,
        cost: level.cost,
        cumulativeCost: cumulative,
      }
    })
}

export function buildUwCalculatorChartRows(
  stats: UwStatValue[],
  startLevels: number[],
  targetLevels: number[],
  selectedIndices: number[],
  minimumLevel: number,
): UwCalculatorChartRow[] {
  if (!stats.length) return []

  const activeIndices = selectedIndices.length > 0
    ? new Set(selectedIndices)
    : new Set(stats.map((_, index) => index))

  const statMaxLevels = stats.map((stat, index) => {
    if (!activeIndices.has(index)) return -1
    const target = targetLevels[index]
    return typeof target === 'number' && Number.isInteger(target) && target >= 0 ? target : getUwStatMaxLevel(stat)
  })

  const chartMaxLevel = statMaxLevels.reduce((max, level) => Math.max(max, level), -1)
  if (chartMaxLevel < 0) return []

  const start = Math.max(0, Math.floor(minimumLevel))
  const rows: UwCalculatorChartRow[] = []

  for (let level = start; level <= chartMaxLevel; level += 1) {
    const row: UwCalculatorChartRow = { level, stats: [], costs: [], totalCost: 0 }

    for (let index = 0; index < stats.length; index += 1) {
      if (!activeIndices.has(index) || level > statMaxLevels[index]) {
        row.stats.push('')
        row.costs.push(0)
        continue
      }

      const stat = stats[index]
      const statData = (stat.levels || []).find(candidate => candidate.level === level)
      row.stats.push(statData ? statData.value : '')

      let cost = 0
      const startLevel = startLevels[index]
      if (startLevel === -1) {
        cost = 0
      } else if (statData && level === 0) {
        cost = 0
      } else if (statData) {
        cost = Math.max(0, Math.floor(Number(statData.cost) || 0))
      }

      row.costs.push(cost)
      row.totalCost += cost
    }

    rows.push(row)
  }

  return rows
}
