/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    PlannerCitationSchema, PlannerCitation, collectPlannerCitations, compilePlannerPipeline, EmitPlannerCodegenResult, emitPlannerCodegen, emitAllPlannerCodegen
 * depends    src/internal/uptime/shared-inputs, src/mechanics/ep-graph, tooling/planner-engine/pipeline, tooling/repo-root, tooling/sdk-graph
 * used by    tooling/builders/index, tooling/planner-engine/eval, tooling/planner-engine/index
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
import fs from 'node:fs'
import path from 'node:path'
import { z } from 'zod'
import { loadEpGraph } from '../../src/mechanics/ep-graph'
import { resolveMechanicsRepoRoot } from '../repo-root'
import { loadSdkGraphWithTrust } from '../sdk-graph'
import {
  compileStructuralPlannerPipeline,
  listPlannerFamilies,
  PlannerPipelineSchema,
  type PlannerPipeline,
} from './pipeline'

export const PlannerCitationSchema = z.object({
  nodeId: z.string(),
  label: z.string(),
  formula: z.string(),
  formulaSource: z.enum(['formulatext', 'lambda', 'wiki', 'code']),
  cells: z.array(z.string()).default([]),
  lambdaName: z.string().optional(),
})
export type PlannerCitation = z.infer<typeof PlannerCitationSchema>

/** Collect oracle/graph-cited formulas only — never invent bodies. */
export function collectPlannerCitations(family: string): PlannerCitation[] {
  const ep = loadEpGraph()
  const { graph } = loadSdkGraphWithTrust({
    mode: 'degraded',
    scanPlannerCitations: false,
    checkDebugGraph: false,
  })
  const familyKey = family.startsWith('ep.') ? family : `ep.${family}`
  const alt = family.startsWith('ep.') ? family.slice(3) : family

  const nodes = [
    ...Object.values(graph.nodes).filter(n => {
      const f = String(n.family)
      return f === family || f === familyKey || f === alt || f.endsWith(`.${alt}`)
    }),
    ...Object.values(ep.nodes).filter(n => n.family === alt || n.family === family),
  ]

  const out: PlannerCitation[] = []
  const seen = new Set<string>()
  for (const n of nodes) {
    if (!n.formula || !n.formulaSource) continue
    if (seen.has(n.id)) continue
    seen.add(n.id)
    out.push({
      nodeId: n.id,
      label: n.label,
      formula: n.formula,
      formulaSource: n.formulaSource,
      cells: (n.sourceCells ?? []).map(c => `${c.sheet}!${c.cell}`),
      lambdaName: n.lambdaName,
    })
  }
  return out
}

/** Compile pipeline; upgrade steps when graph citations exist. */
export function compilePlannerPipeline(family: string): PlannerPipeline {
  const structural = compileStructuralPlannerPipeline(family)
  const citations = collectPlannerCitations(family)
  const gatesReady = citations.some(c => c.formulaSource === 'formulatext')
  const steps = structural.steps.map(step => {
    if (step.kind === 'apply-gates' && gatesReady) {
      return {
        ...step,
        status: 'ready' as const,
        note: `Gates backed by ${citations.filter(c => c.formulaSource === 'formulatext').length} FORMULATEXT citation(s)`,
        nodeIds: [...new Set([...step.nodeIds, ...citations.map(c => c.nodeId)])],
      }
    }
    if (step.kind === 'eval-costs' && citations.some(c => c.formulaSource === 'lambda' || c.lambdaName)) {
      return {
        ...step,
        status: 'ready' as const,
        note: 'Lambda citations present — hand-ported evaluators remain SoT for numeric eval',
      }
    }
    return step
  })

  return PlannerPipelineSchema.parse({
    ...structural,
    codegen: citations.length > 0 ? 'citations' : 'deferred',
    steps,
  })
}

export interface EmitPlannerCodegenResult {
  ok: boolean
  family: string
  citationCount: number
  wrote: string[]
  codegen: 'citations' | 'deferred'
}

/** Emit TypeScript citation modules from graph formulas only. */
export function emitPlannerCodegen(
  family: string,
  opts: { repoRoot?: string; outDir?: string } = {},
): EmitPlannerCodegenResult {
  const repoRoot = resolveMechanicsRepoRoot(opts.repoRoot)
  const citations = collectPlannerCitations(family)
  const familyKey = family.startsWith('ep.') ? family : `ep.${family}`
  const slug = familyKey.replace(/^ep\./, '').replace(/[^A-Za-z0-9._-]/g, '_')
  const outDir = opts.outDir
    ?? path.join(repoRoot, 'packages/sdk/tooling/planner-engine/generated')
  const docsDir = path.join(repoRoot, 'docs/mechanics-map/generated/planners')
  fs.mkdirSync(outDir, { recursive: true })
  fs.mkdirSync(docsDir, { recursive: true })

  const wrote: string[] = []
  if (citations.length === 0) {
    return { ok: true, family: familyKey, citationCount: 0, wrote, codegen: 'deferred' }
  }

  const tsPath = path.join(outDir, `${slug}.citations.ts`)
  fs.writeFileSync(
    tsPath,
    [
      '/**',
      ` * AUTO-GENERATED planner citations for ${familyKey}.`,
      ' * Source: EP/SDK graph formula + formulaSource only.',
      ` * Regenerate: pnpm planner:codegen -- --family ${slug}`,
      ' * NEVER invent formulas.',
      ' */',
      '',
      `export const PLANNER_FAMILY = ${JSON.stringify(familyKey)} as const`,
      '',
      `export const PLANNER_CITATIONS = ${JSON.stringify(citations, null, 2)} as const`,
      '',
      'export type PlannerCitation = (typeof PLANNER_CITATIONS)[number]',
      '',
    ].join('\n'),
    'utf8',
  )
  wrote.push(path.relative(repoRoot, tsPath).split(path.sep).join('/'))

  const mdPath = path.join(docsDir, `${slug}.md`)
  fs.writeFileSync(
    mdPath,
    [
      `# Planner citations — ${familyKey}`,
      '',
      `Generated citations: **${citations.length}** (graph-backed only).`,
      '',
      ...citations.flatMap(c => [
        `## \`${c.nodeId}\``,
        '',
        `- label: ${c.label}`,
        `- formulaSource: \`${c.formulaSource}\``,
        c.lambdaName ? `- lambda: \`${c.lambdaName}\`` : null,
        c.cells.length ? `- cells: ${c.cells.map(x => `\`${x}\``).join(', ')}` : null,
        '',
        '```',
        c.formula,
        '```',
        '',
      ].filter(Boolean) as string[]),
    ].join('\n'),
    'utf8',
  )
  wrote.push(path.relative(repoRoot, mdPath).split(path.sep).join('/'))

  return {
    ok: true,
    family: familyKey,
    citationCount: citations.length,
    wrote,
    codegen: 'citations',
  }
}

export function emitAllPlannerCodegen(opts: { repoRoot?: string } = {}): {
  ok: boolean
  results: EmitPlannerCodegenResult[]
} {
  const families = listPlannerFamilies()
  const results = families.map(f => emitPlannerCodegen(f, opts))
  const repoRoot = resolveMechanicsRepoRoot(opts.repoRoot)
  const outDir = path.join(repoRoot, 'packages/sdk/tooling/planner-engine/generated')
  fs.mkdirSync(outDir, { recursive: true })
  const slugs = results.filter(r => r.citationCount > 0).map(r => r.family.replace(/^ep\./, ''))
  fs.writeFileSync(
    path.join(outDir, 'index.ts'),
    [
      '/** AUTO-GENERATED planner citation index */',
      ...slugs.sort().map(s => {
        const ident = s.replace(/[^A-Za-z0-9]/g, '_')
        return `export * as ${ident} from '../../src/internal/uptime/shared-inputs'`
      }),
      '',
    ].join('\n'),
    'utf8',
  )
  return { ok: results.every(r => r.ok), results }
}
