/**
 * Tiers, and the campaign tiers that run alongside them.
 *
 * A tier is the difficulty a run is played at; a campaign tier is a separate ladder with its own
 * cap. They are filed together because a caller holding a number usually has to know which it is.
 */
/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    —
 * depends    src/data/tiers/campaign, src/data/tiers/data
 * used by    —
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
export * from './data'
export * from './campaign'
