/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    CANONICAL_LAB_SLUG_BY_ALIAS, LAB_LEVEL_TABLE_NAME_BY_SLUG, labLevelTableLookupNames, findLabCategoryForSaveIndex, findLabSlugForSaveIndex, findLabDisplayNameForSaveIndex, findLabSlugFromApiName
 * depends    src/data/labs/catalog, src/data/labs/labs, src/data/labs/research, src/support/own-lookup
 * used by    src/data/labs/display-overrides, src/data/labs/index, src/data/labs/labs, src/data/labs/research-level, src/mechanics/calculators/specs-generated
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
import { ownLookup } from '../../support/own-lookup'
import {
  findLabResearchBySlug,
  LAB_RESEARCH_SLUG_TO_INDEX,
  type LabResearchRecord,
} from './research'
import { LAB_CATALOG } from './catalog'
import { normalizeToolLabCategory } from './labs'

export const CANONICAL_LAB_SLUG_BY_ALIAS: Readonly<Record<string, string>> = {
  gold_bot_cooldown: 'golden_bot_cooldown',
  gold_bot_duration: 'golden_bot_duration',
  missile_despawn_time: 'missiles_despawn_time',
  missile_radius: 'missiles_radius',
  coins_per_wave: 'coins_wave',
  common_enemy_attack: 'basic_enemy_attack',
  common_enemy_health: 'basic_enemy_health',
  module_shards_cost: 'module_shard_cost',
  orb_boss_hit: 'orbs_boss_hit',
  super_crit_multi: 'super_crit_mult',
  swamp_rend: 'swamp_rend_basic_enemies',
  scatter_amp: 'lightning_amplifier_scatter',
  chain_lightning_shock_chance: 'shock_chance',
  chain_lightning_shock_multiplier: 'shock_multiplier',
  // `amp_bot_*` is shorthand the site used for Amplify Bot; it is not a slug in
  // the research catalog, so mapping it across is right.
  amp_bot_cooldown: 'amplify_bot_cooldown',
  amp_bot_duration: 'amplify_bot_duration',
  // `bot_bot_*` is NOT shorthand. Bot Bot and Amplify Bot are separate bots with
  // separate labs -- the catalog carries "Bot Bot - Cooldown" and "Amplify Bot -
  // Cooldown" as distinct records. Aliasing them made Bot Bot read Amplify Bot's
  // research levels, so do not add that back.
  //
  // Nor does a lab belong here just because its level table is filed under
  // another name -- see LAB_TABLE_NAME_ALIASES below. This map also decides
  // which slug a save index resolves to, and putting a table name in it made
  // two card masteries resolve to a slug the research catalog does not have,
  // which failed the import preview audit.
}

/**
 * Canonical slug -> the name its level table is filed under in the catalog.
 *
 * Distinct from CANONICAL_LAB_SLUG_BY_ALIAS, which is about which slug a *save index*
 * means. These two card masteries are only ever mispointed: the data has always
 * been there, under a different spelling. Aliased rather than renamed because
 * the table names are load-bearing elsewhere -- the AI acronym map, the chart
 * registry and the towerai knowledge base all key off them -- and "Berzerker"
 * is the spelling the card carries even where the research catalog says
 * "Berserker".
 */
const LAB_TABLE_NAME_ALIASES: Readonly<Record<string, string>> = {
  berserker_mastery: 'Berzerker Mastery',
  recovery_package_mastery: 'Recovery Package Chance Mastery',
}

/**
 * Canonical slug -> the name the generated level table happens to use.
 *
 * The level tables were generated with older names for some labs, so a lab the
 * research catalog calls `coins_wave` has its costs stored under
 * `coins_per_wave`. A lookup by the catalog slug misses, and the row comes back
 * with a real level and max but 0 for every time, gem and coin column -- which
 * reads as "this lab is free" rather than "we could not find its costs".
 *
 * Derived by inverting CANONICAL_LAB_SLUG_BY_ALIAS, plus the handful of tables filed
 * under a display name rather than a slug, so there is one list and not three.
 */
export const LAB_LEVEL_TABLE_NAME_BY_SLUG: Readonly<Record<string, string>> = {
  ...Object.fromEntries(
    Object.entries(CANONICAL_LAB_SLUG_BY_ALIAS).map(([aliasSlug, canonicalSlug]) => [canonicalSlug, aliasSlug]),
  ),
  ...LAB_TABLE_NAME_ALIASES,
}

/** Names to try, in order, when looking a lab's level table up by slug. */
export function labLevelTableLookupNames(slug: string): string[] {
  // A plain lookup put a function into this `string[]` for a slug of `constructor`.
  const alias = ownLookup(LAB_LEVEL_TABLE_NAME_BY_SLUG, slug)
  return alias && alias !== slug ? [slug, alias] : [slug]
}

const SPECIAL_SITE_LAB_LABELS: Readonly<Record<string, string>> = {
  labs_speed: 'Lab Speed',
  labs_coin_discount: 'Lab Coin Discount',
}

function slugToDisplayLabel(slug: string): string {
  const special = ownLookup(SPECIAL_SITE_LAB_LABELS, slug)
  if (special) return special
  return slug
    .replace(/_/g, ' ')
    .replace(/\b\w/g, char => char.toUpperCase())
}

function resolveCanonicalLabSlug(aliasSlug: string): string {
  return CANONICAL_LAB_SLUG_BY_ALIAS[aliasSlug] ?? aliasSlug
}

function lookupResearch(slug: string): LabResearchRecord | undefined {
  const canonical = resolveCanonicalLabSlug(slug)
  return findLabResearchBySlug(canonical) ?? findLabResearchBySlug(slug)
}

function buildLabSlugBySaveIndex(): ReadonlyMap<number, string> {
  const byIndex = new Map<number, string>()
  for (const [aliasSlug, saveSlug] of Object.entries(CANONICAL_LAB_SLUG_BY_ALIAS)) {
    const index = LAB_RESEARCH_SLUG_TO_INDEX[saveSlug]
    if (index !== undefined) byIndex.set(index, aliasSlug)
  }
  for (const [slug, index] of Object.entries(LAB_RESEARCH_SLUG_TO_INDEX)) {
    if (!byIndex.has(index)) byIndex.set(index, slug)
  }
  return byIndex
}

const LAB_SLUG_BY_SAVE_INDEX = buildLabSlugBySaveIndex()

const SITE_LAB_CATEGORY_BY_SLUG = new Map(
  LAB_CATALOG
    .filter(lab => lab.category)
    .map(lab => [lab.slug, normalizeToolLabCategory(lab.category)]),
)

export function findLabCategoryForSaveIndex(saveIndex: number): string | null {
  const aliasSlug = LAB_SLUG_BY_SAVE_INDEX.get(saveIndex)
  if (!aliasSlug) return null
  const canonical = resolveCanonicalLabSlug(aliasSlug)
  return SITE_LAB_CATEGORY_BY_SLUG.get(canonical)
    ?? SITE_LAB_CATEGORY_BY_SLUG.get(aliasSlug)
    ?? null
}

export function findLabSlugForSaveIndex(saveIndex: number): string | null {
  return LAB_SLUG_BY_SAVE_INDEX.get(saveIndex) ?? null
}

export function findLabDisplayNameForSaveIndex(saveIndex: number): string | null {
  const aliasSlug = LAB_SLUG_BY_SAVE_INDEX.get(saveIndex)
  if (!aliasSlug) return null
  const research = lookupResearch(aliasSlug)
  if (research?.displayName) return research.displayName
  return slugToDisplayLabel(aliasSlug)
}

export function findLabSlugFromApiName(apiSlug: string): { saveIndex: number; saveSlug: string } | null {
  const canonical = resolveCanonicalLabSlug(apiSlug)
  const index = LAB_RESEARCH_SLUG_TO_INDEX[canonical]
  if (index === undefined) return null
  return { saveIndex: index, saveSlug: canonical }
}
