/**
 * Finding a lab by the name a player sees, and how far it goes.
 *
 * Both of these are questions about the game, and both lived in `internal/game-input-data/
 * labs-dropdown-math.ts` because a name picker was the first thing to ask them. A picker needs to
 * resolve a typed name to a lab and know the lab's ceiling; so does anything else that takes a lab
 * name from a user, which is most things.
 */
/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    findLabRecordByName, computeLabsMaxLevel
 * depends    src/data/labs/labs
 * used by    src/data/labs/index, src/mechanics/calculators/specs-generated
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
import { formatLabDisplayName, getLabMaxLevel, getSharedToolLabs, type ToolLabRecord } from './labs'

/**
 * The lab a player-facing name refers to.
 *
 * Matches the catalog name first and the formatted display name second, because the two diverge:
 * the catalog carries `Dissonant Echo - Defense` where the displayed form has no separator. A
 * caller holding either spelling finds the same lab.
 */
export function findLabRecordByName(labName: string): ToolLabRecord | undefined {
  const trimmed = labName.trim()
  if (!trimmed) return undefined
  return getSharedToolLabs().find(lab =>
    lab.name === trimmed
    || formatLabDisplayName(String(lab.displayName ?? lab.name)) === trimmed,
  )
}

/**
 * The highest level a named lab reaches, or 0 when no name was given.
 *
 * The 30 for a name that resolves to nothing is inherited behaviour and is a guess: most labs do
 * cap at 30, and some do not. It is preserved here rather than corrected because callers price
 * upgrades against it, and changing a maximum changes a price — that belongs in its own change,
 * measured against the catalog, not smuggled into a move.
 */
export function computeLabsMaxLevel(labName: string | null | undefined): number {
  if (!labName?.trim()) return 0
  const lab = findLabRecordByName(labName)
  return lab ? getLabMaxLevel(lab) : 30
}
