/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    computeResearchLabLevel
 * depends    src/data/labs/categories, src/data/labs/research, src/support/own-lookup
 * used by    src/data/index, src/internal/shared-tool-inputs/from-research, src/mechanics/calculators/specs-generated
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
import { ownLookup } from '../../support/own-lookup'
import { findLabResearchBySlug } from './research'
import { CANONICAL_LAB_SLUG_BY_ALIAS } from './categories'

function clampInt(value: number, min: number, max: number): number {
  return Math.floor(Math.min(max, Math.max(min, value)))
}

function normalizeLookupKey(value: string): string {
  return value.trim().toLowerCase().replace(/[_\s]+/g, ' ')
}

/**
 * Resolve a research lab level from display-name keyed levels.
 * Matches slug, canonical slug, catalog displayName, and fuzzy display-name equality.
 */
export function computeResearchLabLevel(
  researchLabLevels: Record<string, number>,
  slug: string,
  maxLevel = 99,
): number {
  const canonical = ownLookup(CANONICAL_LAB_SLUG_BY_ALIAS, slug) ?? slug
  const research = findLabResearchBySlug(canonical) ?? findLabResearchBySlug(slug)
  const candidateKeys = [
    slug,
    canonical,
    research?.displayName,
    research?.slug,
  ].filter((key): key is string => typeof key === 'string' && key.length > 0)

  for (const key of candidateKeys) {
    // `researchLabLevels` is the caller's own record — saved settings, a save file —
    // so it gets the same treatment as our catalogs.
    const value = ownLookup(researchLabLevels, key)
    if (typeof value === 'number' && Number.isFinite(value)) {
      return clampInt(value, 0, maxLevel)
    }
  }

  if (research?.displayName) {
    const target = normalizeLookupKey(research.displayName)
    for (const [key, value] of Object.entries(researchLabLevels)) {
      if (!Number.isFinite(value)) continue
      if (normalizeLookupKey(key) === target) {
        return clampInt(value, 0, maxLevel)
      }
    }
  }

  return 0
}
