/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    LAB_WORKSHOP_SCALE, LAB_WORKSHOP_MAIN_LOOP_POW_EXP, LAB_WORKSHOP_FALLBACK_DIVISOR_S13, LAB_WORKSHOP_COIN_DISCOUNT_POW_EXP, LAB_WORKSHOP_ENEMY_EXTENDED_POW_EXP, LAB_WORKSHOP_MULT_70, LAB_WORKSHOP_LINEAR_300, LAB_WORKSHOP_LINEAR_500 (+4 more)
 * depends    —
 * used by    src/mechanics/enemies/get-resistance-level, src/mechanics/workshop/index, src/mechanics/workshop/lab-workshop-calculations
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
/** Tower lab workshop calculation constants. */
export const LAB_WORKSHOP_SCALE = -0.009999999776482582 as const
export const LAB_WORKSHOP_MAIN_LOOP_POW_EXP = 2.4000000953674316 as const
export const LAB_WORKSHOP_FALLBACK_DIVISOR_S13 = 3.5999999046325684 as const
export const LAB_WORKSHOP_COIN_DISCOUNT_POW_EXP = 2.549999952316284 as const
export const LAB_WORKSHOP_ENEMY_EXTENDED_POW_EXP = 3.799999952316284 as const
export const LAB_WORKSHOP_MULT_70 = 70 as const
export const LAB_WORKSHOP_LINEAR_300 = 300 as const
export const LAB_WORKSHOP_LINEAR_500 = 500 as const
export const LAB_WORKSHOP_LINEAR_30000 = 30000 as const
export const LAB_WORKSHOP_META_OFFSETS = {
  labs_coin_discount: 172,
  labs_speed: 176,
} as const
export const LAB_WORKSHOP_ENEMY_EXTENDED_OFFSETS = {
  'common_enemy_health': 472,
  'common_enemy_attack': 476,
  'fast_enemy_health': 480,
  'fast_enemy_attack': 484,
  'tank_enemy_health': 492,
  'tank_enemy_attack': 496,
  'ranged_enemy_health': 500,
  'ranged_enemy_attack': 504,
  'boss_health': 508,
  'boss_attack': 512,
  'protector_health': 516,
} as const
export const LAB_WORKSHOP_RESISTANCE_BASE_OFFSETS = {
  'Orb Resistance': 836,
  'Death Ray Resistance': 840,
  'Thorns Resistance': 844,
  'Knockback Resistance': 848,
  'Plasma Cannon Resistance': 852,
} as const
