/**
 * The fixed numbers behind bot cooldown and duration.
 *
 * Named rather than inlined because two of them are level COUNTS and two are level CAPS, and the
 * difference is where this went wrong before: `oracle_traps('bots')` records that the shared
 * 31-entry cost ladder is not a level count, and every bot carries it regardless of how far its
 * stats actually go. These counts are the stats' own, checked against `BOT_UPGRADES_DATA`:
 * cooldown has 16 levels on all five bots, and the shared duration ladder has 31.
 *
 * Thunder Bot is not on that shared ladder — it has 21 duration levels of its own — which is why
 * its three constants are separate rather than a special case of the others.
 */
/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    BOT_COOLDOWN_LEVEL_COUNT, BOT_DURATION_LEVEL_COUNT, BOT_COOLDOWN_LAB_CAP, BOT_DURATION_LAB_CAP, STANDARD_BOT_COOLDOWN_BASE_SECONDS, STANDARD_BOT_COOLDOWN_STEP_SECONDS, STANDARD_BOT_COOLDOWN_FLOOR_SECONDS, FLAME_BOT_COOLDOWN_BASE_SECONDS (+7 more)
 * depends    —
 * used by    src/mechanics/bots/compute, src/mechanics/bots/index
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */

/** Cooldown levels, 0 through 15, on every bot. */
export const BOT_COOLDOWN_LEVEL_COUNT = 16

/** Duration levels, 0 through 30, on Golden, Amplify and Bot Bot. */
export const BOT_DURATION_LEVEL_COUNT = 31

/** Highest cooldown lab level that still reduces the cooldown. */
export const BOT_COOLDOWN_LAB_CAP = 25

/** Highest duration lab level that still extends the duration. */
export const BOT_DURATION_LAB_CAP = 20

export const STANDARD_BOT_COOLDOWN_BASE_SECONDS = 120
export const STANDARD_BOT_COOLDOWN_STEP_SECONDS = 3
export const STANDARD_BOT_COOLDOWN_FLOOR_SECONDS = 50

export const FLAME_BOT_COOLDOWN_BASE_SECONDS = 75
export const FLAME_BOT_COOLDOWN_FLOOR_SECONDS = 30

/** The lab cannot take Flame Bot's cooldown below this, whatever the base reached. */
export const FLAME_BOT_COOLDOWN_LAB_FLOOR_SECONDS = 5

export const STANDARD_BOT_DURATION_BASE_SECONDS = 20
export const STANDARD_BOT_DURATION_STEP_SECONDS = 0.5

export const THUNDER_BOT_DURATION_BASE_SECONDS = 5
export const THUNDER_BOT_DURATION_STEP_SECONDS = 0.5
export const THUNDER_BOT_DURATION_CAP_SECONDS = 15
