/**
 * How a bot's Range stat becomes an area on the board.
 *
 * A bot's effect is not applied by a formula over "average overlap": every enemy carries a
 * per-bot in-range boolean that Unity's physics sets when it enters the bot's circle. So the
 * spatial half of any average is a genuine geometry question — how big is the circle, and how
 * much of the region the bot patrols does it cover.
 *
 * `Bot.UpdateSize` sets `localScale` from the Range stat and the tower's reach, and
 * `Bot.SetRandomDestination` picks a uniform point in a disc centred on the tower. Both are
 * reproduced here; the constants are the game's own.
 *
 * The tower's contribution is `botTowerFactor`, reused rather than restated. Its constants
 * (3, 12, 0.7, 0.6) are exactly the ones `Bot.UpdateSize` loads, so a second copy here would
 * be two definitions of one law waiting to disagree.
 */
/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    BOT_TRIGGER_COLLIDER_RADIUS, DISPLAY_METRES_PER_WORLD_UNIT, towerMaxDistanceWorldUnits, BOT_ROAM_RADIUS_FACTOR, botWorldRadius, botRoamRadius, botSpatialCoverageFraction, botTriggerRadiusWorldUnits (+1 more)
 * depends    src/mechanics/bots/bots
 * used by    src/mechanics/bots/index, src/mechanics/bots/medal-simulation, src/mechanics/calculators/specs-generated
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */

import { botTowerFactor } from './bots'

/**
 * The radius of every bot's trigger `CircleCollider2D`, read out of the shipped prefabs:
 * `Area of Effect -> Container -> <bot> -> BotsController`, on Golden, Thunder and Amplify.
 *
 * The prefab authors that object with a `localScale` of 2, which would cancel this exactly —
 * but `Bot.UpdateSize` overwrites it. Its last act is
 *
 *     ldr x0, [x19, #0x28]   ; this->trigger   (CircleCollider2D, field @0x28)
 *     bl  get_transform
 *     fmov s0, s8 / fmov s1, s8 / fmov s2, #1.0
 *     bl  set_localScale     ; (scale, scale, 1)
 *
 * so the collider's transform carries the computed scale and nothing else, and the authored
 * 2 never applies at runtime. The world radius is therefore HALF the scale.
 *
 * That is the step `botEffectiveRadius` leaves out: it returns the scale and calls it a
 * radius, which overstates the radius twofold and any area built from it fourfold.
 */
export const BOT_TRIGGER_COLLIDER_RADIUS = 0.5

/**
 * The game plays in world units; a player reads metres off the card. Ten metres to the unit.
 *
 * Every quantity below is in WORLD UNITS. Mixing the two is the mistake this module exists to
 * stop: a bot at 60M has a radius of 2.7 and roams a disc of 3.19, so reading the metres as
 * units instead makes the bot twenty times the size of the region it patrols and every
 * coverage fraction saturates at 1 without ever looking wrong.
 */
export const DISPLAY_METRES_PER_WORLD_UNIT = 10

/** The tower's reach in world units — `Main.maxDistance`, which `botTowerFactor` spans 3..12. */
export function towerMaxDistanceWorldUnits(towerRangeDisplayMetres: number): number {
  return Math.max(0, towerRangeDisplayMetres) / DISPLAY_METRES_PER_WORLD_UNIT
}

/** Roam radius is this times the square root of the tower's reach. Also `RADIUS_PERCENTAGE`. */
export const BOT_ROAM_RADIUS_FACTOR = 1.3

function clamp01(value: number): number {
  return Math.max(0, Math.min(1, value))
}

/**
 * The bot's effect radius in world units: `(rangeStat / 10) * towerFactor * colliderRadius`.
 *
 * `rangeStat` is the game's own Range benefit, which for this stat is numerically the metres
 * printed on the card — Golden's maxed Range is 60.0 in the binary and reads "60M" in the UI.
 * The `/ 10` is the metres-to-world-units conversion, not a normalisation, so cancelling it
 * by pre-multiplying the display value is how a radius ends up ten times too large.
 */
export function botWorldRadius(rangeStat: number, towerMaxDistance: number): number {
  const scale = (Math.max(0, rangeStat) / 10) * botTowerFactor(towerMaxDistance)
  return scale * BOT_TRIGGER_COLLIDER_RADIUS
}

/** The radius of the disc a bot picks its destinations from, centred on the tower. */
export function botRoamRadius(towerMaxDistance: number): number {
  return BOT_ROAM_RADIUS_FACTOR * Math.sqrt(Math.max(0, towerMaxDistance))
}

/**
 * The share of its own roam disc a bot covers at an instant.
 *
 * This is the SPATIAL term only. It is not the probability an enemy is in range: enemies are
 * not spread uniformly over that disc — they walk inward from the spawn ring — and a bot has
 * to be active as well. Combine it with uptime through
 * `botBotAmplificationApplicationFraction` rather than using it alone.
 */
export function botSpatialCoverageFraction(
  rangeStat: number,
  towerMaxDistance: number,
): number {
  const roam = botRoamRadius(towerMaxDistance)
  if (roam <= 0) return 0
  const ratio = botWorldRadius(rangeStat, towerMaxDistance) / roam
  return clamp01(ratio * ratio)
}

/** Trigger radius in world units, from the two numbers a player actually has. */
export function botTriggerRadiusWorldUnits(
  rangeDisplayMetres: number,
  towerRangeDisplayMetres: number,
): number {
  if (!Number.isFinite(rangeDisplayMetres) || rangeDisplayMetres <= 0) return 0
  return botWorldRadius(rangeDisplayMetres, towerMaxDistanceWorldUnits(towerRangeDisplayMetres))
}

/** Coverage of the roam disc, from the two numbers a player actually has. */
export function botCoverageFromDisplayMetres(
  rangeDisplayMetres: number,
  towerRangeDisplayMetres: number,
): number {
  if (!Number.isFinite(rangeDisplayMetres) || rangeDisplayMetres <= 0) return 0
  return botSpatialCoverageFraction(rangeDisplayMetres, towerMaxDistanceWorldUnits(towerRangeDisplayMetres))
}
