/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    BOT_MEDAL_SYNC_SCORE_WEIGHTS, scoreBotMedalSecondarySyncTiming, scoreBotMedalPrimaryLabSyncTiming, scoreBotMedalNaturalSyncAlignmentRow, computeSecondarySyncedDurationPenalty, computeDutyCycleOvershootPenalty
 * depends    src/mechanics/uptime/compute
 * used by    src/mechanics/bots/index, src/mechanics/calculators/specs-generated
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
import { computeUptimeRatio } from '../uptime/compute'

/** Weight profiles for natural-sync decisions (lab, secondary admission, plan objective). */
export const BOT_MEDAL_SYNC_SCORE_WEIGHTS = {
  secondary: {
    fit: 35,
    totalOverlap: 18,
    botUptimeOverlap: 14,
    uptimeRatio: 8,
  },
  primaryLab: {
    fit: 6,
    botUptimeOverlap: 4.4,
    botBotUptimeOverlap: 1.4,
    uptimeObjective: 2.6,
    cooldownGapPenalty: 1.8,
    harmonyCooldownGapDelta: 6,
    harmonyDurationGapDelta: 5,
    labLevelsAdded: 0.7,
  },
  naturalSyncAlignment: {
    fit: 0.85,
    totalOverlap: 1.6,
    botUptimeOverlap: 1.2,
    uptimeRatio: 0.45,
  },
} as const

export function scoreBotMedalSecondarySyncTiming(input: {
  fitScore: number
  overlapOfTotalTimeFraction: number
  overlapOfBotUptimeFraction: number
  uptimeRatio: number
  medalPenalty?: number
  labPenalty?: number
}): number {
  const weights = BOT_MEDAL_SYNC_SCORE_WEIGHTS.secondary
  return (input.fitScore * weights.fit)
    + (input.overlapOfTotalTimeFraction * weights.totalOverlap)
    + (input.overlapOfBotUptimeFraction * weights.botUptimeOverlap)
    + (input.uptimeRatio * weights.uptimeRatio)
    - (input.medalPenalty ?? 0)
    - (input.labPenalty ?? 0)
}

export function scoreBotMedalPrimaryLabSyncTiming(input: {
  fitScore: number
  overlapOfBotUptimeFraction: number
  overlapOfBotBotUptimeFraction: number
  uptimeObjective: number
  cooldownGapPenalty: number
  harmonyCooldownGapDelta: number
  harmonyDurationGapDelta: number
  totalLabLevelsAdded: number
}): number {
  const weights = BOT_MEDAL_SYNC_SCORE_WEIGHTS.primaryLab
  return (input.fitScore * weights.fit)
    + (input.overlapOfBotUptimeFraction * weights.botUptimeOverlap)
    + (input.overlapOfBotBotUptimeFraction * weights.botBotUptimeOverlap)
    + (input.uptimeObjective * weights.uptimeObjective)
    - (input.cooldownGapPenalty * weights.cooldownGapPenalty)
    - (input.harmonyCooldownGapDelta * weights.harmonyCooldownGapDelta)
    - (input.harmonyDurationGapDelta * weights.harmonyDurationGapDelta)
    - (input.totalLabLevelsAdded * weights.labLevelsAdded)
}

export function scoreBotMedalNaturalSyncAlignmentRow(input: {
  fitScore: number
  overlapOfTotalTimeFraction: number
  overlapOfBotUptimeFraction: number
  uptimeRatio: number
  rowWeight: number
}): number {
  const weights = BOT_MEDAL_SYNC_SCORE_WEIGHTS.naturalSyncAlignment
  return input.rowWeight * (
    (input.fitScore * weights.fit)
    + (input.overlapOfTotalTimeFraction * weights.totalOverlap)
    + (input.overlapOfBotUptimeFraction * weights.botUptimeOverlap)
    + (input.uptimeRatio * weights.uptimeRatio)
  )
}

export function computeSecondarySyncedDurationPenalty(input: {
  rows: ReadonlyArray<{
    synced: boolean
    durationLevel: number
    primaryDurationLevel: number
    maxLagLevels: number
  }>
}): number {
  let penalty = 0
  for (const row of input.rows) {
    if (!row.synced) continue
    const maxAllowed = row.primaryDurationLevel - row.maxLagLevels
    const violation = row.durationLevel - maxAllowed
    if (violation > 0) {
      penalty += violation * 0.35
    }
  }
  return penalty
}

export function computeDutyCycleOvershootPenalty(input: {
  rows: ReadonlyArray<{
    durationSeconds: number
    cooldownSeconds: number
    synced: boolean
  }>
  targetDuty?: number
}): number {
  const targetDuty = input.targetDuty ?? 0.92
  if (!input.rows.length) return 0

  let penalty = 0
  for (const row of input.rows) {
    const duty = computeUptimeRatio(row.durationSeconds, row.cooldownSeconds)
    if (duty <= targetDuty) continue
    const weight = row.synced ? 2.5 : 1.2
    penalty += (duty - targetDuty) * weight
  }
  return penalty / input.rows.length
}
