/**
 * What each Bot+ ability actually does.
 *
 * All five were previously treated as a multiplier on the bot's own core effect. Four of them
 * are not, and the game's own descriptions say so:
 *
 *   Wildfire       "Enemies hit by Flame Bot become Enflamed in addition to Burned, receiving
 *                   {0}x extra damage."                       -> DAMAGE. Flame's core stat is
 *                                                                damage REDUCTION.
 *   Titan Shock    "Enemies struck by Thunder Bot have a permanent {0}% decreased attack
 *                   speed."                                   -> SURVIVABILITY. Thunder's core
 *                                                                stat is Linger.
 *   Bonus Cells    "Elites killed in Golden Bot range grant {0}x more Cells."
 *                                                             -> CELLS. Golden's core stat is
 *                                                                the COIN bonus.
 *   Echoing Shot   "Tower Bullets within Range count as {0} bullets. Ultimate Weapon
 *                   projectiles are also boosted, but by 1/3." -> the bot's own effect. This is
 *                                                                the one that does multiply.
 *   Maximum Power  "Boosts the Bot+ abilities of other bots by {0}x."
 *                                                             -> OTHER BOTS' BOT+. Not its own
 *                                                                core, and not their base
 *                                                                effects either.
 *
 * Multiplying a bot's core by an ability that does something else entirely produces numbers
 * that are individually plausible and wrong everywhere — a maxed Bonus Cells was scaling
 * Golden's coin bonus by 2.5x for a bonus that grants no coins at all.
 *
 * The planner reduces a bot to one scalar, so an ability on another axis has to enter it
 * somewhere. It enters as value delivered inside the bot's own window: every one of these
 * applies only to enemies in that bot's range while it is active, so they share the bot's
 * reach exactly. That is a stated modelling assumption rather than a hidden one — the axis is
 * carried on the result so a caller that CAN tell cells from coins is able to.
 */
/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    BotPlusAxis, BOT_PLUS_AXIS_BY_BOT, BotPlusEffect, getBotPlusLevelMultiplier, resolveBotPlusEffect, BotPlusAxisValues, echoingShotWeightedMultiplier, weightedMaximumPower (+8 more)
 * depends    src/data, src/mechanics/combat/wildfire
 * used by    src/internal/local-state/bot-medal-splitter, src/internal/shared-tool-inputs/extended, src/mechanics/bots/index, src/mechanics/calculators/specs-generated
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
import type { BotStatRow } from '../../data'
import { getWildfireAmplification } from '../combat/wildfire'

/** The quantity a Bot+ ability multiplies, per the game's description of it. */
export type BotPlusAxis = 'core' | 'cells' | 'damage' | 'survivability' | 'other-bot-plus'

export const BOT_PLUS_AXIS_BY_BOT: Readonly<Record<string, BotPlusAxis>> = {
  'Flame Bot': 'damage',
  'Thunder Bot': 'survivability',
  'Golden Bot': 'cells',
  'Amplify Bot': 'core',
  'Bot Bot': 'other-bot-plus',
}

export interface BotPlusEffect {
  /** The ability's value at this level, straight off its curve. `1` when not unlocked. */
  multiplier: number
  axis: BotPlusAxis
  /** True only for Amplify: the ability multiplies the bot's own core effect. */
  multipliesCore: boolean
}

function parseMultiplierValue(raw: string): number {
  const trimmed = String(raw || '').trim().toLowerCase()
  if (!trimmed || trimmed === '—') return 1
  if (trimmed.endsWith('x')) {
    const numeric = Number.parseFloat(trimmed.slice(0, -1))
    return Number.isFinite(numeric) && numeric > 0 ? numeric : 1
  }
  if (trimmed.endsWith('%')) {
    const numeric = Number.parseFloat(trimmed.slice(0, -1))
    return Number.isFinite(numeric) ? 1 + (numeric / 100) : 1
  }
  const numeric = Number.parseFloat(trimmed)
  return Number.isFinite(numeric) && numeric > 0 ? numeric : 1
}

export function getBotPlusLevelMultiplier(stat: BotStatRow | undefined, level: number): number {
  if (!stat || level < 0) return 1
  const entry = stat.levels.find(row => row.level === level)
  if (!entry || entry.value === '') return 1
  return parseMultiplierValue(entry.value)
}

/**
 * A bot's Bot+ ability at a given level, with the axis it acts on.
 *
 * `maximumPowerMultiplier` is the Bot Bot's own Bot+, which boosts every OTHER bot's Bot+.
 * It is applied to the part above 1, because it scales the ability rather than the baseline:
 * a 2x Bonus Cells under a 1.5x Maximum Power is 2.5x, not 3x. It is never applied to the
 * Bot Bot's own ability, which is what "other bots" in the description means.
 */
export function resolveBotPlusEffect(input: {
  botLabel: string
  plusStat: BotStatRow | undefined
  plusLevel: number
  maximumPowerMultiplier?: number
  /** What the Bot Bot's Maximum Power is worth to this player, against its own Bonus. 0..1. */
  maximumPowerWeight?: number
}): BotPlusEffect {
  const axis = BOT_PLUS_AXIS_BY_BOT[input.botLabel] ?? 'core'
  if (input.plusLevel < 0 || !input.plusStat) {
    return { multiplier: 1, axis, multipliesCore: false }
  }
  const own = getBotPlusLevelMultiplier(input.plusStat, input.plusLevel)
  // Maximum Power is weighted the same way Echoing Shot is, and for the same reason: what the
  // Bot Bot's ability is worth against its own Bonus stat depends on how much the player cares
  // about the OTHER bots' Bot+ abilities, which it is the only thing it touches. Weighting the
  // part above 1 leaves it at 1x when the answer is zero, rather than at nothing.
  const weightedOwn = 1 + ((own - 1) * clamp01(input.maximumPowerWeight, 1))
  const boost = axis === 'other-bot-plus'
    ? 1
    : Math.max(1, weightedMaximumPower(input.maximumPowerMultiplier, input.maximumPowerWeight))
  const multiplier = axis === 'other-bot-plus'
    ? weightedOwn
    : 1 + ((own - 1) * boost)
  return { multiplier, axis, multipliesCore: axis === 'core' }
}

/**
 * What each Bot+ axis is worth to a player, relative to the number the planner optimises.
 *
 * Three of the five abilities act on something other than the bot's own output — Bonus Cells
 * grants CELLS, Wildfire grants DAMAGE, Titan Shock grants SURVIVABILITY. All three are real
 * value, and how much each is worth depends entirely on what the player is playing for.
 *
 * These are not entered directly. They are derived from two things a player can actually
 * answer about their own bots — see `BOT_PLUS_AXIS_WEIGHT_BY_BOT` — because "how many coins is a cell worth"
 * is a question nobody has a number for, and asking it produced inputs that nobody could
 * fill in honestly.
 *
 * `core` and `other-bot-plus` have no weight here. Amplify's Echoing Shot multiplies the
 * bot's own effect and is already inside `effectiveNumber`, so weighting it again would
 * count it twice; the Bot Bot's Maximum Power is applied to the OTHER abilities rather than
 * to anything of its own.
 */
export interface BotPlusAxisValues {
  /** Golden's Bonus Cells. */
  cells: number
  /** Flame's Wildfire. */
  damage: number
  /** Thunder's Titan Shock. */
  survivability: number
}

const clamp01 = (value: unknown, fallback: number): number =>
  (Number.isFinite(value) ? Math.max(0, Math.min(1, value as number)) : fallback)

/**
 * What Echoing Shot is worth against Amplify's own Bonus, which is not a fixed rate.
 *
 * The ability is not a flat multiplier on the bot's damage amplification, and the game says
 * so: "Tower Bullets within Range count as {0} bullets. Ultimate Weapon projectiles are also
 * boosted, but by 1/3." That sentence was quoted at the top of this file and modelled
 * nowhere — the multiplier was applied whole, which is the claim that none of the player's
 * damage comes from an Ultimate Weapon, made on their behalf and then used to price medals.
 *
 * There is no single correct discount, because it depends on where a build's damage comes
 * from, so Amplify's tab asks for one number covering it: how much its Bot+ is worth against
 * its Bonus. Only the part above 1 is weighted, the same way Maximum Power scales an ability
 * rather than its baseline — a weight of 0 leaves the ability at 1x rather than at nothing.
 */
export function echoingShotWeightedMultiplier(multiplier: number, botPlusWeight: number): number {
  const weight = clamp01(botPlusWeight, DEFAULT_AMPLIFY_BOT_PLUS_WEIGHT)
  return 1 + (Math.max(0, multiplier - 1) * weight)
}

/**
 * What Maximum Power is worth against the Bot Bot's own Bonus.
 *
 * The ability boosts the Bot+ abilities of the other bots and touches nothing else, so its
 * worth rests entirely on how much those abilities are worth to this player — a build that has
 * barely levelled them is buying a multiplier on almost nothing. That is not something the
 * game's tables answer, and the planner cannot see it either: it prices Maximum Power through
 * the other rows, which are themselves weighted by inputs the player set.
 *
 * Only the part above 1 is weighted, so a weight of zero leaves the ability at 1x rather than
 * at nothing. Defaults to full, which is what the tool did before the input existed.
 */
export function weightedMaximumPower(multiplier: number | undefined, weight: number | undefined): number {
  const value = Number.isFinite(multiplier) ? Math.max(1, multiplier as number) : 1
  return 1 + ((value - 1) * clamp01(weight, 1))
}

/**
 * A starting position, derived from the rule rather than picked.
 *
 * A build taking a quarter of its damage from an Ultimate Weapon gets the full boost on three
 * quarters of it and a third of the boost on the rest: `0.75 + (0.25 / 3)` is 0.833, rounded
 * down to 0.8. That is a middling build — enough that the 1/3 rule visibly matters, not so
 * much that Echoing Shot stops being worth buying. The old behaviour was 1.0, which is the
 * bullets-only end of the same range and was never neutral.
 */
export const DEFAULT_AMPLIFY_BOT_PLUS_WEIGHT = 0.8

/**
 * The question each bot's own tab asks, instead of asking for an exchange rate.
 *
 * Every bot with an off-axis Bot+ has TWO things it can be worth, and which one a player is
 * buying is a fact about their build:
 *
 *   Golden Bot    coins vs cells           — its coin bonus against Bonus Cells.
 *   Flame Bot     eHP vs damage            — its damage reduction against Wildfire.
 *   Thunder Bot   crowd control vs damage  — Linger and Titan Shock both slow things down;
 *                                            neither of them kills anything.
 *
 * Asked per bot, in that bot's own words, because "how many coins is a cell worth" is a
 * question nobody has a number for. Each value is the weight of the SECOND quantity named in
 * the label, so 0 is all of the first and 1 is all of the second — the same reading as the
 * input the player sees.
 */
export const BOT_PLUS_AXIS_WEIGHT_BY_BOT: Readonly<Record<string, keyof BotPlusAxisValues>> = {
  'Golden Bot': 'cells',
  'Flame Bot': 'damage',
  'Thunder Bot': 'survivability',
}

/**
 * Starting positions, not claims. Every one is meant to be moved.
 *
 * Golden sits at 0.4 deliberately. The decision to buy its Bot+ at a 60k budget flips at about
 * 0.48 — above it the plan takes eight levels, below it none — so landing on 0.5 would balance
 * the whole Bot+ decision on that edge, where a rounding difference anywhere in the model
 * swings it. 0.4 is off the edge and on the side the game supports: coins are worth more than
 * cells to most players.
 */
export const DEFAULT_BOT_PLUS_AXIS_WEIGHTS: Readonly<Record<string, number>> = {
  'Golden Bot': 0.4,
  'Flame Bot': 0.5,
  'Thunder Bot': 0.8,
  // Amplify's answer is not an axis weight. Its tab asks what Echoing Shot is worth against
  // its own Bonus — see `echoingShotWeightedMultiplier`. It shares this map because it is the
  // same shape of question and the same 0..1 slot.
  'Amplify Bot': DEFAULT_AMPLIFY_BOT_PLUS_WEIGHT,
  // The Bot Bot asks the same question about Maximum Power. It starts at full, which is what
  // the tool asserted before there was an input for it.
  'Bot Bot': 1,
}

/**
 * The per-bot inputs, turned into the three axis weights the scorer uses.
 *
 * Thunder's is INVERTED against the other two, and that is not a quirk of the wiring — it is
 * what its label says. Golden's and Flame's second quantity is the Bot+ one (cells, Wildfire
 * damage), so a higher answer means more Bot+ value. Thunder's second quantity is damage,
 * which Thunder does not provide at all, so a higher answer means LESS worth in Titan Shock.
 */
export function botPlusAxisValuesFromBotWeights(
  weights: Readonly<Record<string, number>> = {},
): BotPlusAxisValues {
  const weightFor = (botLabel: string) =>
    clamp01(weights[botLabel], DEFAULT_BOT_PLUS_AXIS_WEIGHTS[botLabel] ?? 0)
  return {
    cells: weightFor('Golden Bot'),
    damage: weightFor('Flame Bot'),
    survivability: 1 - weightFor('Thunder Bot'),
  }
}

export const DEFAULT_BOT_PLUS_AXIS_VALUES: Readonly<BotPlusAxisValues>
  = botPlusAxisValuesFromBotWeights()

/**
 * What a Bot+ ability adds to the single number the planner optimises.
 *
 * `reach` is the bot's uptime times its coverage — the share of the fight the ability is
 * actually applied over. Only the part above 1 counts: an ability at its baseline multiplies
 * by one and has changed nothing.
 */
export function botPlusReachedValue(
  effect: BotPlusEffect,
  coreValue: number,
  reach: number,
  axisValues: Partial<BotPlusAxisValues> = {},
): number {
  const weights = { ...DEFAULT_BOT_PLUS_AXIS_VALUES, ...axisValues }
  const weight = effect.axis === 'cells' ? weights.cells
    : effect.axis === 'damage' ? weights.damage
      : effect.axis === 'survivability' ? weights.survivability
        : 0
  const clamped = Math.max(0, Math.min(1, Number.isFinite(weight) ? weight : 0))
  if (clamped <= 0) return 0
  const gain = Math.max(0, effect.multiplier - 1)
  return gain * Math.max(0, coreValue) * Math.max(0, Math.min(1, reach)) * clamped
}

export function getFlameWildfireShDamageSupport(input: {
  plusLevel: number
  plusStat: BotStatRow | undefined
  flameCoverageFraction: number
  singularityHarnessActive: boolean
}): number {
  if (!input.singularityHarnessActive || input.plusLevel < 0 || !input.plusStat) return 0
  const statBase = getBotPlusLevelMultiplier(input.plusStat, 0)
  const statMult = getBotPlusLevelMultiplier(input.plusStat, input.plusLevel)
  const wildfireAmp = getWildfireAmplification({
    wildfireActive: input.plusLevel > 0,
    statBase,
    statMult,
  })
  return input.flameCoverageFraction * Math.max(0, wildfireAmp - statBase)
}

/**
 * What Flame's DAMAGE stat is worth, which is nothing at all without Wildfire.
 *
 * Flame's core is its damage reduction; its Damage stat does not feed that, so the planner
 * rated it near zero and never bought it. That is right for a Flame Bot on its own, and wrong
 * for one with Wildfire: the ability makes enemies Enflamed and take `{0}x extra damage`, and
 * the game's own description says the DURATION of that amplification depends on current Flame
 * Bot damage. So the Damage stat is what turns Wildfire from a moment into a window.
 *
 * That makes it the one stat in the tool whose worth is switched on by an ability rather than
 * scaled by it: locked Wildfire means Flame damage is worth buying only for its own sake,
 * which is to say not at all.
 *
 * Returns a share of the bot's reach, weighted by what the player says damage is worth against
 * coins — the same input that governs Wildfire itself, because this is the same effect.
 */
export function flameDamageWithWildfireValue(input: {
  wildfireLevel: number
  wildfireStat: BotStatRow | undefined
  damageStatValue: number
  reach: number
  damageValueRatio?: number
}): number {
  if (input.wildfireLevel < 0 || !input.wildfireStat) return 0
  const wildfire = getBotPlusLevelMultiplier(input.wildfireStat, input.wildfireLevel)
  const amplification = Math.max(0, wildfire - 1)
  if (amplification <= 0) return 0
  const weight = Math.max(0, Math.min(1, input.damageValueRatio ?? DEFAULT_BOT_PLUS_AXIS_VALUES.damage))
  const damage = Math.max(0, input.damageStatValue)
  return Math.log1p(damage) * amplification * Math.max(0, Math.min(1, input.reach)) * weight
}
