/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    BotMedalUpgradeInsightMetrics, BotMedalUpgradeInsightInput, describeBotMedalUpgradeInsight
 * depends    —
 * used by    src/mechanics/bots/index, src/mechanics/calculators/specs-generated
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
/**
 * Human-readable upgrade rationale from simulated metric deltas (not hardcoded bot priority).
 */

export interface BotMedalUpgradeInsightMetrics {
  effectiveNumber: number
  uptimeFraction: number
  avgOverlapFraction: number
  /**
   * The share of its roam disc the bot covers, 0..1.
   *
   * There used to be a `coverageScale` beside this holding the SAME number: the caller's
   * `getRangeCoverageAnchorScale` did nothing but call `getRangeCoverageAnchorFraction`. Two
   * names for one value is how `Math.max(0, coverageScale - 1)` came to be written in five
   * places — a plausible-looking "coverage above baseline" that is structurally zero, because
   * a fraction cannot exceed 1.
   */
  coverageFraction: number
}

export interface BotMedalUpgradeInsightInput {
  botLabel: string
  statName: string
  upgradeKind: 'base' | 'plus'
  objectiveDelta: number
  before: BotMedalUpgradeInsightMetrics
  after: BotMedalUpgradeInsightMetrics
  botBotOverlapBefore?: number
  botBotOverlapAfter?: number
  singularityHarnessActive?: boolean
}

function formatPercent(value: number): string {
  return `${(Math.max(0, value) * 100).toFixed(1)}%`
}

function formatCoverage(value: number): string {
  return value.toFixed(2)
}

function pickDominantSignal(input: BotMedalUpgradeInsightInput): string | null {
  const { before, after, statName, upgradeKind, botLabel } = input
  const overlapGain = after.avgOverlapFraction - before.avgOverlapFraction
  const coverageGain = after.coverageFraction - before.coverageFraction
  const uptimeGain = after.uptimeFraction - before.uptimeFraction
  const effectiveGain = after.effectiveNumber - before.effectiveNumber
  const botBotOverlapGain = (input.botBotOverlapAfter ?? 0) - (input.botBotOverlapBefore ?? 0)

  // Every string below states what the game's own description says the Bot+ does. They are
  // not decoration — a player reads them to decide where medals go, and one of them said
  // "Bonus Cell+ scales coin multiplier" when Golden's Bot+ is
  // "Elites killed in Golden Bot range grant {0}x more Cells". Cells, not coins.
  if (upgradeKind === 'plus') {
    if (botLabel === 'Flame Bot' && input.singularityHarnessActive) {
      return `Wildfire+ raises Singularity Harness burn support (effective ${effectiveGain >= 0 ? '+' : ''}${effectiveGain.toFixed(2)})`
    }
    if (botLabel === 'Flame Bot') {
      return 'Wildfire+ makes hit enemies Enflamed, taking extra damage'
    }
    if (botLabel === 'Golden Bot') {
      return `Bonus Cell+ grants more Cells from Elites killed in range (${formatPercent(before.uptimeFraction)} uptime window)`
    }
    if (botLabel === 'Thunder Bot') {
      return 'Titan Shock+ permanently cuts the attack speed of struck enemies'
    }
    if (botLabel === 'Bot Bot') {
      // Max Power boosts other bots' BOT+ abilities, not their base effects — the base
      // amplification is the Bot Bot's own `Bonus` stat.
      return 'Maximum Power+ boosts the Bot+ abilities of other bots'
    }
    if (botLabel === 'Amplify Bot') {
      return 'Echo+ makes Tower bullets in range count as extra bullets'
    }
    if (effectiveGain > 0.01) {
      return `${statName} improves simulated output (+${effectiveGain.toFixed(2)} effective)`
    }
    return `${statName} unlocks stronger Bot+ scaling`
  }

  if (statName.includes('Range') && coverageGain > 0.008) {
    return `Range expands coverage ${formatCoverage(before.coverageFraction)}→${formatCoverage(after.coverageFraction)}`
  }

  if ((statName === 'Cooldown' || statName === 'Duration') && overlapGain > 0.004) {
    const overlapLabel = formatPercent(after.avgOverlapFraction)
    const priorLabel = formatPercent(before.avgOverlapFraction)
    if (botBotOverlapGain > 0.004) {
      return `${statName} aligns activation with Bot Bot (${priorLabel}→${overlapLabel} overlap)`
    }
    return `${statName} improves overlap duty (${priorLabel}→${overlapLabel})`
  }

  if (statName === 'Cooldown' && uptimeGain > 0.006) {
    return `Cooldown shortens cycle (${formatPercent(before.uptimeFraction)}→${formatPercent(after.uptimeFraction)} uptime)`
  }

  if (statName === 'Duration' && uptimeGain > 0.006) {
    return `Duration lengthens active window (${formatPercent(before.uptimeFraction)}→${formatPercent(after.uptimeFraction)} uptime)`
  }

  if (statName === 'Bonus' && effectiveGain > 0.01) {
    return `Bonus raises effective output (+${effectiveGain.toFixed(2)})`
  }

  if (coverageGain > 0.008) {
    return `Coverage reach improves ${formatCoverage(before.coverageFraction)}→${formatCoverage(after.coverageFraction)}`
  }

  if (overlapGain > 0.004) {
    return `Overlap quality improves ${formatPercent(before.avgOverlapFraction)}→${formatPercent(after.avgOverlapFraction)}`
  }

  if (effectiveGain > 0.01) {
    return `Effective output +${effectiveGain.toFixed(2)} from ${statName}`
  }

  return null
}

export function describeBotMedalUpgradeInsight(input: BotMedalUpgradeInsightInput): string {
  const dominant = pickDominantSignal(input)
  if (dominant) return dominant
  if (input.objectiveDelta > 0.0001) {
    return `Plan objective +${input.objectiveDelta.toFixed(3)}`
  }
  return 'Marginal plan improvement'
}
