/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    BotMedalMetricSnapshot, botBotAmplificationHeadroom, BotMedalPlannerRowContext, BotMedalPlanObjectiveInput, consolidatedSimulatedOverlap, computeOverlapPotentialScore, getSustainedApplicationFactor, BOT_MEDAL_TIMING_HALF_POINT (+4 more)
 * depends    —
 * used by    src/mechanics/bots/index, src/mechanics/calculators/specs-generated
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
/**
 * Bot medal planner objective — weights tuned for game-faithful overlap simulation.
 *
 * Primary signal: `effectiveNumber` from tick sim + Bot Bot amplification model.
 * Overlap terms use a single consolidated metric instead of triple-counting
 * temporal / applied / conditioned averages with unrelated magic coefficients.
 */

export interface BotMedalMetricSnapshot {
  baseNumber: number
  effectiveNumber: number
  uptimeFraction: number
  overlapFraction: number
  avgOverlapFraction: number
  avgOverlapDisplayFraction: number
  coverageFraction: number
  /** The Bot Bot's `Bonus` stat — the whole of its amplification. 1.05 … 2.0. */
  botBotBonus: number
}

/**
 * How much overlap can be worth, relative to uptime, at this Bot Bot Bonus.
 *
 * The game computes a bot's average contribution as
 *
 *     base * [ uptime + (bonus - 1) * overlap ]
 *
 * so the marginal value of uptime is `base` and the marginal value of overlap is
 * `base * (bonus - 1)`. Since the Bonus stat tops out at 2.0, **overlap is worth at most
 * exactly as much as uptime, and usually far less** — at a level-0 Bot Bot (1.05) it is
 * worth five percent as much.
 *
 * Every scoring term that adds overlap alongside uptime has to carry this factor, or it is
 * asserting that overlap can outrank uptime, which no configuration of the game supports.
 */
export function botBotAmplificationHeadroom(botBotBonus: number): number {
  // A non-finite bonus yields no headroom rather than NaN. The field is required by the
  // type, so a real caller cannot omit it — but a NaN here would spread through the whole
  // objective and turn every recommendation into garbage, which is a far worse failure
  // than valuing overlap at zero.
  if (!Number.isFinite(botBotBonus)) return 0
  return clamp01(Math.max(1, botBotBonus) - 1)
}

export interface BotMedalPlannerRowContext {
  synced: boolean
  isBotBot: boolean
}

export interface BotMedalPlanObjectiveInput {
  /** Overrides `BOT_MEDAL_TIMING_MAX_UPLIFT` for this plan. Absent uses the default. */
  timingMaxUplift?: number

  totalScore: number
  coordinationScore: number
  potentialScore: number
  timingHarmonyScore: number
  averageCadence: number
  pairwiseCycleAlignmentScore: number
  timingPairValue: number
  averageUptime: number
  uptimeFloor: number
  averageSimulatedOverlap: number
  averageCoverage: number
  sustainedCoverageScore: number
  sharedPathContinuityScore: number
  priorityCoverageScore: number
  priorityAnchorScore: number
  naturalSyncAlignmentScore: number
  unsyncedRangeShortfall: number
  secondarySyncedDurationPenalty: number
  dutyCycleOvershootPenalty: number
}

function clamp01(value: number): number {
  return Math.max(0, Math.min(1, value))
}

/** Overlap quality from simulation: temporal × spatial while co-active. */
export function consolidatedSimulatedOverlap(snapshot: BotMedalMetricSnapshot): number {
  const temporal = clamp01(snapshot.avgOverlapFraction)
  const spatial = clamp01(Math.max(snapshot.overlapFraction, snapshot.avgOverlapDisplayFraction * snapshot.overlapFraction))
  return temporal * (spatial > 0 ? spatial : temporal)
}

/** Scores how much simulated overlap + uptime can move the needle for this row. */
export function computeOverlapPotentialScore(
  row: BotMedalPlannerRowContext,
  snapshot: BotMedalMetricSnapshot,
): number {
  const effectiveSignal = Math.log1p(Math.max(0, snapshot.effectiveNumber))
  // Overlap is only ever worth `(bonus - 1)` of what uptime is worth. Without this the
  // terms below rated overlap at twice uptime — and `effectiveSignal` was additionally
  // MULTIPLIED by overlap, so the same quantity was counted three times in one expression
  // while uptime was counted once.
  const headroom = botBotAmplificationHeadroom(snapshot.botBotBonus)
  const overlapQuality = consolidatedSimulatedOverlap(snapshot) * headroom
  const uptime = clamp01(snapshot.uptimeFraction)
  // The Bot Bot has no effect of its own — its Bonus IS the amplification — so every one of
  // its stats pays off only through `(bonus - 1)`, its reach included. Unscaled, its Range
  // was ranked as if it were a normal bot covering enemies with its own effect, which made
  // "Bot Bot Range" the first purchase even at a level-0 Bonus of 1.05, where widening the
  // circle multiplies almost nothing. Every other bot's reach does pay off directly.
  const reachScale = row.isBotBot ? headroom : 1
  const coverage = clamp01(snapshot.coverageFraction) * reachScale
  const syncedBias = row.synced ? 1.12 : 1
  // The `rangeReach` term that stood here was `Math.max(0, coverageFraction - 1)`, and a
  // coverage fraction cannot exceed 1 — so it was zero for every
  // input, weighted 1.6 or 0.85, and had never once moved this score.
  return (
    effectiveSignal
    + uptime * 2.4
    + overlapQuality * 2.4
    + coverage * 0.9
  ) * syncedBias
}

export function getSustainedApplicationFactor(snapshot: BotMedalMetricSnapshot): number {
  const headroom = botBotAmplificationHeadroom(snapshot.botBotBonus)
  const overlapQuality = consolidatedSimulatedOverlap(snapshot) * headroom
  const uptime = clamp01(snapshot.uptimeFraction)
  const baseUptimeAverage = Math.max(0, snapshot.baseNumber) * uptime
  // `amplificationRatio` already IS the overlap gain, measured off the effective value:
  // (effective - base*uptime) / (base*uptime) = (bonus - 1) * overlap / uptime. Adding
  // `overlapQuality` beside it counts the same gain twice, so this now leans on the
  // measured ratio and keeps overlapQuality only as the fallback when there is no base to
  // measure against.
  const amplificationRatio = baseUptimeAverage > 0
    ? clamp01((snapshot.effectiveNumber - baseUptimeAverage) / Math.max(baseUptimeAverage, 1e-6))
    : overlapQuality
  // Coverage is no longer added here. It multiplies the value directly — a bot's worth is
  // `base × coverage × uptime × amplification` — so a caller that folds coverage into the
  // value and then multiplies by this factor would be counting reach twice.
  return Math.max(0.25, 0.35 + uptime * 0.9 + amplificationRatio * 0.85)
}

/**
 * Where the timing multiplier reaches half its maximum uplift.
 *
 * The timing terms are unnormalised sums with no natural ceiling — a realistic plan lands
 * somewhere around 200 to 350 — so a saturating `x / (x + k)` converts them to 0..1 without
 * anyone having to know their maximum. Around the middle of the observed range, so real
 * differences in alignment move the multiplier and extreme values cannot run away with it.
 */
export const BOT_MEDAL_TIMING_HALF_POINT = 250

/**
 * The most that perfect timing can be worth, as an uplift on a plan's value.
 *
 * `timingMaxUplift` on the input overrides it per plan, but NOTHING SETS IT and there is no
 * control for it, deliberately. It was exposed as one and measured to do nothing: it scales
 * the whole value signal, and now that cadence, duration and range are hard constraints every
 * candidate plan comes out already synchronised, so `timingQuality` barely differs between
 * them and the multiplier cancels. Plans at 0%, 60% and 150% were identical.
 *
 * The override stays for a caller that relaxes those constraints. A UI control does not,
 * because a knob that cannot change the answer is the same defect as a stat that is never
 * bought — it just fails in the reader's head instead of in the plan.
 */
export const BOT_MEDAL_TIMING_MAX_UPLIFT = 0.6


export function aggregateBotMedalPlanObjective(input: BotMedalPlanObjectiveInput): number {
  /*
   * One source: what the plan is worth, plus the things that are genuinely not in it.
   *
   * A bot's value is `base × coverage × uptime × [1 + (bonus - 1) × overlap]`, and
   * `totalScore` carries it — coverage multiplied in, uptime and amplification inside
   * `effectiveNumber`. Every stat therefore already contributes through the one quantity
   * that decides the plan.
   *
   * There used to be four more signals beside it — `uptimeSignal`, `overlapSignal`,
   * `prioritySignal`, `rangeSignal`, together outweighing the value itself — each a second
   * opinion about a quantity the value already contained. They did not agree with it. On
   * Golden Bot at level 0 the value says Bonus +0.042, Duration +0.010, Cooldown +0.009 and
   * Range -0.0001; the plan those signals produced bought thirty levels of Range and no
   * Cooldown at all. When a term beside the value contradicts the value, it wins by being
   * linear where the value is logarithmic, and the planner stops being about worth.
   *
   * What stays is what the value cannot see: whether activations line up in time, and the
   * penalties that express constraints rather than worth.
   */
  // `potentialScore` is not in here either, for the same reason: it is
  // `log1p(effectiveNumber) + uptime * 2.4 + overlapQuality * 2.4 + coverage * 0.9`, which
  // is the same three quantities added beside a value that already multiplies them — and it
  // uses the effective number WITHOUT coverage, so it disagreed with the value it sat next
  // to. `totalScore` is the value.
  const valueSignal = input.totalScore * 10

  /**
   * Timing MODULATES value. It does not stand beside it.
   *
   * These terms used to be added to the value, and they buried it. Measured on one bot at
   * level zero: the value contributed 2.1 and the timing terms 343 — the value was 0.6% of
   * the objective it was supposed to be. And because two untouched bots share identical
   * default cycles (20s duration, 120s cooldown), alignment is PERFECT before anything is
   * bought and every purchase degrades it. An allocator handed that objective correctly
   * concluded that the best plan was to spend nothing at all, and did.
   *
   * That is the same failure the four signals removed before this one had: a quantity on an
   * unrelated scale, added next to the value, deciding the answer. Removing those and leaving
   * these only made the surviving ones the whole objective.
   *
   * As a bounded multiplier it can express what it actually knows — that bots firing together
   * are worth more than bots firing apart — without being able to claim that no bots at all
   * are worth more than either. A plan worth nothing scores nothing however well aligned it
   * is, because zero times any multiplier is zero.
   */
  const timingSignal = (input.timingHarmonyScore * 3) + (input.averageCadence * 2)
    + (input.pairwiseCycleAlignmentScore * 2) + (input.timingPairValue * 1.5)
    + (input.coordinationScore * 5) + (input.sharedPathContinuityScore * 4)
    + (input.naturalSyncAlignmentScore * 5)
  const timingQuality = timingSignal > 0
    ? timingSignal / (timingSignal + BOT_MEDAL_TIMING_HALF_POINT)
    : 0

  // Penalties stay additive: they express constraints — a duty cycle past its useful ceiling,
  // a secondary bot's duration running ahead of the one it is meant to follow — and a
  // constraint that scaled with value would be satisfied by having less value.
  const penaltySignal = (input.unsyncedRangeShortfall * 2)
    + input.secondarySyncedDurationPenalty + input.dutyCycleOvershootPenalty

  const uplift = Number.isFinite(input.timingMaxUplift)
    ? Math.max(0, Math.min(2, input.timingMaxUplift as number))
    : BOT_MEDAL_TIMING_MAX_UPLIFT
  return (valueSignal * (1 + (uplift * timingQuality))) - penaltySignal
}


/** Shared-path coordination score from per-row timing simulation aggregates. */
export function scoreSharedPathCoordination(
  rowScores: number[],
): number {
  if (!rowScores.length) return 0
  return rowScores.reduce((sum, value) => sum + value, 0) / rowScores.length
}

export function scoreSharedPathCoordinationRow(input: {
  synced: boolean
  timingOverlapOfTotal: number
  timingOverlapOfBotUptime: number
  snapshotOverlapDisplay: number
  snapshotOverlapFraction: number
  snapshotOverlapConditioned: number
  snapshotUptime: number
  snapshotBotBotOverlap: number
}): number {
  const syncWeight = input.synced ? 1.12 : 1
  const temporal = clamp01(input.timingOverlapOfTotal)
  const spatial = clamp01(Math.max(input.snapshotOverlapConditioned, input.snapshotOverlapFraction * temporal))
  return syncWeight * (
    temporal * 2.8
    + clamp01(input.timingOverlapOfBotUptime) * 3.6
    + clamp01(input.snapshotOverlapDisplay) * 2.2
    + spatial * 2.6
    + clamp01(input.snapshotUptime) * 1.8
    + clamp01(input.snapshotBotBotOverlap) * 1.2
  )
}
