/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    BOT_MEDAL_SIM_STEP_SECONDS, BOT_MEDAL_SIM_DURATION_SECONDS, BOT_MEDAL_SIM_MIN_CYCLES, botMedalInteractionWindowSeconds, BOT_MEDAL_DEFAULT_TOWER_RANGE_METERS, BotMedalActivationTimingResult, BotMedalInteractionResult, BotMedalInteractionInput (+7 more)
 * depends    src/mechanics/bots/geometry, src/mechanics/bots/movement, src/mechanics/primitives/unity-random
 * used by    src/mechanics/bots/index, src/mechanics/calculators/specs-generated
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
import {
  BOT_ROAM_RADIUS_FACTOR,
  botCoverageFromDisplayMetres,
  botTriggerRadiusWorldUnits,
  towerMaxDistanceWorldUnits,
} from './geometry'
import { pickBotActivationDestination } from './movement'
import { UnityRandom } from '../primitives/unity-random'

export const BOT_MEDAL_SIM_STEP_SECONDS = 0.5
export const BOT_MEDAL_SIM_DURATION_SECONDS = 1800

/**
 * How many activation cycles of the slower bot the interaction window must span.
 *
 * Two bots on different cooldowns co-activate on their beat period, which is long whenever
 * the cooldowns are close but unequal. Sampling one half-hour of that — 15 cycles at a 120 s
 * cooldown — does not measure the co-activation rate, it measures where in the beat the
 * window happened to land, and for many pairs it lands somewhere they never coincide at all:
 *
 *     window 1800 s   cd 120 -> 0.120   cd 117 -> 0.000   cd 114 -> 0.000   cd 108 -> 0.000
 *     window 18000 s  cd 120 -> 0.120   cd 117 -> 0.111   cd 114 -> 0.122   cd 108 -> 0.130
 *
 * Those zeroes are the reason a planner ranking upgrades by the value they buy would never
 * buy a cooldown level: nearly every one of them breaks the alignment with the Bot Bot and
 * appears to destroy the amplification outright. The stat was not deprioritised, it was
 * measured with an instrument that could not see it.
 *
 * 150 because that is what the measurement showed: an 18,000 second window over a 120 second
 * cooldown is 150 cycles, and it was already stable there. This was 400 for a while, which
 * cost nearly three times as much simulation for no additional accuracy — and the planner
 * calls this thousands of times while pricing ladders, so it is the dominant cost in a plan.
 */
export const BOT_MEDAL_SIM_MIN_CYCLES = 150

/** The window needed to measure this pair, rather than one fixed half-hour for every pair. */
export function botMedalInteractionWindowSeconds(
  otherCooldownSeconds: number,
  botBotCooldownSeconds: number,
): number {
  const slowest = Math.max(0, otherCooldownSeconds, botBotCooldownSeconds)
  return Math.max(BOT_MEDAL_SIM_DURATION_SECONDS, slowest * BOT_MEDAL_SIM_MIN_CYCLES)
}
export const BOT_MEDAL_DEFAULT_TOWER_RANGE_METERS = 60

export interface BotMedalActivationTimingResult {
  overlapOfTotalTimeFraction: number
  overlapOfBotUptimeFraction: number
  overlapOfBotBotUptimeFraction: number
}

export interface BotMedalInteractionResult extends BotMedalActivationTimingResult {
  conditionedSpatialOverlapFraction: number
}

export interface BotMedalInteractionInput {
  otherBotLabel: string
  otherDurationSeconds: number
  otherCooldownSeconds: number
  otherRangeMeters: number
  botBotDurationSeconds: number
  botBotCooldownSeconds: number
  botBotRangeMeters: number
  sharedPath: boolean
  arenaRadiusMeters?: number
  pathSampleSeed?: number
  stepSeconds?: number
  durationSeconds?: number
}

/**
 * The share of its roam disc a bot covers, from the numbers a player reads off the card.
 *
 * There used to be a second, independent implementation of this here. It divided
 * `botEffectiveRadius` — the prefab SCALE, with the collider's 0.5 left out — by the tower's
 * display range rather than by the disc the bot actually roams over, so both terms were
 * wrong and they partly cancelled: 0.81 where the geometry gives 0.719 at 60M.
 *
 * Two implementations of one law will always drift, and this one had no way to be checked
 * against the game, because it was not in any of the game's units. It is an adapter now, and
 * `botSpatialCoverageFraction` is the only place the geometry lives.
 */
export function botMedalCoverageFraction(
  displayRangeMeters: number,
  towerRangeDisplayMeters: number,
  globalRangeBonusMeters = 0,
): number {
  return botCoverageFromDisplayMetres(
    Math.max(0, displayRangeMeters + globalRangeBonusMeters),
    towerRangeDisplayMeters,
  )
}

export function isBotActiveAtTime(
  timeSeconds: number,
  durationSeconds: number,
  cooldownSeconds: number,
): boolean {
  if (durationSeconds <= 0 || cooldownSeconds <= 0) return false
  const cyclePosition = timeSeconds % cooldownSeconds
  return cyclePosition < Math.min(durationSeconds, cooldownSeconds)
}

export function circleOverlapArea(radiusA: number, radiusB: number, distance: number): number {
  if (distance >= radiusA + radiusB) return 0
  if (distance <= Math.abs(radiusA - radiusB)) return Math.PI * Math.min(radiusA, radiusB) ** 2

  const angleA = Math.acos((distance * distance + radiusA * radiusA - radiusB * radiusB) / (2 * distance * radiusA))
  const angleB = Math.acos((distance * distance + radiusB * radiusB - radiusA * radiusA) / (2 * distance * radiusB))
  const chordArea = 0.5 * Math.sqrt(Math.max(0,
    (-distance + radiusA + radiusB)
    * (distance + radiusA - radiusB)
    * (distance - radiusA + radiusB)
    * (distance + radiusA + radiusB),
  ))

  return (radiusA * radiusA * angleA) + (radiusB * radiusB * angleB) - chordArea
}

export function circleOverlapFractionOfTarget(
  targetRadiusMeters: number,
  sourceRadiusMeters: number,
  centerDistanceMeters: number,
): number {
  if (targetRadiusMeters <= 0 || sourceRadiusMeters <= 0) return 0
  const targetArea = Math.PI * targetRadiusMeters * targetRadiusMeters
  if (targetArea <= 0) return 0
  return Math.max(0, Math.min(1, circleOverlapArea(sourceRadiusMeters, targetRadiusMeters, centerDistanceMeters) / targetArea))
}

/** Shared enemy path — Bot Bot centered on the same target as the amplified bot. */
export function sharedPathBotBotOverlapFraction(
  otherRadiusMeters: number,
  botBotRadiusMeters: number,
): number {
  if (otherRadiusMeters <= 0 || botBotRadiusMeters <= 0) return 0
  const ratio = botBotRadiusMeters / otherRadiusMeters
  return Math.max(0, Math.min(1, ratio * ratio))
}

function hashLabelToSeed(label: string): number {
  let hash = 2_166_136_261
  for (let index = 0; index < label.length; index += 1) {
    hash ^= label.charCodeAt(index)
    hash = Math.imul(hash, 16_777_619)
  }
  return hash >>> 0
}

function activationCycleIndex(timeSeconds: number, cooldownSeconds: number): number {
  if (cooldownSeconds <= 0) return 0
  return Math.floor(timeSeconds / cooldownSeconds)
}

/**
 * Where a bot sits for one activation, in display metres.
 *
 * `Bot.SetRandomDestination` is `Random.insideUnitCircle * (RADIUS_PERCENTAGE *
 * sqrt(Main.maxDistance))`, with `maxDistance` in world units — a tenth of the display
 * metres everything here works in. So the roam disc is
 * `10 * 1.3 * sqrt(arenaRadiusMeters / 10)`: about 32 m inside a 60 m arena.
 *
 * This used to pass the bot's range-as-a-fraction-of-the-arena where the game's constant
 * belongs, giving `sqrt(60) * 0.3` — a roam disc of 2.3 m. Two bots with 18 m circles placed
 * within 2.3 m of each other overlap almost completely, which is why average overlap read
 * 94% for bots whose range covers a fraction of the board.
 */
function positionForActivationCycle(
  baseSeed: number,
  botSalt: number,
  cycleIndex: number,
  arenaRadiusMeters: number,
): [number, number] {
  const rng = UnityRandom.fromSeed((baseSeed ^ botSalt ^ Math.imul(cycleIndex + 1, 2_654_435_761)) >>> 0)
  const dest = pickBotActivationDestination(
    rng,
    towerMaxDistanceWorldUnits(arenaRadiusMeters),
    BOT_ROAM_RADIUS_FACTOR,
  )
  return [dest.x, dest.y]
}

/**
 * A cache key component, cheaply.
 *
 * These two simulations are called on the order of a HUNDRED THOUSAND times for a single
 * plan — the beam search evaluates every candidate bundle against every row — and nearly all
 * of those are cache hits. So the cost of a hit is the cost of the planner, and building the
 * key with `toFixed(3)` per field made key construction the dominant expense.
 *
 * Quantising to thousandths as an integer keeps the same precision and is an order of
 * magnitude cheaper than formatting a decimal string.
 */
function keyPart(value: number): number {
  return Math.round(value * 1000)
}

const activationTimingCache = new Map<string, BotMedalActivationTimingResult>()
const interactionSimulationCache = new Map<string, BotMedalInteractionResult>()

export function simulateBotMedalActivationTiming(
  otherDurationSeconds: number,
  otherCooldownSeconds: number,
  botBotDurationSeconds: number,
  botBotCooldownSeconds: number,
  options?: { stepSeconds?: number, durationSeconds?: number },
): BotMedalActivationTimingResult {
  if (otherDurationSeconds <= 0 || otherCooldownSeconds <= 0 || botBotDurationSeconds <= 0 || botBotCooldownSeconds <= 0) {
    return {
      overlapOfTotalTimeFraction: 0,
      overlapOfBotUptimeFraction: 0,
      overlapOfBotBotUptimeFraction: 0,
    }
  }

  const stepSeconds = options?.stepSeconds ?? BOT_MEDAL_SIM_STEP_SECONDS
  const durationSeconds = options?.durationSeconds ?? BOT_MEDAL_SIM_DURATION_SECONDS

  const cacheKey = `${keyPart(otherDurationSeconds)},${keyPart(otherCooldownSeconds)},`
    + `${keyPart(botBotDurationSeconds)},${keyPart(botBotCooldownSeconds)},`
    + `${keyPart(stepSeconds)},${Math.round(durationSeconds)}`
  const cached = activationTimingCache.get(cacheKey)
  if (cached) return cached

  const totalSteps = Math.max(1, Math.round(durationSeconds / stepSeconds))
  let otherActiveSteps = 0
  let botBotActiveSteps = 0
  let bothActiveSteps = 0

  for (let step = 0; step < totalSteps; step += 1) {
    const timeSeconds = (step + 0.5) * stepSeconds
    const otherActive = isBotActiveAtTime(timeSeconds, otherDurationSeconds, otherCooldownSeconds)
    const botBotActive = isBotActiveAtTime(timeSeconds, botBotDurationSeconds, botBotCooldownSeconds)
    if (otherActive) otherActiveSteps += 1
    if (botBotActive) botBotActiveSteps += 1
    if (otherActive && botBotActive) bothActiveSteps += 1
  }

  const result = {
    overlapOfTotalTimeFraction: bothActiveSteps / totalSteps,
    overlapOfBotUptimeFraction: otherActiveSteps > 0 ? bothActiveSteps / otherActiveSteps : 0,
    overlapOfBotBotUptimeFraction: botBotActiveSteps > 0 ? bothActiveSteps / botBotActiveSteps : 0,
  }
  activationTimingCache.set(cacheKey, result)
  return result
}

export function simulateBotMedalInteraction(input: BotMedalInteractionInput): BotMedalInteractionResult {
  const {
    otherBotLabel,
    otherDurationSeconds,
    otherCooldownSeconds,
    otherRangeMeters,
    botBotDurationSeconds,
    botBotCooldownSeconds,
    botBotRangeMeters,
    sharedPath,
  } = input

  if (otherRangeMeters <= 0 || botBotRangeMeters <= 0 || otherDurationSeconds <= 0 || otherCooldownSeconds <= 0 || botBotDurationSeconds <= 0 || botBotCooldownSeconds <= 0) {
    return {
      overlapOfTotalTimeFraction: 0,
      overlapOfBotUptimeFraction: 0,
      overlapOfBotBotUptimeFraction: 0,
      conditionedSpatialOverlapFraction: 0,
    }
  }

  const stepSeconds = input.stepSeconds ?? BOT_MEDAL_SIM_STEP_SECONDS
  const durationSeconds = input.durationSeconds
    ?? botMedalInteractionWindowSeconds(otherCooldownSeconds, botBotCooldownSeconds)
  const arenaRadiusMeters = Math.max(1, input.arenaRadiusMeters ?? BOT_MEDAL_DEFAULT_TOWER_RANGE_METERS)
  const pathSampleSeed = input.pathSampleSeed ?? hashLabelToSeed(otherBotLabel)

  const cacheKey = `${otherBotLabel},${sharedPath ? 1 : 0},`
    + `${keyPart(otherDurationSeconds)},${keyPart(otherCooldownSeconds)},${keyPart(otherRangeMeters)},`
    + `${keyPart(botBotDurationSeconds)},${keyPart(botBotCooldownSeconds)},${keyPart(botBotRangeMeters)},`
    + `${keyPart(arenaRadiusMeters)},${pathSampleSeed},${keyPart(stepSeconds)},${Math.round(durationSeconds)}`
  const cached = interactionSimulationCache.get(cacheKey)
  if (cached) return cached

  // Radii and positions are both in WORLD UNITS. These used to be the raw display metres,
  // which is the localScale rather than the radius — a bit over twice the real thing, so
  // every overlap fraction came out too generous.
  const otherRadiusWorldUnits = botTriggerRadiusWorldUnits(otherRangeMeters, arenaRadiusMeters)
  const botBotRadiusWorldUnits = botTriggerRadiusWorldUnits(botBotRangeMeters, arenaRadiusMeters)

  const totalSteps = Math.max(1, Math.round(durationSeconds / stepSeconds))
  let overlapSum = 0
  let otherActiveSteps = 0
  let botBotActiveSteps = 0
  let bothActiveSteps = 0

  for (let step = 0; step < totalSteps; step += 1) {
    const timeSeconds = (step + 0.5) * stepSeconds
    const otherActive = isBotActiveAtTime(timeSeconds, otherDurationSeconds, otherCooldownSeconds)
    const botBotActive = isBotActiveAtTime(timeSeconds, botBotDurationSeconds, botBotCooldownSeconds)

    if (otherActive) otherActiveSteps += 1
    if (botBotActive) botBotActiveSteps += 1
    if (!(otherActive && botBotActive)) continue

    bothActiveSteps += 1
    const spatialOverlapFraction = sharedPath
      ? sharedPathBotBotOverlapFraction(otherRadiusWorldUnits, botBotRadiusWorldUnits)
      : (() => {
        const otherCycle = activationCycleIndex(timeSeconds, otherCooldownSeconds)
        const botBotCycle = activationCycleIndex(timeSeconds, botBotCooldownSeconds)
        const [otherX, otherY] = positionForActivationCycle(pathSampleSeed, 0x1111, otherCycle, arenaRadiusMeters)
        const [botBotX, botBotY] = positionForActivationCycle(pathSampleSeed, 0x2222, botBotCycle, arenaRadiusMeters)
        const centerDistance = Math.hypot(otherX - botBotX, otherY - botBotY)
        return circleOverlapFractionOfTarget(
          otherRadiusWorldUnits,
          botBotRadiusWorldUnits,
          centerDistance,
        )
      })()

    overlapSum += spatialOverlapFraction
  }

  const result = {
    overlapOfTotalTimeFraction: overlapSum / totalSteps,
    overlapOfBotUptimeFraction: otherActiveSteps > 0 ? overlapSum / otherActiveSteps : 0,
    overlapOfBotBotUptimeFraction: botBotActiveSteps > 0 ? overlapSum / botBotActiveSteps : 0,
    conditionedSpatialOverlapFraction: bothActiveSteps > 0 ? overlapSum / bothActiveSteps : 0,
  } satisfies BotMedalInteractionResult

  interactionSimulationCache.set(cacheKey, result)
  return result
}
