/** Bot wander movement and activation destination selection. */
/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    BOT_MOVEMENT_ARRIVAL_THRESHOLD_SQ, BotMovementState, botRandomDestinationScalar, pickBotActivationDestination, stepBotMovementTowardDestination, buildInitialBotMovementState
 * depends    src/mechanics/primitives/unity-random
 * used by    src/mechanics/bots/index, src/mechanics/bots/medal-simulation, src/mechanics/calculators/specs-generated
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */

import { UnityRandom } from '../primitives/unity-random'

export const BOT_MOVEMENT_ARRIVAL_THRESHOLD_SQ = 0.25

export interface BotMovementState {
  x: number
  y: number
  destinationX: number
  destinationY: number
  finalSpeed: number
  active: boolean
}

/**
 * A radius drawn so points land UNIFORMLY OVER THE DISC, not uniformly along the radius.
 *
 * `Bot.SetRandomDestination` multiplies `Random.insideUnitCircle`, which is uniform over the
 * circle's AREA. Scaling a plain `value()` instead is uniform in the radius, and that is a
 * different distribution: density falls off as 1/r, so points pile up near the centre and the
 * mean distance is R/2 rather than 2R/3.
 *
 * It matters because it decides how much two bots overlap by accident. Bunched toward the
 * tower they sit on top of each other most of the time, so a small Bot Bot circle already
 * catches most of a large bot's area and matching their ranges looks close to worthless.
 * Spread properly they miss each other far more often, and range parity is worth what it
 * should be.
 */
export function botRandomDestinationScalar(rng: UnityRandom, radius: number): number {
  return Math.sqrt(rng.value()) * Math.max(0, radius)
}

export function pickBotActivationDestination(
  rng: UnityRandom,
  maxDistanceDisplayMeters: number,
  radiusPercentage: number,
): { x: number, y: number } {
  const radial = Math.sqrt(Math.max(0, maxDistanceDisplayMeters)) * Math.max(0, radiusPercentage)
  // `Math.sqrt` of the draw, so destinations are uniform over the disc as
  // `Random.insideUnitCircle` is, rather than bunched toward the tower.
  const randomScale = Math.sqrt(rng.value())
  const angle = rng.value() * Math.PI * 2
  const distance = radial * randomScale
  return {
    x: Math.cos(angle) * distance,
    y: Math.sin(angle) * distance,
  }
}

export function stepBotMovementTowardDestination(
  state: BotMovementState,
  targetX: number,
  targetY: number,
  deltaSeconds: number,
): BotMovementState {
  if (!state.active) return state

  const dx = targetX - state.x
  const dy = targetY - state.y
  const distSq = dx * dx + dy * dy
  if (distSq <= BOT_MOVEMENT_ARRIVAL_THRESHOLD_SQ) {
    return { ...state, x: targetX, y: targetY }
  }

  const dist = Math.sqrt(distSq)
  const step = Math.max(0, state.finalSpeed) * Math.max(0, deltaSeconds)
  if (step >= dist) {
    return { ...state, x: targetX, y: targetY }
  }

  return {
    ...state,
    x: state.x + (dx / dist) * step,
    y: state.y + (dy / dist) * step,
  }
}

export function buildInitialBotMovementState(
  rng: UnityRandom,
  maxDistanceDisplayMeters: number,
  radiusPercentage: number,
  finalSpeed: number,
  active: boolean,
): BotMovementState {
  const dest = pickBotActivationDestination(rng, maxDistanceDisplayMeters, radiusPercentage)
  return {
    x: dest.x,
    y: dest.y,
    destinationX: dest.x,
    destinationY: dest.y,
    finalSpeed,
    active,
  }
}
