/** Bot range overlap flags and Bot-on-bot amplification helpers. */
/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    EnemyBotRangeFlags, EnemyBotRangeFlag, EMPTY_ENEMY_BOT_RANGE_FLAGS, EnemyBotRangeTriggerKind, applyEnemyBotRangeEnter, applyEnemyBotRangeExit, computeAverageAmplifiedBotMetric, BotBotAmplificationInput (+2 more)
 * depends    src/mechanics/bots/hit-multiplier
 * used by    src/data/bots/data, src/mechanics/bots/index, src/mechanics/calculators/specs-generated
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */

import { botBotBoostedMultiplier } from './hit-multiplier'

export interface EnemyBotRangeFlags {
  stunBotRange: boolean
  coinBotRange: boolean
  flameBotDamageReduction: boolean
  amplifyLightning: boolean
  swampPoison: boolean
}

export type EnemyBotRangeFlag = keyof EnemyBotRangeFlags

export const EMPTY_ENEMY_BOT_RANGE_FLAGS: EnemyBotRangeFlags = {
  stunBotRange: false,
  coinBotRange: false,
  flameBotDamageReduction: false,
  amplifyLightning: false,
  swampPoison: false,
}

export type EnemyBotRangeTriggerKind =
  | 'stunBot'
  | 'goldenBot'
  | 'amplifyBotEnemy'
  | 'flameBotDr'
  | 'swampPoison'

const ENTER_FLAG_BY_TRIGGER: Record<EnemyBotRangeTriggerKind, EnemyBotRangeFlag> = {
  stunBot: 'stunBotRange',
  goldenBot: 'coinBotRange',
  amplifyBotEnemy: 'amplifyLightning',
  flameBotDr: 'flameBotDamageReduction',
  swampPoison: 'swampPoison',
}

export function applyEnemyBotRangeEnter(
  flags: EnemyBotRangeFlags,
  trigger: EnemyBotRangeTriggerKind,
): EnemyBotRangeFlags {
  const key = ENTER_FLAG_BY_TRIGGER[trigger]
  return key ? { ...flags, [key]: true } : flags
}

export function applyEnemyBotRangeExit(
  flags: EnemyBotRangeFlags,
  trigger: EnemyBotRangeTriggerKind,
): EnemyBotRangeFlags {
  const key = ENTER_FLAG_BY_TRIGGER[trigger]
  return key ? { ...flags, [key]: false } : flags
}

function clamp01(value: number): number {
  return Math.max(0, Math.min(1, value))
}

export function computeAverageAmplifiedBotMetric(
  baseNumber: number,
  projectedNumber: number,
  uptimeFraction: number,
  overlapApplicationFraction: number,
): number {
  const baseAverage = Math.max(0, baseNumber) * clamp01(uptimeFraction)
  const overlapGain = Math.max(0, projectedNumber - baseNumber) * clamp01(overlapApplicationFraction)
  return baseAverage + overlapGain
}

export interface BotBotAmplificationInput {
  botBotBonus: number
  /** How much of the time the Bot Bot is up — its own duration over its own cooldown. */
  temporalOverlapFraction: number
  /** How much of the play area its radius covers while it is up. */
  spatialOverlapFraction: number
}

/**
 * The share of enemy-instants that are inside the Bot Bot's radius while it is active.
 *
 * This is the `P` in `stat * (1 + (bonus - 1) * P)`, and it is a property of the BOT BOT —
 * its uptime and its radius — not of whichever bot is being amplified.
 */
export function botBotAmplificationApplicationFraction(input: BotBotAmplificationInput): number {
  const temporal = clamp01(input.temporalOverlapFraction)
  const spatial = clamp01(input.spatialOverlapFraction)
  return temporal * (spatial > 0 ? spatial : 1)
}

export function botBotPeakStatMultiplier(
  botBotBonus: number,
  applicationFraction: number,
): number {
  return botBotBoostedMultiplier(Math.max(1, botBotBonus), applicationFraction)
}
