/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    Registry, IN_MONOREPO, loadedRegistries, expectedRegistries, ToolEntry, everyTool, callableTools, toolsCallableWithNoArguments
 * depends    mcp/server.mjs, src/mechanics/repo-root
 * used by    —
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
import { existsSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { isMonorepoCheckout } from '../src/mechanics/repo-root'
// @ts-expect-error — the MCP servers are plain ESM JavaScript with no declarations.
import { TOOLS, TOWER_ORACLE_TOOLS } from './server.mjs'

/**
 * One place that knows what "every tool" means.
 *
 * The catalog an agent sees is assembled from three registries — the SDK tools, the oracle tools,
 * and the Effective Paths tools in a sibling server. Every audit in this directory was written
 * against whichever subset was nearest to hand, and twice that produced a guard with the same
 * blind spot as the bug it was written for:
 *
 * - The prototype sweep read `TOOLS` alone, reported "oracle_get is not registered" instead of
 *   testing it, and never saw the epaths tools at all.
 * - The parameter audit read two of three, passed, and missed eight bare parameters — five of
 *   them on a mutating tool.
 *
 * That is the same shape as the `list_modules` defect those audits exist to catch: a count over
 * one registry describing a surface made of several. So the registry is assembled once, here, and
 * a test that wants a subset has to say which and why rather than getting one by accident.
 *
 * ## Why the classifications are hand-written
 *
 * `mutates` and `reachesNetwork` decide whether a sweep may call a tool at all, and getting one
 * wrong is expensive in a way a wrong description is not — an unlisted mutating tool gets invoked
 * by an audit. A name-pattern heuristic would be quietly wrong the first time someone names a tool
 * badly.
 *
 * `REVIEWED` is what makes that safe: every registered tool must appear in it, and `everyTool()`
 * throws otherwise. A new tool is therefore a build failure until someone has looked at it and
 * decided, rather than defaulting to "harmless" — which is the assumption that would eventually
 * hand a sweep something that writes.
 *
 * That sentence used to be in this docblock while the code did nothing of the kind: `MUTATES.has`
 * simply returned false for an unknown name. A comment claiming a guarantee the code does not make
 * is the same defect this whole directory has been hunting, written by the person hunting it.
 */

const HERE = path.dirname(fileURLToPath(import.meta.url))
const EPATHS_SERVER = path.resolve(
  HERE, '..', '..', '..', 'tools', 'effective-paths-oracle', 'server.mjs',
)

export type Registry = 'sdk' | 'oracle' | 'epaths'

/**
 * Whether this checkout is the development monorepo, decided WITHOUT looking at the epaths server.
 *
 * Two of the three registries ship with the package; the Effective Paths tools live in a sibling
 * directory that exists only here. So "all three registries loaded" is true in the monorepo and
 * false, legitimately, everywhere else — and a guard asserting three unconditionally fails in the
 * published repository, which is exactly what it did.
 *
 * The signal has to be independent of `EPATHS_SERVER` or the guard becomes vacuous: gating "epaths
 * loaded" on "the epaths file exists" compares a thing to itself and passes however broken the
 * server is. `isMonorepoCheckout` looks for `scripts/mechanics-trust/`, which is a different fact
 * about a different directory. So if that server is moved, renamed or made unloadable while this
 * is still the monorepo, the two disagree and the audit fails — which is the regression the check
 * is actually for.
 */
export const IN_MONOREPO: boolean = isMonorepoCheckout()

/** The registries that actually loaded, for a test that must not assume all of them are here. */
export function loadedRegistries(): Registry[] {
  return [...new Set(Object.values(everyTool()).map(tool => tool.registry))].sort()
}

/** What `loadedRegistries()` should be in this checkout. */
export function expectedRegistries(): Registry[] {
  return IN_MONOREPO ? ['epaths', 'oracle', 'sdk'] : ['oracle', 'sdk']
}

export interface ToolEntry {
  name: string
  registry: Registry
  description?: string
  inputSchema?: {
    type?: string
    properties?: Record<string, { type?: unknown, enum?: unknown[], description?: string }>
    required?: string[]
  }
  run: (args: unknown) => unknown
  /** Writes something — a file, a graph, a spreadsheet cell. Never called by an audit. */
  mutates: boolean
  /** Leaves the process: HTTP, a spawned CLI, the Sheets API. Never called by a fast sweep. */
  reachesNetwork: boolean
}

/**
 * Tools that write. An audit must never call one.
 *
 * `record_ep_relation` is on the list despite being deprecated and returning only instructions:
 * its name says it records, and a classification that depends on reading the body is one that
 * rots the moment the body changes.
 */
const MUTATES = new Set([
  'begin_mechanic_task',
  'record_mechanic_note',
  'record_work_status',
  'record_ep_relation',
  'sdk_graph_mutate',
  'ep_graph_mutate',
  'sdk_doctor_autofix',
  'sdk_doctor_repair',
  'sdk_sandbox_run',
  'write_cells',
  'trust_drift_check',
  'sdk_docs_generate',
])

/**
 * Tools that leave the process.
 *
 * Every epaths tool talks to the Sheets API, so the whole registry is network-bound and is marked
 * as such rather than enumerated. The rest are named: the wiki fetchers, and the SDK tools that
 * spawn a monorepo CLI.
 */
const REACHES_NETWORK = new Set([
  'wiki_page',
  'wiki_search',
  'sdk_graph_get',
  'sdk_graph_context',
  'sdk_graph_render',
  'sdk_graph_validate',
  'sdk_kernel_load',
  'sdk_registry_get',
  'sdk_save_graph_get',
  'sdk_debug_snapshot',
  'sdk_debug_watch',
  'sdk_debug_validate',
  'sdk_debug_trace',
  'sdk_doctor_check',
  'sdk_doctor_prescribe',
  'sdk_doctor_validate',
  'sdk_lsp_diagnostics',
  'sdk_planner_compile',
  'trust_coverage_report',
])

/**
 * Every tool name that has been looked at and classified.
 *
 * Not a duplicate of the two sets above: those say what a tool DOES, this says someone decided.
 * Without it, "absent from MUTATES" and "never reviewed" are the same state, and the safe-looking
 * one wins by default.
 */
const REVIEWED = new Set([
  'begin_mechanic_task', 'calc_chart', 'calc_describe',
  'calc_graph', 'calc_list', 'calc_run',
  'compliance_contract', 'decode_save', 'define_term',
  'describe_schema', 'ep_graph_get', 'ep_graph_mutate',
  'ep_graph_render', 'ep_graph_validate', 'eval_formula',
  'get_export', 'input_ranges', 'inspect_tab_ui',
  'list_exports', 'list_lambdas', 'mcp_contract',
  'mirror_map', 'oracle_brief', 'oracle_contradictions',
  'oracle_coverage', 'oracle_expand', 'oracle_footguns',
  'oracle_get', 'oracle_map', 'oracle_search',
  'oracle_traps', 'plan_effective_path', 'read_ids',
  'read_path_display', 'read_range', 'record_ep_relation',
  'record_mechanic_note', 'record_work_status', 'run_extractor',
  'sdk_debug_snapshot', 'sdk_debug_trace', 'sdk_debug_validate',
  'sdk_debug_watch', 'sdk_docs_generate', 'sdk_doctor_autofix',
  'sdk_doctor_check', 'sdk_doctor_prescribe', 'sdk_doctor_repair',
  'sdk_doctor_validate', 'sdk_graph_context', 'sdk_graph_get',
  'sdk_graph_mutate', 'sdk_graph_render', 'sdk_graph_validate',
  'sdk_kernel_load', 'sdk_lsp_diagnostics', 'sdk_planner_compile',
  'sdk_registry_get', 'sdk_sandbox_run', 'sdk_save_graph_get',
  'sheet_info', 'trust_coverage_report', 'trust_drift_check',
  'wiki_page', 'wiki_search', 'write_cells',
])

let cached: Record<string, ToolEntry> | null = null

/** Every tool the assembled catalog exposes, from every registry. */
export function everyTool(): Record<string, ToolEntry> {
  if (cached) return cached

  const registries: [Registry, Record<string, unknown>][] = [
    ['sdk', TOOLS],
    ['oracle', TOWER_ORACLE_TOOLS],
  ]

  if (existsSync(EPATHS_SERVER)) {
    /*
     * `require` rather than `await import`, so this stays synchronous and a test can build its
     * case list at module scope. Vitest transforms this file, and the epaths server loads under
     * that transform — unlike `mechanics-server.mjs`, which does not and is read out-of-process
     * where it is needed.
     */
    // eslint-disable-next-line @typescript-eslint/no-require-imports -- see above
    const epaths = require(EPATHS_SERVER) as { TOOLS: Record<string, unknown> }
    registries.push(['epaths', epaths.TOOLS])
  }

  const all: Record<string, ToolEntry> = {}
  for (const [registry, tools] of registries) {
    for (const [name, def] of Object.entries(tools)) {
      const entry = def as Omit<ToolEntry, 'name' | 'registry' | 'mutates' | 'reachesNetwork'>
      all[name] = {
        ...entry,
        name,
        registry,
        mutates: MUTATES.has(name),
        reachesNetwork: REACHES_NETWORK.has(name) || registry === 'epaths',
      }
    }
  }

  const unreviewed = Object.keys(all).filter(name => !REVIEWED.has(name))
  if (unreviewed.length > 0) {
    throw new Error(
      `${unreviewed.length} tool(s) have never been classified: ${unreviewed.join(', ')}.
`
      + 'Add each to REVIEWED in mcp/every-tool.ts, and to MUTATES / REACHES_NETWORK if it writes '
      + 'or leaves the process. An audit calls whatever it is handed.',
    )
  }

  cached = all
  return all
}

/**
 * The tools a sweep may actually call, with the exclusions made explicit.
 *
 * Filtering is a parameter rather than a default so a reader can see what a given audit did NOT
 * cover. A sweep that quietly skipped the network tools would look complete and be a third of one.
 */
export function callableTools(
  { includeMutating = false, includeNetwork = false } = {},
): ToolEntry[] {
  return Object.values(everyTool())
    .filter(tool => includeMutating || !tool.mutates)
    .filter(tool => includeNetwork || !tool.reachesNetwork)
    .sort((a, b) => a.name.localeCompare(b.name))
}

/** Tools taking no required argument, so `run({})` is a call a client can really make. */
export function toolsCallableWithNoArguments(options?: Parameters<typeof callableTools>[0]) {
  return callableTools(options).filter(tool => (tool.inputSchema?.required ?? []).length === 0)
}
