/**
 * The closest known names to what someone typed.
 *
 * Every tool that resolves a caller-supplied identifier ends up needing this, and before it lived
 * in one place there were three implementations across three files, all substring-only. That is
 * the wrong shape for the case it exists to serve: `'modules'.includes('moduls')` is false, so a
 * single dropped letter — the ordinary typo — produced an empty list, and a suggestion list that
 * cannot survive one missing character is decoration.
 *
 * Containment is kept alongside edit distance so a genuine fragment ("uw", "lab") still finds the
 * longer names it appears in. Beyond two edits it is a different word, and offering it is worse
 * than offering nothing: a confident wrong suggestion sends a caller somewhere real and useless.
 *
 * The oracle's own `missSuggestions` and `resolution.alternatives` are deliberately NOT routed
 * through here. Those resolve semantically over the knowledge graph — scoring labels, summaries
 * and traps — which is a different question from "which of these strings did you mean", and
 * collapsing the two would make the oracle worse to make the code shorter.
 */
/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    editDistance, nearestNames
 * depends    —
 * used by    —
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */

/** Levenshtein distance. Cheap enough over a few thousand short strings to not need a cache. */
export function editDistance(a, b) {
  let previous = Array.from({ length: b.length + 1 }, (_, index) => index)

  for (let i = 1; i <= a.length; i += 1) {
    const current = [i]
    for (let j = 1; j <= b.length; j += 1) {
      current[j] = Math.min(
        previous[j] + 1,
        current[j - 1] + 1,
        previous[j - 1] + (a[i - 1] === b[j - 1] ? 0 : 1),
      )
    }
    previous = current
  }

  return previous[b.length]
}

/**
 * Candidates worth offering for `query`, best first.
 *
 * Returns an empty array when nothing is close. That is a real answer — see the note above about
 * confident wrong suggestions.
 */
export function nearestNames(query, candidates, limit = 8) {
  const wanted = String(query).toLowerCase()
  if (!wanted) return []

  return [...new Set(candidates)]
    .map((name) => {
      const lower = String(name).toLowerCase()
      const contains = lower.includes(wanted) || wanted.includes(lower)
      return { name, score: contains ? 0 : editDistance(wanted, lower) }
    })
    .filter(entry => entry.score <= 2)
    .sort((a, b) => a.score - b.score || String(a.name).localeCompare(String(b.name)))
    .slice(0, limit)
    .map(entry => entry.name)
}
