/**
 * Effective Paths — assist module efficiency, settled.
 *
 * This corner has hidden three separate errors while porting: two upgrades
 * missing from the eHP lab paths, a units mismatch, and a near-miss where
 * three same-named candidates were about to be summed into one. All three came
 * from the same gap — there are **two** quantities here, not one, and they are
 * bought on different paths with different currencies.
 *
 * ## The two quantities
 *
 * An assist module contributes a share of what a primary module would. That
 * share is:
 *
 * ```text
 * efficiency = (1 + stoneLevel + labLevel) / 100
 * ```
 *
 * - **`stoneLevel`** is the slot upgrade, bought with Power Stones, priced
 *   `12 + 3 × level`. `Data_Val_Tables!EO:ET` is the ladder.
 * - **`labLevel`** is the Assist Module Bonus / Substats lab, 0–30, bought
 *   with coins and research time — and also purchasable on the coin path.
 * - The leading **`1`** is the point every assist module has for free.
 *
 * ## Why the caps differ
 *
 * | | Stone levels | Lab | Total |
 * |---|---|---|---|
 * | Multiplier ("Bonus") | 0–99 → 100% | +30 | **130%** |
 * | Substat | 0–69 → 70% | +30 | **100%** |
 *
 * The sheet stops the substat path at 69 and the multiplier path at 99, and
 * the cost table simply has no substat price past 69. So a fully invested
 * assist module gives 130% of a primary's *multiplier* and 100% of its
 * *substats* — the multiplier can exceed a primary, the substats cannot.
 *
 * ## The four categories are independent
 *
 * Cannon, Armor, Generator and Core each have their own pair of levels. The
 * damage grid reads Cannon for bullet stats, Armor for the shockwave and Core
 * for ultimate weapons; the eHP grid reads Armor and Generator. Nothing reads
 * the Generator substat for damage, which is why that candidate column is
 * blank on the damage matrix.
 */
/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    ASSIST_MULTIPLIER_MAX_STONE_LEVEL, ASSIST_SUBSTAT_MAX_STONE_LEVEL, ASSIST_LAB_MAX_LEVEL, ASSIST_MULTIPLIER_MAX_EFFICIENCY, ASSIST_SUBSTAT_MAX_EFFICIENCY, AssistEfficiencyKind, AssistModuleCategory, assistEfficiencyStoneCost (+3 more)
 * depends    src/data/modules/bonus
 * used by    src/mechanics/calculators/specs-generated, src/mechanics/effective-paths/edamage-plan, src/mechanics/effective-paths/eecon-plan, src/mechanics/effective-paths/index
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */

/** The highest stone level for each kind of assist efficiency. */
import type { ModuleCalcType } from '../../data/modules/bonus'

export const ASSIST_MULTIPLIER_MAX_STONE_LEVEL = 99
export const ASSIST_SUBSTAT_MAX_STONE_LEVEL = 69

/** The Assist Module Bonus and Substats labs both stop at 30. */
export const ASSIST_LAB_MAX_LEVEL = 30

/** What a fully invested assist module gives, as a fraction. */
export const ASSIST_MULTIPLIER_MAX_EFFICIENCY = 1.3
export const ASSIST_SUBSTAT_MAX_EFFICIENCY = 1

/** Which of the two an upgrade moves. */
export type AssistEfficiencyKind = 'multiplier' | 'substat'

/**
 * The module categories, each with its own independent pair of levels.
 *
 * The same four the module bonus tables are keyed by, so this is an alias rather than a second
 * copy of the union. Two identical literal unions under two names is the shape that lets one of
 * them drift: add a fifth category to one and the other still compiles, still type-checks, and
 * silently covers three quarters of the game.
 */
export type AssistModuleCategory = ModuleCalcType

/**
 * Power Stones to take a slot upgrade from `level - 1` to `level`.
 *
 * `12 + 3 × level`, which the sheet writes inline and the data table confirms
 * at every rung: level 1 costs 15, level 99 costs 309. Returns `null` past the
 * kind's own cap rather than pricing a level that cannot be bought — the
 * substat ladder has no entry past 69.
 */
export function assistEfficiencyStoneCost(
  kind: AssistEfficiencyKind,
  level: number,
): number | null {
  if (!Number.isInteger(level) || level < 1) return null
  if (level > maxStoneLevel(kind)) return null
  return 12 + 3 * level
}

/** The highest stone level a kind can reach. */
export function maxStoneLevel(kind: AssistEfficiencyKind): number {
  return kind === 'multiplier'
    ? ASSIST_MULTIPLIER_MAX_STONE_LEVEL
    : ASSIST_SUBSTAT_MAX_STONE_LEVEL
}

/**
 * The efficiency a stone level and a lab level give together, as a fraction.
 *
 * The same `(1 + stone + lab) / 100` every `EPH_*` and `EPD_*` function
 * applies, in one place. `hasAssist` false is zero rather than the bare 1% —
 * there is no module to be efficient with.
 */
export function assistEfficiency(input: {
  hasAssist: boolean
  stoneLevel: number
  labLevel: number
}): number {
  if (!input.hasAssist) return 0
  return (1 + input.stoneLevel + input.labLevel) / 100
}

/** Total Power Stones to take a slot upgrade from one level to another. */
export function cumulativeAssistEfficiencyStoneCost(
  kind: AssistEfficiencyKind,
  fromLevel: number,
  toLevel: number,
): number | null {
  if (!Number.isInteger(fromLevel) || !Number.isInteger(toLevel)) return null
  if (fromLevel < 0 || toLevel < fromLevel || toLevel > maxStoneLevel(kind)) return null

  let total = 0
  for (let level = fromLevel + 1; level <= toLevel; level++) {
    const step = assistEfficiencyStoneCost(kind, level)
    if (step === null) return null
    total += step
  }
  return total
}
