/**
 * Attribution for the Effective Paths formulas.
 *
 * The `effective-paths-*` modules in this package are ports of the community
 * "Effective Paths" spreadsheet. The math is the maintainers' work, not ours;
 * this package only translates it into TypeScript so other tools can reuse it.
 *
 * Anything built on those formulas should carry this credit somewhere a user
 * can see it. {@link EFFECTIVE_PATHS_ATTRIBUTION} is a ready-made line for that.
 *
 * Names are taken from the sheet's own Home Page as of the version in
 * {@link EFFECTIVE_PATHS_SOURCE}.
 */
/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    EffectivePathsCredit, EFFECTIVE_PATHS_AUTHORS, EFFECTIVE_PATHS_MAINTAINERS, EFFECTIVE_PATHS_CONTRIBUTORS, EFFECTIVE_PATHS_SOURCE, EFFECTIVE_PATHS_SUPPORT, effectivePathsAttribution, EFFECTIVE_PATHS_ATTRIBUTION (+2 more)
 * depends    src/data/effective-paths-coin-costs.json
 * used by    src/contributions/index, src/mechanics/calculators/specs-generated, src/mechanics/effective-paths/index
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */

import coinCosts from '../../data/effective-paths-coin-costs.json'

export interface EffectivePathsCredit {
  /** Name as the sheet spells it. */
  readonly name: string
  /** The role the sheet gives them, where it gives one. */
  readonly role?: string
}

/** The sheet's primary authors, as listed under "Thank your favorite contributor". */
export const EFFECTIVE_PATHS_AUTHORS: readonly EffectivePathsCredit[] = [
  { name: 'Mattew', role: 'IDS Master' },
  { name: 'QuietFanta', role: 'eEcon Squirrel' },
] as const

/** Listed under "Other Maintainers & helpers". */
export const EFFECTIVE_PATHS_MAINTAINERS: readonly EffectivePathsCredit[] = [
  { name: 'Bisse' },
  { name: 'Shiriru' },
  { name: 'Gladiator' },
  { name: 'Meringue' },
] as const

/**
 * Listed on the sheet as the people who helped build it — "NOT ALL HEROES WEAR
 * CAPES", in its words.
 */
export const EFFECTIVE_PATHS_CONTRIBUTORS: readonly EffectivePathsCredit[] = [
  { name: '1410c' },
  { name: 'TP' },
  { name: 'Andy' },
  { name: 'Đ4ЯK3И5TØИ3' },
  { name: 'Audacious' },
  { name: 'Keizhac' },
  { name: 'IGotSlain' },
  { name: 'zAlpha' },
  { name: 'Nykola' },
  { name: 'Phil' },
  { name: 'Solaaar' },
  { name: 'iam_ImpulsE' },
  { name: 'TravellingPotato', role: 'grammar' },
  { name: 'Boromir' },
] as const

/** Pull a version like `v5.10.02` out of the ported data's source filename. */
function sheetVersionFromSource(source: string): string {
  const match = /v\d+(?:\.\d+)+/i.exec(source)
  return match ? match[0] : 'unversioned'
}

/**
 * The sheet version the ported data in this package came from.
 *
 * Derived from the data itself — the `source` stamped into
 * `effective-paths-coin-costs.json` at extraction — so it can never drift from
 * what actually shipped and never needs hand-editing. Surfaces that evaluate a
 * newer workbook (the site runs the live extraction) should pass that version
 * to {@link effectivePathsAttribution} instead of relying on this default.
 */
export const EFFECTIVE_PATHS_SOURCE = {
  version: sheetVersionFromSource((coinCosts as { source?: string }).source ?? ''),
  spreadsheetUrl: 'https://docs.google.com/spreadsheets/d/1YwZtKP6B4WYhRba5T6APJ1YxKNdfnIGQnprgnxmO7zc',
} as const

/**
 * How to support the Effective Paths team directly.
 *
 * Tech Tree Games' webstore credits a creator code on purchase, so entering `SHEETLORD`
 * sends support to the sheet's team at no extra cost to the buyer. This is the only way
 * this package can meaningfully give back for formulas it did not write.
 */
export const EFFECTIVE_PATHS_SUPPORT = {
  creatorCode: 'SHEETLORD',
  storeUrl: 'https://store.techtreegames.com/thetower/',
} as const

/**
 * Compose the one-line credit for a given sheet version.
 *
 * Pass the version the calling surface actually evaluates; it defaults to the
 * package's own ported-from version in {@link EFFECTIVE_PATHS_SOURCE}. Either
 * way the version is data, never a hand-typed literal — so the credit stays
 * correct as the sheet moves on.
 */
export function effectivePathsAttribution(
  sheetVersion: string = EFFECTIVE_PATHS_SOURCE.version,
): string {
  return 'Effective Paths formulas by Mattew, QuietFanta, Bisse and the Effective Paths maintainers. '
    + `Ported from the community spreadsheet (${sheetVersion}).`
}

/** A one-line credit suitable for a footer or an about box. */
export const EFFECTIVE_PATHS_ATTRIBUTION = effectivePathsAttribution()

/**
 * The credit line plus the ask, for a given sheet version. Use this where there
 * is room for two sentences; use {@link effectivePathsAttribution} where there
 * is only room for one.
 */
export function effectivePathsAttributionWithSupport(
  sheetVersion: string = EFFECTIVE_PATHS_SOURCE.version,
): string {
  return `${effectivePathsAttribution(sheetVersion)} Support the Effective Paths team with creator code `
    + `${EFFECTIVE_PATHS_SUPPORT.creatorCode} in The Tower webstore.`
}

/** The credit line plus the ask, at the package's own ported-from version. */
export const EFFECTIVE_PATHS_ATTRIBUTION_WITH_SUPPORT = effectivePathsAttributionWithSupport()
