/**
 * Effective Paths — how the damage tab reads a substat, and bullets per second.
 *
 * Every stat column on the damage grid opens the same way:
 *
 * ```text
 * SubstatAssistCap, EPG_ASSIST_SUB_CAP(hasAssist, stoneCap, labCap)
 * Substat,          $AM$<row> + SubstatAssistCap * $AO$<row>
 * ```
 *
 * — the primary module's substat at face value, plus the assist's scaled by
 * the assist capacity. Writing it once here keeps thirty-odd columns from each
 * having their own copy, and keeps the capacity from being applied to the
 * primary by accident.
 *
 * Credit for the original formulas belongs to the Effective Paths maintainers —
 * see `effective-paths-credits.ts`.
 */
/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    SubstatPair, AssistCapacities, ModuleCategory, assistCapacities, combinedSubstat, bulletsPerSecond
 * depends    src/mechanics/effective-paths/generics
 * used by    src/mechanics/calculators/specs-generated, src/mechanics/effective-paths/edamage-compute, src/mechanics/effective-paths/edamage-config, src/mechanics/effective-paths/eecon-stats, src/mechanics/effective-paths/index
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */

import { assistSubstatCap } from './generics'

/** A module pair's contribution to one stat. */
export interface SubstatPair {
  /** The primary module's substat, at face value. */
  primary: number
  /** The assist module's substat, before the capacity scaling. */
  assist: number
}

/**
 * The four module categories the damage tab reads, each with its own assist
 * capacity — Cannon for the bullet stats, Armor for the shockwave, Core for
 * the ultimate weapons, Generator for the economy ones.
 */
export interface AssistCapacities {
  cannon: number
  armor: number
  core: number
  generator: number
}

export type ModuleCategory = keyof AssistCapacities

/** Build the four capacities from each category's own stone and lab levels. */
export function assistCapacities(input: Record<ModuleCategory, {
  hasAssist: boolean
  /** Capacity bought with stones, in percentage points. */
  stoneCap: number
  /** Capacity from the Assist Module Substats lab, in percentage points. */
  labCap: number
}>): AssistCapacities {
  const of = (category: ModuleCategory) =>
    assistSubstatCap(input[category].hasAssist, input[category].stoneCap, input[category].labCap)

  return {
    cannon: of('cannon'),
    armor: of('armor'),
    core: of('core'),
    generator: of('generator'),
  }
}

/**
 * `$AM$n + SubstatAssistCap * $AO$n` — one stat's combined substat.
 *
 * Only the assist half is scaled. Applying the capacity to the primary too is
 * the mistake this exists to prevent, and it would be invisible in the total.
 */
export function combinedSubstat(pair: SubstatPair, assistCapacity: number): number {
  return pair.primary + assistCapacity * pair.assist
}

/**
 * `BULLET_PER_SECOND` — bullets a second from attack speed.
 *
 * A fitted quadratic rather than anything derived, times 1.3. The constants are
 * the sheet's own and are not round numbers, so they are reproduced exactly
 * rather than tidied.
 */
export function bulletsPerSecond(attackSpeed: number): number {
  return ((0.01413 * attackSpeed ** 2) + (4.01278 * attackSpeed) + 92.8885) * 1.3
}
