/**
 * eDamage lab Current/Target/Max table (`BB5:BE50`) → planner `targetLevels`.
 *
 * Row labels are structural (live `eDamage!BB5:BB50`); IDS dumps often omit
 * `BB` and only carry `BC`/`BD`/`BE` numbers. A blank `BD` means no player
 * target (fall back to max). A numeric `0` is a real stop — `EPG_LEVEL_CHECK`
 * hides the column when the next level is past that stop.
 */
/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    EDAMAGE_LAB_LEVEL_TABLE_NAMES, edamageLabTargetLevelsFromSheet
 * depends    src/mechanics/effective-paths/edamage-candidates, src/mechanics/effective-paths/edamage-levels
 * used by    src/mechanics/calculators/specs-generated, src/mechanics/effective-paths/index
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */

import { EFFECTIVE_DAMAGE_LAB_CANDIDATES } from './edamage-candidates'
import { ZERO_EFFECTIVE_DAMAGE_LEVELS } from './edamage-levels'

/**
 * `eDamage!BB5:BB50` — lab names in sheet order (verified live v5.10).
 *
 * Display names here follow the level table, which spells Super Crit as
 * "Super Critical …"; the ROI matrix uses "Super Crit …". Matching is by
 * normalised letters/digits so both resolve to the same upgrade id.
 */
export const EDAMAGE_LAB_LEVEL_TABLE_NAMES: readonly string[] = [
  'Dissonant Echo - Attack',
  'Dissonant Echo - Ultimate Weapons',
  'Starting Cash',
  'Damage',
  'Attack Speed',
  'Critical Chance',
  'Critical Factor',
  'Range',
  'Damage / Meter',
  'Multishot Chance',
  'Multishot Targets',
  'Rapid Fire Chance',
  'Rapid Fire Duration',
  'Bounce Shot Chance',
  'Bounce Shot Targets',
  'Super Critical Chance',
  'Super Critical Mult',
  'Max Rend Armor Multiplier',
  'Shockwave Size',
  'Shockwave Frequency',
  'Land Mine Chance',
  'Package Chance',
  'Package After Boss',
  'Standard Perks Bonus',
  'Improve Trade-off Perks',
  'Death Wave Damage Amplifier',
  'Shock Multiplier',
  'Shock Chance',
  'Spotlight Missiles',
  'Missile Amplifier',
  'Swamp Rend',
  'Inner Land Mine - Chrono Jump',
  'Super Tower Bonus',
  'Damage Mastery',
  'Attack Speed Mastery',
  'Critical Chance Mastery',
  'Range Mastery',
  'Super Tower Mastery',
  'Ultimate Crit Mastery',
  'Demon Mode Mastery',
  'Assist Module Substats - Cannon',
  'Assist Module Substats - Armor',
  'Assist Module Substats - Generator',
  'Assist Module Substats - Core',
  'Assist Module Bonus - Cannon',
  'Assist Module Bonus - Core',
] as const

const LAB_TABLE_FIRST_ROW = 5

const normalize = (name: string): string => name.toLowerCase().replace(/[^a-z0-9]+/g, '')

/** Table / matrix label → lab-band upgrade id (`lab.range`). */
const LAB_UPGRADE_ID_BY_NORMALIZED = new Map<string, string>()
{
  const keys = Object.keys(ZERO_EFFECTIVE_DAMAGE_LEVELS.lab)
  for (let i = 0; i < EFFECTIVE_DAMAGE_LAB_CANDIDATES.length; i += 1) {
    const candidate = EFFECTIVE_DAMAGE_LAB_CANDIDATES[i]!
    const key = keys[i]
    if (!key) continue
    LAB_UPGRADE_ID_BY_NORMALIZED.set(normalize(candidate.sheetName), `lab.${key}`)
  }
  // Level-table spellings that differ from the ROI matrix headers.
  LAB_UPGRADE_ID_BY_NORMALIZED.set(normalize('Super Critical Chance'), 'lab.superCritChance')
  LAB_UPGRADE_ID_BY_NORMALIZED.set(normalize('Super Critical Mult'), 'lab.superCritMulti')
}
function readTarget(raw: unknown): number | null {
  if (raw === null || raw === undefined) return null
  if (typeof raw === 'number' && Number.isFinite(raw)) return raw
  if (typeof raw === 'string') {
    const text = raw.trim()
    // Blank / dash = no target set. Do NOT coerce to 0 — 0 is a real stop.
    if (text === '' || text === '-') return null
    if (/^[+-]?\d+(\.\d+)?$/.test(text)) return Number(text)
  }
  return null
}

/**
 * Build `targetLevels` keyed by upgrade id from an eDamage cell dump.
 *
 * Only rows with an explicit `BD` value are included. Absent keys mean the
 * planner uses the catalog max (sheet `LEN(target)=0` behaviour).
 */
export function edamageLabTargetLevelsFromSheet(
  source: Readonly<Record<string, unknown>>,
): Record<string, number> {
  const out: Record<string, number> = {}
  for (let i = 0; i < EDAMAGE_LAB_LEVEL_TABLE_NAMES.length; i += 1) {
    const row = LAB_TABLE_FIRST_ROW + i
    const target = readTarget(source[`BD${row}`])
    if (target === null) continue
    const tableName = EDAMAGE_LAB_LEVEL_TABLE_NAMES[i]!
    const id = LAB_UPGRADE_ID_BY_NORMALIZED.get(normalize(tableName))
    if (!id) continue
    out[id] = target
  }
  return out
}
