/**
 * Effective Paths — effective damage, end to end.
 *
 * `eDamage!ES5` is one multiplication of seven factors, and every one of those
 * is a column of its own reading a dozen more. This walks the grid in the
 * sheet's own order: the base, the crit pair, the bullet multiplier, Spotlight,
 * the ultimate weapons and the slow — with each step named for the column it
 * comes from, so it can be checked cell by cell.
 *
 * The one thing worth knowing before reading it: the two halves are **added**,
 * not multiplied. Bullets and ultimate weapons are separate sources of damage,
 * which is why a player with no ultimate weapons still has a number and why an
 * Attack Dissonance run — where the tower does not fire at all — still has one.
 */
/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    EffectiveDamageBreakdown, CHRONO_SLOW_CAP, EffectiveDamageShadow, computeEffectiveDamage, ENHANCEMENT_MULTIPLIER_PER_LEVEL, STONE_STAT_FIELD_KEYS, STONE_PLUS_STATS
 * depends    src/data/modules/bonus, src/mechanics/effective-paths/damage-base, src/mechanics/effective-paths/damage-stats, src/mechanics/effective-paths/damage-substats, src/mechanics/effective-paths/edamage-config, src/mechanics/effective-paths/edamage-costs (+6 more)
 * used by    src/mechanics/calculators/run, src/mechanics/effective-paths/edamage-plan, src/mechanics/effective-paths/index
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */

import {
  ampStrike,
  damageBase,
  demonModeMastery,
  perfectFreeze,
  perfectFreezeCash,
  shockMultiplier,
  standardDamagePerk,
  towerDamage,
  tradeOffDamagePerk,
} from './damage-base'
import {
  attackRange,
  attackSpeed,
  bounceShotChance,
  bounceShotMultiplier,
  bounceShotTargets,
  criticalChance,
  criticalMultiplier,
  damagePerMeter,
  maxRendArmourMultiplier,
  multishotChance,
  multishotMultiplier,
  multishotTargets,
  rangeDamageMultiplier,
  rapidFireChance,
  rapidFireDuration,
  rapidFireMultiplier,
  shockwaveDamage,
  spotlightCoverage,
  superTowerBonus,
  superTowerCooldown,
  superTowerEffectiveBonus,
  superTowerLabFactor,
  spotlightCandidateSuperTower,
  superTowerEffectiveUltimateBonus,
  ultimateWeaponCriticalMultiplier,
} from './damage-stats'
import { bulletsPerSecond } from './damage-substats'
import { bulletDamageMultiplier, composeEffectiveDamage } from './edamage-model'
import {
  assistSubstatCap,
  moduleBonus,
  recoveryPackageTimeBoost,
} from './generics'
import {
  chainLightningChance,
  chainLightningDamage,
  chainLightningQuantity,
  deathWaveCooldown,
  deathWaveDamage,
  deathWaveQuantity,
  innerLandMineDamage,
  innerLandMineQuantity,
  smartMissileCooldown,
  smartMissileDamage,
  smartMissileDamagePerSecond,
  smartMissileQuantity,
  spotlightAngle,
  spotlightDamage,
  spotlightLightRange,
  ultimateWeaponHeatUp,
  ultimateWeaponTotalDamage,
} from './ultimate-weapons'
import {
  chainLightningDps,
  deathWaveDps,
  innerLandMinesDps,
  poisonSwampDps,
  smartMissilesDps,
  spotlightFinalBonus,
  spotlightMissilesDps,
} from './uw-dps'
import { dissonantBoostOfType } from './ehp-model'
import { computeModuleStat } from '../../data/modules/bonus'
import {
  KEYS_CANDIDATE_NODES,
  resolveUltimateWeaponStat,
  ultimateWeaponStatValue,
} from './edamage-costs'
import type {
  DamageCard,
  DamageCardSource,
  DamagePerk,
  DamageStatSource,
  DamageSubstat,
  EffectiveDamageConfig,
  ModuleSlot,
} from './edamage-config'
import type { EffectiveDamageLevels } from './edamage-levels'

/**
 * Every factor of `ES5`, kept rather than collapsed.
 *
 * A planner only needs the last field, but a player looking at a path wants to
 * know *which* half moved — and a test comparing against the sheet can compare
 * a column at a time instead of bisecting one number.
 */
/** What a Spotlight-lit missile hits for when Smart Missiles is not unlocked. */
const UNLOCKED_SMART_MISSILE_BASE_DAMAGE = 10

export interface EffectiveDamageBreakdown {
  /** `DI5`. */
  base: number
  /** `DN5`. */
  crit: number
  /** `DO5`. */
  ultimateWeaponCrit: number
  /** `EA5`. */
  bulletDamageMultiplier: number
  /** `ED5`. */
  spotlight: number
  /** `EO5`. */
  ultimateWeapons: number
  /** `ER5`. */
  slow: number
  /** `ES5`. */
  effectiveDamage: number
  /**
   * Every intermediate column, by its own name on the sheet.
   *
   * The seven factors above are each built from a dozen of these, so when one
   * of them disagrees with the sheet this is what says which part did. It is
   * also what the page reads to show a player *which* half a step moved.
   */
  columns: Readonly<Record<string, number>>
}

/**
 * `eDamage!ES5` — effective damage for a player at a given set of levels.
 *
 * `config` is who the player is; `levels` is what the path has bought so far.
 * Anything a path can buy lives in `levels` and *only* there, so a planner
 * moving a level never has to touch the config.
 */
/**
 * Deliberate departures from the base columns, for candidate evaluation only.
 *
 * The sheet does not evaluate a candidate by recomputing its own columns. Each
 * upgrade has a SHADOW column that rebuilds the total with one level bumped,
 * and those shadows do not always agree with the base. Reproducing the sheet
 * means reproducing that, and it cannot live in the base computation without
 * breaking the columns that already match.
 */
/**
 * The `MIN(90%, …)` in `eDamage Stone!EB5` — the ceiling on Chrono Field's slow.
 *
 * Declared here because this is the only place it binds. A second copy lived in the plan
 * module, where it was never read: the literal below was doing the work, so the named
 * constant said the cap was modelled while the number said what it actually was.
 */
export const CHRONO_SLOW_CAP = 0.9

export interface EffectiveDamageShadow {
  /**
   * Spotlight's ultimate-weapon vault percentage, held at the base row's value.
   *
   * Every `eDamage Keys` candidate column ends on the BASE row's Spotlight:
   * `SL, $CY5`. `CY5` reads `$BM$39` — the ultimate weapon vault — so on the
   * one candidate that raises `BM39`, the sheet prices the bump through
   * `UWAdditionalDMG` and leaves Spotlight where it was.
   *
   * The port recomputes the whole composition, so it moved Spotlight too and
   * valued UW Damage at roughly twenty times the sheet's figure, ranking it
   * first where the sheet ranks it seventeenth. Every later step shifted with
   * it.
   *
   * Set for the whole keys band, not just UW Damage: all eleven columns reuse
   * `$CY5`, and for the other ten the frozen value is the recomputed one
   * anyway, so it is exact there and does nothing.
   */
  spotlightVaultPct?: number
  /** `CY5` held whole at the base row — see the use site. */
  frozenSpotlightBonus?: number
  /** `eDamage Keys!CU5` drops the assist substat — see the use site. */
  maxRendPrimarySubstatOnly?: boolean

  /**
   * COIN band only — Max Rend caps its assist substat with the wrong level.
   *
   * Every other column on `eDamage Coins` takes the cannon assist cap from
   * `CH5`, "Assist Module Substats - Cannon" (`=BC45`) — nine of them, from
   * crit through Range Mastery. Max Rend takes it from `CK5`, "Assist Module
   * BONUS - Cannon" (`=BC49`):
   *
   *     eDamage!DZ5        EPG_ASSIST_SUB_CAP($AN$4, $BL$42, CO5)   <- Substat
   *     eDamage Coins!DM5  EPG_ASSIST_SUB_CAP($AN$4, $BL$42, CK5)   <- Bonus
   *
   * Two cells carry it, `DM5` and the `Rend Armor Mult +` candidate column
   * `EP5`, and they are the only two on the tab that do. On `account-19` the
   * two levels are 26 and 2, so the cap is 0.27 against 0.03 and the tab's
   * `Max Rend Armor Multiplier` reads 15.100489250 where the port rebuilt
   * 14.982343250 — 0.78% low, and the ONLY factor of seven in `OtherMults`
   * that disagreed at all.
   *
   * Whether the sheet means it or fat-fingered a column, the port reproduces
   * it, the same as every other entry here.
   */
  maxRendAssistCapFromBonusLevel?: boolean

  /**
   * The ILM cooldown taken from the DISPLAY cell, which counts its substat
   * twice.
   *
   * `eDamage!EL5`, the base column, builds the cooldown from the raw weapon
   * value: `IlmCD, $BK$37 + $AM$41 + SubstatAssistCapCore*$AO$41`. Two
   * CANDIDATE columns build it from `$AY$10` instead — `FM5`
   * (Inner Land Mine - Chrono Jump) and `FS5` (Assist Module Substats - Core)
   * — and `AY10` is
   *
   *     =IF(BH37, MAX(37, BK37 + AM41 + AR41), )     AR41 = AO41 * $AO$24
   *
   * so it already carries the substat that the candidate then adds again:
   * 247.013 raw, 247.3254 from the display cell, and the candidate's cooldown
   * ends up `BK37 + 2*AM41 + cap*AO41`.
   *
   * A longer cooldown is fewer detonations, so this makes the sheet price
   * Chrono Jump slightly HIGH against its peers — 2.7e-5, one part in 37,000,
   * far too small to see without a peer comparison and far too structured to
   * be rounding.
   *
   * `AR41` is the assist substat at the core module's FULL efficiency
   * (`AO41 * $AO$24`), not the capped share the base column uses. It is 0 on
   * every captured account because that module carries no assist, but it is
   * modelled rather than assumed.
   */
  innerLandMineCooldownFromDisplayCell?: boolean

  /**
   * Optional UW DPS overrides (stone rebuild / probes).
   *
   * Pre-v5.10 the keys planner forced lab/stone borrows here because
   * `eDamage Keys` cross-referenced other tabs. v5.10+ Keys!DF5:DN5 compute
   * those weapons locally — the keys pathShadow no longer sets this field.
   * Kept for stone / ad-hoc shadows that still need a forced weapon value.
   */
  ultimateWeaponOverrides?: {
    deathWave?: number
    chainLightning?: number
    smartMissiles?: number
    spotlightMissiles?: number
    innerLandMines?: number
    poisonSwamp?: number
    superTowerUltimateMastery?: number
  }
  /**
   * Percentage points added to crit chance outside the card gate.
   *
   * `eDamage!EV5`, the Critical Chance Mastery shadow, writes `CC, DJ5 + 1%`
   * flat. The base column reaches crit chance through `EPD_CRIT_CHANCE`, whose
   * mastery term is nested inside `IF(has_card, …)` with
   * `has_card = AND($AY$39, $AY$47)`. So on an account with the cards master
   * off, the sheet's estimate of a mastery level credits a percentage point its
   * own base column refuses to apply — and then the purchase delivers nothing,
   * because the next row is computed by the base column again.
   *
   * The port reproduces that rather than correcting it: matching the sheet is
   * the job. Measured on `account-26` step 34 — sheet `1.83674216e-2`, port
   * `1.28635275e-2` before this, a ratio of 1.4278.
   */
  flatCriticalChanceBonus?: number
  /**
   * Super crit chance added while a candidate is priced.
   *
   * `eDamage Keys!DL5`, the Critical Chance candidate, bumps TWO inputs:
   *
   *   CC, CF5+1%,   ...   SCC, CH5+1%,
   *
   * where the Super Crit Chance candidate one column over bumps only
   * `SCC, CH5 + 2%`. Reproduced rather than judged: it is what the column
   * computes, and the port ranked Critical Chance below the sheet on four of
   * the five real accounts without it.
   */
  flatSuperCritChanceBonus?: number

  /**
   * The Spotlight Missiles cooldown to use while PRICING that lab.
   *
   * The base column `eDamage!EH5` reads the lab properly, `20 - CH5`. Its
   * shadow `FI5` passes the literal `2` — which is `20 - 18`, the cooldown at
   * the lab's cap.
   *
   * Unlike the other two fields here, this is NOT the sheet disagreeing with
   * itself. Its ROI column is the only one of the 34 that divides by the cost
   * of every remaining level rather than the next one:
   *
   *     GO5 = (FI5/$ES5-1) / SUM(ARRAYFORMULA(LABDURATION_SINGLE_ADJUSTED(
   *             $GO$4, SEQUENCE(18-CH5+1, 1, CH5+1))))
   *
   * So the column asks "what does FINISHING this lab buy, per day spent
   * finishing it" — value at the cap over cost to the cap — and the two halves
   * are consistent. The lab's whole effect is the cooldown, and a single level
   * of it is not a meaningful unit.
   *
   * Reading the shadow alone made it look like a bug and priced one level at
   * the value of the entire run to cap: parity went 96/100 to 89/100, with
   * failures appearing in BOTH directions, which is what a broken baseline
   * looks like rather than a mis-valued upgrade. See `costOf`, which owns the
   * matching half — the two must move together or neither is right.
   */
  spotlightMissilesCooldownSeconds?: number

  /**
   * Price a CF Slow level WITHOUT the 90% cap the base column applies.
   *
   * `eDamage Stone!EB5` — the base slow — is
   * `1/(1 - MIN(90%, SpeedReduction(CK5) + Substat))`. Its candidate column
   * `FF5` is `1/(1 - SpeedReduction(CK5+1) - Substat)`, with no `MIN`. The
   * sheet disagrees with itself, and the port reproduces that rather than
   * correcting it, because matching the sheet is the job.
   *
   * The effect is one-sided and only near the cap: below 90% the two agree
   * exactly, and above it the shadow keeps rising while the base does not — so
   * the level is priced high and then delivers the capped amount. The planner
   * re-settles from the base after every pick, which is what keeps that
   * generosity from compounding.
   *
   * Nothing stops the shadow's denominator reaching zero, and neither does the
   * sheet: at a reduction of 100% its `1/(1-1)` is a division by zero, and the
   * ROI column would drop out on the error. No account in the sweep reaches it.
   */
  chronoSlowUnclamped?: boolean

  /**
   * Chrono slow held at the path-start row — sheet \ES\ on lab shadows /
   * \ET5\. Lab ROI columns multiply by absolute row-5 slow for the whole
   * fill-down; stone uses relative \EE5\ and must not freeze. Absent,
   * composition uses the recomputed slow (standalone calls).
   */
  frozenSlow?: number

  /**
   * Perfect Freeze as it stands at the START of the path — the sheet's `$DH$5`.
   *
   * `eDamage!DA5` opens with tower damage divided by absolute `$DH$5` (PF).
   * Row 5's PF is held for the fill-down while each shadow multiplies its own
   * PF back in. Under Util Disso PF moves with Starting Cash — that lab's
   * whole benefit lives in the gap between the fixed divisor and the moving
   * multiplier. Compute both sides with one value and Starting Cash cancels
   * to a gain of zero (never appears in a path).
   *
   * Absent, the row divides by its own — which is what row 5 itself does.
   */
  perfectFreezeBaseline?: number

  /**
   * Gate the CANNON substat cap on the CORE module's assist flag.
   *
   * `eDamage Stone!FH5` — the shadow that prices Assist Module Substats -
   * Cannon — opens:
   *
   *     SubstatAssistCap,     EPG_ASSIST_SUB_CAP($AN$23, CN5+1, $BC$45)
   *     SubstatAssistCapCore, EPG_ASSIST_SUB_CAP($AN$23, CQ5,   $BC$48)
   *
   * `CN5` is the cannon stone ladder, so the first is the cannon cap — built
   * with `$AN$23`, which is the **Core** module's assist flag. The sheet does
   * use all three flags elsewhere (`$AN$4` cannon, `$AN$23` core, `$AN$47`
   * armor, 88 calls between them), so this is that column and not a convention.
   *
   * Verified by experiment on the working copy rather than inferred: flipping
   * `AN23` alone, with nothing else touched, moves the priced gain from
   * **-7.099%** to **+2.442%**. Negative is the whole point — the sheet offers
   * this upgrade (its own hide flag is `NOT(AN4)`, and `AN4` is true) and then
   * prices it below doing nothing, so it is never taken.
   *
   * The port gave each module its own flag, scored a real gain, and opened the
   * stone path with it on all ten accounts of the first sweep.
   */
  cannonAssistCapUsesCoreFlag?: boolean

  /**
   * Resolve every ultimate-weapon stat from its stone LEVEL, not the observed
   * value. The stone path only.
   *
   * The two tabs do not share a model, and this is the difference:
   *
   *     eDamage!EH5       STAT_UW_SL_FINAL_DMG($BI$33, ...)
   *     eDamage Stone!EE5 ... DVT_UW_STAT("Spotlight", "Multiplier", BY5) ...
   *
   * The planner tab takes the player's stat as OBSERVED — `BI`, `BJ`, `BK` are
   * what the save reports. The stone tab rebuilds each stat from the level
   * column it is about to increment, because that is the thing the path buys.
   *
   * Mixing the two is worse than either. Deriving only the bumped candidate,
   * while the baseline kept the observed value, priced a level-1 stat against a
   * fully-upgraded weapon and produced a NEGATIVE gain: `ILM Damage` was the
   * sheet's first pick on `account-3` at `4.21e-4` and the port would not take
   * it at all in six steps.
   *
   * So it is all or nothing, per path. The four other variants do not buy
   * stones and keep the observed values.
   */
  weaponStatsFromStoneLevels?: boolean

  /**
   * `eDamage Stone!EU5` / `EV5` — the SL Angle and SL Quantity candidates, which
   * rebuild Super Tower inline instead of calling the function the base column
   * calls, and get a different number out of it.
   *
   * The base column `DB5` is
   *
   *     EPD_SUPERTOWER_BONUS(RIGHT($AU$52, 1), $BC$37)
   *
   * whose bonus is `card × (1 + 3% × lab)`. The two candidate columns write
   *
   *     STB, $AV$52 * $BF$37
   *
   * where `$AV$52` is that same finished bonus and `$BF$37` is the lab factor
   * again — so the Super Tower lab is applied **twice**. On `account-9`, whose
   * card is level 5 and whose lab is 29, `$AV$52` is 7.667 and `$BF$37` is 1.87:
   * the base column gives 3.2223 and the candidate 5.4458, a flat **1.6900**
   * on the bullet half of those two candidates and nothing else.
   *
   * That factor was recorded as an unexplained "1.69x reconstruction" before it
   * was read; it is not a reconstruction, it is a double-count.
   *
   * Coverage is why only these two candidates carry it: they are the only ones
   * that move `SLC`, so they are the only ones that re-derive Super Tower at
   * all. Everything else reads `DB5` and inherits the base column's answer.
   *
   * The inline version also differs in two ways this sweep does NOT exercise,
   * transcribed here rather than guessed at: its mastery term is `0.35 × STB`
   * where the base column's is `1 + 0.35 × (STB - 1)`, and its cooldown reads
   * the mastery LAB alone where the base column adds the coin band's levels.
   * Every account in the sweep has Super Tower Mastery switched off, which
   * makes both branches unreachable and both claims unverified.
   */
  spotlightCandidateSuperTowerInline?: boolean
}

export function computeEffectiveDamage(
  config: EffectiveDamageConfig,
  levels: EffectiveDamageLevels,
  shadow: EffectiveDamageShadow = {},
): EffectiveDamageBreakdown {
  const lab = levels.lab

  /**
   * A stat's four sources, with the vault share taken from `levels.keys`.
   *
   * The vault is the keys path's whole inventory, so its bonus has to move as
   * the path buys — the sheet reads the relationship the other way round and
   * *derives* the level from the bonus (`eDamage Keys!BO5 = BM8 / 5%`), which
   * is the same relationship read backwards. A `vaultPct` on the config would
   * be a second, stale copy of it, so for these ten stats it is ignored.
   */
  const stat = (name: Parameters<typeof statOf>[1]) => {
    const source = statOf(config, name)

    // The coin path's workshop enhancements, which used to reach nothing.
    //
    // `config.stats[name].enhancementMultiplier` is read straight off the
    // sheet's `BK` column and never moved, while the planner writes the levels
    // it buys into `levels.coin.enhancement*`. Nothing joined the two, so every
    // one of the seven `+` candidates was offered, priced, and computed to the
    // SAME effective damage after purchase — a gain of exactly zero, which no
    // ranking will ever choose. All ten accounts in the coin sweep diverged at
    // step 1 because of it.
    //
    // The DELTA is added rather than the multiplier rebuilt from the level.
    // Rebuilding would re-derive the sheet's own `BK` and would silently drop
    // its gate — `BK` is 1 while the Workshop Enhancements lab is unbought,
    // regardless of level — so adding keeps the sheet authoritative for the
    // starting point and makes only the bought levels ours. It is also exactly
    // a no-op when nothing has been bought, which is why lab-time and stone
    // parity are unaffected.
    // `levels.coin.enhancement*` is ABSOLUTE, matching the levels the sheet
    // prints, so the bought part is the difference from where the account
    // started. Treating it as relative and adding it to the config level would
    // double-count the nine levels this account already owns; treating the
    // config level as the whole story is what made these candidates worthless.
    // Clamped at zero so an unseeded 0 — which is what every other variant
    // passes — is a no-op rather than a negative correction.
    const coinKey = COIN_ENHANCEMENT_LEVELS[name]
    const bought = coinKey
      ? Math.max(0, (levels.coin[coinKey] ?? 0) - source.enhancementLevel)
      : 0
    const enhanced = bought > 0
      ? {
          ...source,
          enhancementLevel: source.enhancementLevel + bought,
          enhancementMultiplier: source.enhancementMultiplier + ENHANCEMENT_MULTIPLIER_PER_LEVEL * bought,
        }
      : source

    const keysKey = KEYS_STAT_LEVELS[name]
    if (!keysKey) return enhanced
    const node = KEYS_CANDIDATE_NODES[keysKey.sheetName]
    return { ...enhanced, vaultPct: levels.keys[keysKey.key] * node.perLevel }
  }

  const cannonCapacity = assistCapacity(config, levels, 'cannon', shadow)
  /*
   * Max Rend's own capacity, because on the coin tab it caps off a different
   * level from every other column. See
   * {@link EffectiveDamageShadow.maxRendAssistCapFromBonusLevel}.
   */
  const rendCapacity = shadow.maxRendAssistCapFromBonusLevel
    ? assistCapacity(config, levels, 'cannon', shadow, 'bonus')
    : cannonCapacity
  const coreCapacity = assistCapacity(config, levels, 'core', shadow)
  const armorCapacity = assistCapacity(config, levels, 'armor', shadow)

  /** `AM_n + capacity × AO_n` — a substat with its assist half weighted. */
  const substat = (name: DamageSubstat, capacityValue: number): number => {
    const pair = config.substats[name]
    return pair.primary + capacityValue * pair.assist
  }
  const cannonSubstat = (name: DamageSubstat) => substat(name, cannonCapacity)
  const coreSubstat = (name: DamageSubstat) => substat(name, coreCapacity)

  /** `AM_n + AR_n` — a unique effect, which both modules can carry. */
  const unique = (name: Parameters<typeof uniqueOf>[1]) => uniqueOf(config, name)

  const card = (name: Parameters<typeof cardOf>[1]) => cardOf(config, name)
  /**
   * `AND($AY$61, $AY$6n)` — the grid's only perk gate.
   *
   * The tournament rule is not here. The sheet drives `AY61` from the
   * simulated tier, so by the time a column reads it the decision is made.
   */
  const perk = (name: DamagePerk) =>
    config.perksEquipped && config.perks[name]

  // --- Dissonance --------------------------------------------------------
  const dissonanceBoost = (type: 'attack' | 'uw', level: number): number => {
    if (!config.dissonance.active) return 1
    /*
     * The ultimate weapon echo reads its OWN tier bests when the caller has
     * them. See {@link EffectiveDamageConfig.dissonance.ultimateWeapon}: the
     * sheet passes `$CX$40, $CX$41:$CX$61` there against `$CX$13,
     * $CX$14:$CX$34` for attack, and on a real account those differ.
     */
    const source = type === 'uw' && config.dissonance.ultimateWeapon
      ? config.dissonance.ultimateWeapon
      : config.dissonance
    return dissonantBoostOfType(
      type, source.tierPersonalBest, source.allTierPersonalBests, level,
    )
  }

  /** `CY5`. */
  const attackDisco = dissonanceBoost(
    'attack', lab.dissonantEchoAttack + levels.coin.dissonantEchoAttack,
  )
  /** `EB5`. */
  const ultimateDisco = dissonanceBoost(
    'uw',
    lab.dissonantEchoUltimateWeapons + levels.coin.dissonantEchoUltimateWeapons,
  )

  // --- The base, CZ5 through DI5 ----------------------------------------

  /**
   * What the Cash Bonus enhancement multiplies effective damage by.
   *
   * `eDamage Coins!EJ5` over `CT5`, read on 2026-08-20. Both compute the same
   * shape and differ only in the level:
   *
   *     PF,        $AM$45 + $AR$45
   *     CashBInit, 1 + $BU$5/100          the level the account starts at
   *     CashB,     1 + BU5/100            CT5, the current level
   *                1 + (BU5+1)/100        EJ5, one level on
   *     OldPF,     1 + IF(PF<>0, PF*log10(cash), 0)
   *     NewPF,     1 + IF(PF<>0, PF*log10(cash / CashBInit * CashB), 0)
   *     ->         NewPF/OldPF
   *
   * The ROI column is `(EJ5/$CT5 - 1)`, a ratio of ratios, so the candidate is
   * a plain MULTIPLIER on effective damage and its gain is that ratio minus one.
   *
   * APPLIED HERE RATHER THAN BY SCALING `cash`, and the difference is not
   * cosmetic. Feeding the raised cash into `perfectFreeze` looks more faithful
   * and does almost nothing during planning: the planner pins `DH5` through
   * {@link EffectiveDamageShadow.perfectFreezeBaseline}, so the freeze term it
   * divides out of the base is deliberately frozen. Scaling cash there moved
   * the number by some other route and over-valued the candidate — three
   * accounts started buying it nine steps early, which the sixteen-step guard
   * caught. The sheet says multiplier; this is the multiplier.
   *
   * With no Project Funding substat `PF` is 0, both sides collapse to 1, and
   * the candidate is worth exactly nothing — which is why only seven of the ten
   * swept accounts ever buy it.
   */
  const cashBonusRatio = (() => {
    const owned = config.cashBonusEnhancementLevel
    const priced = Math.max(owned, levels.coin.enhancementCashBonus ?? 0)
    if (priced === owned) return 1
    const substat = unique('Project Funding')
    if (substat === 0) return 1
    const cash = perfectFreezeCash(config.runType, lab.startingCash, config.cash)
    const rebased = cash / (1 + owned / 100) * (1 + priced / 100)
    const oldPf = perfectFreeze({ substat, cash })
    const newPf = perfectFreeze({ substat, cash: rebased })
    return oldPf === 0 ? 1 : newPf / oldPf
  })()

  /** `DH5` — Perfect Freeze off Project Funding (PF); divided back out of tower damage via `$DH$5`. */
  const freeze = perfectFreeze({
    substat: unique('Project Funding'),
    cash: perfectFreezeCash(config.runType, lab.startingCash, config.cash),
  })

  /** `DA5`. */
  const damage = towerDamage({
    // `$DH$5` absolute — see {@link EffectiveDamageShadow.perfectFreezeBaseline}.
    baseDamage: config.towerDamageBase / ((shadow.perfectFreezeBaseline ?? freeze) || 1),
    labLevel: lab.damage,
    enhancementMultiplier: stat('Damage').enhancementMultiplier,
    hasDamageCard: config.cardsEquipped && card('Damage').active,
    cardValue: card('Damage').value,
    hasCardMastery: card('Damage Mastery').active,
    masteryLevel: lab.damageMastery,
    dissonance: attackDisco,
  })

  /** `DF5` — the Cannon module pair. */
  const cannonModule = moduleBonus({
    primaryBonus: moduleBonusAtLevel(
      'cannon', config.modules.cannon.primaryRarity,
      levels.coin.primaryModuleCannon, config.modules.cannon.primaryBonus,
    ),
    hasAssist: config.modules.cannon.hasAssist,
    assistBonus: moduleBonusAtLevel(
      'cannon', config.modules.cannon.assistRarity,
      levels.coin.assistModuleCannon, config.modules.cannon.assistBonus,
    ),
    stoneBonusCap: levels.stone.assistBonusCannonStone,
    labBonusCap: lab.assistBonusCannon + levels.coin.assistBonusCannon,
  })

  /** `DG5` — ACP / shockwave (`EPD_SHOCKWAVE_DAMAGE`, vault from `$BN$24`). */
  const shockwave = shockwaveDamage({
    cannonBonus: unique('Anti-Cube Portal'),
    sizeWorkshopLevel: config.shockwave.sizeWorkshopLevel,
    sizeLabLevel: config.shockwave.sizeLabLevel,
    frequencyWorkshopLevel: config.shockwave.frequencyWorkshopLevel,
    frequencyVault: config.shockwave.frequencyVault,
    frequencySubstat: substat('Shockwave Frequency', armorCapacity),
  })

  // Hoisted out of the `damageBase` call so each can be compared against the
  // sheet cell it reproduces. They were correct as arguments; they were also
  // invisible, and an intermediate nobody compares is one the parity sweeps
  // have to find the hard way — see the column sweep in the compute test.
  /** `DA5`. */
  const damagePerk = standardDamagePerk(
    perk('Damage'), lab.standardPerksBonus, config.perkQuantity.damage,
  )
  /** `DB5`. */
  const tradeOffPerk = tradeOffDamagePerk(
    perk('Boss Health Trade-off'), lab.improveTradeOffPerks,
  )
  /** `DC5`. */
  const shock = shockMultiplier({
    hasShock: config.shockMultiplierUnlocked
      && config.ultimateWeapons['Chain Lightning'].unlocked,
    labLevel: lab.shockMultiplier,
    deathChainSubstat: unique('Dimension Core'),
  })
  /** `DD5`. */
  const demonMode = demonModeMastery(
    card('Demon Mode Mastery').active, lab.demonModeMastery + levels.coin.demonModeMastery,
  )
  /** `DH5`. */
  const amp = ampStrike({
    share: config.ampStrikeShare,
    substat: unique('Amplifying Strike'),
    divisor: config.waveDurationSeconds,
  })

  const base = damageBase({
    runType: config.runType,
    towerDamage: damage,
    damagePerk,
    tradeOffPerk,
    shock,
    demonModeMastery: demonMode,
    cannonAssist: cannonModule,
    shockwave,
    perfectFreeze: freeze,
    ampStrike: amp,
  })

  // --- The crit pair, DJ5 through DO5 -----------------------------------

  const critChanceMasteryLevel
    = lab.criticalChanceMastery + levels.coin.criticalChanceMastery

  // `DJ5` — every one of the four crit columns opens with the same Attack
  // Dissonance guard. The tower does not fire, so there is nothing to crit.
  const critInput = {
    criticalChance: config.runType === 'Attack Disso' ? 0 : (shadow.flatCriticalChanceBonus ?? 0) + criticalChance({
      workshopLevel: stat('Critical Chance').workshopLevel,
      hasCriticalChanceCard: config.cardsEquipped && card('Critical Chance').active,
      cardLevel: card('Critical Chance').level,
      relicPct: stat('Critical Chance').relicPct,
      vaultPct: stat('Critical Chance').vaultPct,
      substat: cannonSubstat('Critical Chance'),
      hasCardMastery: card('Critical Chance Mastery').active,
      masteryLevel: critChanceMasteryLevel,
    }),
    criticalFactor: critFactor(),
    superCritChance: superCritChance(),
    superCritMultiplier: superCritMultiplier(),
  }

  function critFactor(): number {
    if (config.runType === 'Attack Disso') return 1
    const source = stat('Critical Factor')
    return (config.criticalFactorBase * (1 + 0.03 * lab.criticalFactor)
      + cannonSubstat('Critical Factor'))
      * source.enhancementMultiplier
      * (1 + source.relicPct)
      * (1 + source.vaultPct)
  }

  function superCritChance(): number {
    if (config.runType === 'Attack Disso') return 0
    return (shadow.flatSuperCritChanceBonus ?? 0)
      + config.superCritChanceBase
      + cannonSubstat('Super Crit Chance')
      + 0.001 * lab.superCritChance
      + (card('Critical Chance Mastery').active ? 0.01 * (1 + critChanceMasteryLevel) : 0)
      + unique('Being Annihilator')
  }

  function superCritMultiplier(): number {
    if (config.runType === 'Attack Disso') return 1
    const source = stat('Super Critical Mult')
    const mastery = card('Critical Chance Mastery').active
      ? 1 + 0.01 * (1 + critChanceMasteryLevel)
      : 1
    return (config.superCritMultiBase * (1 + 0.02 * lab.superCritMulti)
      + cannonSubstat('Super Crit Multi'))
      * source.enhancementMultiplier
      * (1 + source.relicPct)
      * (1 + source.vaultPct)
      * mastery
  }

  /** `DN5`. Being Annihilator lets bullets crit five times over. */
  const crit = criticalMultiplier({
    ...critInput,
    beingAnnihilator: unique('Being Annihilator') ? 5 : 0,
  })
  /** `DO5` — the ultimate weapons' own crit, which Being Annihilator misses. */
  const uwCrit = ultimateWeaponCriticalMultiplier(critInput)

  // --- The bullet multiplier, DP5 through EA5 ---------------------------

  const bullet = bulletStats({
    config,
    labLevels: lab,
    stat,
    cannonSubstat,
    bounceShotPerkTargets: perk('Bounce Shot') ? config.bounceShotPerkTargets : 0,
    card,
    attackSpeedMasteryLevel: lab.attackSpeedMastery + levels.coin.attackSpeedMastery,
    astralDeliverance: unique('Astral Deliverance'),
    rangeMasteryLevel: lab.rangeMastery + levels.coin.rangeMastery,
  })
  const {
    bps, multishot, bounce, bounceNoAstral, rapidFire, range, perMeter, rangeDamage,
  } = bullet

  // --- Super Tower, DX5 and DY5 -----------------------------------------
  // The card multiplies bullet damage; the mastery passes a share of that
  // multiplier to the ultimate weapons. Two different quantities, which is why
  // the sheet computes them separately rather than reusing one.

  const superTowerLevel = card('Super Tower').level
  const superTowerMasteryLevel = lab.superTowerMastery + levels.coin.superTowerMastery
  const stBonus = superTowerBonus(superTowerLevel, lab.superTowerBonus)
  const stCooldown = superTowerCooldown(
    card('Super Tower Mastery').active, superTowerMasteryLevel,
  )

  const spotlightAngleDegrees = spotlightAngle(
    weaponOf(config, levels, 'Spotlight', shadow).quantity, coreSubstat('Spotlight - Angle'),
  )

  /** `DX5`. */
  const superTowerBase = superTowerEffectiveBonus({
    hasCard: config.cardsEquipped && card('Super Tower').active,
    hasMastery: card('Super Tower Mastery').active,
    bonus: stBonus,
    cooldownSeconds: stCooldown,
    hasSpotlight: weaponOf(config, levels, 'Spotlight', shadow).unlocked,
    spotlightQuantity: spotlightQuantityOf(config, levels, shadow),
    spotlightAngleDegrees,
  })

  /**
   * `DX5`, or the double-counted rebuild of it — see
   * {@link EffectiveDamageShadow.spotlightCandidateSuperTowerInline}.
   */
  const superTower = shadow.spotlightCandidateSuperTowerInline
    ? spotlightCandidateSuperTower({
      hasCard: config.cardsEquipped && card('Super Tower').active,
      hasMastery: card('Super Tower Mastery').active,
      bonus: stBonus * superTowerLabFactor(lab.superTowerBonus),
      cooldownSeconds: superTowerCooldown(
        card('Super Tower Mastery').active, lab.superTowerMastery,
      ),
      coverage: weaponOf(config, levels, 'Spotlight', shadow).unlocked
        ? spotlightCoverage(spotlightQuantityOf(config, levels, shadow), spotlightAngleDegrees)
        : 0,
    })
    : superTowerBase

  /** `DY5`. */
  const superTowerUltimate = shadow.ultimateWeaponOverrides?.superTowerUltimateMastery ?? superTowerEffectiveUltimateBonus({
    hasCard: config.cardsEquipped && card('Super Tower').active,
    hasMastery: card('Super Tower Mastery').active,
    bonus: stBonus,
    cooldownSeconds: stCooldown,
  })

  /** `DZ5`. */
  const rend = config.runType === 'Attack Disso'
    ? 1
    : maxRendArmourMultiplier({
      hasRend: config.hasRendArmour,
      labLevel: lab.maxRendArmorMultiplier,
      /*
       * The keys tab leaves the ASSIST half of this substat out.
       *
       *   eDamage!DZ5        Substat = $AM$16 + EPG_ASSIST_SUB_CAP(...)*$AO$16
       *   eDamage Keys!CU5   ($BF$22 + $AM$16) * $BK$22
       *
       * `$AM$16` is the primary substat and the assist term simply is not in
       * the keys column. That one omission is the whole of the 0.478% by which
       * the keys tab's `Other Mults` sat below eDamage's `BulletDmgMulti`, and
       * with it the last systematic difference between the two tabs' bases.
       */
      substat: shadow.maxRendPrimarySubstatOnly
        ? config.substats['Max Rend Armor Multi']?.primary ?? 0
        : substat('Max Rend Armor Multi', rendCapacity),
      enhancementLevel: stat('Max Rend Armor Multiplier').enhancementLevel,
    })

  /** `EA5`. */
  const bulletMultiplier = bulletDamageMultiplier({
    multishot,
    bounceShot: bounce,
    bulletsPerSecond: bps,
    rapidFire,
    rangeDamagePerMeter: rangeDamage,
    superTowerCard: superTower,
    maxRendArmour: rend,
  })

  // --- The ultimate weapons, EC5 through EO5 ----------------------------

  /** `BM39`, which the keys path buys four nodes' worth of. */
  const ultimateWeaponVaultPct = levels.keys.ultimateWeaponDamage
    * KEYS_CANDIDATE_NODES['UW Damage'].perLevel

  /**
   * How the frozen `CX6` above is allowed to MOVE when a vault level is bought.
   *
   * `config.ultimateWeaponDamageVaultPct` and `levels.keys.ultimateWeaponDamage`
   * are the same cell twice -- `eDamage!BM39`, once as a percentage and once
   * divided by 5% -- so at the account's own levels this ratio is exactly 1 and
   * `CX6` passes through untouched. That is what keeps every captured fixture
   * valid, including `effective-paths-edamage-states.fixtures.json`, whose
   * `CX6` is a free literal that does NOT equal `(1+BL39)*(1+BM39)` for any of
   * its ten states.
   *
   * When the PLANNER raises the level, the numerator moves and the denominator
   * does not, so the term responds the way the sheet's candidate column does.
   * Before this the vault reached the ultimate weapons only through a captured
   * constant, so buying a vault level moved `spotlightDamage` and nothing else,
   * and the keys planner ranked UW Damage on a fraction of its effect.
   *
   * This also gives `ultimateWeaponDamageVaultPct` its first reader. It was
   * declared, read from the sheet, populated from the player's vault -- and
   * consumed by nothing at all.
   */
  const vaultResponse = (1 + ultimateWeaponVaultPct)
    / (1 + config.ultimateWeaponDamageVaultPct)

  /** `EC5` — how much shorter recovery packages make the wave. */
  const timeBoost = waveTimeBoost(config)

  const weapon = (name: Parameters<typeof weaponOf>[2]) =>
    weaponOf(config, levels, name, shadow)

  /** `EF5`. */
  const deathWave = shadow.ultimateWeaponOverrides?.deathWave ?? deathWaveDps({
    unlocked: weapon('Death Wave').unlocked,
    damage: deathWaveDamage(
      weapon('Death Wave').damage,
      coreSubstat('Death Wave - Damage'),
      weapon('Death Wave').vaultPct ?? 0,
    ),
    quantity: deathWaveQuantity(
      weapon('Death Wave').quantity,
      coreSubstat('Death Wave - Quantity'),
      perk('Death Wave Quantity'),
    ),
    cooldownSeconds: deathWaveCooldown(
      weapon('Death Wave').cooldown, coreSubstat('Death Wave - Cooldown'), timeBoost,
    ),
    damageAmplifierLabLevel: lab.deathWaveDamageAmplifier,
  })

  /** `EF5` — the only weapon whose output moves when a bullet stat does. */
  const chainLightning = shadow.ultimateWeaponOverrides?.chainLightning ?? (
    weapon('Chain Lightning').unlocked
      ? chainLightningDps({
        damage: chainLightningDamage(
          weapon('Chain Lightning').damage,
          coreSubstat('Chain Lightning - Damage'),
          perk('Chain Lightning Damage'),
          weapon('Chain Lightning').vaultPct ?? 0,
        ),
        quantity: chainLightningQuantity(
          weapon('Chain Lightning').quantity,
          coreSubstat('Chain Lightning - Quantity'),
          unique('Dimension Core') > 0,
        ),
        chance: chainLightningChance(
          weapon('Chain Lightning').cooldown, coreSubstat('Chain Lightning - Chance'),
        ),
        attackSpeed: bps,
        rapidFire,
        multishot,
        bounce: bounceNoAstral,
        displayedGameSpeed: config.gameSpeed,
      })
      : 0
  )

  /*
   * `$AY$59` — the card ROW, without the cards master beside it.
   *
   * Every cooldown-based weapon takes this argument the same way:
   *
   *     EP_SM_DPS(SMB, SMQ, SMC, SMCF, EI5, $AY$30, $AY$59, RIGHT($AU$59, 1))
   *     EP_PS_DPS($BH$35, PSDmg, PSDur, PSCd, ..., $AY$59, RIGHT($AU$59, 1))
   *     EP_ILM_DPS($BH$37, ILMDmg, ..., $AY$36, $AY$59, RIGHT($AU$59, 1))
   *
   * `$AY$39`, the master, appears in none of them. This ANDed it in, so on any
   * account with cards switched off at the head but Area of Effect switched on
   * in its row, EVERY ultimate weapon's DPS came out short by exactly the
   * card's own multiplier.
   *
   * On `account-26` that factor is `AV59 = 0.11`, and the whole UW total `EO5`
   * was 1/1.11 of the sheet's — 0.90090090, to eight figures, on all four
   * weapons at once. The bullet columns matched exactly, which is why nine
   * planned steps agreed before the ranking tipped.
   *
   * Second instance of this exact mistake: `Demon Mode Mastery`'s gate had it
   * too. Both were found by a 150-account path sweep and neither by reading.
   */
  const areaOfEffect = {
    hasAreaOfEffectCard: card('Area of Effect').active,
    areaOfEffectCardLevel: card('Area of Effect').level,
  }

  /** `EI5` — the Smart Missile heat-up, which Spotlight Missiles share. */
  const missileHeatUp = ultimateWeaponHeatUp(
    1 + 1.5 * lab.missileAmplifier, Math.max(1, config.heatUpHits.smartMissiles),
  )

  const smDamage = smartMissileDamage(
    weapon('Smart Missiles').damage,
    coreSubstat('Smart Missiles - Damage'),
    weapon('Smart Missiles').vaultPct ?? 0,
  )
  const smCooldown = smartMissileCooldown(
    weapon('Smart Missiles').cooldown, coreSubstat('Smart Missiles - Cooldown'), timeBoost,
  )

  /** `EG5`. */
  const smartMissiles = shadow.ultimateWeaponOverrides?.smartMissiles ?? (weapon('Smart Missiles').unlocked
    ? smartMissilesDps({
      damage: smDamage,
      quantity: smartMissileQuantity(
        weapon('Smart Missiles').quantity,
        coreSubstat('Smart Missiles - Quantity'),
        perk('More Smart Missiles'),
      ),
      cooldownSeconds: smCooldown,
      // `STAT_UW_SM_FINAL_CF(SMB, $BL$32)` — Cover Fire is a *rate*, the
      // missile's damage over the interval between bursts, which is why it
      // is added after the cooldown divide rather than before it.
      coverFire: smartMissileDamagePerSecond(smDamage, weapon('Smart Missiles').plus),
      heatUp: missileHeatUp,
      areaOfEffect: config.areaOfEffect.smartMissiles,
      ...areaOfEffect,
    })
    : 0)

  /** Spotlight's own damage, which every other weapon is measured against. */
  const spotlightLight = spotlightLightRange(weapon('Spotlight').plus, rangeDamage)
  const slDamage = spotlightDamage({
    base: weapon('Spotlight').damage,
    lightRange: spotlightLight,
    substat: coreSubstat('Spotlight - Bonus'),
    relicPct: config.ultimateWeaponDamageRelicPct,
    vaultPct: shadow.spotlightVaultPct ?? ultimateWeaponVaultPct,
    weaponVaultPct: weapon('Spotlight').vaultPct ?? 0,
    hasPerk: perk('Spotlight Damage Bonus'),
  }) * ultimateDisco

  /** `ED5` — the coverage-weighted bonus, on the bullet half only. */
  /*
       * Nine of the eleven `eDamage Keys` candidates end on the base row's
       * Spotlight — `SL, $EE5` on the planner tab (v5.10; was ED5 before the
       * Avg Time Boost column landed). Not just its vault component — the
       * whole column, which also carries the light range and therefore RDPM,
       * so bumping Damage / Meter or Range moves Spotlight in a full
       * recomputation and not on the sheet.
       */
  const spotlight = shadow.frozenSpotlightBonus ?? (weapon('Spotlight').unlocked
    ? spotlightFinalBonus(
      spotlightCoverage(spotlightQuantityOf(config, levels, shadow), spotlightAngleDegrees),
      slDamage,
    )
    : 1)

  /**
   * `EH5` — the missiles a lit Smart Missile fires.
   *
   * Spotlight Missiles do not need Smart Missiles to be unlocked. Without it
   * the sheet substitutes a base of 10 — `IF($BH$32, $BI$32, 10)` — so a
   * player who has Spotlight and its `+` but never bought Smart Missiles still
   * gets them, just off an unupgraded base.
   */
  const spotlightMissileBase = weapon('Smart Missiles').unlocked
    ? weapon('Smart Missiles').damage
    : UNLOCKED_SMART_MISSILE_BASE_DAMAGE

  const spotlightMissiles
    = shadow.ultimateWeaponOverrides?.spotlightMissiles ?? (weapon('Spotlight').unlocked && weapon('Spotlight Missiles').unlocked
      ? spotlightMissilesDps({
        smartMissileDamage: smartMissileDamage(
          spotlightMissileBase, coreSubstat('Smart Missiles - Damage'),
          weapon('Smart Missiles').vaultPct ?? 0,
        ),
        spotlightDamage: slDamage,
        cooldownSeconds: shadow.spotlightMissilesCooldownSeconds ?? 20 - lab.spotlightMissiles,
        heatUp: missileHeatUp,
        // Spotlight Missiles are Smart Missiles, so they share its estimate.
        areaOfEffect: config.areaOfEffect.smartMissiles,
        ...areaOfEffect,
      })
      : 0)

  /** `EK5` — Poison Swamp's own heat-up, from its Death Creep `+`. */
  const swampDeathCreep = ultimateWeaponHeatUp(
    1 + (weapon('Poison Swamp').plus ?? 0.5), Math.max(1, config.heatUpHits.poisonSwamp),
  )

  /** `EJ5`, or the stone tab's if this is the keys band — see the shadow. */
  const poisonSwamp = shadow.ultimateWeaponOverrides?.poisonSwamp ?? poisonSwampDps({
    unlocked: weapon('Poison Swamp').unlocked,
    damage: (weapon('Poison Swamp').damage + coreSubstat('Poison Swamp - Damage'))
      * (1 + (weapon('Poison Swamp').vaultPct ?? 0)),
    durationSeconds: weapon('Poison Swamp').quantity,
    cooldownSeconds: weapon('Poison Swamp').cooldown,
    // `EJ5` passes `$EK$5 * $AY$31` — the heat-up and the area together.
    deathCreep: swampDeathCreep * config.areaOfEffect.poisonSwamp,
    rend: 1 + (rend - 1) * lab.swampRend * 0.03,
    ...areaOfEffect,
  })

  /** `EL5` — the only weapon the Armor module reaches, via Space Displacer. */
  const landMineChance
    = config.landMineChance + substat('Land Mine Chance', armorCapacity)
  const spaceDisplacerMines
    = config.enemySpawnsPerSecond * landMineChance * unique('Space Displacer')
  const ilmQuantity = innerLandMineQuantity(
    weapon('Inner Land Mines').quantity,
    coreSubstat('Inner Land Mines - Quantity'),
    perk('Extra Inner Mines'),
  )
  const ilmCooldown = (() => {
    const raw = weapon('Inner Land Mines').cooldown
    const added = coreSubstat('Inner Land Mines - Cooldown')
    if (!shadow.innerLandMineCooldownFromDisplayCell) return raw + added
    // `$AY$10` = MAX(37, BK37 + AM41 + AR41), and the candidate adds the
    // substat on top of it. See
    // {@link EffectiveDamageShadow.innerLandMineCooldownFromDisplayCell}.
    const pair = config.substats['Inner Land Mines - Cooldown']
    /*
     * `AR41` is `AO41 * $AO$24`, and `$AO$24` is the literal `0` sitting in
     * eDamage's "Substat Compared To:" block (`AM24` "Common", `AN24` 0.01,
     * `AO24` 0). So the term is zero and is left out rather than guessed at.
     * Reading it as the core module's assist bonus was tried and overshot:
     * Chrono Jump went from 1.0000270 to 0.9999906, past the mark.
     */
    const display = Math.max(SHEET_ILM_COOLDOWN_FLOOR, raw + pair.primary)
    return display + added
  })()

  /** `EM5` — ILM+ Heat. */
  const innerLandMineHeatUp = ultimateWeaponHeatUp(1, config.heatUpHits.innerLandMines)

  const innerLandMines = shadow.ultimateWeaponOverrides?.innerLandMines ?? innerLandMinesDps({
    unlocked: weapon('Inner Land Mines').unlocked,
    damage: innerLandMineDamage(
      weapon('Inner Land Mines').damage,
      coreSubstat('Inner Land Mines - Damage'),
      weapon('Inner Land Mines').vaultPct ?? 0,
    ),
    detonationsPerSecond: ilmQuantity / ilmCooldown + spaceDisplacerMines,
    chronoJump: lab.innerLandMineChronoJump * 5 * innerLandMineHeatUp,
    /*
     * The unowned neutral, which the two tabs do NOT agree on.
     *
     *   eDamage!EL5        EP_ILM_DPS(..., N($BL$37), ...)
     *   eDamage Stone!DY5  ILMCM, IF(CJ5=-1, 1, N(DVT_UW_STAT(...)))
     *
     * `$BL$37` holds the string `"Locked"` until the `+` is bought and `N()` of
     * a string is **0**, so the base tab zeroes the charged-mine term outright.
     * The stone tab, which carries the level rather than the value, branches on
     * its `-1` sentinel to a multiplier of **1** instead.
     *
     * Porting either one everywhere breaks the other: `?? 0` made the stone
     * tab's `ILM` column read half the sheet's, and `?? 1` then made the base
     * tab's `EL5` read 421x it on `account-1`. So it is keyed on which tab is
     * being reproduced, like every other place the sheet disagrees with itself.
     */
    chargedMines: weapon('Inner Land Mines').plus
      ?? (shadow.weaponStatsFromStoneLevels ? 1 : 0),
    areaOfEffect: config.areaOfEffect.innerLandMines,
    ...areaOfEffect,
  })

  /** `EN5` — the Core module pair, which boosts every ultimate weapon. */
  const coreModule = moduleBonus({
    primaryBonus: moduleBonusAtLevel(
      'core', config.modules.core.primaryRarity,
      levels.coin.primaryModuleCore, config.modules.core.primaryBonus,
    ),
    hasAssist: config.modules.core.hasAssist,
    assistBonus: moduleBonusAtLevel(
      'core', config.modules.core.assistRarity,
      levels.coin.assistModuleCore, config.modules.core.assistBonus,
    ),
    stoneBonusCap: levels.stone.assistBonusCoreStone,
    labBonusCap: lab.assistBonusCore + levels.coin.assistBonusCore,
  })

  /**
   * The Ultimate Crit card, which is the *only* place the mastery appears —
   * it raises the share of the crit factor ultimate weapons receive.
   */
  const ultimateCritCard
    = config.cardsEquipped && card('Ultimate Crit').active
      ? 1 + (card('Ultimate Crit').value
        + (card('Ultimate Crit Mastery').active
          ? 0.0033 * (1 + lab.ultimateCritMastery + levels.coin.ultimateCritMastery)
          : 0))
      * (critInput.criticalFactor - 1)
      : 1

  /** `EO5`. */
  const ultimateWeapons = ultimateWeaponTotalDamage({
    deathWave,
    chainLightning,
    smartMissiles,
    spotlightDamage: spotlightMissiles,
    spotlightBonus: spotlight,
    poisonSwamp,
    innerLandMines,
    /*
     * `eDamage!CX6`, and it is a FROZEN PRODUCT: `(1+$BL$39)*(1+$BM$39)`, the
     * ultimate weapon damage relic times its vault.
     *
     * That matters for the keys planner and is why `eDamage Keys` does not
     * reach parity. The same vault also arrives as
     * `levels.keys.ultimateWeaponDamage` -- `eDamage Keys!BO5` is `=BM8/5%`
     * and its UW sibling `=BM39/5%` -- so buying a vault level moves
     * `spotlightDamage` below and CANNOT move this term. The composition is
     * exactly right, which is why every eDamage answer matches the sheet to
     * 1e-9 and nothing ever reported it; only the CANDIDATE is wrong, and only
     * on the one path that buys vault levels.
     *
     * Rebuilding it from the relic and the level was tried and reverted. It is
     * correct for today's sheet -- the identity holds live and on a 22-account
     * capture -- but `effective-paths-edamage-states.fixtures.json` predates
     * the current `CX6` and its stored `CX6` is not `(1+BL39)*(1+BM39)` for
     * ANY of its ten states (1.581 against 1.0, 3.963 against 1.207). Every
     * `EO5` it disagreed about was out by exactly that ratio. That fixture is
     * a bespoke copy with no capture script, so the derivation cannot be
     * checked against it, and shipping a model change that only one of two
     * fixtures can verify is worse than the gap it closes.
     *
     * Re-capturing the states fixture is what unblocks this.
     */
    damageBoost: config.ultimateWeaponAdditionalDamage
      * vaultResponse * coreModule * ultimateDisco,
    superTowerUltimateMastery: superTowerUltimate,
    ultimateCritCard,
  })

  // --- The slow, EP5 through ER5 ----------------------------------------

  // `AND(AY33, BH36)` — the weapon has to be unlocked *and* switched on.
  const chronoUnlocked = config.chronoFieldEnabled && weapon('Chrono Field').unlocked
  const chronoSubstat = coreSubstat('Chrono Field - Speed Reduction')
  // `MIN(90%, …)` is in the BASE column (`eDamage Stone!EB5`) and NOT in the
  // column that prices a CF Slow level (`FF5`) — see
  // {@link EffectiveDamageShadow.chronoSlowUnclamped}.
  const chronoReduction = weapon('Chrono Field').quantity + chronoSubstat
  const chronoSlow = chronoUnlocked
    ? 1 / (1 - (shadow.chronoSlowUnclamped ? chronoReduction : Math.min(CHRONO_SLOW_CAP, chronoReduction)))
    : 1
  const chronoPlusSlow = chronoUnlocked && weapon('Chrono Field').plus !== null
    ? 1 / (1 - (weapon('Chrono Field').plus as number))
    : 1
  const slow = chronoSlow * chronoPlusSlow
  const compositionSlow = shadow.frozenSlow ?? slow

  const effectiveDamage = composeEffectiveDamage({
    base,
    crit,
    bulletDamageMultiplier: bulletMultiplier,
    spotlight,
    ultimateWeapons,
    ultimateWeaponCrit: uwCrit,
    slow: compositionSlow,
  }) * cashBonusRatio

  return {
    base,
    crit,
    ultimateWeaponCrit: uwCrit,
    bulletDamageMultiplier: bulletMultiplier,
    spotlight,
    ultimateWeapons,
    slow,
    effectiveDamage,
    columns: {
      // v5.10: CY is Constant Value; computation band is CZ..ET (eDamage at ET).
      CZ5: attackDisco,
      DA5: damage,
      DB5: damagePerk,
      DC5: tradeOffPerk,
      DD5: shock,
      DE5: demonMode,
      DF5: cannonModule,
      DG5: shockwave,
      DH5: freeze,
      DI5: amp,
      DJ5: base,
      DK5: critInput.criticalChance,
      DL5: critInput.criticalFactor,
      DM5: critInput.superCritChance,
      DN5: critInput.superCritMultiplier,
      DO5: crit,
      DP5: uwCrit,
      DQ5: multishot,
      DR5: bounce,
      DS5: bounceNoAstral,
      DT5: rapidFire,
      DU5: bps,
      DV5: range,
      DW5: perMeter,
      DX5: rangeDamage,
      DY5: superTower,
      DZ5: superTowerUltimate,
      EA5: rend,
      EB5: bulletMultiplier,
      EC5: ultimateDisco,
      ED5: timeBoost,
      EE5: spotlight,
      EF5: deathWave,
      EG5: chainLightning,
      EH5: smartMissiles,
      EI5: spotlightMissiles,
      EJ5: missileHeatUp,
      EK5: poisonSwamp,
      EL5: swampDeathCreep,
      EM5: innerLandMines,
      EN5: innerLandMineHeatUp,
      EO5: coreModule,
      EP5: ultimateWeapons,
      EQ5: chronoSlow,
      ER5: chronoPlusSlow,
      ES5: slow,
      ET5: effectiveDamage,
    },
  }
}

// ---------------------------------------------------------------------------
// Small readers, kept out of the walk above so it stays readable
// ---------------------------------------------------------------------------

/**
 * The ten bullet stats the vault raises, and the keys level that raises each.
 *
 * The eleventh keys candidate is Ultimate Weapon Damage, which is not a bullet
 * stat and is applied to Spotlight's damage instead.
 */
/**
 * One workshop enhancement level is worth one percentage point, on every stat.
 *
 * Not assumed from the Damage-specific helper. Checked against the sheet's own
 * two columns — `BI` holds the level and `BK` the multiplier — and `BK` is
 * `1 + 0.01 × BI` exactly on every stat that carries an enhancement: Damage
 * 31/1.31, Critical Factor 57/1.57, Damage / Meter 41/1.41, Super Critical Mult
 * 9/1.09, Max Rend Armor Multiplier 75/1.75, Attack Speed 12/1.12. Stats with
 * no enhancement show `-`, which is what makes the list of six meaningful
 * rather than a partial read.
 */
export const ENHANCEMENT_MULTIPLIER_PER_LEVEL = 0.01

/**
 * Which coin-path candidate raises which stat's enhancement.
 *
 * Six of the seven `+` candidates. `Cash Bonus +` is deliberately absent: there
 * is no cash row among the damage workshop stats, so it has nothing to raise
 * here. It DOES appear in the sheet's coin paths, which means it reaches
 * effective damage by some route this model does not yet carry — recorded as an
 * open question rather than mapped onto the nearest stat to make a number move.
 */
const COIN_ENHANCEMENT_LEVELS: Partial<Record<
  keyof EffectiveDamageConfig['stats'],
  keyof EffectiveDamageLevels['coin']
>> = {
  'Damage': 'enhancementDamage',
  'Critical Factor': 'enhancementCriticalFactor',
  'Super Critical Mult': 'enhancementSuperCritMult',
  'Attack Speed': 'enhancementAttackSpeed',
  'Damage / Meter': 'enhancementDamagePerMeter',
  'Max Rend Armor Multiplier': 'enhancementRendArmor',
}

const KEYS_STAT_LEVELS: Partial<Record<
  keyof EffectiveDamageConfig['stats'],
  { sheetName: string, key: keyof EffectiveDamageLevels['keys'] }
>> = {
  'Damage': { sheetName: 'Damage', key: 'damage' },
  'Critical Chance': { sheetName: 'Critical Chance', key: 'criticalChance' },
  'Critical Factor': { sheetName: 'Critical Factor', key: 'criticalFactor' },
  'Super Critical Chance': { sheetName: 'Super Crit Chance', key: 'superCritChance' },
  'Super Critical Mult': { sheetName: 'Super Crit Mult', key: 'superCritMult' },
  'Attack Speed': { sheetName: 'Attack Speed', key: 'attackSpeed' },
  'Multishot Chance': { sheetName: 'Multishot Chance', key: 'multishotChance' },
  'Damage / Meter': { sheetName: 'Damage / Meter', key: 'damagePerMeter' },
  'Rapid Fire Chance': { sheetName: 'Rapid Fire Chance', key: 'rapidFireChance' },
  'Bounce Shot Chance': { sheetName: 'Bounce Shot Chance', key: 'bounceShotChance' },
}

/** The literal `37` in `eDamage!AY10`'s `MAX(37, ...)`. */
const SHEET_ILM_COOLDOWN_FLOOR = 37

/**
 * How much of an assist module's substat counts, for one module.
 *
 * The stone half is bought by the stone path and the lab half by the lab and
 * coin paths, and the two add rather than replacing each other. Cannon and
 * Core take theirs from `levels`, because a path can buy them; Armor and
 * Generator have no candidate, so their stone level stays in the config.
 */
function assistCapacity(
  config: EffectiveDamageConfig,
  levels: EffectiveDamageLevels,
  slot: ModuleSlot,
  shadow: EffectiveDamageShadow,
  /** Which level caps it. `bonus` is the coin tab's Max Rend quirk. */
  from: 'substat' | 'bonus' = 'substat',
): number {
  const module = config.modules[slot]
  const stone = slot === 'cannon'
    ? levels.stone.assistSubstatCannonStone
    : slot === 'core'
      ? levels.stone.assistSubstatCoreStone
      : slot === 'armor'
        ? levels.stone.assistSubstatArmorStone
        : module.substatStoneLevel
  const labLevel = from === 'bonus'
    ? levels.lab.assistBonusCannon + levels.coin.assistBonusCannon
    : slot === 'cannon'
      ? levels.lab.assistSubstatCannon + levels.coin.assistSubstatCannon
    : slot === 'core'
      ? levels.lab.assistSubstatCore + levels.coin.assistSubstatCore
      : slot === 'armor'
        ? levels.lab.assistSubstatArmor + levels.coin.assistSubstatArmor
        : 0
  // See {@link EffectiveDamageShadow.cannonAssistCapUsesCoreFlag}.
  const hasAssist = slot === 'cannon' && shadow.cannonAssistCapUsesCoreFlag
    ? config.modules.core.hasAssist
    : module.hasAssist
  return assistSubstatCap(hasAssist, stone, labLevel)
}

/**
 * A module's bonus at the level the path has taken it to, when the rarity is
 * known. The coin path buys module levels, so this has to move with them.
 */
function moduleBonusAtLevel(
  type: 'cannon' | 'core',
  rarity: string | undefined,
  level: number,
  fallback: number,
): number {
  return rarity && level > 0
    ? computeModuleStat({ type, rarityLabel: rarity, level })
    : fallback
}

/** What one call to {@link bulletStats} needs from the walk above. */
interface BulletStatsInput {
  config: EffectiveDamageConfig
  labLevels: EffectiveDamageLevels['lab']
  stat: (name: keyof EffectiveDamageConfig['stats']) => DamageStatSource
  cannonSubstat: (name: DamageSubstat) => number
  /** Already resolved, because the perk gate belongs with the other perks. */
  bounceShotPerkTargets: number
  card: (name: DamageCard) => DamageCardSource
  /** Mastery levels are labs, and the coin path buys the same ones. */
  attackSpeedMasteryLevel: number
  rangeMasteryLevel: number
  /** The Astral Deliverance unique, which adds bounces that do not proc. */
  astralDeliverance: number
}

/**
 * `DP5` through `DZ5` — everything a bullet does, and the Attack Dissonance
 * guard every one of them opens with.
 *
 * Kept together because the guard is the same each time: the tower does not
 * fire, so each column collapses to its own identity — one for a multiplier,
 * zero for damage per meter, and the base 30 metres for range.
 */
function bulletStats(input: BulletStatsInput) {
  const { config, labLevels: lab, stat, cannonSubstat, card } = input
  const attacksPerSecond = config.runType === 'Attack Disso'
    ? 1
    : attackSpeed({
      workshopLevel: stat('Attack Speed').workshopLevel,
      enhancementLevel: stat('Attack Speed').enhancementLevel,
      labLevel: lab.attackSpeed,
      hasAttackSpeedCard: config.cardsEquipped && card('Attack Speed').active,
      cardLevel: card('Attack Speed').level,
      hasCardMastery: card('Attack Speed Mastery').active,
      masteryLevel: input.attackSpeedMasteryLevel,
      substat: cannonSubstat('Attack Speed'),
      relicPct: stat('Attack Speed').relicPct,
      vaultPct: stat('Attack Speed').vaultPct,
    })

  /** `DT5`. */
  const bps = bulletsPerSecond(attacksPerSecond)

  /** `DP5`. */
  const multishot = config.runType === 'Attack Disso'
    ? 1
    : multishotMultiplier(
      multishotChance(
        stat('Multishot Chance').workshopLevel,
        cannonSubstat('MultiShot Chance'),
        stat('Multishot Chance').vaultPct,
      ),
      multishotTargets(
        stat('Multishot Targets').workshopLevel,
        cannonSubstat('Multishot Targets'),
      ),
    )

  const bounceChance = bounceShotChance(
    stat('Bounce Shot Chance').workshopLevel,
    cannonSubstat('Bounce Shot Chance'),
    stat('Bounce Shot Chance').vaultPct,
  )
  const bounceTargets = bounceShotTargets(
    stat('Bounce Shot Targets').workshopLevel,
    input.bounceShotPerkTargets,
    cannonSubstat('Bounce Shot Targets'),
  )

  /** `DQ5` — with Astral Deliverance, which the bullet multiplier uses. */
  const bounce = config.runType === 'Attack Disso'
    ? 1
    : bounceShotMultiplier(bounceChance, bounceTargets, input.astralDeliverance)
  /**
   * `DR5` — the same without it. Chain Lightning reads this one, because
   * Astral Deliverance's extra bounces do not roll for a proc.
   */
  const bounceNoAstral = config.runType === 'Attack Disso'
    ? 1
    : bounceShotMultiplier(bounceChance, bounceTargets, 0)

  /** `DS5`. */
  const rapidFire = config.runType === 'Attack Disso'
    ? 1
    : rapidFireMultiplier(
      rapidFireChance(
        stat('Rapid Fire Chance').workshopLevel,
        cannonSubstat('Rapid Fire Chance'),
        stat('Rapid Fire Chance').vaultPct,
      ),
      rapidFireDuration(
        stat('Rapid Fire Duration').workshopLevel,
        cannonSubstat('Rapid Fire Duration'),
      ),
      bps,
    )

  /** `DU5` — range, which an Attack Dissonance run fixes at the base 30m. */
  const range = config.runType === 'Attack Disso'
    ? 30
    : attackRange({
      workshopLevel: stat('Range').workshopLevel,
      hasRangeCard: config.cardsEquipped && card('Range').active,
      cardLevel: card('Range').level,
      labLevel: lab.range,
      substat: cannonSubstat('Attack Range'),
    })

  /** `DV5`. */
  const perMeter = config.runType === 'Attack Disso'
    ? 0
    : damagePerMeter({
      workshopValue: stat('Damage / Meter').workshopValue,
      enhancementLevel: stat('Damage / Meter').enhancementLevel,
      labLevel: lab.damagePerMeter,
      substat: cannonSubstat('Damage / Meter'),
      relicPct: stat('Damage / Meter').relicPct,
      vaultPct: stat('Damage / Meter').vaultPct,
      hasRangeMastery: card('Range Mastery').active,
      masteryLevel: input.rangeMasteryLevel,
    })

  /** `DW5`. */
  const rangeDamage = config.runType === 'Attack Disso'
    ? 1
    : rangeDamageMultiplier(range, perMeter, config.damageAtRangePct)
  return { bps, multishot, bounce, bounceNoAstral, rapidFire, range, perMeter, rangeDamage }
}

function statOf(
  config: EffectiveDamageConfig,
  name: keyof EffectiveDamageConfig['stats'],
) {
  return config.stats[name]
}

function uniqueOf(
  config: EffectiveDamageConfig,
  name: keyof EffectiveDamageConfig['uniques'],
): number {
  const pair = config.uniques[name]
  return pair.primary + pair.assist
}

function cardOf(
  config: EffectiveDamageConfig,
  name: keyof EffectiveDamageConfig['cards'],
) {
  return config.cards[name]
}


/**
 * Which field of an ultimate weapon's row each stone candidate moves.
 *
 * ## Why this is written out rather than derived by position
 *
 * The weapon row is four columns -- `BI` damage, `BJ` quantity, `BK` cooldown,
 * `BL` plus -- and the stone candidates come in matching groups, so mapping the
 * Nth candidate to the Nth field looks obviously right. It is wrong for two of
 * the seven weapons, and wrong silently:
 *
 *   - **Chrono Field** has two candidates, Slow and Chrono Loop, and the model
 *     reads `.quantity` and `.plus`. It never reads `.damage` at all, so a
 *     positional rule would have written Slow into a field nothing consults.
 *   - **Spotlight** reads `.damage` (Multiplier), `.quantity` (Angle) and
 *     `.plus` (Light Range) -- while its actual *quantity* comes from somewhere
 *     else entirely, `config.spotlightQuantity`, the sheet's `AY8`.
 *     Positionally, `SL Quantity` would have landed in `.cooldown`, which
 *     Spotlight does not use.
 *
 * Both would have produced a wired-looking model with dead stats in it, which
 * is the very defect this table exists to fix. Every entry was read off the
 * call site that consumes it, and the stone sweep test proves each of the 24
 * moves effective damage rather than trusting the list.
 */
const STONE_STAT_FIELDS: Readonly<Record<string, {
  sheetName: string
  weapon: keyof EffectiveDamageConfig['ultimateWeapons']
  field: 'damage' | 'quantity' | 'cooldown' | 'plus' | 'spotlightQuantity'
}>> = {
  deathWaveDamage: { sheetName: 'DW Damage', weapon: 'Death Wave', field: 'damage' },
  deathWaveQuantity: { sheetName: 'DW Quantity', weapon: 'Death Wave', field: 'quantity' },
  deathWaveCooldown: { sheetName: 'DW Cooldown', weapon: 'Death Wave', field: 'cooldown' },
  chainLightningDamage: { sheetName: 'CL Damage', weapon: 'Chain Lightning', field: 'damage' },
  chainLightningQuantity: {
    sheetName: 'CL Quantity', weapon: 'Chain Lightning', field: 'quantity',
  },
  // `chainLightningChance(weapon('Chain Lightning').cooldown, ...)` -- the third
  // column is the weapon's cooldown-OR-EQUIVALENT, and Chain Lightning's is a
  // proc chance.
  chainLightningChance: { sheetName: 'CL Chance', weapon: 'Chain Lightning', field: 'cooldown' },
  smartMissileDamage: { sheetName: 'SM Damage', weapon: 'Smart Missiles', field: 'damage' },
  smartMissileQuantity: { sheetName: 'SM Quantity', weapon: 'Smart Missiles', field: 'quantity' },
  smartMissileCooldown: { sheetName: 'SM Cooldown', weapon: 'Smart Missiles', field: 'cooldown' },
  smartMissileCoverFire: { sheetName: 'SM Cover Fire', weapon: 'Smart Missiles', field: 'plus' },
  spotlightDamage: { sheetName: 'SL Damage', weapon: 'Spotlight', field: 'damage' },
  spotlightAngle: { sheetName: 'SL Angle', weapon: 'Spotlight', field: 'quantity' },
  spotlightQuantity: {
    sheetName: 'SL Quantity', weapon: 'Spotlight', field: 'spotlightQuantity',
  },
  spotlightLightRange: { sheetName: 'SL Light Range', weapon: 'Spotlight', field: 'plus' },
  poisonSwampDamage: { sheetName: 'PS Damage', weapon: 'Poison Swamp', field: 'damage' },
  poisonSwampDuration: { sheetName: 'PS Duration', weapon: 'Poison Swamp', field: 'quantity' },
  poisonSwampCooldown: { sheetName: 'PS Cooldown', weapon: 'Poison Swamp', field: 'cooldown' },
  poisonSwampDeathCreep: { sheetName: 'PS Death Creep', weapon: 'Poison Swamp', field: 'plus' },
  innerLandMineDamage: { sheetName: 'ILM Damage', weapon: 'Inner Land Mines', field: 'damage' },
  innerLandMineQuantity: {
    sheetName: 'ILM Quantity', weapon: 'Inner Land Mines', field: 'quantity',
  },
  innerLandMineCooldown: {
    sheetName: 'ILM Cooldown', weapon: 'Inner Land Mines', field: 'cooldown',
  },
  innerLandMineChargedMines: {
    sheetName: 'ILM Charged Mines', weapon: 'Inner Land Mines', field: 'plus',
  },
  chronoFieldSlow: { sheetName: 'CF Slow', weapon: 'Chrono Field', field: 'quantity' },
  chronoFieldChronoLoop: { sheetName: 'CF Chrono Loop', weapon: 'Chrono Field', field: 'plus' },
}

/** The stone level keys that reach a weapon stat, for the test that checks them. */
export const STONE_STAT_FIELD_KEYS: readonly string[] = Object.keys(STONE_STAT_FIELDS)

/**
 * The five stone stats that live in a weapon's `+` column, by sheet name.
 *
 * `BL` reads the string `"Locked"` until the `+` is bought, which the config
 * carries as `plus: null`. The stone tab hides those candidates then — not
 * through its row-2 flag, which only checks the weapon, but inside the shadow
 * itself, so the ROI cell simply comes back blank.
 *
 * Confirmed by reading a row rather than by reasoning: on `account-3` the
 * sheet shows ILM Damage, Quantity and Cooldown and blanks ILM Charged Mines.
 * The weapon is plainly owned; only the `+` is not.
 */
export const STONE_PLUS_STATS: ReadonlySet<string> = new Set(
  Object.values(STONE_STAT_FIELDS)
    .filter(entry => entry.field === 'plus')
    .map(entry => entry.sheetName),
)

/**
 * One stone stat's value at the level the path has taken it to.
 *
 * `null` when the level is 0 or the chart does not price it -- level 0 is the
 * weapon's unlock, not a stat value -- and the caller then keeps whatever the
 * config observed. That is what makes this safe for the four paths that do NOT
 * buy stones: their stone levels never move, so the value never changes.
 */
function stoneStatValue(levels: EffectiveDamageLevels, key: string): number | null {
  const entry = STONE_STAT_FIELDS[key]
  if (!entry) return null
  const level = (levels.stone as unknown as Record<string, number>)[key]
  // Level 0 is a real level here — `DVT_UW_STAT` prices a stat from 0 upwards
  // and only its COST is the string "Unlock". Treating 0 as "no answer" is
  // what made the baseline fall back to the observed value; see
  // {@link EffectiveDamageShadow.weaponStatsFromStoneLevels}.
  if (!Number.isFinite(level) || level < 0) return null
  const stat = resolveUltimateWeaponStat(entry.sheetName)
  if (!stat) return null
  return ultimateWeaponStatValue(stat.weapon, stat.stat, Math.floor(level))
}

/**
 * The Spotlight count, which the stone path can buy and the weapon row cannot
 * hold. `AY8` on the sheet; `SL Quantity` in the stone band.
 */
function spotlightQuantityOf(
  config: EffectiveDamageConfig,
  levels: EffectiveDamageLevels,
  shadow: EffectiveDamageShadow,
): number {
  if (!shadow.weaponStatsFromStoneLevels) return config.spotlightQuantity
  return stoneStatValue(levels, 'spotlightQuantity') ?? config.spotlightQuantity
}

/**
 * A weapon's row with every stone-bought stat resolved from its LEVEL.
 *
 * The config carries what the player's stats are *now*; the stone path buys
 * levels, and the sheet turns a level into a value with
 * `DVT_UW_STAT(weapon, stat, level)`. Reading only the config meant the stone
 * band moved 24 levels that reached nothing: every candidate gained exactly
 * zero, and the planner then returned the candidate list in declaration order.
 */
function weaponOf(
  config: EffectiveDamageConfig,
  levels: EffectiveDamageLevels,
  name: keyof EffectiveDamageConfig['ultimateWeapons'],
  shadow: EffectiveDamageShadow,
) {
  const base = config.ultimateWeapons[name]
  if (!shadow.weaponStatsFromStoneLevels) return base
  let row: (typeof base) | null = null
  for (const key of STONE_STAT_FIELD_KEYS) {
    const entry = STONE_STAT_FIELDS[key]
    if (entry.weapon !== name || entry.field === 'spotlightQuantity') continue
    // `-1` is the stone tab's "not owned" marker for a `+` stat, written by
    // `IFERROR(VALUE(LEFT(IDS_UW_LEVEL(...), 2)), -1)` in row 5. Every consumer
    // of a `+` guards on it explicitly rather than pricing level -1:
    //
    //     SMCF  = IF(BX5>-1, STAT_UW_SM_FINAL_CF(...), 0)
    //     SLLR  = IF(CB5=-1, 1, STAT_UW_SL_FINAL_LR(...))
    //     PS DC = 1 + IF(CF5=-1, 0.5, DVT_UW_STAT(...))
    //     ILMCM = IF(CJ5=-1, 1, N(DVT_UW_STAT(...)))
    //     CF+   = IF(AND(..., CL5>-1), 1/(1-DVT_UW_STAT(...)), 1)
    //
    // Carrying it as `plus: null` puts each of those neutrals in exactly one
    // place -- the helper that already takes `number | null`. Falling through
    // to the config's OBSERVED value instead, which is what happened before,
    // made an unowned `+` read as owned, and it is why the stone tab's `ILM`
    // column came out at half ours and `UWs` at anywhere from 0.55x to 1.24x.
    if (entry.field === 'plus'
      && (levels.stone as unknown as Record<string, number>)[key] === -1) {
      row ??= { ...base }
      row.plus = null
      continue
    }
    const value = stoneStatValue(levels, key)
    if (value === null) continue
    row ??= { ...base }
    row[entry.field] = value
  }
  return row ?? base
}

/**
 * `eDamage!EC5` — what recovery packages do to the length of a wave.
 *
 * The econ tab computes the same thing in `EPC_GCOMP`, so the arithmetic lives
 * in {@link recoveryPackageTimeBoost} and this only assembles the inputs.
 */
function waveTimeBoost(config: EffectiveDamageConfig): number {
  const compressor = config.uniques['Galaxy Compressor']
  return recoveryPackageTimeBoost({
    chance: config.waveAcceleratorRecovery + config.recovery.durationBonus,
    afterBoss: config.recovery.bossWave,
    bossWaveInterval: config.recovery.bossWaveDivisor,
    galaxyCompressorValue: compressor.primary + compressor.assist,
    waveDurationSeconds: config.waveDurationSeconds,
  })
}
