/**
 * Effective Paths — stone costs for the five card masteries on the econ stone tab.
 *
 * `eEcon Stones!EA5:EE5` ranks each mastery by pasting a cell from `eEcon!AX32`
 * / neighbours. Those cells already divide by a stone price:
 *
 * | Mastery | Cell | Denominator |
 * |---|---|---|
 * | Coins Mastery | AX32 | 1250 |
 * | Extra Orb Mastery | AX34 | 750 |
 * | Wave Skip Mastery | AX36 | 1000 |
 * | Intro Sprint Mastery | AX38 | 1250 |
 * | Wave Accelerator Mastery | AX41 | 1000 |
 *
 * This port prices each step with those denominators and scores it through
 * `computeEffectiveEconomy`. Coins / Extra Orb sheet numerators are simple
 * heuristics (~3% / tag-share×4%); the three wave cells rewrite the model —
 * scoring through the model is the honest match for those, and close for the
 * two heuristics (oracle: 0.03 vs model ~0.029 at compare level 0).
 */
/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    STONE_MASTERY_COSTS, STONE_MASTERY_LEVEL_KEY_BY_NAME, STONE_MASTERY_CARD_KEY_BY_NAME, STONE_MASTERY_NAMES, STONE_MASTERY_MAX_LEVEL, isStoneMasteryOwned, withStoneMasteriesActivated
 * depends    src/mechanics/effective-paths/coin-costs, src/mechanics/effective-paths/eecon-compute, src/mechanics/effective-paths/eecon-levels
 * used by    src/mechanics/calculators/specs-generated, src/mechanics/effective-paths/eecon-plan, src/mechanics/effective-paths/index
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */

import type { EffectiveEconomyConfig } from './eecon-compute'
import type { EffectiveEconomyLevels } from './eecon-levels'
import { CARD_MASTERY_MAX_LEVEL } from './coin-costs'

/** Sheet name → stone cost baked into the AX ROI cell. */
export const STONE_MASTERY_COSTS: Readonly<Record<string, number>> = {
  'Coins Mastery': 1250,
  'Extra Orb Mastery': 750,
  'Wave Skip Mastery': 1000,
  'Intro Sprint Mastery': 1250,
  'Wave Accelerator Mastery': 1000,
}

/** Sheet name → `levels.time` key. */
export const STONE_MASTERY_LEVEL_KEY_BY_NAME: Readonly<
  Record<string, keyof EffectiveEconomyLevels['time']>
> = {
  'Coins Mastery': 'coinsMastery',
  'Extra Orb Mastery': 'extraOrbMastery',
  'Wave Skip Mastery': 'waveSkipMastery',
  'Intro Sprint Mastery': 'introSprintMastery',
  'Wave Accelerator Mastery': 'waveAcceleratorMastery',
}

/** Sheet name → which `config.cards` flag `IDS_CARD_MASTERY` reads. */
export const STONE_MASTERY_CARD_KEY_BY_NAME: Readonly<
  Record<string, keyof EffectiveEconomyConfig['cards']>
> = {
  'Coins Mastery': 'coinsMastery',
  'Extra Orb Mastery': 'extraOrbMastery',
  'Wave Skip Mastery': 'waveSkipMastery',
  'Intro Sprint Mastery': 'introSprintMastery',
  'Wave Accelerator Mastery': 'waveAcceleratorMastery',
}

export const STONE_MASTERY_NAMES = new Set(Object.keys(STONE_MASTERY_COSTS))

/** Highest mastery level the stone path may buy. */
export const STONE_MASTERY_MAX_LEVEL = CARD_MASTERY_MAX_LEVEL

/**
 * Whether the sheet's hide row would drop this mastery as already owned.
 *
 * `eEcon Stones!EA2` is, in full and identically for all five:
 *
 *   =OR(IDS_CARD_MASTERY(LEFT(EA4, LEN(EA4)-8)),
 *       AND($AZ$11, NOT(IDS_LAB_HAS_UNLOCKED(EA4))))
 *
 * so exactly two things hide a mastery candidate: it is already unlocked, or
 * "hide non-unlocked labs" is on and its lab is not researched. Nothing about
 * the card being EQUIPPED appears anywhere in it.
 *
 * This read `config.cards[key].active` — the equipped toggle, `eEcon!AZ34` and
 * its siblings, which are hand-set booleans and not `IDS_CARD_MASTERY` at all.
 * On the generated sweep that excluded Extra Orb Mastery and Wave Accelerator
 * Mastery as "already unlocked" while the sheet was ranking both.
 */
export function isStoneMasteryOwned(
  sheetName: string,
  config: EffectiveEconomyConfig,
): boolean {
  const key = STONE_MASTERY_CARD_KEY_BY_NAME[sheetName]
  return key ? Boolean(config.cards[key]?.masteryUnlocked) : false
}

/**
 * Config for scoring a stone path that has just bought a mastery level.
 *
 * Buying the first level is what flips `IDS_CARD_MASTERY` on the sheet. The
 * model gates each mastery term on that flag, so without this a level-up from
 * zero would score as gain zero and never win a step.
 */
export function withStoneMasteriesActivated(
  config: EffectiveEconomyConfig,
  before: EffectiveEconomyLevels,
  after: EffectiveEconomyLevels,
): EffectiveEconomyConfig {
  let cards = config.cards
  let changed = false

  for (const [sheetName, cardKey] of Object.entries(STONE_MASTERY_CARD_KEY_BY_NAME)) {
    if (cards[cardKey].active) continue
    const levelKey = STONE_MASTERY_LEVEL_KEY_BY_NAME[sheetName]
    if (!levelKey) continue
    if (after.time[levelKey] <= before.time[levelKey]) continue
    if (!changed) {
      cards = { ...cards }
      changed = true
    }
    cards = {
      ...cards,
      [cardKey]: { ...cards[cardKey], active: true },
    }
  }

  return changed ? { ...config, cards } : config
}
