/**
 * Effective Paths — planning an eEcon path.
 *
 * Three paths across three currencies. The time and coin paths rank the same
 * 23 candidates priced two ways; the stone path ranks ultimate weapon upgrades;
 * the discount path is not comparable to either, because it maximises coins
 * saved rather than coins earned.
 *
 * As on the other two domains, every candidate is scored by what a level does
 * to the *whole* model rather than to its own stat — Golden Tower's duration
 * pays through the synchronisation term, not just through its own row.
 */
/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    EffectiveEconomyPlanVariant, ECONOMY_PLAN_VARIANTS, DISCOUNT_PATH_UNSUPPORTED, SHEET_DEFAULT_COINS_PER_HOUR, EffectiveEconomyUpgrade, EFFECTIVE_ECONOMY_UPGRADES, EffectiveEconomyPlanOptions, EffectiveEconomyPlan (+2 more)
 * depends    src/mechanics/effective-paths/assist-efficiency, src/mechanics/effective-paths/coin-costs, src/mechanics/effective-paths/edamage-costs, src/mechanics/effective-paths/eecon-candidates, src/mechanics/effective-paths/eecon-compute, src/mechanics/effective-paths/eecon-levels (+6 more)
 * used by    src/mechanics/calculators/specs-generated, src/mechanics/effective-paths/index, src/mechanics/effective-paths/input-ranges, src/save/effective-paths/from-save
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */

import { EFFECTIVE_ECONOMY_CANDIDATES_BY_PATH } from './eecon-candidates'
import {
  ECONOMY_DISCOUNT_LEVEL_KEYS,
  ECONOMY_STONE_LEVEL_REFS,
  ECONOMY_TIME_LEVEL_KEYS,
} from './eecon-levels'
import type { EffectiveEconomyLevels } from './eecon-levels'
import { checkEffectiveEconomyLevels } from './levels-schema'
import type { EffectiveLevelsIssue } from './levels-schema'
import { COMPARE_MASTERIES_AT_DEFAULT, computeEffectiveEconomy } from './eecon-compute'
import type { EffectiveEconomyShadow } from './eecon-compute'
import type { EffectiveEconomyConfig } from './eecon-compute'
import {
  assistEfficiencyStoneCost,
  maxStoneLevel,
} from './assist-efficiency'
import {
  isStoneMasteryOwned,
  STONE_MASTERY_CARD_KEY_BY_NAME,
  STONE_MASTERY_COSTS,
  STONE_MASTERY_LEVEL_KEY_BY_NAME,
  STONE_MASTERY_MAX_LEVEL,
  STONE_MASTERY_NAMES,
  withStoneMasteriesActivated,
} from './eecon-stone-mastery'
import {
  applyUwCdPurchases,
  isUwCdCandidateVisible,
  uwCdRemainingPurchases,
  uwCdStoneCost,
} from './eecon-uw-cd'
import {
  ultimateWeaponMaxLevel,
  ultimateWeaponStoneCost,
} from './edamage-costs'
import {
  MODULE_COIN_PATH_MAX_LEVEL,
  MODULE_COIN_PATH_MIN_LEVEL,
  moduleUpgradeCoinCost,
} from './coin-costs'
import {
  enhancementCoinCost,
  enhancementMaxLevel,
  UTILITY_ENHANCEMENT_SPEND_UNLOCKS,
  workshopEnhancementCoinsInvested,
} from './enhancement-costs'
import type { WorkshopEnhancementDiscounts } from './enhancement-costs'
import {
  labCoinCostToReachLevel,
  labDurationDaysToReachLevel,
  labMaxCatalogLevel,
} from './lab-costs'
import type { LabCostModifiers } from './lab-costs'
import {
  appendSkipExclusions,
  assertPathVariant,
  type PathExclusion,
  type PathSkip,
  planPath,
} from './planner'
import type { PathStep, PathUpgrade } from './planner'

/** The paths the econ tabs publish. The time tab is priced two ways. */
export type EffectiveEconomyPlanVariant = 'time' | 'coin' | 'stone' | 'discount'

/**
 * Every variant this planner recognises, including the one it refuses.
 *
 * `discount` is in the list deliberately: it is a real path, planned by
 * {@link planEffectiveEconomyDiscountPath}, and it earns the message that says
 * so rather than being lumped in with a typo.
 */
export const ECONOMY_PLAN_VARIANTS: readonly EffectiveEconomyPlanVariant[] = [
  'time', 'coin', 'stone', 'discount',
]

/**
 * Why the discount path is planned elsewhere.
 *
 * The other three rank a candidate by what a level does to `effectiveEconomy`.
 * The discount tab does not: nothing on it moves coins per kill, so scoring it
 * that way gives every candidate a gain of exactly zero and a rank decided by
 * the tie-break. It has its own model and its own planner —
 * `planEffectiveEconomyDiscountPath` in `effective-paths-eecon-discount.ts`,
 * which ranks coins saved and takes the account totals that model needs.
 *
 * This one refuses rather than silently returning that table of zeroes.
 */
export const DISCOUNT_PATH_UNSUPPORTED
  = 'the discount path ranks coins saved rather than coins earned — call '
    + 'planEffectiveEconomyDiscountPath instead'

/** The two workshop enhancements the time path buys rather than labs. */
const ENHANCEMENT_STATS: Readonly<Record<string, string>> = {
  'Coin Bonus': 'Coin Bonus',
  'Free Upgrades': 'Free Upgrades',
}

/** The two module levels it buys. */
const MODULE_CANDIDATES = new Set(['Primary Module - Generator', 'Assist Module - Generator'])

/**
 * The four time-path candidates that cost coins rather than research time.
 *
 * `eEcon!EO2`, `EP2`, `EQ2` and `ER2` — the hide rows for these four and no
 * others — each carry `NOT(O$3<>"DO")`, so all four leave the path when the
 * tab is counting days only. They are the only candidates in the list with no
 * research duration at all, which is why they are the only ones that clause
 * names: on a days-only ranking a purchase that takes no research time is free,
 * and free wins every step forever.
 */
const COIN_PRICED_TIME_CANDIDATES: ReadonlySet<string> = new Set([
  ...Object.keys(ENHANCEMENT_STATS),
  ...MODULE_CANDIDATES,
])

/**
 * `eEcon!E6`'s divisor, beside the coins-per-hour rate.
 *
 * Not hours in a day — the sheet prices a day of farming at 23 hours of it, and
 * the literal is `CpH * 23`. Kept as the sheet's number rather than 24, because
 * agreeing with it matters more than the rounding being explicable.
 */
const FARM_HOURS_PER_DAY = 23

/**
 * The rate the sheet ships, from `IDS_PS_PLAYERDATA("Coin / Hour")`.
 *
 * It is a real default rather than a placeholder — the tab renders a warning
 * beside it telling the player to replace it with their own figure — so a
 * caller that supplies nothing gets the same path the sheet would show.
 */
export const SHEET_DEFAULT_COINS_PER_HOUR = 100_000

/** Which ultimate weapon stat each stone candidate buys. */
const STONE_WEAPON_STATS: Readonly<Record<string, { weapon: string, stat: string }>> = {
  'GT Bonus': { weapon: 'Golden Tower', stat: 'Multiplier' },
  'GT Duration': { weapon: 'Golden Tower', stat: 'Duration' },
  'GT Cooldown': { weapon: 'Golden Tower', stat: 'Cooldown' },
  'GT Golden Combo': { weapon: 'Golden Tower', stat: 'Golden Combo' },
  'BH Duration': { weapon: 'Black Hole', stat: 'Duration' },
  'BH Cooldown': { weapon: 'Black Hole', stat: 'Cooldown' },
  'DW Quantity': { weapon: 'Death Wave', stat: 'Quantity' },
  'DW Cooldown': { weapon: 'Death Wave', stat: 'Cooldown' },
  'SL Angle': { weapon: 'Spotlight', stat: 'Angle' },
  'SL Quantity': { weapon: 'Spotlight', stat: 'Quantity' },
}

/**
 * Candidates the sheet hides when the weapon behind them is not owned.
 *
 * Read off `eEcon!DV2:DZ2`, the time band's hide row: the Golden Tower
 * candidates open with `NOT(BK15)`, and `BK15` is `IDS_UW_OWN("Golden Tower")`.
 *
 * Without this the planner does not *mis-price* them — a locked weapon
 * contributes nothing, so their gain is zero — but a zero-gain candidate still
 * fills the path in tie-break order, which is how an account owning no ultimate
 * weapons was being told to buy Golden Tower Bonus twenty-five times. Excluding
 * them leaves an empty path, which is the honest answer.
 */
const WEAPON_GATED_CANDIDATES: Readonly<Record<string, keyof EffectiveEconomyConfig['weapons']>> = {
  'Golden Tower Bonus': 'goldenTower',
  'Golden Tower Duration': 'goldenTower',
  'Black Hole Coin Bonus': 'blackHole',
  'Death Wave Coin Bonus': 'deathWave',
  'Spotlight Coin Bonus': 'spotlight',
  // Sheet name carries the hyphen; a typo here left Gold Bot ungated.
  'Gold Bot - Duration': 'goldBot',
}

/**
 * Time/coin candidates the sheet hides until a prerequisite is met.
 *
 * Read off `eEcon!DV2:ER2`. Same shape as the damage tab's lab prerequisites:
 * unmet, their gain is ~0 and a zero still fills the path in tie-break order.
 */
const TIME_PATH_PREREQUISITES: Readonly<
  Record<string, (config: EffectiveEconomyConfig) => boolean>
> = {
  // `AO7+AS7=0` — Galaxy Compressor unique (primary + assist).
  'Recovery Package Chance': config => {
    const u = config.uniques.galaxyCompressor
    return u.primary + u.assist !== 0
  },
  // `AO6+AS6=0` on the Free Upgrades enhancement column.
  'Free Upgrades': config => {
    const u = config.uniques.blackHoleDigestor
    return u.primary + u.assist !== 0
  },
  // `NOT(AZ32)` — card equipped and mastery unlocked (`AND(AZ31, IDS_CARD_MASTERY)`).
  'Coins Mastery': config =>
    Boolean(config.cards.coins.active && config.cards.coinsMastery.active),
  // `AZ34` uses LEFT(AU34,9)="Extra Orb" plus cards-on and mastery.
  'Extra Orb Mastery': config => Boolean(config.cards.extraOrbMastery.active),
  'Wave Skip Mastery': config =>
    Boolean(config.cards.waveSkip.active && config.cards.waveSkipMastery.active),
  'Intro Sprint Mastery': config =>
    Boolean(config.cards.introSprint.active && config.cards.introSprintMastery.active),
  'Wave Accelerator Mastery': config => Boolean(config.cards.waveAcceleratorMastery.active),
  // `NOT(AZ43)` or `NOT(OR(AZ45, AZ46))` — perks on, and Coins or Free Ups taken.
  'Standard Perks Bonus': config =>
    config.perksEquipped && (config.perks.coins || config.perks.freeUpgrades),
  // `NOT(AND(AZ43, AZ47))` — perks on and the coin trade-off taken.
  'Improve Trade-off Perks': config =>
    config.perksEquipped && config.perks.coinsTradeOff,
}

/**
 * Assist-efficiency candidates that need an assist module in the slot (`AP5` /
 * `AP14` on both the time and stone tabs).
 */
const ASSIST_SLOT_GATES: Readonly<
  Record<string, (config: EffectiveEconomyConfig) => boolean>
> = {
  'Assist Module Bonus - Generator': config => config.generator.hasAssist,
  'Assist Module Substats - Generator': config => config.generator.hasAssist,
  'Assist Module - Generator': config => config.generator.hasAssist,
  'Assist Module Substats - Core': config => config.generator.coreHasAssist,
}

/**
 * Golden Combo needs more than eight ultimate weapons unlocked.
 *
 * `eEcon Stones!DP2` hides it on
 * `COUNTIF('_IDS'!$AA$2:$AA$37, "UW Unlocked") <= 8`. The stone cost table
 * still prices it, so nothing else stops the planner recommending a stat the
 * player has no way to buy.
 */
const GOLDEN_COMBO_MINIMUM_WEAPONS = 9

/**
 * Stone candidates that need their coin-bonus lab started first.
 *
 * Read off `eEcon Stones!DM2:EQ2`:
 * - `DQ2` / `DR2` hide BH Duration and BH Cooldown on `BE20=0`
 * - `DT2` / `DU2` hide SL Angle and SL Quantity on `BE21=0`
 *
 * `BE20` / `BE21` are `IDS_LAB_LEVEL` of Black Hole Coin Bonus and Spotlight
 * Coin Bonus on the mirrored lab block (`eEcon!BD20` / `BD21`). Duration and
 * angle stones do nothing for the econ model until those labs contribute, and
 * a zero-gain candidate still fills the path in tie-break order.
 */
const STONE_COIN_LAB_GATES: Readonly<Record<string, keyof EffectiveEconomyLevels['time']>> = {
  'BH Duration': 'blackHoleCoinBonus',
  'BH Cooldown': 'blackHoleCoinBonus',
  'SL Angle': 'spotlightCoinBonus',
  'SL Quantity': 'spotlightCoinBonus',
}

/** Human names for {@link STONE_COIN_LAB_GATES} exclusion reasons. */
const STONE_COIN_LAB_LABELS: Readonly<Record<string, string>> = {
  blackHoleCoinBonus: 'Black Hole Coin Bonus',
  spotlightCoinBonus: 'Spotlight Coin Bonus',
}

/** The three cooldowns `AZ17`, "Keep GT|BH|DW CD Synced", takes off the path. */
const SYNCED_COOLDOWN_CANDIDATES = new Set(['GT Cooldown', 'BH Cooldown', 'DW Cooldown'])

/** The weapon each stone candidate's name refers to, in the config's spelling. */
const WEAPON_KEYS: Readonly<Record<string, keyof EffectiveEconomyConfig['weapons']>> = {
  'Golden Tower': 'goldenTower',
  'Black Hole': 'blackHole',
  'Death Wave': 'deathWave',
  'Spotlight': 'spotlight',
}

/** The stone path's assist capacities, and which ladder each climbs. */
const STONE_ASSIST_KINDS: Readonly<Record<string, 'multiplier' | 'substat'>> = {
  'Assist Module Bonus - Generator': 'multiplier',
  'Assist Module Substats - Generator': 'substat',
  'Assist Module Substats - Core': 'substat',
}

/**
 * Card masteries the stone tab used to leave unpriced.
 *
 * All five now have sheet stone costs ({@link STONE_MASTERY_COSTS}) and score
 * through the econ model. Kept as an empty set so a future AX-only mastery
 * can land here without reinventing the exclusion branch.
 */
const STONE_MASTERY_UNPORTED = new Set<string>()

/**
 * `UW CD` — cooldown levels bought together while Keep CD Synced is on.
 *
 * `eEcon Stones!DW5` advances every unlocked GT/BH/DW Cooldown that sits at
 * `CA5` (the longest chart cooldown) and prices the step as the sum. Hide row
 * `DW2` is `OR(NOT(AZ17), CA5<110)`. See {@link applyUwCdPurchases}.
 */
const STONE_COMPOSITE = 'UW CD'

/** Planner id for the composite — `stone:stone.ultimateWeaponCooldownStone`. */
function isUwCdUpgrade(upgrade: EffectiveEconomyUpgrade): boolean {
  return upgrade.sheetName === STONE_COMPOSITE
}

/** One candidate, resolved to the level it moves. */
export interface EffectiveEconomyUpgrade {
  id: string
  band: keyof EffectiveEconomyLevels
  key: string
  sheetName: string
  column: string
  variants: readonly EffectiveEconomyPlanVariant[]
}

const TIME_VARIANTS: readonly EffectiveEconomyPlanVariant[] = ['time', 'coin']

export const EFFECTIVE_ECONOMY_UPGRADES: readonly EffectiveEconomyUpgrade[] = [
  ...EFFECTIVE_ECONOMY_CANDIDATES_BY_PATH.time.map((candidate, index) => ({
    id: `time.${ECONOMY_TIME_LEVEL_KEYS[index]}`,
    band: 'time' as const,
    key: ECONOMY_TIME_LEVEL_KEYS[index] as string,
    sheetName: candidate.sheetName,
    column: candidate.column,
    variants: TIME_VARIANTS,
  })),
  ...EFFECTIVE_ECONOMY_CANDIDATES_BY_PATH.stone.map((candidate, index) => {
    const ref = ECONOMY_STONE_LEVEL_REFS[index]
    return {
      id: `stone:${ref.band}.${ref.key}`,
      band: ref.band,
      key: ref.key,
      sheetName: candidate.sheetName,
      column: candidate.column,
      variants: ['stone'] as const,
    }
  }),
  ...EFFECTIVE_ECONOMY_CANDIDATES_BY_PATH.discount.map((candidate, index) => ({
    id: `discount.${ECONOMY_DISCOUNT_LEVEL_KEYS[index]}`,
    band: 'discount' as const,
    key: ECONOMY_DISCOUNT_LEVEL_KEYS[index] as string,
    sheetName: candidate.sheetName,
    column: candidate.column,
    variants: ['discount'] as const,
  })),
]

export interface EffectiveEconomyPlanOptions {
  config: EffectiveEconomyConfig
  levels: EffectiveEconomyLevels
  variant: EffectiveEconomyPlanVariant
  steps?: number
  maxLevels?: Readonly<Record<string, number>>
  targetLevels?: Readonly<Record<string, number>>
  excludeIds?: readonly string[]
  /**
   * Why a given `excludeIds` entry was left out, by id.
   *
   * `excludeIds` is one flat set fed from several places -- a lab the account
   * has not unlocked, and the sheet's display toggles -- and the reason it was
   * reported with was hard-coded to "not unlocked yet" for all of them. So
   * turning on "Hide UW Cooldown" told a player `DW Cooldown - not unlocked
   * yet` about a stat they had MAXED, which is a false statement about their
   * own account and sends them to the wrong screen to fix it.
   *
   * Callers that know the cause supply it here; anything unlabelled keeps the
   * old wording.
   */
  excludeReasons?: Readonly<Record<string, string>>
  /**
   * Every candidate the greedy loop prices, at every step — so a parity test
   * can compare against the sheet's `DV5:ES5` band candidate by candidate
   * rather than only noticing that step N differs.
   */
  onCandidateRoi?: (entry: {
    step: number
    id: string
    name: string
    nextLevel: number
    roi: number
    gain: number
    price: number
  }) => void
  /**
   * Whether an upgrade is on the board AT THIS STEP.
   *
   * The sheet re-evaluates each candidate column's gate on every ROW, so an
   * upgrade can be offered at step 1 and withdrawn later. `excludeIds` is the
   * right tool for one the currency cannot buy at all; this is for the ones
   * that come and go. See `PathPlanOptions.available`.
   */
  available?: (step: number, id: string) => boolean
  labModifiers?: LabCostModifiers
  moduleDiscountPercent?: number
  enhancementDiscounts?: WorkshopEnhancementDiscounts
  /**
   * `eEcon!AZ17` — "Keep GT|BH|DW CD Synced".
   *
   * Hides the three individual cooldown candidates (`DO2` / `DR2` / `DT2`) and
   * reveals `UW CD` (`DW2`) while the longest chart cooldown is still ≥ 110s.
   * The composite is planned through {@link applyUwCdPurchases}.
   */
  keepCooldownsSynced?: boolean
  /**
   * `eEcon!O3` — count research days only, rather than days plus farm time.
   *
   * The tab's cost mode, spelled `DO` against `D+FT` on the sheet, and read by
   * the hide rows of the four candidates that cost coins and no research time:
   * `NOT(O$3<>"DO")` drops all four when it is `DO`.
   *
   * Off is `D+FT`, where every candidate also carries the time to farm its
   * coins — see {@link costOf}. That is what the sheet ships, so an absent
   * value behaves as `D+FT` does.
   */
  daysOnly?: boolean
  /**
   * `IDS_PS_PLAYERDATA("Coin / Hour")` — coins the player farms in an hour.
   *
   * Turns a coin cost into days, at `cost / (rate * 23)`. Only read when
   * {@link daysOnly} is off, and defaults to
   * {@link SHEET_DEFAULT_COINS_PER_HOUR}, which is the sheet's own default.
   */
  coinsPerHour?: number
  /**
   * Whether the Workshop Enhancements lab is bought — `'Master Sheet'!$F$5`.
   * The coin path buys two enhancements and neither exists without it.
   */
  workshopEnhancementsUnlocked?: boolean
  /**
   * Workshop enhancement levels, keyed by display name or `WSP_*`
   * code. Used for `eEcon!EO2` / `EP2` — Coin Bonus and Free Upgrades stay
   * hidden until Utility enhancement spend clears their thresholds (see
   * {@link UTILITY_ENHANCEMENT_SPEND_UNLOCKS}).
   */
  enhancementLevels?: Readonly<Record<string, number>>
}

export interface EffectiveEconomyPlan {
  steps: PathStep[]
  /** Coins per kill before any of it. */
  startingEffectiveEconomy: number
  finalEffectiveEconomy: number
  excluded: PathExclusion[]
  /**
   * What made the levels unusable, when they were. Empty on every plan that
   * ran — the same contract the damage plan already kept.
   */
  issues: EffectiveLevelsIssue[]
}

/** The highest level a candidate can reach, or `null` when nothing prices one. */
function resolveMaxLevel(
  upgrade: EffectiveEconomyUpgrade,
  options: EffectiveEconomyPlanOptions,
): number | null {
  if (isUwCdUpgrade(upgrade)) {
    if (!options.keepCooldownsSynced) return null
    return uwCdRemainingPurchases(options.config, options.levels.stone)
  }
  if (STONE_MASTERY_UNPORTED.has(upgrade.sheetName) && upgrade.variants[0] === 'stone') {
    return null
  }
  if (STONE_MASTERY_NAMES.has(upgrade.sheetName) && upgrade.variants[0] === 'stone') {
    return STONE_MASTERY_MAX_LEVEL
  }

  const weaponStat = STONE_WEAPON_STATS[upgrade.sheetName]
  if (weaponStat) return ultimateWeaponMaxLevel(weaponStat.weapon, weaponStat.stat)

  const assist = STONE_ASSIST_KINDS[upgrade.sheetName]
  if (assist && upgrade.variants[0] === 'stone') return maxStoneLevel(assist)

  if (MODULE_CANDIDATES.has(upgrade.sheetName)) return MODULE_COIN_PATH_MAX_LEVEL

  const enhancement = ENHANCEMENT_STATS[upgrade.sheetName]
  if (enhancement) return enhancementMaxLevel(enhancement)

  const max = labMaxCatalogLevel(upgrade.sheetName)
  return max > 0 ? max : null
}

/**
 * What it costs to take a candidate to `nextLevel`, in the path's currency.
 *
 * ## The time path spends two things at once
 *
 * A lab costs research time *and* coins, and four of the 23 candidates — the
 * two workshop enhancements and the two Generator module levels — cost only
 * coins. Ranking those against research days needs the two put in one unit,
 * and the sheet does it by asking how long farming the coins takes:
 *
 * ```text
 * eEcon!E6 = IF(AND(O3<>"DO", NOT(ISBLANK(CpH))),
 *              <that level's coin cost> / (UNFORMAT_NUMBER(CpH) * 23), )
 * eEcon!O6 = SCAN over MAP(Duration, FarmTime, (d, c) => d + c)
 * ```
 *
 * So a step's cost is its research duration plus its farm time, and `O3`
 * chooses whether the second half counts: `D+FT` for days plus farm time, `DO`
 * for days only. Under `DO` the four coin-only candidates leave the path
 * entirely — they would otherwise cost nothing at all, and nothing beats free.
 *
 * The `23` is the sheet's own literal, not hours in a day: it prices a day of
 * farming at 23 hours of it. Both halves come out in days, which is what
 * `ROI / Day` ranks by.
 */
function costOf(
  upgrade: EffectiveEconomyUpgrade,
  nextLevel: number,
  variant: EffectiveEconomyPlanVariant,
  options: EffectiveEconomyPlanOptions,
): number | null {
  if (variant === 'stone') {
    if (isUwCdUpgrade(upgrade)) {
      // Cost of the Nth composite purchase from the player's starting CDs.
      const prior = applyUwCdPurchases(options.config, options.levels.stone, nextLevel - 1)
      return uwCdStoneCost(options.config, prior)
    }
    const weaponStat = STONE_WEAPON_STATS[upgrade.sheetName]
    if (weaponStat) {
      return ultimateWeaponStoneCost(weaponStat.weapon, weaponStat.stat, nextLevel)
    }
    const masteryCost = STONE_MASTERY_COSTS[upgrade.sheetName]
    if (masteryCost !== undefined) return masteryCost
    const assist = STONE_ASSIST_KINDS[upgrade.sheetName]
    return assist ? assistEfficiencyStoneCost(assist, nextLevel) : null
  }

  const coins = coinCostOf(upgrade, nextLevel, options)

  if (variant === 'coin') return coins

  /*
   * The time path, in days.
   *
   * A lab contributes its research duration; the four coin-only candidates have
   * none, which is exactly why they leave the path under days-only rather than
   * ranking as free. Every candidate then contributes the time to farm its
   * coins. Both halves are days, which is what `ROI / Day` ranks by.
   */
  const research = COIN_PRICED_TIME_CANDIDATES.has(upgrade.sheetName)
    ? 0
    : labDurationDaysToReachLevel(upgrade.sheetName, nextLevel, options.labModifiers)

  // A duration the catalog cannot supply still drops the candidate, as before:
  // a lab with no known duration is not a lab that takes no time.
  if (research === null) return null
  if (options.daysOnly) return research

  return coins === null ? research : research + farmDays(coins, options)
}

/** What a candidate's next level costs in coins, whatever the path. */
function coinCostOf(
  upgrade: EffectiveEconomyUpgrade,
  nextLevel: number,
  options: EffectiveEconomyPlanOptions,
): number | null {
  if (MODULE_CANDIDATES.has(upgrade.sheetName)) {
    // The table is keyed by the level being left, not the one bought.
    return moduleUpgradeCoinCost(nextLevel - 1, {
      discountLabLevel: options.moduleDiscountPercent,
    })
  }

  const enhancement = ENHANCEMENT_STATS[upgrade.sheetName]
  if (enhancement) {
    return enhancementCoinCost(enhancement, nextLevel, options.enhancementDiscounts)
  }

  return labCoinCostToReachLevel(upgrade.sheetName, nextLevel, options.labModifiers)
}

/**
 * `eEcon!E6` — how long farming a coin cost takes, in days.
 *
 * ```text
 * =IF(AND(O3<>"DO", NOT(ISBLANK(CpH))),
 *      <that level's coin cost> / (UNFORMAT_NUMBER(CpH) * 23), )
 * ```
 *
 * The `23` is the sheet's own literal and is not hours in a day: it prices a
 * day of farming at 23 hours of it.
 *
 * Exported so it can be checked against the cell it comes from. Left as a
 * private helper it was only ever reachable through a planned step, and a test
 * that reproduces `cost / (rate * 23)` to check `cost / (rate * 23)` passes
 * whatever the constant says — which is how a `24` survived a green suite here.
 */
export function coinFarmDays(coins: number, coinsPerHour = SHEET_DEFAULT_COINS_PER_HOUR): number {
  if (!(coinsPerHour > 0) || !Number.isFinite(coins)) return 0
  /*
   * Never negative. A fully discounted cost can come back at or below zero, and
   * farm time is added to a research duration — so a negative would pay the
   * player back time and could drag a step's cost to zero, where the planner
   * skips it silently for having no price at all.
   */
  return Math.max(0, coins) / (coinsPerHour * FARM_HOURS_PER_DAY)
}

function farmDays(coins: number, options: EffectiveEconomyPlanOptions): number {
  return coinFarmDays(coins, options.coinsPerHour ?? SHEET_DEFAULT_COINS_PER_HOUR)
}

/** A candidate's current level. */
function levelOf(levels: EffectiveEconomyLevels, upgrade: EffectiveEconomyUpgrade): number {
  return (levels[upgrade.band] as unknown as Record<string, number>)[upgrade.key] ?? 0
}

/** The player's levels with a step's purchases applied. */
function withLevels(
  levels: EffectiveEconomyLevels,
  current: ReadonlyMap<string, number>,
  config: EffectiveEconomyConfig,
): EffectiveEconomyLevels {
  const next: EffectiveEconomyLevels = {
    time: { ...levels.time },
    stone: { ...levels.stone },
    discount: { ...levels.discount },
  }
  let uwCdPurchases: number | null = null
  for (const [id, level] of current) {
    const upgrade = EFFECTIVE_ECONOMY_UPGRADES.find(entry => entry.id === id)
    if (!upgrade) continue
    if (isUwCdUpgrade(upgrade)) {
      uwCdPurchases = level
      continue
    }
    (next[upgrade.band] as unknown as Record<string, number>)[upgrade.key] = level
  }
  if (uwCdPurchases !== null) {
    // Composite purchases rewrite the three CD stone levels from the starting
    // account — individual CD candidates are off the path while sync is on.
    const applied = applyUwCdPurchases(config, {
      ...next.stone,
      goldenTowerCooldownStone: levels.stone.goldenTowerCooldownStone,
      blackHoleCooldownStone: levels.stone.blackHoleCooldownStone,
      deathWaveCooldownStone: levels.stone.deathWaveCooldownStone,
    }, uwCdPurchases)
    next.stone = { ...applied, ultimateWeaponCooldownStone: uwCdPurchases }
  }
  return next
}

/**
 * Plan an eEcon path.
 *
 * Candidates keep their matrix order, because the planner breaks a tie by
 * taking the earliest — which is the sheet taking the leftmost column.
 */
/**
 * The candidates the sheet prices with a different cooldown guard.
 *
 * Keyed on the CANDIDATE, so the quirk cannot reach the baseline or any other
 * upgrade -- `evaluate` is called with no candidate for the baseline, which
 * gives the sheet's `Old`, and with one for the candidate, which gives `New`.
 * The eDamage planner learned this the hard way: keying on a level delta left
 * an override switched on for the rest of the path and repriced the board.
 *
 * See {@link EffectiveEconomyShadow.candidateCooldownGuardUsesGoldenTower}.
 */
const GOLDEN_TOWER_GUARD_CANDIDATES = new Set([
  'Recovery Package Chance',
  'Assist Module Substats - Generator',
  /*
   * The three STONE cooldown candidates, which were missing.
   *
   * Enumerated by reading all nineteen `eEcon Stones` candidate formulas and
   * asking which compare Black Hole's and Death Wave's duration against
   * GOLDEN TOWER's cooldown rather than their own -- `CV5>=GTcd1*CO5` and
   * `CY5>=GTcd1*CO5`. Exactly three do: GT Cooldown, BH Cooldown, DW Cooldown.
   * The other sixteen keep each weapon's own threshold.
   *
   * This is why the port ranked DW Cooldown 30x below DW Quantity while the
   * sheet ranked it ABOVE. A shorter cooldown lifts uptime AND the overlap
   * between weapons, and weapons firing together are worth more than the sum
   * of them firing apart -- which is the whole reason the sheet ranks cooldown
   * so high, and it is invisible unless the candidate rebuilds the sync.
   *
   * Two explanations were tried and killed before this, and are recorded so
   * they are not tried again. NOT a floored cooldown: `syncMultiplier` does
   * `Math.floor(cycle.cooldown)`, which looked like it would swallow small
   * reductions, but a bump moves DW cooldown 286.9 -> 277.3 and the floor
   * moves with it. And NOT a sync that fails to respond: it goes 1.228040 ->
   * 1.228509 on account-1, exactly the 3.8e-4 measured, and DOWN 6% on
   * account-2 -- overlap is not monotonic in cooldown, which is real.
   */
  'GT Cooldown',
  'BH Cooldown',
  'DW Cooldown',
])

function shadowFor(candidate: { name: string } | undefined): EffectiveEconomyShadow {
  if (candidate === undefined) return {}

  /*
   * `eEcon!EF5` computes its free-upgrade term with `$AZ$35`/`$AW$35`, the Wave
   * Skip card, where the base column uses `$AZ$33`/`$AW$33`, Free Upgrades.
   * Enumerated by `candidate-vs-base-diff.mjs`, not found by chasing a sweep.
   */
  if (candidate.name === 'Wave Skip Mastery') {
    return { freeUpgradeCardFromWaveSkip: true }
  }

  if (candidate.name === 'Intro Sprint Mastery'
    || candidate.name === 'Wave Accelerator Mastery') {
    return { waveSkipDroppedByCandidateGate: true }
  }
  return GOLDEN_TOWER_GUARD_CANDIDATES.has(candidate.name)
    ? { candidateCooldownGuardUsesGoldenTower: true }
    : {}
}

export function planEffectiveEconomyPath(
  options: EffectiveEconomyPlanOptions,
): EffectiveEconomyPlan {
  const { config, levels, variant } = options
  // Order matters: a real path routed to the wrong planner deserves the message
  // that names the right one, not "unknown variant".
  assertPathVariant(variant, ECONOMY_PLAN_VARIANTS, 'eEcon')
  if (variant === 'discount') throw new Error(DISCOUNT_PATH_UNSUPPORTED)

  const steps = options.steps ?? 145
  const skipped = new Set(options.excludeIds ?? [])

  // Once here rather than inside `evaluate`, which runs thousands of times
  // over inputs that do not change between the calls.
  const check = checkEffectiveEconomyLevels(levels)
  if (!check.ok) {
    return {
      steps: [],
      startingEffectiveEconomy: 0,
      finalEffectiveEconomy: 0,
      excluded: [],
      issues: check.issues,
    }
  }

  const upgrades: PathUpgrade[] = []
  const excluded: EffectiveEconomyPlan['excluded'] = []
  const byId = new Map(EFFECTIVE_ECONOMY_UPGRADES.map(upgrade => [upgrade.id, upgrade]))
  const utilityEnhancementSpend = workshopEnhancementCoinsInvested(
    'utility',
    options.enhancementLevels ?? {},
  )

  for (const upgrade of EFFECTIVE_ECONOMY_UPGRADES) {
    if (!upgrade.variants.includes(variant)) continue

    if (skipped.has(upgrade.id)) {
      excluded.push({
        sheetName: upgrade.sheetName,
        reason: options.excludeReasons?.[upgrade.id] ?? 'not unlocked yet',
      })
      continue
    }

    if (upgrade.sheetName === STONE_COMPOSITE) {
      if (!options.keepCooldownsSynced) {
        excluded.push({
          sheetName: upgrade.sheetName,
          reason: 'the path is ranking cooldowns individually',
        })
        continue
      }
      if (!isUwCdCandidateVisible(config, levels.stone, true)) {
        excluded.push({
          sheetName: upgrade.sheetName,
          reason: 'longest cooldown is under 110 seconds',
        })
        continue
      }
    }

    if (options.daysOnly && COIN_PRICED_TIME_CANDIDATES.has(upgrade.sheetName)) {
      excluded.push({
        sheetName: upgrade.sheetName,
        reason: 'costs coins rather than research time, and the path is counting days only',
      })
      continue
    }

    if (variant === 'stone' && STONE_MASTERY_UNPORTED.has(upgrade.sheetName)) {
      excluded.push({
        sheetName: upgrade.sheetName,
        reason: 'the sheet ranks it from an unported mastery-return formula rather than a stone price',
      })
      continue
    }

    if (variant === 'stone' && STONE_MASTERY_NAMES.has(upgrade.sheetName)
      && isStoneMasteryOwned(upgrade.sheetName, config)) {
      excluded.push({
        sheetName: upgrade.sheetName,
        reason: 'the card mastery is already unlocked',
      })
      continue
    }

    /*
     * NO card-equipped gate on the stone masteries. There were three, for
     * Coins, Wave Skip and Intro Sprint, on the reasoning that "without the
     * card the unlock does nothing, and a zero-gain candidate still fills the
     * path".
     *
     * The sheet does not agree, and it is unambiguous about it.
     * `eEcon Stones!EA2` through `EE2` are identical:
     *
     *   =OR(IDS_CARD_MASTERY(LEFT(EA4, LEN(EA4)-8)),
     *       AND($AZ$11, NOT(IDS_LAB_HAS_UNLOCKED(EA4))))
     *
     * Already unlocked, or hide-non-unlocked-labs with the lab unresearched.
     * The equipped toggle appears nowhere. And the premise was wrong on its own
     * terms: on the generated sweep the sheet ranks Coins Mastery at ROI
     * 2.4e-05, which is not zero.
     */

    // The weapon behind a candidate has to be owned. The stone band buys
    // weapon stats outright, so its gate is the weapon it names; the time band
    // names five coin-bonus labs that need theirs.
    const gatedWeapon = STONE_WEAPON_STATS[upgrade.sheetName]
      ? WEAPON_KEYS[STONE_WEAPON_STATS[upgrade.sheetName].weapon]
      : WEAPON_GATED_CANDIDATES[upgrade.sheetName]
    if (gatedWeapon && !config.weapons[gatedWeapon]?.unlocked) {
      excluded.push({ sheetName: upgrade.sheetName, reason: 'the weapon is not unlocked' })
      continue
    }

    // Time/coin hide-row prerequisites — assist slots, unique modules, mastery
    // labs that need the unlock first, and perk labs.
    if (variant === 'time' || variant === 'coin') {
      const ready = TIME_PATH_PREREQUISITES[upgrade.sheetName]
      if (ready && !ready(config)) {
        excluded.push({
          sheetName: upgrade.sheetName,
          reason: 'its prerequisite is not met',
        })
        continue
      }
    }

    const assistReady = ASSIST_SLOT_GATES[upgrade.sheetName]
    if (assistReady && !assistReady(config)) {
      excluded.push({
        sheetName: upgrade.sheetName,
        reason: 'no assist module is equipped in that slot',
      })
      continue
    }

    // `eEcon Stones!DQ2` / `DR2` / `DT2` / `DU2`: BH and SL stone stats stay
    // hidden until their coin-bonus lab is at least level 1 (`BE20` / `BE21`).
    if (variant === 'stone') {
      const coinLabKey = STONE_COIN_LAB_GATES[upgrade.sheetName]
      if (coinLabKey && levels.time[coinLabKey] <= 0) {
        const labLabel = STONE_COIN_LAB_LABELS[coinLabKey] ?? coinLabKey
        excluded.push({
          sheetName: upgrade.sheetName,
          reason: `the ${labLabel} lab is not started yet`,
        })
        continue
      }
    }

    if (options.workshopEnhancementsUnlocked === false
      && ENHANCEMENT_STATS[upgrade.sheetName]) {
      excluded.push({
        sheetName: upgrade.sheetName,
        reason: 'the Workshop Enhancements lab is not bought yet',
      })
      continue
    }

    // `eEcon!EO2` / `EP2`: hide while utility spend is still at or below the
    // wiki unlock threshold (`WSPUTILITY_TOTAL_COINS_INVESTED(...)<=N`).
    const utilityUnlockAt = UTILITY_ENHANCEMENT_SPEND_UNLOCKS[upgrade.sheetName]
    if (utilityUnlockAt !== undefined && utilityEnhancementSpend <= utilityUnlockAt) {
      excluded.push({
        sheetName: upgrade.sheetName,
        reason: `locked until more than ${utilityUnlockAt} coins are spent on Utility enhancements`,
      })
      continue
    }

    if (upgrade.sheetName === 'GT Golden Combo'
      && config.unlockedUltimateWeaponCount < GOLDEN_COMBO_MINIMUM_WEAPONS) {
      excluded.push({
        sheetName: upgrade.sheetName,
        reason: `needs ${GOLDEN_COMBO_MINIMUM_WEAPONS} ultimate weapons unlocked`,
      })
      continue
    }

    if (options.keepCooldownsSynced && SYNCED_COOLDOWN_CANDIDATES.has(upgrade.sheetName)) {
      excluded.push({
        sheetName: upgrade.sheetName,
        reason: 'cooldowns are being kept synced, which buys them together',
      })
      continue
    }

    const level = isUwCdUpgrade(upgrade) ? 0 : levelOf(levels, upgrade)

    if (MODULE_CANDIDATES.has(upgrade.sheetName) && level < MODULE_COIN_PATH_MIN_LEVEL) {
      excluded.push({
        sheetName: upgrade.sheetName,
        reason: `below level ${MODULE_COIN_PATH_MIN_LEVEL}, where shards are cheaper`,
      })
      continue
    }

    const maxLevel = options.maxLevels?.[upgrade.id] ?? resolveMaxLevel(upgrade, options)
    if (maxLevel === null || maxLevel <= level) {
      excluded.push({
        sheetName: upgrade.sheetName,
        reason: maxLevel === null ? 'no maximum level known' : 'longest cooldown is under 110 seconds',
      })
      continue
    }

    upgrades.push({
      id: upgrade.id,
      name: upgrade.sheetName,
      level,
      maxLevel,
      targetLevel: options.targetLevels?.[upgrade.id],
    })
  }

  /**
   * The five stone masteries' returns, computed ONCE from the account's own
   * state rather than from wherever the path has got to.
   *
   * `eEcon Stones!EC5` is the whole Wave Skip Mastery candidate:
   *
   *   =IFS(OR(EC$2, $DL5), , TRUE, $AX$36)
   *
   * An ABSOLUTE reference to one cell, so every row of the ROI band carries
   * the same number and the value does not move as the path spends. `AX36`
   * itself is `(New/Old-1)/1000`, where `Old` is the account's current coins
   * and `New` is the coins with that mastery unlocked at
   * `RIGHT($AX$29, 1)` -- the "Compare Masteries at" level, NOT the account's
   * own mastery level.
   *
   * The planner used to rank these by raising the mastery lab one level from
   * wherever the account had it, which is a different quantity and a different
   * size: it printed `Wave Skip Mastery@4` where the sheet prints `lvl 0`, and
   * ranked all five against the stone candidates accordingly.
   */
  const stoneMasteryGains = new Map<string, number>()
  if (variant === 'stone') {
    /*
     * Each mastery's return, taken from `eEcon!AX32`..`AX40` verbatim.
     *
     * Two of the five are closed forms and do not touch the economy at all;
     * two compare a NAMED SUB-PRODUCT rather than effective economy; the fifth
     * has no formula on the sheet, so its ROI cell is blank and it ranks last.
     *
     *   AX32 Coins       `0.03*(1+RIGHT(AX29,1))/1250`
     *   AX34 Extra Orb   `$AZ$26*0.04*(1+RIGHT(AX29,1))/750`
     *   AX36 Wave Skip   `(New/Old-1)/1000`, Old = `CU5*DR5`
     *   AX38 Intro Spr.  `(New/Old-1)/1250`, Old = `DR5`
     *   AX41 Wave Accel. `(New/Old-1)/1000`, Old = `DR5`
     *
     * Scoring these on total effective economy — which is what this did first
     * — is a different quantity and came out about 5x the sheet's on Wave
     * Skip. `Old` is two columns multiplied together, not the answer.
     *
     * The cells are taken from the candidate columns `EA5`..`EE5`, each of
     * which is a bare `$AX$nn` reference, rather than by counting rows in the
     * label column beside them — that is how Wave Accelerator was first read
     * as `AX40`, which is empty.
     *
     * The denominators are already `STONE_MASTERY_COSTS`, so what is stored
     * here is the NUMERATOR: the planner divides by the cost itself.
     */
    const at = config.compareMasteriesAt ?? COMPARE_MASTERIES_AT_DEFAULT
    const idOf = (sheetName: string) => EFFECTIVE_ECONOMY_UPGRADES
      .find(u => u.sheetName === sheetName && u.variants[0] === 'stone')?.id

    const base = computeEffectiveEconomy(config, levels)
    /*
     * Two of them ADD the compare level to the mastery's own; one REPLACES it.
     *
     *   AX36 Wave Skip   `EPC_WS_FUP(13, 1, $AV$35, 1, RIGHT($AX$29,1))`
     *                    — the compare level IS the mastery level
     *   AX38 Intro Spr.  `100*1.8*(1+CB5+RIGHT(AX29,1))`
     *   AX41 Wave Accel. `1+10%*(1+CC5+RIGHT(AX29,1))`
     *                    — both add it to the level the account already has
     *
     * Treating all three as "replace" priced Wave Skip exactly and left Intro
     * Sprint 5x low and Wave Accelerator NEGATIVE, which is what a level going
     * DOWN looks like.
     */
    const ADDS_COMPARE_LEVEL = new Set(['Intro Sprint Mastery', 'Wave Accelerator Mastery'])
    const withMastery = (sheetName: string) => {
      const levelKey = STONE_MASTERY_LEVEL_KEY_BY_NAME[sheetName]
      const cardKey = STONE_MASTERY_CARD_KEY_BY_NAME[sheetName]
      if (!levelKey || !cardKey) return null
      const level = ADDS_COMPARE_LEVEL.has(sheetName) ? levels.time[levelKey] + at : at
      /*
       * The MASTERY card is switched on and the base card is left alone.
       *
       * `AX36` does pass a literal `1` for `has_card` into `EPC_WS_FUP` and
       * `EPC_WSM`, so forcing Wave Skip's own card on looked like a read of the
       * formula. It priced MORE accounts differently, not fewer — 5 of 22
       * against 3 — so whatever that literal stands for, it is not "pretend the
       * player equipped it". Reverted rather than kept for the one account
       * whose path it moved.
       */
      const cards = { ...config.cards, [cardKey]: { ...config.cards[cardKey], active: true } }
      return computeEffectiveEconomy(
        { ...config, cards },
        { ...levels, time: { ...levels.time, [levelKey]: level } },
      )
    }
    const ratio = (sheetName: string, of: (c: Readonly<Record<string, number>>) => number) => {
      const after = withMastery(sheetName)
      if (!after) return null
      const before = of(base.columns)
      if (!(before > 0)) return null
      return of(after.columns) / before - 1
    }

    const gains: Record<string, number | null> = {
      'Coins Mastery': 0.03 * (1 + at),
      'Extra Orb Mastery': config.estimates.extraOrbTagShare * 0.04 * (1 + at),
      'Wave Skip Mastery': ratio('Wave Skip Mastery', c => c.CU5 * c.DR5),
      'Intro Sprint Mastery': ratio('Intro Sprint Mastery', c => c.DR5),
      /*
       * `EE5` is `$AX$41`, NOT `$AX$40`. Reading the label column one row off
       * put this at an empty cell and scored the candidate at zero — on
       * account-2 its real return is 0.001122, the HIGHEST on the board at
       * step 8, which is exactly where the sheet buys it and the port did not.
       */
      'Wave Accelerator Mastery': ratio('Wave Accelerator Mastery', c => c.DR5),
    }
    for (const [sheetName, gain] of Object.entries(gains)) {
      const id = idOf(sheetName)
      if (id && gain !== null && Number.isFinite(gain)) stoneMasteryGains.set(id, gain)
    }
  }

  const skips: PathSkip[] = []
  const planned = planPath({
    upgrades,
    steps,
    evaluate: (current, candidate) => {
      const nextLevels = withLevels(levels, current, config)
      const scored = variant === 'stone'
        ? withStoneMasteriesActivated(config, levels, nextLevels)
        : config
      return computeEffectiveEconomy(scored, nextLevels, shadowFor(candidate)).effectiveEconomy
    },
    cost: (id, nextLevel, _current) => {
      const upgrade = byId.get(id)
      if (!upgrade) return Number.NaN
      return costOf(upgrade, nextLevel, variant, options) ?? Number.NaN
    },
    onSkip: skip => skips.push(skip),
    onCandidateRoi: options.onCandidateRoi,
    available: options.available,
    relativeGain: id => stoneMasteryGains.get(id) ?? null,
  })

  /*
   * Everything the loop passed over on the first step and that never made it
   * into the path, said out loud.
   *
   * Without this a candidate that is capped or unpriced appears nowhere at all
   * — not in the steps, not in `excluded` — so a path that stops after one step
   * offers no way to find out why. That is not hypothetical: a real account
   * planned a module level nine orders of magnitude worse per day than a lab
   * whose next level simply never appeared, and there was nothing to read. It
   * turned out every lab was at its cap, which the path can now say.
   */
  appendSkipExclusions(excluded, planned, skips)

  const startingEffectiveEconomy = computeEffectiveEconomy(config, levels).effectiveEconomy

  return {
    steps: planned,
    startingEffectiveEconomy,
    finalEffectiveEconomy: planned.length
      ? planned[planned.length - 1].value
      : startingEffectiveEconomy,
    excluded,
    issues: [],
  }
}
