/**
 * Build an eHP config and levels from a captured `eHP` row.
 *
 * eDamage and eEcon have had a cell reader since they were ported; eHP never
 * did, so its tests built config objects by hand and its only path fixture was
 * one account "from an all-zero starting state". Without a reader there is no
 * way to drive the port from a real captured account, and so no way to check a
 * component model against the sheet's own component row.
 *
 * Every cell below is named by the formula that reads it, not inferred from a
 * neighbour:
 *
 *   CJ5  EPH_HEALTH($BH$6, BO5, AND($AY$16,$AY$19), $AV$19, $AY$20, BZ5,
 *                   $BI$6, AND($AY$28,$AY$30), BU5, AND($AY$28,$AY$36),
 *                   AND($AY$28,$AY$37), $BL$6, $BM$6, $AM$25, BX5, CI5)
 *   CK5  EPH_ARMOR($AN$4, $AO$5, $AO$4, $BK$22, CD5)
 *   CL5  EPH_DABS($BH$8, BP5, AND($AY$16,$AY$25), $AV$25, $BK$23, CB5,
 *                 $AN$9, $AO$9, $BI$8, AND($AY$28,$AY$33), BU5, $BL$8, $BM$8) * $AY$11
 *   CM5  1/(1-EPH_DEF_PCT($BH$9, BQ5, AND($AY$16,$AY$23), $AV$23, $AY$24, CA5,
 *                         $BK$23, CB5, $AN$8, $AO$8, AND($AY$28,$AY$32), BU5, $BL$9, $BM$9))
 *   CN5  IF($AM$21, EPH_WALL_HEALTH($BH$10, BR5, $BK$23, CB5, $AN$10, $AO$10,
 *                                   $BI$10, $AN$6, $AR$6, BS5), "")
 *   CO5  IF($AM$23, EPH_MAX_RCVR($BH$13, BT5, $BK$25, CC5, $AN$13, $AO$13,
 *                                $BI$13, $BM$13), "")
 *   CP5  1/(1-IF(AND($AY$28,$AY$34), 0.5*(1+1%*BV5), 0))
 *   CQ5  1/(1-IF($AM$26, (10%+0.5%*BW5), 0))
 *   CR5  1/(1-IF($AM$24, MIN($AY$12/6*10, 3%*BY5), 0))
 *
 * Two conventions the sheet uses and a reader has to respect:
 *
 * - The workshop VALUE lives in `BH`, not the level. `BH6` is
 *   `DVT_WS_VALUE(BB6, BG6)`, already resolved, so the config takes
 *   `workshopValue` and never `workshopLevel` — looking the level up again
 *   would go through a second table and could disagree with the sheet's.
 * - A numeric control can be stored as TEXT. `cell()` therefore parses numeric
 *   strings; anything else reads 0. eEcon's `AX23` holds the string "1", and a
 *   `typeof === 'number'` reader turned the Gold Bot sync ratio into a zero
 *   that produced a plausible-looking cooldown for months.
 */
/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    SheetCells, effectiveHealthConfigFromSheet, effectiveHealthLevelsFromSheet, effectiveRegenConfigFromSheet
 * depends    src/mechanics/effective-paths/ehp-model, src/mechanics/effective-paths/regen-plan
 * used by    src/mechanics/calculators/specs-generated, src/mechanics/effective-paths/index
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */

import type {
  EffectiveHealthConfig,
  EffectiveHealthLevels,
} from './ehp-model'
import { zeroEffectiveHealthConfig } from './ehp-model'
import type { EffectiveRegenConfig } from './regen-plan'

/** Every level at zero, so a field this reader forgets is 0 rather than undefined. */
const ZERO_LEVELS: EffectiveHealthLevels = {
  health: 0, defenseAbsolute: 0, defensePercent: 0, wallHealth: 0,
  wallFortification: 0, recoveryPackageMax: 0, standardPerksBonus: 0,
  improveTradeOffPerks: 0, chronoFieldReduction: 0, deathWaveHealth: 0,
  chainThunder: 0, healthMastery: 0, extraDefenseMastery: 0,
  assistSubstatArmor: 0, assistSubstatGenerator: 0, assistBonusArmor: 0,
  assistSubstatArmorLab: 0, assistSubstatGeneratorLab: 0, assistBonusArmorLab: 0,
  dissonantEchoDefense: 0, primaryModuleArmor: 0, assistModuleArmor: 0,
  enhancementHealth: 0, enhancementDefenseAbsolute: 0,
  enhancementWallHealth: 0, enhancementRecoveryPackage: 0,
}

export type SheetCells = Record<string, unknown>

const reader = (cells: SheetCells) => ({
  /** A number, or a numeric string, or 0. Never `NaN`. */
  cell: (ref: string): number => {
    const raw = cells[ref]
    if (typeof raw === 'number') return Number.isFinite(raw) ? raw : 0
    if (typeof raw === 'string' && raw.trim() !== '') {
      const parsed = Number(raw)
      if (Number.isFinite(parsed)) return parsed
    }
    return 0
  },
  flag: (ref: string): boolean => cells[ref] === true,
})

/**
 * A stat as the sheet assembles one: a resolved workshop value, a relic and a
 * vault percentage, and the two module substats.
 *
 * The enhancement level is deliberately NOT here. `EffectiveHealthStatSource`
 * has no field for it because the coin path BUYS enhancements, so they are
 * levels rather than fixed player state -- `levels.enhancementHealth` and its
 * three siblings.
 */
function statSource(
  cells: SheetCells,
  workshopValueRef: string,
  relicRef: string,
  vaultRef: string,
  primarySubstatRef?: string,
  assistSubstatRef?: string,
) {
  const { cell } = reader(cells)
  return {
    workshopValue: cell(workshopValueRef),
    relicPct: cell(relicRef),
    vaultPct: cell(vaultRef),
    primarySubstat: primarySubstatRef ? cell(primarySubstatRef) : 0,
    assistSubstat: assistSubstatRef ? cell(assistSubstatRef) : 0,
  }
}

export function effectiveHealthConfigFromSheet(cells: SheetCells): EffectiveHealthConfig {
  const { cell, flag } = reader(cells)
  const zero = zeroEffectiveHealthConfig()

  /**
   * Cards and perks are each gated by their block's own master switch, exactly
   * as the sheet writes it: `AND($AY$16, $AY$19)`, `AND($AY$28, $AY$30)`.
   * Reading the row alone would count a card the run has switched off.
   */
  const card = (row: number) => flag('AY16') && flag(`AY${row}`)
  const perk = (row: number) => flag('AY28') && flag(`AY${row}`)

  return {
    ...zero,

    health: statSource(cells, 'BH6', 'BL6', 'BM6'),
    defenseAbsolute: statSource(cells, 'BH8', 'BL8', 'BM8', 'AN9', 'AO9'),
    defensePercent: statSource(cells, 'BH9', 'BL9', 'BM9', 'AN8', 'AO8'),
    wallHealth: statSource(cells, 'BH10', 'BL10', 'BM10', 'AN10', 'AO10'),
    maxRecovery: statSource(cells, 'BH13', 'BL13', 'BM13', 'AN13', 'AO13'),

    cards: {
      // Row 19 Health / 20 Health Mastery, 23 Extra Defense / 24 its mastery,
      // 25 Fortress -- the rows `CJ5`, `CM5` and `CL5` name.
      // `masteryEquipped` is the ROW alone, deliberately not `card(20)`. The
      // composition reads `AND($AY$16, $AY$20)`; candidacy reads `AY20` on its
      // own, per `eHP!DT2`.
      health: {
        has: card(19), value: cell('AV19'),
        hasMastery: card(20), masteryEquipped: flag('AY20'),
      },
      defensePercent: { has: card(23), value: cell('AV23'), hasMastery: card(24) },
      defenseAbsolute: { has: card(25), value: cell('AV25') },
    },

    /*
     * `EPH_ARMOR($AN$4, $AO$5, $AO$4, $BK$22, CD5)` reads
     * `(primaryBonus, hasAssist, assistBonus, cap, level)` -- so the SECOND
     * argument is the flag and the THIRD is the bonus, which is the reverse of
     * the order the cells sit in.
     *
     * Getting it the other way round is not a type error, because `AO5` holds a
     * boolean and `AO4` a number and both coerce: `hasAssist` came out true
     * from `AO4 !== 0`, the assist multiplier came out of a `false`, and armor
     * read 0.8096 against the sheet's 1.012 -- a flat 0.8, on all ten accounts,
     * looking exactly like a plausible armor value.
     */
    armor: {
      primaryBonus: cell('AN4'),
      hasAssist: flag('AO5'),
      assistBonus: cell('AO4'),
    },

    wall: {
      // `$AM$21` is the gate `CN5` itself branches on -- with it off the sheet
      // writes "" and the pool term becomes 1 rather than 0.
      has: flag('AM21'),
      primaryEffect: cell('AN6'),
      assistEffect: cell('AR6'),
    },

    recovery: { has: flag('AM23') },

    perks: {
      ...zero.perks,
      apply: flag('AY28'),
      health: perk(30),
      healthRegen: perk(31),
      extraDefense: perk(32),
      absoluteDefense: perk(33),
      enemyDamageTradeOff: perk(34),
      enemyHealthTradeOff: perk(35),
      coinTradeOff: perk(36),
      regenTradeOff: perk(37),
    },

    chronoField: { unlocked: flag('AM26') },
    chainThunder: { has: flag('AM24'), damageShare: cell('AY12') },
    deathWave: { hasHealth: flag('AM25') },

    enemiesAttackingTogether: cell('AY11'),

    /*
     * `CI5 = TTG_DISSONANT_ATTACK_BOOST($CH$6, $CH$7:$CH$27, CE5)`, the last
     * argument every component row passes to `EPH_HEALTH`.
     *
     * This was missing, and it is the whole of the Health defect the community
     * sheets found. `zeroEffectiveHealthConfig` leaves `dissonance.active`
     * false, so the boost was 1 on every account this reader has ever built --
     * and on a working copy with a blank `_IDS` there are no personal bests, so
     * the boost really IS 1 and eHP matched to 1e-9 across every generated
     * sweep. On a real account it is 1.18x to 7.72x, and the port was that much
     * low. Dividing the port's error by `Disco Defense` gives exactly 1.000000
     * on four of the five usable accounts.
     *
     * The model was never wrong. `dissonantBoostOfType` implements the
     * mechanic; nothing set its inputs, and nothing reported that.
     *
     * `active` is true whenever a personal best exists: the sheet has no switch
     * for it, it simply computes the boost, and with every best at zero the
     * boost is 1 either way.
     */
    dissonance: (() => {
      const tierPersonalBest = cell('CH6')
      const allTierPersonalBests: number[] = []
      // `$CH$7:$CH$27` — one row a tier, read as cells because the reader takes
      // a flat map rather than ranges.
      for (let row = 7; row <= 27; row += 1) allTierPersonalBests.push(cell(`CH${row}`))
      return {
        active: tierPersonalBest > 0 || allTierPersonalBests.some(best => best > 0),
        tierPersonalBest,
        allTierPersonalBests,
      }
    })(),
  }
}

/**
 * The level band, `BO5` through `CE5`, with headers read off row 4.
 *
 * `CB5`/`CC5`/`CD5` are the LAB capacities; the stone-bought ones are
 * `BK22`/`BK23`/`BK25` on this same tab: they sit in the band that mirrors the tab's lab block,
 * which lists "Assist Module Substats - Armor" as a lab. The stone-bought
 * capacities are not on this tab at all, so they stay 0 -- and because `CK5`
 * (Armor) and `CL5` (Defense Absolute) are constant across every swept account,
 * NOTHING here discriminates that choice. Recorded as unverified rather than
 * asserted.
 */
export function effectiveHealthLevelsFromSheet(cells: SheetCells): EffectiveHealthLevels {
  const { cell } = reader(cells)
  return {
    ...ZERO_LEVELS,
    health: cell('BO5'),
    defenseAbsolute: cell('BP5'),
    defensePercent: cell('BQ5'),
    wallHealth: cell('BR5'),
    wallFortification: cell('BS5'),
    recoveryPackageMax: cell('BT5'),
    standardPerksBonus: cell('BU5'),
    improveTradeOffPerks: cell('BV5'),
    chronoFieldReduction: cell('BW5'),
    deathWaveHealth: cell('BX5'),
    chainThunder: cell('BY5'),
    healthMastery: cell('BZ5'),
    extraDefenseMastery: cell('CA5'),
    assistSubstatArmorLab: cell('CB5'),
    assistSubstatGeneratorLab: cell('CC5'),
    assistBonusArmorLab: cell('CD5'),

    /*
     * The STONE-bought assist capacities, which this reader used to leave at
     * zero on the stated grounds that "the stone-bought capacities are not on
     * this tab at all". They are, at `BK22`, `BK23` and `BK25`, and every
     * component formula names one:
     *
     *   EPH_ARMOR(…, $BK$22, CD5)        bonus armor
     *   EPH_DABS(…, $BK$23, CB5, …)      substat armor
     *   EPH_WALL_HEALTH(…, $BK$23, CB5)  substat armor
     *   EPH_MAX_RCVR(…, $BK$25, CC5, …)  substat generator
     *
     * The cap the stat uses is the stone capacity PLUS the lab one, so leaving
     * these at zero halves the assist term whenever a player has bought any.
     * On `sheet-18` that is armor at 31.65 against the sheet's 71.24: the cap
     * is `BK22 + CD5` = 9 + 1 = 10, and the port was using 1.
     *
     * It read as correct for as long as it did because the generated fixture is
     * built on a copy with a blank `_IDS`, where all three are 0 -- and so are
     * they on the real accounts that happened to match.
     *
     * The neighbouring label spells it out: `BJ22` is
     * "09 | 10% | Cost 39 ⧌ | Next 42 ⧌", and ⧌ is the stone.
     */
    assistBonusArmor: cell('BK22'),
    assistSubstatArmor: cell('BK23'),
    assistSubstatGenerator: cell('BK25'),
    dissonantEchoDefense: cell('CE5'),

    // `$BI$6`, `$BI$8`, `$BI$10`, `$BI$13` — the "WS+" levels each component
    // formula reads beside its workshop value.
    enhancementHealth: cell('BI6'),
    enhancementDefenseAbsolute: cell('BI8'),
    enhancementWallHealth: cell('BI10'),
    enhancementRecoveryPackage: cell('BI13'),
  }
}

/**
 * `EffectiveRegenConfig` from the same eHP cells.
 *
 * The regen path has no input block of its own: `eRegen!AL3` is
 * `={eHP!AL3:BM37}`, so every cell below is the eHP tab's, read at the Health
 * Regen row instead of the Health row. That is why this lives here rather than
 * in a reader of its own.
 *
 * Every address is taken from the sheet's own call, not inferred from the eHP
 * ones by adding a row:
 *
 *   EPH_REGEN($BH$7, BO5, AND($AY$16, $AY$21), $AV$21, $AY$22, BS5, $BK$23,
 *             BU5, $AN$7, $AO$7, $BI$7, AND($AY$28, $AY$31), BQ5,
 *             AND($AY$28, $AY$35), AND($AY$28, $AY$37), BR5, $BL$7, $BM$7,
 *             $AY$26, BT5)
 *
 * The two mastery flags are read RAW, matching the sheet: `has_mastery` is
 * `$AY$22` and `has_swm` is `$AY$26`, neither wrapped in the cards master the
 * way `has_card` is. Wrapping them would be the tidier-looking mistake.
 *
 * The levels (`BO5`, `BQ5`, `BR5`, `BS5`, `BT5`, `BU5`) are NOT here: they are
 * eRegen's own band, which the eHP mirror does not reach, and they come from
 * the captured `eRegen!BO4:BU5` instead.
 */
export function effectiveRegenConfigFromSheet(cells: SheetCells): EffectiveRegenConfig {
  const { cell, flag } = reader(cells)
  return {
    healthRegen: {
      workshopValue: cell('BH7'),
      enhancementLevel: cell('BI7'),
      relicPct: cell('BL7'),
      vaultPct: cell('BM7'),
      primarySubstat: cell('AN7'),
      assistSubstat: cell('AO7'),
    },
    card: {
      has: flag('AY16') && flag('AY21'),
      value: cell('AV21'),
      hasMastery: flag('AY22'),
    },
    hasSecondWindMastery: flag('AY26'),
  }
}
