/**
 * Effective Paths — level validation for the economy, health and regen models.
 *
 * `effective-paths-edamage-schema.ts` covers the damage model's config and
 * levels; this covers levels for the other three.
 *
 * ## What it checks, and why
 *
 * Levels are the input most likely to arrive damaged, because they are rebuilt
 * from stored payloads and partial imports rather than assembled once. Two
 * failures matter:
 *
 * - a **missing** key, so the model reads `undefined` and arithmetic on it
 *   yields `NaN`, which spreads through every term it touches;
 * - a key already holding `NaN`, typically from an emptied number field.
 *
 * Neither throws. The planner ranks against the result and returns a plausible
 * table, so the error surfaces as a wrong answer rather than a failure.
 *
 * Strict about **completeness and finiteness**, lenient about **magnitude**: a
 * level beyond any cap is still the caller's data, whereas an absent one is
 * unusable.
 */
/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    effectiveEconomyLevelsSchema, effectiveHealthLevelsSchema, effectiveRegenLevelsSchema, EffectiveLevelsIssue, EffectiveLevelsCheck, checkEffectiveEconomyLevels, checkEffectiveHealthLevels, checkEffectiveRegenLevels (+3 more)
 * depends    src/mechanics/effective-paths/eecon-levels, src/mechanics/effective-paths/ehp-model, src/mechanics/effective-paths/regen-levels
 * used by    src/mechanics/calculators/specs-generated, src/mechanics/effective-paths/eecon-plan, src/mechanics/effective-paths/ehp-plan, src/mechanics/effective-paths/index, src/mechanics/effective-paths/regen-plan
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */

import { z } from 'zod'
import { ZERO_EFFECTIVE_ECONOMY_LEVELS } from './eecon-levels'
import type { EffectiveEconomyLevels } from './eecon-levels'
import { ZERO_EFFECTIVE_HEALTH_LEVELS } from './ehp-model'
import type { EffectiveHealthLevels } from './ehp-model'
// From the levels module rather than the planner: the planner checks its
// levels through this file, so importing it back would be a cycle.
import { ZERO_EFFECTIVE_REGEN_LEVELS } from './regen-levels'
import type { EffectiveRegenLevels } from './regen-levels'

/**
 * A level: any finite number.
 *
 * Deliberately not `.int().min(0)`. The source this model reproduces contains
 * negative levels, so a lower bound would reject valid input — and it would
 * reject it by returning an empty result, which is indistinguishable from
 * "nothing to plan".
 *
 * `.finite()` is the one constraint that holds regardless: `NaN` and `Infinity`
 * have no useful arithmetic, and rejecting them is the purpose of this file.
 */
const level = z.number().finite()

/**
 * A record with **exactly** these keys, each a level.
 *
 * Built from a zero record's own keys rather than written out, so a level added
 * to a model is covered the moment it exists. `z.record` is not enough: it
 * accepts an object missing half its keys, which is precisely the shape a
 * partial payload has.
 */
function exactLevels<K extends string>(keys: readonly K[]): z.ZodType<Record<K, number>> {
  return z.object(
    Object.fromEntries(keys.map(key => [key, level])) as Record<K, typeof level>,
  ) as unknown as z.ZodType<Record<K, number>>
}

const keysOf = <T extends object>(zero: T) => Object.keys(zero) as Array<keyof T & string>

/** Every economy level, in its four bands. */
export const effectiveEconomyLevelsSchema = z.object({
  time: exactLevels(keysOf(ZERO_EFFECTIVE_ECONOMY_LEVELS.time)),
  stone: exactLevels(keysOf(ZERO_EFFECTIVE_ECONOMY_LEVELS.stone)),
  discount: exactLevels(keysOf(ZERO_EFFECTIVE_ECONOMY_LEVELS.discount)),
})

/** Every eHP level. Flat, unlike the banded damage and economy ones. */
export const effectiveHealthLevelsSchema = exactLevels(keysOf(ZERO_EFFECTIVE_HEALTH_LEVELS))

/** The regen path's own four, which sit alongside the eHP ones. */
export const effectiveRegenLevelsSchema = exactLevels(keysOf(ZERO_EFFECTIVE_REGEN_LEVELS))

/** One thing wrong with a set of levels, and where. */
export interface EffectiveLevelsIssue {
  /** Dotted path — `time.coinsKillBonus`, or `health`. */
  path: string
  message: string
}

export interface EffectiveLevelsCheck {
  ok: boolean
  issues: EffectiveLevelsIssue[]
}

function toCheck(result: { success: boolean, error?: z.ZodError }): EffectiveLevelsCheck {
  if (result.success || !result.error) return { ok: true, issues: [] }
  return {
    ok: false,
    issues: result.error.issues.map((issue: z.core.$ZodIssue) => ({
      path: issue.path.map(String).join('.'),
      message: issue.message,
    })),
  }
}

/**
 * Check levels before planning against them.
 *
 * Reports rather than throws, for the same reason the damage checker does: a
 * caller is better placed to decide whether broken input means "show
 * nothing" or "show this and say which part is unreadable". A page that renders
 * nothing is worse than one that names the problem.
 */
export function checkEffectiveEconomyLevels(levels: unknown): EffectiveLevelsCheck {
  return toCheck(effectiveEconomyLevelsSchema.safeParse(levels))
}

export function checkEffectiveHealthLevels(levels: unknown): EffectiveLevelsCheck {
  return toCheck(effectiveHealthLevelsSchema.safeParse(levels))
}

export function checkEffectiveRegenLevels(levels: unknown): EffectiveLevelsCheck {
  return toCheck(effectiveRegenLevelsSchema.safeParse(levels))
}

/** Types the schemas are built to match, asserted at compile time. */
export type CheckedEconomyLevels = EffectiveEconomyLevels
export type CheckedHealthLevels = EffectiveHealthLevels
export type CheckedRegenLevels = EffectiveRegenLevels
