/**
 * Effective Paths — the sync schema.
 *
 * The spreadsheet is maintained by people who know the game deeply and do not
 * write code. The point of this schema is that their ordinary edits — a changed
 * coefficient, a raised cap, a new term on a stat — reach the site as *data*,
 * validated, without anyone shipping a release.
 *
 * ## The shape, and why it is this shape
 *
 * A stat mirrors the sheet's own `LET`: an ordered list of named terms, then a
 * result expression over them.
 *
 * ```text
 * LET(  WS,  ws_val,                     -> term WS
 *       LAB, 1% * lab_lvl,               -> term LAB
 *       SAC, (1 + stone + lab) * 0.01,   -> term SAC
 *   SUBSTAT, prim + ass * SAC,           -> term SUBSTAT, referring to SAC
 *       (WS + LAB + SUBSTAT) * WSE )     -> result
 * ```
 *
 * Terms may refer to earlier terms, exactly as `LET` bindings do, and the
 * result is an arbitrary expression rather than one fixed combining rule —
 * `(WS + LAB + SUBSTAT) * WSE * VAULT` is a real formula here and is neither a
 * plain sum nor a plain product.
 *
 * ## What this is not
 *
 * It is deliberately not a formula language. Nothing is parsed from text or
 * evaluated as code at runtime — the expression set is closed, so a synced
 * document can carry wrong numbers but cannot introduce behaviour. A genuinely
 * new formula *shape* still needs a release. That is the trade, taken on
 * purpose.
 *
 * Validate with {@link parseEffectivePathsDocument}, which never throws — a
 * document that fails should leave the caller on its bundled copy rather than
 * degrade to a half-applied state.
 */
/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    EffectivePathsCompareOp, EffectivePathsExpr, EffectivePathsExprSchema, EffectivePathsInputs, EffectivePathsInputError, evaluateExpr, collectExprInputs, collectExprTermRefs (+16 more)
 * depends    —
 * used by    src/mechanics/calculators/specs-generated, src/mechanics/effective-paths/aliases, src/mechanics/effective-paths/formula, src/mechanics/effective-paths/index, src/mechanics/effective-paths/workbook
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */

import { z } from 'zod'

const Name = z.string().min(1)

export type EffectivePathsCompareOp = 'eq' | 'neq' | 'gt' | 'gte' | 'lt' | 'lte'

export type EffectivePathsExpr =
  /** A fixed number. The sheet's `2%` extracts as `0.02`. */
  | { kind: 'const', value: number }
  /** A named input supplied by the caller — a workshop value, a lab level. */
  | { kind: 'input', ref: string }
  /** An earlier term in the same stat, as a `LET` binding refers to one. */
  | { kind: 'ref', term: string }
  /** `base + perLevel × level`. Sugar for the sheet's commonest shape. */
  | { kind: 'linear', base: number, perLevel: number, level: string }
  | { kind: 'sum', of: EffectivePathsExpr[] }
  | { kind: 'product', of: EffectivePathsExpr[] }
  | { kind: 'divide', numerator: EffectivePathsExpr, denominator: EffectivePathsExpr }
  | { kind: 'negate', of: EffectivePathsExpr }
  | { kind: 'power', base: EffectivePathsExpr, exponent: EffectivePathsExpr }
  | { kind: 'abs', of: EffectivePathsExpr }
  /**
   * `ROUND`, `FLOOR` and `CEILING`. `modifier` is decimal places for `nearest`
   * and a multiple to snap to for `down` and `up`, matching the sheet.
   */
  | {
    kind: 'round'
    mode: 'nearest' | 'down' | 'up'
    value: EffectivePathsExpr
    modifier?: EffectivePathsExpr
  }
  | { kind: 'compare', op: EffectivePathsCompareOp, left: EffectivePathsExpr, right: EffectivePathsExpr }
  /** `when ? then : otherwise`. A numeric `when` is truthy when non-zero. */
  | { kind: 'gated', when: EffectivePathsExpr, then: EffectivePathsExpr, otherwise: EffectivePathsExpr }
  | { kind: 'min', of: EffectivePathsExpr[] }
  | { kind: 'max', of: EffectivePathsExpr[] }
  /** Clamp, for a cap the game applies — defense percent stops at 98%. */
  | { kind: 'clamp', value: EffectivePathsExpr, min?: number, max?: number }

export const EffectivePathsExprSchema: z.ZodType<EffectivePathsExpr> = z.lazy(() =>
  z.discriminatedUnion('kind', [
    z.object({ kind: z.literal('const'), value: z.number().finite() }),
    z.object({ kind: z.literal('input'), ref: Name }),
    z.object({ kind: z.literal('ref'), term: Name }),
    z.object({
      kind: z.literal('linear'),
      base: z.number().finite(),
      perLevel: z.number().finite(),
      level: Name,
    }),
    z.object({ kind: z.literal('sum'), of: z.array(EffectivePathsExprSchema).min(1) }),
    z.object({ kind: z.literal('product'), of: z.array(EffectivePathsExprSchema).min(1) }),
    z.object({
      kind: z.literal('divide'),
      numerator: EffectivePathsExprSchema,
      denominator: EffectivePathsExprSchema,
    }),
    z.object({ kind: z.literal('negate'), of: EffectivePathsExprSchema }),
    z.object({
      kind: z.literal('power'),
      base: EffectivePathsExprSchema,
      exponent: EffectivePathsExprSchema,
    }),
    z.object({ kind: z.literal('abs'), of: EffectivePathsExprSchema }),
    z.object({
      kind: z.literal('round'),
      mode: z.enum(['nearest', 'down', 'up']),
      value: EffectivePathsExprSchema,
      modifier: EffectivePathsExprSchema.optional(),
    }),
    z.object({
      kind: z.literal('compare'),
      op: z.enum(['eq', 'neq', 'gt', 'gte', 'lt', 'lte']),
      left: EffectivePathsExprSchema,
      right: EffectivePathsExprSchema,
    }),
    z.object({
      kind: z.literal('gated'),
      when: EffectivePathsExprSchema,
      then: EffectivePathsExprSchema,
      otherwise: EffectivePathsExprSchema,
    }),
    z.object({ kind: z.literal('min'), of: z.array(EffectivePathsExprSchema).min(1) }),
    z.object({ kind: z.literal('max'), of: z.array(EffectivePathsExprSchema).min(1) }),
    z.object({
      kind: z.literal('clamp'),
      value: EffectivePathsExprSchema,
      min: z.number().finite().optional(),
      max: z.number().finite().optional(),
    }),
  ]),
)

/** Values an expression may read: numbers for levels and stats, booleans for gates. */
export type EffectivePathsInputs = Readonly<Record<string, number | boolean>>

export class EffectivePathsInputError extends Error {
  constructor(public readonly ref: string, kind: 'input' | 'term' = 'input') {
    super(`Effective Paths: no ${kind} named "${ref}"`)
    this.name = 'EffectivePathsInputError'
  }
}

const toNumber = (value: number | boolean): number =>
  typeof value === 'boolean' ? (value ? 1 : 0) : value

type Evaluate = (part: EffectivePathsExpr) => number

/**
 * `ROUND`, `FLOOR` and `CEILING`, which read their second argument differently.
 *
 * `ROUND` takes decimal places; the other two take a multiple to snap to. Both
 * default to leaving the value alone.
 */
function evaluateRound(
  expr: Extract<EffectivePathsExpr, { kind: 'round' }>,
  evaluate: Evaluate,
): number {
  const value = evaluate(expr.value)

  if (expr.mode === 'nearest') {
    const places = expr.modifier === undefined ? 0 : evaluate(expr.modifier)
    const scale = Math.pow(10, places)
    return Math.round(value * scale) / scale
  }

  const multiple = expr.modifier === undefined ? 1 : evaluate(expr.modifier)
  if (multiple === 0) return 0
  return (expr.mode === 'down' ? Math.floor(value / multiple) : Math.ceil(value / multiple))
    * multiple
}

/** The six comparisons, as the sheet's 1-or-0 arithmetic rather than booleans. */
function evaluateCompare(
  expr: Extract<EffectivePathsExpr, { kind: 'compare' }>,
  evaluate: Evaluate,
): number {
  const left = evaluate(expr.left)
  const right = evaluate(expr.right)

  switch (expr.op) {
    case 'eq': return left === right ? 1 : 0
    case 'neq': return left !== right ? 1 : 0
    case 'gt': return left > right ? 1 : 0
    case 'gte': return left >= right ? 1 : 0
    case 'lt': return left < right ? 1 : 0
    case 'lte': return left <= right ? 1 : 0
  }
  return 0
}

/**
 * Evaluate an expression.
 *
 * `terms` holds the values of earlier terms in the same stat. Missing inputs
 * throw {@link EffectivePathsInputError} rather than reading as zero — a
 * silently-absent level produces a plausible wrong answer, which is worse than
 * a loud failure.
 */
export function evaluateExpr(
  expr: EffectivePathsExpr,
  inputs: EffectivePathsInputs,
  terms: ReadonlyMap<string, number> = new Map(),
): number {
  const evaluate = (part: EffectivePathsExpr) => evaluateExpr(part, inputs, terms)

  switch (expr.kind) {
    case 'const':
      return expr.value
    case 'input': {
      const value = inputs[expr.ref]
      if (value === undefined) throw new EffectivePathsInputError(expr.ref)
      return toNumber(value)
    }
    case 'ref': {
      const value = terms.get(expr.term)
      if (value === undefined) throw new EffectivePathsInputError(expr.term, 'term')
      return value
    }
    case 'linear': {
      const level = inputs[expr.level]
      if (level === undefined) throw new EffectivePathsInputError(expr.level)
      return expr.base + expr.perLevel * toNumber(level)
    }
    case 'sum':
      return expr.of.reduce((total, part) => total + evaluate(part), 0)
    case 'product':
      return expr.of.reduce((total, part) => total * evaluate(part), 1)
    case 'divide':
      return evaluate(expr.numerator) / evaluate(expr.denominator)
    case 'negate':
      return -evaluate(expr.of)
    case 'power':
      return Math.pow(evaluate(expr.base), evaluate(expr.exponent))
    case 'abs':
      return Math.abs(evaluate(expr.of))
    case 'round':
      return evaluateRound(expr, evaluate)
    case 'compare':
      return evaluateCompare(expr, evaluate)
    case 'gated':
      return evaluate(expr.when) !== 0 ? evaluate(expr.then) : evaluate(expr.otherwise)
    case 'min':
      return Math.min(...expr.of.map(evaluate))
    case 'max':
      return Math.max(...expr.of.map(evaluate))
    case 'clamp': {
      let value = evaluate(expr.value)
      if (expr.min !== undefined) value = Math.max(expr.min, value)
      if (expr.max !== undefined) value = Math.min(expr.max, value)
      return value
    }
  }
}

/** Every caller-supplied input an expression reads. Term references are excluded. */
export function collectExprInputs(expr: EffectivePathsExpr, into = new Set<string>()): Set<string> {
  switch (expr.kind) {
    case 'input': into.add(expr.ref); break
    case 'linear': into.add(expr.level); break
    case 'sum': case 'product': case 'min': case 'max':
      for (const part of expr.of) collectExprInputs(part, into)
      break
    case 'divide':
      collectExprInputs(expr.numerator, into)
      collectExprInputs(expr.denominator, into)
      break
    case 'negate': case 'abs': collectExprInputs(expr.of, into); break
    case 'power':
      collectExprInputs(expr.base, into)
      collectExprInputs(expr.exponent, into)
      break
    case 'round':
      collectExprInputs(expr.value, into)
      if (expr.modifier) collectExprInputs(expr.modifier, into)
      break
    case 'compare':
      collectExprInputs(expr.left, into)
      collectExprInputs(expr.right, into)
      break
    case 'gated':
      collectExprInputs(expr.when, into)
      collectExprInputs(expr.then, into)
      collectExprInputs(expr.otherwise, into)
      break
    case 'clamp': collectExprInputs(expr.value, into); break
    case 'const': case 'ref': break
  }
  return into
}

/** Every term an expression refers to. */
export function collectExprTermRefs(expr: EffectivePathsExpr, into = new Set<string>()): Set<string> {
  switch (expr.kind) {
    case 'ref': into.add(expr.term); break
    case 'sum': case 'product': case 'min': case 'max':
      for (const part of expr.of) collectExprTermRefs(part, into)
      break
    case 'divide':
      collectExprTermRefs(expr.numerator, into)
      collectExprTermRefs(expr.denominator, into)
      break
    case 'negate': case 'abs': collectExprTermRefs(expr.of, into); break
    case 'power':
      collectExprTermRefs(expr.base, into)
      collectExprTermRefs(expr.exponent, into)
      break
    case 'round':
      collectExprTermRefs(expr.value, into)
      if (expr.modifier) collectExprTermRefs(expr.modifier, into)
      break
    case 'compare':
      collectExprTermRefs(expr.left, into)
      collectExprTermRefs(expr.right, into)
      break
    case 'gated':
      collectExprTermRefs(expr.when, into)
      collectExprTermRefs(expr.then, into)
      collectExprTermRefs(expr.otherwise, into)
      break
    case 'clamp': collectExprTermRefs(expr.value, into); break
    case 'const': case 'input': case 'linear': break
  }
  return into
}

// ---------------------------------------------------------------------------
// Stats
// ---------------------------------------------------------------------------

export const EffectivePathsTermSchema = z.object({
  /** The sheet's own `LET` name, kept verbatim: `WS`, `PERKHP`, `SUBSTAT`. */
  id: Name,
  /** What to show a reader: "Death Wave Health". */
  label: Name,
  /** Why this term exists, for whoever maintains it next. */
  note: z.string().optional(),
  expr: EffectivePathsExprSchema,
})
export type EffectivePathsTerm = z.infer<typeof EffectivePathsTermSchema>

export const EffectivePathsStatSchema = z.object({
  id: Name,
  label: Name,
  /** The function this came from, e.g. `EPH_HEALTH`. */
  sheetFunction: z.string().optional(),
  /** Parameter names, in the order the sheet's LAMBDA declares them. */
  inputs: z.array(Name).default([]),
  /** `LET` bindings, in order. A term may refer to any term before it. */
  terms: z.array(EffectivePathsTermSchema).default([]),
  /** The expression the function returns. */
  result: EffectivePathsExprSchema,
})
export type EffectivePathsStat = z.infer<typeof EffectivePathsStatSchema>

export interface EffectivePathsStatResult {
  value: number
  /** Each term's value, in declaration order — what a breakdown view shows. */
  terms: Array<{ id: string, label: string, value: number }>
}

/** Evaluate a stat: each term in order, then the result over them. */
export function evaluateStat(
  stat: EffectivePathsStat,
  inputs: EffectivePathsInputs,
): EffectivePathsStatResult {
  const values = new Map<string, number>()
  const breakdown: EffectivePathsStatResult['terms'] = []

  for (const term of stat.terms) {
    const value = evaluateExpr(term.expr, inputs, values)
    values.set(term.id, value)
    breakdown.push({ id: term.id, label: term.label, value })
  }

  return { value: evaluateExpr(stat.result, inputs, values), terms: breakdown }
}

// ---------------------------------------------------------------------------
// Aliases
// ---------------------------------------------------------------------------

/**
 * Where an upgrade lives. This is what stops a name being mapped to a
 * plausible-looking neighbour: an Ultimate Weapon lab and a Defense lab can
 * share a word without sharing a domain.
 */
export const EffectivePathsDomainSchema = z.enum([
  'lab',
  'workshop',
  'workshop-enhancement',
  'card',
  'module',
  'ultimate-weapon',
  'perk',
  'relic',
  'vault',
  'guardian',
  'bot',
])
export type EffectivePathsDomain = z.infer<typeof EffectivePathsDomainSchema>

/**
 * One upgrade, named three ways: as the sheet writes it, as this package keys
 * it, and as the save file stores it.
 *
 * Chrono Field is the reason this is explicit. It has three separate reduction
 * stats — a speed reduction the weapon applies by default, a lab that
 * *unlocks* damage reduction, and a lab that *increases* it. Two of those are
 * labs with near-identical names, and only one is what the eHP path scores.
 */
export const EffectivePathsAliasSchema = z.object({
  /** Exactly as the sheet labels it, including its capitalisation. */
  sheetName: Name,
  /** Other spellings the sheet uses. Lookup is case-insensitive already. */
  sheetAliases: z.array(Name).default([]),
  /** Stable id used everywhere in this package. */
  id: Name,
  label: Name,
  domain: EffectivePathsDomainSchema,
  /** The game's own grouping — "Defense", "Ultimate Weapon", "Perks". */
  category: Name,
  /** Key in the lab catalog / save file, when this upgrade has one. */
  saveKey: Name.optional(),
  /**
   * `true` when the upgrade is a one-off unlock rather than a level to climb.
   * The Chrono Field damage-reduction lab is one: a single level turning the
   * stat on, with a second lab governing how much.
   */
  isUnlock: z.boolean().default(false),
  /** What this upgrade feeds, when the name does not make it obvious. */
  note: z.string().optional(),
})
export type EffectivePathsAlias = z.infer<typeof EffectivePathsAliasSchema>

// ---------------------------------------------------------------------------
// The document
// ---------------------------------------------------------------------------

export const EffectivePathsDocumentSchema = z.object({
  /** Bump when the shape changes, not when the numbers do. */
  schemaVersion: z.literal(1),
  /** The spreadsheet release this was extracted from, e.g. "v5.09.02.01". */
  sheetVersion: Name,
  /** ISO timestamp of extraction. */
  generatedAt: Name,
  aliases: z.array(EffectivePathsAliasSchema).default([]),
  stats: z.array(EffectivePathsStatSchema).default([]),
})
export type EffectivePathsDocument = z.infer<typeof EffectivePathsDocumentSchema>

export type EffectivePathsParseResult =
  | { ok: true, document: EffectivePathsDocument }
  | { ok: false, errors: string[] }

/**
 * Validate a synced document.
 *
 * Never throws, and never returns a partly-valid document: a caller that gets
 * `ok: false` should stay on the copy it already has. Beyond the shape this
 * rejects documents that are internally inconsistent — a duplicate id, a name
 * two aliases both claim, a term referring to one declared after it — because
 * those mismap or misread silently rather than failing visibly.
 */
export function parseEffectivePathsDocument(input: unknown): EffectivePathsParseResult {
  const parsed = EffectivePathsDocumentSchema.safeParse(input)
  if (!parsed.success) {
    return {
      ok: false,
      errors: parsed.error.issues.map(i => `${i.path.join('.') || '(root)'}: ${i.message}`),
    }
  }

  const document = parsed.data
  const errors: string[] = []

  const seenIds = new Set<string>()
  const seenNames = new Set<string>()
  for (const alias of document.aliases) {
    if (seenIds.has(alias.id)) errors.push(`duplicate alias id: ${alias.id}`)
    seenIds.add(alias.id)
    for (const name of [alias.sheetName, ...alias.sheetAliases]) {
      const key = name.toLowerCase()
      if (seenNames.has(key)) errors.push(`sheet name claimed twice: ${name}`)
      seenNames.add(key)
    }
  }

  const seenStats = new Set<string>()
  for (const stat of document.stats) {
    if (seenStats.has(stat.id)) errors.push(`duplicate stat id: ${stat.id}`)
    seenStats.add(stat.id)

    const declared = new Set<string>()
    for (const term of stat.terms) {
      if (declared.has(term.id)) errors.push(`duplicate term id in ${stat.id}: ${term.id}`)
      for (const ref of collectExprTermRefs(term.expr)) {
        if (!declared.has(ref)) {
          errors.push(`${stat.id}.${term.id} refers to "${ref}" before it is declared`)
        }
      }
      declared.add(term.id)
    }
    for (const ref of collectExprTermRefs(stat.result)) {
      if (!declared.has(ref)) errors.push(`${stat.id} result refers to undeclared term "${ref}"`)
    }
  }

  return errors.length ? { ok: false, errors } : { ok: true, document }
}

/** Look an upgrade up by any name the sheet uses for it. */
export function findAliasBySheetName(
  document: EffectivePathsDocument,
  name: string,
): EffectivePathsAlias | null {
  const needle = name.trim().toLowerCase()
  return document.aliases.find(alias =>
    alias.sheetName.toLowerCase() === needle
    || alias.sheetAliases.some(other => other.toLowerCase() === needle),
  ) ?? null
}

/** Every input the document's stats read — what a caller has to supply. */
export function collectDocumentInputs(document: EffectivePathsDocument): Set<string> {
  const inputs = new Set<string>()
  for (const stat of document.stats) {
    for (const term of stat.terms) collectExprInputs(term.expr, inputs)
    collectExprInputs(stat.result, inputs)
  }
  return inputs
}
