/**
 * Effective Paths — the `STAT_UW_*` and `EP_UW_*` layer.
 *
 * The seven ultimate weapons the damage path cares about, and the two helpers
 * that combine them. Each weapon's stats are the same shape — a base from its
 * stone upgrades plus a module substat, sometimes floored, sometimes doubled by
 * a perk — so most of these are one line, and the interest is in which ones are
 * floored and which are not.
 *
 * `SL` and `SLM` are both Spotlight and are not the same thing: `SLM` is
 * Spotlight's own damage as a weapon, and `SL` is the coverage multiplier
 * Spotlight applies to the *other* weapons. They enter
 * {@link ultimateWeaponTotalDamage} in different places.
 *
 * Credit for the original formulas belongs to the Effective Paths maintainers —
 * see `effective-paths-credits.ts`.
 */
/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    chainLightningChance, chainLightningDamage, chainLightningQuantity, deathWaveDamage, deathWaveCooldown, deathWaveCooldownWithMvn, deathWaveQuantity, smartMissileDamage (+11 more)
 * depends    —
 * used by    src/mechanics/calculators/specs-generated, src/mechanics/effective-paths/edamage-compute, src/mechanics/effective-paths/index
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */

/** A stat that is a base plus its substat, with nothing else to it. */
const plain = (base: number, substat: number): number => base + substat

// ---------------------------------------------------------------------------
// Chain Lightning
// ---------------------------------------------------------------------------

/** `STAT_UW_CL_FINAL_CH` — Chain Lightning's proc chance. */
export const chainLightningChance = plain

/**
 * `STAT_UW_CL_FINAL_DMG` — Chain Lightning's damage; the perk doubles it.
 *
 * `vaultPct` is `BM31` as a fraction (`BN31 = BM31*5%`).
 */
export function chainLightningDamage(
  base: number,
  substat: number,
  hasPerk: boolean,
  vaultPct = 0,
): number {
  return (base + substat) * (hasPerk ? 2 : 1) * (1 + vaultPct)
}

/**
 * `STAT_UW_CL_FINAL_QTY` — how many bolts Chain Lightning throws.
 *
 * Floored, because a fraction of a bolt does not exist — and then Death Chain
 * adds six tenths on top, which is *not* floored. The sheet means that: the
 * remainder is a chance at another bolt rather than a whole one.
 */
export function chainLightningQuantity(
  base: number,
  substat: number,
  hasDeathChain: boolean,
): number {
  return Math.floor(base + substat) + (hasDeathChain ? 0.6 : 0)
}

// ---------------------------------------------------------------------------
// Death Wave
// ---------------------------------------------------------------------------

/** `STAT_UW_DW_FINAL_DMG` — Death Wave's damage (`BM30` vault as a fraction). */
export function deathWaveDamage(base: number, substat: number, vaultPct = 0): number {
  return (base + substat) * (1 + vaultPct)
}

/** `STAT_UW_DW_FINAL_CD` — Death Wave's cooldown, after Golden Combo. */
export function deathWaveCooldown(
  base: number,
  substat: number,
  goldenComboReduction: number,
): number {
  return (base + substat) * goldenComboReduction
}

/**
 * `STAT_UW_DW_FINAL_CD_MVN` — the same, unless the player runs Max Value Nuke.
 *
 * With MVN the cooldown is whatever that strategy dictates, so a number given
 * there wins outright over the computed one.
 */
export function deathWaveCooldownWithMvn(
  base: number,
  substat: number,
  goldenComboReduction: number,
  mvnCooldown: number | null | undefined,
): number {
  return typeof mvnCooldown === 'number' && Number.isFinite(mvnCooldown)
    ? mvnCooldown
    : deathWaveCooldown(base, substat, goldenComboReduction)
}

/** `STAT_UW_DW_FINAL_QTY` — Death Wave count, floored, with a perk worth one. */
export function deathWaveQuantity(base: number, substat: number, hasPerk: boolean): number {
  return Math.floor(base + substat + (hasPerk ? 1 : 0))
}

// ---------------------------------------------------------------------------
// Smart Missiles
// ---------------------------------------------------------------------------

/** `STAT_UW_SM_FINAL_DMG` — Smart Missile damage (`BM32` vault as a fraction). */
export function smartMissileDamage(base: number, substat: number, vaultPct = 0): number {
  return (base + substat) * (1 + vaultPct)
}

/** `STAT_UW_SM_FINAL_CD` — Smart Missile cooldown, after Golden Combo. */
export function smartMissileCooldown(
  base: number,
  substat: number,
  goldenComboReduction: number,
): number {
  return (base + substat) * goldenComboReduction
}

/** `STAT_UW_SM_FINAL_QTY` — missile count, floored, with a perk worth four. */
export function smartMissileQuantity(base: number, substat: number, hasPerk: boolean): number {
  return Math.floor(base + substat + (hasPerk ? 4 : 0))
}

/**
 * `STAT_UW_SM_FINAL_CF` — Smart Missiles' damage per second.
 *
 * Damage divided by the time between volleys. Without a cooldown to divide by
 * the sheet answers zero rather than dividing — the weapon never fires.
 */
export function smartMissileDamagePerSecond(
  damage: number,
  cooldownSeconds: number | null | undefined,
): number {
  return typeof cooldownSeconds === 'number' && Number.isFinite(cooldownSeconds)
    ? damage / cooldownSeconds
    : 0
}

// ---------------------------------------------------------------------------
// Inner Land Mines
// ---------------------------------------------------------------------------

/** `STAT_UW_ILM_FINAL_DMG` — Inner Land Mine damage (`BM37` vault as a fraction). */
export function innerLandMineDamage(base: number, substat: number, vaultPct = 0): number {
  return (base + substat) * (1 + vaultPct)
}

/** `STAT_UW_ILM_FINAL_QTY` — mine count, floored, with a perk worth six. */
export function innerLandMineQuantity(base: number, substat: number, hasPerk: boolean): number {
  return Math.floor(base + substat + (hasPerk ? 6 : 0))
}

// ---------------------------------------------------------------------------
// Spotlight
// ---------------------------------------------------------------------------

/** `STAT_UW_SL_FINAL_ANGLE` — how wide each spotlight is, in degrees. */
export const spotlightAngle = plain

/**
 * `STAT_UW_SL_FINAL_LR` — what Light Range is worth.
 *
 * Spotlight's damage bonus is boosted by a share of your damage per meter.
 * Without the upgrade the sheet leaves the term at 1 rather than at zero.
 */
export function spotlightLightRange(
  lightRange: number | null | undefined,
  damagePerMeter: number,
): number {
  const has = typeof lightRange === 'number' && Number.isFinite(lightRange)
  return 1 + (has ? lightRange * (damagePerMeter - 1) : 0)
}

/**
 * `STAT_UW_SL_FINAL_DMG` — Spotlight's own damage; the perk adds half again.
 *
 * The sheet passes two vaults: `vault_uw` (`BM39`, shared UW Damage) and
 * `vault` (`BM33`, Spotlight's own row). Both are fractions here.
 */
export function spotlightDamage(input: {
  base: number
  substat: number
  lightRange: number
  relicPct: number
  /** `BM39` / keys UW Damage vault, as a fraction. */
  vaultPct: number
  /** `BM33` Spotlight-row vault, as a fraction. */
  weaponVaultPct?: number
  hasPerk: boolean
}): number {
  return (input.base + input.substat)
    * (1 + input.relicPct)
    * (1 + input.vaultPct)
    * (1 + (input.weaponVaultPct ?? 0))
    * (input.hasPerk ? 1.5 : 1)
    * input.lightRange
}

// ---------------------------------------------------------------------------
// Combining them
// ---------------------------------------------------------------------------

/**
 * `EP_UW_HEATUP` — what repeatedly hitting one target is worth.
 *
 * Missile Amplifier makes each successive hit on the same enemy stronger, so
 * the average hit is worth the midpoint of the ramp. A non-numeric hit count
 * means no ramp at all, and the sheet's `IFERROR` answers 1.
 */
export function ultimateWeaponHeatUp(
  missileAmplifier: number,
  hitsOnSameTarget: number | null | undefined,
): number {
  if (typeof hitsOnSameTarget !== 'number' || !Number.isFinite(hitsOnSameTarget)) return 1
  const value = missileAmplifier * (hitsOnSameTarget - 1) / 2 + 1
  return Number.isFinite(value) ? value : 1
}

export interface UltimateWeaponDamageInput {
  /** Death Wave. */
  deathWave: number
  /** Chain Lightning. */
  chainLightning: number
  /** Smart Missiles. */
  smartMissiles: number
  /** Spotlight's own damage, which is added *outside* the Spotlight bonus. */
  spotlightDamage: number
  /** Spotlight's coverage bonus, applied to every other weapon. */
  spotlightBonus: number
  /** Poison Swamp. */
  poisonSwamp: number
  /** Inner Land Mines. */
  innerLandMines: number
  /** The Core module's ultimate weapon damage bonus, and dissonance. */
  damageBoost: number
  /** Super Tower's ultimate weapon share — see the note below. */
  superTowerUltimateMastery: number
  /** The Ultimate Crit card. */
  ultimateCritCard: number
}

/**
 * `EP_UW_TOTAL_DAMAGE` — the ultimate weapons' contribution.
 *
 * ```text
 * boost × ((DW + SM + CL + PS + ILM) × SL × STmastery + SLM) × critCard × STmastery
 * ```
 *
 * Two things about that shape are deliberate and easy to "tidy" into being
 * wrong. Spotlight's own damage is added *after* the Spotlight bonus, because
 * a weapon does not light itself. And `superTowerUltimateMastery` genuinely
 * appears **twice** — once inside the bracket and once outside — so it is
 * squared for every weapon except Spotlight, which takes it once.
 */
export function ultimateWeaponTotalDamage(input: UltimateWeaponDamageInput): number {
  const lit = input.deathWave
    + input.smartMissiles
    + input.chainLightning
    + input.poisonSwamp
    + input.innerLandMines

  return input.damageBoost
    * (lit * input.spotlightBonus * input.superTowerUltimateMastery + input.spotlightDamage)
    * input.ultimateCritCard
    * input.superTowerUltimateMastery
}
