/**
 * Effective Paths — what each ultimate weapon contributes per second.
 *
 * `effective-paths-ultimate-weapons.ts` resolves a weapon's *stats*; this turns
 * those stats into damage per second, which is what the `UWs` factor sums.
 *
 * Six of the seven are a plain damage ÷ cooldown. Chain Lightning is not: it
 * procs per bullet, so its rate is a function of the tower's own fire rate and
 * of the game speed, and it is the only weapon whose output moves when a
 * bullet stat does.
 */
/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    realGameSpeed, deathWaveDps, chainLightningDps, smartMissilesDps, spotlightMissilesDps, poisonSwampDps, innerLandMinesDps, spotlightFinalBonus
 * depends    src/mechanics/effective-paths/damage-stats
 * used by    src/mechanics/calculators/specs-generated, src/mechanics/effective-paths/edamage-compute, src/mechanics/effective-paths/index
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */

import { areaOfEffectCardBoost } from './damage-stats'

/**
 * `TTG_GAME_SPEED` — the real speed multiplier behind a displayed one.
 *
 * The game's speed settings do not deliver what they say: 5× runs at 4×, and
 * 1× actually runs slightly fast. Anything that counts frames has to use this
 * rather than the number on the button.
 */
export function realGameSpeed(displayedSpeed: number): number {
  const scale
    = displayedSpeed >= 5 ? 0.8
      : displayedSpeed >= 4.5 ? 0.82
        : displayedSpeed >= 4 ? 0.84
          : displayedSpeed >= 3.5 ? 0.88
            : displayedSpeed >= 3 ? 0.92
              : displayedSpeed >= 2.5 ? 0.95
                : displayedSpeed >= 2 ? 1
                  : 1.07
  return displayedSpeed * scale
}

/** The Area of Effect card, which every cooldown-based weapon takes. */
interface AreaOfEffectCard {
  hasAreaOfEffectCard: boolean
  areaOfEffectCardLevel: number
}

/**
 * `EP_DW_DPS` — Death Wave.
 *
 * The `5 + 1.5 × amp` term is the number of enemies a wave is assumed to pass
 * through, not a damage multiplier, which is why the Damage Amplifier lab pays
 * off far better than its name suggests.
 */
export function deathWaveDps(input: {
  unlocked: boolean
  damage: number
  quantity: number
  cooldownSeconds: number
  damageAmplifierLabLevel: number
}): number {
  if (!input.unlocked) return 0
  return (input.damage / input.cooldownSeconds)
    * input.quantity
    * (5 + input.damageAmplifierLabLevel * 1.5)
}

/**
 * `EP_CL_DPS` — Chain Lightning.
 *
 * Every bullet rolls for a proc, so the sheet works in frames: bullets a frame
 * at 120 frames a second, the chance at least one of them procs, and back to
 * procs a second. Multishot and bounce multiply it because each extra bullet
 * rolls too.
 *
 * This is why Chain Lightning appears on the *bullet* stats' payoff: raising
 * attack speed raises it, and no other weapon behaves that way.
 */
export function chainLightningDps(input: {
  damage: number
  quantity: number
  /** Proc chance a bullet, as a fraction. */
  chance: number
  attackSpeed: number
  rapidFire: number
  multishot: number
  /** Bounce shot *without* Astral Deliverance — the sheet's `DR`, not `DQ`. */
  bounce: number
  displayedGameSpeed: number
}): number {
  const speed = realGameSpeed(input.displayedGameSpeed)
  const fireRate = input.attackSpeed * input.rapidFire
  const bulletsPerFrame = fireRate * speed / 120
  const procChancePerFrame = 1 - Math.pow(1 - input.chance, bulletsPerFrame)
  const procsPerSecond = 120 / speed * procChancePerFrame

  return input.damage
    * input.quantity
    * procsPerSecond
    * input.multishot
    * input.bounce
    * bulletsPerFrame
}

/**
 * `EP_SM_DPS` — Smart Missiles.
 *
 * Cover Fire is added *after* the cooldown divide because it is already a rate.
 */
export function smartMissilesDps(input: AreaOfEffectCard & {
  damage: number
  quantity: number
  cooldownSeconds: number
  coverFire: number
  heatUp: number
  areaOfEffect: number
}): number {
  return input.heatUp
    * input.areaOfEffect
    * (input.damage * input.quantity / input.cooldownSeconds + input.coverFire)
    * areaOfEffectCardBoost(input.hasAreaOfEffectCard, input.areaOfEffectCardLevel)
}

/**
 * `EP_SLM_DPS` — the Spotlight Missiles a lit Smart Missile fires.
 *
 * Unconditional: the caller gates it on both Spotlight and Smart Missiles
 * being unlocked, because neither alone produces any.
 */
export function spotlightMissilesDps(input: AreaOfEffectCard & {
  smartMissileDamage: number
  spotlightDamage: number
  /** The sheet passes `20 - level`, so the lab shortens it. */
  cooldownSeconds: number
  heatUp: number
  areaOfEffect: number
}): number {
  return input.heatUp
    * input.areaOfEffect
    * input.smartMissileDamage
    * input.spotlightDamage
    / input.cooldownSeconds
    * areaOfEffectCardBoost(input.hasAreaOfEffectCard, input.areaOfEffectCardLevel)
}

/** `EP_PS_DPS` — Poison Swamp. */
export function poisonSwampDps(input: AreaOfEffectCard & {
  unlocked: boolean
  damage: number
  durationSeconds: number
  cooldownSeconds: number
  deathCreep: number
  rend: number
}): number {
  if (!input.unlocked) return 0
  return input.damage
    * (input.durationSeconds / input.cooldownSeconds)
    * input.deathCreep
    * input.rend
    * areaOfEffectCardBoost(input.hasAreaOfEffectCard, input.areaOfEffectCardLevel)
}

/**
 * `EP_ILM_DPS` — Inner Land Mines.
 *
 * `detonationsPerSecond` already folds in Space Displacer's extra mines, which
 * is why it is a rate rather than a quantity and a cooldown.
 */
export function innerLandMinesDps(input: AreaOfEffectCard & {
  unlocked: boolean
  damage: number
  detonationsPerSecond: number
  /** The Chrono Jump lab, five per level, already multiplied by the `+` heat-up. */
  chronoJump: number
  chargedMines: number
  areaOfEffect: number
}): number {
  if (!input.unlocked) return 0
  return input.damage
    * input.detonationsPerSecond
    * (1 + input.chronoJump * input.chargedMines)
    * input.areaOfEffect
    * areaOfEffectCardBoost(input.hasAreaOfEffectCard, input.areaOfEffectCardLevel)
}

/**
 * `EP_SL_FINAL_BONUS` — Spotlight's bonus, weighted by how much it lights.
 *
 * A bonus that only reaches part of the field is worth only that part of it,
 * so a wide-angle Spotlight is worth more than its damage stat implies.
 */
export function spotlightFinalBonus(coverage: number, bonus: number): number {
  return 1 + (bonus - 1) * coverage
}
