/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    LoadMechanicsKernelOptions, loadMechanicsKernel, loadMechanicsContext, resolveMechanicsRepoRoot
 * depends    src/mechanics/ep-graph, tooling/coverage/schema, tooling/debug-graph, tooling/kernel/schema, tooling/repo-root, tooling/save-graph (+1 more)
 * used by    tooling/kernel/index, tooling/kernel/validate, tooling/registry/build
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
import fs from 'node:fs'
import path from 'node:path'
import {
  CoverageInventorySchema,
  coverageStatusCounts,
  findSilentGaps,
  type CoverageInventory,
} from '../coverage/schema'
import { loadDebugGraphDegraded } from '../debug-graph'
import { loadEpGraph } from '../../src/mechanics/ep-graph'
import { resolveMechanicsRepoRoot } from '../repo-root'
import { loadSaveGraphDegraded } from '../save-graph'
import {
  buildSdkGraphIndex,
  loadSdkGraphWithTrust,
  type TrustMode,
} from '../sdk-graph'
import {
  MechanicsContextSchema,
  type MechanicsContext,
  type MechanicsKernelHandle,
} from './schema'

export { resolveMechanicsRepoRoot } from '../repo-root'

export interface LoadMechanicsKernelOptions {
  repoRoot?: string
  mode?: TrustMode
  scanPlannerCitations?: boolean
  checkDebugGraph?: boolean
}

function loadInventoryFile(filePath: string): CoverageInventory | null {
  if (!fs.existsSync(filePath)) return null
  try {
    return CoverageInventorySchema.parse(JSON.parse(fs.readFileSync(filePath, 'utf8')))
  } catch {
    return null
  }
}

function summarizeInventory(inv: CoverageInventory | null) {
  if (!inv) {
    return { entryCount: 0, silentGapCount: 0, counts: {} as Record<string, number> }
  }
  return {
    entryCount: inv.entries.length,
    silentGapCount: findSilentGaps(inv).length,
    counts: coverageStatusCounts(inv),
  }
}

/**
 * Unified mechanics load: graphs + trust + coverage.
 * Graph is SoT for relationships; this facade does not invent facts.
 */
export function loadMechanicsKernel(
  opts: LoadMechanicsKernelOptions = {},
): MechanicsKernelHandle {
  const repoRoot = resolveMechanicsRepoRoot(opts.repoRoot)
  const mode = opts.mode ?? 'degraded'

  const { graph: sdkGraph, report: trust, trust: trustLabel } = loadSdkGraphWithTrust({
    mode,
    scanPlannerCitations: opts.scanPlannerCitations ?? true,
    checkDebugGraph: opts.checkDebugGraph ?? true,
  })
  const epGraph = loadEpGraph()
  const dbg = loadDebugGraphDegraded()
  const save = loadSaveGraphDegraded()
  const index = buildSdkGraphIndex(sdkGraph)

  const coverageDir = path.join(repoRoot, 'packages/sdk/tooling/coverage/data')
  const inventories: Record<string, CoverageInventory | null> = {
    sheets: loadInventoryFile(path.join(coverageDir, 'sheets.v1.json')),
    'sdk-modules': loadInventoryFile(path.join(coverageDir, 'sdk-modules.v1.json')),
    wiki: loadInventoryFile(path.join(coverageDir, 'wiki.v1.json')),
    'save-schema': loadInventoryFile(path.join(coverageDir, 'save-schema.v1.json')),
  }


  const debugNodes = Object.values(dbg.graph.nodes)
  const debugSymbolCount = debugNodes.filter(n => n.type === 'runtime.symbol').length
  const debugModuleCount = debugNodes.filter(n => n.type === 'runtime.module').length

  const surfaces: MechanicsContext['coverage']['surfaces'] = {}
  for (const [key, inv] of Object.entries(inventories)) {
    surfaces[key] = summarizeInventory(inv)
  }

  const context = MechanicsContextSchema.parse({
    generatedAt: new Date().toISOString(),
    constitution: 'docs/AGENT_MECHANICS_CONSTITUTION.md',
    trustLabel,
    graphs: {
      sdk: {
        nodeCount: Object.keys(sdkGraph.nodes).length,
        edgeCount: sdkGraph.edges.length,
        contentVersion: sdkGraph.contentVersion,
        sheetVersion: sdkGraph.sheetVersion,
      },
      ep: {
        nodeCount: Object.keys(epGraph.nodes).length,
        edgeCount: epGraph.edges.length,
        contentVersion: epGraph.contentVersion,
        sheetVersion: epGraph.sheetVersion,
      },
      debug: {
        nodeCount: Object.keys(dbg.graph.nodes).length,
        edgeCount: dbg.graph.edges.length,
        contentVersion: dbg.graph.contentVersion,
        errors: dbg.errors,
        warnings: dbg.warnings,
      },
      save: {
        nodeCount: Object.keys(save.graph.nodes).length,
        edgeCount: save.graph.edges.length,
        contentVersion: save.graph.contentVersion,
        errors: save.errors,
        warnings: save.warnings,
      },
    },
    coverage: { surfaces },
    indexHints: {
      cellCount: Object.keys(index.byCell).length,
      wikiCount: Object.keys(index.byWiki).length,
      symbolCount: Object.keys(index.bySymbol).length,
      debugSymbolCount,
      debugModuleCount,
    },
    trustOk: trust.ok,
    ok:
      trust.ok
      && dbg.errors.length === 0
      && save.errors.length === 0,
  })

  return {
    context,
    trust,
    sdkGraph,
    epGraph,
    debugGraph: dbg.graph,
    saveGraph: save.graph,
    inventories: inventories as Record<string, unknown>,
  }
}

/** Convenience: context summary only. */
export function loadMechanicsContext(opts: LoadMechanicsKernelOptions = {}): MechanicsContext {
  return loadMechanicsKernel(opts).context
}
