/**
 * Run a mechanics export under instrumentation and append a Debug Graph session trace.
 */
/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    RunExportTraceOptions, RunExportTraceResult, runExportTrace, watchDebugSources
 * depends    tooling/debug-graph/data/debug-graph.v1.json, tooling/debug-graph/schema, tooling/debug-graph/session, tooling/paths
 * used by    tooling/debug-graph/index
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
import fs from 'node:fs'
import path from 'node:path'
import { pathToFileURL } from 'node:url'
import debugRaw from './data/debug-graph.v1.json'
import { DebugGraphSchema, debugSymbolId } from './schema'
import {
  appendSessionEvent,
  previewValue,
  newTraceId,
  readSessionEvents,
  type DebugTraceRecord,
} from './session'
import { MECHANICS, MONOREPO_ROOT } from '../paths'

const HERE = __dirname
const MECHANICS_DIR = MECHANICS
const REPO_ROOT = MONOREPO_ROOT

function loadGraph() {
  return DebugGraphSchema.parse(debugRaw)
}

export interface RunExportTraceOptions {
  exportName: string
  args?: unknown[]
  repoRoot?: string
}

export interface RunExportTraceResult {
  supported: true
  trace: DebugTraceRecord
  ok: boolean
}

export async function runExportTrace(opts: RunExportTraceOptions): Promise<RunExportTraceResult> {
  const exportName = String(opts.exportName)
  const args = Array.isArray(opts.args) ? opts.args : []
  const repoRoot = opts.repoRoot ?? REPO_ROOT
  const graph = loadGraph()
  const symbol = graph.nodes[debugSymbolId(exportName)]
  if (!symbol) {
    const trace: DebugTraceRecord = {
      id: newTraceId(exportName),
      kind: 'trace',
      at: new Date().toISOString(),
      exportName,
      argsPreview: previewValue(args),
      error: {
        name: 'DebugSymbolNotFound',
        message: `No runtime.symbol for ${exportName} — run pnpm debug-graph:compile`,
      },
      durationMs: 0,
      mechanicNodeIds: [],
    }
    appendSessionEvent(trace, repoRoot)
    appendSessionEvent({
      id: `error.${trace.id}`,
      kind: 'error',
      at: trace.at,
      exportName,
      message: trace.error!.message,
    }, repoRoot)
    return { supported: true, trace, ok: false }
  }

  const rel = symbol.path
  if (!rel) {
    const trace: DebugTraceRecord = {
      id: newTraceId(exportName),
      kind: 'trace',
      at: new Date().toISOString(),
      exportName,
      argsPreview: previewValue(args),
      error: { name: 'DebugPathMissing', message: `symbol ${exportName} has no path` },
      durationMs: 0,
      mechanicNodeIds: symbol.mechanicNodeIds ?? [],
    }
    appendSessionEvent(trace, repoRoot)
    return { supported: true, trace, ok: false }
  }

  const abs = path.isAbsolute(rel) ? rel : path.join(repoRoot, rel)
  const modulePath = fs.existsSync(abs) ? abs : path.join(MECHANICS_DIR, path.basename(rel))
  if (!fs.existsSync(modulePath)) {
    const trace: DebugTraceRecord = {
      id: newTraceId(exportName),
      kind: 'trace',
      at: new Date().toISOString(),
      exportName,
      modulePath: rel,
      argsPreview: previewValue(args),
      error: { name: 'ModuleNotFound', message: `Cannot find ${rel}` },
      durationMs: 0,
      mechanicNodeIds: symbol.mechanicNodeIds ?? [],
    }
    appendSessionEvent(trace, repoRoot)
    return { supported: true, trace, ok: false }
  }

  const started = Date.now()
  let resultPreview: unknown
  let error: DebugTraceRecord['error']
  try {
    const mod = await import(pathToFileURL(modulePath).href)
    const target = mod[exportName]
    if (typeof target === 'function') {
      const out = await Promise.resolve(target(...args))
      resultPreview = previewValue(out)
    } else if (target !== undefined) {
      resultPreview = previewValue(target)
    } else {
      error = {
        name: 'ExportMissing',
        message: `${exportName} not exported from ${path.basename(modulePath)}`,
      }
    }
  } catch (err) {
    const e = err as Error
    error = {
      name: e.name || 'Error',
      message: e.message,
      stack: e.stack?.split('\n').slice(0, 12).join('\n'),
    }
  }

  const trace: DebugTraceRecord = {
    id: newTraceId(exportName),
    kind: 'trace',
    at: new Date().toISOString(),
    exportName,
    modulePath: rel,
    argsPreview: previewValue(args),
    resultPreview,
    error,
    durationMs: Date.now() - started,
    mechanicNodeIds: symbol.mechanicNodeIds ?? [],
  }
  appendSessionEvent(trace, repoRoot)
  if (error) {
    appendSessionEvent({
      id: `error.${trace.id}`,
      kind: 'error',
      at: trace.at,
      exportName,
      message: error.message,
      stack: error.stack,
    }, repoRoot)
  }
  return { supported: true, trace, ok: !error }
}

export function watchDebugSources(opts: { since?: string; repoRoot?: string } = {}) {
  const repoRoot = opts.repoRoot ?? REPO_ROOT
  const mechanicsDir = path.join(repoRoot, 'packages/sdk/src/mechanics')
  const files = fs.readdirSync(mechanicsDir)
    .filter(n => n.endsWith('.ts'))
    .map(n => {
      const p = path.join(mechanicsDir, n)
      const st = fs.statSync(p)
      return {
        path: `packages/sdk/src/mechanics/${n}`,
        mtimeMs: st.mtimeMs,
        mtime: st.mtime.toISOString(),
      }
    })
  const sinceMs = opts.since ? Date.parse(opts.since) : NaN
  const changed = Number.isNaN(sinceMs)
    ? files.sort((a, b) => b.mtimeMs - a.mtimeMs).slice(0, 20)
    : files.filter(f => f.mtimeMs >= sinceMs)
  return {
    supported: true,
    mode: 'poll' as const,
    checkedAt: new Date().toISOString(),
    changed,
    recentEvents: readSessionEvents({ limit: 20, since: opts.since, repoRoot }),
  }
}
