/**
 * Perks, their tiers, and the ones that can be banned.
 *
 * A perk is offered rather than bought: the game presents a choice each time one is earned, and a
 * banned perk is removed from that offer. So a player's perks are a function of what was offered
 * and what was banned, not a list they picked from freely — which is why the ban list is part of
 * this catalog rather than a setting somewhere else.
 */
/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    —
 * depends    src/data/perks/data
 * used by    —
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
export * from './data'
