/**
 * Guardian levels and the chips fitted to them.
 *
 * `guardianChipUnlocked[i]` and `guardianChipLevel[i]` are indexed by chip slot, not by guardian,
 * and three chip types have no key of their own — reading a chip against its guardian's index puts
 * it on the wrong twin.
 */
/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    —
 * depends    src/save/guardians/read
 * used by    —
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
export * from './read'
