/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    CurrencyName, CurrencyDefinition, CurrencyFlowRow, CashEnemyValueRule, EliteCellTierRow, CURRENCY_OVERVIEW_FACTS, CURRENCY_DEFINITIONS, CURRENCY_FLOW_ROWS (+18 more)
 * depends    —
 * used by    src/data/currency/index, src/data/index, src/knowledge/compartments/economy, src/mechanics/enemies/drops-simulation, src/mechanics/enemies/drops-wave-context
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
export type CurrencyName =
  | 'Cash'
  | 'Coins'
  | 'Gems'
  | 'Power Stones'
  | 'Medals'
  | 'Elite Cells'
  | 'Keys'
  | 'Bits'
  | 'Tokens'
  | 'Module Currency'

export interface CurrencyDefinition {
  name: CurrencyName
  summary: string
  persistence: 'run-only' | 'account' | 'mixed'
}

export interface CurrencyFlowRow {
  name: CurrencyName
  acquisitionSources: readonly string[]
  spendUses: readonly string[]
}

export interface CashEnemyValueRule {
  startWave: number
  endWaveInclusive: number | null
  waveStep: number
  cashIncreasePerStep: number
}

export interface EliteCellTierRow {
  tier: number
  minimumCells: number
  maximumCells: number
  averageCells: number
  averageIncreaseFromPriorPercent: number | null
}

function buildCurrencyFlowRow(
  name: CurrencyName,
  acquisitionSources: readonly string[],
  spendUses: readonly string[] = [],
): CurrencyFlowRow {
  return {
    name,
    acquisitionSources,
    spendUses,
  }
}

export const CURRENCY_OVERVIEW_FACTS = [
  'The game economy is split between run-only currencies, permanent account currencies, and special-purpose progression currencies.',
  'Cash is a run-only economy, while most other currencies persist on the account and feed permanent progression systems.',
  'Different currencies are tied to different parent systems such as Tournaments, Events, Guilds, Labs, Modules, and the Workshop.',
] as const

export const CURRENCY_DEFINITIONS = [
  { name: 'Cash', summary: 'Run-only currency used for temporary upgrades during a run.', persistence: 'run-only' },
  { name: 'Coins', summary: 'Core progression currency used for Workshop, Labs, and permanent enhancement unlocks.', persistence: 'account' },
  { name: 'Gems', summary: 'Core premium currency used for cards, slots, rushing, modules, and extra tournament entries.', persistence: 'account' },
  { name: 'Power Stones', summary: 'Premium progression currency used to buy and upgrade Ultimate Weapons.', persistence: 'account' },
  { name: 'Medals', summary: 'Event currency used for Event Shop purchases and saved between events.', persistence: 'account' },
  { name: 'Elite Cells', summary: 'Elite-enemy currency used to buy lab boosts.', persistence: 'account' },
  { name: 'Keys', summary: 'Legend-tournament currency used for Vault tech-tree upgrades.', persistence: 'account' },
  { name: 'Bits', summary: 'Guild-shop currency used for guardian chip upgrades.', persistence: 'account' },
  { name: 'Tokens', summary: 'Guild-shop currency earned from weekly challenge and guild reward systems.', persistence: 'account' },
  { name: 'Module Currency', summary: 'Module Shards level modules, and Reroll Dice reroll module substats.', persistence: 'account' },
] as const satisfies readonly CurrencyDefinition[]

export const CURRENCY_FLOW_ROWS = [
  buildCurrencyFlowRow('Cash', [
    'Defeating enemies',
    'Completing waves',
    'Cash / Wave upgrades',
    'Interest on unspent cash',
  ]),
  buildCurrencyFlowRow('Coins', [
    'Killing enemies',
    'Coins / Wave upgrade',
    'Daily Missions',
    'Milestones',
  ], [
    'Workshop upgrades',
    'Lab upgrades',
    'Workshop Enhancements',
  ]),
  buildCurrencyFlowRow('Gems', [
    'Floating gems (Bob)',
    'Ad gems',
    'Offer walls / TapJoy',
    'Daily free gems',
    'Tournaments',
    'Store purchases',
    'Medal or guild-token exchange paths',
    'Daily Mission and Guild reward payouts',
  ], [
    'Cards',
    'Card slots',
    'Lab slots',
    'Lab rushing',
    'Modules',
    'Tournament tickets',
  ]),
  buildCurrencyFlowRow('Power Stones', [
    'Tournaments',
    'Event medal exchange',
    'Daily Mission weekly rewards',
    'Milestones',
    'Monthly stone packs and other store offers',
  ], [
    'Ultimate Weapon purchases',
    'Ultimate Weapon upgrades',
  ]),
  buildCurrencyFlowRow('Medals', [
    'Event Missions',
    'Weekly Rewards from Daily Missions',
    'Guardian Fetch module',
  ], [
    'Event Shop currencies',
    'Themes',
    'Music',
    'Bots',
    'Event-rerun Relics',
  ]),
  buildCurrencyFlowRow('Elite Cells', [
    'Elite enemy drops from Vampire, Ray, and Scatter',
  ], [
    'Lab boosts',
  ]),
  buildCurrencyFlowRow('Keys', [
    'Legend Tournament placement from rank 1 through 15',
  ], [
    'Vault tech trees',
  ]),
  buildCurrencyFlowRow('Bits', [
    'Guild Reward Chests',
    'Guild Shop seasonal currency purchases',
  ], [
    'Guardian chip upgrades',
  ]),
  buildCurrencyFlowRow('Tokens', [
    'Weekly Challenge boxes',
    'Guild Reward Chests',
  ], [
    'Guild Shop purchases',
  ]),
  buildCurrencyFlowRow('Module Currency', [
    'Enemy drops',
    'Daily rewards',
    'Drop-rate labs',
  ], [
    'Module levels via shards',
    'Module substat rerolls via reroll dice',
  ]),
] as const satisfies readonly CurrencyFlowRow[]

export const CASH_ENEMY_VALUE_RULES = [
  { startWave: 1, endWaveInclusive: 200, waveStep: 10, cashIncreasePerStep: 1 },
  { startWave: 201, endWaveInclusive: null, waveStep: 20, cashIncreasePerStep: 1 },
] as const satisfies readonly CashEnemyValueRule[]

export const CASH_WAVE_FLOW_FACTS = [
  'Cash per Wave is a flat payout applied first at the end of each wave.',
  'Interest is then calculated as a percentage of current unspent cash on hand, up to the current interest cap.',
  'Because Cash per Wave is applied before Interest, end-of-wave cash can push the player into a higher interest payout when they were previously below cap.',
] as const

export const CASH_IMPROVEMENT_FACTS = [
  'Cash flow improves through Cash Bonus, Cash / Wave, Interest / Wave, and Max Interest upgrades from Workshop and Labs.',
  'Cards that improve cash flow include Cash and Enemy Balance.',
  'Golden Tower, cash-oriented module effects, and Workshop Enhancements also increase run cash flow.',
] as const

export const CASH_BONUS_ENHANCEMENT_FACTS = [
  'Cash Bonus enhancement unlocks for free after completing the Workshop Enhancement labs.',
  'It increases the cash bonus multiplier by x1 when unlocked and by 0.01x per level.',
  'It also increases Cash / Wave, Interest / Wave, and Max Interest per wave by 1% each level.',
  'Its maximum level is 400 for a 5x bonus.',
] as const

export const COIN_ACQUISITION_FACTS = [
  'Coins come from enemy kills other than the pure-basic-only case, Coins / Wave, Daily Missions, and Milestones.',
  'Coin efficiency depends on both tier and wave depth, so higher tier is only better when the run still reaches strong spawn-rate and enemy-composition breakpoints.',
] as const

export const COIN_IMPROVEMENT_FACTS = [
  'Coin flow improves through higher tiers, Coins / Kill, Coins / Wave, economy cards, Ultimate Weapon income tools, module effects, perks, guardian bounty effects, and Workshop Enhancements.',
  'Important Ultimate Weapon income contributors named in the source are Golden Tower, Black Hole Coin Bonus, Spotlight Coin Bonus, and Death Wave Coin Bonus.',
] as const

export const COIN_BONUS_ENHANCEMENT_FACTS = [
  'Coin Bonus enhancement requires 50 billion coins spent on Utility enhancements to unlock.',
  'It increases the Coin Bonus multiplier by x1 when unlocked and by 0.01x per level.',
  'Its maximum level is 200 for a 3x bonus.',
  'The source notes that Coin Bonus enhancement affects both tier bonus and Coins / Kill, which makes the overall benefit effectively squared.',
] as const

export const GEM_ACQUISITION_FACTS = [
  'Floating gems spawn around the tower, up to ten per run, at two gems per pickup.',
  'Floating gems spawn about once every 400 to 500 waves and no more than once every 15 minutes.',
  'Ad gems appear about every 10 minutes and grant five gems per claim.',
  'Gems also come from store claims, tournaments, medal and guild exchange paths, daily missions, weekly reward systems, and real-money purchases.',
] as const

export const GEM_SPENDING_FACTS = [
  'Gems are spent on cards, card slots, lab slots, rushing lab upgrades, modules, and tournament tickets.',
  'This makes Gems both a progression currency and a convenience currency rather than a single-purpose shop token.',
] as const

export const POWER_STONE_FACTS = [
  'Power Stones buy and upgrade Ultimate Weapons.',
  'Purchases of 500 Power Stones or more show a confirmation prompt.',
  'Main sources listed are Tournaments, Event medal exchanges, weekly rewards, Milestones, and store offers.',
] as const

export const MEDAL_FACTS = [
  'Medals are the Event Shop currency.',
  'They are obtained from Event Missions, Weekly Rewards from Daily Missions, and Guardian Fetch.',
  'Medals do not expire when an Event ends, so they can be saved for future Event Shops.',
  'Relic threshold progress only counts medals earned during the corresponding event, not carried-over medals or daily-mission box medals.',
] as const

export const ELITE_CELL_TIER_FACTS = [
  'Elite Cells only come from defeating Vampire, Ray, and Scatter elites.',
  'For Tiers 1 through 13, each elite drops between 1 and X cells where X equals the current tier, for an average of (1 + X) / 2.',
] as const

export const ELITE_CELL_TIER_ROWS = [
  { tier: 14, minimumCells: 7, maximumCells: 14, averageCells: 10.5, averageIncreaseFromPriorPercent: 50 },
  { tier: 15, minimumCells: 11, maximumCells: 15, averageCells: 13, averageIncreaseFromPriorPercent: 23.8 },
  { tier: 16, minimumCells: 12, maximumCells: 16, averageCells: 14, averageIncreaseFromPriorPercent: 7.69 },
  { tier: 17, minimumCells: 12, maximumCells: 17, averageCells: 14.5, averageIncreaseFromPriorPercent: 3.57 },
  { tier: 18, minimumCells: 12, maximumCells: 18, averageCells: 15, averageIncreaseFromPriorPercent: 3.45 },
  { tier: 19, minimumCells: 15, maximumCells: 19, averageCells: 17, averageIncreaseFromPriorPercent: 13.3 },
  { tier: 20, minimumCells: 15, maximumCells: 20, averageCells: 17.5, averageIncreaseFromPriorPercent: 2.94 },
  { tier: 21, minimumCells: 15, maximumCells: 21, averageCells: 18, averageIncreaseFromPriorPercent: 2.86 },
  { tier: 22, minimumCells: 16, maximumCells: 22, averageCells: 19, averageIncreaseFromPriorPercent: 5.56 },
  { tier: 23, minimumCells: 16, maximumCells: 23, averageCells: 19.5, averageIncreaseFromPriorPercent: 2.63 },
  { tier: 24, minimumCells: 16, maximumCells: 24, averageCells: 20, averageIncreaseFromPriorPercent: 2.56 },
] as const satisfies readonly EliteCellTierRow[]

export const ELITE_CELL_IMPROVEMENT_FACTS = [
  'Elite Cell flow improves through Death Wave Cell Bonus, higher tiers, higher waves, Cells Bonus in Workshop Enhancements, and run-speed helpers such as Enemy Balance, Wave Skip, and Intro Sprint masteries.',
  'Cells / Kill Bonus enhancement requires 500 billion coins spent on Utility enhancements, starts at x1, increases by 0.01x per level, and caps at level 200 for a 3x bonus.',
] as const

export const KEY_FACTS = [
  'Keys are earned from placing 1st through 15th in Legend Tournament.',
  'They are used for unique Tower upgrades in the Vault tech trees.',
] as const

export const BIT_FACTS = [
  'Bits are bought from the Guild Shop using Guild Tokens and are used for guardian chip upgrades.',
  'The source lists Guild Chests at 10, 25, 50, and 100 bits for 185 bits per week.',
  'It also lists Guild Shop bit purchases at 25, 50, and 75 for 150 bits per month, with a stated combined monthly total of 890 bits.',
] as const

export const TOKEN_FACTS = [
  'Tokens are earned from Weekly Challenge boxes and Guild Reward Chests.',
  'They are spent in the Guild Shop on items and seasonal currency purchases.',
] as const

export const MODULE_CURRENCY_FACTS = [
  'Module Shards are used to upgrade module levels and can be earned from enemy drops and daily rewards.',
  'There are labs that increase module-shard drop rate.',
  'Reroll Dice are used to roll new module substats and apply across module types rather than being locked to one module family.',
] as const
