/**
 * The game's currencies, and what each is spent on.
 *
 * Worth keeping straight because the same upgrade often exists in two of them and behaves
 * differently in each — coins persist where cash resets, medals come only from events.
 */
/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    —
 * depends    src/data/currency/data
 * used by    —
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
export * from './data'
