/**
 * How long a thing is active, and how often it comes back.
 *
 * Uptime is where several systems meet — ultimate weapons, bots, guardians and the labs that
 * shorten cooldowns — so it is computed from a combined input rather than per weapon. That is why
 * this is one subject and not a helper inside each of them.
 */
/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    —
 * depends    src/mechanics/uptime/compute
 * used by    —
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
export * from './compute'
