/**
 * Thorns: how many contacts it takes to kill what is touching your wall.
 *
 * This asks for what a player can read off their own screen — base thorns, the tier they are
 * playing, plasma cannon and its mastery, the two BC reduction labs, Sharp Fortitude — and
 * answers in hits to kill, which is how the community compares thorns builds.
 *
 * It used to ask for an enemy factor, a thorn multiplier and a module benefit, and return damage
 * per hit. Those are the parameters of the underlying formula, not quantities anyone can look up,
 * and the answer was in units nobody uses. `thornDamageOnHit` is still exported from
 * `thetowersdk/mechanics` for a caller who has those values already.
 */
/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    ThornsInput, ThornsResult, thornsCalculator
 * depends    src/builders/types, src/mechanics/index
 * used by    src/builders/index
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
import {
  buildThornsBaseChart,
  buildThornsWallChart,
  normalizeThornsInput,
  type ThornsCalculatorInput,
  type ThornsWallChartRow,
} from '../mechanics/index'
import { type CalculatorBuilder, type CalculatorResultBase, clampNumber ,
  safeRecord} from './types'

/*
 * One set of keys, and they are the player-facing ones.
 *
 * The first attempt kept the model's own shorter names on the input and mapped the field keys
 * onto them. `builders.test.ts` refuses that, and is right to: a field with no default, or a
 * default with no field, is how a control comes to be read by nothing. The translation to the
 * model's names happens in one place, below.
 */
export interface ThornsInput {
  baseThorns: number
  /** The wall thorns level to report on. The chart still covers 1–20. */
  wallThorns: number
  tier: number
  plasmaCannonLevel: number
  plasmaCannonMasteryLevel: number
  bcLabLevel: number
  thornsBcReductionLabLevel: number
  plasmaCannonBcReductionLabLevel: number
  sharpFortitude: boolean
  tournamentTier: ThornsCalculatorInput['tournamentTier']
  heatWave: number
}

export interface ThornsResult extends CalculatorResultBase {
  /** Hits to kill at the wall thorns level asked for. */
  readonly atWallThorns: ThornsWallChartRow
  /** Wall thorns 1–20, for a table or a chart. */
  readonly byWallThorns: readonly ThornsWallChartRow[]
  /** The same sweep over base thorns, from where it is now. */
  readonly byBaseThorns: readonly { readonly baseThornsVal: number, readonly hitsToKillElite: number }[]
}

const defaults: ThornsInput = {
  baseThorns: 100,
  wallThorns: 10,
  tier: 1,
  plasmaCannonLevel: 0,
  plasmaCannonMasteryLevel: 0,
  bcLabLevel: 0,
  thornsBcReductionLabLevel: 0,
  plasmaCannonBcReductionLabLevel: 0,
  sharpFortitude: false,
  tournamentTier: 'none',
  heatWave: 0,
}

/** The model's own names for the same quantities. */
const toModel = (input: ThornsInput): ThornsCalculatorInput => ({
  baseThorns: input.baseThorns,
  tier: input.tier,
  pcLevel: input.plasmaCannonLevel,
  pcMasteryLevel: input.plasmaCannonMasteryLevel,
  bcLabLevel: input.bcLabLevel,
  bcReductionLabLevel: input.thornsBcReductionLabLevel,
  pcReductionLabLevel: input.plasmaCannonBcReductionLabLevel,
  tournamentTier: input.tournamentTier,
  heatWave: input.heatWave,
  sharpFortitude: input.sharpFortitude,
})

const TOURNAMENT_TIERS = [
  { value: 'none', label: 'Not a tournament' },
  { value: 't11', label: 'Tournament T11' },
  { value: 't14', label: 'Tournament T14' },
  { value: 't17', label: 'Tournament T17' },
]

export const thornsCalculator: CalculatorBuilder<ThornsInput, ThornsResult> = {
  id: 'thorns.damage',
  title: 'Thorns',
  summary: 'Hits to kill an elite, a fleet or a boss touching your wall.',

  fields: [
    { key: 'baseThorns', label: 'Base Thorns %', kind: 'number', min: 0, max: 600 },
    { key: 'wallThorns', label: 'Wall Thorns Level', kind: 'number', min: 1, max: 20 },
    { key: 'tier', label: 'Tier', kind: 'number', min: 1, max: 24 },
    { key: 'plasmaCannonLevel', label: 'Plasma Cannon Level', kind: 'number', min: 0, max: 7 },
    { key: 'plasmaCannonMasteryLevel', label: 'Plasma Cannon Mastery Level', kind: 'number', min: 0, max: 9 },
    { key: 'bcLabLevel', label: 'BC Reduction Lab Level', kind: 'number', min: 0, max: 10 },
    {
      key: 'thornsBcReductionLabLevel',
      label: 'Thorns BC Reduction Lab Level',
      kind: 'number',
      min: 0,
      max: 20,
    },
    {
      key: 'plasmaCannonBcReductionLabLevel',
      label: 'Plasma Cannon BC Reduction Lab Level',
      kind: 'number',
      min: 0,
      max: 20,
    },
    { key: 'sharpFortitude', label: 'Sharp Fortitude', kind: 'boolean' },
    { key: 'tournamentTier', label: 'Tournament', kind: 'select', options: TOURNAMENT_TIERS },
    {
      key: 'heatWave',
      label: 'Heat (Wave)',
      kind: 'number',
      min: 0,
      max: 1000,
      help: 'Only read during a tournament run, where thorn effectiveness falls with the wave.',
    },
  ],

  defaults,

  normalize(rawInput = {}) {
    const input = safeRecord(rawInput) as typeof rawInput

    const source = input as Partial<ThornsInput>
    /*
     * No String() and no Number() on anything that came from outside.
     *
     * Both coerce by calling a method on the value, and a value whose toString or valueOf throws
     * turns a normaliser into a thrower. `invariants.test.ts` passes exactly that object to every
     * field of every builder, which is how these two were found.
     */
    const tournamentTier = typeof source.tournamentTier === 'string'
      && ['none', 't11', 't14', 't17'].includes(source.tournamentTier)
      ? (source.tournamentTier as ThornsInput['tournamentTier'])
      : defaults.tournamentTier

    const normalized: ThornsInput = {
      baseThorns: clampNumber(source.baseThorns, 0, 600, defaults.baseThorns),
      wallThorns: clampNumber(source.wallThorns, 1, 20, defaults.wallThorns),
      tier: clampNumber(source.tier, 1, 24, defaults.tier),
      plasmaCannonLevel: clampNumber(source.plasmaCannonLevel, 0, 7, 0),
      plasmaCannonMasteryLevel: clampNumber(source.plasmaCannonMasteryLevel, 0, 9, 0),
      bcLabLevel: clampNumber(source.bcLabLevel, 0, 10, 0),
      thornsBcReductionLabLevel: clampNumber(source.thornsBcReductionLabLevel, 0, 20, 0),
      plasmaCannonBcReductionLabLevel: clampNumber(source.plasmaCannonBcReductionLabLevel, 0, 20, 0),
      sharpFortitude: source.sharpFortitude === true,
      tournamentTier,
      heatWave: clampNumber(source.heatWave, 0, 1000, 0),
    }

    /* The model enforces the mastery/level pairing; take its answer rather than a second copy. */
    const settled = normalizeThornsInput(toModel(normalized))
    normalized.plasmaCannonLevel = settled.pcLevel
    normalized.plasmaCannonMasteryLevel = settled.pcMasteryLevel
    return normalized
  },

  compute(rawInput = {}) {
    const input = this.normalize(rawInput)
    /* What the caller asked for, read safely — the mastery note compares it against the clamp. */
    const asked = safeRecord(rawInput) as Partial<ThornsInput>
    const notes: string[] = []

    const model = toModel(input)
    const byWallThorns = buildThornsWallChart(model)
    const atWallThorns
      = byWallThorns.find(row => row.wallThorns === input.wallThorns) ?? byWallThorns[0]

    if (input.tournamentTier !== 'none' && input.heatWave === 0) {
      notes.push('Tournament effectiveness is read from the heat wave, which is 0 — set the wave you are on.')
    }
    if (input.tournamentTier === 'none' && input.heatWave > 0) {
      notes.push('Heat (Wave) only applies to a tournament run, so it is being ignored here.')
    }
    const masteryAsked = clampNumber(asked.plasmaCannonMasteryLevel, 0, 9, 0)
    if (input.plasmaCannonLevel === 0 && masteryAsked > 0) {
      notes.push('Plasma Cannon mastery needs Plasma Cannon at level 7, so it is not being applied.')
    }

    return {
      atWallThorns,
      byWallThorns,
      byBaseThorns: buildThornsBaseChart(model),
      notes,
    }
  },
}
