/**
 * The shape every calculator builder shares.
 *
 * A builder is the plumbing between "what the player has" and "what to show", so building a tool on
 * this package is a UI job rather than a maths job. Each one carries `defaults` (a complete valid
 * input), `fields` (enough to render the form), `compute` (pure and total), and `notes` on the
 * result saying what it could not do.
 *
 * `compute` takes a `Partial` on purpose: a form hands you half-filled state constantly, so every
 * builder normalises first rather than throwing or returning `NaN`. Nothing here does I/O, reads a
 * clock, or touches the DOM, so a builder runs identically in a browser, in Node, and in a worker.
 */
/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    CalculatorField, CalculatorResultBase, CalculatorBuilder, MAX_INPUT_MAGNITUDE, MAX_MODEL_WAVE, clampLevel, clampMagnitude, costIndexForLevel (+43 more)
 * depends    src/mechanics
 * used by    src/builders/assist-module-stones, src/builders/bot-upgrade, src/builders/coins-per-kill, src/builders/damage-reduction, src/builders/dissonance, src/builders/enemy-drops (+10 more)
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
import type { DissonanceType, ModuleShatterRarity, ThornsCalculatorInput, ThornsWallChartRow } from '../mechanics'

/** A single input, described well enough to render a control for it. */
export interface CalculatorField {
  /** Key on the input object. */
  readonly key: string
  readonly label: string
  /**
   * `number-list` is a variable-length row of numbers — one per tier, one per slot — for the cases
   * where collapsing the row to a single total is wrong because the per-entry contribution is non-linear.
   */
  readonly kind: 'number' | 'select' | 'boolean' | 'number-list'
  /** `coins`, `stones`, `seconds`, `percent`, `waves`… — for a suffix or a formatter. */
  readonly unit?: string
  readonly min?: number
  readonly max?: number
  /** Present for `select`. */
  readonly options?: readonly { readonly value: string | number, readonly label: string }[]
  /** One line a tooltip can use. */
  readonly help?: string
}

/**
 * Every result carries `notes`. A calculator that cannot answer must say so rather than return a
 * confident zero — an unknown lab, a locked weapon — so the number and the reason travel together
 * and a UI never has to guess which zeros are real.
 */
export interface CalculatorResultBase {
  readonly notes: readonly string[]
}

export interface CalculatorBuilder<TInput, TResult extends CalculatorResultBase> {
  /** Stable id, dotted, safe as a key or a route segment. */
  readonly id: string
  readonly title: string
  /** One sentence: what question this answers. */
  readonly summary: string
  readonly fields: readonly CalculatorField[]
  readonly defaults: TInput
  /** Fill in what is missing and clamp what is out of range. Never throws. */
  normalize(input?: Partial<TInput>): TInput
  /** Normalises, then computes. Never throws. */
  compute(input?: Partial<TInput>): TResult
}

/**
 * The largest magnitude an open-ended numeric input is allowed to take.
 *
 * Some inputs have no catalog cap — a wave, a damage figure, a multiplier — and clamping those to
 * `Number.MAX_SAFE_INTEGER` does not stop a formula that squares them from reaching `Infinity`/`NaN`
 * with nothing to say which input caused it. 1e12 is past any real figure and short of overflow.
 */
export const MAX_INPUT_MAGNITUDE = 1e12

/**
 * The highest wave the enemy-scaling model can still answer for.
 *
 * The game does not cap waves (tower-oracle `enemy.waveScaling`: "wave 1 upward"), so this bounds
 * the model, not the game. Base health is a banded polynomial raised to a tier exponent and
 * overflows to `Infinity` before wave 1,000,000; 100,000 keeps every answer a real number.
 */
export const MAX_MODEL_WAVE = 100_000

/**
 * A level, as a whole number between 0 and this ladder's cap.
 *
 * Every ladder caps at what its own catalog prices, not a shared constant — the curves differ in
 * length (workshop Attack Speed stops at 75 where Damage runs to 400) — so the cap is derived per
 * stat and a builder cannot quote a price for a level that does not exist.
 */
export function clampLevel(value: unknown, cap: number, fallback: number): number {
  const safeCap = Number.isFinite(cap) && cap > 0 ? Math.floor(cap) : 0
  return Math.floor(clampNumber(value, 0, safeCap, Math.min(fallback, safeCap)))
}

/**
 * An open-ended quantity — a wave, a damage figure, a multiplier — bounded so that whatever
 * is computed from it stays finite. See `MAX_INPUT_MAGNITUDE`.
 */
export function clampMagnitude(value: unknown, fallback: number, min = 0): number {
  return clampNumber(value, min, MAX_INPUT_MAGNITUDE, fallback)
}

/**
 * The index in a cost table that prices buying `level`.
 *
 * Levels are 1-based and cost tables 0-based; tower-oracle `workshop.upgradeTable` records that a
 * row's cost buys the **next** level, so reading a row as "what this level cost" is off by one.
 */
export function costIndexForLevel(level: number): number {
  return Math.max(0, Math.floor(level) - 1)
}

/**
 * Whatever arrived, as a plain object this package can read safely.
 *
 * Accepts only a real object (`null` and primitives return `{}`), copies own enumerable keys one
 * at a time, and swallows any whose getter throws — reading someone else's object runs their code.
 * Own keys only, so `__proto__` and `constructor` arrive as ordinary absent properties.
 */
export function safeRecord(input: unknown): Record<string, unknown> {
  if (input === null || typeof input !== 'object') return {}

  const out: Record<string, unknown> = Object.create(null)
  for (const key of Object.keys(input)) {
    try {
      out[key] = (input as Record<string, unknown>)[key]
    }
    catch {
      /* A getter that throws has no value to offer; treat the property as absent. */
    }
  }
  return out
}

/**
 * Clamp helper shared by the builders; keeps `NaN` out of every downstream formula.
 *
 * Only a finite number, or a string that trims and parses as one, is accepted; everything else
 * falls back, because `Number()` coerces far too willingly to be safe on form state (`Number('')`
 * and `Number([])` are both `0`). It never throws — no coercion into unvetted `valueOf`/`toString`.
 */
export function clampNumber(value: unknown, min: number, max: number, fallback: number): number {
  let numeric: number
  if (typeof value === 'number') numeric = value
  else if (typeof value === 'string') {
    const trimmed = value.trim()
    numeric = trimmed === '' ? Number.NaN : Number(trimmed)
  }
  else return fallback

  if (!Number.isFinite(numeric)) return fallback
  return Math.min(max, Math.max(min, numeric))
}

/**
 * Coerce anything a form hands over into a fixed-length row of numbers.
 *
 * A `number-list` control produces sparse and stringy arrays constantly, so each entry falls back
 * independently — one bad cell (a cleared box, an untouched row) cannot blank the whole row.
 */
export function clampNumberList(
  value: unknown,
  length: number,
  min: number,
  max: number,
  fallback: number,
): number[] {
  const source = Array.isArray(value) ? value : []
  return Array.from({ length }, (_, i) => clampNumber(source[i], min, max, fallback))
}

/** Build a `select`'s options from a list of labels. */
export function optionsFrom(values: readonly string[]): CalculatorField['options'] {
  return values.map(value => ({ value, label: value }))
}

/* ── per-calculator input and result shapes ─────────────────────────────────────
 * Each builder's own `*Input` / `*Result` pair, kept beside the shared `CalculatorBuilder`
 * contract so the module next door can name a shape instead of re-declaring it.
 */

export interface AssistModuleStonesInput {
  currentLevel: number
  targetLevel: number
}

export interface AssistModuleStonesResult extends CalculatorResultBase {
  readonly levels: readonly { readonly level: number, readonly stoneCost: number }[]
  readonly totalStones: number
  readonly maxLevel: number
}
export interface BotUpgradeInput {
  bot: string
  stat: string
  currentLevel: number
  targetLevel: number
}

export interface BotUpgradeLevel {
  readonly level: number
  readonly medalCost: number
  readonly value: unknown
}

export interface BotUpgradeResult extends CalculatorResultBase {
  readonly bot: string
  readonly stat: string
  readonly levels: readonly BotUpgradeLevel[]
  readonly totalMedals: number
  readonly maxLevel: number
  readonly statsForBot: readonly string[]
}

export interface CoinsPerKillInputs {
  workshopLevel: number
  labLevel: number
  enhancementLevel: number
  primarySubstat: number
  assistSubstat: number
  hasCoinPerk: boolean
  hasCoinTradeOffPerk: boolean
  standardPerksBonusLabLevel: number
  improveTradeOffPerksLabLevel: number
  vaultPercent: number
}

export interface CoinsPerKillResult extends CalculatorResultBase {
  readonly coinsPerKill: number
  readonly workshopValue: number
}

export interface DamageReductionInput {
  rawDamage: number

  useDefensePercent: boolean
  defensePercent: number

  useDefenseAbsolute: boolean
  defenseAbsolute: number

  useChronoField: boolean
  chronoReductionPercent: number

  useFlameBot: boolean
  flameBotReductionPercent: number

  useNmp: boolean
  nmpReductionPercent: number

  usePrimordialCollapse: boolean
  primordialCollapseReductionPercent: number

  useChainThunder: boolean
  chainThunderReductionPercent: number
}

export interface DamageReductionLayer {
  readonly key: string
  readonly reductionPercent: number
  readonly remaining: number
}

export interface DamageReductionResult extends CalculatorResultBase {
  readonly finalDamage: number
  readonly totalReduction: number
  readonly layers: readonly DamageReductionLayer[]
}

export interface DissonanceInputs {
  type: DissonanceType
  tier: number
  tierPersonalBests: number[]
  echoLevel: number
}

export interface DissonanceResult extends CalculatorResultBase {
  readonly boost: number
  readonly bonusPercent: number
  readonly currentTierBoost: number
  readonly echoContribution: number
  readonly cappedTiers: readonly number[]
}

export interface EnemyDropsInputs {
  tier: number
  commonDropLabLevel: number
  rareDropLabLevel: number
  rerollShardsLabLevel: number
  shatterShardsLabLevel: number
  deathWaveCellsBonusLevel: number
  shatterRarity: ModuleShatterRarity
}

export interface EnemyDropsResult extends CalculatorResultBase {
  readonly commonDropChance: number
  readonly rareDropChance: number
  readonly rerollShardsPerBoss: number
  readonly expectedRerollShardsPerBoss: number
  readonly rerollShardsTierBase: number
  readonly shatterShards: number
  readonly deathWaveCellsBonus: number
  readonly rerollShardsDeadLevels: number
  readonly shatterShardsDeadLevels: number
}

export const ENEMY_WAVE_TYPES = [
  'Basic',
  'Fast',
  'Tank',
  'Ranged',
  'Boss',
  'Protector',
  'Scatter',
  'Ray',
  'Saboteur',
  'Commander',
  'Overcharge',
  'Vampire',
] as const

export type EnemyWaveType = (typeof ENEMY_WAVE_TYPES)[number]

export interface EnemyWaveInput {
  tier: number
  wave: number
  tournament: boolean
}

export interface EnemyWaveRow {
  readonly type: string
  readonly health: number
  readonly damage: number
}

export interface EnemyWaveResult extends CalculatorResultBase {
  readonly baseHealth: number
  readonly baseDamage: number
  readonly rows: readonly EnemyWaveRow[]
}

export interface GuardianInput {
  guardian: string
  stat: string
  currentLevel: number
  targetLevel: number
}

export interface GuardianLevel {
  readonly level: number
  readonly bitCost: number
  readonly value: string | number | null
}

export interface GuardianResult extends CalculatorResultBase {
  readonly guardian: string
  readonly stat: string
  readonly levels: readonly GuardianLevel[]
  readonly totalBits: number
  readonly maxLevel: number
  readonly statsForGuardian: readonly string[]
}

export interface InnerLandMinesInputs {
  damageLevel: number
  quantityLevel: number
  cooldownLevel: number
  chargedMinesLevel: number
  chargedMinesActive: boolean
  chronoJumpLabLevel: number
  timesHitByIlm: number
  mineAgeSeconds: number
}

export interface InnerLandMinesResult extends CalculatorResultBase {
  readonly damageMultiplier: number
  readonly mineCount: number
  readonly cooldownSeconds: number
  readonly charge: number
  readonly maxCharge: number
  readonly effectiveDamageMultiplier: number
  readonly damageMultiplierPerSecond: number
  readonly chargedRatePerSecond: number
  readonly chronoJumpBenefit: number
  readonly mineLifetimeSeconds: number
}

export interface LabResearchInput {
  labName: string
  currentLevel: number
  targetLevel: number
  coinDiscountPercent: number
  labSpeedPercent: number
}

export interface LabResearchLevel {
  readonly level: number
  readonly coinCost: number
  readonly hours: number
}

export interface LabResearchResult extends CalculatorResultBase {
  readonly labName: string
  readonly levels: readonly LabResearchLevel[]
  readonly totalCoinCost: number
  readonly totalHours: number
  readonly maxLevel: number
}

export interface ModuleCostInput {
  rarity: string
  currentLevel: number
  targetLevel: number
  shardDiscountPercent: number
  coinDiscountPercent: number
}

export interface ModuleCostLevel {
  readonly level: number
  readonly shardCost: number
  readonly coinCost: number
  readonly cumulativeShards: number
  readonly cumulativeCoins: number
}

export interface ModuleCostResult extends CalculatorResultBase {
  readonly levels: readonly ModuleCostLevel[]
  readonly totalShards: number
  readonly totalCoins: number
  readonly levelCap: number
}

export interface ThornsInput {
  baseThorns: number
  wallThorns: number
  tier: number
  plasmaCannonLevel: number
  plasmaCannonMasteryLevel: number
  bcLabLevel: number
  thornsBcReductionLabLevel: number
  plasmaCannonBcReductionLabLevel: number
  sharpFortitude: boolean
  tournamentTier: ThornsCalculatorInput['tournamentTier']
  heatWave: number
}

export interface ThornsResult extends CalculatorResultBase {
  readonly atWallThorns: ThornsWallChartRow
  readonly byWallThorns: readonly ThornsWallChartRow[]
  readonly byBaseThorns: readonly { readonly baseThornsVal: number, readonly hitsToKillElite: number }[]
}

export interface UltimateWeaponInput {
  weapon: string
  stat: string
  currentLevel: number
  targetLevel: number
}

export interface UltimateWeaponResult extends CalculatorResultBase {
  readonly weapon: string
  readonly stat: string
  readonly levels: readonly { readonly level: number, readonly stoneCost: number }[]
  readonly totalStones: number
  readonly maxLevel: number
  readonly statsForWeapon: readonly string[]
}

export interface UptimeInput {
  durationSeconds: number
  cooldownSeconds: number
}

export interface UptimeResult extends CalculatorResultBase {
  readonly ratio: number
  readonly percent: number
  readonly permanent: boolean
  readonly downtimeSeconds: number
}

export interface WorkshopUpgradeInput {
  costKey: string
  currentLevel: number
  targetLevel: number
  sectionDiscountPercent: number
  vaultDiscountPercent: number
}

export interface WorkshopUpgradeLevel {
  readonly level: number
  readonly baseCost: number
  readonly discountedCost: number
  readonly cumulativeCost: number
  readonly bonusMultiplier: number
}

export interface WorkshopUpgradeResult extends CalculatorResultBase {
  readonly levels: readonly WorkshopUpgradeLevel[]
  readonly totalCost: number
  readonly appliedDiscountPercent: number
}
