/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    SharedLabsSettings, sharedLabsSettingsSchema, defaultSharedLabsSettings, SharedLabLevelRange, sharedLabLevelRangeSchema, normalizeSharedLabsSettings, normalizeSharedLabLevelRange, coerceLabsTrackerLabLevel (+5 more)
 * depends    src/data/labs, src/data/labs-research
 * used by    src/internal/shared-tool-inputs, src/internal/shared-tool-inputs-from-research, src/mechanics/calculators/specs-generated, src/mechanics/enemy-drops-context, src/save/labs
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
import { z } from 'zod'
import {
  findLabResearchByDisplayName,
  findLabResearchByIndex,
  findLabResearchBySlug,
} from '../data/labs-research'
import { isLabsTrackerResearchLabName } from '../data/labs'

export interface SharedLabsSettings {
  labSpeed: number
  labRelic: number
  labDiscount: number
  gemDiscount: number
  speedUp: number
}

export const sharedLabsSettingsSchema = z.object({
  labSpeed: z.number(),
  labRelic: z.number(),
  labDiscount: z.number(),
  gemDiscount: z.number(),
  speedUp: z.number(),
})

export const defaultSharedLabsSettings: Readonly<SharedLabsSettings> = {
  labSpeed: 0,
  labRelic: 0,
  labDiscount: 0,
  gemDiscount: 0,
  speedUp: 1,
}

export interface SharedLabLevelRange {
  startLevel: number
  targetLevel: number
}

export const sharedLabLevelRangeSchema = z.object({
  startLevel: z.number(),
  targetLevel: z.number(),
})

function normalizeNumber(value: unknown, fallback: number): number {
  const parsed = Number(value)
  return Number.isFinite(parsed) ? parsed : fallback
}

export function normalizeSharedLabsSettings(value: unknown): SharedLabsSettings {
  if (!value || typeof value !== 'object') {
    return { ...defaultSharedLabsSettings }
  }

  const source = value as Record<string, unknown>
  return {
    labSpeed: Math.max(0, Math.floor(normalizeNumber(source.labSpeed, defaultSharedLabsSettings.labSpeed))),
    labRelic: Math.max(0, normalizeNumber(source.labRelic, defaultSharedLabsSettings.labRelic)),
    labDiscount: Math.max(0, Math.floor(normalizeNumber(source.labDiscount, defaultSharedLabsSettings.labDiscount))),
    gemDiscount: normalizeNumber(source.gemDiscount, defaultSharedLabsSettings.gemDiscount),
    speedUp: Math.max(1, normalizeNumber(source.speedUp, defaultSharedLabsSettings.speedUp)),
  }
}

export function normalizeSharedLabLevelRange(value: unknown): SharedLabLevelRange {
  if (!value || typeof value !== 'object') {
    return { startLevel: 0, targetLevel: 0 }
  }

  const source = value as Record<string, unknown>
  const startLevel = Math.max(0, Math.floor(normalizeNumber(source.startLevel, 0)))
  const targetLevel = Math.max(startLevel, Math.floor(normalizeNumber(source.targetLevel, startLevel)))
  return { startLevel, targetLevel }
}

/** Coerce legacy/corrupt lab level map values (e.g. `{ current, target }`) to integers. */
export function coerceLabsTrackerLabLevel(value: unknown): number | undefined {
  if (typeof value === 'number' && Number.isFinite(value)) {
    return Math.max(0, Math.floor(value))
  }
  if (typeof value === 'string' && value.trim().length > 0) {
    const parsed = Number(value)
    if (Number.isFinite(parsed)) return Math.max(0, Math.floor(parsed))
  }
  if (value && typeof value === 'object') {
    const source = value as Record<string, unknown>
    for (const key of ['current', 'currentLevel', 'level'] as const) {
      const candidate = source[key]
      if (typeof candidate === 'number' && Number.isFinite(candidate)) {
        return Math.max(0, Math.floor(candidate))
      }
    }
  }
  return undefined
}

/** Resolve any persisted lab key (slug, display name, or malformed legacy key) to a catalog slug. */
export function findCanonicalLabResearchSlug(key: string | null | undefined): string | null {
  const trimmed = String(key || '').trim()
  if (!trimmed) return null

  const bySlug = findLabResearchBySlug(trimmed)
  if (bySlug?.slug) return bySlug.slug

  const byDisplay = findLabResearchByDisplayName(trimmed)
  if (byDisplay?.slug) return byDisplay.slug

  if (/AssetsTools\.NET/i.test(trimmed)) {
    return findLabResearchByIndex(0)?.slug ?? null
  }

  return isLabsTrackerResearchLabName(trimmed) ? trimmed : null
}

/** Canonical research lab level map — keys are catalog slugs only; values are non-negative integers. */
export function normalizeLabsTrackerLabLevelMap(
  input: Record<string, unknown> | null | undefined,
): Record<string, number> {
  if (!input || typeof input !== 'object') return {}
  const out: Record<string, number> = {}
  for (const [key, raw] of Object.entries(input)) {
    if (!key.trim()) continue
    const slug = findCanonicalLabResearchSlug(key)
    if (!slug) continue
    const level = coerceLabsTrackerLabLevel(raw)
    if (level === undefined) continue
    out[slug] = Math.max(out[slug] ?? 0, level)
  }
  return out
}

export function labsTrackerLabLevelMapsEqual(
  left: Record<string, unknown> | null | undefined,
  right: Record<string, unknown> | null | undefined,
): boolean {
  const normalizedLeft = normalizeLabsTrackerLabLevelMap(left)
  const normalizedRight = normalizeLabsTrackerLabLevelMap(right)
  const leftKeys = Object.keys(normalizedLeft)
  const rightKeys = Object.keys(normalizedRight)
  if (leftKeys.length !== rightKeys.length) return false
  return leftKeys.every(key => normalizedLeft[key] === normalizedRight[key])
}

/** Merge hub + tracker lab levels into one slug-keyed map (same shape everywhere). */
export function buildTrackerCurrentLabLevels(
  hubLevels: Record<string, unknown> | null | undefined,
  existing: Record<string, number> = {},
): Record<string, number> {
  return normalizeLabsTrackerLabLevelMap({
    ...existing,
    ...(hubLevels ?? {}),
  })
}

/** Hub persistence uses the same slug-keyed map as the tracker store. */
export function buildResearchHubLevels(
  trackerLevels: Record<string, unknown> | null | undefined,
): Record<string, number> {
  return normalizeLabsTrackerLabLevelMap(trackerLevels)
}
