/**
 * Record lookups that cannot return a prototype member.
 *
 * Keys reach this package from saves, from the community sheet, from URLs and from tool
 * input, and none of those are ours to trust. Plain `record[key]` walks the prototype
 * chain, so `record['constructor']` is the `Object` function, `record['toString']` is a
 * function, and `record['__proto__']` is `Object.prototype` — all from lookups whose
 * signatures promise a string, a number, or `undefined`.
 *
 * That failure is quiet in the worst way: `??` and `||` do not catch a function, so the
 * fallback never fires and the wrong value travels on as if it were data.
 *
 * `Object.prototype.hasOwnProperty.call` rather than `Object.hasOwn`, which is ES2022 —
 * this package targets ES2020.
 */
/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    ownLookup, ownLookupOr, hasOwnKey, atIndex
 * depends    —
 * used by    src/bot/calculator-command, src/bot/create-bot, src/charts/chart-data-lookup, src/data/labs-categories, src/data/labs-display-overrides, src/data/labs-unlocks (+27 more)
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */

/** The value at `key`, or `undefined` when the record has no such own key. */
export function ownLookup<TValue>(
  record: Readonly<Record<PropertyKey, TValue>>,
  key: PropertyKey,
): TValue | undefined {
  return Object.prototype.hasOwnProperty.call(record, key) ? record[key] : undefined
}

/** The value at `key`, or `fallback` when the record has no such own key. */
export function ownLookupOr<TValue>(
  record: Readonly<Record<PropertyKey, TValue>>,
  key: PropertyKey,
  fallback: TValue,
): TValue {
  return Object.prototype.hasOwnProperty.call(record, key) ? record[key] : fallback
}

/** Whether the record itself defines `key`, ignoring anything inherited. */
export function hasOwnKey(record: object, key: PropertyKey): boolean {
  return Object.prototype.hasOwnProperty.call(record, key)
}

/**
 * The element at `index`, or `undefined` when the index is not a real position.
 *
 * The array counterpart of `ownLookup`. A numeric parameter type is a compile-time promise,
 * not a runtime one: indices reach this package from saves and from parsed grids, where a
 * value can arrive fractional, negative, or as a string. `list[1.5]` and `list['constructor']`
 * both miss the elements and reach for a property instead — the second one successfully.
 */
export function atIndex<TValue>(list: readonly TValue[], index: number): TValue | undefined {
  if (!Number.isInteger(index) || index < 0 || index >= list.length) return undefined
  return list[index]
}
