/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    buildUptimeCoreStateFromRecord
 * depends    src/mechanics/uptime-core
 * used by    src/internal/shared-uptime-inputs, src/mechanics/calculators/specs-generated
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
import {
  type Compressor,
  type MVNMode,
  type RarityPick,
  type UptimeCoreState,
} from '../mechanics/uptime-core'

function clampBotCdLevel(level: number | null | undefined): number | null {
  if (level == null) return null
  const num = Number(level)
  if (!Number.isFinite(num)) return null
  return Math.min(15, Math.max(0, Math.floor(num)))
}

function normalizeCompressor(value: unknown): Compressor {
  const allowed: Compressor[] = ['Disabled', 'Epic', 'Legendary', 'Mythic', 'Ancestral']
  if (value === 'None') return 'Disabled'
  return allowed.includes(value as Compressor) ? value as Compressor : 'Disabled'
}

function normalizeMvnRarity(saved: Record<string, unknown>): MVNMode {
  const requested = saved['mvnRarity']
  const enabled = Boolean(saved['mvnEnabled'] ?? (requested && requested !== 'Disabled'))
  if (!enabled) return 'Disabled'
  const allowed: MVNMode[] = ['Disabled', 'Epic', 'Legendary', 'Mythic', 'Ancestral']
  return allowed.includes(requested as MVNMode) && requested !== 'Disabled'
    ? requested as MVNMode
    : 'Epic'
}

function toNumber(value: unknown, fallback: number): number {
  const parsed = Number(value)
  return Number.isFinite(parsed) ? parsed : fallback
}

function toNullableNumber(value: unknown): number | null {
  if (value == null) return null
  const parsed = Number(value)
  return Number.isFinite(parsed) ? parsed : null
}

function toRarity(value: unknown): RarityPick {
  const allowed: RarityPick[] = ['None', 'Rare', 'Epic', 'Legendary', 'Mythic', 'Ancestral']
  return allowed.includes(value as RarityPick) ? value as RarityPick : 'None'
}

/** Build uptime core state from a flat calculator data record (uptime store `data` shape). */
export function buildUptimeCoreStateFromRecord(saved: Record<string, unknown>): UptimeCoreState {
  return {
    mvnRarity: normalizeMvnRarity(saved),
    mvnGt: Boolean(saved['mvnGt'] ?? false),
    mvnDw: Boolean(saved['mvnDw'] ?? false),
    mvnBh: Boolean(saved['mvnBh'] ?? false),
    gtCdLevel: toNullableNumber(saved['gtCdLevel']),
    gtCdStat: toRarity(saved['gtCdStat']),
    gtCdAssist: toRarity(saved['gtCdAssist']),
    dwCdLevel: toNullableNumber(saved['dwCdLevel']),
    dwCdStat: toRarity(saved['dwCdStat']),
    dwCdAssist: toRarity(saved['dwCdAssist']),
    bhCdLevel: toNullableNumber(saved['bhCdLevel']),
    bhCdStat: toRarity(saved['bhCdStat']),
    bhCdAssist: toRarity(saved['bhCdAssist']),
    psCdLevel: toNullableNumber(saved['psCdLevel']),
    psCdStat: toRarity(saved['psCdStat']),
    psCdAssist: toRarity(saved['psCdAssist']),
    cfCdLevel: toNullableNumber(saved['cfCdLevel']),
    cfCdStat: toRarity(saved['cfCdStat']),
    cfCdAssist: toRarity(saved['cfCdAssist']),
    smCdLevel: toNullableNumber(saved['smCdLevel']),
    smCdStat: toRarity(saved['smCdStat']),
    smCdAssist: toRarity(saved['smCdAssist']),
    ilmCdLevel: toNullableNumber(saved['ilmCdLevel']),
    ilmCdStat: toRarity(saved['ilmCdStat']),
    ilmCdAssist: toRarity(saved['ilmCdAssist']),
    wavesPerBoss: toNumber(saved['wavesPerBoss'], 5),
    compressor: normalizeCompressor(saved['compressor']),
    waLevel: toNumber(saved['waLevel'], 0),
    dwBaseWavesLevel: Math.max(1, toNumber(saved['dwBaseWavesLevel'], 1)),
    pkgChance: toNumber(saved['pkgChance'], 0),
    gtDurLab: toNumber(saved['gtDurLab'], 0),
    cfDurLab: toNumber(saved['cfDurLab'], 0),
    gtDurLevel: toNullableNumber(saved['gtDurLevel']),
    gtDurStat: toRarity(saved['gtDurStat']),
    gtDurAssist: toRarity(saved['gtDurAssist']),
    bhDurLevel: toNullableNumber(saved['bhDurLevel']),
    bhDurStat: toRarity(saved['bhDurStat']),
    bhDurAssist: toRarity(saved['bhDurAssist']),
    psDurLevel: toNullableNumber(saved['psDurLevel']),
    psDurStat: toRarity(saved['psDurStat']),
    psDurAssist: toRarity(saved['psDurAssist']),
    cfDurLevel: toNullableNumber(saved['cfDurLevel']),
    cfDurStat: toRarity(saved['cfDurStat']),
    cfDurAssist: toRarity(saved['cfDurAssist']),
    smQtyLevel: toNullableNumber(saved['smQtyLevel']),
    smQtyStat: toRarity(saved['smQtyStat']),
    smQtyAssist: toRarity(saved['smQtyAssist']),
    slAngleLevel: toNullableNumber(saved['slAngleLevel']),
    slAngleStat: toRarity(saved['slAngleStat']),
    slAngleAssist: toRarity(saved['slAngleAssist']),
    slQtyLevel: toNullableNumber(saved['slQtyLevel']),
    gbCdLevel: clampBotCdLevel(toNullableNumber(saved['gbCdLevel'])),
    gbDurLevel: toNullableNumber(saved['gbDurLevel']),
    gbCdLab: toNumber(saved['gbCdLab'], 0),
    gbDurLab: toNumber(saved['gbDurLab'], 0),
    abCdLevel: clampBotCdLevel(toNullableNumber(saved['abCdLevel'])),
    abDurLevel: toNullableNumber(saved['abDurLevel']),
    abCdLab: toNumber(saved['abCdLab'], 0),
    abDurLab: toNumber(saved['abDurLab'], 0),
    bbCdLevel: clampBotCdLevel(toNullableNumber(saved['bbCdLevel'])),
    bbDurLevel: toNullableNumber(saved['bbDurLevel']),
    bbCdLab: toNumber(saved['bbCdLab'], 0),
    bbDurLab: toNumber(saved['bbDurLab'], 0),
    fbCdLevel: clampBotCdLevel(toNullableNumber(saved['fbCdLevel'])),
    fbDurLevel: toNullableNumber(saved['fbDurLevel']),
    fbCdLab: toNumber(saved['fbCdLab'], 0),
    tbCdLevel: clampBotCdLevel(toNullableNumber(saved['tbCdLevel'])),
    tbDurLevel: toNullableNumber(saved['tbDurLevel']),
    tbCdLab: toNumber(saved['tbCdLab'], 0),
    dwQtyStat: toRarity(saved['dwQtyStat']),
    dwQtyAssist: toRarity(saved['dwQtyAssist']),
    assistEffPct: toNumber(saved['assistEffPct'] ?? saved['cdAssistEffPct'] ?? saved['durAssistEffPct'], 0),
    tournament: Boolean(saved['tournament'] ?? false),
    bhPerk: Boolean(saved['bhPerk'] ?? false),
    cfDurPerk: Boolean(saved['cfDurPerk'] ?? false),
    dwPerk: Boolean(saved['dwPerk'] ?? false),
    smQtyPerk: Boolean(saved['smQtyPerk'] ?? false),
    uwBc: Boolean(saved['uwBc'] ?? false),
    bcLabLevel: toNumber(saved['bcLabLevel'], 0),
    summonCooldownLevel: toNullableNumber(saved['summonCooldownLevel'] ?? saved['summonLevel'] ?? 1),
    summonDurationLevel: toNullableNumber(saved['summonDurationLevel'] ?? saved['summonLevel'] ?? 1),
    attackCooldownLevel: toNullableNumber(saved['attackCooldownLevel'] ?? 1),
    allyCooldownLevel: toNullableNumber(saved['allyCooldownLevel'] ?? 1),
    bountyCooldownLevel: toNullableNumber(saved['bountyCooldownLevel'] ?? 1),
    fetchCooldownLevel: toNullableNumber(saved['fetchCooldownLevel'] ?? 1),
    scoutCooldownLevel: toNullableNumber(saved['scoutCooldownLevel'] ?? 1),
    scoutDurationLevel: toNullableNumber(saved['scoutDurationLevel'] ?? 1),
  }
}
