/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    uptimeColumnsStateSchema, uptimeTableSettingsSchema, uptimeUiStateSchema, uptimePersistedPayloadSchema, UptimePersistedPayload, normalizeUptimePersistedPayload, uptimeLocalPersistenceSchema
 * depends    src/internal/local-persistence-types
 * used by    src/internal/shared-uptime-inputs, src/mechanics/calculators/specs-generated
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
import { z } from 'zod'
import { buildNormalizerPersistenceSchema } from './local-persistence-types'

const defaultTableSettings = {
  gtEnabled: true,
  bhEnabled: true,
  dwEnabled: true,
  psEnabled: true,
  cfEnabled: true,
  smEnabled: true,
  ilmEnabled: true,
  slEnabled: true,
  gbEnabled: true,
  abEnabled: true,
  bbEnabled: true,
  fbEnabled: true,
  tbEnabled: true,
  attackEnabled: true,
  allyEnabled: true,
  bountyEnabled: true,
  fetchEnabled: true,
  summonEnabled: true,
  scoutEnabled: true,
  dwKillWave: false,
  reorderRows: false,
}

export const uptimeColumnsStateSchema = z.object({
  order: z.array(z.string()).default([]),
  selected: z.array(z.string()).default([]),
})

export const uptimeTableSettingsSchema = z.object({
  gtEnabled: z.boolean().default(defaultTableSettings.gtEnabled),
  bhEnabled: z.boolean().default(defaultTableSettings.bhEnabled),
  dwEnabled: z.boolean().default(defaultTableSettings.dwEnabled),
  psEnabled: z.boolean().default(defaultTableSettings.psEnabled),
  cfEnabled: z.boolean().default(defaultTableSettings.cfEnabled),
  smEnabled: z.boolean().default(defaultTableSettings.smEnabled),
  ilmEnabled: z.boolean().default(defaultTableSettings.ilmEnabled),
  slEnabled: z.boolean().default(defaultTableSettings.slEnabled),
  gbEnabled: z.boolean().default(defaultTableSettings.gbEnabled),
  abEnabled: z.boolean().default(defaultTableSettings.abEnabled),
  bbEnabled: z.boolean().default(defaultTableSettings.bbEnabled),
  fbEnabled: z.boolean().default(defaultTableSettings.fbEnabled),
  tbEnabled: z.boolean().default(defaultTableSettings.tbEnabled),
  attackEnabled: z.boolean().default(defaultTableSettings.attackEnabled),
  allyEnabled: z.boolean().default(defaultTableSettings.allyEnabled),
  bountyEnabled: z.boolean().default(defaultTableSettings.bountyEnabled),
  fetchEnabled: z.boolean().default(defaultTableSettings.fetchEnabled),
  summonEnabled: z.boolean().default(defaultTableSettings.summonEnabled),
  scoutEnabled: z.boolean().default(defaultTableSettings.scoutEnabled),
  dwKillWave: z.boolean().default(defaultTableSettings.dwKillWave),
  reorderRows: z.boolean().default(defaultTableSettings.reorderRows),
})

export const uptimeUiStateSchema = z.object({
  panels: z.number().nullable().default(null),
  tableSettings: uptimeTableSettingsSchema.default(defaultTableSettings),
  rowOrder: z.array(z.string()).default([]),
})

export const uptimePersistedPayloadSchema = z.object({
  data: z.record(z.string(), z.unknown()).default({}),
  columns: uptimeColumnsStateSchema.default({ order: [], selected: [] }),
  ui: uptimeUiStateSchema.default({
    panels: null,
    tableSettings: defaultTableSettings,
    rowOrder: [],
  }),
})

export type UptimePersistedPayload = z.infer<typeof uptimePersistedPayloadSchema>

export function normalizeUptimePersistedPayload(value: unknown): UptimePersistedPayload {
  const parsed = uptimePersistedPayloadSchema.safeParse(value)
  if (parsed.success) {
    return parsed.data
  }
  return uptimePersistedPayloadSchema.parse({})
}

export const uptimeLocalPersistenceSchema = buildNormalizerPersistenceSchema(normalizeUptimePersistedPayload)
