/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    buildBattleReportStatFields, buildBattleReportExtendedFields, readBattleReportRawSaveValue, getBattleReportSaveKeysForTest, getBattleReportExtendedSaveKeysForTest
 * depends    src/formatting/tools/compute, src/save/battle/duration, src/save/runs/fields
 * used by    src/mechanics/calculators/specs-generated, src/save/battle/index, src/save/battle/report-extended, src/save/battle/reports
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
import { readDurationSecondsFromSave } from './duration'
import { RUN_EXTENDED_FIELDS, RUN_OPTIONAL_STRING_FIELDS } from '../runs/fields'
import { formatCompact } from '../../formatting/tools/compute'

type BattleReportStatField = (typeof RUN_OPTIONAL_STRING_FIELDS)[number]

const BATTLE_REPORT_SAVE_KEY_ALIASES: Partial<Record<BattleReportStatField, readonly string[]>> = {
  basic: ['totalBasic'],
  fast: ['totalFast'],
  tank: ['totalTank'],
  ranged: ['totalRanged'],
  boss: ['totalBoss'],
  protector: ['totalProtector'],
  vampires: ['totalVampire'],
  rays: ['totalRays'],
  scatters: ['totalScatters'],
  saboteurs: ['totalSaboteurs'],
  commanders: ['totalCommanders'],
  overcharges: ['totalOvercharges'],
  enemiesHitByOrbs: ['orbHits', 'orbHitsThisRound'],
  taggedByDeathWave: ['taggedByDeathwave', 'totalEnemiesTaggedByDeathwaveThisRound'],
  destroyedInSpotlight: ['enemiesDestroyedInSpotlightThisRound'],
  totalEnemies: ['totalEnemiesDestroyedThisRound'],
  freeAttackUpgrade: ['freeAttackUpgrades'],
  freeDefenseUpgrade: ['freeDefenseUpgrades'],
  freeUtilityUpgrade: ['freeUtilityUpgrades'],
  coinsFromBlackhole: ['coinsFromBlackHole'],
  destroyedInGoldenBot: ['destroyedInGoldenBot', 'enemiesKilledInGoldenBot', 'enemiesKilledInGoldenBotThisRound'],
  guardianSummonedEnemies: ['guardianSummoned', 'totalSummonedByGuardianThisRound', 'summonedEnemies'],
  killsWithGoldenTower: ['destroyedInGoldenTower', 'goldenTowerKills', 'killedWithGoldenTower'],
  enemiesHitByBlackHole: ['blackHoleHits', 'enemiesHitByBlackHoleThisRound'],
  killsWithAmplifyBot: ['destroyedInAmplifyBot', 'enemiesKilledInAmplifyBot', 'killedWithAmplifyBot'],
  coinsFetched: ['guardianCoinsFetched'],
  gemsFetched: ['guardianGems'],
  medalsFetched: ['guardianMedals'],
  rerollShardsFetched: ['guardianRerollShards'],
  cannonShardsFetched: ['guardianCannonShards'],
  armorShardsFetched: ['guardianArmorShards'],
  generatorShardsFetched: ['guardianGeneratorShards'],
  coreShardsFetched: ['guardianCoreShards'],
  commonModulesFetched: ['guardianCommonModules'],
  rareModulesFetched: ['guardianRareModules'],
  highestCoinsPerMinute: ['highestCPM'],
  nukeCount: ['nukesUsed'],
  secondWindCount: ['secondWindsUsed'],
  demonModeCount: ['demonModesUsed'],
  hitsAbsorbedByEnergyShield: ['energyShieldHitsAbsorbed'],
  enemyAttackLevelsSkipped: ['attackLevelSkips'],
  enemyHealthLevelsSkipped: ['healthLevelSkips'],
  coinsFromWaveSkip: ['coinsEarnedWaveSkip'],
  coinsPerWave: ['coinsEarnedCPW'],
  gemsEarned: ['gemsThisRound'],
  adGemsEarned: ['adGemsThisRound'],
  fetchGems: ['guardianGems'],
  medalsEarned: ['guardianMedals'],
  killsWithDeathPenalty: ['destroyedByDeathPenalty'],
  killsWithDeathWave: [
    // v29 BattleHistoryEntry field; older aliases kept for prior saves.
    'destroyedByDeathWave',
    'destroyedInDeathWave',
    'destroyedInDeathwave',
    'enemiesHitByDeathWaveThisRound',
    'enemiesHitByDeathwaveThisRound',
  ],
  killsWithBlackHole: ['destroyedInBlackhole', 'destroyedInBlackHole', 'killedWithBlackHole'],
  killsWithOrbs: ['destroyedInOrbs', 'killedWithOrbs'],
  coinsFromGoldenCombo: ['coinsFromGoldenTowerPlus'],
  criticalCoinCoins: ['coinsFromCritCoin'],
  largestInnerLandmineCharge: ['largestILMCharge'],
  negativeMassProjectorBlocked: ['magicOrbBlocked'],
  enemiesHitByLandMines: ['enemiesHitByLandMines', 'enemiesHitByLandMineThisRound'],
  healthFromRecoveryPackages: ['recoveryPackagesRegen', 'healthFromRecoveryPackages'],
  guardianCatches: ['guardianCatches'],
}

const COUNT_STAT_FIELDS = new Set<BattleReportStatField>([
  'deathDefy',
  'projectilesCount',
  'lifesteal',
  'enemiesHitByOrbs',
  'landMinesSpawned',
  'wavesSkipped',
  'recoveryPackages',
  'healthFromRecoveryPackages',
  'freeAttackUpgrade',
  'freeDefenseUpgrade',
  'freeUtilityUpgrade',
  'hpFromDeathWave',
  'gemBlocksTapped',
  'totalEnemies',
  'basic',
  'fast',
  'tank',
  'ranged',
  'boss',
  'protector',
  'totalElites',
  'vampires',
  'rays',
  'scatters',
  'saboteurs',
  'commanders',
  'overcharges',
  'destroyedByOrbs',
  'destroyedByThorns',
  'destroyedByDeathRay',
  'destroyedByLandMine',
  'destroyedInSpotlight',
  'thunderBotStuns',
  'destroyedInGoldenBot',
  'guardianSummonedEnemies',
  'guardianCatches',
  'gemsFetched',
  'medalsFetched',
  'rerollShardsFetched',
  'cannonShardsFetched',
  'armorShardsFetched',
  'generatorShardsFetched',
  'coreShardsFetched',
  'commonModulesFetched',
  'rareModulesFetched',
  'taggedByDeathWave',
  'nukeCount',
  'secondWindCount',
  'demonModeCount',
  'hitsAbsorbedByEnergyShield',
  'enemyAttackLevelsSkipped',
  'enemyHealthLevelsSkipped',
  'fetchGems',
  'medalsEarned',
  'adGemsEarned',
  'gemsEarned',
  'largestWaveSkip',
  'largestSmartMissileStack',
  'largestGoldenCombo',
  'killsWithGoldenTower',
  'killsWithDeathWave',
  'killsWithBlackHole',
  'killsWithOrbs',
  'killsWithAmplifyBot',
  'killsWithDeathPenalty',
  'destroyedByProjectiles',
  'destroyedByChainLightning',
  'destroyedBySmartMissiles',
  'destroyedByInnerLandMines',
  'destroyedByPoisonSwamp',
  'destroyedByBlackHole',
  'destroyedByFlameBot',
  'destroyedByOther',
  'enemiesHitByProjectiles',
  'enemiesHitByThorns',
  'enemiesHitByDeathRay',
  'enemiesHitByChainLightning',
  'enemiesHitBySmartMissiles',
  'enemiesHitByInnerLandMines',
  'enemiesHitByPoisonSwamp',
  'enemiesHitByBlackHole',
  'enemiesHitByChronoField',
  'enemiesHitByLandMines',
  'enemiesHitByThunderBot',
  'enemiesHitByFlameBot',
  'enemiesHitByAttackChip',
  'enemiesHitByOrbitalAugment',
])

function readNumber(raw: unknown): number | null {
  if (typeof raw === 'number' && Number.isFinite(raw)) return raw
  if (typeof raw === 'string' && raw.trim()) {
    const parsed = Number(raw.trim())
    if (Number.isFinite(parsed)) return parsed
  }
  return null
}

function compactBattleReportStat(value: unknown): string | null {
  if (value == null) return null
  if (typeof value === 'number' && Number.isFinite(value)) {
    return formatCompact(value).substring(0, 20)
  }
  const raw = String(value).trim()
  return raw.length > 0 ? raw.substring(0, 20) : null
}

function optionalCountField(value: unknown): string | null {
  if (value == null) return null
  const raw = String(value).trim()
  return raw.length > 0 ? raw.substring(0, 20) : null
}

function resolveBattleReportSaveKeys(targetField: string): readonly string[] {
  const aliases = BATTLE_REPORT_SAVE_KEY_ALIASES[targetField as BattleReportStatField]
  const keys = new Set<string>([targetField, ...(aliases ?? [])])
  if (targetField.startsWith('enemiesHitBy')) {
    keys.add(`${targetField}ThisRound`)
  }
  return [...keys]
}

function readBattleReportSaveValue(
  run: Record<string, unknown>,
  targetField: string,
): unknown {
  for (const saveKey of resolveBattleReportSaveKeys(targetField)) {
    if (!(saveKey in run)) continue
    const value = run[saveKey]
    if (value == null) continue
    if (typeof value === 'number' && Number.isFinite(value)) return value
    if (String(value).trim().length > 0) return value
  }
  return null
}

function formatBattleReportStatValue(
  targetField: BattleReportStatField,
  value: unknown,
): string | null {
  if (COUNT_STAT_FIELDS.has(targetField)) {
    return optionalCountField(value)
  }
  return compactBattleReportStat(value)
}

function computePerHourStat(
  run: Record<string, unknown>,
  amountKey: string,
): string | null {
  const seconds = readDurationSecondsFromSave(run.realTime)
  const amount = readNumber(run[amountKey])
  if (seconds == null || seconds <= 0 || amount == null || amount <= 0) return null
  return compactBattleReportStat(amount / (seconds / 3600))
}

function computeCoinsPerKill(run: Record<string, unknown>): string | null {
  const coins = readNumber(run.coinsEarned)
  const kills = readNumber(run.totalEnemies)
  if (coins == null || kills == null || kills <= 0 || coins <= 0) return null
  return compactBattleReportStat(coins / kills)
}

function inferZeroBattleReportStat(
  run: Record<string, unknown>,
  targetField: BattleReportStatField,
): string | null {
  if (targetField === 'bountyCoins' && !resolveBattleReportSaveKeys(targetField).some(key => key in run)) {
    return '0'
  }
  if (targetField === 'attackChipDamage') {
    const chipHits = readNumber(run.enemiesHitByAttackChipThisRound)
    if (chipHits === 0 && readBattleReportSaveValue(run, 'attackChipDamage') == null) {
      return '0'
    }
  }
  if (targetField === 'negativeMassProjectorBlocked') {
    const blocked = readNumber(run.magicOrbBlocked)
    if (blocked === 0 && readBattleReportSaveValue(run, 'negativeMassProjectorBlocked') == null) {
      return '0'
    }
  }
  if (targetField === 'largestInnerLandmineCharge') {
    const charge = readNumber(run.largestILMCharge)
    if (charge === 0 && readBattleReportSaveValue(run, 'largestInnerLandmineCharge') == null) {
      return '0'
    }
  }
  return null
}

function readDerivedBattleReportStat(
  run: Record<string, unknown>,
  targetField: BattleReportStatField,
): string | null {
  switch (targetField) {
    case 'coinsPerHour':
      return computePerHourStat(run, 'coinsEarned')
    case 'cellsPerHour':
      return computePerHourStat(run, 'cellsEarned')
    case 'rerollShardsPerHour':
      return computePerHourStat(run, 'rerollShardsEarned')
    case 'coinsPerKill':
      return computeCoinsPerKill(run)
    default:
      return null
  }
}

function readBattleReportStatValue(
  run: Record<string, unknown>,
  targetField: BattleReportStatField,
): string | null {
  const direct = readBattleReportSaveValue(run, targetField)
  if (direct != null) {
    return formatBattleReportStatValue(targetField, direct)
  }

  const derived = readDerivedBattleReportStat(run, targetField)
  if (derived != null) return derived

  return inferZeroBattleReportStat(run, targetField)
}

const BATTLE_REPORT_STAT_FIELDS = RUN_OPTIONAL_STRING_FIELDS.filter(
  key => key !== 'username' && key !== 'note',
)

/** Map save battle-history entry fields onto all optional run stat keys. */
export function buildBattleReportStatFields(
  run: Record<string, unknown>,
): Partial<Record<BattleReportStatField, string | null>> {
  const mapped: Partial<Record<BattleReportStatField, string | null>> = {}

  for (const targetField of BATTLE_REPORT_STAT_FIELDS) {
    const value = readBattleReportStatValue(run, targetField)
    if (value == null) continue
    mapped[targetField] = value
  }

  return mapped
}

/** Extended-only subset for runs_extended_data writes. */
export function buildBattleReportExtendedFields(
  run: Record<string, unknown>,
): Partial<Record<(typeof RUN_EXTENDED_FIELDS)[number], string | null>> {
  const all = buildBattleReportStatFields(run)
  const mapped: Partial<Record<(typeof RUN_EXTENDED_FIELDS)[number], string | null>> = {}

  for (const targetField of RUN_EXTENDED_FIELDS) {
    const value = all[targetField as BattleReportStatField]
    if (value != null) mapped[targetField] = value
  }

  return mapped
}

/** Read a raw save value for a progress field, including save-key aliases. */
export function readBattleReportRawSaveValue(
  run: Record<string, unknown>,
  targetField: string,
): unknown {
  return readBattleReportSaveValue(run, targetField)
}

export function getBattleReportSaveKeysForTest(targetField: string): readonly string[] {
  return resolveBattleReportSaveKeys(targetField)
}

export function getBattleReportExtendedSaveKeysForTest(targetField: string): readonly string[] {
  return resolveBattleReportSaveKeys(targetField)
}
