/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    LoadSdkGraphOptions, loadSdkGraph, loadSdkGraphWithTrust, filterSdkGraph, isEpFamily, applySdkGraphMutations, validateSdkGraph, renderSdkGraphMermaidSlices (+3 more)
 * depends    src/mechanics/ep-graph, src/mechanics/sdk-graph/build-index, src/mechanics/sdk-graph/data/sdk-graph.v1.json, src/mechanics/sdk-graph/invariants, src/mechanics/sdk-graph/merge, src/mechanics/sdk-graph/mutate (+5 more)
 * used by    —
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
import coreRaw from './data/sdk-graph.v1.json'
import { loadEpGraph } from '../ep-graph'
import { SdkGraphSchema, type SdkGraph } from './schema'
import { epGraphToSdkModule, mergeSdkGraphs } from './merge'
import { oracleGraphToSdkModule } from './oracle-module'
import { validateSdkGraph } from './validate'
import { applySdkGraphMutations } from './mutate'
import { renderSdkGraphMermaidSlices } from './render-mermaid'
import {
  buildSdkGraphIndex,
  buildSdkGraphContextPack,
  formatSdkGraphStatusReport,
} from './build-index'
import { sdkFamilyToEp } from './schema'
import { buildTrustReport, type TrustMode, type TrustReport } from './trust-report'

export * from './schema'
export * from './mutate'
export * from './validate'
export * from './merge'
export * from './render-mermaid'
export * from './build-index'
export * from './invariants'
export * from './trust-report'
export * from './oracle-module'

export interface LoadSdkGraphOptions {
  mode?: TrustMode
  /** Skip planner citation scan (unit tests / early bootstrap). */
  scanPlannerCitations?: boolean
  /** Skip Debug Graph cross-check (bootstrap). */
  checkDebugGraph?: boolean
}

function mergeCoreAndEp(): SdkGraph {
  const core = SdkGraphSchema.parse(coreRaw)
  const ep = loadEpGraph()
  const epMod = epGraphToSdkModule(ep)
  // The oracle joins as a third module. It is read-only here: mechanics
  // knowledge is written in `src/knowledge/compartments`, and this lifts a
  // projection so the trust and coverage layer can see it at all.
  const oracleMod = oracleGraphToSdkModule()
  const merged = mergeSdkGraphs(core, [
    { name: 'ep', ...epMod },
    { name: 'oracle', ...oracleMod },
  ])
  merged.contentVersion = core.contentVersion + ep.contentVersion
  merged.sheetVersion = ep.sheetVersion
  return merged
}

/**
 * Strict load (default): throws when TrustReport has errors.
 * Prefer loadSdkGraphWithTrust when you need the report.
 */
export function loadSdkGraph(opts: LoadSdkGraphOptions = {}): SdkGraph {
  const mode = opts.mode ?? 'strict'
  const result = loadSdkGraphWithTrust({ ...opts, mode })
  if (!result.report.ok && mode === 'strict') {
    const errs = [
      ...result.report.structural.errors,
      ...result.report.invariants.filter(i => i.severity === 'error').map(i => i.message),
    ]
    throw new Error(`sdk-graph trust invalid: ${errs.join('; ')}`)
  }
  return result.graph
}

/**
 * Always returns graph + TrustReport. In degraded mode, ok:false does not throw.
 */
export function loadSdkGraphWithTrust(opts: LoadSdkGraphOptions = {}): {
  graph: SdkGraph
  report: TrustReport
  trust: 'ok' | 'degraded'
} {
  const mode = opts.mode ?? 'strict'
  const merged = mergeCoreAndEp()
  const report = buildTrustReport(merged, {
    mode,
    scanPlannerCitations: opts.scanPlannerCitations,
    checkDebugGraph: opts.checkDebugGraph,
  })
  if (report.ok) return { graph: merged, report, trust: 'ok' }
  if (mode === 'degraded') return { graph: merged, report, trust: 'degraded' }
  return { graph: merged, report, trust: 'degraded' }
}

export function filterSdkGraph(
  graph: SdkGraph,
  opts: {
    family?: string
    type?: string
    status?: string
    module?: string
    edgeKind?: string
  } = {},
): SdkGraph {
  const nodes: SdkGraph['nodes'] = {}
  for (const [id, node] of Object.entries(graph.nodes)) {
    if (opts.family && node.family !== opts.family) continue
    if (opts.type && node.type !== opts.type) continue
    if (opts.status && node.status !== opts.status) continue
    if (opts.module && node.module !== opts.module) continue
    nodes[id] = node
  }
  const ids = new Set(Object.keys(nodes))
  const edges = graph.edges.filter(e => {
    if (opts.edgeKind && e.kind !== opts.edgeKind) return false
    return ids.has(e.from) && ids.has(e.to)
  })
  return { ...graph, nodes, edges }
}

export function isEpFamily(family: string): boolean {
  return sdkFamilyToEp(family) != null
}

export {
  applySdkGraphMutations,
  validateSdkGraph,
  renderSdkGraphMermaidSlices,
  buildSdkGraphIndex,
  buildSdkGraphContextPack,
  formatSdkGraphStatusReport,
}
