/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    InvariantHit, InvariantOptions, runSdkGraphInvariants
 * depends    src/mechanics/coverage/data/sheets.v1.json, src/mechanics/coverage/ep-citations, src/mechanics/coverage/schema, src/mechanics/debug-graph, src/mechanics/debug-graph/schema, src/mechanics/sdk-graph/build-index (+2 more)
 * used by    src/mechanics/sdk-graph/index, src/mechanics/sdk-graph/trust-report
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
import type { SdkGraph } from './schema'
import { buildSdkGraphIndex } from './build-index'
import { collectSdkGraphCells } from './validate'
import {
  CoverageInventorySchema,
  isExplicitUnknown,
  type CoverageInventory,
} from '../coverage/schema'
import { distinctEpPlannerCellKeys } from '../coverage/ep-citations'
import sheetsInventoryRaw from '../coverage/data/sheets.v1.json'
import { loadDebugGraphDegraded } from '../debug-graph'
import { debugSymbolId } from '../debug-graph/schema'

export interface InvariantHit {
  id: string
  severity: 'error' | 'warning'
  message: string
  nodeIds?: string[]
  surfaceIds?: string[]
}

export interface InvariantOptions {
  /** When false, skip filesystem scan of effective-paths sources (tests with fixtures). */
  scanPlannerCitations?: boolean
  /** When false, skip Debug Graph cross-check (bootstrap). Default true. */
  checkDebugGraph?: boolean
  sheetsInventory?: CoverageInventory
  mechanicsDir?: string
}

function hasRecheckableEvidence(node: SdkGraph['nodes'][string]): boolean {
  if ((node.sourceCells?.length ?? 0) > 0) return true
  if ((node.wikiPages?.length ?? 0) > 0) return true
  if (node.lambdaName) return true
  if ((node.codeSymbols?.length ?? 0) > 0) return true
  // An oracle node carries origin, ref, source version and verification date on
  // every claim it makes, and its assertions are exercised by the knowledge
  // suite. That is recheckable in the sense this invariant means.
  if (node.oracleNodeId) return true
  return false
}

function loadDefaultSheetsInventory(): CoverageInventory {
  return CoverageInventorySchema.parse(sheetsInventoryRaw)
}

/**
 * First-class mechanics trust invariants (milestone 1).
 * See docs/AGENT_MECHANICS_TRUST_CONTRACT.md.
 */
export function runSdkGraphInvariants(
  graph: SdkGraph,
  opts: InvariantOptions = {},
): InvariantHit[] {
  const hits: InvariantHit[] = []
  const index = buildSdkGraphIndex(graph)
  const sheets = opts.sheetsInventory ?? loadDefaultSheetsInventory()

  // 1. verified-without-evidence
  for (const node of Object.values(graph.nodes)) {
    if (node.status !== 'verified') continue
    if (!hasRecheckableEvidence(node)) {
      hits.push({
        id: 'verified-without-evidence',
        severity: 'error',
        message: `verified node ${node.id} lacks recheckable evidence (sourceCells/wiki/lambda/codeSymbols)`,
        nodeIds: [node.id],
      })
    }
  }

  // Edge evidence is Zod-enforced; still flag empty evidence if somehow present
  for (const edge of graph.edges) {
    const ev = edge.evidence
    const ok = (ev.sourceCells?.length ?? 0) > 0
      || !!ev.wikiTitle
      || !!ev.lambdaName
      || !!ev.codeSymbol
    if (!ok) {
      hits.push({
        id: 'edge-without-evidence',
        severity: 'error',
        message: `edge ${edge.id} has no evidence`,
        nodeIds: [edge.from, edge.to],
      })
    }
  }

  // 2 + 4. planner citations + silent gaps (sheets)
  const allowlisted = new Map<string, CoverageInventory['entries'][number]>()
  for (const entry of sheets.entries) {
    allowlisted.set(entry.id, entry)
    if (!isCoverageEntryComplete(entry)) {
      hits.push({
        id: 'silent-coverage-gap',
        severity: 'error',
        message: `sheets coverage ${entry.id} has neither graphNodeIds nor unmodeled/out_of_scope/historical marker`,
        surfaceIds: [entry.id],
      })
    }
  }

  if (opts.scanPlannerCitations !== false) {
    const keys = distinctEpPlannerCellKeys(opts.mechanicsDir)
    const byCell = index.byCell
    for (const key of keys) {
      const inGraph = (byCell[key]?.length ?? 0) > 0
      const entry = allowlisted.get(key)
      if (inGraph) continue
      if (entry && isExplicitUnknown(entry.coverageStatus)) continue
      hits.push({
        id: 'planner-cell-not-in-graph',
        severity: 'error',
        message: `planner cites ${key} but it is not in graph byCell and not allowlisted as unmodeled/historical/out_of_scope`,
        surfaceIds: [key],
        nodeIds: entry?.graphNodeIds,
      })
    }
  }

  // Warn when modeled coverage points at missing nodes
  for (const entry of sheets.entries) {
    if (entry.coverageStatus !== 'modeled') continue
    for (const id of entry.graphNodeIds) {
      if (!graph.nodes[id]) {
        hits.push({
          id: 'coverage-dangling-node',
          severity: 'warning',
          message: `sheets coverage ${entry.id} references missing node ${id}`,
          surfaceIds: [entry.id],
          nodeIds: [id],
        })
      }
    }
  }

  // Debug Graph: mechanics codeSymbols must resolve to runtime.symbol nodes
  if (opts.checkDebugGraph !== false) {
    try {
      const { graph: dbg } = loadDebugGraphDegraded()
      for (const node of Object.values(graph.nodes)) {
        for (const sym of node.codeSymbols ?? []) {
          const sid = debugSymbolId(sym)
          if (!dbg.nodes[sid]) {
            hits.push({
              id: 'code-symbol-missing-debug',
              severity: 'error',
              message: `mechanics node ${node.id} codeSymbol ${sym} missing from debug graph (${sid})`,
              nodeIds: [node.id],
              surfaceIds: [sid],
            })
          }
        }
      }
    } catch (error) {
      hits.push({
        id: 'debug-graph-load-failed',
        severity: 'error',
        message: `debug graph load failed: ${error instanceof Error ? error.message : String(error)}`,
      })
    }
  }

  // Optional: cells collected but unused — keep API warm for drift later
  void collectSdkGraphCells(graph)

  return hits
}

function isCoverageEntryComplete(entry: CoverageInventory['entries'][number]): boolean {
  if ((entry.graphNodeIds?.length ?? 0) > 0) return true
  return isExplicitUnknown(entry.coverageStatus)
}
