/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    SdkMutateResult, applySdkGraphMutations
 * depends    src/mechanics/sdk-graph/schema, src/mechanics/sdk-graph/validate
 * used by    src/mechanics/builders/index, src/mechanics/sdk-graph/index
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
import {
  SdkGraphSchema,
  SdkMutationOpSchema,
  type SdkGraph,
  type SdkMutationOp,
} from './schema'
import { validateSdkGraph } from './validate'

export interface SdkMutateResult {
  graph: SdkGraph
  applied: number
  contentVersion: number
  issues: string[]
}

export function applySdkGraphMutations(
  graph: SdkGraph,
  ops: readonly unknown[],
): SdkMutateResult {
  const parsedOps: SdkMutationOp[] = []
  const issues: string[] = []
  for (let i = 0; i < ops.length; i++) {
    const parsed = SdkMutationOpSchema.safeParse(ops[i])
    if (!parsed.success) {
      issues.push(`op[${i}]: ${parsed.error.issues.map(x => x.message).join('; ')}`)
      continue
    }
    parsedOps.push(parsed.data)
  }
  if (issues.length) {
    return { graph, applied: 0, contentVersion: graph.contentVersion, issues }
  }

  const next: SdkGraph = {
    ...graph,
    nodes: { ...graph.nodes },
    edges: [...graph.edges],
    historicalAllowlist: [...(graph.historicalAllowlist ?? [])],
  }

  for (const op of parsedOps) {
    switch (op.op) {
      case 'addNode': {
        if (next.nodes[op.node.id]) {
          issues.push(`addNode: ${op.node.id} already exists`)
          break
        }
        next.nodes[op.node.id] = op.node
        break
      }
      case 'modifyNode': {
        const cur = next.nodes[op.id]
        if (!cur) {
          issues.push(`modifyNode: missing ${op.id}`)
          break
        }
        next.nodes[op.id] = { ...cur, ...op.patch, id: op.id }
        break
      }
      case 'deleteNode': {
        if (!next.nodes[op.id]) {
          issues.push(`deleteNode: missing ${op.id}`)
          break
        }
        delete next.nodes[op.id]
        next.edges = next.edges.filter(e => e.from !== op.id && e.to !== op.id)
        break
      }
      case 'addEdge': {
        if (next.edges.some(e => e.id === op.edge.id)) {
          issues.push(`addEdge: ${op.edge.id} already exists`)
          break
        }
        next.edges.push(op.edge)
        break
      }
      case 'modifyEdge': {
        const idx = next.edges.findIndex(e => e.id === op.id)
        if (idx < 0) {
          issues.push(`modifyEdge: missing ${op.id}`)
          break
        }
        next.edges[idx] = { ...next.edges[idx], ...op.patch, id: op.id }
        break
      }
      case 'deleteEdge': {
        const before = next.edges.length
        next.edges = next.edges.filter(e => e.id !== op.id)
        if (next.edges.length === before) issues.push(`deleteEdge: missing ${op.id}`)
        break
      }
      default:
        issues.push('unknown op')
    }
  }

  if (issues.length) {
    return { graph, applied: 0, contentVersion: graph.contentVersion, issues }
  }

  next.contentVersion = graph.contentVersion + 1
  next.updatedAt = new Date().toISOString().slice(0, 10)

  const schemaCheck = SdkGraphSchema.safeParse(next)
  if (!schemaCheck.success) {
    return {
      graph,
      applied: 0,
      contentVersion: graph.contentVersion,
      issues: schemaCheck.error.issues.map(i => i.message),
    }
  }

  const structural = validateSdkGraph(schemaCheck.data)
  if (structural.errors.length) {
    return {
      graph,
      applied: 0,
      contentVersion: graph.contentVersion,
      issues: structural.errors,
    }
  }

  return {
    graph: schemaCheck.data,
    applied: parsedOps.length,
    contentVersion: schemaCheck.data.contentVersion,
    issues: [],
  }
}
