/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    DEFAULT_UPTIME_CHART_ORDER, UptimeChartOrientation, UptimeChartView, UptimeChartLocalState, defaultUptimeChartLocalState, normalizeUptimeChartLocalState, uptimeChartLocalPersistenceSchema
 * depends    src/internal/local-state/local-persistence-types
 * used by    src/internal/local-state/calculator-local-state-schemas, src/mechanics/calculators/specs-generated
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
import { buildNormalizerPersistenceSchema } from './local-persistence-types'

export const DEFAULT_UPTIME_CHART_ORDER = ['gb', 'ab', 'fb', 'tb', 'dw', 'gt', 'bh', 'ps', 'cf', 'sm', 'ilm', 'attack', 'ally', 'bounty', 'fetch', 'summon'] as const

export type UptimeChartOrientation = 'landscape' | 'portrait'
export type UptimeChartView = 'segmented' | 'linear'

export type UptimeChartLocalState = {
  chartCollapsed: boolean
  chartOrientation: UptimeChartOrientation
  chartView: UptimeChartView
  chartSettings: Record<string, unknown>
  chartOrder: string[]
}

export const defaultUptimeChartLocalState = (): UptimeChartLocalState => ({
  chartCollapsed: false,
  chartOrientation: 'landscape',
  chartView: 'segmented',
  chartSettings: {},
  chartOrder: [...DEFAULT_UPTIME_CHART_ORDER],
})

function normalizeChartOrder(value: unknown): string[] {
  if (!Array.isArray(value)) return [...DEFAULT_UPTIME_CHART_ORDER]
  const normalized = value.filter((entry): entry is string => typeof entry === 'string' && entry.trim().length > 0)
  return normalized.length > 0 ? normalized : [...DEFAULT_UPTIME_CHART_ORDER]
}

export function normalizeUptimeChartLocalState(
  input: unknown,
  base: UptimeChartLocalState = defaultUptimeChartLocalState(),
): UptimeChartLocalState {
  const data = input && typeof input === 'object' ? input as Record<string, unknown> : {}
  return {
    chartCollapsed: typeof data.chartCollapsed === 'boolean' ? data.chartCollapsed : base.chartCollapsed,
    chartOrientation: data.chartOrientation === 'portrait' ? 'portrait' : 'landscape',
    chartView: data.chartView === 'linear' ? 'linear' : 'segmented',
    chartSettings: data.chartSettings && typeof data.chartSettings === 'object'
      ? (data.chartSettings as Record<string, unknown>)
      : base.chartSettings,
    chartOrder: normalizeChartOrder(data.chartOrder),
  }
}

export const uptimeChartLocalPersistenceSchema = buildNormalizerPersistenceSchema(normalizeUptimeChartLocalState)
