/**
 * ControlRelation query helpers over the curated ep-graph.
 *
 * sheet-ast = UI IR · sheet-graph = formula DAG · ep-graph = named edges.
 * These helpers walk `feeds` / `dependsOn` / `affectsPath` only — never invent
 * a fourth graph.
 */
/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    epControlAffectsPathEdges, epControlPathVariants, epControlHasAffectsPath, epDependsOnEdges, epDependsOnCycles, epSatelliteReadsMissingFeeds, epTabBoundControlsMissingAffectsPath
 * depends    src/mechanics/ep-controls/data/swept-regions.v1.json, src/mechanics/ep-controls/sheet-ast, src/mechanics/ep-graph
 * used by    src/mechanics/calculators/specs-generated, src/mechanics/ep-controls/index
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
import { loadEpGraph, type EpGraph, type EpGraphEdge } from '../ep-graph'
import sweptRaw from './data/swept-regions.v1.json'
import { epSheetAstBoundInteractiveControls } from './sheet-ast'

interface SatelliteTab {
  tab: string
  readsControls?: readonly string[]
}

const SATELLITES = (sweptRaw as { satelliteTabs?: SatelliteTab[] }).satelliteTabs ?? []

function controlNodeByCell(graph: EpGraph): Map<string, string> {
  const map = new Map<string, string>()
  for (const node of Object.values(graph.nodes)) {
    if (node.type !== 'control') continue
    for (const cell of node.sourceCells ?? []) {
      map.set(`${cell.sheet}!${cell.cell}`, node.id)
    }
  }
  return map
}

/** Every `affectsPath` edge leaving a control (optionally one control id). */
export function epControlAffectsPathEdges(
  controlId?: string,
  graph: EpGraph = loadEpGraph(),
): EpGraphEdge[] {
  return graph.edges.filter(e =>
    e.kind === 'affectsPath'
    && (controlId === undefined || e.from === controlId))
}

/** pathVariants listed on affectsPath for a control, or undefined if unrestricted. */
export function epControlPathVariants(
  controlId: string,
  graph: EpGraph = loadEpGraph(),
): readonly string[] | undefined {
  const edges = epControlAffectsPathEdges(controlId, graph)
  const variants = new Set<string>()
  let anyListed = false
  for (const edge of edges) {
    if (edge.pathVariants?.length) {
      anyListed = true
      for (const v of edge.pathVariants) variants.add(v)
    }
  }
  return anyListed ? [...variants].sort() : undefined
}

export function epControlHasAffectsPath(
  controlId: string,
  graph: EpGraph = loadEpGraph(),
): boolean {
  return epControlAffectsPathEdges(controlId, graph).length > 0
}

export function epDependsOnEdges(graph: EpGraph = loadEpGraph()): EpGraphEdge[] {
  return graph.edges.filter(e => e.kind === 'dependsOn')
}

/**
 * Cycles in the dependsOn subgraph only. Cycle DFS for the full graph skips
 * dependsOn; this check keeps the config-order DAG honest on its own.
 */
export function epDependsOnCycles(graph: EpGraph = loadEpGraph()): string[] {
  const adj = new Map<string, string[]>()
  for (const edge of epDependsOnEdges(graph)) {
    const list = adj.get(edge.from) ?? []
    list.push(edge.to)
    adj.set(edge.from, list)
  }
  const visiting = new Set<string>()
  const visited = new Set<string>()
  const cycles: string[] = []

  function dfs(node: string, stack: string[]): void {
    if (visiting.has(node)) {
      cycles.push([...stack, node].join(' -> '))
      return
    }
    if (visited.has(node)) return
    visiting.add(node)
    for (const next of adj.get(node) ?? []) {
      dfs(next, [...stack, node])
    }
    visiting.delete(node)
    visited.add(node)
  }

  for (const node of adj.keys()) dfs(node, [])
  return cycles
}

/**
 * Satellite `readsControls` cells that have no control→consumer `feeds` edge.
 * Mirror hops (reads→display derives→control) must still yield feeds.
 */
export function epSatelliteReadsMissingFeeds(
  graph: EpGraph = loadEpGraph(),
): string[] {
  const byCell = controlNodeByCell(graph)
  const withFeeds = new Set(
    graph.edges.filter(e => e.kind === 'feeds').map(e => e.from),
  )
  const missing: string[] = []
  for (const region of SATELLITES) {
    for (const cell of region.readsControls ?? []) {
      const controlId = byCell.get(cell)
      if (!controlId) {
        missing.push(`${region.tab}: ${cell} (no control node)`)
        continue
      }
      if (!withFeeds.has(controlId)) {
        missing.push(`${region.tab}: ${cell} (${controlId})`)
      }
    }
  }
  return missing
}

/**
 * Bound interactive sheet-AST controls with webPlacement `tab` that lack
 * affectsPath. Settings-only / IDS-derived rows are out of scope.
 */
export function epTabBoundControlsMissingAffectsPath(
  graph: EpGraph = loadEpGraph(),
): string[] {
  const byCell = controlNodeByCell(graph)
  const withAffects = new Set(
    graph.edges.filter(e => e.kind === 'affectsPath').map(e => e.from),
  )
  const missing: string[] = []
  for (const control of epSheetAstBoundInteractiveControls()) {
    if (control.webPlacement !== 'tab' || !control.webKey) continue
    const cellKey = `${control.tab}!${control.cell}`
    const nodeId = byCell.get(cellKey)
    if (!nodeId) continue
    if (!withAffects.has(nodeId)) {
      missing.push(`${control.webKey} (${nodeId} @ ${cellKey})`)
    }
  }
  return missing
}
