/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    EpControlRow, EP_CONTROL_SURFACE_SHEET_VERSION, EP_INPUT_RANGE_CONTROL_CELLS, EP_WIRED_CONTROL_CELLS, epControlRows, EpControlCoverage, epControlCoverage, epUnwiredControls (+7 more)
 * depends    src/mechanics/ep-controls/data/control-surface.v1.json, src/mechanics/ep-graph
 * used by    —
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
import { loadEpGraph } from '../ep-graph'
import surfaceRaw from './data/control-surface.v1.json'

/**
 * The Effective Paths control surface, and how much of it is wired.
 *
 * ## Why this exists
 *
 * The EP port took the main formulas and stopped before the controls. Nothing
 * recorded that, so "the port is done" and "the port computes the default
 * configuration correctly" were the same sentence. This is the inventory that
 * separates them.
 *
 * The four planner tabs expose 175 rows in their control panels. Fifteen of
 * them are wired — eight as `ep-graph` nodes, and eleven `control.*` entries in
 * `input_ranges`, overlapping. Every other row is a switch a player can flip
 * that this package cannot express, which means a planner answer computed here
 * is an answer for one configuration of the sheet.
 *
 * ## What a row here is, and is not
 *
 * A capture, taken from `inspect_tab_ui` at sheet version v5.09.03.07 on
 * 2026-08-18. It is NOT live: the sheet is canonical and read-only, but it does
 * get versioned updates, and the row numbers drift between them — the sheet's
 * own tooling warns about exactly that. `ep-graph` still records
 * v5.09.03.01, which is one reason the wired set is worth re-checking rather
 * than trusted.
 *
 * Refresh by re-running `inspect_tab_ui` for each tab and updating
 * `data/control-surface.v1.json`, including `sheetVersion`.
 *
 * ## Rows with no value
 *
 * Some rows read back `null`. Those are section headers (`User Inputs`,
 * `PRESETS`) and controls whose cell was empty at capture time (`Run Type` on
 * eDamage). The capture cannot tell those apart, so they are counted as
 * `valueUnknown` rather than sorted into a guess. Anything relying on the
 * distinction has to go back to the sheet.
 *
 * ## eRegen is a hidden tab
 *
 * Read from the rendered tab bar rather than from the API: **23 of the
 * workbook's 30 tabs are hidden**, eRegen among them. A player sees Home Page,
 * IDS, Giveaways, eHP, eDamage, eEcon and Master Sheet, and nothing else.
 *
 * `sheet_info` lists all thirty without marking any of them, and
 * `inspect_tab_ui` accepts eRegen as a planner tab, so nothing reachable
 * through the oracle says this. It took looking at the sheet.
 *
 * It also explains the mirror rather than merely accompanying it: eRegen can be
 * a spilled copy of eHP precisely because nobody opens it.
 *
 * The consequence for the numbers here: of 175 panel rows, 32 belong to a tab
 * no player can reach. The player-facing surface is 143.
 *
 * ## eRegen has no controls of its own
 *
 * `eRegen!AL3` is `={eHP!AL3:BM37}`. Everything in that window is a spilled
 * mirror of eHP, and the window contains eRegen's entire AT/AY control panel.
 * Its 32 panel rows are eHP's controls displayed on another tab.
 *
 * This was modelled wrongly first: eleven of those cells were wired as eRegen
 * controls, because a VALUE read of the region returns toggles and booleans
 * while a FORMULA read of the same cells returns nothing at all. A spilled
 * range reads empty through formulas, which is the one trap the sheet's own
 * tooling warns about first, and it is invisible in the direction most likely
 * to be read.
 *
 * `eRegen!AJ22` (`Rows Calculated`) is outside the mirrored window and is a
 * real eRegen control.
 *
 * Rows carrying `mirroredFrom` are the mirrored ones. They are excluded from
 * the unwired work list: wiring them would model the same control twice.
 *
 * ## Finding what reads a cell
 *
 * The read API answers "what is this cell's formula" and cannot answer "what
 * references this cell". The sheet's own **Find and replace** dialog offers
 * *"Also search within formulas"* and is available on the view-only copy, which
 * makes it the only consumer search there is. Use *Find* only.
 *
 * **Read its result carefully.** Clicking Find moves the cursor, and a moved
 * cursor is not a match. That was misread once here: the cursor landed on
 * `eEcon!FR5` and it was recorded as the consumer of `$AZ$15`, then retracted —
 * the API, a range read and the formula bar all agree that FR5 is empty. Check
 * the cell the search lands on actually contains the string before believing
 * it.
 *
 * ## Sweeping a tab, and what a swept window claims
 *
 * `data/swept-regions.v1.json` records which columns of a tab have actually
 * been read cell by cell, and what was in them. eHP is swept for
 * `AH14:BM40` plus its panel; the other three tabs are not swept at all.
 *
 * The point of recording the WINDOW rather than a conclusion is that "eHP has
 * 38 controls" is only true within it. Outside the window nothing has been
 * enumerated, which is not the same as nothing being there — and a denominator
 * that does not say which it means is the kind of number this file exists to
 * stop being quoted.
 *
 * The eHP sweep found six controls outside the panel: five in the Total Value
 * block and `Rows Calculated` at AJ22. It also found what is NOT a control —
 * the BA-BM band is reference tables and dropdown source lists — which is worth
 * as much, because it bounds where else to look.
 *
 * ## 175 is the panel, not the tab
 *
 * The denominator here counts rows in each tab's control PANEL. It is not the
 * number of controls a tab has. eHP keeps five more in its Total Value block
 * (column AM, rows 20-26) — Wall Health, Max Recovery, Chain Thunder, Chrono
 * Field and a fifth that turns out not to be a control at all — and neither
 * `inspect_tab_ui` nor this capture reaches that region.
 *
 * So `53 of 175` means "53 of the 175 panel rows". Read as "53 of all controls"
 * it is optimistic, and by an unknown margin: nothing has enumerated the
 * off-panel regions of any tab.
 *
 * ## The panel tool reads one column, and some controls are in another
 *
 * `inspect_tab_ui` reads a single value column per tab — AZ for eEcon, AY for
 * the other three. Sixteen controls are in **AX** instead, so it reported them
 * with no value at all: the preset selectors on eHP, eRegen and eDamage, plus
 * eDamage's `Run Type` and `Simulated Tier`. Its own layout note naming
 * `Run Type AY19` is wrong; AY19 is empty.
 *
 * They are not laid out consistently either, which is why each had to be read
 * rather than inferred from the tab next door: eHP puts a value in the
 * `PRESETS` master row (AX3) and eRegen leaves that row a header. Assuming
 * eRegen mirrored eHP would have invented a control.
 *
 * Rows carrying `valueColumn` are the ones read outside the panel column.
 *
 * ## Eight eDamage rows are a computed display, not controls
 *
 * Rows 3 to 10 — `Bullet Damage %`, `UW* Damage %`, and one per ultimate — are
 * formulas across four columns showing the damage split. They read as valueless
 * in the panel column because that is not where their output goes. Marked
 * `isComputedDisplay` so they stay out of the work list.
 *
 * ## Ten labels on eDamage are placeholders, not names
 *
 * Rows 28 to 37 read back as `// Unlock SM //`, `// Equip Project Funding //`
 * and so on. Those are not control names. Each label cell is an `IF` that shows
 * the real name once the prerequisite is owned and the placeholder until then,
 * so what a capture sees depends on the account the sheet is configured for —
 * the demo account owns none of them.
 *
 * `labelWhenUnlocked` carries the real name, read from FORMULATEXT. Two of the
 * ten (`AY28`, `AY37`) compute their VALUE conditionally as well, so the
 * captured number is a default for this account rather than a free input;
 * `valueIsComputed` marks those.
 *
 * The trap generalises: a label read from this sheet is a value like any other,
 * and can be a function of the account.
 */

export interface EpControlRow {
  tab: string
  row: number
  /** What the label cell read at capture time — may be a placeholder. */
  label: string
  /** The real control name, when the label cell is conditional. */
  labelWhenUnlocked?: string
  /** What has to be owned or equipped before the label resolves. */
  unlockCondition?: string
  /** True when the VALUE is computed rather than freely entered. */
  valueIsComputed?: boolean
  /** Column the value was read from, when not the tab panel column. */
  valueColumn?: string
  /** True when the row is a computed display rather than any kind of control. */
  isComputedDisplay?: boolean
  /** Tab this row is a spilled mirror of, when it is one. */
  mirroredFrom?: string
  /** True when the row is a column header rather than any kind of cell value. */
  isHeader?: boolean
  /**
   * Set when the row came from reading the sheet's formulas rather than from
   * `inspect_tab_ui`. The tool reads one value column per tab, so a row that
   * carries two controls is reported once. Marking these keeps
   * `epReportedControlCounts()` comparable to what the tool actually said.
   */
  discoveredBy?: string
  /** Cell address in the tab's value column, e.g. `AZ12`. */
  cell: string
  value: string | number | boolean | null
  /** True when the capture read no value — a header, or an empty control. */
  valueUnknown: boolean
  /** True when this cell is modelled by ep-graph or named in input_ranges. */
  wired: boolean
}

interface RawTab {
  playerVisible?: boolean
  labelCol: string
  valueCol: string
  reportedControlCount: number
  rows: Array<{
    row: number
    label: string
    value: string | number | boolean | null
    labelIsConditional?: boolean
    labelWhenUnlocked?: string
    unlockCondition?: string
    valueIsComputed?: boolean
    valueColumn?: string
    isComputedDisplay?: boolean
    mirroredFrom?: string
    isHeader?: boolean
    discoveredBy?: string
  }>
}

interface RawSurface {
  sheetVersion: string
  capturedAt: string
  source: string
  tabs: Record<string, RawTab>
}

const SURFACE = surfaceRaw as RawSurface

/** Sheet version the capture was taken from. */
export const EP_CONTROL_SURFACE_SHEET_VERSION = SURFACE.sheetVersion

/** Every cell the capture actually contains, as `tab!cell`. */
const PANEL_CELLS = new Set(
  Object.entries((surfaceRaw as RawSurface).tabs)
    .flatMap(([tab, data]) => data.rows.map(
      row => `${tab}!${row.valueColumn ?? data.valueCol}${row.row}`,
    )),
)

/**
 * Panel cells named by `input_ranges` as `control.*` inputs.
 *
 * Hard-coded because `input_ranges` lives behind the sheet oracle rather than
 * in this package. Cells outside a tab control panel are deliberately absent —
 * `eEcon Stones!AZ18` and `eEcon!O3` are modelled but are not panel rows, and
 * counting them here would inflate the wired figure against a 175-row
 * denominator that never included them.
 */
export const EP_INPUT_RANGE_CONTROL_CELLS: readonly string[] = [
  'eEcon!AZ11',
  'eEcon!AZ12',
  'eEcon!AZ13',
  'eEcon!AZ43',
  'eHP!AY13',
  'eHP!AY14',
  'eDamage!AY24',
  'eDamage!AY25',
  'eDamage!AY26',
  'eDamage!AY27',
  'eDamage!AY39',
  'eDamage!AY61',
]

/**
 * Every panel cell this package models, derived rather than listed.
 *
 * The `ep-graph` half is read from the graph itself, so wiring a control there
 * raises this count and unwiring one lowers it. It was a hand-written list
 * first, and that list did not notice when seven eRegen controls were added —
 * a wired set that cannot see the wiring is the same defect this inventory
 * exists to catch.
 */
export const EP_WIRED_CONTROL_CELLS: readonly string[] = [...new Set([
  ...EP_INPUT_RANGE_CONTROL_CELLS,
  // ANY node type, not just `control`. The question this inventory answers is
  // "does the package model this row", and several rows turned out to be
  // displays or gates rather than controls. Counting only controls would make
  // correcting a mis-typed node look like losing coverage, which is a reason to
  // avoid correcting it.
  ...Object.values(loadEpGraph().nodes)
    .flatMap(node => (node.sourceCells ?? []).map(cell => `${cell.sheet}!${cell.cell}`)),
])]
  // Only cells that are actually panel rows. `eEcon!O3` is a modelled control
  // living outside the AU/AZ panel, so it belongs to neither the numerator nor
  // the denominator here.
  .filter(cell => PANEL_CELLS.has(cell))
  .sort()

const WIRED = new Set(EP_WIRED_CONTROL_CELLS)

/** Every control-panel row across the four planner tabs. */
export function epControlRows(): EpControlRow[] {
  const rows: EpControlRow[] = []
  for (const [tab, data] of Object.entries(SURFACE.tabs)) {
    for (const entry of data.rows) {
      const cell = `${entry.valueColumn ?? data.valueCol}${entry.row}`
      rows.push({
        tab,
        row: entry.row,
        label: entry.label,
        ...(entry.labelWhenUnlocked ? { labelWhenUnlocked: entry.labelWhenUnlocked } : {}),
        ...(entry.unlockCondition ? { unlockCondition: entry.unlockCondition } : {}),
        ...(entry.valueIsComputed ? { valueIsComputed: entry.valueIsComputed } : {}),
        ...(entry.valueColumn ? { valueColumn: entry.valueColumn } : {}),
        ...(entry.isComputedDisplay ? { isComputedDisplay: entry.isComputedDisplay } : {}),
        ...(entry.mirroredFrom ? { mirroredFrom: entry.mirroredFrom } : {}),
        ...(entry.isHeader ? { isHeader: entry.isHeader } : {}),
        ...(entry.discoveredBy ? { discoveredBy: entry.discoveredBy } : {}),
        cell,
        value: entry.value,
        valueUnknown: entry.value === null,
        wired: WIRED.has(`${tab}!${cell}`),
      })
    }
  }
  return rows
}

export interface EpControlCoverage {
  tab: string
  total: number
  wired: number
  valueUnknown: number
  /** False for hidden tabs — rows a player cannot reach. */
  playerVisible: boolean
}

/** Per-tab totals, derived from the rows so the two cannot disagree. */
export function epControlCoverage(): EpControlCoverage[] {
  const byTab = new Map<string, EpControlCoverage>()
  for (const row of epControlRows()) {
    const entry = byTab.get(row.tab)
      ?? {
        tab: row.tab,
        total: 0,
        wired: 0,
        valueUnknown: 0,
        playerVisible: SURFACE.tabs[row.tab]?.playerVisible !== false,
      }
    entry.total += 1
    if (row.wired) entry.wired += 1
    if (row.valueUnknown) entry.valueUnknown += 1
    byTab.set(row.tab, entry)
  }
  return [...byTab.values()].sort((a, b) => a.tab.localeCompare(b.tab))
}

/**
 * Rows no part of this package models. The work remaining, by name.
 *
 * Computed displays are excluded: they are not controls, so wiring one would
 * be modelling a formula as an input.
 */
export function epUnwiredControls(): EpControlRow[] {
  return epControlRows().filter(row =>
    !row.wired && !row.valueUnknown && !row.isComputedDisplay && !row.mirroredFrom && !row.isHeader)
}

/** Rows that are a spilled mirror of another tab, not controls of their own. */
export function epMirroredControls(): EpControlRow[] {
  return epControlRows().filter(row => row.mirroredFrom != null)
}

/** Controls the tab panel column cannot see. */
export function epControlsOutsidePanelColumn(): EpControlRow[] {
  return epControlRows().filter(row => row.valueColumn != null)
}

/** What the capture reported per tab, for checking the capture itself. */
export function epReportedControlCounts(): Record<string, number> {
  return Object.fromEntries(
    Object.entries(SURFACE.tabs).map(([tab, data]) => [tab, data.reportedControlCount]),
  )
}

/** Rows whose displayed label depends on what the account owns. */
export function epConditionalLabelControls(): EpControlRow[] {
  return epControlRows().filter(row => row.labelWhenUnlocked != null)
}

/** The name to show a user: the resolved one when there is one. */
export function epControlDisplayName(row: EpControlRow): string {
  return row.labelWhenUnlocked ?? row.label
}

/** Panel rows on tabs a player can actually reach. */
export function epPlayerVisibleRowCount(): number {
  return epControlRows().filter(row => SURFACE.tabs[row.tab]?.playerVisible !== false).length
}

/** Tabs the workbook shows in its tab bar, hidden ones excluded. */
export const EP_VISIBLE_TABS: readonly string[] = (SURFACE as unknown as {
  visibleTabs: string[]
}).visibleTabs
