/**
 * Semantic sheet AST for Effective Paths planner panels.
 *
 * Built by `scripts/effective-paths/build-sheet-ast.mjs` from the enriched
 * control-surface capture (dataValidation → controlType) plus web-control-map.
 * layoutBlocks group controls under sheet section headers / paint clusters.
 *
 * This is the IR the web compiler gate validates against — not a second
 * hand-written inventory of what the page "should" show.
 */
/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    EpSheetAstControlType, EpSheetAstControl, EpSheetAstLayoutBlock, EpSheetAstMerge, EpSheetAstTab, EP_SHEET_AST_SHEET_VERSION, EP_SHEET_AST_SCHEMA_VERSION, epSheetAstTabs (+4 more)
 * depends    src/mechanics/ep-controls/data/sheet-ast.v1.json
 * used by    src/mechanics/calculators/specs-generated, src/mechanics/ep-controls/control-relations, src/mechanics/ep-controls/index
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
import astRaw from './data/sheet-ast.v1.json'

export type EpSheetAstControlType =
  | 'HEADER'
  | 'DISPLAY'
  | 'TOGGLE'
  | 'DROPDOWN'
  | 'NUMBER'
  | 'TEXT'
  | 'UNKNOWN'

export interface EpSheetAstControl {
  id: string
  tab: string
  cell: string
  row: number
  label: string
  labelRaw: string
  controlType: EpSheetAstControlType
  interactive: boolean
  classifiedBy: string
  value: string | number | boolean | null
  labelWhenUnlocked?: string
  unlockCondition?: string
  valueIsComputed?: boolean
  isComputedDisplay?: boolean
  mirroredFrom?: string
  optionValues?: readonly string[]
  backgroundColor?: { red?: number, green?: number, blue?: number }
  webKey: string | null
  webStatus: string
  webPlacement: string | null
  families?: readonly string[]
  note?: string
}

export interface EpSheetAstLayoutBlock {
  id: string
  type: 'FORM_GROUP'
  label: string
  sheetRow: number
  bounds: string
  headerCell?: string
  headerLabel?: string
  controls: readonly EpSheetAstControl[]
}

export interface EpSheetAstMerge {
  a1: string
  startRowIndex: number
  endRowIndex: number
  startColumnIndex: number
  endColumnIndex: number
}

export interface EpSheetAstTab {
  playerVisible: boolean
  labelCol: string
  valueCol: string
  merges: readonly EpSheetAstMerge[]
  layoutBlocks: readonly EpSheetAstLayoutBlock[]
  controlCount: number
  interactiveCount: number
}

interface RawAst {
  schemaVersion: number
  sheetVersion: string
  builtAt: string
  stats: {
    interactive: number
    boundInteractive: number
    missingUiInteractive: number
  }
  interactiveControlTypes: readonly string[]
  tabs: Record<string, EpSheetAstTab>
}

const AST = astRaw as RawAst

export const EP_SHEET_AST_SHEET_VERSION = AST.sheetVersion
export const EP_SHEET_AST_SCHEMA_VERSION = AST.schemaVersion

export function epSheetAstTabs(): Readonly<Record<string, EpSheetAstTab>> {
  return AST.tabs
}

/** Every control across all layout blocks. */
export function epSheetAstControls(): EpSheetAstControl[] {
  return Object.values(AST.tabs).flatMap(tab =>
    tab.layoutBlocks.flatMap(block => [...block.controls]))
}

/**
 * Interactive controls a player can flip on a reachable tab.
 * Excludes mirrors (eRegen spill of eHP) — those are the same control twice.
 */
export function epSheetAstInteractiveControls(): EpSheetAstControl[] {
  return epSheetAstControls().filter(control =>
    control.interactive
    && !control.mirroredFrom
    && AST.tabs[control.tab]?.playerVisible !== false)
}

/**
 * Interactive controls that still need a web binding or UI.
 * Statuses that explain absence (header / display / ids_derived) are excluded.
 */
export function epSheetAstControlsMissingUi(): EpSheetAstControl[] {
  const explained = new Set([
    'header',
    'display_only',
    'ids_derived',
    'mirrored',
    'non_sheet',
  ])
  return epSheetAstInteractiveControls().filter(control =>
    control.webStatus === 'missing_ui'
    || control.webStatus === 'unmapped'
    || (!explained.has(control.webStatus) && !control.webKey
      && control.webStatus !== 'bound'
      && control.webStatus !== 'bound_buried'))
}

/** Bound interactive controls — the compiler gate's primary work list. */
export function epSheetAstBoundInteractiveControls(): EpSheetAstControl[] {
  return epSheetAstInteractiveControls().filter(control =>
    (control.webStatus === 'bound' || control.webStatus === 'bound_buried')
    && control.webKey != null)
}
