/**
 * Sheet dependency DAG for Effective Paths planner-panel controls.
 *
 * Built by `scripts/effective-paths/build-sheet-graph.mjs` from a FORMULA dump
 * + sheet-ast INPUT_LEAF set. Every requiredInputLeaf must be bound in the web
 * inventory — that is the structural fix for silently dropped small toggles.
 */
/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    EpSheetGraphNodeType, EpSheetGraphNode, EpSheetGraphEdge, EP_SHEET_GRAPH_SHEET_VERSION, EP_SHEET_GRAPH_SCHEMA_VERSION, epSheetGraphStats, epSheetGraphNodes, epSheetGraphEdges (+4 more)
 * depends    src/mechanics/ep-controls/data/sheet-graph.v1.json
 * used by    src/mechanics/calculators/specs-generated, src/mechanics/ep-controls/index
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
import graphRaw from './data/sheet-graph.v1.json'

export type EpSheetGraphNodeType = 'INPUT_LEAF' | 'COMPUTED_NODE'

export interface EpSheetGraphNode {
  id: string
  label: string
  type: EpSheetGraphNodeType
  controlType?: string
  dataType?: string | null
  tab?: string
  cell?: string
  webKey?: string | null
  webStatus?: string | null
  classifiedBy?: string
  formula?: string
}

export interface EpSheetGraphEdge {
  from: string
  to: string
  kind: string
}

interface RawGraph {
  schemaVersion: number
  sheetVersion: string
  stats: {
    inputLeaves: number
    requiredInputLeaves: number
    unreferencedInputLeaves: number
    computedNodes: number
    computedNodesTotal?: number
    edges: number
    edgesTotal?: number
    formulasScanned?: number
    formulasWithHits?: number
    samplePerLeaf?: number
  }
  graphNodes: Record<string, EpSheetGraphNode>
  edges: EpSheetGraphEdge[]
  validationTargets: {
    requiredInputLeaves: string[]
    unreferencedInputLeaves: string[]
    terminalOutputNodes: string[]
  }
}

const GRAPH = graphRaw as RawGraph

export const EP_SHEET_GRAPH_SHEET_VERSION = GRAPH.sheetVersion
export const EP_SHEET_GRAPH_SCHEMA_VERSION = GRAPH.schemaVersion

export function epSheetGraphStats() {
  return GRAPH.stats
}

export function epSheetGraphNodes(): Readonly<Record<string, EpSheetGraphNode>> {
  return GRAPH.graphNodes
}

export function epSheetGraphEdges(): readonly EpSheetGraphEdge[] {
  return GRAPH.edges
}

/** Leaves that at least one formula reads — must be present in the web store/UI. */
export function epSheetGraphRequiredInputLeaves(): readonly string[] {
  return GRAPH.validationTargets.requiredInputLeaves
}

/** Interactive leaves with no scanned formula consumer — manual review list. */
export function epSheetGraphUnreferencedInputLeaves(): readonly string[] {
  return GRAPH.validationTargets.unreferencedInputLeaves
}

export function epSheetGraphInputLeafNodes(): EpSheetGraphNode[] {
  return Object.values(GRAPH.graphNodes).filter(n => n.type === 'INPUT_LEAF')
}

/**
 * requiredInputLeaves that lack a webKey binding (or are missing_ui).
 * Empty when the DAG→web compiler gate passes.
 */
export function epSheetGraphRequiredLeavesMissingWebBinding(): EpSheetGraphNode[] {
  const explained = new Set(['header', 'ids_derived', 'display_only', 'mirrored'])
  return epSheetGraphRequiredInputLeaves()
    .map(id => GRAPH.graphNodes[id])
    .filter((node): node is EpSheetGraphNode => {
      if (!node) return false
      if (node.webStatus && explained.has(node.webStatus)) return false
      if (!node.webKey) return true
      return node.webStatus === 'missing_ui' || node.webStatus === 'unmapped'
    })
}
