/**
 * Sheet → web binding map for Effective Paths controls.
 *
 * Built by `scripts/effective-paths/build-web-control-map.mjs` from the live
 * control-surface capture. Every real panel row is either bound, mirrored,
 * display-only, IDS-derived, explicitly missing, or a non-sheet allowlist entry.
 */
/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    EpWebControlStatus, EpWebControlPlacement, EpWebControlEntry, EP_WEB_CONTROL_MAP_SHEET_VERSION, EP_WEB_CONTROL_NON_SHEET_ALLOWLIST, epWebControlEntries, epWebControlsMissingUi, epWebControlsRequiringBinding
 * depends    src/mechanics/ep-controls/data/web-control-map.v1.json
 * used by    src/mechanics/calculators/specs-generated, src/mechanics/ep-controls/index
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
import mapRaw from './data/web-control-map.v1.json'

export type EpWebControlStatus =
  | 'bound'
  | 'bound_buried'
  | 'missing_ui'
  | 'missing_planner'
  | 'display_only'
  | 'ids_derived'
  | 'header'
  | 'mirrored'
  | 'non_sheet'

export type EpWebControlPlacement = 'tab' | 'settings'

export interface EpWebControlEntry {
  tab: string | null
  cell: string | null
  label: string
  sheetGroup: string
  webKey: string | null
  placement: EpWebControlPlacement
  status: EpWebControlStatus
  families?: readonly string[]
  note?: string
  mirroredFrom?: string
}

interface RawMap {
  sheetVersion: string
  nonSheetAllowlist: string[]
  entries: EpWebControlEntry[]
}

const MAP = mapRaw as RawMap

export const EP_WEB_CONTROL_MAP_SHEET_VERSION = MAP.sheetVersion
export const EP_WEB_CONTROL_NON_SHEET_ALLOWLIST: readonly string[] = MAP.nonSheetAllowlist

export function epWebControlEntries(): readonly EpWebControlEntry[] {
  return MAP.entries
}

/** Rows that should have UI and do not yet. */
export function epWebControlsMissingUi(): readonly EpWebControlEntry[] {
  return MAP.entries.filter(entry => entry.status === 'missing_ui')
}

/**
 * Rows a player can flip that still need a planner or UI binding.
 * Excludes headers, mirrors, displays, IDS presets, and non-sheet allowlist.
 */
export function epWebControlsRequiringBinding(): readonly EpWebControlEntry[] {
  return MAP.entries.filter(entry =>
    entry.status === 'missing_ui' || entry.status === 'missing_planner')
}
