/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    EnemyCcTimers, tickCcTimers, isStunned, isPoisoned, isSlowedByShockwave, titanShockAttackSpeedDivider, titanShockMassFactor, computeBotPlusBenefit (+4 more)
 * depends    —
 * used by    src/mechanics/calculators/specs-generated, src/mechanics/combat/index
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
export interface EnemyCcTimers {
  stunTime: number
  poisonTime: number
  poisonCount: number
  lingerTime: number
  fearedTime: number
  blackHoleTime: number
  shockwaveTime: number
  flameBotDamageReduction: number
  stunDebt: number
}

export function tickCcTimers(timers: EnemyCcTimers, deltaTime: number): EnemyCcTimers {
  return {
    ...timers,
    stunTime: Math.max(0, timers.stunTime - deltaTime),
    poisonTime: Math.max(0, timers.poisonTime - deltaTime),
    lingerTime: Math.max(0, timers.lingerTime - deltaTime),
    fearedTime: Math.max(0, timers.fearedTime - deltaTime),
    blackHoleTime: Math.max(0, timers.blackHoleTime - deltaTime),
    shockwaveTime: Math.max(0, timers.shockwaveTime - deltaTime),
  }
}

export function isStunned(timers: EnemyCcTimers): boolean {
  return timers.stunTime > 0
}

export function isPoisoned(timers: EnemyCcTimers): boolean {
  return timers.poisonTime > 0 || timers.poisonCount > 0
}

export function isSlowedByShockwave(timers: EnemyCcTimers): boolean {
  return timers.shockwaveTime > 0
}

export function titanShockAttackSpeedDivider(
  currentDivider: number,
  ccDuration: number,
  titanSlowFactor: number,
): number {
  const base = Math.max(ccDuration, 1)
  const tier = Math.floor(base)
  const stack = tier + 1
  const slow = titanSlowFactor * stack + 1
  return currentDivider * slow
}

/**
 * Mass term of `Enemy.GetTitanShockReduction` (game v29.0.0).
 *
 * Clamp `enemyMassOnActivate` to min 1.0, then `log10`, then add 1.
 * Multiplied by `GetTitanShockAttackSpeedSlow()`.
 */
export function titanShockMassFactor(enemyMassOnActivate: number): number {
  return Math.log10(Math.max(enemyMassOnActivate, 1)) + 1
}

/**
 * `Bots.GetBotPlusBenefit(BotType, level)` (v29):
 * `plusBaseBenefit[type] + plusBenefitPerLevel[type] * level`.
 *
 * Ladder constants live in `BOT_PLUS_BASE_BENEFIT_V29` /
 * `BOT_PLUS_BENEFIT_PER_LEVEL_V29` (filled in `Bots.Initialize`).
 */
export function computeBotPlusBenefit(
  plusBaseBenefit: number,
  plusBenefitPerLevel: number,
  level: number,
): number {
  return plusBaseBenefit + plusBenefitPerLevel * level
}

/**
 * `Enemy.GetTitanShockAttackSpeedSlow` (game v29.0.0).
 *
 * Reads runtime `Bots.plusBenefit` (`float[]`), filled by `UpdatePlusValues`
 * via `GetBotPlusBenefit` for each `BotType` (Flame=0 … Bot=4):
 * - index 1: Thunder Bot+ Titan Shock current value
 * - index 4: Bot Bot+ Maximum Power current value
 *
 * If `Enemy.boostedTitanShocked`: `plusBenefit[1] * plusBenefit[4]`
 * (requires length > 4). Else if `titanShocked`: `plusBenefit[1]`
 * (requires length ≥ 2). Else `1.0`.
 *
 * Titan Shock level ladder is binary-pinned (`BOT_PLUS_*_V29` index 1 =
 * `0.05 + 0.01 * level`). Callers may still pass a live `plusBenefit` snapshot.
 */
export function resolveTitanShockAttackSpeedSlow(
  plusBenefit: readonly number[],
  boostedTitanShocked: boolean,
  titanShocked = true,
): number {
  if (boostedTitanShocked) {
    if (plusBenefit.length <= 4) return 1
    return plusBenefit[1]! * plusBenefit[4]!
  }
  if (titanShocked) {
    if (plusBenefit.length < 2) return 1
    return plusBenefit[1]!
  }
  return 1
}

/** `GetTitanShockReduction` when AttackSpeedSlow is supplied by the caller. */
export function titanShockReduction(
  enemyMassOnActivate: number,
  attackSpeedSlow: number,
): number {
  return titanShockMassFactor(enemyMassOnActivate) * attackSpeedSlow
}

/**
 * `ApplyTitanShock` cooldown multiply when shocked flags are set:
 * `atkCooldown *= (reduction + 1)`.
 */
export function applyTitanShockAttackCooldown(
  atkCooldown: number,
  enemyMassOnActivate: number,
  attackSpeedSlow: number,
): number {
  return atkCooldown * (titanShockReduction(enemyMassOnActivate, attackSpeedSlow) + 1)
}

export const CC_TIMER_FIELDS = [
  'stunTime',
  'poisonTime',
  'poisonCount',
  'lingerTime',
  'fearedTime',
  'blackHoleTime',
  'shockwaveTime',
] as const
