/**
 * Damage Reduction calculator pipeline — game layers from `CalculateDamageReductionResult`
 * plus site module layers (NMP, PC, Chain Thunder).
 */
/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    DamageReduxLayerConfig, DamageReduxLayerKey, DamageReduxLayerStep, applyDamageReduxLayerStack, effectiveRelativeDefenseReductionPct
 * depends    src/mechanics/combat/damage-reduction, src/mechanics/primitives/math
 * used by    src/mechanics/calculators/specs-generated, src/mechanics/combat/index
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
import {
  applyAbsoluteDefense,
  applyRelativeDefense,
  effectiveRelativeDefenseReductionPct,
} from './damage-reduction'
import { clamp } from '../primitives/math'

export interface DamageReduxLayerConfig {
  useDefense: boolean
  defenseRel: number
  useDefAbs: boolean
  defenseAbsolute: number
  useChrono: boolean
  chronoReductionPct: number
  useFlameBot: boolean
  flameBotReductionPct: number
  useNmp: boolean
  nmpTotalReductionPct: number
  usePc: boolean
  pcReductionPct: number
  useChainThunder: boolean
  chainThunderReductionPct: number
}

export type DamageReduxLayerKey =
  | 'defenseRel'
  | 'defenseAbsolute'
  | 'chrono'
  | 'flameBot'
  | 'nmp'
  | 'pc'
  | 'chainThunder'

export interface DamageReduxLayerStep {
  key: DamageReduxLayerKey
  /** Display reduction percent for this layer. */
  reductionPct: number
  value: number
  prev: number
  reduced: number
}

function multFromReductionPct(pct: number): number {
  return clamp(1 - pct / 100, 0, 1)
}

export { effectiveRelativeDefenseReductionPct } from './damage-reduction'

/** Apply full reduction stack; returns final damage and ordered layer steps. */
export function applyDamageReduxLayerStack(
  rawDamage: number,
  config: DamageReduxLayerConfig,
): { final: number, steps: DamageReduxLayerStep[] } {
  const steps: DamageReduxLayerStep[] = []
  let working = rawDamage

  // Matches `computeDamageReductionResult` + run blocked-stat order:
  // Defense % → Defense Absolute → chrono → CT → flame → PC → NMP.
  if (config.useDefense && config.defenseRel > 0) {
    const prev = working
    working = applyRelativeDefense(working, config.defenseRel)
    steps.push({
      key: 'defenseRel',
      reductionPct: effectiveRelativeDefenseReductionPct(config.defenseRel),
      value: working,
      prev,
      reduced: prev - working,
    })
  }

  if (config.useDefAbs && config.defenseAbsolute > 0) {
    const prev = working
    working = applyAbsoluteDefense(working, config.defenseAbsolute)
    steps.push({
      key: 'defenseAbsolute',
      reductionPct: prev > 0 ? ((prev - working) / prev) * 100 : 0,
      value: working,
      prev,
      reduced: prev - working,
    })
  }

  const moduleLayers: Array<{ key: DamageReduxLayerKey; pct: number; capAt50?: boolean }> = [
    { key: 'chrono', pct: config.useChrono ? config.chronoReductionPct : 0 },
    { key: 'chainThunder', pct: config.useChainThunder ? config.chainThunderReductionPct : 0 },
    { key: 'flameBot', pct: config.useFlameBot ? config.flameBotReductionPct : 0 },
    { key: 'pc', pct: config.usePc ? config.pcReductionPct : 0 },
    { key: 'nmp', pct: config.useNmp ? config.nmpTotalReductionPct : 0, capAt50: true },
  ]

  for (const layer of moduleLayers) {
    if (layer.pct <= 0) continue
    const reductionPct = layer.capAt50 ? Math.min(layer.pct, 50) : layer.pct
    const prev = working
    working *= multFromReductionPct(reductionPct)
    steps.push({
      key: layer.key,
      reductionPct,
      value: working,
      prev,
      reduced: prev - working,
    })
  }

  return { final: clamp(working, 0, Number.MAX_VALUE), steps }
}
