/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    KnockbackInput, knockbackDisplacement, KnockbackImpulseInput, knockbackImpulseApplied
 * depends    —
 * used by    src/mechanics/calculators/specs-generated, src/mechanics/combat/index
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
/**
 * Knockback impulse from workshop force stats and enemy mass.
 */

export interface KnockbackInput {
  knockbackForce: number
  forceMultiplier?: number
  enemyMass: number
}

export function knockbackDisplacement(input: KnockbackInput): number {
  const force = input.knockbackForce * (input.forceMultiplier ?? 1)
  if (input.enemyMass <= 0) return 0
  return force / input.enemyMass
}

export interface KnockbackImpulseInput {
  knockbackForce: number
  massScale: number
  existingVelocity?: number
  randomImpulse?: number
}

export function knockbackImpulseApplied(input: KnockbackImpulseInput): number {
  const impulse = input.knockbackForce * input.massScale + (input.randomImpulse ?? 0)
  const existing = Math.abs(input.existingVelocity ?? 0)
  if (impulse <= existing) return 0
  return impulse
}
