/**
 * Ultimate weapon hit damage — the part every ultimate weapon shares.
 *
 * Whatever deals the hit, the same two steps run first:
 *
 *   moduleMult = module bonus for the slot + 1.0
 *   effective  = max(0, incomingDamage − enemyAbsorbPool)
 *
 * The absorb pool depletes first; whatever is left over counts as tower damage.
 *
 * ## Chain Lightning
 *
 *   base = incoming × moduleMult
 *   if elite (type 7–8) and lab active:
 *     stackMult = labValue × hitCount² + 1
 *     base ×= stackMult
 *     hitCount += 1
 *
 * ## Black Hole / Death Ray absorb
 *
 *   pool -= damage; if pool < 0, credit overflow to Main totals and clamp pool.
 */
/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    ultimateModuleMultiplier, UltimateAbsorbInput, UltimateAbsorbResult, applyUltimateAbsorbPool, LightningStackInput, lightningDamageWithStack, nextLightningHitCount, isLightningEliteType
 * depends    —
 * used by    src/mechanics/calculators/specs-generated, src/mechanics/combat/index, src/mechanics/combat/land-mines, src/mechanics/modules/ilm-charge
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */

/** Ultimate benefit pattern: returned mult is `bonus + 1`. */
export function ultimateModuleMultiplier(moduleBonus: number): number {
  return moduleBonus + 1
}

export interface UltimateAbsorbInput {
  incomingDamage: number
  absorbPool: number
}

export interface UltimateAbsorbResult {
  damageApplied: number
  absorbPool: number
  overflow: number
}

export function applyUltimateAbsorbPool(input: UltimateAbsorbInput): UltimateAbsorbResult {
  const nextPool = input.absorbPool - input.incomingDamage
  if (nextPool >= 0) {
    return {
      damageApplied: input.incomingDamage,
      absorbPool: nextPool,
      overflow: 0,
    }
  }
  return {
    damageApplied: input.absorbPool,
    absorbPool: 0,
    overflow: -nextPool,
  }
}

export interface LightningStackInput {
  baseDamage: number
  moduleBonus: number
  labValue: number
  hitCount: number
  isEliteType: boolean
  labActive: boolean
}

export function lightningDamageWithStack(input: LightningStackInput): number {
  let dmg = input.baseDamage * ultimateModuleMultiplier(input.moduleBonus)
  if (input.isEliteType && input.labActive && input.hitCount >= 1) {
    const stackMult = input.labValue * input.hitCount * input.hitCount + 1
    dmg *= stackMult
  }
  return dmg
}

export function nextLightningHitCount(hitCount: number): number {
  return hitCount + 1
}

/** True when enemy.type − 7 ∈ [0, 1] (Ray / Scatter elites). */
export function isLightningEliteType(enemyType: number): boolean {
  const t = enemyType - 7
  return t >= 0 && t <= 1
}
