/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    BotLabInfoRow, BotStatUnit, BotStatDefinition, BotValueRow, BotStatRow, BotUpgradeTierData, BotPlusData, BotData (+59 more)
 * depends    src/mechanics/bots/hit-multiplier, src/mechanics/bots/overlap, src/mechanics/uptime/compute
 * used by    src/data/bots/index, src/data/index, src/internal/local-state/bot-medal-splitter, src/internal/local-state/bots-calcs, src/internal/uptime/shared-inputs, src/knowledge/compartments/bots (+10 more)
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
export interface BotLabInfoRow {
  name: string
  maxLevel: number
  maxValue: string
}

/** The units a bot stat is measured in. Carried by the stat, not by its text. */
export type BotStatUnit = '%' | 's' | 'x' | 'M'

/**
 * A bot stat as the game defines it: a straight line.
 *
 * Every one of the 25 ladders is exactly `base + perLevel * level` over contiguous levels
 * from 0, in a single unit — checked against the game's own `Bots.Initialize` tables, and
 * checked again against the authored strings this replaced.
 *
 * They used to be thirty-odd formatted strings apiece — `'20s'`, `'2.2x'`, `'18M'` — which
 * made the unit part of the value's text. Every consumer then stripped the suffix to get a
 * number and re-attached one to display it; the medal planner did that three and a half
 * MILLION times for a single plan. Worse than the cost, it made the unit a convention rather
 * than a fact, which is the same weakness that let `coverageScale` be a fraction that five
 * heuristics read as a scale.
 */
export interface BotStatDefinition {
  /** Value at level 0. */
  base: number
  /** Added per level. Negative for Cooldown, where lower is better. */
  perLevel: number
  /** Highest level, inclusive; levels run 0..maxLevel. */
  maxLevel: number
  unit: BotStatUnit
}

export interface BotValueRow {
  level: number
  /** Formatted for display, e.g. `'22.5s'`. */
  value: string
  /** The same thing as a number, so a model never has to parse the string back. */
  number: number
  cost: number
}

export interface BotStatRow {
  name: string
  levels: BotValueRow[]
}

export interface BotUpgradeTierData {
  statOrder: string[]
  costs: number[]
  stats: Record<string, BotStatDefinition>
}

export interface BotPlusData extends BotUpgradeTierData {
  label: string
  unlockStoneCost: number
}

export interface BotData extends BotUpgradeTierData {
  name: string
  label: string
  unlockIndex: number
  labInfo: BotLabInfoRow[]
  plus?: BotPlusData
}

export type BotLabLevels = Record<string, number | undefined>
export type BotUpgradeTier = 'base' | 'plus'

import { computeUptimeRatio } from '../../mechanics/uptime/compute'
import { botBotBoostedMultiplier } from '../../mechanics/bots/hit-multiplier'
import { botBotAmplificationApplicationFraction } from '../../mechanics/bots/overlap'

/**
 * Flame Bot has no Duration stat. The game returns a fixed three seconds for it, so its
 * uptime is `3 / cooldown` rather than a ratio of two stats — and there is no duration lab
 * or duration level to spend on.
 */
export const FLAME_BOT_FIXED_DURATION_SECONDS = 3

export interface BotBotOverlapArgs {
  towerRange: number
  otherRangeValue: string
  botBotRangeValue: string
  sharedPath?: boolean
}

export const BOT_BASE_UNLOCK_COSTS = [0, 150, 300, 600, 900, 1200]
export const BOT_PLUS_UNLOCK_COST = 1250
export const BOT_SYNC_SLOT_COST = 1500

/**
 * Bot+ ladders from `Bots.Initialize` (game v29.0.0):
 * `plusMaxLevel` / `plusBaseBenefit` / `plusBenefitPerLevel`.
 * Index order = `Bot.BotType`: Flame, Thunder, Golden, Amplify, Bot.
 *
 * Thunder Titan Shock (index 1): `0.05 + 0.01 * level` → UI `5%…25%` over levels 0…20.
 */
export const BOT_PLUS_MAX_LEVEL_V29 = [20, 20, 25, 9, 20] as const
export const BOT_PLUS_BASE_BENEFIT_V29 = [1.5, 0.05, 1.25, 3.0, 1.25] as const
export const BOT_PLUS_BENEFIT_PER_LEVEL_V29 = [0.1, 0.01, 0.05, 1.0, 0.05] as const

/** BotType index for Thunder / Titan Shock in the Bot+ float arrays. */
export const BOT_PLUS_INDEX_THUNDER_TITAN_SHOCK = 1 as const

const BASE_RANGE_ANCHOR = 60
const SHARED_BOT_COSTS = [0, 100, 140, 180, 220, 260, 300, 340, 380, 420, 460, 500, 540, 580, 620, 660, 700, 740, 780, 820, 860, 900, 940, 980, 1020, 1060, 1100, 1140, 1180, 1220, 1260]
const SHARED_BOT_PLUS_COSTS = [0, 100, 150, 200, 250, 300, 350, 400, 450, 500, 550, 600, 650, 700, 750, 800, 850, 900, 950, 1000, 1050, 1100, 1150, 1200, 1250, 1300]

const COMMON_DURATION_COOLDOWN_LABS: BotLabInfoRow[] = [
  { name: 'Duration', maxLevel: 20, maxValue: '10s' },
  { name: 'Cooldown', maxLevel: 25, maxValue: '-25s' },
]

function buildPlusData(label: string, statName: string, stat: BotStatDefinition): BotPlusData {
  return {
    label,
    unlockStoneCost: BOT_PLUS_UNLOCK_COST,
    statOrder: [statName],
    costs: SHARED_BOT_PLUS_COSTS,
    stats: { [statName]: stat },
  }
}

export const BOT_UPGRADES_DATA: BotData[] = [
  {
    name: 'Flame Bot',
    label: 'Flame Bot',
    unlockIndex: 0,
    statOrder: ['Damage Reduction', 'Cooldown', 'Damage', 'Range'],
    costs: SHARED_BOT_COSTS,
    stats: {
      'Damage Reduction': { base: 20, perLevel: 3, maxLevel: 25, unit: '%' },
      Cooldown: { base: 75, perLevel: -3, maxLevel: 15, unit: 's' },
      // Not a damage stat in practice: the Bot+ description says the Enflamed amplification's
      // DURATION depends on Flame Bot damage.
      Damage: { base: 50, perLevel: 8, maxLevel: 30, unit: 'x' },
      Range: { base: 30, perLevel: 4, maxLevel: 15, unit: 'M' },
    },
    labInfo: [
      { name: 'Cooldown', maxLevel: 25, maxValue: '-25s' },
      { name: 'Burn Stack', maxLevel: 5, maxValue: '+5' },
    ],
    plus: buildPlusData('FB+', 'Wildfire', { base: 1.5, perLevel: 0.1, maxLevel: 20, unit: 'x' }),
  },
  {
    name: 'Thunder Bot',
    label: 'Thunder Bot',
    unlockIndex: 1,
    statOrder: ['Duration', 'Cooldown', 'Linger', 'Range'],
    costs: SHARED_BOT_COSTS,
    stats: {
      Duration: { base: 5, perLevel: 0.5, maxLevel: 20, unit: 's' },
      Cooldown: { base: 120, perLevel: -3, maxLevel: 15, unit: 's' },
      Linger: { base: 20, perLevel: 3, maxLevel: 20, unit: '%' },
      Range: { base: 25, perLevel: 3, maxLevel: 15, unit: 'M' },
    },
    labInfo: [
      { name: 'Cooldown', maxLevel: 25, maxValue: '-25s' },
      // Not used by any calculation yet; listed so the lab the player actually
      // has ("Thunder Bot - Linger Time") is imported and shown like the rest.
      { name: 'Linger Time', maxLevel: 20, maxValue: '+20' },
    ],
    plus: buildPlusData('TB+', 'Titan Shock', { base: 5, perLevel: 1, maxLevel: 20, unit: '%' }),
  },
  {
    name: 'Golden Bot',
    label: 'Golden Bot',
    unlockIndex: 2,
    statOrder: ['Duration', 'Cooldown', 'Bonus', 'Range'],
    costs: SHARED_BOT_COSTS,
    stats: {
      Duration: { base: 20, perLevel: 0.5, maxLevel: 30, unit: 's' },
      Cooldown: { base: 120, perLevel: -3, maxLevel: 15, unit: 's' },
      Bonus: { base: 2, perLevel: 0.2, maxLevel: 30, unit: 'x' },
      Range: { base: 20, perLevel: 2, maxLevel: 20, unit: 'M' },
    },
    labInfo: [...COMMON_DURATION_COOLDOWN_LABS],
    // Cells, not coins: "Elites killed in Golden Bot range grant {0}x more Cells."
    plus: buildPlusData('GB+', 'Bonus Cell', { base: 1.25, perLevel: 0.05, maxLevel: 25, unit: 'x' }),
  },
  {
    name: 'Amplify Bot',
    label: 'Amplify Bot',
    unlockIndex: 3,
    statOrder: ['Duration', 'Cooldown', 'Bonus', 'Range'],
    costs: SHARED_BOT_COSTS,
    stats: {
      Duration: { base: 20, perLevel: 0.5, maxLevel: 30, unit: 's' },
      Cooldown: { base: 120, perLevel: -3, maxLevel: 15, unit: 's' },
      Bonus: { base: 3.5, perLevel: 0.4, maxLevel: 30, unit: 'x' },
      Range: { base: 25, perLevel: 2, maxLevel: 18, unit: 'M' },
    },
    labInfo: [...COMMON_DURATION_COOLDOWN_LABS],
    plus: {
      label: 'AB+',
      unlockStoneCost: BOT_PLUS_UNLOCK_COST,
      statOrder: ['Echoing Shot'],
      // Amplify alone steps 200 a level where every other bot steps 50, so it cannot share
      // SHARED_BOT_PLUS_COSTS. `GetBotPlusUpgradeCostAtLevel` is 100 + level * 200 for it.
      costs: [0, 100, 300, 500, 700, 900, 1100, 1300, 1500, 1700],
      stats: { 'Echoing Shot': { base: 3, perLevel: 1, maxLevel: 9, unit: 'x' } },
    },
  },
  {
    name: 'Bot Bot',
    label: 'Bot Bot',
    unlockIndex: 4,
    statOrder: ['Duration', 'Cooldown', 'Bonus', 'Range'],
    costs: SHARED_BOT_COSTS,
    stats: {
      Duration: { base: 20, perLevel: 0.5, maxLevel: 30, unit: 's' },
      Cooldown: { base: 120, perLevel: -3, maxLevel: 15, unit: 's' },
      // This is the whole of the Bot Bot's amplification of other bots' BASE effects. It
      // lands on exactly 2.0 at its odd cap of 19.
      Bonus: { base: 1.05, perLevel: 0.05, maxLevel: 19, unit: 'x' },
      Range: { base: 20, perLevel: 2, maxLevel: 20, unit: 'M' },
    },
    labInfo: [...COMMON_DURATION_COOLDOWN_LABS],
    // Boosts the BOT+ abilities of other bots, not their base effects.
    plus: buildPlusData('BB+', 'Maximum Power', { base: 1.25, perLevel: 0.05, maxLevel: 20, unit: 'x' }),
  },
]

/**
 * Stat values are authored as display strings — `'20s'`, `'2x'`, `'18m'` — and every consumer
 * parses them back to numbers. The medal planner does this 3.5 MILLION times for a single
 * plan, because the beam search re-derives each bot's metrics for every candidate it scores.
 *
 * The set of distinct strings is tiny and fixed: it is the catalog. Memoising turns the
 * regex-and-parse into a Map lookup, which is where most of a plan's time was going.
 *
 * The real fix is for the numbers not to be strings at all. Until the catalog carries typed
 * values with their units, this keeps the cost off the hot path without changing a result.
 */
const parsedNumberCache = new Map<string, number>()
const parsedUnitCache = new Map<string, string>()

function parseBaseNumber(value: string): number {
  const cached = parsedNumberCache.get(value)
  if (cached !== undefined) return cached
  const parsed = Number.parseFloat(value.replace(/[^\d.-]/g, ''))
  parsedNumberCache.set(value, parsed)
  return parsed
}

function parseUnit(value: string): string {
  const cached = parsedUnitCache.get(value)
  if (cached !== undefined) return cached
  const unit = value.replace(/[\d.-]/g, '')
  parsedUnitCache.set(value, unit)
  return unit
}

function formatNumber(value: number): string {
  if (!Number.isFinite(value)) return '0'
  const rounded = Math.round(value * 100) / 100
  return Number.isInteger(rounded) ? String(rounded) : rounded.toFixed(2).replace(/\.0+$/, '').replace(/(\.\d*[1-9])0+$/, '$1')
}

function resolveBotLabAdjustment(bot: BotData, statName: string, labLevels: BotLabLevels): number {
  const lab = bot.labInfo.find(entry => entry.name === statName)
  if (!lab) return 0

  const appliedLevel = Math.max(0, Math.min(Number(lab.maxLevel) || 0, Number(labLevels[statName] ?? 0)))
  if (!Number.isFinite(appliedLevel) || appliedLevel === 0) return 0

  const maxLevel = Number(lab.maxLevel) || 0
  if (maxLevel <= 0) return 0

  const totalAdjustment = parseBaseNumber(lab.maxValue)
  if (!Number.isFinite(totalAdjustment)) return 0

  return (totalAdjustment / maxLevel) * appliedLevel
}

function getTierData(bot: BotData, tier: BotUpgradeTier): BotUpgradeTierData | null {
  if (tier === 'plus') {
    return bot.plus ?? null
  }
  return bot
}

/**
 * A stat's value at a level, as a number.
 *
 * The single place the ladder is evaluated. Levels outside 0..maxLevel clamp rather than
 * extrapolating, because a level a bot cannot reach has no value.
 */
export function botStatValueAt(stat: BotStatDefinition, level: number): number {
  const clamped = Math.max(0, Math.min(stat.maxLevel, Math.floor(Number(level) || 0)))
  return stat.base + stat.perLevel * clamped
}

/** The same value formatted the way the game shows it. */
export function formatBotStatValue(stat: BotStatDefinition, level: number): string {
  return `${formatNumber(botStatValueAt(stat, level))}${stat.unit}`
}

function getTierStatRows(bot: BotData, tier: BotUpgradeTier, labLevels: BotLabLevels = {}): BotStatRow[] {
  const tierData = getTierData(bot, tier)
  if (!tierData) return []

  return tierData.statOrder.map((name) => {
    const stat = tierData.stats[name]
    // A lab shifts the whole ladder; it does not change its shape.
    const adjustment = stat && tier === 'base' ? resolveBotLabAdjustment(bot, name, labLevels) : 0

    const levels = tierData.costs.map((cost, level) => {
      // The shared cost ladder is 31 long and no stat uses all of it. Levels past a stat's
      // own ceiling are blank rows, not upgrades that can be bought.
      if (!stat || level > stat.maxLevel) {
        return { level, value: '', number: Number.NaN, cost }
      }
      const value = botStatValueAt(stat, level) + adjustment
      return { level, value: `${formatNumber(value)}${stat.unit}`, number: value, cost }
    })

    return { name, levels }
  })
}

/**
 * The highest level a single bot stat actually reaches.
 *
 * Every bot carries one shared `costs` ladder of 31 entries, and no stat uses all of it. Flame
 * Bot's Damage runs to 30; its Cooldown and Range stop at 15. Reading `costs.length` as "levels
 * available" therefore offers upgrades that do not exist and charges medals for them — 14,700 of
 * them on Flame Bot Cooldown, which is most of the total.
 *
 * The ceiling is a property of the STAT, not of the bot, and it is already in the stat's own level
 * table. This reads it there rather than anywhere restating it.
 */
export function botStatMaxLevel(bot: BotData, statName: string, tier: BotUpgradeTier = 'base'): number {
  return getTierData(bot, tier)?.stats?.[statName]?.maxLevel ?? 0
}

export function findBotByName(botName: string): BotData | undefined {
  const normalized = botName.trim().toLowerCase() === 'coin bot'
    ? 'golden bot'
    : botName.trim().toLowerCase()
  return BOT_UPGRADES_DATA.find(bot => bot.name.toLowerCase() === normalized || bot.label.toLowerCase() === normalized)
}

export function findBotStatIndex(bot: BotData, statName: string, tier: BotUpgradeTier = 'base'): number {
  const tierData = getTierData(bot, tier)
  if (!tierData) return -1
  const normalized = statName.trim().toLowerCase()
  return tierData.statOrder.findIndex(name => name.toLowerCase() === normalized)
}

export function getBotStatNames(bot: BotData): string[] {
  return getBotTierStatNames(bot, 'base')
}

export function getBotPlusStatNames(bot: BotData): string[] {
  return getBotTierStatNames(bot, 'plus')
}

export function getBotTierStatNames(bot: BotData, tier: BotUpgradeTier): string[] {
  const tierData = getTierData(bot, tier)
  return Array.isArray(tierData?.statOrder) ? [...tierData.statOrder] : []
}

export function getBotBaseValues(bot: BotData): string[] {
  return getBotTierBaseValues(bot, 'base')
}

export function getBotPlusBaseValues(bot: BotData): string[] {
  return getBotTierBaseValues(bot, 'plus')
}

export function getBotTierBaseValues(bot: BotData, tier: BotUpgradeTier): string[] {
  const tierData = getTierData(bot, tier)
  return tierData
    ? tierData.statOrder.map(statName => {
      const stat = tierData.stats[statName]
      return stat ? formatBotStatValue(stat, 0) : ''
    })
    : []
}

export function getBotStatValues(bot: BotData): string[][] {
  return getBotTierStatValues(bot, 'base')
}

export function getBotPlusStatValues(bot: BotData): string[][] {
  return getBotTierStatValues(bot, 'plus')
}

export function getBotTierStatValues(bot: BotData, tier: BotUpgradeTier): string[][] {
  const tierData = getTierData(bot, tier)
  if (!tierData) return []
  return tierData.statOrder.map(statName => {
    const stat = tierData.stats[statName]
    return tierData.costs.map((_, level) => (
      stat && level <= stat.maxLevel ? formatBotStatValue(stat, level) : ''
    ))
  })
}

export function getBotStatBoundsByIndex(bot: BotData, statIndex: number): { min: number; max: number } {
  return getBotTierStatBoundsByIndex(bot, 'base', statIndex)
}

export function getBotPlusStatBoundsByIndex(bot: BotData, statIndex: number): { min: number; max: number } {
  return getBotTierStatBoundsByIndex(bot, 'plus', statIndex)
}

export function getBotTierStatBoundsByIndex(bot: BotData, tier: BotUpgradeTier, statIndex: number): { min: number; max: number } {
  const values = getBotTierStatValues(bot, tier)[statIndex] ?? []
  const validLevels = values
    .map((value, level) => ({ value: String(value || '').trim(), level }))
    .filter(item => item.value.length > 0)
    .map(item => item.level)

  if (validLevels.length === 0) return { min: 0, max: 0 }
  return {
    min: Math.min(...validLevels),
    max: Math.max(...validLevels),
  }
}

export function getBotStatBoundsByName(bot: BotData, statName: string): { min: number; max: number } {
  return getBotTierStatBoundsByName(bot, 'base', statName)
}

export function getBotPlusStatBoundsByName(bot: BotData, statName: string): { min: number; max: number } {
  return getBotTierStatBoundsByName(bot, 'plus', statName)
}

export function getBotTierStatBoundsByName(bot: BotData, tier: BotUpgradeTier, statName: string): { min: number; max: number } {
  const statIndex = findBotStatIndex(bot, statName, tier)
  if (statIndex < 0) return { min: 0, max: 0 }
  return getBotTierStatBoundsByIndex(bot, tier, statIndex)
}

export function normalizeBotStats(bot: BotData, labLevels: BotLabLevels = {}): BotStatRow[] {
  return getTierStatRows(bot, 'base', labLevels)
}

export function normalizeBotPlusStats(bot: BotData): BotStatRow[] {
  return getTierStatRows(bot, 'plus')
}

export function normalizeBotTierStats(bot: BotData, tier: BotUpgradeTier, labLevels: BotLabLevels = {}): BotStatRow[] {
  return getTierStatRows(bot, tier, labLevels)
}

/**
 * A bot stat's value at a level, as a number.
 *
 * The table stores what the game displays -- `20s`, `2.2x`, `20M` -- because
 * that is what a progress view shows. A model wants the number, and the unit is
 * carried by the stat rather than by the string: `Cooldown` is always seconds,
 * `Bonus` always a multiplier. So the suffix is stripped rather than
 * interpreted, and a stat whose string is not a number at all returns `null`
 * rather than `0`, which would read as a real value.
 *
 * The level is the *base* tier's, and lab levels are deliberately not applied
 * -- callers that want them add their own, as the effective paths do for the
 * Gold Bot's cooldown.
 */
export function botStatValue(
  botLabel: string,
  statName: string,
  level: number,
): number | null {
  const bot = findBotByName(botLabel)
  const stat = bot?.stats[statName]
  if (!stat) return null

  const value = botStatValueAt(stat, level)
  return Number.isFinite(value) ? value : null
}

export function getBotStatMinLevel(stat: BotStatRow): number {
  const valid = stat.levels.filter(level => level.value !== '')
  if (!valid.length) return 0
  return Math.min(...valid.map(level => level.level))
}

export function getBotStatMaxLevel(stat: BotStatRow): number {
  const valid = stat.levels.filter(level => level.value !== '')
  if (!valid.length) return 0
  return Math.max(...valid.map(level => level.level))
}

export interface BotCostPreviewRow {
  level: number
  value: string
  cost: number
  cumulativeCost: number
}

export function buildBotStatCostRows(stat: BotStatRow, startLevel: number, targetLevel: number): BotCostPreviewRow[] {
  const clampedStart = Math.max(0, Math.trunc(startLevel))
  const clampedTarget = Math.max(clampedStart, Math.trunc(targetLevel))
  const rows: BotCostPreviewRow[] = []
  let cumulativeCost = 0

  for (const level of stat.levels) {
    if (level.level <= clampedStart || level.level > clampedTarget || level.value === '') {
      continue
    }

    cumulativeCost += level.cost
    rows.push({
      level: level.level,
      value: level.value,
      cost: level.cost,
      cumulativeCost,
    })
  }

  return rows
}

export function sumBotStatCostsBetween(stat: BotStatRow, startLevel: number, targetLevel: number): number {
  return buildBotStatCostRows(stat, startLevel, targetLevel).reduce((total, row) => total + row.cost, 0)
}

export function sumBotAllStatCosts(stats: BotStatRow[], startLevels: number[], targetLevels?: number[]): number {
  return stats.reduce((total, stat, index) => {
    const start = startLevels[index] ?? getBotStatMinLevel(stat)
    const target = targetLevels?.[index] ?? getBotStatMaxLevel(stat)
    return total + sumBotStatCostsBetween(stat, start, target)
  }, 0)
}

export function getBotUnlockCost(unlockedBotCount: number): number {
  const clamped = Math.max(0, Math.min(BOT_BASE_UNLOCK_COSTS.length - 1, Math.trunc(unlockedBotCount)))
  return BOT_BASE_UNLOCK_COSTS[clamped] ?? 0
}

export function sumBotUnlockCosts(unlockedBotCount: number): number {
  const clamped = Math.max(0, Math.min(BOT_UPGRADES_DATA.length, Math.trunc(unlockedBotCount)))
  let total = 0
  for (let index = 1; index <= clamped; index += 1) {
    total += getBotUnlockCost(index)
  }
  return total
}

/** Assign sequential unlock slots (1st = 150, 2nd = 300, …) among enabled base bots. */
export function getEnabledBotUnlockOrder(
  enabledLabels: readonly string[],
  orderLabels?: readonly string[],
): string[] {
  const enabledSet = new Set(enabledLabels)
  const canonicalOrder = orderLabels?.length
    ? [...orderLabels]
    : BOT_UPGRADES_DATA.map(bot => bot.label)

  const ordered: string[] = []
  for (const label of canonicalOrder) {
    if (enabledSet.has(label) && !ordered.includes(label)) ordered.push(label)
  }
  for (const label of enabledLabels) {
    if (!ordered.includes(label)) ordered.push(label)
  }
  return ordered
}

export function buildBotUnlockOrdinalByLabel(
  enabledLabels: readonly string[],
  orderLabels?: readonly string[],
): Map<string, number> {
  const ordinals = new Map<string, number>()
  getEnabledBotUnlockOrder(enabledLabels, orderLabels).forEach((label, index) => {
    ordinals.set(label, index + 1)
  })
  return ordinals
}

export function getBotUnlockCostForEnabledBot(
  botLabel: string,
  enabledLabels: readonly string[],
  orderLabels?: readonly string[],
): number {
  const ordinal = buildBotUnlockOrdinalByLabel(enabledLabels, orderLabels).get(botLabel)
  if (!ordinal) return 0
  return getBotUnlockCost(ordinal)
}

export function sumBotPlusUnlockCosts(unlockedPlusCount: number): number {
  const clamped = Math.max(0, Math.min(BOT_UPGRADES_DATA.length, Math.trunc(unlockedPlusCount)))
  return clamped * BOT_PLUS_UNLOCK_COST
}

export function sumBotSyncSlotCosts(slotCount: number): number {
  return Math.max(0, Math.trunc(slotCount)) * BOT_SYNC_SLOT_COST
}

export function parseBotMetricValue(value: string): number {
  return parseBaseNumber(value)
}

export function formatBotMetricValue(value: number, unit: string): string {
  return `${formatNumber(value)}${unit}`
}

export function getBotEffectiveRangeValue(rangeValue: string, towerRange = BASE_RANGE_ANCHOR): number {
  const baseRange = parseBaseNumber(rangeValue)
  if (!Number.isFinite(baseRange) || baseRange <= 0) return 0
  const rangeRatio = Math.max(0, Number(towerRange) || 0) / BASE_RANGE_ANCHOR
  return baseRange * rangeRatio
}

export function getBotEffectiveRangeScale(rangeValue: string, towerRange = BASE_RANGE_ANCHOR): number {
  const effectiveRange = getBotEffectiveRangeValue(rangeValue, towerRange)
  if (effectiveRange <= 0) return 0
  return (effectiveRange * effectiveRange) / (BASE_RANGE_ANCHOR * BASE_RANGE_ANCHOR)
}

export function getBotCoverageFraction(rangeValue: string, towerRange = BASE_RANGE_ANCHOR): number {
  return Math.min(1, getBotEffectiveRangeScale(rangeValue, towerRange))
}

export function estimateBotBotOverlapFraction(args: BotBotOverlapArgs): number {
  const otherCoverage = getBotCoverageFraction(args.otherRangeValue, args.towerRange)
  const botBotCoverage = getBotCoverageFraction(args.botBotRangeValue, args.towerRange)
  if (otherCoverage <= 0 || botBotCoverage <= 0) return 0

  const samePathOverlap = Math.min(1, botBotCoverage / Math.max(otherCoverage, Number.EPSILON))
  if (args.sharedPath) return samePathOverlap

  const randomOverlap = Math.min(1, Math.sqrt(otherCoverage * botBotCoverage))
  return Math.min(samePathOverlap, randomOverlap)
}

/**
 * The average factor the Bot Bot applies to another bot's headline stat.
 *
 * `applicationFraction` is the share of enemy-instants inside the Bot Bot's radius while it
 * is up — see `botBotAmplificationApplicationFraction`. The Bot Bot's own `Maximum Power`
 * Bot+ value is deliberately NOT an argument: the game's three amplified effects read the
 * base `Bonus` stat and nothing else, and folding Bot+ in here inflated every one of them.
 */
export function estimateBotBotAmplificationMultiplier(botBotBonusValue: string, applicationFraction: number): number {
  const botBotBonus = Math.max(1, parseBaseNumber(botBotBonusValue) || 1)
  return botBotBoostedMultiplier(botBotBonus, applicationFraction)
}

/**
 * Duration over cooldown.
 *
 * Flame has no Duration stat — the game returns a fixed 3 seconds for it — so pass
 * `FLAME_BOT_FIXED_DURATION_SECONDS` rather than looking a duration up for that bot.
 */
export function estimateBotUptimeFraction(durationValue: string, cooldownValue: string): number {
  return computeUptimeRatio(parseBaseNumber(durationValue), parseBaseNumber(cooldownValue))
}

export function estimateAmplifiedBotMetricValue(baseMetricValue: string, botBotBonusValue: string, applicationFraction: number): string {
  const baseMetric = parseBaseNumber(baseMetricValue)
  if (!Number.isFinite(baseMetric)) return baseMetricValue
  const multiplier = estimateBotBotAmplificationMultiplier(botBotBonusValue, applicationFraction)
  const unit = parseUnit(baseMetricValue)
  return formatBotMetricValue(baseMetric * multiplier, unit)
}

/**
 * A bot's stat averaged over its own uptime, with the Bot Bot's amplification averaged over
 * the fraction of the time IT applies.
 *
 * The two uptimes are separate on purpose: the amplified bot has to be up for its stat to
 * matter at all, and the Bot Bot has to be up for the amplification to land.
 */
export function estimateEffectiveAmplifiedBotMetricValue(
  baseMetricValue: string,
  botBotBonusValue: string,
  spatialOverlapFraction: number,
  botUptimeFraction: number,
  botBotUptimeFraction: number,
): string {
  const baseMetric = parseBaseNumber(baseMetricValue)
  if (!Number.isFinite(baseMetric)) return baseMetricValue
  const targetUptime = Math.max(0, Math.min(1, botUptimeFraction))
  const applied = botBotAmplificationApplicationFraction({
    botBotBonus: Math.max(1, parseBaseNumber(botBotBonusValue) || 1),
    temporalOverlapFraction: botBotUptimeFraction,
    spatialOverlapFraction,
  })
  const effectiveMultiplier = estimateBotBotAmplificationMultiplier(botBotBonusValue, applied)
  const unit = parseUnit(baseMetricValue)
  return formatBotMetricValue(baseMetric * targetUptime * effectiveMultiplier, unit)
}
