/**
 * The five bots: their unlock costs, their four upgrade stats, and the levels each stat reaches.
 *
 * The stats are NOT the same across bots and the save stores levels positionally, so the order in
 * `statOrder` is load-bearing rather than descriptive.
 */
/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    —
 * depends    src/data/bots/data
 * used by    —
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
export * from './data'
