/**
 * Frozen wave-base reference implementation, kept as a comparison baseline.
 *
 * Test-only: `wave-base-empirical-parity.test.ts` and related parity suites.
 * Production uses `wave-base-scaling.ts` → `wave-base-empirical-scaling.ts`.
 */
/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    tierDifficultyMultiplier, damageTierDifficultyMultiplier, healthTierDifficultyMultiplier, tierCoinMultiplier, WaveBaseScalingInput, computeWaveBaseHealthRaw, computeWaveBaseHealth, computeWaveBaseDamage (+3 more)
 * depends    src/mechanics/wave/_reference/wave-base-constants
 * used by    src/mechanics/calculators/specs-generated
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
import {
  DAMAGE_TIER_DIVISOR_TABLE,
  TIER_COIN_MULTIPLIER_TABLE,
  TIER_DIFFICULTY_MULTIPLIER_TABLE,
  WAVE_FORMULA,
} from './wave-base-constants'

const HEALTH = WAVE_FORMULA.health
const DAMAGE = WAVE_FORMULA.damage

type BandTerm = {
  coeff?: number
  base?: number
  divisor?: number
  crossBand?: true
  exponentFromWaveShift10?: true
  skipWhenTier?: number
}

function band(wave: number, divisor: number): number {
  return Math.floor(Math.max(1, Math.floor(wave)) / divisor)
}

/** Reciprocal-multiply form of an integer divide; kept literal so the baseline stays bit-exact. */
const CROSS_BAND_RECIPROCAL = 843_314_851

function damageCrossBandExponent(wave: number): number {
  const w = Math.max(1, Math.floor(wave)) >>> 0
  const high = Math.floor((w * CROSS_BAND_RECIPROCAL) / 2 ** 32)
  return (high + ((w - high) >> 1)) >> 6
}

function evalPoly(w: number, terms: readonly BandTerm[], plusOne: boolean): number {
  let s = plusOne ? 1 : 0
  for (const t of terms) s += (t.coeff ?? 0) * band(w, t.divisor ?? 1)
  return s
}

function evalPowChain(w: number, terms: readonly BandTerm[]): number {
  const wi = Math.max(1, Math.floor(w))
  let p = 1
  for (const t of terms) {
    let e = 0
    if (t.crossBand) e = damageCrossBandExponent(wi)
    else if (t.exponentFromWaveShift10) e = (wi >> 10) & 0x3fffff
    else e = band(wi, t.divisor ?? 1)
    if (e > 0) p *= (t.base ?? 1) ** e
  }
  return p
}

function tierExpAddon(tier: number, table: readonly number[], cap: number): number {
  const t = Math.min(21, Math.max(1, Math.round(tier)))
  if (t <= 9) return 0
  if (t <= 14) return table[t - 10] ?? 0
  return cap
}

function wave100Mult(wave: number, mult: number, active: boolean): number {
  if (!active) return 1
  const w = Math.max(1, Math.floor(wave))
  if (w < 100) return 1
  let m = 1
  let t = 100
  while (t < w) { m *= mult; t += 100 }
  return m
}

export function tierDifficultyMultiplier(tier: number): number {
  const t = Math.min(21, Math.max(1, Math.round(tier)))
  return TIER_DIFFICULTY_MULTIPLIER_TABLE[t] ?? 1
}

export const damageTierDifficultyMultiplier = tierDifficultyMultiplier
export const healthTierDifficultyMultiplier = tierDifficultyMultiplier

export function tierCoinMultiplier(tier: number): number {
  const t = Math.min(21, Math.max(1, Math.round(tier)))
  return TIER_COIN_MULTIPLIER_TABLE[t] ?? 1
}

export interface WaveBaseScalingInput {
  wave: number
  tier: number
  tournament?: boolean
  isTestingTournamentConditions?: boolean
  /** @deprecated Use isTestingTournamentConditions */
  tournamentLeague?: boolean
  tierDifficultyMultiplier?: number
  highestWaveThisTierAltBody?: boolean
}

function healthAdjust(w: number): number {
  return evalPoly(w, HEALTH.polynomialTerms, HEALTH.polyPlusOne) * evalPowChain(w, HEALTH.powChain)
}

function damageAdjust(w: number, tier: number): number {
  const t = Math.min(21, Math.max(1, Math.round(tier)))
  let p = evalPoly(w, DAMAGE.polynomialTerms, DAMAGE.polyPlusOne) * evalPowChain(w, DAMAGE.powChain)
  if (t > 6) {
    for (const term of DAMAGE.powChainTierGt6) {
      if ('skipWhenTier' in term && term.skipWhenTier != null && t === term.skipWhenTier) continue
      const e = band(w, term.divisor ?? 1)
      if (e > 0) p *= (term.base ?? 1) ** e
    }
  }
  return p * evalPowChain(w, DAMAGE.powChainLate)
}

function damageTierFactor(tier: number, tierMult: number): number {
  const t = Math.min(21, Math.max(1, Math.round(tier)))
  if (t < 4) return tierMult * DAMAGE.tierBranchLt4
  if (t < 7) return tierMult * DAMAGE.tierBranchLt7
  if (t < 10) return tierMult * DAMAGE.tierScale
  if (t <= 20) {
    const div = DAMAGE_TIER_DIVISOR_TABLE[t] || 1
    return (tierMult * DAMAGE.tierScale) / div
  }
  return (tierMult * DAMAGE.tierScale) / DAMAGE.tierCapDivisor
}

function resolveIsTesting(input: WaveBaseScalingInput): boolean {
  if (input.isTestingTournamentConditions != null) {
    return input.isTestingTournamentConditions
  }
  if (input.tournamentLeague != null) return input.tournamentLeague
  return false
}

function resolveHealthExp(input: WaveBaseScalingInput): number {
  const b = HEALTH.body
  const addon = tierExpAddon(input.tier, b.tierExpAddon_t10_14, b.tierExpCap_t15plus)
  if (input.highestWaveThisTierAltBody) {
    return HEALTH.tournamentAltExp + addon
  }
  if (!input.tournament) return b.baseExp + addon
  if (resolveIsTesting(input)) return b.tournamentBaseExpNoLeague + addon
  return b.tournamentBaseExp + addon
}

function resolveDamageExp(input: WaveBaseScalingInput): number {
  const b = DAMAGE.body
  const addon = tierExpAddon(input.tier, b.tierExpAddon_t10_14, b.tierExpCap_t15plus)
  if (!input.tournament) return b.baseExp + addon
  if (resolveIsTesting(input)) return b.tournamentBaseExp + addon
  return b.tournamentBaseExpNoLeague + addon
}

function resolveHealthBodyCoeffs(input: WaveBaseScalingInput): { a: number, b: number } {
  const hb = HEALTH.body
  if (input.tournament) {
    return { a: hb.a, b: hb.b }
  }
  return { a: hb.aNonTournament, b: hb.bNonTournament }
}

function resolveDamageBodyCoeffs(input: WaveBaseScalingInput): { a: number, b: number } {
  const db = DAMAGE.body
  if (!input.tournament) {
    return { a: db.aNonTournament, b: db.bNonTournament }
  }
  return { a: db.a, b: db.b }
}

function waveBaseHealthCore(input: WaveBaseScalingInput): number {
  const w = Math.max(1, Math.floor(input.wave))
  const t = Math.min(21, Math.max(1, Math.round(input.tier)))
  const tierMult = input.tierDifficultyMultiplier ?? tierDifficultyMultiplier(t)
  const adjust = healthAdjust(w)
  const { a, b: bodyB } = resolveHealthBodyCoeffs(input)
  const c = HEALTH.body.c
  const exp = resolveHealthExp(input)
  const wavePow = w ** exp
  const linearBody = wavePow * a + bodyB * w + c
  const w100 = wave100Mult(w, HEALTH.wave100Mult, !!input.tournament)
  let core = adjust * linearBody * w100
  if (input.tournament && !input.highestWaveThisTierAltBody) {
    core *= HEALTH.tournamentWavePowBase ** w
  }
  return core * tierMult
}

export function computeWaveBaseHealthRaw(input: WaveBaseScalingInput): number {
  return waveBaseHealthCore(input)
}

export function computeWaveBaseHealth(input: WaveBaseScalingInput): number {
  return Math.floor(waveBaseHealthCore(input))
}

export function computeWaveBaseDamage(input: WaveBaseScalingInput): number {
  const w = Math.max(1, Math.floor(input.wave))
  const t = Math.min(21, Math.max(1, Math.round(input.tier)))
  const tierMult = input.tierDifficultyMultiplier ?? tierDifficultyMultiplier(t)
  const adjust = damageAdjust(w, t)
  const exp = resolveDamageExp(input)
  const { a: bodyA, b: bodyB } = resolveDamageBodyCoeffs(input)
  const c = DAMAGE.body.c
  const linearBody = w ** exp * bodyA + bodyB * w + c
  const w100 = wave100Mult(w, DAMAGE.wave100Mult, !!input.tournament)
  const raw = adjust * linearBody * w100 * damageTierFactor(t, tierMult)
  return Math.floor(raw)
}

export const healthWave100Multiplier = (w: number, tournament = false) =>
  wave100Mult(w, HEALTH.wave100Mult, tournament)
export const damageWave100Multiplier = (w: number, tournament = false) =>
  wave100Mult(w, DAMAGE.wave100Mult, tournament)
export const wave100Multiplier = healthWave100Multiplier
