/**
 * Every field a player's save carries, by domain, and the order the game recomputes them in.
 *
 * This is the field catalog rather than a reader: it says what exists and what shape it has, which
 * is what makes it possible to check that a save-shaped object is one. The recompute order matters
 * because Damage is computed by its own function rather than with the other stats, so a list built
 * from the shared one is missing the stat everything else is measured against.
 */
/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    —
 * depends    src/data/player-stats/data, src/data/player-stats/recompute-order
 * used by    —
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
export * from './data'
export * from './recompute-order'
