/**
 * The game's asset tables — which sprite belongs to which module, card, bot or theme.
 *
 * Names only. There are no images in this package; a consumer that wants art uses these to find
 * it in their own copy of the game's files.
 */
/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    —
 * depends    src/data/assets/data
 * used by    —
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
export * from './data'
