/**
 * Invented expansions of real acronyms.
 *
 * `Omni Amplifier` shipped in this package. The failure is not that the phrase was unknown —
 * plenty of unknown Title-Case phrases are ordinary English. It is that its initials are **OA**,
 * OA is a real acronym in this game, and OA means **Orbital Augment**. The text asserted an
 * expansion for an acronym that already has one, and disagreed with it.
 *
 * That is a much narrower and much more checkable claim than "is this a real name?", which is why
 * this check exists next to `authored-names.test.ts` rather than inside it. It reports things that
 * check cannot: a phrase can be absent from every catalog and still be fine (ordinary English), but
 * a phrase whose initials collide with a known acronym and which is *not itself* a known name is
 * almost always someone expanding an acronym from memory.
 *
 * Two detectors, in order of confidence:
 *
 *   1. **Paired** — `OA (Orbital Augment)` or `Orbital Augment (OA)`. The text states the mapping
 *      outright, so it can be compared directly with the glossary. Near-zero false positives.
 *   2. **Initials** — a Title-Case phrase whose initials are a known acronym, where the phrase is
 *      neither a known expansion of it nor a known game name in its own right.
 *
 * Detector 2 needs the "known game name in its own right" escape or it drowns: `Game Speed` has
 * the initials GS, and GS is a real acronym, but `Game Speed` is a real term too and is not
 * claiming to be anything. Only a phrase that no catalog knows *and* collides is reported.
 *
 * Run: `npm run lint:acronyms` (`--json` for machine output). Covered by
 * `check-acronym-expansions.test.ts`, which plants both failure shapes.
 */
/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    PACKAGE_ROOT, AcronymFinding, buildAcronymAuthority, buildNameAuthority, scanText, textFilesUnder, scanRoots, findInventedExpansions
 * depends    src/data, src/data/glossary/glossary
 * used by    —
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */

import { readdirSync, readFileSync, statSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { GLOSSARY } from '../src/data/glossary/glossary'
import {
  ALL_PERKS,
  CARD_TEMPLATES,
  getWorkshopEnhancementDefinitions,
  GUARDIAN_CHIP_IMPORT_CATALOG,
  LAB_CATALOG,
  LAB_LEVEL_TABLE_NAME_BY_SLUG,
  LAB_RESEARCH_DISPLAY_NAME_OVERRIDES,
  MODULE_SUBSTAT_CANONICAL_DATA,
  MODULE_TEMPLATES,
  RELIC_ENUM,
  uwStoneChartData,
} from '../src/data'

const HERE = path.dirname(fileURLToPath(import.meta.url))
export const PACKAGE_ROOT = path.resolve(HERE, '..')
const MONOREPO_ROOT = path.resolve(PACKAGE_ROOT, '..', '..')

export interface AcronymFinding {
  /** `paired` — the text stated the mapping. `initials` — the phrase's initials collide. */
  readonly kind: 'paired' | 'initials'
  readonly acronym: string
  /** The expansion the text asserts. */
  readonly claimed: string
  /** What the glossary actually says the acronym means. */
  readonly known: readonly string[]
  readonly file: string
  readonly line: number
}

/** acronym (lower) → the expansions the glossary allows for it. */
export function buildAcronymAuthority(): ReadonlyMap<string, ReadonlySet<string>> {
  const authority = new Map<string, Set<string>>()
  const record = (acronym: unknown, expansion: unknown) => {
    if (typeof acronym !== 'string' || typeof expansion !== 'string') return
    const key = acronym.trim().toLowerCase()
    const value = expansion.trim().toLowerCase()
    if (!key || !value) return
    let known = authority.get(key)
    if (!known) authority.set(key, (known = new Set()))
    known.add(value)
    /*
     * The same compound splitting the name authority needs. `Coin Bot/Coin Bonus` is one glossary
     * entry covering two real expansions of `cb`; without splitting, writing either one reads as
     * a disagreement with the other.
     */
    for (const part of expansion.split('/')) {
      const trimmed = part.trim().toLowerCase()
      if (trimmed) known.add(trimmed)
    }
    const dashed = expansion.split(' - ')[0]?.trim().toLowerCase()
    if (dashed) known.add(dashed)
  }

  for (const entry of GLOSSARY) {
    if (entry.kind !== 'acronym') continue
    record(entry.term, (entry as { expansion?: string }).expansion)
  }
  /*
   * Modules carry their own initials, and those are the acronyms players actually type. The
   * glossary is generated from the catalogs, so this mostly agrees with it — but a module whose
   * initials never became a glossary entry would otherwise be an acronym with no authority, and
   * an acronym with no authority is one this check silently cannot defend.
   */
  for (const module of MODULE_TEMPLATES) record(module.initials, module.name)
  return authority
}

/** Every real name, so a phrase that merely shares initials with an acronym is not reported. */
export function buildNameAuthority(): ReadonlySet<string> {
  const names = new Set<string>()
  const add = (value: unknown) => {
    if (typeof value !== 'string') return
    const trimmed = value.trim().toLowerCase()
    if (!trimmed) return
    names.add(trimmed)
    for (const part of trimmed.split('/')) if (part.trim()) names.add(part.trim())
    /*
     * Every dash-separated part, not just the first. Lab names carry the distinguishing term on
     * either side — `Amplify Bot - Cooldown` but also `Labs Coin Discount` and
     * `Enhancement Attack - Coin Discount`, where `Coin Discount` never appears alone. Keeping
     * only the head lost it, and CD collides with Cooldown, so a real lab read as invented.
     */
    for (const part of trimmed.split(' - ')) if (part.trim()) names.add(part.trim())
  }
  for (const entry of GLOSSARY) {
    add(entry.term)
    add((entry as { expansion?: string }).expansion)
  }
  /*
   * Perks, substats and relics name stats inside a longer string — `x1.15 Defense Absolute`,
   * `Attack Range`, `No Spoon`. Adding only the whole string leaves the stat name itself unknown,
   * which is why `Attack Range`, `Defense Percent`, `Enemies Damage` and `Orb Size` were all
   * reported as invented. They are real; the authority was not looking at the catalogs that hold
   * them. Suspect the fixture before the source.
   */
  const addPhrases = (value: unknown) => {
    if (typeof value !== 'string') return
    add(value)
    for (const match of value.matchAll(/\b[A-Z][a-z-]+(?: [A-Z][a-z-]+){0,3}\b/g)) add(match[0])
  }

  for (const module of MODULE_TEMPLATES) add(module.name)
  for (const card of CARD_TEMPLATES) {
    add(card.name)
    // A card's mastery has its own name — `Electrified Net`, `Demon Revenge` — and those are
    // the names a page renders. Omitting them reported four real masteries as invented.
    addPhrases((card as { masteryName?: string }).masteryName)
  }
  for (const lab of LAB_CATALOG) addPhrases(lab.name)
  for (const perk of ALL_PERKS) addPhrases((perk as { perk?: string }).perk)
  for (const category of Object.values(MODULE_SUBSTAT_CANONICAL_DATA)) {
    addPhrases(category.title)
    // `label`, not `name`. Reading the wrong field added nothing at all and the check went on
    // reporting `Attack Range` as invented — a loop that silently contributes nothing looks
    // exactly like a loop that found nothing to contribute.
    for (const substat of category.substats ?? []) addPhrases(substat.label)
  }
  for (const relic of RELIC_ENUM) addPhrases((relic as { label?: string }).label)
  // Workshop enhancement stats — `Orb Size`, `Damage Reduction`, `Rend Armor`.
  for (const stat of getWorkshopEnhancementDefinitions()) addPhrases(stat.label)
  // Lab display names, which are what a lab is called on a page rather than its slug.
  for (const name of Object.values(LAB_LEVEL_TABLE_NAME_BY_SLUG)) addPhrases(name)
  for (const name of Object.values(LAB_RESEARCH_DISPLAY_NAME_OVERRIDES)) addPhrases(name)
  for (const chip of GUARDIAN_CHIP_IMPORT_CATALOG) {
    addPhrases((chip as { label?: string, name?: string }).label ?? (chip as { name?: string }).name)
  }
  const weapons = uwStoneChartData as Record<string, { name?: string, stats?: { name: string }[] }>
  for (const weapon of Object.values(weapons)) {
    add(weapon?.name)
    for (const stat of weapon?.stats ?? []) add(stat.name)
  }
  return names
}

/**
 * Title-Case phrases that are prose, not a claim about the game.
 *
 * Every entry is a place this check is deliberately blind, so it stays short. These are phrases
 * whose initials collide with a real acronym by coincidence — the phrase is plainly English and
 * could not be read as naming a module, card, lab or stat.
 */
const NOT_A_CLAIM = new Set([
  'the tower', 'run tracker', 'effective paths', 'google sheets', 'service account',
  'pull request', 'getting started', 'personal access', 'private network', 'quick start',
  'table of contents', 'code of conduct', 'source code', 'breaking change', 'good luck',
  /*
   * `Multiplies Cells` — the Cells card's mastery description, and a verb phrase rather than a
   * name. MC is Matter Cannon. Nothing in a catalog holds "Multiplies Cells" as a name, so the
   * authority cannot vouch for it, and no reader would take it for one.
   */
  'mod shards',
  'multiplies cells',
  /*
   * Real game terms that no catalog holds as a *name*, so the name authority cannot vouch for
   * them and their initials collide with an unrelated acronym. Each was checked by hand:
   *
   *   `Guild Season`           — a guild concept; GS is Game Speed
   *   `Damage Reduction`       — a stat; DR is Death Ray
   *   `Chrono Field Reduction` — short for the `Chrono Field Damage Reduction` lab; CFR
   *   `Lab Speed`              — a lab; LS is Lifesteal
   *   `Mod Shards`             — a label in the tracker app for module shards; MS is Matrix Sim
   *
   * They are listed rather than added to the authority because widening the authority to reach
   * them would mean sweeping in arbitrary strings, and an authority that knows every phrase
   * cannot report an invented one.
   */
  'guild season', 'damage reduction', 'chrono field reduction', 'lab speed',
])

const INITIALS_PHRASE = /\b([A-Z][a-z-]{1,}(?: [A-Z][a-z-]{1,}){1,3})\b/g
/* `OA (Orbital Augment)` — an acronym followed by a parenthesised expansion. */
const PAIRED_FORWARD = /\b([A-Z]{2,5})\s*\(([A-Z][a-z-]+(?: [A-Z][a-z-]+){0,3})\)/g
/* `Orbital Augment (OA)` — the same claim written the other way round. */
const PAIRED_REVERSE = /\b([A-Z][a-z-]+(?: [A-Z][a-z-]+){1,3})\s*\(([A-Z]{2,5})\)/g

/**
 * Words that make the surrounding text a claim that a phrase NAMES something.
 *
 * This is what separates the one real defect from 1,399 coincidences. `Omni Amplifier` was
 * written as `moduleAssetPath('Omni Amplifier')` — the function name says the argument is a
 * module, so the phrase is an assertion about the game. `'Total Cost'` sitting in an array of
 * chart axis labels asserts nothing, even though TC is a real acronym.
 *
 * Without this window the check reports every English phrase whose initials happen to be taken,
 * which with ~300 acronyms in play is most of them.
 */
const ENTITY = 'module|card|lab|bot|weapon|relic|perk|enhancement|guardian|ultimate|mastery|substat'

/**
 * The phrase is being handed to something that resolves game entities by name.
 *
 * `moduleAssetPath('Omni Amplifier')` matches: an identifier naming an entity type, then an
 * opening bracket or a colon, then the quoted phrase. A merely *nearby* mention of modules does
 * not — an earlier version allowed an 80-character window and still reported 530 findings,
 * because a page about modules mentions modules on every line while its chart axis labels
 * (`Total Coins`, `Damage Dealt`) assert nothing about the game at all.
 */
const ENTITY_WORDS = new Set(ENTITY.split('|'))
/** The identifier immediately before the opening quote: `moduleAssetPath('`, `card: "`. */
const NAMING_CALL = /([A-Za-z_$][A-Za-z0-9_$]*)\s*[([:=]\s*['"`]$/

/**
 * Split an identifier the way it was written: camelCase humps, then `_` and `-` runs.
 *
 * Done in code rather than in the pattern because the regex version could not be made to work.
 * `(?:lab)(?=[A-Z_]|\b)` looks like it rejects `label`, but the surrounding pattern carried the
 * `i` flag, and under `i` the class `[A-Z_]` also matches `e` — so `label` kept matching `lab`
 * and every `label: 'Cannon Shards'` in the tracker's stat tables read as a lab being named.
 * Segmenting the identifier and comparing whole words cannot express that mistake.
 */
function identifierWords(identifier: string): string[] {
  return identifier
    .replace(/([a-z0-9])([A-Z])/g, '$1 $2')
    .split(/[\s_$-]+/)
    .filter(Boolean)
    .map(word => word.toLowerCase())
}

function isNamedAsEntity(text: string, at: number): boolean {
  const before = text.slice(Math.max(0, at - 60), at)
  const line = before.slice(before.lastIndexOf('\n') + 1)
  const identifier = NAMING_CALL.exec(line)?.[1]
  if (!identifier) return false
  return identifierWords(identifier).some(word => ENTITY_WORDS.has(word))
}

/**
 * Two wordings of the same name, rather than a disagreement about what an acronym means.
 *
 * `Land Mines` against `land mine`, `Amp Bot` against `amplify bot`, `Enemy Attack Levels Skipped`
 * against `enemy attack level skip` — same word count, each word a prefix of its counterpart.
 * These are plurals and abbreviations of the real term, not invented expansions, and reporting
 * them buries the ones that are.
 */
function isSameWording(a: string, b: string): boolean {
  const left = a.toLowerCase().split(/[\s-]+/).filter(Boolean)
  const right = b.toLowerCase().split(/[\s-]+/).filter(Boolean)
  if (left.length !== right.length) return false
  return left.every((word, index) => {
    const other = right[index]!
    return word.startsWith(other) || other.startsWith(word)
  })
}

function initialsOf(phrase: string): string {
  return phrase.split(/[\s-]+/).filter(Boolean).map(word => word[0]!).join('').toLowerCase()
}

function lineOf(text: string, index: number): number {
  return text.slice(0, index).split('\n').length
}

export function scanText(
  text: string,
  file: string,
  acronyms: ReadonlyMap<string, ReadonlySet<string>>,
  names: ReadonlySet<string>,
  loose = false,
): AcronymFinding[] {
  const findings: AcronymFinding[] = []
  const seen = new Set<string>()

  const report = (kind: AcronymFinding['kind'], acronym: string, claimed: string, at: number) => {
    const known = acronyms.get(acronym.toLowerCase())
    if (!known || known.has(claimed.toLowerCase())) return
    if ([...known].some(expansion => isSameWording(claimed, expansion))) return
    const dedupe = `${kind}:${acronym}:${claimed}`
    if (seen.has(dedupe)) return
    seen.add(dedupe)
    findings.push({
      kind,
      acronym: acronym.toUpperCase(),
      claimed,
      known: [...known].sort(),
      file,
      line: lineOf(text, at),
    })
  }

  /*
   * A parenthetical is only an expansion claim when the initials line up. `Tank Ult (CD)` is a
   * qualifier — CD is the cooldown, not an acronym of "Tank Ult" — and reading it as a mapping
   * reported six correct chart labels as invented. Requiring initials(phrase) === acronym is
   * what makes this detector mean "the text states a mapping" rather than "brackets appear".
   */
  const pair = (acronym: string, phrase: string, at: number) => {
    if (initialsOf(phrase) !== acronym.toLowerCase()) return
    if (names.has(phrase.toLowerCase())) return
    report('paired', acronym, phrase, at)
  }
  for (const match of text.matchAll(PAIRED_FORWARD)) pair(match[1]!, match[2]!, match.index!)
  for (const match of text.matchAll(PAIRED_REVERSE)) pair(match[2]!, match[1]!, match.index!)

  for (const match of text.matchAll(INITIALS_PHRASE)) {
    const phrase = match[1]!
    const key = phrase.toLowerCase()
    /*
     * A phrase that is itself a real name is never a claim about an acronym, even when its
     * initials collide with one. Without this the check reports every correct term whose
     * initials happen to be taken, which is most of them.
     */
    if (names.has(key) || NOT_A_CLAIM.has(key)) continue
    if (!loose && !isNamedAsEntity(text, match.index!)) continue
    report('initials', initialsOf(phrase), phrase, match.index!)
  }
  return findings
}

const TEXT_FILE = /\.(ts|tsx|mts|mjs|js|vue|md|json)$/
/*
 * `assets` is deliberately NOT here. It was, to skip the artwork store — and it also skipped
 * `src/assets`, the SDK's own resolver, which is the exact file the invented module name was
 * written in. Planting `moduleAssetPath('Omni Amplifier')` there and watching the check pass is
 * how that was found. Artwork is excluded by extension instead: `TEXT_FILE` never matches a PNG.
 */
const SKIP_DIR = new Set([
  'node_modules', 'dist', 'coverage', '.git', '.wiki-build', 'generated', 'public',
])

export function textFilesUnder(root: string): string[] {
  const found: string[] = []
  const walk = (dir: string) => {
    let entries: string[]
    try {
      entries = readdirSync(dir)
    }
    catch {
      return
    }
    for (const entry of entries) {
      if (SKIP_DIR.has(entry)) continue
      const full = path.join(dir, entry)
      let isDir = false
      try {
        isDir = statSync(full).isDirectory()
      }
      catch {
        continue
      }
      if (isDir) walk(full)
      else if (TEXT_FILE.test(entry) && !entry.includes('.generated.')) found.push(full)
    }
  }
  walk(root)
  return found
}

/**
 * Everywhere a game name reaches a person: this package, and the sites that render it.
 *
 * Missing roots are skipped rather than failing. The SDK site is a sibling checkout that not every
 * machine has, and a check that cannot run anywhere but one laptop is not a check.
 */
export function scanRoots(): string[] {
  const candidates = [
    path.join(PACKAGE_ROOT, 'src'),
    path.join(PACKAGE_ROOT, 'docs'),
    path.join(PACKAGE_ROOT, 'examples'),
    path.join(PACKAGE_ROOT, 'templates'),
    path.join(PACKAGE_ROOT, 'mcp'),
    // The flagship site — the tracker webapp's own pages and components.
    path.join(MONOREPO_ROOT, 'src', 'pages'),
    path.join(MONOREPO_ROOT, 'src', 'components'),
    /*
     * The SDK site, wherever it currently lives: a sibling checkout today, and `packages/sdk/site`
     * once it is folded into this repo. Both are listed so the move does not quietly drop it.
     *
     * A missing root is skipped, which is the right behaviour on a machine that has only one of
     * them — but it also means a wrong path looks exactly like an absent checkout. The first
     * version pointed one directory too shallow and scanned nothing at all, silently.
     */
    path.resolve(MONOREPO_ROOT, '..', '..', 'TheTowerSDK-site'),
    path.resolve(MONOREPO_ROOT, '..', 'TheTowerSDK-site'),
    path.join(PACKAGE_ROOT, 'site'),
  ]
  return candidates.filter((dir) => {
    try {
      return statSync(dir).isDirectory()
    }
    catch {
      return false
    }
  })
}

export function findInventedExpansions(
  roots: string[] = scanRoots(),
  loose = false,
): AcronymFinding[] {
  const acronyms = buildAcronymAuthority()
  const names = buildNameAuthority()
  const findings: AcronymFinding[] = []
  for (const root of roots) {
    for (const file of textFilesUnder(root)) {
      if (file.includes('check-acronym-expansions')) continue
      let text: string
      try {
        text = readFileSync(file, 'utf8')
      }
      catch {
        continue
      }
      findings.push(...scanText(text, file, acronyms, names, loose))
    }
  }
  return findings
}

if (process.argv[1] && fileURLToPath(import.meta.url) === path.resolve(process.argv[1])) {
  const roots = scanRoots()
  /*
   * `--all` widens the initials detector to every Title-Case phrase, not just those handed to an
   * entity-resolving call. It is a review sweep, not a gate: it reports hundreds of coincidental
   * collisions and is meant to be read by a person once, not run in CI.
   */
  const loose = process.argv.includes('--all')
  const findings = findInventedExpansions(roots, loose)

  if (process.argv.includes('--json')) {
    console.log(JSON.stringify({ roots, findings }, null, 2))
  }
  else {
    /*
     * The file count per root is printed because "clean" and "scanned nothing" produce identical
     * output otherwise, and this check has already been wrong that way once — a root resolved one
     * directory too shallow, matched no files, and reported success for a corpus it never opened.
     */
    console.log(`Scanned ${roots.length} root(s):`)
    for (const root of roots) {
      const count = textFilesUnder(root).length
      console.log(`  ${path.relative(MONOREPO_ROOT, root) || root} — ${count} file(s)`)
      if (!count) console.log('    ^ no files matched; the path is probably wrong')
    }
    console.log('')
    if (!findings.length) {
      console.log('No invented acronym expansions.')
    }
    else {
      for (const finding of findings) {
        const where = `${path.relative(MONOREPO_ROOT, finding.file)}:${finding.line}`
        console.log(`${finding.acronym} — "${finding.claimed}" (${finding.kind})`)
        console.log(`  the glossary says: ${finding.known.join(', ')}`)
        console.log(`  ${where}`)
      }
      console.log(`\n${findings.length} invented expansion(s).`)
    }
  }
  process.exit(findings.length ? 1 : 0)
}
