#!/usr/bin/env node
/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    —
 * depends    —
 * used by    —
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
/**
 * Move source modules and repoint every import, by resolving paths rather than matching text.
 *
 * The first attempt at this rewrote specifiers with a regex on the module's last segment. That
 * turned `'../../data/bots'` into `'./read'` while moving `save/bots.ts`, because the tail matched,
 * and produced 154 type errors across twenty files. A tail is not a path.
 *
 * So: every relative specifier is RESOLVED to the absolute file it points at, looked up in the
 * move table, and written back as a path relative to wherever the importing file now lives. A
 * specifier that resolves to a file which did not move is left exactly as it was, whatever it
 * looks like.
 *
 *   node scripts/move-modules.mjs <plan.json>
 *
 * The plan is `{ "moves": { "src/save/bots.ts": "src/save/bots/read.ts", ... } }`, paths relative
 * to the package root.
 */
import { existsSync, mkdirSync, readFileSync, readdirSync, renameSync, statSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import process from 'node:process'
import { fileURLToPath } from 'node:url'

const PACKAGE_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const MONOREPO_ROOT = path.resolve(PACKAGE_ROOT, '..', '..')

const SKIP = new Set(['node_modules', 'dist', '.git', '.svelte-kit', 'build', 'dumps', 'coverage'])
const SOURCE = /\.(ts|tsx|vue|mjs)$/

function walk(dir, out = []) {
  if (!existsSync(dir)) return out
  for (const entry of readdirSync(dir)) {
    if (SKIP.has(entry)) continue
    const full = path.join(dir, entry)
    if (statSync(full).isDirectory()) walk(full, out)
    else if (SOURCE.test(full)) out.push(full)
  }
  return out
}

/** Every relative specifier in a file, with the offsets to rewrite. */
const SPECIFIER = /(from\s*|import\s*\(\s*|require\s*\(\s*)(['"])(\.[^'"]*)\2/g

/**
 * What a relative specifier points at on disk.
 *
 * Tries the extensionless forms TypeScript would, in the order it would, so a directory import
 * resolves to its index rather than to nothing.
 */
function resolveSpecifier(fromFile, specifier) {
  const base = path.resolve(path.dirname(fromFile), specifier)
  const candidates = [
    `${base}.ts`, `${base}.tsx`, `${base}.mjs`,
    path.join(base, 'index.ts'), path.join(base, 'index.mjs'),
  ]
  return candidates.find(candidate => existsSync(candidate)) ?? null
}

/**
 * The specifier that names `target` from `fromDir`.
 *
 * `./x/index.ts` normally shortens to `./x` — except where a file `x.ts` sits beside the directory
 * `x/`, because the runtime resolves the FILE first. If the importer is that file, `./x` points at
 * itself and the module exports from itself; the app reported one of these as "Detected cycle
 * while resolving name ...". Same hazard as a `workshop.json` shadowing a `workshop/` directory.
 *
 * So the `/index` is kept whenever dropping it would land on a different file than intended.
 */
function toSpecifier(fromDir, target) {
  const relative = path.relative(fromDir, target).split(path.sep).join('/')
  const shortened = relative.replace(/\/index\.(ts|mjs)$/, '').replace(/\.(ts|tsx|mjs)$/, '')

  let out = shortened
  if (relative !== shortened && /\/index\.(ts|mjs)$/.test(relative)) {
    const asFile = ['.ts', '.tsx', '.mjs']
      .map(extension => path.resolve(fromDir, shortened + extension))
      .find(candidate => existsSync(candidate))
    if (asFile) out = relative.replace(/\.(ts|mjs)$/, '')
  }

  if (!out.startsWith('.')) out = `./${out}`
  return out
}

function main() {
  const planPath = process.argv[2]
  if (!planPath) throw new Error('usage: move-modules.mjs <plan.json>')
  const plan = JSON.parse(readFileSync(planPath, 'utf8'))

  /** absolute old path -> absolute new path */
  const moves = new Map()
  for (const [from, to] of Object.entries(plan.moves)) {
    const src = path.join(PACKAGE_ROOT, from)
    if (!existsSync(src)) throw new Error(`missing ${from}`)
    moves.set(src, path.join(PACKAGE_ROOT, to))
  }

  const scope = [
    ...walk(path.join(PACKAGE_ROOT, 'src')),
    ...walk(path.join(PACKAGE_ROOT, 'tests')),
    ...walk(path.join(PACKAGE_ROOT, 'scripts')),
    /*
     * tooling/ and mcp/ ship or run beside the package and import from src. Leaving them out is
     * how the support/ move broke tooling/sdk-graph — the type-check does not cover them, so the
     * break surfaced only when the full suite ran.
     */
    ...walk(path.join(PACKAGE_ROOT, 'tooling')),
    ...walk(path.join(PACKAGE_ROOT, 'mcp')),
    ...walk(path.join(MONOREPO_ROOT, 'packages', 'platform', 'src')),
    ...walk(path.join(MONOREPO_ROOT, 'src')),
  ]

  /*
   * Resolve BEFORE moving. Once files have moved, a relative specifier in an un-moved file still
   * points where it always did, but one in a moved file would resolve against its new directory
   * and find the wrong thing — or nothing.
   */
  const edits = new Map()
  for (const file of scope) {
    const text = readFileSync(file, 'utf8')
    if (!text.includes('from') && !text.includes('require')) continue
    const found = []
    for (const match of text.matchAll(SPECIFIER)) {
      const target = resolveSpecifier(file, match[3])
      if (target) found.push({ specifier: match[3], target })
    }
    if (found.length > 0) edits.set(file, found)
  }

  /* Move. */
  for (const [from, to] of moves) {
    mkdirSync(path.dirname(to), { recursive: true })
    renameSync(from, to)
  }

  /* Rewrite. */
  let touched = 0
  let rewritten = 0
  for (const [file, found] of edits) {
    const nowAt = moves.get(file) ?? file
    const text = readFileSync(nowAt, 'utf8')
    let out = text

    for (const { specifier, target } of found) {
      const newTarget = moves.get(target) ?? target
      const wanted = toSpecifier(path.dirname(nowAt), newTarget)
      if (wanted === specifier) continue
      /* Replace only this exact quoted specifier, so a shorter one cannot be caught inside it. */
      out = out.split(`'${specifier}'`).join(`'${wanted}'`).split(`"${specifier}"`).join(`"${wanted}"`)
      rewritten += 1
    }

    if (out !== text) { writeFileSync(nowAt, out); touched += 1 }
  }

  /* A curated surface for each folder the plan creates. */
  for (const [rel, body] of Object.entries(plan.indexes ?? {})) {
    const full = path.join(PACKAGE_ROOT, rel)
    mkdirSync(path.dirname(full), { recursive: true })
    writeFileSync(full, body)
  }

  console.log(`moved ${moves.size} modules, rewrote ${rewritten} specifiers across ${touched} files`)
}

main()
