/**
 * Deciding what to buy next, rather than computing what something does.
 *
 * ROI scaling prices an upgrade against the economy it sits in, so the same upgrade is worth
 * different amounts to different accounts. Formula coverage is the other half of planning: which
 * mechanics this package can price at all, so a planner can say what it left out instead of
 * silently ranking a shorter list.
 */
/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    —
 * depends    src/mechanics/planning/formula-coverage, src/mechanics/planning/roi-scaling
 * used by    —
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
export * from './roi-scaling'
export * from './formula-coverage'
