/**
 * A1 notation — parsing, building, and the escaping rules that bite.
 *
 * Ranges are strings that carry structure, and every tool that touches a sheet ends up
 * re-deriving the same three things: which columns a range covers, how to name a tab that
 * has an apostrophe in it, and how to widen a range without going off the end of the sheet.
 */
/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    A1RangeCoordinates, columnLabelToIndex, columnIndexToLabel, quoteSheetName, buildA1Range, sheetNameFromRange, parseA1RangeToCoordinates, a1RangeCellCount (+1 more)
 * depends    —
 * used by    src/sheets/client, src/sheets/index
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */

/** Zero-based, inclusive on both ends. */
export interface A1RangeCoordinates {
  readonly startRow: number
  readonly startCol: number
  readonly endRow: number
  readonly endCol: number
}

/** `A` → 0, `Z` → 25, `AA` → 26. Returns `-1` for anything that is not a column label. */
export function columnLabelToIndex(label: string): number {
  if (!label) return -1
  let value = 0
  for (const char of label.toUpperCase()) {
    const code = char.charCodeAt(0)
    if (code < 65 || code > 90) return -1
    value = value * 26 + (code - 64)
  }
  return value - 1
}

/**
 * `0` → `A`, `25` → `Z`, `26` → `AA`.
 *
 * Spreadsheet columns are bijective base-26 — there is no zero digit — so the usual
 * base conversion is off by one at every carry and produces `A@` where it should produce
 * `Z`. Hence the decrement inside the loop.
 */
export function columnIndexToLabel(index: number): string {
  if (!Number.isInteger(index) || index < 0) return ''
  let remaining = index
  let label = ''
  while (remaining >= 0) {
    label = String.fromCharCode(65 + (remaining % 26)) + label
    remaining = Math.floor(remaining / 26) - 1
  }
  return label
}

/**
 * Quote a tab name for use in a range, if it needs it.
 *
 * A tab called `Player's Data` produces `'Player''s Data'!A1` — the apostrophe doubles.
 * Getting this wrong does not error: the API reads the truncated name, finds no such tab,
 * and returns an empty result that looks exactly like an empty range.
 */
export function quoteSheetName(name: string): string {
  if (/^[A-Za-z_][A-Za-z0-9_]*$/.test(name)) return name
  return `'${name.replace(/'/g, "''")}'`
}

/** `Tab!A1:C10` from a tab name and coordinates. Omit the tab for a bare range. */
export function buildA1Range(coordinates: A1RangeCoordinates, sheetName?: string): string {
  const start = `${columnIndexToLabel(coordinates.startCol)}${coordinates.startRow + 1}`
  const end = `${columnIndexToLabel(coordinates.endCol)}${coordinates.endRow + 1}`
  const range = `${start}:${end}`
  return sheetName ? `${quoteSheetName(sheetName)}!${range}` : range
}

/** The tab name in front of a range, unquoted, or `null` when the range has none. */
export function sheetNameFromRange(rangeExpression: string): string | null {
  const bang = rangeExpression.lastIndexOf('!')
  if (bang < 0) return null
  const raw = rangeExpression.slice(0, bang).trim()
  if (raw.startsWith("'") && raw.endsWith("'")) {
    return raw.slice(1, -1).replace(/''/g, "'")
  }
  return raw
}

/**
 * Coordinates for an `A1:C10` range, with or without a leading tab name.
 *
 * Returns `null` rather than guessing. An open-ended range (`A:C`, `A1:C`) has no row
 * bound in the string — only the sheet knows where its data stops — so it is rejected
 * here instead of being resolved to an invented last row.
 */
export function parseA1RangeToCoordinates(rangeExpression: string): A1RangeCoordinates | null {
  const bang = rangeExpression.lastIndexOf('!')
  const scoped = bang >= 0 ? rangeExpression.slice(bang + 1) : rangeExpression
  const match = /^([A-Za-z]+)(\d+):([A-Za-z]+)(\d+)$/.exec(scoped.trim())
  if (!match) return null

  const startCol = columnLabelToIndex(match[1]!)
  const endCol = columnLabelToIndex(match[3]!)
  const startRow = Number(match[2]) - 1
  const endRow = Number(match[4]) - 1
  if (startCol < 0 || endCol < 0 || startRow < 0 || endRow < 0) return null

  // Normalised, so `C10:A1` describes the same block as `A1:C10` rather than an empty one.
  return {
    startRow: Math.min(startRow, endRow),
    startCol: Math.min(startCol, endCol),
    endRow: Math.max(startRow, endRow),
    endCol: Math.max(startCol, endCol),
  }
}

/** How many cells a range covers. `0` when it does not parse. */
export function a1RangeCellCount(rangeExpression: string): number {
  const at = parseA1RangeToCoordinates(rangeExpression)
  if (!at) return 0
  return (at.endRow - at.startRow + 1) * (at.endCol - at.startCol + 1)
}

/**
 * Split a range into chunks of at most `maxCells`, top to bottom.
 *
 * The Sheets API rejects a request whose ranges are too large, and a planner that reads a
 * whole tab in one call works right up until someone's sheet grows. Splitting by rows keeps
 * every chunk a rectangle, so the pieces reassemble by concatenation.
 */
export function splitA1Range(rangeExpression: string, maxCells: number): string[] {
  const at = parseA1RangeToCoordinates(rangeExpression)
  if (!at || maxCells <= 0) return [rangeExpression]

  const sheetName = sheetNameFromRange(rangeExpression)
  const width = at.endCol - at.startCol + 1
  const rowsPerChunk = Math.max(1, Math.floor(maxCells / width))
  const chunks: string[] = []

  for (let row = at.startRow; row <= at.endRow; row += rowsPerChunk) {
    chunks.push(buildA1Range({
      startRow: row,
      startCol: at.startCol,
      endRow: Math.min(row + rowsPerChunk - 1, at.endRow),
      endCol: at.endCol,
    }, sheetName ?? undefined))
  }
  return chunks
}
