/**
 * Fold per-wave econ rows into round totals.
 * Bridge enemy-drops round API to the per-wave wave econ simulator.
 */
/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    NEUTRAL_COIN_SIMULATION_DEFAULTS, waveEconInputFromEnemyDrops, WaveEconTotals, WaveCoinTotals, foldWaveEconRows, foldWaveCoinRows, simulateWaveEconTotals, simulateWaveCoinTotals (+2 more)
 * depends    src/mechanics/enemies/drops-game-data, src/mechanics/enemies/drops-shared, src/mechanics/resource-drops/coin-simulation-types, src/mechanics/resource-drops/simulate-wave-coins, src/mechanics/resource-drops/simulate-wave-econ, src/mechanics/waves/wave-spawn-yield
 * used by    src/mechanics/calculators/specs-generated, src/mechanics/resource-drops/coin-simulation, src/mechanics/resource-drops/enemy-drop-roi, src/mechanics/resource-drops/index
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
import type { EnemyDropsSimulationInput, EnemyDropsYieldBreakdown } from '../enemies/drops-shared'
import { getEnemyDropsLabBenefits } from '../enemies/drops-game-data'
import type { WaveCoinSimRow } from './simulate-wave-coins'
import { accumulateWaveCoin, simulateWaveCoinRows } from './simulate-wave-coins'
import type { WaveEconSimRow } from './simulate-wave-econ'
import { accumulateWaveEcon, simulateWaveEconRows } from './simulate-wave-econ'
import type { ResourceDropsCoinSimulationInput } from './coin-simulation-types'
import type { WaveSpawnYieldInput } from '../waves/wave-spawn-yield'

/** Coin/UW fields at neutral values — drop yields ignore coin multipliers. */
export const NEUTRAL_COIN_SIMULATION_DEFAULTS: Omit<
  ResourceDropsCoinSimulationInput,
  keyof EnemyDropsSimulationInput
> = {
  waveAcceleratorMasteryLevel: -1,
  coinsKillWorkshopLevel: 0,
  coinsWaveWorkshopLevel: 0,
  coinBonusEnhancementLevel: 0,
  coinsKillLabLevel: 0,
  coinsWaveLabLevel: 0,
  gtBonusLabLevel: 0,
  bhCoinLabLevel: 0,
  dwCoinLabLevel: 0,
  slCoinLabLevel: 0,
  coinsCardLevel: 1,
  coinsCardMastery: 0,
  themeCoinBonusPct: 0,
  relicCoinBonusPct: 0,
  iapToggles: { hasStarterPack: false, hasEpicPack: false, hasDisableAds: false },
  moduleCoinsKillBonus: 0,
  vaultCoinskillLevel: 0,
  allCoinPerkLevel: 0,
  standardPerkBonusPct: 0,
  hasCoinTradeOffPerk: false,
  improveTradeOffLabPct: 0,
  introSprintZeroCoinWaveCap: 0,
  bhdCpkBonusPct: 0,
  gtPlusLevel: 0,
  goldenBotCoverageFraction: 1,
  goldenBotBonusLevel: 0,
  useGoldenBotCoinBonus: false,
  assumeSyncedUwCoinWindows: true,
  uwLevels: {
    gtMultiplierLevel: 0,
    gtCdLevel: 0,
    gtDurLevel: 0,
    gtCdLab: 0,
    gtDurLab: 0,
    bhCdLevel: 0,
    bhDurLevel: 0,
    bhCdLab: 0,
    bhDurLab: 0,
    dwCdLevel: 0,
    dwQtyLevel: 0,
    slCdLevel: 0,
    slQtyLevel: 0,
    slAngleLevel: 0,
  },
  botLevels: {
    gbBonusLevel: 0,
    gbCdLevel: 0,
    gbDurLevel: 0,
    gbCdLab: 0,
    gbDurLab: 0,
  },
  uptime: null,
}

export function waveEconInputFromEnemyDrops(
  input: EnemyDropsSimulationInput,
): ResourceDropsCoinSimulationInput {
  return {
    ...NEUTRAL_COIN_SIMULATION_DEFAULTS,
    ...input,
  }
}

export type WaveEconTotals = {
  expectedKills: number
  expectedEliteKills: number
  rawKillCoins: number
  waveCoins: number
  cells: number
  skipCells: number
  moduleShards: number
  moduleShardsOneType: number
  rerollShards: number
  bossWaves: number
  fleetWaves: number
}

export type WaveCoinTotals = {
  expectedKills: number
  rawKillCoins: number
  skipKillCoins: number
  waveCoins: number
  skipWaveCoins: number
}

export function foldWaveEconRows(rows: readonly WaveEconSimRow[]): WaveEconTotals {
  let expectedKills = 0
  let expectedEliteKills = 0
  let rawKillCoins = 0
  let waveCoins = 0
  let cells = 0
  let skipCells = 0
  let moduleShards = 0
  let moduleShardsOneType = 0
  let rerollShards = 0
  let bossWaves = 0
  let fleetWaves = 0

  for (const row of rows) {
    expectedKills += row.expectedKills
    expectedEliteKills += row.expectedEliteKills
    rawKillCoins += row.rawKillCoins
    waveCoins += row.waveCoins
    cells += row.cells
    skipCells += row.skipCells
    moduleShards += row.moduleShards
    moduleShardsOneType += row.moduleShardsOneType
    rerollShards += row.rerollShards
    if (row.isBossWave) bossWaves += 1
    if (row.isFleetWave) fleetWaves += 1
  }

  return {
    expectedKills,
    expectedEliteKills,
    rawKillCoins,
    waveCoins,
    cells,
    skipCells,
    moduleShards,
    moduleShardsOneType,
    rerollShards,
    bossWaves,
    fleetWaves,
  }
}

export function foldWaveCoinRows(rows: readonly WaveCoinSimRow[]): WaveCoinTotals {
  let expectedKills = 0
  let rawKillCoins = 0
  let skipKillCoins = 0
  let waveCoins = 0
  let skipWaveCoins = 0

  for (const row of rows) {
    expectedKills += row.expectedKills
    rawKillCoins += row.rawKillCoins
    skipKillCoins += row.skipKillCoins
    waveCoins += row.waveCoins
    skipWaveCoins += row.skipWaveCoins
  }

  return {
    expectedKills,
    rawKillCoins,
    skipKillCoins,
    waveCoins,
    skipWaveCoins,
  }
}

export function simulateWaveEconTotals(
  input: ResourceDropsCoinSimulationInput,
  options: { maxRows?: number; spawnYield?: WaveSpawnYieldInput } = {},
): WaveEconTotals {
  return accumulateWaveEcon(input, options)
}

export function simulateWaveCoinTotals(
  input: ResourceDropsCoinSimulationInput,
  options: { maxRows?: number; spawnYield?: WaveSpawnYieldInput; coinsPerWaveMult: number },
): WaveCoinTotals {
  return accumulateWaveCoin(input, options)
}

export function enemyDropYieldBreakdownFromWaveEconRows(
  rows: readonly WaveEconSimRow[],
  input: EnemyDropsSimulationInput,
): EnemyDropsYieldBreakdown {
  const labs = getEnemyDropsLabBenefits(input)
  let cellsFromElites = 0
  let cellsFromWaveSkip = 0
  let moduleShardsFromShatter = 0
  let rerollShardsFromBosses = 0
  let commonModulesDropped = 0
  let rareModulesDropped = 0

  for (const row of rows) {
    cellsFromElites += row.cells - row.skipCells
    cellsFromWaveSkip += row.skipCells
    moduleShardsFromShatter += row.moduleShards
    rerollShardsFromBosses += row.rerollShards
    if (row.isBossWave) {
      commonModulesDropped += labs.commonDropChance
      rareModulesDropped += labs.rareDropChance
    }
  }

  return {
    cellsFromElites,
    cellsFromWaveSkip,
    totalCells: cellsFromElites + cellsFromWaveSkip,
    moduleShardsFromDrops: 0,
    moduleShardsFromShatter,
    totalModuleShards: moduleShardsFromShatter,
    rerollShardsFromBosses,
    commonModulesDropped,
    rareModulesDropped,
  }
}

export function enemyDropYieldBreakdownFromPerWave(
  input: EnemyDropsSimulationInput,
  options: { maxRows?: number; spawnYield?: WaveSpawnYieldInput } = {},
): EnemyDropsYieldBreakdown {
  const waveInput = waveEconInputFromEnemyDrops(input)
  const rows = simulateWaveEconRows(waveInput, options)
  return enemyDropYieldBreakdownFromWaveEconRows(rows, input)
}
