/**
 * Coin multiplier model.
 *
 * Extracted verbatim from `coin-simulation.ts` so the per-wave econ simulator can
 * import `buildResourceDropsCoinMultipliers` without closing an import cycle back
 * through the hub. Bodies are unchanged; only their home moved.
 */
/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    COINS_KILL_WORKSHOP_KEY, COINS_WAVE_WORKSHOP_KEY, RESOURCE_DROPS_COIN_LAB_SLUGS, coinBonusEnhancementMult, vaultCoinskillMult, themePassiveCoinMultFromBonusPct, themePassiveCoinMult, computeLabCoinMultiplier (+7 more)
 * depends    src/data, src/mechanics/combat/uw-stat-values, src/mechanics/enemies/drops-wave-context, src/mechanics/primitives/math, src/mechanics/resource-drops/coin-iap, src/mechanics/resource-drops/coin-intro-sprint (+8 more)
 * used by    src/mechanics/calculators/specs-generated, src/mechanics/resource-drops/coin-simulation, src/mechanics/resource-drops/simulate-wave-econ
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
import { CARD_TEMPLATES, type CardTemplate } from '../../data'
import { MAX_CAMPAIGN_TIER } from '../../data'
import { findLabResearchBySlug } from '../../data'
import {
  computeLabValueAtLevel,
  getSharedToolLabs,
  type ToolLabRecord,
} from '../../data'
import {
  buildUwStatLevelEntries,
  findUwStatSpec,
  parseUwStatNumericValue,
} from '../combat/uw-stat-values'
import { BOT_UPGRADES_DATA, botStatValueAt } from '../../data'
import { WORKSHOP_DATA } from '../../data'
import { empiricalTierCoinMultiplier } from '../waves/base-empirical-scaling'
import {
  buildWaveContext,
  waveSkipResourceMultiplier,
} from '../enemies/drops-wave-context'
import { clamp } from '../primitives/math'
import {
  computeDurations,
  computeEffectiveCooldowns,
  computeUptimeRatio,
  type UptimeCoreState,
} from '../uptime/compute'
import { findWaveAcceleratorMasteryForSpawnCap } from '../waves/accelerator-spawn-rate-cap'
import {
  killsPerWaveFromSpawnContext,
  type WaveSpawnYieldInput,
} from '../waves/wave-spawn-yield'
import { resolveWaveSpawnYieldFromAccount } from '../waves/resolve-wave-spawn-yield'
import { computePackCoinMultFromIapToggles, type ResourceDropsCoinIapToggles } from './coin-iap'
import { allCoinBonusesPerkMult } from './coin-perks'
import {
  introSprintZeroCoinFraction,
} from './coin-intro-sprint'
import { coinTradeOffPerkMult } from './coin-trade-off'
import type {
  ResourceDropsCoinEconomyInputs,
  ResourceDropsCoinSimulationInput,
  ResourceDropsCoinMultiplierBreakdown,
} from './coin-simulation-types'

export const COINS_KILL_WORKSHOP_KEY = 'Coins / Kill Bonus'
export const COINS_WAVE_WORKSHOP_KEY = 'Coins / Wave'

export const RESOURCE_DROPS_COIN_LAB_SLUGS = {
  coinsKill: 'coins_kill_bonus',
  coinsWave: 'coins_per_wave',
  gtBonus: 'golden_tower_bonus',
  bhCoin: 'black_hole_coin_bonus',
  dwCoin: 'death_wave_coin_bonus',
  slCoin: 'spotlight_coin_bonus',
} as const

function findCard(cardId: string): CardTemplate | undefined {
  return CARD_TEMPLATES.find(entry => entry.id === cardId)
}

function cardLevelIndex(gameLevel: number): number {
  return clamp(Math.floor(gameLevel) - 1, 0, 6)
}

function cardLevelMulti(cardId: string, gameLevel: number): number {
  const card = findCard(cardId)
  if (!card || card.levelType !== 'multi') return 1
  const idx = cardLevelIndex(gameLevel)
  const raw = card.levelValues[idx]
  return typeof raw === 'number' ? raw : 1
}

function cardMasteryMulti(cardId: string, gameLevel: number, masteryLevel: number): number {
  const card = findCard(cardId)
  if (!card?.masteryValues?.length || gameLevel < 7) return 1
  const idx = clamp(Math.floor(masteryLevel), 0, card.masteryValues.length - 1)
  const raw = card.masteryValues[idx]
  return typeof raw === 'number' ? raw : 1
}

function cardLevelPercent(cardId: string, gameLevel: number): number {
  const card = findCard(cardId)
  if (!card || card.levelType !== 'percent') return 0
  const idx = cardLevelIndex(gameLevel)
  const raw = card.levelValues[idx]
  return typeof raw === 'number' ? raw / 100 : 0
}

function readWorkshopUtilityValue(key: string, level: number): number {
  const row = WORKSHOP_DATA[key]
  if (!row) return 1
  const clamped = Math.max(0, Math.floor(level))
  const keys = Object.keys(row).map(Number).filter(Number.isFinite).sort((a, b) => a - b)
  const resolved = keys.reduce((chosen, candidate) => (candidate <= clamped ? candidate : chosen), keys[0] ?? 0)
  return row[String(resolved)]?.value ?? 1
}

export function coinBonusEnhancementMult(level: number): number {
  const L = clamp(Math.floor(level), 0, 200)
  return 1 + L * 0.01
}

export function vaultCoinskillMult(level: number): number {
  const L = clamp(Math.floor(level), 0, 3)
  return 1 + L * 0.05
}

export function themePassiveCoinMultFromBonusPct(themeCoinBonusPct: number): number {
  const pct = Math.max(0, Number(themeCoinBonusPct) || 0)
  return 1 + pct / 100
}

/** @deprecated Prefer {@link themePassiveCoinMultFromBonusPct}. Per-category counts for legacy tests. */
export function themePassiveCoinMult(input: Pick<
  ResourceDropsCoinEconomyInputs,
  'themeCoinBonusPct'
> & Partial<{
  towerThemesOwned: number
  backgroundThemesOwned: number
  menuThemesOwned: number
  guardianThemesOwned: number
}>): number {
  if (input.themeCoinBonusPct != null && Number.isFinite(input.themeCoinBonusPct)) {
    return themePassiveCoinMultFromBonusPct(input.themeCoinBonusPct)
  }
  const tower = Math.max(0, Math.floor(input.towerThemesOwned ?? 0))
  const background = Math.max(0, Math.floor(input.backgroundThemesOwned ?? 0))
  const menu = Math.max(0, Math.floor(input.menuThemesOwned ?? 0))
  const guardian = Math.max(0, Math.floor(input.guardianThemesOwned ?? 0))
  return 1 + tower * 0.004 + background * 0.008 + menu * 0.006 + guardian * 0.006
}

function findLabRecordBySlug(slug: string): ToolLabRecord | undefined {
  const research = findLabResearchBySlug(slug)
  if (!research) return undefined
  return getSharedToolLabs().find(lab => lab.name === slug || lab.name === research.slug)
}

export function computeLabCoinMultiplier(slug: string, level: number): number {
  const lab = findLabRecordBySlug(slug)
  if (!lab || level <= 0) return slug === RESOURCE_DROPS_COIN_LAB_SLUGS.gtBonus ? 0 : 1
  return computeLabValueAtLevel(lab, Math.floor(level))
}

function uwStoneStatMult(weaponName: string, statName: string, level: number): number {
  const spec = findUwStatSpec(weaponName, statName)
  if (!spec) return 1
  const entries = buildUwStatLevelEntries(spec)
  const clamped = Math.max(0, Math.floor(level))
  const match = entries.find(entry => entry.value === clamped)
  if (match) return Math.max(1, match.baseValue)
  const last = entries[entries.length - 1]
  return Math.max(1, last?.baseValue ?? 1)
}

export function computeGoldenTowerCoinMult(stoneMultiplierLevel: number, gtBonusLabLevel: number): number {
  const stoneMult = uwStoneStatMult('Golden Tower', 'Multiplier', stoneMultiplierLevel)
  const labBonus = computeLabCoinMultiplier(RESOURCE_DROPS_COIN_LAB_SLUGS.gtBonus, gtBonusLabLevel)
  return stoneMult + labBonus
}

export function computePackCoinMult(toggles: ResourceDropsCoinIapToggles): number {
  return computePackCoinMultFromIapToggles(toggles)
}

/** Golden Tower+ combo bonus — `(1 + 0.0003 × (level + 1))^kills − 1`, distributed as a run multiplier. */
export function goldenTowerPlusCoinMult(gtPlusLevel: number, avgKillsPerGtWindow: number): number {
  const level = Math.max(0, Math.floor(Number(gtPlusLevel) || 0))
  const kills = Math.max(0, Number(avgKillsPerGtWindow) || 0)
  if (level <= 0 || kills <= 0) return 1
  const rate = 0.0003 * (level + 1)
  return 1 + (Math.pow(1 + rate, kills) - 1)
}

function parseBotStatMultiplier(botName: string, statName: string, level: number): number {
  const bot = BOT_UPGRADES_DATA.find(entry => entry.name === botName || entry.label === botName)
  if (!bot) return 1
  const stat = bot.stats[statName as keyof typeof bot.stats]
  if (!stat) return 1
  const parsed = botStatValueAt(stat, level)
  return parsed > 0 ? parsed : 1
}

function parseBotStatSeconds(botName: string, statName: string, level: number): number {
  const bot = BOT_UPGRADES_DATA.find(entry => entry.name === botName || entry.label === botName)
  if (!bot) return 0
  const stat = bot.stats[statName as keyof typeof bot.stats]
  if (!stat) return 0
  return botStatValueAt(stat, level)
}

function resolveUwUptimeRatios(
  uptime: UptimeCoreState | null,
): Pick<ResourceDropsCoinMultiplierBreakdown, 'gtUptimeRatio' | 'bhUptimeRatio' | 'dwUptimeRatio' | 'slUptimeRatio' | 'gbUptimeRatio'> {
  if (!uptime) {
    return {
      gtUptimeRatio: 0,
      bhUptimeRatio: 0,
      dwUptimeRatio: 0,
      slUptimeRatio: 0,
      gbUptimeRatio: 0,
    }
  }

  const cds = computeEffectiveCooldowns(uptime)
  const durations = computeDurations(uptime)

  const gtUptimeRatio = computeUptimeRatio(durations.gt, cds.gt)
  const bhUptimeRatio = computeUptimeRatio(durations.bh, cds.bh)
  const dwUptimeRatio = computeUptimeRatio(durations.dw, cds.dw)
  const slUptimeRatio = clamp(durations.sl / 100, 0, 1)
  const gbCd = parseBotStatSeconds('Golden Bot', 'Cooldown', uptime.gbCdLevel ?? 0)
  const gbDur = parseBotStatSeconds('Golden Bot', 'Duration', uptime.gbDurLevel ?? 0)
  const gbUptimeRatio = computeUptimeRatio(gbDur, gbCd)

  return {
    gtUptimeRatio,
    bhUptimeRatio,
    dwUptimeRatio,
    slUptimeRatio,
    gbUptimeRatio,
  }
}

/**
 * Expected multiplicative boost from timed coin sources (UW + Golden Bot).
 * When `assumeSynced`, overlapping uptime uses the product of active mults in the overlap window.
 */
export function expectedTimedCoinKillMult(
  mults: Pick<ResourceDropsCoinMultiplierBreakdown,
    | 'gtCoinMult'
    | 'bhCoinMult'
    | 'dwCoinMult'
    | 'slCoinMult'
    | 'goldenBotMult'
    | 'gtUptimeRatio'
    | 'bhUptimeRatio'
    | 'dwUptimeRatio'
    | 'slUptimeRatio'
    | 'gbUptimeRatio'
  >,
  assumeSynced: boolean,
): number {
  const entries = [
    { mult: mults.gtCoinMult, uptime: mults.gtUptimeRatio },
    { mult: mults.bhCoinMult, uptime: mults.bhUptimeRatio },
    { mult: mults.dwCoinMult, uptime: mults.dwUptimeRatio },
    { mult: mults.slCoinMult, uptime: mults.slUptimeRatio },
    { mult: mults.goldenBotMult, uptime: mults.gbUptimeRatio },
  ].filter(entry => entry.mult > 1 && entry.uptime > 0)

  if (entries.length === 0) return 1

  if (assumeSynced) {
    const overlap = entries.reduce((min, entry) => Math.min(min, entry.uptime), 1)
    const unsyncedContribution = entries.reduce((sum, entry) => {
      const solo = Math.max(0, entry.uptime - overlap)
      return sum + solo * (entry.mult - 1)
    }, 0)
    const overlapMult = entries.reduce((product, entry) => product * entry.mult, 1)
    return 1 + overlap * (overlapMult - 1) + unsyncedContribution
  }

  return entries.reduce((total, entry) => total + entry.uptime * (entry.mult - 1), 1)
}

export function buildResourceDropsCoinMultipliers(
  input: ResourceDropsCoinSimulationInput,
): ResourceDropsCoinMultiplierBreakdown {
  const tier = clamp(Math.floor(input.tier), 1, MAX_CAMPAIGN_TIER)
  const tierCoinMult = empiricalTierCoinMultiplier(tier)
  const coinBonusEnhancement = coinBonusEnhancementMult(input.coinBonusEnhancementLevel)
  const coinsCardMult = cardLevelMulti('coins', input.coinsCardLevel)
    * cardMasteryMulti('coins', input.coinsCardLevel, input.coinsCardMastery)
  const themeMult = themePassiveCoinMult(input)
  const relicMult = 1 + Math.max(0, Number(input.relicCoinBonusPct) || 0) / 100
  const packMult = computePackCoinMult(input.iapToggles)
  const tradeOffCoinMult = coinTradeOffPerkMult(input.hasCoinTradeOffPerk, input.improveTradeOffLabPct)
  const perkCoinMult = allCoinBonusesPerkMult(input.allCoinPerkLevel, input.standardPerkBonusPct)
  const workshopCoinsKillMult = readWorkshopUtilityValue(COINS_KILL_WORKSHOP_KEY, input.coinsKillWorkshopLevel)
  const coinsKillLabMult = computeLabCoinMultiplier(RESOURCE_DROPS_COIN_LAB_SLUGS.coinsKill, input.coinsKillLabLevel)
  const moduleBonus = Math.max(0, Number(input.moduleCoinsKillBonus) || 0)
  const bhdBonusPct = Math.max(0, Number(input.bhdCpkBonusPct) || 0)
  const vaultMult = vaultCoinskillMult(input.vaultCoinskillLevel)

  const globalMult = tierCoinMult
    * coinBonusEnhancement
    * coinsCardMult
    * themeMult
    * relicMult
    * packMult
    * perkCoinMult
    * tradeOffCoinMult

  const cpkCore = (workshopCoinsKillMult * coinsKillLabMult + moduleBonus) * vaultMult
  const bhdMult = bhdBonusPct > 0 ? 1 + bhdBonusPct / 100 : 1
  const baselineKillMult = globalMult * coinBonusEnhancement * cpkCore * bhdMult

  const coinsWaveLabMult = computeLabCoinMultiplier(RESOURCE_DROPS_COIN_LAB_SLUGS.coinsWave, input.coinsWaveLabLevel)
  const cpwWorkshop = readWorkshopUtilityValue(COINS_WAVE_WORKSHOP_KEY, input.coinsWaveWorkshopLevel)
  const coinsPerWaveMult = cpwWorkshop * globalMult * coinsWaveLabMult

  const skipChance = cardLevelPercent('ws', input.waveSkipCardLevel)
  const waveSkipMult = waveSkipResourceMultiplier(skipChance, buildWaveContext(input).waveSkipExpectedSkipsPerProc)
  const introSprintCoinFraction = 1 - introSprintZeroCoinFraction(
    input.introSprintZeroCoinWaveCap,
    input.targetWave,
  )

  const gtCoinMult = computeGoldenTowerCoinMult(input.uwLevels.gtMultiplierLevel, input.gtBonusLabLevel)
  const bhCoinMult = computeLabCoinMultiplier(RESOURCE_DROPS_COIN_LAB_SLUGS.bhCoin, input.bhCoinLabLevel)
  const dwCoinMult = computeLabCoinMultiplier(RESOURCE_DROPS_COIN_LAB_SLUGS.dwCoin, input.dwCoinLabLevel)
  const slCoinMult = computeLabCoinMultiplier(RESOURCE_DROPS_COIN_LAB_SLUGS.slCoin, input.slCoinLabLevel)

  const goldenBotBase = input.useGoldenBotCoinBonus
    ? parseBotStatMultiplier('Golden Bot', 'Bonus', input.goldenBotBonusLevel)
    : 1
  const gbRangeFraction = Math.min(1, Math.max(0, Number(input.goldenBotCoverageFraction) || 0))
  const goldenBotMult = gbRangeFraction > 0 && goldenBotBase > 1
    ? 1 + gbRangeFraction * (goldenBotBase - 1)
    : 1

  const uptimeRatios = resolveUwUptimeRatios(input.uptime)
  const avgKillsPerGt = estimateKillsDuringGoldenTowerWindow(input, uptimeRatios.gtUptimeRatio)
  const gtPlusMult = goldenTowerPlusCoinMult(input.gtPlusLevel, avgKillsPerGt)
  const expectedTimedKillMult = expectedTimedCoinKillMult(
    {
      gtCoinMult,
      bhCoinMult,
      dwCoinMult,
      slCoinMult,
      goldenBotMult,
      ...uptimeRatios,
    },
    input.assumeSyncedUwCoinWindows,
  ) * gtPlusMult

  return {
    tierCoinMult,
    coinBonusEnhancementMult: coinBonusEnhancement,
    coinsCardMult,
    themeMult,
    relicMult,
    packMult,
    perkCoinMult,
    tradeOffCoinMult,
    introSprintCoinFraction,
    bhdCpkBonusPct: bhdBonusPct,
    gtPlusMult,
    goldenBotRangeFraction: gbRangeFraction,
    workshopCoinsKillMult,
    coinsKillLabMult,
    moduleCoinsKillBonus: moduleBonus,
    vaultCoinskillMult: vaultMult,
    baselineKillMult,
    coinsPerWaveMult,
    waveSkipMult,
    goldenBotMult,
    gtCoinMult,
    bhCoinMult,
    dwCoinMult,
    slCoinMult,
    ...uptimeRatios,
    expectedTimedKillMult,
  }
}

export function spawnYieldForWave(
  input: ResourceDropsCoinSimulationInput,
  wave: number,
): WaveSpawnYieldInput | undefined {
  if (input.spawnYield != null) return input.spawnYield
  if (!input.useAccountSpawnYield) return undefined
  return resolveWaveSpawnYieldFromAccount({
    tier: input.tier,
    wave,
    enemyBalanceMastery: input.enemyBalanceMasteryLevel,
    waveAcceleratorMastery: input.waveAcceleratorMasteryLevel,
    useDisasmGates: input.useDisasmSpawnGates === true,
    useDisasmQuantum: input.useDisasmQuantum,
    enemyDoubleSpawnThreshold: input.enemyDoubleSpawnThreshold,
    doubleSpawnThemeBucketBase: input.doubleSpawnThemeBucketBase,
    waveLengthSeconds: input.waveLengthSeconds,
    moreEnemiesHeatLevel: input.moreEnemiesHeatLevel,
    moreEnemiesResistance: input.moreEnemiesResistance,
  })
}

function estimateKillsDuringGoldenTowerWindow(
  input: ResourceDropsCoinSimulationInput,
  gtUptimeRatio: number,
): number {
  if (!input.uptime || gtUptimeRatio <= 0) return 0
  const ctx = buildWaveContext(input)
  const waMastery = findWaveAcceleratorMasteryForSpawnCap(input.waveAcceleratorMasteryLevel)
  const midWave = Math.max(1, Math.floor(ctx.targetWave / 2))
  const killsPerWave = killsPerWaveAt(midWave, ctx.enemyBalanceMult, waMastery, input)
  const gtDur = computeDurations(input.uptime).gt
  const waveSeconds = Math.max(1, Number(input.averageWaveSeconds) || 30)
  return killsPerWave * (gtDur / waveSeconds)
}

export function killsPerWaveAt(
  wave: number,
  enemyBalanceMult: number,
  waveAcceleratorMastery: number | null,
  simulationInput?: ResourceDropsCoinSimulationInput,
): number {
  const spawnYield = simulationInput ? spawnYieldForWave(simulationInput, wave) : undefined
  return killsPerWaveFromSpawnContext({
    wave,
    enemyBalanceMult,
    waveAcceleratorMastery,
    spawnYield,
  })
}
