/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    RESOURCE_DROPS_AVG_ENEMY_COIN_WEIGHT, RESOURCE_DROPS_ENEMIES_PER_SPAWN_TICK, COIN_BONUS_ENHANCEMENT_KEY, ResourceDropsCoinYieldBreakdown, ResourceDropsCoinSimulationResult, emptyResourceDropsCoinSimulationResult, goldenBotRangeCoverageFraction, accumulateResourceDropsKillYields (+16 more)
 * depends    src/data/charts/data, src/mechanics/enemies/drops-wave-context, src/mechanics/enemies/type-mix, src/mechanics/resource-drops/accumulate-wave-econ, src/mechanics/resource-drops/coin-fetch, src/mechanics/resource-drops/coin-multipliers (+4 more)
 * used by    src/knowledge/compartments/enemies, src/mechanics/calculators/specs-generated, src/mechanics/resource-drops/coin-context, src/mechanics/resource-drops/index
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
/* â”€â”€ file map â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
 * exports    RESOURCE_DROPS_AVG_ENEMY_COIN_WEIGHT, RESOURCE_DROPS_ENEMIES_PER_SPAWN_TICK, COIN_BONUS_ENHANCEMENT_KEY, COINS_KILL_WORKSHOP_KEY, COINS_WAVE_WORKSHOP_KEY, RESOURCE_DROPS_COIN_LAB_SLUGS, ResourceDropsCoinEconomyInputs, ResourceDropsCoinUwLevels (+21 more)
 * depends    src/data, src/data/charts/data, src/mechanics/combat/uw-stat-values, src/mechanics/enemies/drops-simulation, src/mechanics/enemies/type-mix, src/mechanics/primitives/math (+8 more)
 * used by    src/knowledge/compartments/enemies, src/mechanics/calculators/specs-generated, src/mechanics/resource-drops/coin-context, src/mechanics/resource-drops/index
 * â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€ generated by `npm run map` â”€â”€
 */
import type {
  ResourceDropsCoinEconomyInputs,
  ResourceDropsCoinUwLevels,
  ResourceDropsCoinBotLevels,
  ResourceDropsCoinSimulationInput,
  ResourceDropsCoinMultiplierBreakdown,
} from './coin-simulation-types'
import {
  buildResourceDropsCoinMultipliers,
  killsPerWaveAt,
  spawnYieldForWave,
} from './coin-multipliers'
import {
  buildWaveContext,
  WAVE_SKIP_SKIPPED_WAVE_MULT,
} from '../enemies/drops-wave-context'
import {
  waveAcceleratorSpawnRateChartColumn,
} from '../waves/accelerator-spawn-rate-cap'
import {
  expectedEnemiesPerSpawnTick,
  killsPerWaveFromSpawnContext,
  WAVE_SPAWN_CALIBRATED_ENEMIES_PER_TICK,
  type WaveSpawnYieldInput,
} from '../waves/wave-spawn-yield'
import { WAVE_ACCELERATOR_SPAWN_RATE_ROWS } from '../../data/charts/data'
import {
  estimateFetchCoinsFromRunCpm,
  estimateRunDurationMinutes,
} from './coin-fetch'
import { measuredAverageEnemyCoinWeight } from '../enemies/type-mix'
import { foldWaveCoinRows } from './accumulate-wave-econ'
import { accumulateWaveCoin, simulateWaveCoinRows } from './simulate-wave-coins'

/**
 * Average enemy coin weight vs basic, MEASURED from a real round.
 *
 * Was a hand-blended 1.15 with the comment "fast/ranged 2x, tank 4x mix". The
 * mix it assumed was never checked. Per-type kill counters in
 * `test/playerInfo.dat` partition a round exactly, and the measured mix is near
 * uniform (basic 27.9%, fast 25.5%, tank 24.0%, ranged 22.6%), which weights to
 * 2.20 rather than 1.15.
 *
 * Derived, not retyped: change the measured counts and this follows.
 * See `src/pages/import/utils/enemy-type-mix-vs-save.test.ts`.
 */
export const RESOURCE_DROPS_AVG_ENEMY_COIN_WEIGHT = measuredAverageEnemyCoinWeight()

/**
 * Enemies produced per spawn TICK, above the one the chart implies.
 *
 * `Main.WaveUpdate` does not spawn a single enemy per tick. It rolls against
 * `enemySpawnChance` and calls `SpawnRandomBasicEnemy` at three separate sites
 * â€” gated by cards, tournament state and `CustomizeGame.GetResistanceLevel` â€”
 * then rolls `enemyDoubleSpawnChance` for one more. The wave-accelerator chart
 * gives the tick count; this is what each tick actually yields.
 *
 * The STRUCTURE is from the binary; the MAGNITUDE is measured, because the
 * three call sites are conditional on state a static read cannot resolve. Two
 * independent estimates from `test/playerInfo.dat` agree to 2%:
 *
 *   one wave    350 spawned at wave 4875 / (56 ticks x 1.9 Enemy Balance) = 3.29
 *   whole round 621,640 kills / (model total x the 45% of waves not skipped)  = 3.22
 *
 * Both assume full Wave Accelerator mastery. Under NO mastery the same two
 * estimates give 3.76 and 3.95 â€” they disagree by 5% instead of 2%, which is
 * the evidence for the mastery assumption rather than an assertion of it.
 *
 * A per-tick yield derived from the actual spawn conditions would replace this.
 * Until then it is a calibration, and is named as one.
 */
export const RESOURCE_DROPS_ENEMIES_PER_SPAWN_TICK = WAVE_SPAWN_CALIBRATED_ENEMIES_PER_TICK

export const COIN_BONUS_ENHANCEMENT_KEY = 'coin_bonus'

export {
  buildResourceDropsCoinMultipliers,
  coinBonusEnhancementMult,
  vaultCoinskillMult,
  themePassiveCoinMultFromBonusPct,
  themePassiveCoinMult,
  computeLabCoinMultiplier,
  computeGoldenTowerCoinMult,
  computePackCoinMult,
  goldenTowerPlusCoinMult,
  expectedTimedCoinKillMult,
  COINS_KILL_WORKSHOP_KEY,
  COINS_WAVE_WORKSHOP_KEY,
  RESOURCE_DROPS_COIN_LAB_SLUGS,
} from './coin-multipliers'

export type {
  ResourceDropsCoinEconomyInputs,
  ResourceDropsCoinUwLevels,
  ResourceDropsCoinBotLevels,
  ResourceDropsCoinSimulationInput,
  ResourceDropsCoinMultiplierBreakdown,
} from './coin-simulation-types'

export interface ResourceDropsCoinYieldBreakdown {
  coinsFromKills: number
  coinsFromKillsWaveSkipBonus: number
  coinsFromWavePayout: number
  coinsFromWavePayoutWaveSkipBonus: number
  coinsFromFetch: number
  totalCoins: number
}

export interface ResourceDropsCoinSimulationResult {
  multipliers: ResourceDropsCoinMultiplierBreakdown
  coins: ResourceDropsCoinYieldBreakdown
  totalKillsEstimated: number
  averageCoinsPerKill: number
  averageCoinsPerWave: number
}

const EMPTY_RESOURCE_DROPS_COIN_MULTIPLIERS: ResourceDropsCoinMultiplierBreakdown = {
  tierCoinMult: 1,
  coinBonusEnhancementMult: 1,
  coinsCardMult: 1,
  themeMult: 1,
  relicMult: 1,
  packMult: 1,
  perkCoinMult: 1,
  tradeOffCoinMult: 1,
  introSprintCoinFraction: 1,
  bhdCpkBonusPct: 0,
  gtPlusMult: 1,
  goldenBotRangeFraction: 0,
  workshopCoinsKillMult: 1,
  coinsKillLabMult: 1,
  moduleCoinsKillBonus: 0,
  vaultCoinskillMult: 1,
  baselineKillMult: 1,
  coinsPerWaveMult: 0,
  waveSkipMult: 1,
  goldenBotMult: 1,
  gtCoinMult: 1,
  bhCoinMult: 1,
  dwCoinMult: 1,
  slCoinMult: 1,
  gtUptimeRatio: 0,
  bhUptimeRatio: 0,
  dwUptimeRatio: 0,
  slUptimeRatio: 0,
  gbUptimeRatio: 0,
  expectedTimedKillMult: 1,
}

export function emptyResourceDropsCoinSimulationResult(): ResourceDropsCoinSimulationResult {
  return {
    multipliers: { ...EMPTY_RESOURCE_DROPS_COIN_MULTIPLIERS },
    coins: {
      coinsFromKills: 0,
      coinsFromKillsWaveSkipBonus: 0,
      coinsFromWavePayout: 0,
      coinsFromWavePayoutWaveSkipBonus: 0,
      coinsFromFetch: 0,
      totalCoins: 0,
    },
    totalKillsEstimated: 0,
    averageCoinsPerKill: 0,
    averageCoinsPerWave: 0,
  }
}

export function goldenBotRangeCoverageFraction(towerRange: number, botRange: number): number {
  const tower = Math.max(0, Number(towerRange) || 0)
  const bot = Math.max(0, Number(botRange) || 0)
  if (tower <= 0 || bot <= 0) return 1
  return Math.min(1, bot / tower)
}

function sumWaveIndexRange(wStart: number, wEnd: number): number {
  if (wEnd < wStart) return 0
  const count = wEnd - wStart + 1
  return ((wStart + wEnd) * count) / 2
}

function spawnRateThresholdForRow(
  row: (typeof WAVE_ACCELERATOR_SPAWN_RATE_ROWS)[number],
  column: ReturnType<typeof waveAcceleratorSpawnRateChartColumn>,
): number {
  const value = row[column]
  return typeof value === 'number' ? value : Number.POSITIVE_INFINITY
}

/** Segment-wise kill/coin totals â€” O(chart rows) instead of O(targetWave). */
export function accumulateResourceDropsKillYields(input: {
  targetWave: number
  enemyBalanceMult: number
  waveAcceleratorMastery: number | null
  introSprintZeroCoinWaveCap: number
  coinSimulation?: ResourceDropsCoinSimulationInput
  spawnYield?: WaveSpawnYieldInput
}): { totalKills: number; rawKillCoins: number } {
  const targetWave = Math.max(1, Math.floor(Number(input.targetWave) || 1))
  const enemyBalanceMult = Math.max(0, Number(input.enemyBalanceMult) || 0)
  const waMastery = input.waveAcceleratorMastery
  const introCap = Math.max(0, Math.floor(Number(input.introSprintZeroCoinWaveCap) || 0))
  const coinSimulation = input.coinSimulation ?? (input.spawnYield != null ? ({ spawnYield: input.spawnYield } as ResourceDropsCoinSimulationInput) : undefined)

  let totalKills = 0
  let rawKillCoins = 0

  const column = waveAcceleratorSpawnRateChartColumn(waMastery)
  const rows = WAVE_ACCELERATOR_SPAWN_RATE_ROWS
  const firstRow = rows[0]
  const firstThreshold = firstRow ? spawnRateThresholdForRow(firstRow, column) : 1

  const linearEnd = Math.min(targetWave, Math.max(0, firstThreshold - 1))
  for (let wave = 1; wave <= linearEnd; wave += 1) {
    const kills = killsPerWaveAt(wave, enemyBalanceMult, waMastery, coinSimulation)
    totalKills += kills
    if (wave <= introCap) continue
    rawKillCoins += kills * wave * RESOURCE_DROPS_AVG_ENEMY_COIN_WEIGHT
  }

  if (targetWave <= linearEnd || !rows.length) {
    return { totalKills, rawKillCoins }
  }

  const accumulateSegment = (wStart: number, wEnd: number, spawnCap: number) => {
    if (wEnd < wStart) return
    const repWave = Math.floor((wStart + wEnd) / 2)
    const segmentSpawnYield = coinSimulation
      ? spawnYieldForWave(coinSimulation, repWave)
      : undefined
    const killsPerWave = segmentSpawnYield?.useDisasmGates
      ? killsPerWaveFromSpawnContext({
        wave: repWave,
        enemyBalanceMult,
        waveAcceleratorMastery: waMastery,
        spawnYield: {
          ...segmentSpawnYield,
          spawnTickCap: segmentSpawnYield.spawnTickCap ?? spawnCap,
        },
      })
      : spawnCap * enemyBalanceMult * expectedEnemiesPerSpawnTick(segmentSpawnYield)
    const waveCount = wEnd - wStart + 1
    totalKills += killsPerWave * waveCount
    const coinStart = Math.max(wStart, introCap + 1)
    if (coinStart > wEnd) return
    rawKillCoins += killsPerWave * RESOURCE_DROPS_AVG_ENEMY_COIN_WEIGHT * sumWaveIndexRange(coinStart, wEnd)
  }

  for (let index = 0; index < rows.length; index += 1) {
    const row = rows[index]
    const threshold = spawnRateThresholdForRow(row, column)
    const nextThreshold = index + 1 < rows.length
      ? spawnRateThresholdForRow(rows[index + 1], column)
      : Number.POSITIVE_INFINITY
    const segStart = Math.max(threshold, linearEnd + 1)
    const segEnd = Math.min(targetWave, nextThreshold - 1)
    accumulateSegment(segStart, segEnd, row.spawnCount)
    if (targetWave < nextThreshold) {
      return { totalKills, rawKillCoins }
    }
  }

  const lastRow = rows[rows.length - 1]
  const lastThreshold = spawnRateThresholdForRow(lastRow, column)
  accumulateSegment(Math.max(lastThreshold, linearEnd + 1), targetWave, lastRow.spawnCount)

  return { totalKills, rawKillCoins }
}

export function simulateResourceDropsCoins(
  input: ResourceDropsCoinSimulationInput,
): ResourceDropsCoinSimulationResult {
  const ctx = buildWaveContext(input)
  const multipliers = buildResourceDropsCoinMultipliers(input)
  const targetWave = ctx.targetWave
  const coinTotals = accumulateWaveCoin(input, { coinsPerWaveMult: multipliers.coinsPerWaveMult })
  const killStack = multipliers.baselineKillMult * multipliers.expectedTimedKillMult
  const playedKillCoins = coinTotals.rawKillCoins - coinTotals.skipKillCoins
  const coinsFromKills = playedKillCoins * killStack
  const coinsFromKillsWaveSkipBonus = coinTotals.skipKillCoins * killStack
  const playedWaveCoins = coinTotals.waveCoins - coinTotals.skipWaveCoins
  const coinsFromWavePayout = playedWaveCoins
  const coinsFromWavePayoutWaveSkipBonus = coinTotals.skipWaveCoins
  const preFetchTotal = coinsFromKills + coinsFromKillsWaveSkipBonus + coinsFromWavePayout + coinsFromWavePayoutWaveSkipBonus
  const runMinutes = estimateRunDurationMinutes(targetWave, input.averageWaveSeconds)
  const coinsFromFetch = estimateFetchCoinsFromRunCpm({
    enemyDrops: input,
    runCoinTotalBeforeFetch: preFetchTotal,
    runDurationMinutes: runMinutes,
  })
  const totalCoins = preFetchTotal + coinsFromFetch
  return {
    multipliers,
    coins: {
      coinsFromKills,
      coinsFromKillsWaveSkipBonus,
      coinsFromWavePayout,
      coinsFromWavePayoutWaveSkipBonus,
      coinsFromFetch,
      totalCoins,
    },
    totalKillsEstimated: coinTotals.expectedKills,
    averageCoinsPerKill: coinTotals.expectedKills > 0 ? (coinsFromKills + coinsFromKillsWaveSkipBonus) / coinTotals.expectedKills : 0,
    averageCoinsPerWave: targetWave > 0 ? totalCoins / targetWave : 0,
  }
}

export const RESOURCE_DROPS_COIN_APPROXIMATION_NOTES = [
  'Kill coins use wave Ã— enemy-type weight (â‰ˆ1.15Ã— basic) Ã— spawn-rate cap Ã— Enemy Balance per wave, then apply account multipliers.',
  'Timed Ultimate Weapon and Golden Bot boosts use uptime-calculator durations/cooldowns; Galaxy Compressor pkg CD reduction flows through the same compressor model.',
  'Singularity Harness extends Golden Bot range coverage; Black Hole Digestor adds temporary CPK % from expected free upgrades per wave.',
  'Wave Skip compounds skipped-wave income at 1.10x per wave on kill coins and wave payout; kill coin weight follows Wave Info spawn mix per wave.',
  'Fetch coin procs (~86.5% of finds) use 0.2% Ã— run CPM Ã— expected coin procs; daily caps not modeled.',
  'Intro Sprint zero-coin waves and x1.80 coin trade-off perk (+ Improve Trade-Off lab) are optional toggles.',
  'Golden Combo post-GT kill scaling beyond the GT+ approximation is not modeled.',
] as const

export { WAVE_SKIP_SKIPPED_WAVE_MULT }
