/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    ALL_COIN_BONUS_PERK_BASE, ALL_COIN_BONUS_PERK_MAX_LEVEL, allCoinBonusesPerkMult
 * depends    —
 * used by    src/mechanics/calculators/specs-generated, src/mechanics/resource-drops/coin-multipliers, src/mechanics/resource-drops/index
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
/** Standard perk: x1.15 All Coin Bonuses (max quantity 5). */

export const ALL_COIN_BONUS_PERK_BASE = 0.15
export const ALL_COIN_BONUS_PERK_MAX_LEVEL = 5

/**
 * Multiplicative coin perk stack — `(1 + 0.15 × qty) × (1 + SPB/100)`.
 * Matches {@link STANDARD_PERK_MATH_FACTS} multiplicative perk pattern.
 */
export function allCoinBonusesPerkMult(
  perkLevel: number,
  standardPerkBonusPct = 0,
): number {
  const qty = Math.max(0, Math.min(ALL_COIN_BONUS_PERK_MAX_LEVEL, Math.floor(Number(perkLevel) || 0)))
  if (qty <= 0) return 1
  const base = 1 + ALL_COIN_BONUS_PERK_BASE * qty
  const spb = 1 + Math.max(0, Number(standardPerkBonusPct) || 0) / 100
  return base * spb
}
