/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    simulateEnemyDropYields, simulateEnemyDrops, buildCellsPerKillBonusRoiRows, buildWaveSkipCardRoiRows, buildEnemyBalanceMasteryRoiRows, buildRerollShardsLabRoiRows, buildFetchUpgradeRoiRows
 * depends    src/data, src/formatting/tools/compute, src/mechanics/cards/costs, src/mechanics/enemies/drops-game-data, src/mechanics/enemies/drops-shared, src/mechanics/enemies/drops-simulation (+4 more)
 * used by    src/mechanics/calculators/specs-generated, src/mechanics/resource-drops/index
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
import {
  computeEnemyDropsNormalizedRoiPct,
  simulateFetchDrops,
  fetchUpgradeAtLevel,
  type EnemyDropsRoiRow,
  type EnemyDropsSimulationResult,
  type EnemyDropsRoiBuildContext,
} from '../enemies/drops-simulation'
import {
  clampCardGameLevel,
  clampCardMasteryLevel,
  type EnemyDropsSimulationInput,
  type EnemyDropsYieldBreakdown,
} from '../enemies/drops-shared'
import { buildWaveContext } from '../enemies/drops-wave-context'
import {
  getExpectedBossRerollShardsPerKill,
  getEnemyDropsLabBenefits,
} from '../enemies/drops-game-data'
import { enemyDropYieldBreakdownFromPerWave } from './accumulate-wave-econ'
import {
  findLabResearchBySlug,
  getSharedToolLabs,
  buildLabProgressRows,
  type LabProgressModifiers,
  getWorkshopCostsByKey,
  computeWorkshopTotalDiscountPercent,
  computeWorkshopCostTotal,
  guardianUpgrades,
} from '../../data'
import { formatCompact } from '../../formatting/tools/compute'
import { clamp } from '../primitives/math'
import { cardLevelUpgradeGemCost } from '../cards/costs'
import { computeRoiReferenceCost } from '../planning/roi-scaling'

type EnemyDropsRoiDraft = {
  id: string
  label: string
  category: string
  level: number
  nextLevel: number
  costLabel: string
  marginalGain: number
  cost: number
  currentTotal: number
  totalYieldAtLevel: number
}

function finalizeEnemyDropsRoiRows(drafts: EnemyDropsRoiDraft[]): EnemyDropsRoiRow[] {
  const referenceCost = computeRoiReferenceCost(drafts.map(draft => draft.cost))
  const rows = drafts.map(draft => ({
    id: draft.id,
    label: draft.label,
    category: draft.category,
    level: draft.level,
    nextLevel: draft.nextLevel,
    costLabel: draft.costLabel,
    marginalGain: draft.marginalGain,
    roi: computeEnemyDropsNormalizedRoiPct(
      draft.marginalGain,
      draft.currentTotal,
      draft.cost,
      referenceCost,
    ),
    totalYieldAtLevel: draft.totalYieldAtLevel,
  }))
  return rows.sort((a, b) => b.roi - a.roi)
}

function lookupLabRecord(slug: string) {
  const research = findLabResearchBySlug(slug)
  return getSharedToolLabs().find(
    lab => lab.name === slug || lab.displayName === research?.displayName,
  ) ?? { name: slug, displayName: research?.displayName ?? undefined }
}

function labLevelCoinCost(
  slug: string,
  fromLevel: number,
  toLevel: number,
  modifiers: LabProgressModifiers,
): number {
  const lab = lookupLabRecord(slug)
  const rows = buildLabProgressRows(lab, fromLevel, toLevel, modifiers)
  if (rows.length === 0) return 0
  return rows[rows.length - 1]?.coins ?? 0
}

function cellsPerKillUpgradeCoinCost(
  fromLevel: number,
  toLevel: number,
  utilityDiscountPct = 0,
  vaultDiscountPct = 0,
): number {
  const costs = getWorkshopCostsByKey('WSP_CELLS_PER_KILL_BONUS')
  if (!costs?.length) return 0
  const discount = computeWorkshopTotalDiscountPercent(utilityDiscountPct, vaultDiscountPct)
  return computeWorkshopCostTotal(costs, fromLevel, toLevel, discount)
}

export function simulateEnemyDropYields(
  input: EnemyDropsSimulationInput,
): EnemyDropsYieldBreakdown {
  return enemyDropYieldBreakdownFromPerWave(input)
}

function cumulativeFetchStatCost(
  stat: 'cooldownCost' | 'findChanceCost' | 'doubleFindChanceCost',
  fromLevel: number,
  toLevel: number,
): number {
  const lastLevel = Math.min(toLevel, guardianUpgrades.fetch.length)
  let total = 0
  for (let level = fromLevel + 1; level <= lastLevel; level += 1) {
    const row = fetchUpgradeAtLevel(level)
    const cost = row[stat]
    if (typeof cost === 'number' && Number.isFinite(cost)) total += cost
  }
  return total
}

export function simulateEnemyDrops(input: EnemyDropsSimulationInput): EnemyDropsSimulationResult {
  const context = buildWaveContext(input)
  const yieldBreakdown = simulateEnemyDropYields(input)
  const fetch = simulateFetchDrops(input)
  return {
    context,
    cells: yieldBreakdown,
    shards: yieldBreakdown,
    fetch,
  }
}

export function buildCellsPerKillBonusRoiRows(
  input: EnemyDropsSimulationInput,
  context: EnemyDropsRoiBuildContext = {},
  maxLevel = 200,
): EnemyDropsRoiRow[] {
  const drafts: EnemyDropsRoiDraft[] = []
  const start = clamp(Math.floor(input.cellsPerKillBonusLevel), 0, maxLevel - 1)

  for (let level = start; level < maxLevel; level += 1) {
    const current = simulateEnemyDropYields({ ...input, cellsPerKillBonusLevel: level })
    const next = simulateEnemyDropYields({ ...input, cellsPerKillBonusLevel: level + 1 })
    const marginalGain = next.totalCells - current.totalCells
    const coinCost = cellsPerKillUpgradeCoinCost(
      level,
      level + 1,
      context.workshopUtilityDiscountPct,
      context.workshopVaultDiscountPct,
    )
    drafts.push({
      id: `cells-per-kill-${level + 1}`,
      label: 'Cells / Kill Bonus',
      category: 'Workshop Enhancement',
      level,
      nextLevel: level + 1,
      costLabel: coinCost > 0 ? `${formatCompact(Math.round(coinCost))} coins` : '—',
      marginalGain,
      cost: coinCost,
      currentTotal: current.totalCells,
      totalYieldAtLevel: next.totalCells,
    })
  }

  return finalizeEnemyDropsRoiRows(drafts)
}

export function buildWaveSkipCardRoiRows(
  input: EnemyDropsSimulationInput,
): EnemyDropsRoiRow[] {
  const drafts: EnemyDropsRoiDraft[] = []
  const start = clampCardGameLevel(input.waveSkipCardLevel)
  for (let gameLevel = start; gameLevel < 7; gameLevel += 1) {
    const current = simulateEnemyDropYields({ ...input, waveSkipCardLevel: gameLevel })
    const next = simulateEnemyDropYields({ ...input, waveSkipCardLevel: gameLevel + 1 })
    const marginalGain = next.totalCells - current.totalCells
    const gemCost = cardLevelUpgradeGemCost(gameLevel, gameLevel + 1)
    drafts.push({
      id: `wave-skip-card-${gameLevel + 1}`,
      label: 'Wave Skip Card',
      category: 'Card',
      level: gameLevel,
      nextLevel: gameLevel + 1,
      costLabel: gemCost > 0 ? `${formatCompact(gemCost)} gems` : '—',
      marginalGain,
      cost: gemCost,
      currentTotal: current.totalCells,
      totalYieldAtLevel: next.totalCells,
    })
  }
  return finalizeEnemyDropsRoiRows(drafts)
}

export function buildEnemyBalanceMasteryRoiRows(
  input: EnemyDropsSimulationInput,
): EnemyDropsRoiRow[] {
  const drafts: EnemyDropsRoiDraft[] = []
  const start = clampCardMasteryLevel(input.enemyBalanceMasteryLevel)
  for (let level = start; level < 9; level += 1) {
    const current = simulateEnemyDropYields({ ...input, enemyBalanceMasteryLevel: level })
    const next = simulateEnemyDropYields({ ...input, enemyBalanceMasteryLevel: level + 1 })
    const marginalGain = next.totalCells - current.totalCells
    drafts.push({
      id: `eb-mastery-${level + 1}`,
      label: 'Enemy Balance Mastery',
      category: 'Card Mastery',
      level,
      nextLevel: level + 1,
      costLabel: 'Mastery upgrade',
      marginalGain,
      cost: 1,
      currentTotal: current.totalCells,
      totalYieldAtLevel: next.totalCells,
    })
  }
  return finalizeEnemyDropsRoiRows(drafts)
}

export function buildRerollShardsLabRoiRows(
  input: EnemyDropsSimulationInput,
  context: EnemyDropsRoiBuildContext = {},
  maxLevel = 100,
): EnemyDropsRoiRow[] {
  const drafts: EnemyDropsRoiDraft[] = []
  const ctx = buildWaveContext(input)
  const modifiers = context.labsEconomy ?? {
    labSpeed: 0,
    labRelic: 0,
    labDiscount: 0,
    speedUp: 1,
    gemDiscount: 0,
  }
  const start = clamp(Math.floor(input.rerollShardsLabLevel), 0, maxLevel - 1)

  for (let level = start; level < maxLevel; level += 1) {
    const currentPerBoss = getExpectedBossRerollShardsPerKill(
      ctx.tier,
      getEnemyDropsLabBenefits({ ...input, rerollShardsLabLevel: level }).rerollShardsBenefit,
    )
    const nextPerBoss = getExpectedBossRerollShardsPerKill(
      ctx.tier,
      getEnemyDropsLabBenefits({ ...input, rerollShardsLabLevel: level + 1 }).rerollShardsBenefit,
    )
    const currentTotal = ctx.bossCount * currentPerBoss * ctx.waveSkipResourceMult
    const marginalGain = ctx.bossCount * (nextPerBoss - currentPerBoss) * ctx.waveSkipResourceMult
    const coinCost = labLevelCoinCost('reroll_shards', level, level + 1, modifiers)
    drafts.push({
      id: `reroll-shards-lab-${level + 1}`,
      label: 'Reroll Shards Lab',
      category: 'Lab',
      level,
      nextLevel: level + 1,
      costLabel: coinCost > 0 ? `${formatCompact(Math.round(coinCost))} coins` : '—',
      marginalGain,
      cost: coinCost,
      currentTotal,
      totalYieldAtLevel: ctx.bossCount * nextPerBoss * ctx.waveSkipResourceMult,
    })
  }
  return finalizeEnemyDropsRoiRows(drafts)
}

export function buildFetchUpgradeRoiRows(input: EnemyDropsSimulationInput): EnemyDropsRoiRow[] {
  const drafts: EnemyDropsRoiDraft[] = []
  const metrics: Array<{
    key: 'fetchCooldownLevel' | 'fetchFindChanceLevel' | 'fetchDoubleFindLevel'
    label: string
    stat: 'cooldownCost' | 'findChanceCost' | 'doubleFindChanceCost'
    max: number
  }> = [
    { key: 'fetchCooldownLevel', label: 'Fetch Cooldown', stat: 'cooldownCost', max: 60 },
    { key: 'fetchFindChanceLevel', label: 'Fetch Find Chance', stat: 'findChanceCost', max: 41 },
    { key: 'fetchDoubleFindLevel', label: 'Fetch Double Find', stat: 'doubleFindChanceCost', max: 49 },
  ]

  for (const metric of metrics) {
    const currentLevel = input[metric.key]
    for (let level = currentLevel; level < metric.max; level += 1) {
      const current = simulateFetchDrops({ ...input, [metric.key]: level } as EnemyDropsSimulationInput)
      const next = simulateFetchDrops({ ...input, [metric.key]: level + 1 } as EnemyDropsSimulationInput)
      const marginalGain = next.expectedProcs - current.expectedProcs
      const cost = cumulativeFetchStatCost(metric.stat, level, level + 1)
      drafts.push({
        id: `${metric.key}-${level + 1}`,
        label: metric.label,
        category: 'Fetch Guardian',
        level,
        nextLevel: level + 1,
        costLabel: cost > 0 ? `${formatCompact(cost)} bits` : '—',
        marginalGain,
        cost,
        currentTotal: current.expectedProcs,
        totalYieldAtLevel: next.expectedProcs,
      })
    }
  }

  return finalizeEnemyDropsRoiRows(drafts)
}
