/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    WaveCoinSimRow, WaveCoinSimTotals, WaveCoinSimulationOptions, forEachWaveCoinRow, accumulateWaveCoin, simulateWaveCoinRows
 * depends    src/mechanics/enemies/drops-wave-context, src/mechanics/resource-drops/coin-simulation-types, src/mechanics/resource-drops/wave-ordinary-coin-weight, src/mechanics/resource-drops/wave-skip-per-wave, src/mechanics/waves/accelerator-spawn-rate-cap, src/mechanics/waves/resolve-wave-spawn-yield (+1 more)
 * used by    src/mechanics/calculators/specs-generated, src/mechanics/resource-drops/accumulate-wave-econ, src/mechanics/resource-drops/coin-simulation, src/mechanics/resource-drops/index
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
import { buildWaveContext } from '../enemies/drops-wave-context'
import { findWaveAcceleratorMasteryForSpawnCap, enemySpawnRateCapFromWaveAcceleratorChart } from '../waves/accelerator-spawn-rate-cap'
import { resolveWaveSpawnYieldFromAccount } from '../waves/resolve-wave-spawn-yield'
import { killsPerWaveFromSpawnContext, type WaveSpawnYieldInput } from '../waves/wave-spawn-yield'
import type { ResourceDropsCoinSimulationInput } from './coin-simulation-types'
import { buildWaveSkipPerWaveAdjust, waveSkipIncomeEv } from './wave-skip-per-wave'
import { ordinaryCoinWeightAtWave } from './wave-ordinary-coin-weight'

export type WaveCoinSimRow = {
  wave: number
  spawnTicks: number
  expectedKills: number
  rawKillCoins: number
  waveCoins: number
  skipKillCoins: number
  skipWaveCoins: number
  spawnFraction: number
  coinWeightPerKill: number
}

export type WaveCoinSimTotals = {
  expectedKills: number
  rawKillCoins: number
  skipKillCoins: number
  waveCoins: number
  skipWaveCoins: number
}

export type WaveCoinSimulationOptions = {
  maxRows?: number
  spawnYield?: WaveSpawnYieldInput
  coinsPerWaveMult: number
}

function emptyWaveCoinTotals(): WaveCoinSimTotals {
  return {
    expectedKills: 0,
    rawKillCoins: 0,
    skipKillCoins: 0,
    waveCoins: 0,
    skipWaveCoins: 0,
  }
}

function spawnYieldForWaveRow(
  input: ResourceDropsCoinSimulationInput,
  wave: number,
  override?: WaveSpawnYieldInput,
): WaveSpawnYieldInput | undefined {
  if (override != null) return override
  if (input.spawnYield != null) return input.spawnYield
  if (!input.useAccountSpawnYield) return undefined
  return resolveWaveSpawnYieldFromAccount({
    tier: input.tier,
    wave,
    enemyBalanceMastery: input.enemyBalanceMasteryLevel,
    waveAcceleratorMastery: input.waveAcceleratorMasteryLevel,
    useDisasmGates: input.useDisasmSpawnGates === true,
    useDisasmQuantum: input.useDisasmQuantum,
    enemyDoubleSpawnThreshold: input.enemyDoubleSpawnThreshold,
    doubleSpawnThemeBucketBase: input.doubleSpawnThemeBucketBase,
    waveLengthSeconds: input.waveLengthSeconds,
    moreEnemiesHeatLevel: input.moreEnemiesHeatLevel,
    moreEnemiesResistance: input.moreEnemiesResistance,
  })
}

function foldWaveCoinRow(totals: WaveCoinSimTotals, row: WaveCoinSimRow): void {
  totals.expectedKills += row.expectedKills
  totals.rawKillCoins += row.rawKillCoins
  totals.skipKillCoins += row.skipKillCoins
  totals.waveCoins += row.waveCoins
  totals.skipWaveCoins += row.skipWaveCoins
}

export function forEachWaveCoinRow(
  input: ResourceDropsCoinSimulationInput,
  options: WaveCoinSimulationOptions,
  visit: (row: WaveCoinSimRow) => void,
): void {
  const ctx = buildWaveContext(input)
  const wsAdjust = buildWaveSkipPerWaveAdjust(
    ctx.waveSkipSkipChance,
    ctx.waveSkipExpectedSkipsPerProc,
  )
  const waMastery = findWaveAcceleratorMasteryForSpawnCap(input.waveAcceleratorMasteryLevel)
  const coinsPerWaveMult = options.coinsPerWaveMult
  const introCap = Math.max(0, Math.floor(Number(input.introSprintZeroCoinWaveCap) || 0))
  const limit = Math.min(
    ctx.targetWave,
    Math.max(1, Math.floor(Number(options.maxRows ?? ctx.targetWave) || ctx.targetWave)),
  )
  let prevRawKillCoins = 0
  let prevPlayedBaseKillCoins = 0
  let prevRawWaveCoins = 0
  let prevPlayedBaseWaveCoins = 0

  for (let wave = 1; wave <= limit; wave += 1) {
    const spawnFraction = wsAdjust.spawnFraction
    const spawnTicks = enemySpawnRateCapFromWaveAcceleratorChart({ wave, waveAcceleratorMastery: waMastery })
    const spawnYield = spawnYieldForWaveRow(input, wave, options.spawnYield)
    const fullKills = killsPerWaveFromSpawnContext({
      wave,
      enemyBalanceMult: ctx.enemyBalanceMult,
      waveAcceleratorMastery: waMastery,
      spawnYield,
    })
    const expectedKills = fullKills * spawnFraction
    const coinWeightPerKill = ordinaryCoinWeightAtWave(input.tier, wave)
    const rawKillCoins = wave <= introCap
      ? 0
      : expectedKills * wave * coinWeightPerKill
    const playedBaseKillCoins = rawKillCoins
    const skipKillCoins = wave > 1 && wave > introCap
      ? waveSkipIncomeEv(
        prevRawKillCoins,
        prevPlayedBaseKillCoins,
        ctx.waveSkipSkipChance,
        ctx.waveSkipExpectedSkipsPerProc,
        spawnFraction,
        wsAdjust.incomeMultiplier,
      )
      : 0
    const playedBaseWaveCoins = wave <= introCap ? 0 : coinsPerWaveMult * spawnFraction
    const skipWaveCoins = wave > 1 && wave > introCap
      ? waveSkipIncomeEv(
        prevRawWaveCoins,
        prevPlayedBaseWaveCoins,
        ctx.waveSkipSkipChance,
        ctx.waveSkipExpectedSkipsPerProc,
        spawnFraction,
        wsAdjust.incomeMultiplier,
      )
      : 0
    const waveCoins = playedBaseWaveCoins + skipWaveCoins

    visit({
      wave,
      spawnTicks,
      expectedKills,
      rawKillCoins: playedBaseKillCoins + skipKillCoins,
      waveCoins,
      skipKillCoins,
      skipWaveCoins,
      spawnFraction,
      coinWeightPerKill,
    })
    prevRawKillCoins = playedBaseKillCoins + skipKillCoins
    prevPlayedBaseKillCoins = playedBaseKillCoins > 0 ? playedBaseKillCoins : prevPlayedBaseKillCoins
    prevRawWaveCoins = playedBaseWaveCoins + skipWaveCoins
    prevPlayedBaseWaveCoins = playedBaseWaveCoins > 0 ? playedBaseWaveCoins : prevPlayedBaseWaveCoins
  }
}

export function accumulateWaveCoin(
  input: ResourceDropsCoinSimulationInput,
  options: WaveCoinSimulationOptions,
): WaveCoinSimTotals {
  const totals = emptyWaveCoinTotals()
  forEachWaveCoinRow(input, options, (row) => foldWaveCoinRow(totals, row))
  return totals
}

export function simulateWaveCoinRows(
  input: ResourceDropsCoinSimulationInput,
  options: WaveCoinSimulationOptions,
): WaveCoinSimRow[] {
  const rows: WaveCoinSimRow[] = []
  forEachWaveCoinRow(input, options, (row) => rows.push(row))
  return rows
}
