/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    WaveEconSimRow, WaveEconSimTotals, WaveEconSimulationOptions, forEachWaveEconRow, accumulateWaveEcon, simulateWaveEconRows
 * depends    src/mechanics/enemies/drops-wave-context, src/mechanics/resource-drops/coin-multipliers, src/mechanics/resource-drops/coin-simulation-types, src/mechanics/resource-drops/wave-drop-yield, src/mechanics/resource-drops/wave-ordinary-coin-weight, src/mechanics/resource-drops/wave-skip-per-wave (+3 more)
 * used by    src/mechanics/calculators/specs-generated, src/mechanics/resource-drops/accumulate-wave-econ, src/mechanics/resource-drops/index
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
import { buildWaveContext } from '../enemies/drops-wave-context'
import { findWaveAcceleratorMasteryForSpawnCap, enemySpawnRateCapFromWaveAcceleratorChart } from '../waves/accelerator-spawn-rate-cap'
import { resolveWaveSpawnYieldFromAccount } from '../waves/resolve-wave-spawn-yield'
import { killsPerWaveFromSpawnContext, type WaveSpawnYieldInput } from '../waves/wave-spawn-yield'
import { buildResourceDropsCoinMultipliers } from './coin-multipliers'
import type { ResourceDropsCoinSimulationInput } from './coin-simulation-types'
import { computeWaveDropYield } from './wave-drop-yield'
import { buildWaveSkipPerWaveAdjust, waveSkipIncomeEv } from './wave-skip-per-wave'
import { ordinaryCoinWeightAtWave } from './wave-ordinary-coin-weight'

export type WaveEconSimRow = {
  wave: number
  spawnTicks: number
  /** EV enemies killed on this wave index (zero when the wave is skipped). */
  expectedKills: number
  expectedEliteKills: number
  rawKillCoins: number
  waveCoins: number
  cells: number
  /** Cells from skip payout (compounds on prior wave total + multi-skip burst). */
  skipCells: number
  moduleShards: number
  /** Fleet module shards EV for one module type (5% proc). */
  moduleShardsOneType: number
  rerollShards: number
  isBossWave: boolean
  isFleetWave: boolean
  /** EV fraction of this wave index that spawns enemies. */
  spawnFraction: number
  /** Coin weight per kill at this wave (Wave Info spawn mix). */
  coinWeightPerKill: number
}

export type WaveEconSimTotals = {
  expectedKills: number
  expectedEliteKills: number
  rawKillCoins: number
  waveCoins: number
  cells: number
  skipCells: number
  moduleShards: number
  moduleShardsOneType: number
  rerollShards: number
  bossWaves: number
  fleetWaves: number
}

export type WaveEconSimulationOptions = {
  maxRows?: number
  spawnYield?: WaveSpawnYieldInput
}

function emptyWaveEconTotals(): WaveEconSimTotals {
  return {
    expectedKills: 0,
    expectedEliteKills: 0,
    rawKillCoins: 0,
    waveCoins: 0,
    cells: 0,
    skipCells: 0,
    moduleShards: 0,
    moduleShardsOneType: 0,
    rerollShards: 0,
    bossWaves: 0,
    fleetWaves: 0,
  }
}

function spawnYieldForWaveRow(
  input: ResourceDropsCoinSimulationInput,
  wave: number,
  override?: WaveSpawnYieldInput,
): WaveSpawnYieldInput | undefined {
  if (override != null) return override
  if (input.spawnYield != null) return input.spawnYield
  if (!input.useAccountSpawnYield) return undefined
  return resolveWaveSpawnYieldFromAccount({
    tier: input.tier,
    wave,
    enemyBalanceMastery: input.enemyBalanceMasteryLevel,
    waveAcceleratorMastery: input.waveAcceleratorMasteryLevel,
    useDisasmGates: input.useDisasmSpawnGates === true,
    useDisasmQuantum: input.useDisasmQuantum,
    enemyDoubleSpawnThreshold: input.enemyDoubleSpawnThreshold,
    doubleSpawnThemeBucketBase: input.doubleSpawnThemeBucketBase,
    waveLengthSeconds: input.waveLengthSeconds,
    moreEnemiesHeatLevel: input.moreEnemiesHeatLevel,
    moreEnemiesResistance: input.moreEnemiesResistance,
  })
}

function foldWaveEconRow(totals: WaveEconSimTotals, row: WaveEconSimRow): void {
  totals.expectedKills += row.expectedKills
  totals.expectedEliteKills += row.expectedEliteKills
  totals.rawKillCoins += row.rawKillCoins
  totals.waveCoins += row.waveCoins
  totals.cells += row.cells
  totals.skipCells += row.skipCells
  totals.moduleShards += row.moduleShards
  totals.moduleShardsOneType += row.moduleShardsOneType
  totals.rerollShards += row.rerollShards
  if (row.isBossWave) totals.bossWaves += 1
  if (row.isFleetWave) totals.fleetWaves += 1
}

/** Shared per-wave loop — rows optional; totals path avoids row array allocation. */
export function forEachWaveEconRow(
  input: ResourceDropsCoinSimulationInput,
  options: WaveEconSimulationOptions = {},
  visit: (row: WaveEconSimRow) => void,
): void {
  const ctx = buildWaveContext(input)
  const wsAdjust = buildWaveSkipPerWaveAdjust(
    ctx.waveSkipSkipChance,
    ctx.waveSkipExpectedSkipsPerProc,
  )
  const waMastery = findWaveAcceleratorMasteryForSpawnCap(input.waveAcceleratorMasteryLevel)
  const multipliers = buildResourceDropsCoinMultipliers(input)
  const introCap = Math.max(0, Math.floor(Number(input.introSprintZeroCoinWaveCap) || 0))
  const limit = Math.min(
    ctx.targetWave,
    Math.max(1, Math.floor(Number(options.maxRows ?? ctx.targetWave) || ctx.targetWave)),
  )
  let prevWaveCells = 0
  let prevPlayedBaseCells = 0

  for (let wave = 1; wave <= limit; wave += 1) {
    const spawnFraction = wsAdjust.spawnFraction
    const spawnTicks = enemySpawnRateCapFromWaveAcceleratorChart({ wave, waveAcceleratorMastery: waMastery })
    const spawnYield = spawnYieldForWaveRow(input, wave, options.spawnYield)
    const fullKills = killsPerWaveFromSpawnContext({
      wave,
      enemyBalanceMult: ctx.enemyBalanceMult,
      waveAcceleratorMastery: waMastery,
      spawnYield,
    })
    const expectedKills = fullKills * spawnFraction
    const coinWeightPerKill = ordinaryCoinWeightAtWave(input.tier, wave)
    const rawKillCoins = wave <= introCap
      ? 0
      : expectedKills * wave * coinWeightPerKill
    const waveCoins = wave <= introCap ? 0 : multipliers.coinsPerWaveMult * spawnFraction

    const drops = computeWaveDropYield(input, wave, ctx.enemyBalanceMult, 1)
    const expectedEliteKills = drops.expectedEliteKills * spawnFraction
    const baseCells = drops.cells
    const playedBaseCells = baseCells * spawnFraction

    const skipCells = wave > 1
      ? waveSkipIncomeEv(
        prevWaveCells,
        prevPlayedBaseCells,
        ctx.waveSkipSkipChance,
        ctx.waveSkipExpectedSkipsPerProc,
        spawnFraction,
        wsAdjust.incomeMultiplier,
      )
      : 0
    const cells = playedBaseCells + skipCells

    let rerollShards = drops.rerollShards * spawnFraction
    let moduleShards = drops.moduleShards * spawnFraction
    let moduleShardsOneType = drops.moduleShardsOneType * spawnFraction
    if (drops.isBossWave) {
      const bossReroll = drops.rerollShards
      rerollShards = bossReroll * ctx.waveSkipResourceMult
      if (!drops.isFleetWave) {
        const bossModule = drops.moduleShards
        moduleShards = bossModule * ctx.waveSkipResourceMult
        moduleShardsOneType = 0
      }
    }

    visit({
      wave,
      spawnTicks,
      expectedKills,
      expectedEliteKills,
      rawKillCoins,
      waveCoins,
      cells,
      skipCells,
      moduleShards,
      moduleShardsOneType,
      rerollShards,
      isBossWave: drops.isBossWave,
      isFleetWave: drops.isFleetWave,
      spawnFraction,
      coinWeightPerKill,
    })
    prevWaveCells = cells
    prevPlayedBaseCells = playedBaseCells > 0 ? playedBaseCells : prevPlayedBaseCells
  }
}

/** Round totals without retaining per-wave rows (O(1) memory). */
export function accumulateWaveEcon(
  input: ResourceDropsCoinSimulationInput,
  options: WaveEconSimulationOptions = {},
): WaveEconSimTotals {
  const totals = emptyWaveEconTotals()
  forEachWaveEconRow(input, options, (row) => foldWaveEconRow(totals, row))
  return totals
}

export function simulateWaveEconRows(
  input: ResourceDropsCoinSimulationInput,
  options: WaveEconSimulationOptions = {},
): WaveEconSimRow[] {
  const rows: WaveEconSimRow[] = []
  forEachWaveEconRow(input, options, (row) => rows.push(row))
  return rows
}
