/**
 * Per-wave cells and shard yields (elite, boss, fleet).
 */
/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    WaveDropYieldRow, computeWaveDropYield
 * depends    src/mechanics/enemies/drops-game-data, src/mechanics/enemies/drops-simulation, src/mechanics/enemies/elite-spawn-chance, src/mechanics/resource-drops/coin-simulation-types
 * used by    src/mechanics/calculators/specs-generated, src/mechanics/resource-drops/index, src/mechanics/resource-drops/simulate-wave-econ
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
import {
  averageEliteCellsPerKill,
  cellsPerKillBonusMult,
} from '../enemies/drops-simulation'
import {
  computeWaveInfoBossWaveInterval,
  expectedEliteKillsPerWave,
  fleetSpawnSchedule,
  isBossSpawnWave,
  isFleetSpawnWave,
} from '../enemies/elite-spawn-chance'
import {
  FLEET_MODULE_SHARD_PROC,
  FLEET_REROLL_SHARD_PROC,
  expectedFleetModuleShardsEv,
  getEnemyDropsLabBenefits,
  getExpectedBossRerollShardsPerKill,
  getFleetRewardRow,
  getShatterShards,
} from '../enemies/drops-game-data'
import type { ResourceDropsCoinSimulationInput } from './coin-simulation-types'

export type WaveDropYieldRow = {
  expectedEliteKills: number
  cells: number
  /** Module shards EV summed across all four types. */
  moduleShards: number
  /** Module shards EV for one type (5% proc × tier table). */
  moduleShardsOneType: number
  rerollShards: number
  isBossWave: boolean
  isFleetWave: boolean
  fleetCount: number
}

export function computeWaveDropYield(
  input: ResourceDropsCoinSimulationInput,
  wave: number,
  enemyBalanceMult: number,
  wsMult: number,
): WaveDropYieldRow {
  const tier = input.tier
  const w = Math.max(1, Math.floor(wave))
  const labs = getEnemyDropsLabBenefits(input)
  const baseCellsPerElite =
    averageEliteCellsPerKill(tier) * cellsPerKillBonusMult(input.cellsPerKillBonusLevel)
    + labs.deathWaveCellsBonus

  const expectedEliteKills =
    expectedEliteKillsPerWave(tier, w, { enemyBalanceMastery: input.enemyBalanceMasteryLevel })
    * enemyBalanceMult

  const cells = expectedEliteKills * baseCellsPerElite * wsMult
  let moduleShards = 0
  let moduleShardsOneType = 0
  let rerollShards = 0

  const bossInterval = computeWaveInfoBossWaveInterval({ tier })
  const isBossWave = isBossSpawnWave(w, bossInterval)

  if (isBossWave) {
    rerollShards += getExpectedBossRerollShardsPerKill(tier, labs.rerollShardsBenefit) * wsMult
    const commonShatterYield = getShatterShards('common', labs.shatterBenefit)
    const rareShatterYield = getShatterShards('rare', labs.shatterBenefit)
    if (input.shatterCommonModules) {
      moduleShards += labs.commonDropChance * commonShatterYield * wsMult
    }
    if (input.shatterRareModules) {
      moduleShards += labs.rareDropChance * rareShatterYield * wsMult
    }
  }

  const isFleetWave = isFleetSpawnWave(tier, w)
  let fleetCount = 0
  if (isFleetWave) {
    fleetCount = fleetSpawnSchedule(tier)?.fleetsPerSpawn ?? 0
    const fleetReward = getFleetRewardRow(tier)
    if (fleetReward && fleetCount > 0) {
      rerollShards +=
        fleetCount * FLEET_REROLL_SHARD_PROC * fleetReward.rerollShards * wsMult
      moduleShards = expectedFleetModuleShardsEv(
        fleetCount,
        fleetReward.moduleShardsPerType,
        wsMult,
        'allTypes',
      )
      moduleShardsOneType = expectedFleetModuleShardsEv(
        fleetCount,
        fleetReward.moduleShardsPerType,
        wsMult,
        'oneType',
      )
    }
  }

  return {
    expectedEliteKills,
    cells,
    moduleShards,
    moduleShardsOneType,
    rerollShards,
    isBossWave,
    isFleetWave,
    fleetCount,
  }
}
