/**
 * Per-wave ordinary enemy coin weight from tier spawn chance weights.
 *
 * Uses `ordinarySpawnChancesForCoinMix` (fast/tank/ranged scaled by tier; basic
 * fills the remainder). Protector is excluded — spawn-gated, not in the basic
 * draw pool — see `spawn-type-chances-coin-mix.ts`.
 */
/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    PROTECTOR_COIN_VALUE, ordinaryCoinWeightFromSpawnChances, ordinaryCoinWeightAtWave, ENEMY_TYPE_BASE_COIN_VALUE, measuredAverageEnemyCoinWeight
 * depends    src/mechanics/enemies/type-mix, src/mechanics/waves/spawn-type-chances-coin-mix
 * used by    src/mechanics/calculators/specs-generated, src/mechanics/resource-drops/index, src/mechanics/resource-drops/simulate-wave-coins, src/mechanics/resource-drops/simulate-wave-econ
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
import {
  averageEnemyCoinWeight,
  ENEMY_TYPE_BASE_COIN_VALUE,
  measuredAverageEnemyCoinWeight,
  type EnemyTypeCounts,
} from '../enemies/type-mix'
import { ordinarySpawnChancesForCoinMix } from '../waves/spawn-type-chances-coin-mix'

/** Coin value of a protector kill relative to basic (= tier × 1). */
export const PROTECTOR_COIN_VALUE = 1 as const

export function ordinaryCoinWeightFromSpawnChances(chances: {
  Basic: number
  Fast: number
  Tank: number
  Ranged: number
  Protector?: number
}): number {
  const counts: EnemyTypeCounts = {
    basic: Math.max(0, chances.Basic),
    fast: Math.max(0, chances.Fast),
    tank: Math.max(0, chances.Tank),
    ranged: Math.max(0, chances.Ranged),
  }
  const protector = Math.max(0, chances.Protector ?? 0)
  const total = counts.basic + counts.fast + counts.tank + counts.ranged + protector
  if (total <= 0) return measuredAverageEnemyCoinWeight()
  let weighted = 0
  for (const type of Object.keys(ENEMY_TYPE_BASE_COIN_VALUE) as (keyof EnemyTypeCounts)[]) {
    weighted += counts[type] * ENEMY_TYPE_BASE_COIN_VALUE[type]
  }
  weighted += protector * PROTECTOR_COIN_VALUE
  return weighted / total
}

/** Coin value per ordinary kill at this tier/wave (relative to basic = 1). */
export function ordinaryCoinWeightAtWave(tier: number, wave: number): number {
  const chances = ordinarySpawnChancesForCoinMix(tier, wave)
  return ordinaryCoinWeightFromSpawnChances(chances)
}

export { ENEMY_TYPE_BASE_COIN_VALUE, measuredAverageEnemyCoinWeight }
