/**
 * Per-wave wave skip EV — skipped waves spawn nothing; skip payout compounds 1.1^n.
 *
 * Sequential rows compound on the previous wave's **total** (wiki). Multi-skip procs
 * add a burst correction because several skip slots in one chain pay 1.1^k on the
 * anchor played wave, not only 1.1 × previous total per slot.
 */
/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    WaveSkipPerWaveAdjust, waveSkipSpawnFraction, waveSkipChainIncomeFactor, waveSkipIncomeEv, buildWaveSkipPerWaveAdjust
 * depends    src/mechanics/enemies/drops-simulation, src/mechanics/primitives/math
 * used by    src/mechanics/calculators/specs-generated, src/mechanics/resource-drops/index, src/mechanics/resource-drops/simulate-wave-coins, src/mechanics/resource-drops/simulate-wave-econ
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
import {
  WAVE_SKIP_SKIPPED_WAVE_MULT,
  waveSkipResourceMultiplier,
} from '../enemies/drops-simulation'
import { clamp } from '../primitives/math'

export type WaveSkipPerWaveAdjust = {
  /** EV fraction of nominal wave indices that spawn enemies. */
  spawnFraction: number
  /** Round-level resource multiplier (cells/shards aggregate model). */
  resourceMult: number
  /** Per skipped slot income vs the prior played wave (wiki: 1.1). */
  incomeMultiplier: number
  /** Expected compound sum 1.1^1 + … + 1.1^extra for multi-skip procs. */
  chainIncomeFactor: number
}

/**
 * EV spawn fraction when skip procs with expected multi-skip depth.
 *
 * Each proc advances `expectedSkipsPerProc` wave counters while only the anchor wave spawned;
 * `(expectedSkipsPerProc - 1)` slots in that chain are skip-only.
 */
export function waveSkipSpawnFraction(
  skipChance: number,
  expectedSkipsPerProc: number,
): number {
  const p = clamp(skipChance, 0, 1)
  const extra = Math.max(0, expectedSkipsPerProc - 1)
  if (p <= 0 || extra <= 0) return 1
  return 1 / (1 + p * extra)
}

/** Sum of 1.1^k for k = 1..extra (extra = expectedSkipsPerProc − 1). */
export function waveSkipChainIncomeFactor(
  expectedSkipsPerProc: number,
  incomeMult: number = WAVE_SKIP_SKIPPED_WAVE_MULT,
): number {
  const extra = Math.max(0, expectedSkipsPerProc - 1)
  if (extra <= 0) return 0
  return incomeMult * (Math.pow(incomeMult, extra) - 1) / (incomeMult - 1)
}

/**
 * Skip payout EV for one nominal wave (cells, kill coins, etc.).
 *
 * @param prevTotal - previous wave's total payout (compounds on this)
 * @param anchorPlayedBase - previous wave's pre-skip spawn payout (multi-skip chain anchor)
 */
export function waveSkipIncomeEv(
  prevTotal: number,
  anchorPlayedBase: number,
  skipChance: number,
  expectedSkipsPerProc: number,
  spawnFraction: number,
  incomeMult: number = WAVE_SKIP_SKIPPED_WAVE_MULT,
): number {
  const skipFrac = clamp(1 - spawnFraction, 0, 1)
  if (skipFrac <= 0) return 0

  const linearOnPrev = prevTotal > 0 ? skipFrac * incomeMult * prevTotal : 0
  const extra = Math.max(0, expectedSkipsPerProc - 1)
  const p = clamp(skipChance, 0, 1)
  if (extra <= 0 || p <= 0 || anchorPlayedBase <= 0) return linearOnPrev

  const chainFactor = waveSkipChainIncomeFactor(expectedSkipsPerProc, incomeMult)
  const burstBonus =
    p * anchorPlayedBase * Math.max(0, chainFactor - incomeMult) / (1 + p * extra)

  return linearOnPrev + burstBonus
}

export function buildWaveSkipPerWaveAdjust(
  skipChance: number,
  expectedSkipsPerProc: number,
): WaveSkipPerWaveAdjust {
  return {
    spawnFraction: waveSkipSpawnFraction(skipChance, expectedSkipsPerProc),
    resourceMult: waveSkipResourceMultiplier(skipChance, expectedSkipsPerProc),
    incomeMultiplier: WAVE_SKIP_SKIPPED_WAVE_MULT,
    chainIncomeFactor: waveSkipChainIncomeFactor(expectedSkipsPerProc),
  }
}
