/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    epGraphToSdkModule, mergeSdkGraphs
 * depends    src/mechanics/ep-graph/schema, tooling/sdk-graph/schema
 * used by    tooling/sdk-graph/index
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
import type { EpGraph } from '../../src/mechanics/ep-graph/schema'
import {
  epFamilyToSdk,
  type SdkGraph,
  type SdkGraphEdge,
  type SdkGraphNode,
} from './schema'

/** Lift an EP module graph into SDK-namespaced families (ep.*). */
export function epGraphToSdkModule(ep: EpGraph): Pick<SdkGraph, 'nodes' | 'edges'> {
  const nodes: Record<string, SdkGraphNode> = {}
  for (const node of Object.values(ep.nodes)) {
    nodes[node.id] = {
      id: node.id,
      family: epFamilyToSdk(node.family),
      type: node.type as SdkGraphNode['type'],
      label: node.label,
      module: 'ep',
      sourceCells: (node.sourceCells ?? []).map(c => ({
        sheet: c.sheet,
        cell: c.cell,
        kind: c.kind,
      })),
      wikiPages: node.wikiTitles ?? [],
      codeSymbols: [],
      dependsOn: [],
      formula: node.formula,
      formulaSource: node.formulaSource,
      traps: node.traps ?? [],
      status: node.status,
      lambdaName: node.lambdaName,
    }
  }
  const edges: SdkGraphEdge[] = ep.edges.map(e => ({
    id: e.id,
    from: e.from,
    to: e.to,
    kind: e.kind as SdkGraphEdge['kind'],
    module: 'ep',
    evidence: {
      sourceCells: e.evidence.sourceCells?.map(c => ({
        sheet: c.sheet,
        cell: c.cell,
        kind: c.kind,
      })),
      wikiTitle: e.evidence.wikiTitle,
      lambdaName: e.evidence.lambdaName,
    },
  }))
  return { nodes, edges }
}

export function mergeSdkGraphs(
  core: SdkGraph,
  modules: Array<{ name: string, nodes: Record<string, SdkGraphNode>, edges: SdkGraphEdge[] }>,
): SdkGraph {
  const nodes = { ...core.nodes }
  const edges = [...core.edges]
  const contentVersion = core.contentVersion

  for (const mod of modules) {
    for (const [id, node] of Object.entries(mod.nodes)) {
      if (nodes[id] && nodes[id].module !== mod.name) {
        throw new Error(`sdk-graph node id collision: ${id} (${nodes[id].module} vs ${mod.name})`)
      }
      nodes[id] = node
    }
    for (const edge of mod.edges) {
      if (edges.some(e => e.id === edge.id && e.module !== mod.name)) {
        throw new Error(`sdk-graph edge id collision: ${edge.id}`)
      }
      if (!edges.some(e => e.id === edge.id)) edges.push(edge)
    }
  }

  return {
    ...core,
    contentVersion,
    nodes,
    edges,
  }
}
