/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    SdkMermaidSlice, renderSdkGraphMermaidSlices
 * depends    tooling/sdk-graph/schema
 * used by    tooling/sdk-graph/index
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
import type { SdkGraph, SdkGraphFamily, SdkGraphNodeType } from './schema'

function mermaidId(id: string): string {
  return id.replace(/[^A-Za-z0-9_]/g, '_')
}

function escapeLabel(label: string): string {
  return label.replace(/"/g, "'")
}

export interface SdkMermaidSlice {
  name: string
  mermaid: string
}

function renderFamilySlice(graph: SdkGraph, family: SdkGraphFamily, types: SdkGraphNodeType[] | null): string {
  const nodes = Object.values(graph.nodes).filter(n => {
    if (n.family !== family) return false
    if (types && !types.includes(n.type)) return false
    return true
  })
  const ids = new Set(nodes.map(n => n.id))
  const edges = graph.edges.filter(e => ids.has(e.from) && ids.has(e.to))
  const lines = [
    'flowchart LR',
    `%% ${family} · sdk contentVersion ${graph.contentVersion}`,
  ]
  const byType = new Map<string, typeof nodes>()
  for (const n of nodes) {
    const list = byType.get(n.type) ?? []
    list.push(n)
    byType.set(n.type, list)
  }
  for (const [type, group] of [...byType.entries()].sort((a, b) => a[0].localeCompare(b[0]))) {
    lines.push(`  subgraph ${mermaidId(`${type}_${family}`)} ["${type}"]`)
    for (const n of group.sort((a, b) => a.id.localeCompare(b.id))) {
      lines.push(`    ${mermaidId(n.id)}["${escapeLabel(n.label)}"]`)
    }
    lines.push('  end')
  }
  for (const e of edges.sort((a, b) => a.id.localeCompare(b.id))) {
    lines.push(`  ${mermaidId(e.from)} -->|${e.kind}| ${mermaidId(e.to)}`)
  }
  return `${lines.join('\n')}\n`
}

export function renderSdkGraphMermaidSlices(graph: SdkGraph): SdkMermaidSlice[] {
  const families = [...new Set(Object.values(graph.nodes).map(n => n.family))].sort() as SdkGraphFamily[]
  const slices: SdkMermaidSlice[] = []
  for (const family of families) {
    const safe = family.replace(/\./g, '_')
    slices.push({ name: safe, mermaid: renderFamilySlice(graph, family, null) })
  }
  return slices
}
