/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    TrustMode, TrustReport, BuildTrustReportOptions, buildTrustReport, formatTrustReportMarkdown
 * depends    tooling/coverage/data/sheets.v1.json, tooling/coverage/schema, tooling/sdk-graph/build-index, tooling/sdk-graph/invariants, tooling/sdk-graph/schema, tooling/sdk-graph/validate
 * used by    tooling/kernel/schema, tooling/kernel/validate, tooling/sdk-graph/index
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
import type { SdkGraph } from './schema'
import { validateSdkGraph, type SdkGraphValidation } from './validate'
import { buildSdkGraphIndex } from './build-index'
import {
  runSdkGraphInvariants,
  type InvariantHit,
  type InvariantOptions,
} from './invariants'
import {
  CoverageInventorySchema,
  coverageStatusCounts,
  findSilentGaps,
  type CoverageInventory,
} from '../coverage/schema'
import sheetsInventoryRaw from '../coverage/data/sheets.v1.json'

export type TrustMode = 'strict' | 'degraded'

export interface TrustReport {
  ok: boolean
  mode: TrustMode
  structural: SdkGraphValidation
  invariants: InvariantHit[]
  coverage: {
    silentGaps: string[]
    counts: Record<string, number>
  }
  trustSummary: {
    byStatus: Record<string, number>
  }
  drift?: {
    checkedAt: string
    mismatches: unknown[]
  }
}

export interface BuildTrustReportOptions extends InvariantOptions {
  mode?: TrustMode
  sheetsInventory?: CoverageInventory
}

function defaultSheetsInventory(): CoverageInventory {
  return CoverageInventorySchema.parse(sheetsInventoryRaw)
}

export function buildTrustReport(
  graph: SdkGraph,
  opts: BuildTrustReportOptions = {},
): TrustReport {
  const mode = opts.mode ?? 'strict'
  const sheets = opts.sheetsInventory ?? defaultSheetsInventory()
  const structural = validateSdkGraph(graph)
  const invariants = runSdkGraphInvariants(graph, { ...opts, sheetsInventory: sheets })
  const index = buildSdkGraphIndex(graph)

  const silentGaps = findSilentGaps(sheets).map(e => e.id)
  const counts = coverageStatusCounts(sheets)

  const errorInvariants = invariants.filter(h => h.severity === 'error')
  const ok = structural.errors.length === 0 && errorInvariants.length === 0

  return {
    ok,
    mode,
    structural,
    invariants,
    coverage: { silentGaps, counts },
    trustSummary: {
      byStatus: Object.fromEntries(
        Object.entries(index.byStatus).map(([k, v]) => [k, v.length]),
      ),
    },
  }
}

export function formatTrustReportMarkdown(report: TrustReport): string {
  const lines = [
    `# Mechanics trust report`,
    ``,
    `- **ok:** ${report.ok}`,
    `- **mode:** ${report.mode}`,
    `- **structural errors:** ${report.structural.errors.length}`,
    `- **structural warnings:** ${report.structural.warnings.length}`,
    `- **invariant errors:** ${report.invariants.filter(i => i.severity === 'error').length}`,
    `- **invariant warnings:** ${report.invariants.filter(i => i.severity === 'warning').length}`,
    `- **silent coverage gaps:** ${report.coverage.silentGaps.length}`,
    ``,
    `## Coverage counts`,
    ...Object.entries(report.coverage.counts).map(([k, v]) => `- ${k}: ${v}`),
    ``,
    `## Trust by status`,
    ...Object.entries(report.trustSummary.byStatus).map(([k, v]) => `- ${k}: ${v}`),
    ``,
  ]
  if (report.invariants.length) {
    lines.push(`## Invariants`)
    for (const hit of report.invariants) {
      lines.push(`- **${hit.severity}** \`${hit.id}\`: ${hit.message}`)
    }
    lines.push('')
  }
  if (report.structural.errors.length) {
    lines.push(`## Structural errors`)
    for (const e of report.structural.errors) lines.push(`- ${e}`)
    lines.push('')
  }
  return lines.join('\n')
}
