/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    —
 * depends    src/mechanics/waves/reference/base-constants, src/mechanics/waves/reference/base-scaling-legacy, src/mechanics/waves/reference/public-wave-formulas
 * used by    —
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
export * from './base-constants'
export * from './base-scaling-legacy'
export * from './public-wave-formulas'
