/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    ILM_DAMAGE_MODULE_SUBSTAT_LABEL, ILM_MODULE_SUBSTAT_NONE, IlmModuleSubstatRarityChoice, IlmUniqueModuleRarityChoice, ILM_UNIQUE_MODULE_ID_BY_KEY, IlmUniqueModuleId, IlmSelectOption, parseIlmModuleSubstatBonus (+6 more)
 * depends    src/data
 * used by    src/mechanics/calculators/specs-generated, src/mechanics/modules/ilm-calculator-resolve, src/mechanics/modules/ilm-charge, src/mechanics/modules/index
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
import { BOT_UPGRADES_DATA, botStatValueAt, formatBotStatValue } from '../../data'
import { getModuleTemplate } from '../../data'
import { MODULE_SUBSTAT_CANONICAL_DATA } from '../../data'

export const ILM_DAMAGE_MODULE_SUBSTAT_LABEL = 'Inner Land Mines - Damage'
export const ILM_MODULE_SUBSTAT_NONE = 'none' as const

export type IlmModuleSubstatRarityChoice =
  | typeof ILM_MODULE_SUBSTAT_NONE
  | 'Common'
  | 'Rare'
  | 'Epic'
  | 'Legendary'
  | 'Mythic'
  | 'Ancestral'

export type IlmUniqueModuleRarityChoice =
  | typeof ILM_MODULE_SUBSTAT_NONE
  | 'Epic'
  | 'Legendary'
  | 'Mythic'
  | 'Ancestral'

export const ILM_UNIQUE_MODULE_ID_BY_KEY = {
  dimensionCore: 'dimension-core',
  magneticHook: 'magnetic-hook',
  singularityHarness: 'singularity-harness',
  antiCubePortal: 'anti-cube-portal',
} as const

export type IlmUniqueModuleId = typeof ILM_UNIQUE_MODULE_ID_BY_KEY[keyof typeof ILM_UNIQUE_MODULE_ID_BY_KEY]

export interface IlmSelectOption<T = number | string> {
  title: string
  value: T
}

function ilmDamageSubstatDefinition() {
  return MODULE_SUBSTAT_CANONICAL_DATA.Core.substats.find(
    entry => entry.label === ILM_DAMAGE_MODULE_SUBSTAT_LABEL,
  )
}

export function parseIlmModuleSubstatBonus(raw: string | null | undefined): number {
  if (!raw) return 0
  const parsed = Number.parseFloat(String(raw).replace(/[^\d.]/g, ''))
  return Number.isFinite(parsed) ? parsed : 0
}

export function buildIlmModuleSubstatRarityOptions(): IlmSelectOption<IlmModuleSubstatRarityChoice>[] {
  const definition = ilmDamageSubstatDefinition()
  const options: IlmSelectOption<IlmModuleSubstatRarityChoice>[] = [
    { title: 'None', value: ILM_MODULE_SUBSTAT_NONE },
  ]
  if (!definition) return options

  for (const rarity of definition.availableRarities) {
    const display = definition.valuesByRarity[rarity]
    if (!display) continue
    options.push({
      title: `${rarity} (${display})`,
      value: rarity as IlmModuleSubstatRarityChoice,
    })
  }
  return options
}

export function ilmModuleSubstatBonusFromRarity(
  rarity: IlmModuleSubstatRarityChoice,
): number {
  if (rarity === ILM_MODULE_SUBSTAT_NONE) return 0
  const definition = ilmDamageSubstatDefinition()
  const raw = definition?.valuesByRarity[rarity]
  return parseIlmModuleSubstatBonus(raw)
}

export function buildIlmUniqueModuleRarityOptions(
  moduleId: IlmUniqueModuleId,
): IlmSelectOption<IlmUniqueModuleRarityChoice>[] {
  const template = getModuleTemplate(moduleId)
  const options: IlmSelectOption<IlmUniqueModuleRarityChoice>[] = [
    { title: 'Not equipped', value: ILM_MODULE_SUBSTAT_NONE },
  ]
  for (const bonus of template?.rarityBonuses ?? []) {
    options.push({
      title: `${bonus.rarity} (${bonus.value})`,
      value: bonus.rarity as IlmUniqueModuleRarityChoice,
    })
  }
  return options
}

export function computeIlmUniqueModuleRarityBonus(
  moduleId: IlmUniqueModuleId,
  rarity: IlmUniqueModuleRarityChoice,
): number {
  if (rarity === ILM_MODULE_SUBSTAT_NONE) return 0
  const template = getModuleTemplate(moduleId)
  const match = template?.rarityBonuses?.find(entry => entry.rarity === rarity)
  return match?.value ?? 0
}

export function computeAmplifyBotBonusMultiplier(level: number): number {
  const bot = BOT_UPGRADES_DATA.find(entry => entry.label === 'Amplify Bot')
  const stat = bot?.stats.Bonus
  if (!stat) return 1
  const value = botStatValueAt(stat, level)
  return Number.isFinite(value) && value > 0 ? value : 1
}

export function buildIlmAmplifyBotBonusLevelOptions(): IlmSelectOption[] {
  const bot = BOT_UPGRADES_DATA.find(entry => entry.label === 'Amplify Bot')
  const stat = bot?.stats.Bonus
  if (!stat) return []
  return Array.from({ length: stat.maxLevel + 1 }, (_, level) => ({
    title: `Level ${level} (${formatBotStatValue(stat, level)})`,
    value: level,
  }))
}
