/**
 * Enemy types and the multipliers that separate them.
 *
 * The type multiplier table is what makes a Fast different from a Tank at the same wave, and it is
 * consulted by wave stats, drops and level skip alike.
 */
/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    —
 * depends    src/data/enemies/data
 * used by    —
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
export * from './data'
