/**
 * Wave-base scaling entry point.
 *
 * Re-exports the empirical regression scaler; see `wave-base-empirical-scaling`
 * for how the coefficients behave and what accuracy to expect.
 */
/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    computeWaveBaseDamage, computeWaveBaseHealth, computeWaveBaseHealthRaw, damageTierDifficultyMultiplier, damageWave100Multiplier, healthTierDifficultyMultiplier, healthWave100Multiplier, tierCoinMultiplier (+3 more)
 * depends    src/mechanics/waves/base-empirical-scaling
 * used by    src/mechanics/enemies/wave-stats, src/mechanics/waves/index
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
export {
  computeWaveBaseDamage,
  computeWaveBaseHealth,
  computeWaveBaseHealthRaw,
  damageTierDifficultyMultiplier,
  damageWave100Multiplier,
  healthTierDifficultyMultiplier,
  healthWave100Multiplier,
  tierCoinMultiplier,
  tierDifficultyMultiplier,
  wave100Multiplier,
  type WaveBaseScalingInput,
} from './base-empirical-scaling'
