/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    MAIN_SPAWN_TYPE_FIELD_OFFSETS_V29, NEW_WAVE_SPAWN_TYPE_CHANCE_WRITES_V29, COIN_MIX_TIER_SPAWN_COEFF_V29
 * depends    —
 * used by    src/mechanics/waves/index, src/mechanics/waves/spawn-type-chances-coin-mix
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
/**
/**
 * Main.chance*Enemy field layout and NewWave write set (game v29.0.0).
 *
 * Scene primary (`MAIN_SPAWN_TYPE_SCENE_CHANCES_V29`) is absolute level1 Main
 * Inspector defaults (e.g. fast=15, tank=15), not tier-weight coefficients.
 * `COIN_MIX_TIER_SPAWN_COEFF_V29` remains the coin-mix SoT until the NewWave /
 * tier formula for fast/ranged/tank at high tier is ported.
 */
export const MAIN_SPAWN_TYPE_FIELD_OFFSETS_V29 = {
  chanceNormalEnemy: 0x5e0,
  chanceFastEnemy: 0x5e4,
  chanceTankEnemy: 0x5e8,
  chanceRangedEnemy: 0x5ec,
  chanceProtectorEnemy: 0x5f0,
  protectorEnemyLastWaveSpawned: 0x5f4,
  protectorEnemyWavesUntilNextCanSpawn: 0x5f8,
} as const

/** Fields NewWave stores each wave - fast/ranged stay scene-serialized. */
export const NEW_WAVE_SPAWN_TYPE_CHANCE_WRITES_V29 = [
  'chanceNormalEnemy',
  'chanceProtectorEnemy',
  'chanceTankEnemy',
  'protectorEnemyWavesUntilNextCanSpawn',
] as const

/**
 * Fitted tier-weight coeffs for ordinary coin mix (~3.x), not scene ints.
 * Coin mix SoT until NewWave/tier evolution for fast/ranged/tank is ported.
 */
export const COIN_MIX_TIER_SPAWN_COEFF_V29 = {
  fast: 3.294,
  tank: 3.019,
  ranged: 2.881,
} as const
