/**
 * Bridge account + wave context -> WaveSpawnYieldInput for coin / drop simulators.
 *
 * Main.enemySpawnChance (field @ +0x1A8) is the **0-100 master spawn gate** set in NewWave
 * from the Wave Accelerator chart (+ wave-band bonuses). Under the calibrated path it is
 * still treated as a tick-count multiplier; under disasm quantum it is the master threshold.
 */
/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    ResolveWaveSpawnYieldInput, moreEnemiesResistanceFromHeat, waveSpawnDoubleChanceFromEliteChart, resolveWaveSpawnYieldFromAccount, expectedEnemiesPerSpawnTickFromAccount, expectedEnemiesPerWaveFromAccount
 * depends    src/mechanics/enemies/elite-spawn-chance, src/mechanics/enemies/get-resistance-level, src/mechanics/uptime/compute, src/mechanics/waves/accelerator-spawn-rate-cap, src/mechanics/waves/update-spawn-gate-pass, src/mechanics/waves/wave-spawn-disasm-constants (+1 more)
 * used by    src/mechanics/calculators/specs-generated, src/mechanics/resource-drops/coin-multipliers, src/mechanics/resource-drops/simulate-wave-coins, src/mechanics/resource-drops/simulate-wave-econ, src/mechanics/waves/index
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
import { waveInfoEliteEffectiveDoubleSpawnPct } from '../enemies/elite-spawn-chance'
import { getResistanceLevel } from '../enemies/get-resistance-level'
import { computeWaveCombatDurationSeconds } from '../uptime/compute'
import { enemySpawnRateCapFromWaveAcceleratorChart } from './accelerator-spawn-rate-cap'
import {
  WAVE_SPAWN_RANDOM_BASIC_CALL_SITE_COUNT_V29,
  expectedEnemiesPerSpawnTickFromWaveGates,
} from './wave-spawn-disasm-constants'
import type { WaveSpawnYieldInput } from './wave-spawn-yield'
import {
  expectedEnemiesPerSpawnQuantumFromDisasmV29,
  expectedEnemiesPerSpawnTickFromDisasmGatesV29,
  expectedEnemiesPerWaveFromDisasmQuantumV29,
  newWaveEnemyDoubleSpawnThresholdV29,
} from './update-spawn-gate-pass'

export type ResolveWaveSpawnYieldInput = {
  tier: number
  wave: number
  enemyBalanceMastery?: number | null
  waveAcceleratorMastery?: number | null
  randomBasicCallSites?: number | null
  randomBasicGatePassRate?: number | null
  enemyDoubleSpawnChance?: number | null
  useDisasmGates?: boolean
  /**
   * When useDisasmGates: quantum model (default true). Set false for additive probe.
   */
  useDisasmQuantum?: boolean
  waveLengthSeconds?: number | null
  /** +0x1AC on 0-100 scale; omit under quantum -> NewWave base 5. */
  enemyDoubleSpawnThreshold?: number | null
  /** Theme-bucket base for +0x1AC; default 5 when useDisasmGates and threshold omitted. */
  doubleSpawnThemeBucketBase?: number | null
  /** Override Main.enemySpawnChance (+0x1A8) for disasm master gate; defaults to WA chart. */
  spawnTickCap?: number | null
  /** heatLevel[7] More Enemies; used only when useDisasmGates. */
  moreEnemiesHeatLevel?: number | null
  /** Direct GetResistanceLevel(7) override; wins over heat when set. */
  moreEnemiesResistance?: number | null
}

export function moreEnemiesResistanceFromHeat(heatLevel: number | null | undefined): number {
  const heat = Math.max(0, Math.floor(Number(heatLevel) || 0))
  if (heat <= 0) return 1
  return getResistanceLevel({
    heatLevel: heat,
    workshopGlobal0x33C: 0,
    perBcWorkshopBase: 0,
  })
}

export function waveSpawnDoubleChanceFromEliteChart(input: {
  tier: number
  wave: number
  enemyBalanceMastery?: number | null
}): number {
  const pct = waveInfoEliteEffectiveDoubleSpawnPct(input.tier, input.wave, {
    enemyBalanceMastery: input.enemyBalanceMastery,
  })
  return Math.max(0, Math.min(1, pct / 100))
}

export function resolveWaveSpawnYieldFromAccount(
  input: ResolveWaveSpawnYieldInput | null | undefined,
): WaveSpawnYieldInput | undefined {
  if (input == null) return undefined
  const wave = Math.max(1, Math.floor(Number(input.wave) || 1))
  const tier = Math.max(1, Math.floor(Number(input.tier) || 1))
  const sites = Math.max(0, Math.floor(Number(input.randomBasicCallSites ?? WAVE_SPAWN_RANDOM_BASIC_CALL_SITE_COUNT_V29) || 0))
  const gatePass = input.randomBasicGatePassRate != null ? Math.max(0, Math.min(1, Number(input.randomBasicGatePassRate) || 0)) : 1
  // Elite chart keeps additive-probe backward compat; quantum uses enemyDoubleSpawnThreshold (base 5).
  const doubleChance = input.enemyDoubleSpawnChance != null ? Math.max(0, Math.min(1, Number(input.enemyDoubleSpawnChance) || 0)) : waveSpawnDoubleChanceFromEliteChart({ tier, wave, enemyBalanceMastery: input.enemyBalanceMastery })
  return {
    randomBasicCallSites: sites,
    randomBasicGatePassRate: gatePass,
    enemyDoubleSpawnChance: doubleChance,
    useDisasmGates: input.useDisasmGates === true,
    useDisasmQuantum: input.useDisasmQuantum,
    waveLengthSeconds: input.waveLengthSeconds,
    enemyDoubleSpawnThreshold:
      input.enemyDoubleSpawnThreshold != null
        ? Number(input.enemyDoubleSpawnThreshold)
        : input.useDisasmGates
          ? newWaveEnemyDoubleSpawnThresholdV29({
              tier,
              themeBucketBase: input.doubleSpawnThemeBucketBase,
            })
          : undefined,
    spawnTickCap: input.spawnTickCap,
    moreEnemiesResistance:
      input.moreEnemiesResistance != null
        ? Number(input.moreEnemiesResistance)
        : input.moreEnemiesHeatLevel != null
          ? moreEnemiesResistanceFromHeat(input.moreEnemiesHeatLevel)
          : undefined,
  }
}

/**
 * Expected enemies per spawn tick / quantum from account context.
 * Under disasm quantum (default when useDisasmGates): per-quantum EV (master x cluster).
 * Under additive probe (useDisasmQuantum:false): sum of site EVs.
 * Calibrated path: uniform gate formula.
 */
export function expectedEnemiesPerSpawnTickFromAccount(input: ResolveWaveSpawnYieldInput): number {
  const yieldInput = resolveWaveSpawnYieldFromAccount(input)
  if (!yieldInput) return 0
  if (yieldInput.useDisasmGates) {
    const cap = enemySpawnRateCapFromWaveAcceleratorChart({
      wave: Math.max(1, Math.floor(Number(input.wave) || 1)),
      waveAcceleratorMastery: input.waveAcceleratorMastery,
    })
    const threshold = yieldInput.spawnTickCap ?? cap
    if (yieldInput.useDisasmQuantum !== false) {
      return expectedEnemiesPerSpawnQuantumFromDisasmV29({
        enemySpawnChanceThreshold: threshold,
        enemyDoubleSpawnThreshold: yieldInput.enemyDoubleSpawnThreshold,
        moreEnemiesResistance: yieldInput.moreEnemiesResistance,
      })
    }
    return expectedEnemiesPerSpawnTickFromDisasmGatesV29({
      spawnTickCap: threshold,
      enemyDoubleSpawnChance: yieldInput.enemyDoubleSpawnChance,
      moreEnemiesResistance: yieldInput.moreEnemiesResistance,
    })
  }
  return expectedEnemiesPerSpawnTickFromWaveGates({
    randomBasicCallSites: yieldInput.randomBasicCallSites ?? undefined,
    randomBasicGatePassRate: yieldInput.randomBasicGatePassRate ?? 1,
    enemyDoubleSpawnChance: yieldInput.enemyDoubleSpawnChance ?? undefined,
  })
}

/** Full-wave expected ordinary enemies (quantum or calibrated tick-count model). */
export function expectedEnemiesPerWaveFromAccount(
  input: ResolveWaveSpawnYieldInput & { enemyBalanceMult?: number },
): number {
  const yieldInput = resolveWaveSpawnYieldFromAccount(input)
  if (!yieldInput) return 0
  const wave = Math.max(1, Math.floor(Number(input.wave) || 1))
  const cap = enemySpawnRateCapFromWaveAcceleratorChart({
    wave,
    waveAcceleratorMastery: input.waveAcceleratorMastery,
  })
  const eb = input.enemyBalanceMult ?? 1
  if (yieldInput.useDisasmGates && yieldInput.useDisasmQuantum !== false) {
    return expectedEnemiesPerWaveFromDisasmQuantumV29({
      waveLengthSeconds: yieldInput.waveLengthSeconds ?? computeWaveCombatDurationSeconds(false),
      enemySpawnChanceThreshold: yieldInput.spawnTickCap ?? cap,
      enemyDoubleSpawnThreshold: yieldInput.enemyDoubleSpawnThreshold,
      moreEnemiesResistance: yieldInput.moreEnemiesResistance,
      enemyBalanceMult: eb,
    })
  }
  return cap * eb * expectedEnemiesPerSpawnTickFromAccount(input)
}
