/**
 * Per-site WaveUpdate spawn gate pass rates (game v29.0.0).
 *
 * Three heterogeneous gates precede SpawnRandomBasicEnemy.
 *
 * Master-gate quantum model: enemySpawnChance is a 0-100 gate over the whole
 * cluster; ticks/wave = waveLength/0.125.
 *
 * Default simulators keep the save-calibrated aggregate (3x1.0 + 0.25). Opt in via
 * `useDisasmGates` on WaveSpawnYieldInput when probing gate-derived yield.
 */
/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    waveUpdateTickCapGatePassRate, waveUpdateThresholdGtPassRate, waveUpdateThresholdGtePassRate, waveUpdateFixedIntGatePassRate, waveUpdateFloatComplementGatePassRate, expectedEnemiesPerSpawnTickFromDisasmGatesV29, newWaveEnemyDoubleSpawnThresholdV29, expectedEnemiesPerSpawnQuantumFromDisasmV29 (+2 more)
 * depends    src/mechanics/primitives/math, src/mechanics/waves/wave-update-spawn-gates-constants
 * used by    src/mechanics/calculators/specs-generated, src/mechanics/waves/index, src/mechanics/waves/resolve-wave-spawn-yield, src/mechanics/waves/wave-spawn-yield
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
import { clamp } from '../primitives/math'
import {
  WAVE_SPAWN_DOUBLE_CHANCE_BASE_THRESHOLD_V29,
  WAVE_SPAWN_DOUBLE_CHANCE_TIER_DIVISOR_V29,
  WAVE_SPAWN_TIMER_QUANTUM_SECONDS_V29,
  WAVE_UPDATE_GATE2_INT_THRESHOLD_V29,
  WAVE_UPDATE_GATE2_RANDOM_EXCLUSIVE_MAX_V29,
  WAVE_UPDATE_GATE3_COMPLEMENT_PASS_RATE_V29,
} from './wave-update-spawn-gates-constants'

/** Gate 1: spawn when Main.enemySpawnChance > Random.Range(0, 100). */
export function waveUpdateTickCapGatePassRate(spawnTickCap: number): number {
  const cap = Math.max(0, Number(spawnTickCap) || 0)
  const max = WAVE_UPDATE_GATE2_RANDOM_EXCLUSIVE_MAX_V29
  if (cap <= 0) return 0
  if (cap >= max) return 1
  return cap / max
}

/** Pass rate for 0-100 threshold vs int Range(0,100) with pass when field > roll (master gate). */
export function waveUpdateThresholdGtPassRate(threshold: number): number {
  return waveUpdateTickCapGatePassRate(threshold)
}

/** Pass rate when field >= roll (double-spawn path). F=5 -> 0.06; F=24 -> 0.25. */
export function waveUpdateThresholdGtePassRate(threshold: number): number {
  const t = Math.max(0, Number(threshold) || 0)
  const max = WAVE_UPDATE_GATE2_RANDOM_EXCLUSIVE_MAX_V29
  if (t < 0) return 0
  if (t >= max - 1) return 1
  return Math.min(1, (Math.floor(t) + 1) / max)
}

/** Gate 2: spawn when Random.Range(0, 100) <= 79. */
export function waveUpdateFixedIntGatePassRate(
  threshold: number = WAVE_UPDATE_GATE2_INT_THRESHOLD_V29,
  randomExclusiveMax: number = WAVE_UPDATE_GATE2_RANDOM_EXCLUSIVE_MAX_V29,
): number {
  const t = Math.max(0, Math.floor(Number(threshold) || 0))
  const max = Math.max(1, Math.floor(Number(randomExclusiveMax) || 100))
  return Math.min(1, (t + 1) / max)
}

/**
 * Gate 3: spawn when Random.value < (1 - GetResistanceLevel(7,-1)).
 * Pass moreEnemiesResistance from getResistanceLevel({ heatLevel, ... }); default 1 -> pass 0.
 */
export function waveUpdateFloatComplementGatePassRate(
  moreEnemiesResistance: number = 1,
): number {
  const r = Number(moreEnemiesResistance)
  if (!Number.isFinite(r)) return WAVE_UPDATE_GATE3_COMPLEMENT_PASS_RATE_V29
  return clamp(1 - r, 0, 1)
}

/**
 * @deprecated Additive probe (gate1+gate2+gate3+double as independent site EVs).
 * Prefer {@link expectedEnemiesPerSpawnQuantumFromDisasmV29} — master gate multiplies the
 * whole cluster and ticks are waveLength/0.125, not WA chart as tick count.
 */
export function expectedEnemiesPerSpawnTickFromDisasmGatesV29(input: {
  spawnTickCap: number
  enemyDoubleSpawnChance?: number | null
  /** GetResistanceLevel(7,-1) result; omit/1 = no More Enemies -> gate3 pass 0. */
  moreEnemiesResistance?: number | null
}): number {
  const gate1 = waveUpdateTickCapGatePassRate(input.spawnTickCap)
  const gate2 = waveUpdateFixedIntGatePassRate()
  const gate3 = waveUpdateFloatComplementGatePassRate(
    input.moreEnemiesResistance == null ? 1 : Number(input.moreEnemiesResistance),
  )
  const doubleChance = clamp(Number(input.enemyDoubleSpawnChance ?? 0), 0, 1)
  return gate1 + gate2 + gate3 + doubleChance
}

/**
 * NewWave enemyDoubleSpawnChance (+0x1AC) before WaveUpdate roll.
 * themeBucketBase defaults to 5; final = base + tier/2.85 (0-100 scale).
 */
export function newWaveEnemyDoubleSpawnThresholdV29(input: {
  tier: number
  themeBucketBase?: number | null
}): number {
  const base =
    input.themeBucketBase == null
      ? WAVE_SPAWN_DOUBLE_CHANCE_BASE_THRESHOLD_V29
      : Number(input.themeBucketBase)
  const tier = Math.max(1, Math.floor(Number(input.tier) || 1))
  const bonus = tier / WAVE_SPAWN_DOUBLE_CHANCE_TIER_DIVISOR_V29
  return Math.max(0, base + bonus)
}

/**
 * Expected ordinary enemies per waveSpawnTimer quantum (one cluster attempt).
 * Master gate multiplies the whole cluster (3 sites + double).
 */
export function expectedEnemiesPerSpawnQuantumFromDisasmV29(input: {
  /** +0x1A8 threshold 0-100 (WA chart spawnCount). */
  enemySpawnChanceThreshold: number
  /** +0x1AC threshold 0-100; default NewWave base 5. */
  enemyDoubleSpawnThreshold?: number | null
  moreEnemiesResistance?: number | null
}): number {
  const master = waveUpdateThresholdGtPassRate(input.enemySpawnChanceThreshold)
  const gate2 = waveUpdateFixedIntGatePassRate()
  const gate3 = waveUpdateFloatComplementGatePassRate(
    input.moreEnemiesResistance == null ? 1 : Number(input.moreEnemiesResistance),
  )
  const doubleThreshold =
    input.enemyDoubleSpawnThreshold == null
      ? WAVE_SPAWN_DOUBLE_CHANCE_BASE_THRESHOLD_V29
      : Number(input.enemyDoubleSpawnThreshold)
  const doublePass = waveUpdateThresholdGtePassRate(doubleThreshold)
  // site1 contributes 1.0 after master
  return master * (1 + gate2 + gate3 + doublePass)
}

export function expectedSpawnQuantaPerWaveV29(waveLengthSeconds: number): number {
  const length = Math.max(0, Number(waveLengthSeconds) || 0)
  if (length <= 0) return 0
  return length / WAVE_SPAWN_TIMER_QUANTUM_SECONDS_V29
}

export function expectedEnemiesPerWaveFromDisasmQuantumV29(input: {
  waveLengthSeconds: number
  enemySpawnChanceThreshold: number
  enemyDoubleSpawnThreshold?: number | null
  moreEnemiesResistance?: number | null
  enemyBalanceMult?: number | null
}): number {
  const ticks = expectedSpawnQuantaPerWaveV29(input.waveLengthSeconds)
  const perTick = expectedEnemiesPerSpawnQuantumFromDisasmV29(input)
  const eb = Math.max(0, Number(input.enemyBalanceMult ?? 1) || 0)
  return ticks * perTick * eb
}
