/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    WAVE_UPDATE_SPAWN_BASIC_BL_SITES_V29, WAVE_UPDATE_SPAWN_BASIC_GATE_KINDS_V29, WaveUpdateSpawnBasicGateKindV29, WAVE_UPDATE_SPAWN_BASIC_TICK_CAP_GATE_SITE_V29, WAVE_UPDATE_GATE2_INT_THRESHOLD_V29, WAVE_UPDATE_GATE2_RANDOM_EXCLUSIVE_MAX_V29, WAVE_UPDATE_GATE2_PASS_RATE_V29, WAVE_UPDATE_MORE_ENEMIES_CONDITION_INDEX_V29 (+4 more)
 * depends    —
 * used by    src/mechanics/waves/index, src/mechanics/waves/update-spawn-gate-pass
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
/**
 * WaveUpdate spawn gate constants observed in game v29.0.0.
 */
export const WAVE_UPDATE_SPAWN_BASIC_BL_SITES_V29 = [
  0x01_fccaec,
  0x01_fccb3c,
  0x01_fccbd4,
] as const

/** Per-site gate kind from scoped preamble scan — not a uniform tick-cap compare. */
export const WAVE_UPDATE_SPAWN_BASIC_GATE_KINDS_V29 = [
  'enemySpawnChance_vs_random0_100',
  'random0_100_le_0x4f',
  'random_float_lt_complement',
] as const

export type WaveUpdateSpawnBasicGateKindV29 = (typeof WAVE_UPDATE_SPAWN_BASIC_GATE_KINDS_V29)[number]

/** Only the first SpawnRandomBasicEnemy gate loads Main.enemySpawnChance. */
export const WAVE_UPDATE_SPAWN_BASIC_TICK_CAP_GATE_SITE_V29 = 0x01_fccaec as const

/** Gate 2: `cmp w0, #0x4f` then `b.gt` skip — pass when random int <= 79 (Unity Range 0, 100). */
export const WAVE_UPDATE_GATE2_INT_THRESHOLD_V29 = 0x4f as const
export const WAVE_UPDATE_GATE2_RANDOM_EXCLUSIVE_MAX_V29 = 100 as const
export const WAVE_UPDATE_GATE2_PASS_RATE_V29 =
  (WAVE_UPDATE_GATE2_INT_THRESHOLD_V29 + 1) / WAVE_UPDATE_GATE2_RANDOM_EXCLUSIVE_MAX_V29

/** Gate 3: More Enemies BC index into GetResistanceLevel(conditionIndex, -1). */
export const WAVE_UPDATE_MORE_ENEMIES_CONDITION_INDEX_V29 = 7 as const

/**
 * Gate 3 default pass rate when More Enemies heat is inactive.
 * Observed: Random.value < (1 - GetResistanceLevel(7,-1)); heat 0 → resistance ≈ 1 → pass 0.
 */
export const WAVE_UPDATE_GATE3_COMPLEMENT_PASS_RATE_V29 = 0 as const

/** waveSpawnTimer quantum - subtract 0.125 per spawn-cluster attempt. */
export const WAVE_SPAWN_TIMER_QUANTUM_SECONDS_V29 = 0.125 as const

/** Theme-bucket base for the [600,799]-style band that stores 5.0; other themes differ. */
export const WAVE_SPAWN_DOUBLE_CHANCE_BASE_THRESHOLD_V29 = 5 as const

/** NewWave adds currentTier / this divisor onto the double-spawn chance field. */
export const WAVE_SPAWN_DOUBLE_CHANCE_TIER_DIVISOR_V29 = 2.85 as const

