/**
 * Save indices to named entities.
 *
 * A save file stores most things positionally — bot 3, relic 112, vault node 47.
 * These maps turn those indices into the named entries in `thetowersdk/data`.
 */
/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    —
 * depends    src/save/catalogs/bots, src/save/catalogs/guardians, src/save/catalogs/indexes, src/save/catalogs/perks, src/save/catalogs/relic-template-match, src/save/catalogs/relics (+6 more)
 * used by    —
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
export * from './indexes'
export * from './bots'
export * from './guardians'
export * from './perks'
export * from './relics'
export * from './relic-template-match'
export * from './themes'
export * from './ultimate-weapons'
export * from './vault'
export * from './vault-overrides'
export * from './vault-power'
export * from './workshop'
