/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    UltimateWeaponCatalogRow, findUltimateWeaponCatalogRow, findUltimateWeaponCatalogName, listUltimateWeaponCatalogRows, UW_CATALOG_SLOT_COUNT
 * depends    src/save/catalogs/indexes
 * used by    src/mechanics/calculators/specs-generated, src/save/catalogs/index, src/save/ids/import-blocks, src/save/ids/import-collections, src/save/ids/import-domains, src/save/ids/import-progression (+3 more)
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
import { ULTIMATE_WEAPON_IMPORT_CATALOG } from './indexes'

export type UltimateWeaponCatalogRow = (typeof ULTIMATE_WEAPON_IMPORT_CATALOG)[number]

/** By save index, not array position. See findBotCatalogRow for why. */
export function findUltimateWeaponCatalogRow(index: number): UltimateWeaponCatalogRow | null {
  return ULTIMATE_WEAPON_IMPORT_CATALOG.find(row => row.index === index) ?? null
}

export function findUltimateWeaponCatalogName(index: number): string | null {
  return findUltimateWeaponCatalogRow(index)?.name ?? null
}

export function listUltimateWeaponCatalogRows(): readonly UltimateWeaponCatalogRow[] {
  return ULTIMATE_WEAPON_IMPORT_CATALOG
}

export const UW_CATALOG_SLOT_COUNT = ULTIMATE_WEAPON_IMPORT_CATALOG.length
