/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    HARMONY_VAULT_SLOT_OVERRIDES, POWER_VAULT_SLOT_OVERRIDES, POWER_VAULT_SINGLE_PURCHASE_NODE_IDS
 * depends    —
 * used by    src/save/catalogs/index, src/save/catalogs/vault, src/save/catalogs/vault-power, src/save/shared-tool-inputs-from-save-extended, src/save/vault
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
/**
 * Corrections where vault tree traversal order diverges from import serialization.
 * Prefer parent-child traversal in vault-tree-traversal.ts; only add overrides when
 * structure alone is insufficient (e.g. harmony end-cap swaps confirmed in saves).
 */
export const HARMONY_VAULT_SLOT_OVERRIDES: Readonly<Record<string, number>> = {
  botpreset: 47,
  botslider: 45,
} as const

/** Power tree save slots are derived from BFS parent-child traversal — no per-label overrides. */
export const POWER_VAULT_SLOT_OVERRIDES: Readonly<Record<string, number>> = {} as const

/** Single-key purchases (not 1–3 star upgrades). Detected by cost shape and tree role. */
export const POWER_VAULT_SINGLE_PURCHASE_NODE_IDS: ReadonlySet<string> = new Set([
  'ultdmg1',
  'ultdmg2',
  'ultdmg3',
  'ultdmg4',
  'botrange1',
  'botrange2',
  'botrange3',
  'botrange4',
  'tier2',
  'tier3',
  'shockwave',
  'orbs',
  'wallrebuild',
])
