/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    VaultPowerImportSlice, VaultPowerMappingScore, VaultPowerMappingStrategyId, scoreVaultPowerSaveMapping, scoreVaultPowerMappingStrategy, compareVaultPowerMappingStrategies, VAULT_POWER_DEV_SAVE_ANCHOR_LEVELS, scoreVaultPowerAnchorLevelMismatches (+1 more)
 * depends    src/data/vault/tree, src/data/vault/tree-traversal, src/save/catalogs/vault, src/save/catalogs/vault-overrides
 * used by    src/mechanics/calculators/specs-generated, src/save/catalogs/index
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
import { powerTreeNodes, type VaultTreeNode } from '../../data/vault/tree'
import { POWER_VAULT_SINGLE_PURCHASE_NODE_IDS } from './vault-overrides'
import { buildVaultChartSlotIndexById } from './vault'
import {
  buildVaultPowerLevelSlotIndexById,
  buildVaultTreeBfsSlotIndexById,
  POWER_VAULT_TIER_UNLOCK_NODE_IDS,
} from '../../data/vault/tree-traversal'

export interface VaultPowerImportSlice {
  levels: readonly number[]
  unlocked: readonly boolean[]
  tier2Unlock: boolean
  tier3Unlock: boolean
}

export interface VaultPowerMappingScore {
  parentViolations: number
  singlePurchaseHighRaw: number
  tierSlotHighRaw: number
  leveledNodeCount: number
  total: number
}

export type VaultPowerMappingStrategyId =
  | 'chart-layout'
  | 'bfs-direct'
  | 'hybrid-bfs-tier2-skip'

const STRATEGY_BUILDERS: Record<
  VaultPowerMappingStrategyId,
  (nodes: readonly VaultTreeNode[]) => Record<string, number>
> = {
  'chart-layout': buildVaultChartSlotIndexById,
  'bfs-direct': buildVaultTreeBfsSlotIndexById,
  'hybrid-bfs-tier2-skip': buildVaultPowerLevelSlotIndexById,
}

function displayLevel(raw: number, unlocked: boolean, singlePurchase: boolean): number {
  if (singlePurchase) return raw > 0 || unlocked ? 1 : 0
  if (raw <= 0) return unlocked ? 1 : 0
  return Math.min(3, raw + 1)
}

function nodeProgress(
  nodeId: string,
  indexById: Record<string, number>,
  slice: VaultPowerImportSlice,
): boolean {
  if (nodeId === 'tier2') return slice.tier2Unlock
  if (nodeId === 'tier3') return slice.tier3Unlock
  const saveIndex = indexById[nodeId]
  if (saveIndex == null) return false
  const raw = slice.levels[saveIndex] ?? 0
  const unlocked = slice.unlocked[saveIndex] ?? false
  const single = POWER_VAULT_SINGLE_PURCHASE_NODE_IDS.has(nodeId)
  return displayLevel(raw, unlocked, single) > 0
}

export function scoreVaultPowerSaveMapping(
  indexById: Record<string, number>,
  slice: VaultPowerImportSlice,
): VaultPowerMappingScore {
  let parentViolations = 0
  let singlePurchaseHighRaw = 0
  let tierSlotHighRaw = 0
  let leveledNodeCount = 0

  for (const node of powerTreeNodes) {
    const saveIndex = indexById[node.id]
    if (saveIndex == null) continue
    const raw = slice.levels[saveIndex] ?? 0
    const unlocked = slice.unlocked[saveIndex] ?? false
    const single = POWER_VAULT_SINGLE_PURCHASE_NODE_IDS.has(node.id)
    const level = displayLevel(raw, unlocked, single)
    if (level > 0) leveledNodeCount++

    if (POWER_VAULT_TIER_UNLOCK_NODE_IDS.has(node.id) && raw >= 2) tierSlotHighRaw++
    if (single && !POWER_VAULT_TIER_UNLOCK_NODE_IDS.has(node.id) && raw >= 2) {
      singlePurchaseHighRaw++
    }

    if (level <= 0) continue
    for (const parentId of node.parents) {
      if (!nodeProgress(parentId, indexById, slice)) parentViolations++
    }
  }

  return {
    parentViolations,
    singlePurchaseHighRaw,
    tierSlotHighRaw,
    leveledNodeCount,
    total: parentViolations * 10 + singlePurchaseHighRaw * 5 + tierSlotHighRaw * 5,
  }
}

export function scoreVaultPowerMappingStrategy(
  strategy: VaultPowerMappingStrategyId,
  slice: VaultPowerImportSlice,
): VaultPowerMappingScore {
  return scoreVaultPowerSaveMapping(STRATEGY_BUILDERS[strategy](powerTreeNodes), slice)
}

export function compareVaultPowerMappingStrategies(slice: VaultPowerImportSlice): Array<{
  strategy: VaultPowerMappingStrategyId
  score: VaultPowerMappingScore
}> {
  return (Object.keys(STRATEGY_BUILDERS) as VaultPowerMappingStrategyId[])
    .map(strategy => ({
      strategy,
      score: scoreVaultPowerMappingStrategy(strategy, slice),
    }))
    .sort((left, right) => left.score.total - right.score.total)
}

export const VAULT_POWER_DEV_SAVE_ANCHOR_LEVELS: Readonly<Record<string, number>> = {
  cash: 3,
  dmgmeter: 3,
  botrange2: 1,
  knockback: 1,
  orbspeed: 3,
  freeatk: 2,
  freedef: 2,
  freeutil: 2,
  deathdefy: 2,
  multichance: 3,
  bouncchance: 3,
}

export function scoreVaultPowerAnchorLevelMismatches(
  indexById: Record<string, number>,
  slice: VaultPowerImportSlice,
): number {
  let mismatches = 0
  for (const [nodeId, expectedLevel] of Object.entries(VAULT_POWER_DEV_SAVE_ANCHOR_LEVELS)) {
    const saveIndex = indexById[nodeId]
    if (saveIndex == null) {
      mismatches++
      continue
    }
    const raw = slice.levels[saveIndex] ?? 0
    const unlocked = slice.unlocked[saveIndex] ?? false
    const single = POWER_VAULT_SINGLE_PURCHASE_NODE_IDS.has(nodeId)
    const level = displayLevel(raw, unlocked, single)
    if (level !== expectedLevel) mismatches++
  }
  return mismatches
}

export function assertVaultPowerChainProgression(
  nodeIds: readonly string[],
  indexById: Record<string, number>,
  slice: VaultPowerImportSlice,
): boolean {
  let priorLevel = 0
  for (const nodeId of nodeIds) {
    const saveIndex = indexById[nodeId]
    if (saveIndex == null) return false
    const raw = slice.levels[saveIndex] ?? 0
    const unlocked = slice.unlocked[saveIndex] ?? false
    const level = displayLevel(raw, unlocked, POWER_VAULT_SINGLE_PURCHASE_NODE_IDS.has(nodeId))
    if (level > 0 && priorLevel <= 0) return false
    if (level > 0) priorLevel = level
  }
  return true
}
