/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    searchPatchNotes, whenIntroduced, patchNotesForVersion, patchNotesBetween, recentPatchNotes, patchNoteVersions
 * depends    src/knowledge/generated/patch-notes.generated
 * used by    src/knowledge/index, src/mechanics/calculators/specs-generated
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
import { PATCH_NOTES, type PatchNote } from './generated/patch-notes.generated'

export * from './generated/patch-notes.generated'

/**
 * Querying the developers' own patch notes.
 *
 * Five years of announcements, oldest first. This answers the question the catalogs cannot:
 * *when* did a thing arrive, and what did the developers say about it at the time. The SDK's
 * data says what a number is today; this says when it became that.
 *
 * Every result carries the note's Discord message id, so a claim is traceable back to the post
 * rather than to this package.
 */

/** Fold text for comparison: case, punctuation and spacing all vary in prose. */
function fold(value: string): string {
  return value.toLowerCase().replace(/[^a-z0-9]+/g, ' ').trim()
}

/**
 * Notes that mention a term, newest first.
 *
 * Matches the body as written, so searching `golden tower` finds it however it was capitalised.
 * This is a text search over announcements, not a claim that the mechanic changed — a note that
 * merely mentions something is a lead, and `whenIntroduced` is the narrower question.
 */
export function searchPatchNotes(term: string, limit = 20): readonly PatchNote[] {
  const needle = fold(term)
  if (!needle) return []
  return PATCH_NOTES
    .filter(note => fold(`${note.title} ${note.body}`).includes(needle))
    .sort((a, b) => b.postedAt.localeCompare(a.postedAt))
    .slice(0, limit)
}

/**
 * The FIRST note that mentions a term — the earliest public word on it.
 *
 * `null` when nothing mentions it, which is a real answer: the archive starts in July 2021 and
 * anything older than that was never posted here. It is not evidence the thing does not exist.
 */
export function whenIntroduced(term: string): PatchNote | null {
  const needle = fold(term)
  if (!needle) return null
  return PATCH_NOTES.find(note => fold(`${note.title} ${note.body}`).includes(needle)) ?? null
}

/** Every note naming a version, oldest first. Versions are as written by the developers. */
export function patchNotesForVersion(version: string): readonly PatchNote[] {
  const wanted = version.replace(/^v/i, '')
  return PATCH_NOTES.filter(note => note.version === wanted)
}

/**
 * Notes posted in a date range, inclusive, oldest first.
 *
 * Dates are ISO (`2024-10-17`) or anything `Date` accepts. Compared as timestamps rather than
 * strings so a partial date does not silently exclude the day it names.
 */
export function patchNotesBetween(from: string, to: string): readonly PatchNote[] {
  const start = new Date(from).getTime()
  const end = new Date(to).getTime()
  if (Number.isNaN(start) || Number.isNaN(end)) return []
  return PATCH_NOTES.filter((note) => {
    const at = new Date(note.postedAt).getTime()
    return at >= start && at <= end
  })
}

/** The most recent notes, newest first — what changed lately. */
export function recentPatchNotes(count = 5): readonly PatchNote[] {
  return [...PATCH_NOTES].reverse().slice(0, count)
}

/** Every version the notes name, oldest first, de-duplicated. */
export function patchNoteVersions(): readonly string[] {
  const seen = new Set<string>()
  const versions: string[] = []
  for (const note of PATCH_NOTES) {
    if (note.version && !seen.has(note.version)) {
      seen.add(note.version)
      versions.push(note.version)
    }
  }
  return versions
}
