/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    MAX_ASSIST_MODULE_SLOT_EFFICIENCY_PCT, MAX_ASSIST_MULTIPLIER_EFFICIENCY_PCT, clampAssistModuleSlotEfficiencyPct, clampAssistMultiplierEfficiencyPct, computeAssistMultiplierEfficiencyPct, assistMultiplierEfficiencyFactor
 * depends    —
 * used by    src/internal/calculator-local-state-schemas, src/internal/game-input-data/uptime-relic-dropdown-math, src/internal/game-input-data/uptime-substat-dropdown-math, src/internal/shard-splitter-schema, src/mechanics/calculators/specs-generated, src/mechanics/els-calculator-options (+5 more)
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
/**
 * Assist module multiplier efficiency bounds (v28.3+).
 *
 * In-game "Multiplier Efficiency" = module slot % + Assist Module Bonus lab levels,
 * capped at {@link MAX_ASSIST_MULTIPLIER_EFFICIENCY_PCT} (was 100% pre-v28.3).
 */
export const MAX_ASSIST_MODULE_SLOT_EFFICIENCY_PCT = 100 as const

/** Combined cap for slot efficiency + Assist Module Bonus lab levels. */
export const MAX_ASSIST_MULTIPLIER_EFFICIENCY_PCT = 130 as const

/** Clamp assist efficiency configured on the module slot (labs excluded). */
export function clampAssistModuleSlotEfficiencyPct(value: unknown): number {
  const numeric = Math.floor(Number(value) || 0)
  return Math.max(0, Math.min(MAX_ASSIST_MODULE_SLOT_EFFICIENCY_PCT, numeric))
}

/** Clamp total multiplier efficiency % (slot + labs, or user-entered effective %). */
export function clampAssistMultiplierEfficiencyPct(value: unknown): number {
  const numeric = Math.floor(Number(value) || 0)
  return Math.max(0, Math.min(MAX_ASSIST_MULTIPLIER_EFFICIENCY_PCT, numeric))
}

export function computeAssistMultiplierEfficiencyPct(
  assistSlotEfficiencyPct: unknown,
  assistLabLevel = 0,
): number {
  const combined = Math.floor(Number(assistSlotEfficiencyPct) || 0) + Math.floor(Number(assistLabLevel) || 0)
  return clampAssistMultiplierEfficiencyPct(combined)
}

/** Multiplier applied to assist module bonus (0–1.3). */
export function assistMultiplierEfficiencyFactor(
  assistSlotEfficiencyPct: unknown,
  assistLabLevel = 0,
): number {
  return computeAssistMultiplierEfficiencyPct(assistSlotEfficiencyPct, assistLabLevel) / 100
}
