/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    BOT_BENEFIT_COOLDOWN_LAB_INDICES, BOT_BENEFIT_DURATION_LAB_INDICES, BOT_BENEFIT_RELIC_RANGE_STAT, BOT_BENEFIT_RELIC_RANGE_BOT_MASK, BOT_BENEFIT_TECH_TREE_RANGE_STAT, BotCooldownLabInput, BotGetBenefitInput, botBenefitFromCooldownLab (+1 more)
 * depends    —
 * used by    src/mechanics/calculators/specs-generated, src/mechanics/index
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
/**
 * Bot stat benefit from base values, level scaling, and lab/relic/tech-tree bonuses.
 */

export const BOT_BENEFIT_COOLDOWN_LAB_INDICES = {
  flame: 8,
  thunder: 9,
  golden: 10,
  amplify: 11,
} as const

export const BOT_BENEFIT_DURATION_LAB_INDICES = {
  golden: 14,
  amplify: 15,
} as const

export const BOT_BENEFIT_RELIC_RANGE_STAT = 30
export const BOT_BENEFIT_RELIC_RANGE_BOT_MASK = 170

export const BOT_BENEFIT_TECH_TREE_RANGE_STAT = 13

export interface BotCooldownLabInput {
  researchBase: number
  researchPerLevel: number
  selectedLevel: number
}

export interface BotGetBenefitInput {
  baseBenefit: number
  benefitPerLevel: number
  level: number
  statIndex: number
  cooldownLab?: BotCooldownLabInput
  durationLabFlatBonus?: number
  relicRangeBonus?: number
  techTreeRangeBonus?: number
}

export function botBenefitFromCooldownLab(lab: BotCooldownLabInput): number {
  return lab.researchBase + lab.researchPerLevel * Math.max(0, lab.selectedLevel)
}

export function computeBotGetBenefit(input: BotGetBenefitInput): number {
  let benefit = input.baseBenefit + input.benefitPerLevel * Math.max(0, input.level)

  const cooldownIndices = Object.values(BOT_BENEFIT_COOLDOWN_LAB_INDICES) as number[]
  if (input.cooldownLab && cooldownIndices.includes(input.statIndex)) {
    benefit -= botBenefitFromCooldownLab(input.cooldownLab)
  }

  const durationIndices = Object.values(BOT_BENEFIT_DURATION_LAB_INDICES) as number[]
  if (input.durationLabFlatBonus != null && durationIndices.includes(input.statIndex)) {
    benefit += input.durationLabFlatBonus
  }

  if (input.relicRangeBonus != null && input.statIndex < 8 && (BOT_BENEFIT_RELIC_RANGE_BOT_MASK & (1 << input.statIndex)) !== 0) {
    benefit += input.relicRangeBonus * 10
  }

  if (input.techTreeRangeBonus != null && input.statIndex < 8 && (BOT_BENEFIT_RELIC_RANGE_BOT_MASK & (1 << input.statIndex)) !== 0) {
    benefit += input.techTreeRangeBonus
  }

  return benefit
}
