/**
 * Damage reduction from relative/absolute defense and multiplicative mitigation layers.
 */
/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    DamageReductionStatDelta, DamageReductionStatAccumulator, applyDamageReductionStats, DamageReductionInput, DEFENSE_PERCENT_MAX, applyRelativeDefense, effectiveRelativeDefenseReductionPct, applyAbsoluteDefense (+1 more)
 * depends    src/mechanics/bots, src/mechanics/math
 * used by    src/mechanics/calculators/specs-generated, src/mechanics/damage-redux-calculator, src/mechanics/index
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */

import { flameBotDamageReductionMultiplier } from './bots'
import { clamp } from './math'

export interface DamageReductionStatDelta {
  lane0: number
  lane1: number
  lane2: number
  lane3: number
  lane4: number
  lane5: number
  lane6: number
}

export interface DamageReductionStatAccumulator {
  accum0: number
  accum1: number
  accum2: number
  accum3: number
  accum4: number
  accum5: number
  accum6: number
}

export function applyDamageReductionStats(
  acc: DamageReductionStatAccumulator,
  delta: DamageReductionStatDelta,
): DamageReductionStatAccumulator {
  return {
    accum0: acc.accum0 + delta.lane5,
    accum1: acc.accum1 + delta.lane6,
    accum2: acc.accum2 + delta.lane1,
    accum3: acc.accum3 + delta.lane0,
    accum4: acc.accum4 + delta.lane2,
    accum5: acc.accum5 + delta.lane4,
    accum6: acc.accum6 + delta.lane3,
  }
}

export interface DamageReductionInput {
  rawDamage: number
  defenseRel?: number
  defenseAbsolute?: number
  chronoDamageReductionMult?: number
  flameBotLevel?: number
  flameBotActive?: boolean
  flameBotDamageMult?: number
  moduleDefenseMult?: number
  rendArmorMultiplier?: number
}

/** In-game defense % hard cap (workshop + lab + cards + modules). */
export const DEFENSE_PERCENT_MAX = 98

/** Player-facing defense: `damage × (1 − defense% / 100)`, capped at 98%. */
export function applyRelativeDefense(damage: number, defenseRel: number): number {
  if (defenseRel <= 0) return damage
  const pct = clamp(defenseRel, 0, DEFENSE_PERCENT_MAX)
  return damage * (1 - pct / 100)
}

/** Display / breakdown reduction % — matches the defense stat (capped). */
export function effectiveRelativeDefenseReductionPct(defenseRel: number): number {
  if (defenseRel <= 0) return 0
  return clamp(defenseRel, 0, DEFENSE_PERCENT_MAX)
}

export function applyAbsoluteDefense(damage: number, defenseAbsolute: number): number {
  return Math.max(0, damage - defenseAbsolute)
}

export function computeDamageReductionResult(input: DamageReductionInput): number {
  let dmg = input.rawDamage

  if (input.defenseRel != null) {
    dmg = applyRelativeDefense(dmg, input.defenseRel)
  }

  if (input.defenseAbsolute != null) {
    dmg = applyAbsoluteDefense(dmg, input.defenseAbsolute)
  }

  if (input.chronoDamageReductionMult != null) {
    dmg *= input.chronoDamageReductionMult
  }

  if (input.flameBotDamageMult != null) {
    dmg *= input.flameBotDamageMult
  } else if (input.flameBotActive && input.flameBotLevel != null) {
    dmg *= flameBotDamageReductionMultiplier(input.flameBotLevel)
  }

  if (input.moduleDefenseMult != null) {
    dmg *= input.moduleDefenseMult
  }

  if (input.rendArmorMultiplier != null) {
    dmg *= input.rendArmorMultiplier
  }

  return clamp(dmg, 0, Number.MAX_VALUE)
}
