/**
 * Effective Paths — workshop stat values, in the units the paths expect.
 *
 * The eHP model takes resolved workshop values, and this is where they come
 * from. `WORKSHOP_DATA` already carries all 48 stats at every level, verified
 * against the sheet's own `DVT_Workshop` tab, so nothing is recomputed here —
 * this is a units and naming layer, not a second copy of the curve.
 *
 * ## Two things had to be established rather than assumed
 *
 * **Units.** This package stores percentages as numbers out of 100 and the
 * sheet stores them as fractions, so Wall Health at level 0 is `20` here and
 * `0.2` there. A handful of stats differ by a factor of ten instead. Feeding
 * an unconverted value into the model would be off by 100x with nothing to
 * catch it, so the scale for every stat was derived by probing the sheet at
 * four levels, not by reading the names and guessing which look like percents.
 *
 * **Names.** Six stats are spelled differently in the two — `Defense Percent`
 * against `Defense %`, `Thorns` against `Thorn Damage`, and so on.
 *
 * ## Seven stats this will not convert
 *
 * Seven have no consistent scale against `DVT_WS_VALUE`, because that
 * function's fallback formulas for them are stale — the game's own getters give
 * different curves.
 *
 * That is a smaller problem than it sounds, and worth stating so nobody
 * repeats the mistake this comment used to make: **no path calls those
 * branches.** `DVT_WS_VALUE` has six call sites in the entire workbook, all on
 * the eHP tab and all for defensive stats that agree. The damage and economy
 * paths take the workshop level and apply the curve inline, and match the game
 * where they do.
 *
 * These stay unconvertible here because this module answers in the *sheet's*
 * units for a port that reproduces the sheet, and there is no scale that maps a
 * stale formula onto a live one. Read the level and apply the game's curve
 * instead, as the sheet's own paths do. See
 * `docs/EFFECTIVE_PATHS_SHEET_FINDINGS.md`.
 */
/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    WorkshopStatMapping, WORKSHOP_STAT_MAPPINGS, WORKSHOP_STATS_DIVERGING_FROM_SHEET, WORKSHOP_STATS_ABSENT_FROM_SHEET, WorkshopStatLookup, workshopStatValue, workshopStatMaxLevel, workshopStatsWithSheetMapping (+1 more)
 * depends    src/data/workshop-table
 * used by    src/mechanics/calculators/specs-generated, src/mechanics/effective-paths-ehp-model, src/mechanics/index
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */

import { WORKSHOP_DATA } from '../data/workshop-table'

/** How a stat is named in the sheet, and what its value must be multiplied by. */
export interface WorkshopStatMapping {
  /** The sheet's spelling, for `DVT_WS_VALUE`. */
  sheetName: string
  /** `sdkValue / sheetValue`. Divide by this to get the sheet's units. */
  scale: number
}

/**
 * Stat name in `WORKSHOP_DATA` to its sheet mapping.
 *
 * Derived by probing the live sheet at levels 1, 3, 11 and 37 and requiring the
 * same ratio at all four; see `effective-paths-workshop-values.fixtures.json`.
 */
export const WORKSHOP_STAT_MAPPINGS: Readonly<Record<string, WorkshopStatMapping>> = {
  'Attack Speed': { sheetName: 'Attack Speed', scale: 1 },
  'Bounce Shot Chance': { sheetName: 'Bounce Shot Chance', scale: 100 },
  'Bounce Shot Targets': { sheetName: 'Bounce Shot Targets', scale: 1 },
  'Cash / Wave': { sheetName: 'Cash / Wave', scale: 1 },
  'Coins / Wave': { sheetName: 'Coin / Wave', scale: 1 },
  'Critical Chance': { sheetName: 'Critical Chance', scale: 100 },
  'Critical Factor': { sheetName: 'Critical Factor', scale: 1 },
  'Damage': { sheetName: 'Damage', scale: 1 },
  'Damage / Meter': { sheetName: 'Damage / Meter', scale: 1 },
  'Death Defy': { sheetName: 'Death Defy', scale: 100 },
  'Defense Absolute': { sheetName: 'Defense Absolute', scale: 1 },
  'Defense Percent': { sheetName: 'Defense %', scale: 100 },
  'Enemy Attack Level Skip': { sheetName: 'Enemy Attack Level Skip', scale: 0.1 },
  'Enemy Health Level Skip': { sheetName: 'Enemy Health Level Skip', scale: 0.1 },
  'Free Attack Upgrade': { sheetName: 'Free Attack Upgrade', scale: 100 },
  'Free Defense Upgrade': { sheetName: 'Free Defense Upgrade', scale: 100 },
  'Free Utility Upgrade': { sheetName: 'Free Utility Upgrade', scale: 100 },
  'Health': { sheetName: 'Health', scale: 1 },
  'Health Regen': { sheetName: 'Health Regen', scale: 1 },
  'Interest / Wave': { sheetName: 'Interest / Wave', scale: 100 },
  'Knockback Chance': { sheetName: 'Knockback Chance', scale: 100 },
  'Land Mine Damage': { sheetName: 'Land Mine Damage', scale: 1 },
  'Land Mine Radius': { sheetName: 'Land Mine Radius', scale: 1 },
  'Lifesteal': { sheetName: 'Lifesteal', scale: 1 },
  'Max Recovery': { sheetName: 'Max Recovery', scale: 1 },
  'Multishot Chance': { sheetName: 'Multishot Chance', scale: 100 },
  'Multishot Targets': { sheetName: 'Multishot Targets', scale: 1 },
  'Orb Speed': { sheetName: 'Orb Speed', scale: 0.1 },
  'Orbs': { sheetName: 'Orbs', scale: 1 },
  'Package Chance': { sheetName: 'Package Chance', scale: 1 },
  'Range': { sheetName: 'Range', scale: 0.1 },
  'Rapid Fire Chance': { sheetName: 'Rapid Fire Chance', scale: 100 },
  'Rapid Fire Duration': { sheetName: 'Rapid Fire Duration', scale: 1 },
  'Recovery Amount': { sheetName: 'Recovery Amount', scale: 100 },
  'Rend Armor Mult': { sheetName: 'Rend Armor Mult', scale: 1 },
  'Shockwave Size': { sheetName: 'Shockwave Size', scale: 1 },
  'Super Crit Chance': { sheetName: 'Super Critical Chance', scale: 100 },
  'Super Crit Mult': { sheetName: 'Super Critical Mult', scale: 1 },
  'Thorns': { sheetName: 'Thorn Damage', scale: 100 },
  'Wall Health': { sheetName: 'Wall Health', scale: 100 },
}

/**
 * Stats where the sheet's formula and the game's data are different functions,
 * not different units. Converting one to the other is not possible, so
 * {@link workshopStatValue} refuses rather than guessing.
 */
export const WORKSHOP_STATS_DIVERGING_FROM_SHEET: readonly string[] = [
  'Cash Bonus',
  'Coins / Kill Bonus',
  'Knockback Force',
  'Land Mine Chance',
  'Rend Armor Chance',
  'Shockwave Frequency',
  'Wall Rebuild',
]

/** The sheet returns blank for this one — it has no formula and no table column. */
export const WORKSHOP_STATS_ABSENT_FROM_SHEET: readonly string[] = ['Bounce Shot Range']

const DIVERGING = new Set(WORKSHOP_STATS_DIVERGING_FROM_SHEET)

export interface WorkshopStatLookup {
  /** The stat's value in the sheet's units. */
  value: number
  /** Coins to take the stat from `level - 1` to `level`. */
  coinCost: number
  /** Cash to do the same. */
  cashCost: number
}

/**
 * Look up a workshop stat at a level, in the units the Effective Paths model
 * expects.
 *
 * Returns `null` for an unknown stat, a level the table does not cover, or one
 * of the stats where the sheet and the game disagree — in every case because
 * the honest answer is "this cannot be converted", and a number would be
 * believed.
 */
export function workshopStatValue(stat: string, level: number): WorkshopStatLookup | null {
  if (DIVERGING.has(stat)) return null

  const mapping = WORKSHOP_STAT_MAPPINGS[stat]
  if (!mapping) return null

  if (!Number.isInteger(level) || level < 0) return null
  const row = WORKSHOP_DATA[stat]?.[String(level)]
  if (!row) return null

  return {
    value: row.value / mapping.scale,
    coinCost: row.coins,
    cashCost: row.cash,
  }
}

/** The highest level the table covers for a stat, or `null` if unknown. */
export function workshopStatMaxLevel(stat: string): number | null {
  const rows = WORKSHOP_DATA[stat]
  if (!rows) return null
  let max = -1
  for (const key of Object.keys(rows)) {
    const level = Number(key)
    if (Number.isInteger(level) && level > max) max = level
  }
  return max < 0 ? null : max
}

/** Every stat this can convert. */
export function workshopStatsWithSheetMapping(): string[] {
  return Object.keys(WORKSHOP_STAT_MAPPINGS)
}

/** The five workshop stats the eHP model reads, keyed as the model names them. */
export const EFFECTIVE_HEALTH_WORKSHOP_STATS = {
  health: 'Health',
  defenseAbsolute: 'Defense Absolute',
  defensePercent: 'Defense Percent',
  wallHealth: 'Wall Health',
  maxRecovery: 'Max Recovery',
} as const
