/**
 * Effective Paths — planning an eDamage path.
 *
 * Five paths across four currencies, and the shape is the same each time: rank
 * every candidate by what a level costs against what it does to *effective
 * damage as a whole*, take the best, repeat.
 *
 * Scoring against the whole model rather than against the stat is what makes
 * it work. Attack Speed pays through bullets per second, through Rapid Fire
 * *and* through Chain Lightning's proc rate; Spotlight's angle pays through
 * every other weapon. A per-stat score would rank all three wrong.
 *
 * The candidate lists are not written again here. They are the transcribed
 * matrices in `effective-paths-edamage-candidates.ts`, paired by position with
 * the level keys in `effective-paths-edamage-levels.ts` — and a test asserts
 * the pairing rather than trusting it.
 */
/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    EffectiveDamagePlanVariant, EffectiveDamageBand, DAMAGE_PLAN_VARIANTS, WORKSHOP_ENHANCEMENTS_LAB, EffectiveDamageUpgrade, EFFECTIVE_DAMAGE_UPGRADES, EffectiveDamagePlanOptions, EffectiveDamagePlan (+1 more)
 * depends    src/internal/own-lookup, src/mechanics/effective-paths-assist-efficiency, src/mechanics/effective-paths-coin-costs, src/mechanics/effective-paths-edamage-candidates, src/mechanics/effective-paths-edamage-coin-levels, src/mechanics/effective-paths-edamage-compute (+7 more)
 * used by    src/mechanics/calculators/specs-generated, src/mechanics/effective-paths-input-ranges, src/mechanics/index
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */

import { ownLookup } from '../internal/own-lookup'
import {
  EFFECTIVE_DAMAGE_CANDIDATES,
} from './effective-paths-edamage-candidates'
import {
  ZERO_EFFECTIVE_DAMAGE_LEVELS,
} from './effective-paths-edamage-levels'
import { COIN_BAND_DELTA_FIELDS } from './effective-paths-edamage-coin-levels'
import type {
  EffectiveDamageCoinLevels,
  EffectiveDamageKeysLevels,
  EffectiveDamageLabLevels,
  EffectiveDamageLevels,
  EffectiveDamageStoneLevels,
} from './effective-paths-edamage-levels'
import {
  computeEffectiveDamage,
  ENHANCEMENT_MULTIPLIER_PER_LEVEL,
} from './effective-paths-edamage-compute'
import type { EffectiveDamageShadow } from './effective-paths-edamage-compute'
import { checkEffectiveDamageInputs } from './effective-paths-edamage-schema'
import type { EffectiveDamageInputIssue } from './effective-paths-edamage-schema'
import type { DamageCard, EffectiveDamageConfig } from './effective-paths-edamage-config'
import {
  KEYS_CANDIDATE_NODES,
  keysCandidateCost,
  keysCandidateMaxLevel,
  resolveUltimateWeaponStat,
  ultimateWeaponMaxLevel,
  ultimateWeaponStatValue,
  ultimateWeaponStoneCost,
} from './effective-paths-edamage-costs'
import {
  assistEfficiencyStoneCost,
  maxStoneLevel,
} from './effective-paths-assist-efficiency'
import {
  MODULE_COIN_PATH_MAX_LEVEL,
  MODULE_COIN_PATH_MIN_LEVEL,
  moduleUpgradeCoinCost,
} from './effective-paths-coin-costs'
import {
  ATTACK_ENHANCEMENT_SPEND_UNLOCKS,
  attackEnhancementSpend,
  enhancementCoinCost,
  enhancementMaxLevel,
} from './effective-paths-enhancement-costs'
import type { WorkshopEnhancementDiscounts } from './effective-paths-enhancement-costs'
import {
  labCoinCostToReachLevel,
  labDurationDaysToReachLevel,
  labMaxCatalogLevel,
} from './effective-paths-lab-costs'
import type { LabCostModifiers } from './effective-paths-lab-costs'
import {
  appendSkipExclusions,
  assertPathVariant,
  type PathExclusion,
  type PathSkip,
  planPath,
} from './effective-paths-planner'
import type { PathStep, PathUpgrade } from './effective-paths-planner'

/**
 * The paths the sheet publishes.
 *
 * The lab tab is one candidate list priced two ways — in research days or in
 * coins — because which of the two binds depends on the player, so it is two
 * variants rather than one.
 */
export type EffectiveDamagePlanVariant
  = 'lab-time' | 'lab-coins' | 'stone' | 'coin' | 'keys'

/** Which half of {@link EffectiveDamageLevels} a candidate moves. */
export type EffectiveDamageBand = 'lab' | 'stone' | 'coin' | 'keys'

/** The variants that read each band's candidate list. */
/** Every variant the damage planner answers to. The lab band has two names. */
export const DAMAGE_PLAN_VARIANTS: readonly EffectiveDamagePlanVariant[] = [
  'lab-time', 'lab-coins', 'stone', 'coin', 'keys',
]

const BAND_VARIANTS: Readonly<Record<EffectiveDamageBand, readonly EffectiveDamagePlanVariant[]>> = {
  lab: ['lab-time', 'lab-coins'],
  stone: ['stone'],
  coin: ['coin'],
  keys: ['keys'],
}

/**
 * The one lab whose sheet name is not its catalog name.
 *
 * Every other one of the 32 resolves directly; this is Chain Lightning's, and
 * the sheet drops the weapon from the label.
 */
const LAB_NAME_ALIASES: Readonly<Record<string, string>> = {
  'Shock Multiplier': 'chain_lightning_shock_multiplier',
}

/** The coin path's workshop enhancements, which the sheet suffixes with `+`. */
/**
 * Workshop enhancements do not exist until their lab is bought.
 *
 * `eDamage Coins!EZ2` opens with `'Master Sheet'!$F$5 <> 1` — row 5 of the lab
 * list is "Workshop Enhancements", a single-level lab. Until it is bought there
 * is nothing to buy, and a planner that does not know this spends the coin path
 * on upgrades the player cannot reach.
 */
export const WORKSHOP_ENHANCEMENTS_LAB = 'Workshop Enhancements'

/**
 * Lab candidates whose prerequisite the sheet checks before offering them.
 *
 * From `eDamage!FV2:GA2`, the lab band's hide row. Each of these multiplies
 * something that has to exist first, so with the prerequisite unmet its gain is
 * zero — and a zero still wins a tie-break, which is how a fresh account's
 * damage path filled up with upgrades that do nothing. Same defect the weapon
 * gates fixed, one layer along.
 *
 * One more in that row is Shock Multiplier: `AND($BH$31, $AL$75)`. `BH31` is
 * Chain Lightning; `AL75` is `AND(BH31, 'Master Sheet'!F33=1)` where F33 is the
 * Chain Lightning Shock lab level — see {@link LAB_PREREQUISITES}.
 */
const LAB_PREREQUISITES: Readonly<Record<string, (config: EffectiveDamageConfig) => boolean>> = {
  // `NOT($AY$43)`. Row 43 of the cards block is the **Damage Mastery card**,
  // not the master switch — `AT41` is the Name header and `AT42` is Damage. So
  // the lab needs that one card, not merely cards being on: reading it as the
  // master switch offers the lab to a player who has cards but not this one.
  'Damage Mastery': config => card(config, 'Damage Mastery'),
  // `NOT(AND($AY$61, $AY$63))` — perks on, and the Damage perk among them.
  'Standard Perks Bonus': config => config.perksEquipped && config.perks.Damage,
  /*
   * `NOT(AND($AY$61, $AY$65))` — `AY65` is the third perk row, Boss Health.
   *
   * VERIFIED against `eDamage!FY2` on 2026-08-19, after the Demon Mode Mastery
   * gate turned out to cite a formula nobody had read back. This one is right:
   * the sheet does AND the perks master with the row.
   *
   * It is also NOT the cause of the four Improve Trade-off Perks mismatches in
   * the 150-account sweep. On every one of them the lab is a candidate, not an
   * excluded one, and the port's gain for +1 level matches the sheet exactly
   * (0.009709 on `account-26`), as does the cost (2.8194 days at level 3→4). So
   * the gate, the gain and the cost are all eliminated; what remains is the
   * ranking as the path progresses, and that is still open.
   */
  'Improve Trade-off Perks': config =>
    config.perksEquipped && config.perks['Boss Health Trade-off'],
  /*
   * `NOT($AY$58)` — row 58 alone, and NOT the cards master beside it.
   *
   * This read `NOT(AND($AY$39, $AY$58))` and required `cardsEquipped` too. The
   * sheet's flag at `GA2` is:
   *
   *     =OR(NOT($AY$58), $AX$19="Attack Disso",
   *         EPG_LEVEL_CHECK(BC44+1, BD44, BE44),
   *         AND($AY$26, NOT(IDS_LAB_HAS_UNLOCKED(GA4))))
   *
   * There is no `$AY$39` in it. The extra condition excluded the lab from the
   * plan on every account with the cards master off, and a 300-account parity
   * sweep is what surfaced it: the sheet opened its path with Demon Mode
   * Mastery while the port would not consider it at all — on an account where
   * the port's own damage model scored the same level at +33%.
   *
   * The comment was wrong before the code was. Both cited a formula nobody had
   * read back.
   *
   * It also does NOT go through {@link card}: that helper ANDs `cardsEquipped`
   * itself, so the first attempt at this fix removed one copy of the condition
   * and left the other, and the sweep reported exactly the same mismatches.
   * Reading the card row directly is the only way to express a gate the sheet
   * writes without the master switch.
   */
  'Demon Mode Mastery': config => Boolean(config.cards['Demon Mode Mastery']?.active),
  /*
   * `NOT(AND($BH$31, $AL$75))`.
   *
   * `BH31` is Chain Lightning. `AL75` is labelled "Shock Mult ⚠️" but its
   * formula is `AND(BH31, 'Master Sheet'!F33=1)` — and Master Sheet row 33 is
   * **Chain Lightning Shock**, the one-level unlock lab, not Shock Multiplier
   * itself. `shockMultiplierUnlocked` on the config is that F33 half; compute
   * already ANDs it with the weapon for the multiplier term.
   */
  'Shock Multiplier': config =>
    Boolean(config.ultimateWeapons['Chain Lightning']?.unlocked)
    && config.shockMultiplierUnlocked,
  /*
   * The six ultimate-weapon amplifier labs, from `eDamage!FF2:FN2`, read back
   * on 2026-08-19. `BH30:BH37` is the ownership column and its rows are in the
   * same order as {@link DAMAGE_ULTIMATE_WEAPONS}, which is what lets a row
   * number be named rather than repeated.
   *
   * ## Why an unowned weapon's lab has to be EXCLUDED, not merely worth zero
   *
   * The port already gave these labs no gain when the weapon is missing — the
   * amplifier multiplies a term that is zero — so under most run types they
   * simply sorted last and nothing looked wrong. Attack Disso is where that
   * stops working: it blanks most other columns, so on `account-12` the two
   * surviving candidates had ROI `1.17e-2` and `2.87e-6`, and a zero-gain
   * Missile Amplifier tied its way to the front of the port's path while the
   * sheet had hidden the column outright.
   *
   * A ranking cannot distinguish "no benefit" from "not applicable" — that is
   * the whole reason the sheet writes these as flags and not as gains.
   */
  'Death Wave Damage Amplifier': config =>
    Boolean(config.ultimateWeapons['Death Wave']?.unlocked),
  'Missile Amplifier': config =>
    Boolean(config.ultimateWeapons['Smart Missiles']?.unlocked),
  // `NOT(AND($BH$33, $BH$34))` — this one needs BOTH, the emitter and the
  // missiles it fires.
  'Spotlight Missiles': config =>
    Boolean(config.ultimateWeapons.Spotlight?.unlocked)
    && Boolean(config.ultimateWeapons['Spotlight Missiles']?.unlocked),
  'Inner Land Mine - Chrono Jump': config =>
    Boolean(config.ultimateWeapons['Inner Land Mines']?.unlocked),
  /*
   * `NOT($BH$35), NOT($AL$69), $AX$19="Attack Disso"` — and the same rend
   * conditions guard `Max Rend Armor Multiplier` at `FH2` without a weapon.
   *
   * Attack Disso appears here as a gate rather than as a zero for the same
   * reason as above: under that run type the armour-rend path does not run at
   * all, so its multiplier is not a small benefit, it is not on offer.
   */
  'Swamp Rend': config =>
    Boolean(config.ultimateWeapons['Poison Swamp']?.unlocked)
    && config.hasRendArmour
    && config.runType !== 'Attack Disso',
  'Max Rend Armor Multiplier': config =>
    config.hasRendArmour && config.runType !== 'Attack Disso',
  /*
   * `NOT(AND($AY$39, $AY$52))` at `FF2` — the cards master AND the Super Tower
   * card, so this one DOES go through {@link card}, unlike Demon Mode Mastery
   * above. The sheet is not consistent about which of the two it writes, which
   * is exactly why each gate is read back rather than inferred from its
   * neighbour.
   */
  'Super Tower Bonus': config => card(config, 'Super Tower'),
  // `NOT($AY$55)` — row alone, no master. Plus the Attack Disso blanket.
  'Ultimate Crit Mastery': config =>
    Boolean(config.cards['Ultimate Crit Mastery']?.active)
    && config.runType !== 'Attack Disso',
}

/**
 * Stone candidates the sheet hides, from `eDamage Stone!FH2:FK2` and `GK2`.
 *
 * An assist module's substat ladder does nothing without the module: the cap
 * `EPG_ASSIST_SUB_CAP` returns a flat zero rather than a smaller scale. So the
 * gain is exactly zero — and a zero still wins a tie-break, which is how the
 * stone path opened with an assist upgrade on all ten accounts of the first
 * sweep.
 *
 * Two more in that row are gated on the IDS import — `NOT('_IDS'!$BG$2)` for
 * Assist Module Bonus - Cannon and `NOT('_IDS'!$BV$2)` for Assist Module
 * Substats - Core. That is save data, not player state the port models, so
 * they are NOT here; see the sweep test, which excludes them explicitly and
 * says why rather than quietly matching.
 */
const STONE_PREREQUISITES: Readonly<Record<string, (config: EffectiveDamageConfig) => boolean>> = {
  // `OR(NOT(AN4), $AX$19="Attack Disso", CN5>=69)` — `AN4` is the Cannon
  // module's own assist flag. The level cap is the candidate's max, not a gate.
  'Assist Module Substats - Cannon': config =>
    config.modules.cannon.hasAssist && config.runType !== 'Attack Disso',
  // `OR(NOT(AN47), CO5>=69)`
  'Assist Module Substats - Armor': config => config.modules.armor.hasAssist,
  // `OR(NOT(AN23), CP5>=99)`
  'Assist Module Bonus - Core': config => config.modules.core.hasAssist,
}

/** Whether a card is equipped and switched on, as the cards block reads it. */
function card(config: EffectiveDamageConfig, name: DamageCard): boolean {
  return config.cardsEquipped && Boolean(config.cards[name]?.active)
}

const ENHANCEMENT_SUFFIX = ' +'

/** The coin path's four module candidates, which buy levels rather than a lab. */
const MODULE_CANDIDATES = new Set([
  'Primary Module - Cannon',
  'Assist Module - Cannon',
  'Primary Module - Core',
  'Assist Module - Core',
])

/** The stone path's assist capacities, and which ladder each one climbs. */
const ASSIST_STONE_KINDS: Readonly<Record<string, 'multiplier' | 'substat'>> = {
  'Assist Module Bonus - Cannon': 'multiplier',
  'Assist Module Bonus - Core': 'multiplier',
  'Assist Module Substats - Cannon': 'substat',
  'Assist Module Substats - Armor': 'substat',
  'Assist Module Substats - Core': 'substat',
}

/** A candidate, resolved to the level it moves and the price of moving it. */
export interface EffectiveDamageUpgrade {
  /** `lab.damage`, `stone.deathWaveDamage` — unique across all four bands. */
  id: string
  band: EffectiveDamageBand
  /** The key within that band's level object. */
  key: string
  sheetName: string
  /**
   * The matrix column, kept so a reader can find it on the sheet.
   *
   * **Relative to the band's own tab**, which is the part worth stating: each
   * band is a separate tab, and its columns only mean anything against that one.
   *
   *   lab    -> eDamage
   *   stone  -> eDamage Stone
   *   coin   -> eDamage Coins
   *   keys   -> eDamage Keys
   *
   * Checked against row 4 of each: all 97 columns resolve to a header matching
   * their `sheetName`. Reading a coin column against `eDamage` instead lands in
   * an unrelated block whose headers are lab names — near enough to look like an
   * off-by-one and waste an hour, which is why the mapping is written down.
   *
   * Metadata only. Nothing reads the sheet with it.
   */
  column: string
}

/** The level keys of each band, in the order the candidate matrices list them. */
const BAND_KEYS: Readonly<Record<EffectiveDamageBand, readonly string[]>> = {
  lab: Object.keys(ZERO_EFFECTIVE_DAMAGE_LEVELS.lab),
  stone: Object.keys(ZERO_EFFECTIVE_DAMAGE_LEVELS.stone),
  coin: Object.keys(ZERO_EFFECTIVE_DAMAGE_LEVELS.coin),
  keys: Object.keys(ZERO_EFFECTIVE_DAMAGE_LEVELS.keys),
}

/**
 * Every candidate on every path, paired with the level it moves.
 *
 * The pairing is positional: the matrix lists candidates in the same order the
 * level interface declares them, which is deliberate and is asserted by a test
 * rather than assumed here.
 */
export const EFFECTIVE_DAMAGE_UPGRADES: readonly EffectiveDamageUpgrade[]
  = (['lab', 'stone', 'coin', 'keys'] as const).flatMap(band =>
    EFFECTIVE_DAMAGE_CANDIDATES[band].map((candidate, index) => ({
      id: `${band}.${BAND_KEYS[band][index]}`,
      band,
      key: BAND_KEYS[band][index],
      sheetName: candidate.sheetName,
      column: candidate.column,
    })),
  )

export interface EffectiveDamagePlanOptions {
  config: EffectiveDamageConfig
  /** Where the player is now. */
  levels: EffectiveDamageLevels
  variant: EffectiveDamagePlanVariant
  /** How many steps to plan. The sheet's grid tops out at 145. */
  steps?: number
  /** Per-upgrade caps, by upgrade id, when the catalog has none to read. */
  maxLevels?: Readonly<Record<string, number>>
  /** Player-imposed stops below the maximum, by upgrade id. */
  targetLevels?: Readonly<Record<string, number>>
  /**
   * Whether the Workshop Enhancements lab is bought. Absent means yes, so a
   * caller that knows nothing about it gets the behaviour it had before.
   */
  workshopEnhancementsUnlocked?: boolean
  /** Upgrades to leave out entirely — the sheet's "Hide non-unlocked". */
  excludeIds?: readonly string[]
  /**
   * Why a given `excludeIds` entry was left out, by id.
   *
   * `excludeIds` is one flat set fed from several places -- a lab the account
   * has not unlocked, and the sheet's display toggles -- and the reason it was
   * reported with was hard-coded to "not unlocked yet" for all of them. So
   * turning on "Hide UW Cooldown" told a player `DW Cooldown - not unlocked
   * yet` about a stat they had MAXED, which is a false statement about their
   * own account and sends them to the wrong screen to fix it.
   *
   * Callers that know the cause supply it here; anything unlabelled keeps the
   * old wording.
   */
  excludeReasons?: Readonly<Record<string, string>>
  /**
   * Whether an upgrade is on the board AT THIS STEP.
   *
   * The coin tab's enhancements UNLOCK partway down the path as coins
   * accumulate: `eDamage Coins!EM5` (Damage / Meter +) opens with
   * `OR(NOT(GTE(EF5, 5000000000000)), …)` and `EI5` (Super Crit Mult +) with
   * `GTE(EF5, 50000000000000)`. `excludeIds` is a single up-front set and
   * cannot express that; this can. See `PathPlanOptions.available`.
   */
  available?: (step: number, id: string, levels: ReadonlyMap<string, number>) => boolean
  /** Every candidate the loop prices, at every step. */
  onCandidateRoi?: (entry: {
    step: number
    id: string
    name: string
    nextLevel: number
    roi: number
    gain: number
    price: number
  }) => void
  /** Lab coin discount and lab speed. */
  labModifiers?: LabCostModifiers
  /** Module upgrade coin discount, as a percentage. */
  moduleDiscountPercent?: number
  /** Workshop discount labs and the vault discount, for the coin path. */
  enhancementDiscounts?: WorkshopEnhancementDiscounts
}

export interface EffectiveDamagePlan {
  steps: PathStep[]
  /**
   * What every candidate scored on the first step — the port's own version of
   * the sheet's per-candidate ROI row.
   *
   * Diagnostic, not a result: it exists so a disagreement about a pick names
   * the candidate instead of requiring 29 numbers to be re-derived by hand.
   */
  firstStepRoi: Array<{ name: string, roi: number, gain: number, cost: number }>
  /** Effective damage before any of it. */
  startingEffectiveDamage: number
  /** Effective damage after the last step. */
  finalEffectiveDamage: number
  /** Candidates left out, and why. A path that silently drops half the game is worse than one that says so. */
  excluded: PathExclusion[]
  /**
   * Why the inputs could not be planned against, when they could not.
   *
   * Empty on every normal call. Non-empty means something upstream handed over
   * a `NaN`, a level that is not a number, or a record missing keys — and the
   * plan is empty rather than a confident ranking built on it.
   */
  issues: EffectiveDamageInputIssue[]
}

/** The catalog name for a lab candidate. */
function labName(sheetName: string): string {
  return LAB_NAME_ALIASES[sheetName] ?? sheetName
}

/** The enhancement stat behind a `"Damage +"` style candidate, if it is one. */
function enhancementStat(sheetName: string): string | null {
  return sheetName.endsWith(ENHANCEMENT_SUFFIX)
    ? sheetName.slice(0, -ENHANCEMENT_SUFFIX.length)
    : null
}

/**
 * The highest level a candidate can reach on a given path, or `null` when
 * nothing prices one — in which case it is excluded rather than guessed at.
 */
function resolveMaxLevel(upgrade: EffectiveDamageUpgrade): number | null {
  if (upgrade.band === 'keys') return keysCandidateMaxLevel(upgrade.sheetName)

  if (upgrade.band === 'lab') {
    const max = labMaxCatalogLevel(labName(upgrade.sheetName))
    return max > 0 ? max : null
  }

  if (upgrade.band === 'stone') {
    const kind = ASSIST_STONE_KINDS[upgrade.sheetName]
    if (kind) return maxStoneLevel(kind)
    const stat = resolveUltimateWeaponStat(upgrade.sheetName)
    return stat ? ultimateWeaponMaxLevel(stat.weapon, stat.stat) : null
  }

  // The coin path buys three different kinds of thing.
  if (MODULE_CANDIDATES.has(upgrade.sheetName)) return MODULE_COIN_PATH_MAX_LEVEL
  const enhancement = enhancementStat(upgrade.sheetName)
  if (enhancement) return enhancementMaxLevel(enhancement)

  // Everything else on the coin path is a lab, bought with coins instead of time.
  const max = labMaxCatalogLevel(labName(upgrade.sheetName))
  return max > 0 ? max : null
}

/**
 * Plan an eDamage path.
 *
 * Candidates keep their matrix order, because the planner breaks a tie by
 * taking the earliest — which is the sheet taking the leftmost column.
 */

/**
 * The sheet's shadow columns, where they disagree with its base columns.
 *
 * `eDamage!EV5` — the Critical Chance Mastery shadow — writes `CC, DJ5 + 1%`
 * flat, while the base column reaches crit chance through `EPD_CRIT_CHANCE`,
 * whose mastery term sits inside `IF(has_card, …)` with
 * `has_card = AND($AY$39, $AY$47)`. With the cards master off the two disagree:
 * the shadow credits a percentage point per mastery level, the base credits
 * none.
 *
 * The bonus is applied ONLY while pricing the candidate. The state after the
 * purchase goes back through the base column, so the level is bought and
 * delivers nothing — which is exactly what the sheet does to itself, and why
 * its path buys Critical Chance Mastery at a point where the port would not.
 *
 * When the card IS on, the base already credits the mastery and this returns
 * nothing, so ordinary accounts are untouched.
 */
/**
 * Where the sheet stops offering CF Slow, expressed as a target level.
 *
 * `eDamage Stone!FF5` blanks the column on `EB5>=10`, and `EB5` is
 * `1/(1 - MIN(90%, reduction + substat))`. That reaches 10 exactly when the
 * `MIN` starts binding, so "the slow has hit ten" and "the 90% cap has been
 * reached" are the same condition, and the gate can be resolved once up front
 * instead of re-checked every step.
 *
 * The level that FIRST crosses 90% is still buyable — the gate reads the slow
 * BEFORE the purchase — and the one after it is not. So the ceiling is that
 * crossing level, not the one below it. Getting this off by one leaves the port
 * either one level short of the sheet or one past it, and both look like a
 * ranking bug rather than a boundary.
 *
 * Returns `undefined` when nothing binds, so the normal maximum applies.
 */
function chronoSlowCeiling(
  config: EffectiveDamageConfig,
  levels: EffectiveDamageLevels,
  upgrade: EffectiveDamageUpgrade,
  maxLevel: number,
): number | undefined {
  if (!upgrade.id.startsWith('stone.') || upgrade.sheetName !== 'CF Slow') return undefined

  // Found by asking the model, not by re-deriving the substat. The sheet's
  // `Substat` weights the assist half by an assist CAPACITY that depends on
  // other levels, and a second copy of that arithmetic here would be one more
  // thing to drift. Comparing the clamped slow against the unclamped one says
  // exactly when `MIN(90%, …)` starts binding, which is the same moment
  // `EB5` reaches 10.
  const base = levels.stone.chronoFieldSlow ?? 0
  for (let level = base + 1; level <= maxLevel; level += 1) {
    const at: EffectiveDamageLevels = {
      ...levels,
      stone: { ...levels.stone, chronoFieldSlow: level },
    }
    const clamped = computeEffectiveDamage(config, at, STONE_PATH_SHADOW).slow
    const free = computeEffectiveDamage(
      config, at, { ...STONE_PATH_SHADOW, chronoSlowUnclamped: true }).slow
    if (free > clamped * (1 + 1e-12)) return level
  }
  return undefined
}

/** The stone path's baseline shadow, which its own ceiling search needs too. */
const STONE_PATH_SHADOW: EffectiveDamageShadow = { weaponStatsFromStoneLevels: true }

/** The keys candidates that rebuild Spotlight rather than reading `$CY5`. */
const KEYS_RECOMPUTE_SPOTLIGHT = new Set(['keys.damagePerMeter', 'keys.damage'])

/** `eDamage Keys!CH5` — the vault's super crit chance node is 2% a level. */
const SUPER_CRIT_CHANCE_PER_VAULT_LEVEL = 0.02

function shadowFor(
  config: EffectiveDamageConfig,
  candidate: PathUpgrade | undefined,
  keysSpotlightVaultPct?: number,
  keysFrozenSpotlight?: number,
): EffectiveDamageShadow {
  /*
   * Keyed on the CANDIDATE, not on a level delta.
   *
   * This compared the levels being priced against the levels the path STARTED
   * from. Once Spotlight Missiles had been bought once, every later candidate
   * — and the step's own baseline — still satisfied "its level went up", so
   * the cooldown override stayed switched on for the whole rest of the path
   * and repriced the entire board. Parity went from 96/100 to 89/100 and the
   * failures moved in both directions at once, which is what a distorted
   * baseline looks like rather than a mis-valued upgrade.
   *
   * The sheet has no such ambiguity: each upgrade is priced in its own column,
   * and a column's quirk cannot reach any other. Naming the candidate is how
   * the port gets the same property.
   */
  if (candidate === undefined) return {}

  // The keys band prices every candidate against the base row's Spotlight.
  if (keysSpotlightVaultPct !== undefined && candidate.id.startsWith('keys.')) {
    return {
      spotlightVaultPct: keysSpotlightVaultPct,
      /*
       * Nine of the eleven end on the base row's Spotlight; `Damage / Meter`
       * and `Damage` do not.
       *
       * Read off the columns, not assumed from the family: `DR5` names no
       * `CY5` at all — it recomputes Spotlight, because the light range it
       * feeds is what Damage / Meter moves — and `DW5` is the local ladder
       * that touches none of this. Freezing all eleven put Damage / Meter
       * behind Damage on the first three steps of five accounts.
       */
      ...(keysFrozenSpotlight !== undefined && !KEYS_RECOMPUTE_SPOTLIGHT.has(candidate.id)
        ? { frozenSpotlightBonus: keysFrozenSpotlight }
        : {}),
      /*
       * Super crit chance carries NO vault term in the composition — neither
       * `eDamage!DL5` nor the port's `superCritChance()` has one — so the two
       * keys candidates that move it have to say so themselves. The keys tab
       * does it by subtracting `$BM$20` and adding its own band back:
       *
       *   DL5 (Critical Chance)     CC, CF5+1%   and   SCC, CH5+1%
       *   DN5 (Super Crit Chance)   CC, CF5      and   SCC, CH5+2%
       *
       * Without these the port valued both at nothing on this axis and ranked
       * them below the sheet on four of the five readable real accounts.
       */

    }
  }

  if (candidate.name === 'Spotlight Missiles') {
    return { spotlightMissilesCooldownSeconds: SHEET_SPOTLIGHT_MISSILES_SHADOW_COOLDOWN }
  }

  /*
   * STONE band only — the name alone is not enough.
   *
   * `Assist Module Substats - Cannon` is a candidate in the lab band too, and
   * the lab tab's shadow for it uses `$AN$4`, the Cannon module's own flag,
   * like everything else. Only `eDamage Stone!FH5` reaches for `$AN$23`.
   *
   * Keying on the name alone applied the stone tab's quirk to the lab path and
   * broke five accounts of the 199-account lab-time sweep, all of them the
   * sheet buying this upgrade where the port then would not. Caught because
   * that sweep is a ratchet at zero rather than a count.
   */
  if (candidate.id.startsWith('stone.')
    && candidate.name === 'Assist Module Substats - Cannon') {
    return { cannonAssistCapUsesCoreFlag: true }
  }

  /*
   * STONE band only, and the sheet disagrees with itself here.
   *
   * `eDamage Stone!EB5`, the BASE slow column, clamps:
   *
   *     1/(1 - MIN(90%, SpeedReduction(CK5) + Substat))
   *
   * `eDamage Stone!FF5`, the column that PRICES the candidate, does not:
   *
   *     CFSlow, 1/(1 - SpeedReduction(CK5+1) - Substat)
   *
   * So a level is valued as if the 90% cap did not exist and then delivers the
   * capped amount, because the next row is computed by the base column again.
   * That is the same shape as Spotlight Missiles, and the planner already
   * handles the consequence by re-settling after each pick.
   *
   * It is not academic: on the accounts where this bites, the clamp binds at
   * level 10 and our gain fell to a fraction of the sheet's, so the port
   * stopped buying at 9 where the sheet buys 10.
   *
   * The sheet's own stop is a GATE rather than a clamp — `FF5` blanks the
   * column on `EB5>=10`, which is the same 90% expressed as a ceiling on the
   * result. So the candidate does disappear, one level later than a clamp would
   * have made it worthless.
   */
  if (candidate.id.startsWith('stone.') && candidate.name === 'CF Slow') {
    return { chronoSlowUnclamped: true }
  }

  /*
   * STONE band only, and again the sheet disagreeing with itself.
   *
   * `eDamage Stone!EU5` and `EV5` are the only candidate columns that move
   * Spotlight COVERAGE, so they are the only ones that rebuild Super Tower
   * rather than reading `DB5` — and their rebuild multiplies the Super Tower
   * lab in a second time. See
   * {@link EffectiveDamageShadow.spotlightCandidateSuperTowerInline}.
   *
   * On `account-9` this is the whole of step 1: it makes the sheet's SL Angle
   * worth 0.712 where ours was 0.0145, which is a factor of 49 and the
   * difference between the sheet opening on SL Angle and the port opening on
   * SL Damage.
   */
  if (candidate.id === 'stone.spotlightAngle' || candidate.id === 'stone.spotlightQuantity') {
    return { spotlightCandidateSuperTowerInline: true }
  }

  /*
   * `eDamage Coins!ET5` rebuilds the composition at the bumped cap and takes
   * its `Rend` from `CG5+1` -- the assist module SUBSTATS column -- while the
   * base row `DL5` takes it from `CJ5`, the BONUS column. So this one
   * candidate REPAIRS the wrong-column difference the base row carries, and
   * its gain includes the repair.
   *
   * That was previously unreproducible for a good reason: the port used the
   * substats level everywhere, so it never had the difference to repair. Now
   * that the base reproduces `CJ5`, switching this candidate back to the
   * substats cap reproduces the repair too.
   */
  /*
   * `eDamage!FM5` and `FS5` take the ILM cooldown from `$AY$10`, the display
   * cell, which already carries the substat they then add again. See
   * {@link EffectiveDamageShadow.innerLandMineCooldownFromDisplayCell}.
   */
  if (candidate.name === 'Inner Land Mine - Chrono Jump'
    || candidate.name === 'Assist Module Substats - Core') {
    return { innerLandMineCooldownFromDisplayCell: true }
  }

  if (candidate.name === 'Assist Module Substats - Cannon') {
    return { maxRendAssistCapFromBonusLevel: false }
  }

  if (candidate.name === 'Critical Chance Mastery') {
    const gated = config.cardsEquipped && Boolean(config.cards['Critical Chance']?.active)
    if (gated || !config.cards['Critical Chance Mastery']?.active) return {}
    // One level, so one percentage point — the shadow's `DJ5 + 1%` exactly.
    return { flatCriticalChanceBonus: 0.01 }
  }

  return {}
}

/**
 * The literal `2` in `eDamage!FI5`, named so the test can cite it rather than
 * repeat it. `20 - 18` — the Spotlight Missiles lab at its cap.
 */
const SHEET_SPOTLIGHT_MISSILES_SHADOW_COOLDOWN = 2

export function planEffectiveDamagePath(
  options: EffectiveDamagePlanOptions,
): EffectiveDamagePlan {
  const { config, levels, variant } = options
  const steps = options.steps ?? 145
  const skipped = new Set(options.excludeIds ?? [])

  assertPathVariant(variant, DAMAGE_PLAN_VARIANTS, 'damage')

  /**
   * The boundary check, run once here rather than inside `evaluate`.
   *
   * `evaluate` runs once per candidate per step — thousands of times for a
   * long path — and the inputs do not change between those calls. Checking
   * here costs one parse and catches the same thing.
   */
  const check = checkEffectiveDamageInputs(config, levels)
  if (!check.ok) {
    return {
      steps: [],
      firstStepRoi: [],
      startingEffectiveDamage: 0,
      finalEffectiveDamage: 0,
      excluded: [],
      issues: check.issues,
    }
  }

  const upgrades: PathUpgrade[] = []
  const excluded: EffectiveDamagePlan['excluded'] = []
  const byId = new Map(EFFECTIVE_DAMAGE_UPGRADES.map(upgrade => [upgrade.id, upgrade]))

  for (const upgrade of EFFECTIVE_DAMAGE_UPGRADES) {
    if (!BAND_VARIANTS[upgrade.band].includes(variant)) continue

    if (skipped.has(upgrade.id)) {
      excluded.push({
        sheetName: upgrade.sheetName,
        reason: options.excludeReasons?.[upgrade.id] ?? 'not unlocked yet',
      })
      continue
    }

    // `eDamage Stone!EY2` and its neighbours gate a weapon's stats on the
    // weapon itself — `NOT($BH$35)` for Poison Swamp, `NOT($BH$37)` for Inner
    // Land Mines. Without it the planner spends stones on a weapon the player
    // does not own: the gain is zero, but a zero still wins a tie-break.
    /*
     * Every ultimate-weapon stone stat is gated on owning the weapon.
     *
     * `eDamage Stone!DZ2:GO2` is uniform about it — `NOT($BH$30)` for all
     * three Death Wave stats, `NOT($BH$31)` for all three Chain Lightning
     * ones, and so on for all 24. Derived from the stat name rather than
     * listed, so a new candidate cannot arrive ungated.
     *
     * Chrono Field carries one more: `OR(NOT($AY$33), NOT($BH$36))`, the
     * enable toggle beside the weapon.
     *
     * Not modelled: `$AY$24` "Hide UW Cooldown" also hides DW Cooldown and SM
     * Cooldown. It is a display toggle like "Hide non-UW Upgrades", the port
     * has no field for it, and it is false by default. Recorded here so its
     * absence is a decision rather than an oversight.
     */
    if (upgrade.band === 'stone') {
      const stat = resolveUltimateWeaponStat(upgrade.sheetName)
      const weaponName = stat?.weapon as keyof EffectiveDamageConfig['ultimateWeapons'] | undefined
      if (weaponName && config.ultimateWeapons[weaponName]) {
        const owned = config.ultimateWeapons[weaponName].unlocked
        const enabled = weaponName !== 'Chrono Field' || config.chronoFieldEnabled
        if (!owned || !enabled) {
          excluded.push({
            sheetName: upgrade.sheetName,
            reason: 'the weapon is not unlocked',
          })
          continue
        }
      }
    }

    const stoneGate = STONE_PREREQUISITES[upgrade.sheetName]
    if (upgrade.band === 'stone' && stoneGate && !stoneGate(config)) {
      excluded.push({
        sheetName: upgrade.sheetName,
        reason: 'what it multiplies is not taken yet',
      })
      continue
    }

    const prerequisite = LAB_PREREQUISITES[upgrade.sheetName]
    if (upgrade.band === 'lab' && prerequisite && !prerequisite(config)) {
      excluded.push({
        sheetName: upgrade.sheetName,
        reason: 'what it multiplies is not taken yet',
      })
      continue
    }

    if (options.workshopEnhancementsUnlocked === false
      && upgrade.sheetName.endsWith(ENHANCEMENT_SUFFIX)) {
      excluded.push({
        sheetName: upgrade.sheetName,
        reason: `the ${WORKSHOP_ENHANCEMENTS_LAB} lab is not bought yet`,
      })
      continue
    }

    const weaponStat = upgrade.band === 'stone'
      ? resolveUltimateWeaponStat(upgrade.sheetName)
      : null
    if (weaponStat && !config.ultimateWeapons[
      weaponStat.weapon as keyof typeof config.ultimateWeapons
    ]?.unlocked) {
      excluded.push({ sheetName: upgrade.sheetName, reason: 'the weapon is not unlocked' })
      continue
    }

    /*
     * `Cash Bonus +` is hidden outright on three conditions, not merely worth
     * zero. `eDamage Coins!EJ2`:
     *
     *     =OR(AM45+AR45=0, $AX$19="Attack Disso", $AX$19="Util Disso")
     *
     * `AM45+AR45` is the Project Funding substat, which is the whole reason the
     * candidate does anything — it reaches damage only through Perfect Freeze.
     *
     * The run-type half is the one that mattered. Worth-zero and hidden are not
     * the same thing here: a zero gain still scores ROI 0 and still wins a tie,
     * which is how three Util Disso accounts bought a candidate their sheet
     * never offers. Same trap as the lab prerequisites above.
     */
    if (upgrade.key === 'enhancementCashBonus') {
      const projectFunding
        = config.uniques['Project Funding'].primary + config.uniques['Project Funding'].assist
      const disallowedRun = config.runType === 'Attack Disso' || config.runType === 'Util Disso'
      if (projectFunding === 0 || disallowedRun) {
        excluded.push({
          sheetName: upgrade.sheetName,
          reason: disallowedRun
            ? `the sheet hides it on ${config.runType}`
            : 'no Project Funding substat, so it reaches nothing',
        })
        continue
      }
    }

    const level = levelOf(levels, upgrade, config)

    // Below 160 a module level is cheaper in shards, so the coin path leaves
    // it alone — the same rule the eHP coin path follows.
    if (MODULE_CANDIDATES.has(upgrade.sheetName) && level < MODULE_COIN_PATH_MIN_LEVEL) {
      excluded.push({
        sheetName: upgrade.sheetName,
        reason: `below level ${MODULE_COIN_PATH_MIN_LEVEL}, where shards are cheaper`,
      })
      continue
    }

    const maxLevel = (options.maxLevels ? ownLookup(options.maxLevels, upgrade.id) : undefined)
      ?? resolveMaxLevel(upgrade)
    if (maxLevel === null) {
      excluded.push({ sheetName: upgrade.sheetName, reason: 'no maximum level known' })
      continue
    }

    upgrades.push({
      id: upgrade.id,
      name: upgrade.sheetName,
      level,
      maxLevel,
      targetLevel: options.targetLevels?.[upgrade.id]
        ?? (variant === 'stone'
          ? chronoSlowCeiling(config, levels, upgrade, maxLevel)
          : undefined),
    })
  }

  const skips: PathSkip[] = []
  /*
   * `$DG$5` — Perfect Freeze at row 5, held fixed for the whole fill-down.
   *
   * Computed once, from the levels the path STARTS at, because that is what an
   * absolute reference means. See
   * {@link EffectiveDamageShadow.perfectFreezeBaseline}.
   */
  /*
   * The stone path rebuilds every weapon stat from its level; the others take
   * the observed value. See
   * {@link EffectiveDamageShadow.weaponStatsFromStoneLevels} — it has to hold
   * for the BASELINE as well as for each candidate, or a level-1 stat gets
   * priced against a fully-upgraded weapon and the gain comes out negative.
   */
  const pathShadow: EffectiveDamageShadow = variant === 'stone'
    ? STONE_PATH_SHADOW
    : variant === 'keys'
      /*
       * `eDamage Keys!CU5` computes Max Rend without the assist substat, and
       * the tab BORROWS most of its UW total from elsewhere:
       *
       *     eDamage Keys!CZ5 DW      = eDamage!EE5
       *     eDamage Keys!DC5 SLM    = eDamage!EH5
       *     CX5 mastery = eDamage!DY5
       *     eDamage Keys!DD5 PS     = the STONE tab's Poison Swamp
       *
       * Only Chain Lightning, Spotlight and the additional damage are its own.
       * So two extra passes: one in the LAB context, one in the STONE context.
       *
       * The lab pass must not carry `maxRendPrimarySubstatOnly` — that is a
       * keys-tab quirk, and it reaches Poison Swamp through
       * `PSRend, 1+(DZ5-1)*CI5*3%`.
       */
      ? (() => {
        const lab = computeEffectiveDamage(config, levels, {}).columns
        const stone = computeEffectiveDamage(
          config, levels, { weaponStatsFromStoneLevels: true },
        ).columns
        return {
          maxRendPrimarySubstatOnly: true,
          ultimateWeaponOverrides: {
            deathWave: lab.EE5,
            smartMissiles: lab.EG5,
            spotlightMissiles: lab.EH5,
            innerLandMines: lab.EL5,
            superTowerUltimateMastery: lab.DY5,
            poisonSwamp: stone.EJ5,
          },
        } satisfies EffectiveDamageShadow
      })()
      /*
       * `eDamage Coins!DL5` caps Max Rend's assist substat off the assist
       * module BONUS level, where the tab's other nine cap-using columns take
       * the SUBSTATS level. See
       * {@link EffectiveDamageShadow.maxRendAssistCapFromBonusLevel}.
       */
      : variant === 'coin'
        ? { maxRendAssistCapFromBonusLevel: true }
        : {}

  const perfectFreezeBaseline
    = computeEffectiveDamage(config, levels, pathShadow).columns.DG5

  /**
   * What every candidate scored on the FIRST step.
   *
   * The sheet publishes a whole row of these and the port published one winner,
   * so any disagreement about a pick had to be localised by re-deriving the
   * others by hand. Step 1 only: later steps depend on what was bought, so they
   * are a consequence of the ranking rather than an independent reading of it.
   */
  const firstStepRoi: EffectiveDamagePlan['firstStepRoi'] = []

  const planned = planPath({
    onCandidateRoi: entry => {
      if (entry.step === 1) {
        firstStepRoi.push({ name: entry.name, roi: entry.roi, gain: entry.gain, cost: entry.price })
      }
      // Chained, not replaced. This used to swallow the caller's callback
      // entirely, so `options.onCandidateRoi` was accepted and never called --
      // a hook that reports nothing looks exactly like a step that priced
      // nothing, which is how a probe here read "ours=none" for every
      // candidate.
      options.onCandidateRoi?.(entry)
    },
    upgrades,
    steps,
    evaluate: (current, candidate) => {
      const next = withLevels(levels, current)
      /*
       * The frozen Spotlight tracks the PATH, not the start of it.
       *
       * `$CY5` is column-absolute and row-RELATIVE, so on the candidate row
       * that prices step k it reads `CY(4+k)` — that step's own base row, not
       * row 5. Freezing at the level the account started with made the vault's
       * marginal return decay across the path while the sheet's stayed flat
       * (1.0014e-4, 1.0132e-4, 1.0117e-4 over three consecutive steps), so the
       * port bought UW Damage once where the sheet bought it twice, and every
       * account came out exactly one step short.
       *
       * `next` already carries the candidate's own bump, so the base level is
       * one below it when the candidate IS the vault's UW Damage node.
       */
      /*
       * Spotlight held WHOLE at this step's base row, computed from the levels
       * before the candidate's own bump.
       */
      const keysFrozenSpotlight = variant === 'keys' && candidate !== undefined
        ? (() => {
          // `current` already carries this candidate's bump; the step's base
          // row is that same board with the one purchase undone.
          const beforeThisStep = new Map(current)
          const own = beforeThisStep.get(candidate.id)
          if (own !== undefined) beforeThisStep.set(candidate.id, own - 1)
          return computeEffectiveDamage(config, withLevels(levels, beforeThisStep), {
            ...pathShadow, perfectFreezeBaseline,
          }).columns.ED5
        })()
        : undefined
      const keysSpotlight = variant === 'keys'
        ? (next.keys.ultimateWeaponDamage
          - (candidate?.id === 'keys.ultimateWeaponDamage' ? 1 : 0))
          * KEYS_CANDIDATE_NODES['UW Damage'].perLevel
        : undefined
      /*
       * Super crit chance ACCUMULATES on the keys band, and nowhere else.
       *
       * `eDamage!DL5` carries no vault term at all — `Base + Substat + Lab +
       * CardCCMastery + BAModule` — so the port's `superCritChance()` has none
       * either, and the two agree. `eDamage Keys!CH5` then adds one back:
       *
       *     ... - $BM$20 + BR5*2%
       *
       * `BR5` is that band's level, so at the base row this cancels and after
       * k purchases it is k*2%. A per-candidate flat 2% covered the bump being
       * priced and NOT the levels already bought, so the error grew with the
       * path: 0.05% at step 1 and 3.7% by step 16, which is where two accounts
       * took Super Crit Chance over a candidate the sheet ranks 3% higher.
       *
       * `next` already carries the candidate's own bump, so this one term
       * replaces both.
       */
      const keysSuperCrit = variant === 'keys'
        ? (next.keys.superCritChance - levels.keys.superCritChance) * SUPER_CRIT_CHANCE_PER_VAULT_LEVEL
        : undefined
      return computeEffectiveDamage(config, next, {
        ...pathShadow,
        ...shadowFor(config, candidate, keysSpotlight, keysFrozenSpotlight),
        ...(keysSuperCrit !== undefined
          ? { flatSuperCritChanceBonus: keysSuperCrit
            // `DL5` bumps `SCC, CH5+1%` alongside its own `CC, CF5+1%`.
            + (candidate?.id === 'keys.criticalChance' ? 0.01 : 0) }
          : {}),
        perfectFreezeBaseline,
      }).effectiveDamage
    },
    /**
     * `Damage +` is priced on its own multiplier, not on effective damage.
     *
     * `eDamage Coins!EZ5` — `Now, 1+1%*BO5 · Next, 1+1%*(BO5+1) · Factor,
     * Next/Now-1`. The two enhancement columns beside it use
     * `(shadow/$EC5 - 1)`, the change in total effective damage, so the sheet
     * really does compare a local ratio against a global one here.
     *
     * ONLY this candidate. The others were checked against the sheet on
     * 2026-08-20 and use the global form; extending this to them because they
     * are the same KIND of upgrade would be reasoning by category over reading.
     */
    relativeGain: (id, nextLevel) => {
      if (id === 'coin.enhancementDamage') {
        const now = 1 + ENHANCEMENT_MULTIPLIER_PER_LEVEL * (nextLevel - 1)
        const next = 1 + ENHANCEMENT_MULTIPLIER_PER_LEVEL * nextLevel
        return next / now - 1
      }
      /*
       * The vault's Damage node, the one keys candidate priced on its own
       * ladder: `eDamage Keys!DW5` is `Now, 1+5%*BO5 · Next, 1+5%*(BO5+1) ·
       * Factor, Next/Now-1`, while the other TEN are `(candidate/$DI5 - 1)`,
       * the change in total effective damage. Enumerated by reading all eleven
       * columns, not inferred from Damage being "the same kind of upgrade".
       *
       * This is load-bearing rather than cosmetic. `towerDamage` takes no vault
       * input at all -- the Damage vault node reaches the composition nowhere
       * -- so through the global form the candidate gains exactly nothing and
       * is never bought. The sheet spent two steps on it and the port spent
       * none, on every account.
       *
       * Modelling it here rather than threading a `vaultPct` into
       * `towerDamage` is what the sheet does: no eDamage column applies this
       * node to the damage figure either. Wiring it into the composition would
       * make the port disagree with the sheet everywhere else to make it agree
       * here.
       */
      if (id === 'keys.damage') {
        const now = 1 + VAULT_DAMAGE_PER_LEVEL * (nextLevel - 1)
        const next = 1 + VAULT_DAMAGE_PER_LEVEL * nextLevel
        return next / now - 1
      }
      return null
    },
    cost: (id, nextLevel) => {
      const upgrade = byId.get(id)
      if (!upgrade) return Number.NaN
      return costOf(upgrade, nextLevel, variant, options) ?? Number.NaN
    },
    onSkip: skip => skips.push(skip),
    /*
     * The coin path's enhancement unlocks, ANDed with whatever the caller asks.
     *
     * `eDamage Coins!EM5` and its four siblings open with
     * `OR(NOT(GTE(EF5, <threshold>)), …)`, where `EF5` is the running spend
     * across the six attack enhancements. It climbs as the path buys, so an
     * enhancement joins the board partway down — a single up-front exclusion
     * set cannot say that, which is why this is here and not in `excludeIds`.
     */
    available: (step, id, current) => {
      if (options.available && !options.available(step, id, current)) return false
      if (variant !== 'coin') return true
      const costStat = COIN_ENHANCEMENT_COST_STAT[id.replace(/^coin\./, '')]
      const unlock = costStat === undefined
        ? undefined
        : ATTACK_ENHANCEMENT_SPEND_UNLOCKS[costStat]
      if (unlock === undefined) return true
      return attackEnhancementSpend(attackEnhancementLevelsAt(current, config, levels)) >= unlock
    },
  })

  // Every candidate the loop passed over, named with the number that
  // disqualified it, so a short path can be explained rather than guessed at.
  appendSkipExclusions(excluded, planned, skips)

  const startingEffectiveDamage
    = computeEffectiveDamage(config, levels, pathShadow).effectiveDamage

  return {
    steps: planned,
    firstStepRoi,
    startingEffectiveDamage,
    finalEffectiveDamage: planned.length
      ? planned[planned.length - 1].value
      : startingEffectiveDamage,
    excluded,
    issues: [],
  }
}


/** `eDamage Keys!DW5` — the vault Damage node is 5% a level. */
const VAULT_DAMAGE_PER_LEVEL = 0.05

/** What it costs to take a candidate to `nextLevel`, in the path's currency. */
function costOf(
  upgrade: EffectiveDamageUpgrade,
  nextLevel: number,
  variant: EffectiveDamagePlanVariant,
  options: EffectiveDamagePlanOptions,
): number | null {
  /*
   * Keys are priced by the level being BOUGHT: `keysCandidateCost(name, L+1)`
   * when the candidate sits at L, which is the sheet's
   * `Cost = base * POW(2, BO5)` read off `eDamage Keys!DW5`.
   *
   * Do not "fix" this into an ordinal measured from the starting level. That
   * was tried, on the evidence that the generated sweep priced every keys
   * candidate `null` and planned zero steps against the sheet's forty. The
   * real cause was the FIXTURE: it rolled vault percentages freely, so the
   * levels came out fractional -- Damage at 0.73, UW Damage at 1.42 -- and
   * there is no such thing as level 1.73 to price. On the nine real accounts
   * every keys level is an integer and the sheet stops each candidate exactly
   * at its cap. An ordinal would have undercharged every account that already
   * owns vault levels, silently.
   */
  if (upgrade.band === 'keys') return keysCandidateCost(upgrade.sheetName, nextLevel)

  if (upgrade.band === 'stone') {
    const kind = ASSIST_STONE_KINDS[upgrade.sheetName]
    if (kind) return assistEfficiencyStoneCost(kind, nextLevel)
    const stat = resolveUltimateWeaponStat(upgrade.sheetName)
    return stat ? ultimateWeaponStoneCost(stat.weapon, stat.stat, nextLevel) : null
  }

  if (upgrade.band === 'coin') {
    if (MODULE_CANDIDATES.has(upgrade.sheetName)) {
      // The table is keyed by the level being left, not the one bought.
      return moduleUpgradeCoinCost(nextLevel - 1, {
        discountLabLevel: options.moduleDiscountPercent,
      })
    }
    const enhancement = enhancementStat(upgrade.sheetName)
    if (enhancement) {
      return enhancementCoinCost(enhancement, nextLevel, options.enhancementDiscounts)
    }
    return labCoinCostToReachLevel(
      labName(upgrade.sheetName), nextLevel, options.labModifiers,
    )
  }

  /*
   * Spotlight Missiles is priced ALL THE WAY TO ITS CAP, alone among the 34.
   *
   *     eDamage!GO5 = (FI5/$ES5-1)
   *       / SUM(ARRAYFORMULA(LABDURATION_SINGLE_ADJUSTED($GO$4,
   *                          SEQUENCE(18-CH5+1, 1, CH5+1))))
   *
   * Every other ROI column divides by one level's duration. This one sums the
   * duration of every level from the next one through 18, and its shadow `FI5`
   * matches: it passes `EP_SLM_DPS` a cooldown of `2` — which is `20 - 18`, the
   * value at that same cap — where the base column `EH5` passes `20 - CH5`.
   *
   * So the pair is self-consistent and this is NOT one of the sheet's
   * inconsistencies: the lab's whole point is the cooldown, and the column
   * asks "what does finishing this lab buy, per day spent finishing it". It
   * then buys one level at a time at that ratio.
   *
   * Reading only the shadow made it look like a bug and priced a single level
   * at the value of the whole run to cap — parity went 96/100 to 89/100. The
   * cost half is what makes it honest, and the two have to move together.
   */
  if (variant === 'lab-time' && upgrade.sheetName === SPOTLIGHT_MISSILES) {
    let total = 0
    for (let level = nextLevel; level <= SPOTLIGHT_MISSILES_MAX_LEVEL; level += 1) {
      const day = labDurationDaysToReachLevel(
        labName(upgrade.sheetName), level, options.labModifiers,
      )
      // A level the catalog cannot price makes the SUM meaningless rather than
      // smaller, so the candidate drops out instead of being flattered.
      if (day === null || !Number.isFinite(day)) return null
      total += day
    }
    return total > 0 ? total : null
  }

  return variant === 'lab-time'
    ? labDurationDaysToReachLevel(labName(upgrade.sheetName), nextLevel, options.labModifiers)
    : labCoinCostToReachLevel(labName(upgrade.sheetName), nextLevel, options.labModifiers)
}

/** The one lab the sheet prices to its cap. See {@link costOf}. */
const SPOTLIGHT_MISSILES = 'Spotlight Missiles'
/** The `18` in `SEQUENCE(18-CH5+1, …)`, and the `20 - 18 = 2` in `FI5`. */
const SPOTLIGHT_MISSILES_MAX_LEVEL = 18

/**
 * A candidate's current level.
 *
 * ## Why the coin band adds the lab band
 *
 * Fourteen keys exist in both — the seven masteries, the assist capacities and
 * the two dissonant echoes — and on the sheet they are **one level**, offered
 * at two prices. `eDamage!GK5` prices the next mastery level as `CD5 + 1`, and
 * `CD` is the single level block; the fourth block that looks like a second one
 * carries headers and no formulas.
 *
 * The two are split here because the compute reads them as
 * `lab.X + levels.coin.X` in thirteen places: the lab band holds what the
 * player has, and the coin band accumulates what a coin path buys on top. That
 * makes `levels.coin[key]` an increment, not a level — so reading it alone
 * offered a maxed mastery from level one, which is exactly what the Coins tab
 * did.
 *
 * Adding them gives the planner the real level while leaving the compute's sums
 * correct: a step raises the increment, and both sides agree on the total.
 */
function levelOf(
  levels: EffectiveDamageLevels,
  upgrade: EffectiveDamageUpgrade,
  config?: EffectiveDamageConfig,
): number {
  switch (upgrade.band) {
    case 'lab': return levels.lab[upgrade.key as keyof EffectiveDamageLabLevels]
    case 'stone': return levels.stone[upgrade.key as keyof EffectiveDamageStoneLevels]
    case 'coin': {
      // A workshop enhancement is already owned to some level, and that level
      // lives on the CONFIG (the sheet's `BI` column) rather than in `levels`.
      // Starting these candidates at zero made the planner offer level 1 of an
      // enhancement the account had nine levels of, so the sheet's `@10` and
      // ours could never line up even once the gain was wired.
      const enhancementStatName = config && COIN_ENHANCEMENT_STAT[upgrade.key]
      if (enhancementStatName) {
        const owned = config.stats[enhancementStatName]?.enhancementLevel ?? 0
        const bought = levels.coin[upgrade.key as keyof EffectiveDamageCoinLevels] ?? 0
        // Absolute on both sides: once the planner has bought any, its own
        // number already includes what was owned.
        return Math.max(owned, bought)
      }
      // Cash Bonus is the seventh enhancement and the one with no stat row —
      // its owned level rides on the config directly. Same absolute rule.
      if (config && upgrade.key === 'enhancementCashBonus') {
        return Math.max(
          config.cashBonusEnhancementLevel,
          levels.coin.enhancementCashBonus ?? 0,
        )
      }
      const shared = levels.lab[upgrade.key as keyof EffectiveDamageLabLevels] ?? 0
      return levels.coin[upgrade.key as keyof EffectiveDamageCoinLevels] + shared
    }
    case 'keys': return levels.keys[upgrade.key as keyof EffectiveDamageKeysLevels]
  }
}

/**
 * Coin candidate key -> the workshop stat whose enhancement it raises.
 *
 * Mirrors `COIN_ENHANCEMENT_LEVELS` in the compute module, in the other
 * direction. Both are needed and neither can be derived from the other without
 * exporting one of them across a module boundary that currently has no reason
 * to exist; they are checked against each other in the coin sweep's tests.
 */
/**
 * Coin upgrade key to the name `effective-paths-enhancement-costs` uses.
 *
 * Deliberately its own map rather than a translation of
 * {@link COIN_ENHANCEMENT_STAT}: the two modules spell four of these
 * differently -- `Super Critical Mult` against `Super Crit Mult`,
 * `Max Rend Armor Multiplier` against `Rend Armor`, `Damage / Meter` against
 * `Damage/Meter` -- and a lookup that misses returns 0 spend, which reads as
 * "nothing bought yet" and silently keeps an unlocked candidate off the board.
 */
const COIN_ENHANCEMENT_COST_STAT: Readonly<Record<string, string>> = {
  enhancementDamage: 'Damage',
  enhancementRendArmor: 'Rend Armor',
  enhancementCriticalFactor: 'Critical Factor',
  enhancementDamagePerMeter: 'Damage/Meter',
  enhancementSuperCritMult: 'Super Crit Mult',
  enhancementAttackSpeed: 'Attack Speed',
}

/**
 * The six attack enhancements at their levels for THIS step: whatever the
 * player owned, or what the path has bought, whichever is further.
 */
function attackEnhancementLevelsAt(
  current: ReadonlyMap<string, number>,
  config: EffectiveDamageConfig,
  levels: EffectiveDamageLevels,
): Record<string, number> {
  const out: Record<string, number> = {}
  for (const [key, costStat] of Object.entries(COIN_ENHANCEMENT_COST_STAT)) {
    const statName = COIN_ENHANCEMENT_STAT[key]
    const owned = statName ? (config.stats[statName]?.enhancementLevel ?? 0) : 0
    const started = levels.coin[key as keyof EffectiveDamageCoinLevels] ?? 0
    const bought = current.get(`coin.${key}`) ?? started
    out[costStat] = Math.max(owned, bought)
  }
  return out
}

const COIN_ENHANCEMENT_STAT: Record<string, keyof EffectiveDamageConfig['stats'] | undefined> = {
  enhancementDamage: 'Damage',
  enhancementCriticalFactor: 'Critical Factor',
  enhancementSuperCritMult: 'Super Critical Mult',
  enhancementAttackSpeed: 'Attack Speed',
  enhancementDamagePerMeter: 'Damage / Meter',
  enhancementRendArmor: 'Max Rend Armor Multiplier',
}

/** The player's levels with a step's purchases applied. */
function withLevels(
  levels: EffectiveDamageLevels,
  current: ReadonlyMap<string, number>,
): EffectiveDamageLevels {
  const next: EffectiveDamageLevels = {
    lab: { ...levels.lab },
    stone: { ...levels.stone },
    coin: { ...levels.coin },
    keys: { ...levels.keys },
  }
  for (const [id, level] of current) {
    const [band, key] = id.split('.') as [EffectiveDamageBand, string]
    /*
     * The coin band's shared keys are a DELTA, and `levelOf` hands back a
     * COMPOSITE. Writing that composite straight back double-counts the lab.
     *
     * For the fourteen keys in `COIN_BAND_DELTA_FIELDS` the compute reads
     * `lab.X + levels.coin.X`, so `levelOf` returns `coin + lab` -- the level
     * the player is actually at, which is what a cost and an `@42` label need.
     * Round-tripping that through here made `levels.coin.X = coin + lab`, and
     * the compute then read `lab + coin + lab`.
     *
     * Every evaluation the coin planner made was on that state, its own
     * baseline included. A doubled lab is not a uniform error: it inflates the
     * masteries and leaves the enhancements alone, so it showed up as a ~4%
     * RANKING spread between the two -- `Damage/Meter +` scoring 4.2% above
     * `Super Crit Mult +` where the sheet has them the other way round.
     *
     * Subtracting the lab restores the delta exactly, and a bumped level still
     * arrives as `coin + 1`. Clamped at zero so a lab level above the composite
     * cannot push it negative.
     */
    const value = band === 'coin' && COIN_BAND_DELTA_FIELDS.has(key as never)
      ? Math.max(0, level - (levels.lab[key as keyof EffectiveDamageLabLevels] ?? 0))
      : level
    ;(next[band] as unknown as Record<string, number>)[key] = value
  }
  return next
}
