/**
 * The path table the player actually reads.
 *
 * A whole-workbook scan found 104 columns on the path tabs that have no row 5,
 * and so are not upstream of any answer cell: the step list itself. They are
 * built from seventeen `EPP_*` named functions, none of which the port had --
 * the port reproduced the computation and the ranking, and stopped at the
 * presentation. See `packages/sdk/src/mechanics/coverage/data/sheet-extraction.v1.json`.
 *
 * The wiring, from `eDamage!D6:L6`:
 *
 *     D  EPP_LAB_DUR_NON_FORMAT(F6:F, G6:G, AI21, D5)   days per step
 *     F  EPP_ITEM_NAME(HD4:IK149, MIN(145, AI21))       upgrade
 *     G  EPP_ITEM_LEVEL(HD4:IK149, BO4:CV149, AI21)     level after the step
 *     H  EPP_LAB_COST(F6:G, AI21)  |  EPP_LAB_CPX(...)  cost, or coin/time
 *     I  EPP_LAB_DUR(D6:D, AI21)                        D, formatted
 *     J  EPP_ITEM_ROI(HD4:IK149, FV4:HC149, AI21, L5)   ROI x the L5 multiplier
 *     K  EPP_ITEM_EVALUE(F6:F, ES6:ES, AI21)            the answer after the step
 *     L  EPP_LAB_RUNNING_TIME(D6:D, AI21)               cumulative D
 *
 * `EPP_ITEM_NAME` / `EPP_ITEM_LEVEL` / `EPP_ITEM_ROI` all do the same thing:
 * find the one column of `EPP_MATRIX` that holds a 1 and read the parallel
 * band at that column. The port's planner resolves the winning candidate
 * directly, so that indirection collapses -- what does NOT collapse is
 * everything below, which is why this module exists.
 */
/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    labCostCurveName, pathDisplayMultiplier, PathDisplayOptions, PathDisplayStep, pathStepDurationDays, pathStepCostCoins, pathStepCoinPerTime, describePathDisplay
 * depends    src/mechanics/effective-paths-lab-costs
 * used by    src/mechanics/calculators/specs-generated, src/mechanics/index
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */

import { labCoinCostToReachLevel, labDurationDaysToReachLevel } from './effective-paths-lab-costs'

/**
 * `IF(ISNUMBER(SEARCH("Mastery", name)), "Card Mastery", name)`.
 *
 * Four of the seventeen lambdas fold the name this way before pricing it: any
 * upgrade whose name contains "Mastery" is costed off the shared Card Mastery
 * curve rather than off a lab of its own, because it does not have one.
 * `SEARCH` is case-insensitive, so the fold is too.
 */
export function labCostCurveName(name: string): string {
  return /mastery/i.test(name) ? 'Card Mastery' : name
}

/**
 * The `x1` / `x24` display toggle, as a number.
 *
 * `EPP_ITEM_ROI` reads it as `IF(timemult<>1, RIGHT(timemult, LEN(timemult)-1), 1)`
 * -- the cell holds the STRING `"x1"` and the lambda strips the leading
 * character. `eDamage!D5` is `RIGHT($L$5, LEN($L$5)-1)` for the same reason.
 * Passing the raw string is the sheet's own contract; a caller that already
 * has a number can pass that instead.
 */
export function pathDisplayMultiplier(toggle: string | number): number {
  if (typeof toggle === 'number') return Number.isFinite(toggle) ? toggle : 1
  const stripped = Number(toggle.slice(1))
  return Number.isFinite(stripped) && stripped !== 0 ? stripped : 1
}

export interface PathDisplayOptions {
  /**
   * The `x N` speed toggle. Divides the per-step duration, and multiplies the
   * displayed ROI. A display knob, NOT the player's Lab Speed lab -- that one
   * is already inside `LABDURATION_SINGLE_ADJUSTED`.
   */
  speedToggle?: string | number
  /** `"Cost"`, `"Coin/H"` or otherwise `"Coin/Day"` -- `eDamage!L3`. */
  costMode?: 'Cost' | 'Coin/H' | 'Coin/Day'
}

export interface PathDisplayStep {
  name: string
  /** The level AFTER the step, which is what the sheet shows. */
  level: number
  /**
   * `EPP_LAB_COST` — null when the upgrade is not a lab.
   *
   * `EPP_COIN_COST` is the same number on the coin tabs, wrapped in
   * `IF(rng="", "", FORMAT_NUMBER(rng))`. This carries the VALUE; the thousands
   * suffix the sheet prints is a rendering choice and belongs to the caller.
   */
  costCoins: number | null
  /** `EPP_LAB_DUR_NON_FORMAT`, in days. */
  durationDays: number | null
  /** `EPP_LAB_RUNNING_TIME` — the running sum of {@link durationDays}. */
  runningTimeDays: number | null
  /** `EPP_LAB_CPX` — coins per hour or per day, or null outside those modes. */
  coinPerTime: number | null
  /** `EPP_ITEM_ROI`, already multiplied by the toggle. */
  roi: number | null
  /** `EPP_ITEM_EVALUE` — the tab's answer after the step. */
  eValue: number | null
  /**
   * The running sum of {@link costCoins}.
   *
   * `EPP_COIN_CUMUL_COST`, `EPP_STONE_CUMUL_COST` and `EPP_KEYS_CUMUL_COST` are
   * the same lambda three times over -- `SCAN(0, rng, LAMBDA(a, c, SUM(a, c)))`
   * -- differing only in what they append to the formatted result (the stone
   * one adds a stone glyph). One running sum covers all three.
   */
  cumulativeCost: number | null
}

/** One step's research time. `EPP_LAB_DUR_NON_FORMAT`, which indexes by `level`. */
export function pathStepDurationDays(
  name: string, level: number, speedToggle: string | number = 1,
): number | null {
  const days = labDurationDaysToReachLevel(labCostCurveName(name), level)
  if (days === null) return null
  const speed = pathDisplayMultiplier(speedToggle)
  return speed > 0 ? days / speed : null
}

/**
 * One step's coin cost. `EPP_LAB_COST`, which indexes by `level - 1`.
 *
 * The `- 1` is NOT written here, and that is the whole subtlety.
 *
 * The sheet's two lambdas are indexed differently from the SDK's two functions,
 * and not by the same amount. Measured against the live grid, for a displayed
 * level `L`:
 *
 *     labDurationDaysToReachLevel(n, L) === LABDURATION_SINGLE_ADJUSTED(n, L)
 *     labCoinCostToReachLevel(n, L)     === LABCOST_SINGLE_ADJUSTED(n, L - 1)
 *
 * So `labCoinCostToReachLevel` has already absorbed the sheet's off-by-one, and
 * transcribing `EPP_LAB_COST`'s `- 1` on top of it shifts the column a second
 * time. That is exactly what the first version of this file did: it returned
 * 29,130 where `eDamage!H6` shows "34.36 K", a plausible-looking table one row
 * out of step, and only a real captured value caught it.
 *
 * Both functions therefore take the DISPLAYED level here. They agree with each
 * other for this use and disagree with each other about the sheet, which is why
 * the relationship is written down rather than left to be re-derived.
 */
export function pathStepCostCoins(name: string, level: number): number | null {
  return labCoinCostToReachLevel(labCostCurveName(name), level)
}

/**
 * `EPP_LAB_CPX` — `cost / (dur / boost) / time`, rounded to two decimals.
 *
 * It disagrees with the two columns beside it: `gen, INDEX(rowVals, 2)-1` feeds
 * BOTH its cost and its duration, so its duration is the level below the one
 * the Duration column shows. Reproduced rather than reconciled -- the point of
 * this module is to render what the sheet renders.
 */
export function pathStepCoinPerTime(
  name: string,
  level: number,
  speedToggle: string | number = 1,
  hoursPerUnit = 1,
): number | null {
  const curve = labCostCurveName(name)
  // `gen` is `level - 1` in the sheet and feeds BOTH lookups. Under the index
  // relationship recorded on `pathStepCostCoins`, that is our `level` for the
  // cost and our `level - 1` for the duration -- so CPX really does read the
  // research time of the level below the one the Duration column prints.
  const cost = labCoinCostToReachLevel(curve, level)
  const days = labDurationDaysToReachLevel(curve, level - 1)
  if (cost === null || days === null || days === 0) return null
  const boost = pathDisplayMultiplier(speedToggle)
  return Math.round((cost / (days / boost) / hoursPerUnit) * 100) / 100
}

/**
 * Turn planned steps into the rows the sheet displays.
 *
 * `steps` carries what the planner already resolved. Anything this cannot
 * price -- a stone or a module, which have no lab curve -- comes back `null`
 * rather than `0`, so a missing cost is never silently a free one.
 */
export function describePathDisplay(
  steps: ReadonlyArray<{ name: string, level: number, roi?: number, value?: number }>,
  options: PathDisplayOptions = {},
): PathDisplayStep[] {
  const { speedToggle = 1, costMode = 'Cost' } = options
  const multiplier = pathDisplayMultiplier(speedToggle)
  const hoursPerUnit = costMode === 'Coin/H' ? 24 : 1

  let runningDays = 0
  let runningCost = 0
  let sawDuration = false
  let sawCost = false

  return steps.map(step => {
    const durationDays = pathStepDurationDays(step.name, step.level, speedToggle)
    const costCoins = pathStepCostCoins(step.name, step.level)
    if (durationDays !== null) { runningDays += durationDays; sawDuration = true }
    if (costCoins !== null) { runningCost += costCoins; sawCost = true }

    return {
      name: step.name,
      level: step.level,
      costCoins,
      durationDays,
      runningTimeDays: sawDuration ? runningDays : null,
      coinPerTime: costMode === 'Cost'
        ? null
        : pathStepCoinPerTime(step.name, step.level, speedToggle, hoursPerUnit),
      roi: step.roi === undefined ? null : step.roi * multiplier,
      eValue: step.value ?? null,
      cumulativeCost: sawCost ? runningCost : null,
    }
  })
}
