/**
 * The coin band, `eDamage Coins!BO5:CM5`, read into {@link EffectiveDamageCoinLevels}.
 *
 * This file exists because the band was modelled and never wired. Every field
 * of `EffectiveDamageCoinLevels` is read by `computeEffectiveDamage`, the type
 * is an exact 1:1 with the sheet's band in column order -- and NOTHING ever
 * populated it. `levelsFromSheet` builds `lab`, `keys` and `stone` and stops,
 * so `levels.coin` stayed at all-zero on every account of every sweep.
 *
 * That is invisible rather than loud, because each reader has a sane-looking
 * zero behaviour. The one that showed was the Core module pair:
 *
 *     eDamage!EN5        EPG_MODULE_BONUS($AM$23, $AN$23, $AO$23, $BL$47, CR5)
 *     eDamage Coins!DO5  EPG_MODULE_BONUS(
 *                          MODSTAT_CORE(rarity(primary), CE5), $AN$23,
 *                          MODSTAT_CORE(rarity(assist),  CF5), $BL$47, CK5)
 *
 * eDamage passes the player's FIXED core bonuses; the coin tab RE-DERIVES them
 * from the module rarity at the levels its own path can buy. `moduleBonusAtLevel`
 * already implements exactly that, and falls back to the fixed bonus when the
 * level is 0 -- so with the band unwired it silently produced the eDamage form
 * on the coin tab. On the live sheet that is 1.505 against 1.04, and because
 * the Core factor multiplies the whole `UWAdditionalDMG` term it came out as a
 * flat 1.44714x on the coin tab's ultimate weapons, on every account.
 *
 * Keyed by the sheet's own row-4 header rather than by column letter: the
 * capture stores `satLevels` under those headers, and BO..CM mean different
 * things on the eDamage tab at the same addresses (`eDamage!BS5` is the Poison
 * Swamp lab where `eDamage Coins!BS5` is the Critical Factor enhancement).
 */
/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    COIN_BAND_HEADERS, COIN_BAND_NON_LEVELS, COIN_BAND_DELTA_FIELDS, CoinLevelsResult, effectiveDamageCoinLevelsFromSheet
 * depends    src/mechanics/effective-paths-edamage-levels
 * used by    src/mechanics/calculators/specs-generated, src/mechanics/effective-paths-edamage-plan, src/mechanics/index
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */

import type { EffectiveDamageCoinLevels } from './effective-paths-edamage-levels'
import { ZERO_EFFECTIVE_DAMAGE_LEVELS } from './effective-paths-edamage-levels'

/** Row 4 of the coin band, in column order, `BO` through `CM`. */
export const COIN_BAND_HEADERS: ReadonlyArray<
  readonly [header: string, field: keyof EffectiveDamageCoinLevels]
> = [
  ['Damage', 'enhancementDamage'],
  ['Damage Mastery', 'damageMastery'],
  ['Demon Mode Mastery', 'demonModeMastery'],
  ['Critical Chance Mastery', 'criticalChanceMastery'],
  ['Critical Factor', 'enhancementCriticalFactor'],
  ['Super Crit Multi', 'enhancementSuperCritMult'],
  ['Cash Bonus', 'enhancementCashBonus'],
  ['Attack Speed', 'enhancementAttackSpeed'],
  ['Attack Speed Mastery', 'attackSpeedMastery'],
  ['Damage / Meter', 'enhancementDamagePerMeter'],
  ['Range Mastery', 'rangeMastery'],
  ['Super Tower Mastery', 'superTowerMastery'],
  ['Max Rend Armor Multiplier', 'enhancementRendArmor'],
  ['Ultimate Crit Mastery', 'ultimateCritMastery'],
  ['Primary Cannon', 'primaryModuleCannon'],
  ['Assist Cannon', 'assistModuleCannon'],
  ['Primary Core', 'primaryModuleCore'],
  ['Assist core', 'assistModuleCore'],
  ['Assist Module Substats - Cannon', 'assistSubstatCannon'],
  ['Assist Module Substats - Armor', 'assistSubstatArmor'],
  ['Assist Module Substats - Core', 'assistSubstatCore'],
  ['Assist Module Bonus - Cannon', 'assistBonusCannon'],
  ['Assist Module Bonus - Core', 'assistBonusCore'],
  ['Dissonant Echo - Attack', 'dissonantEchoAttack'],
  ['Dissonant Echo - Ultimate Weapons', 'dissonantEchoUltimateWeapons'],
]

/**
 * Every header the coin band carries that is NOT a level this path buys.
 *
 * `CO5`/`CP5` are both headed "Cannon" and are a level and a bonus rather than
 * a pair of levels. Naming them keeps {@link effectiveDamageCoinLevelsFromSheet}
 * able to say "this header was dropped, deliberately" instead of ignoring
 * anything it does not recognise -- an unknown header is a capture that has
 * drifted, and it should be loud.
 */
export const COIN_BAND_NON_LEVELS: ReadonlySet<string> = new Set([
  'Cannon', 'Damage +',
])

/**
 * The band is TWO kinds of number, and mixing them silently corrupts a path.
 *
 * `computeEffectiveDamage` reads each field one of two ways:
 *
 *   ABSOLUTE   passed straight to a level -> value function, or differenced
 *              against the config's own starting level
 *                `moduleBonusAtLevel('core', rarity, levels.coin.primaryModuleCore, …)`
 *                `Math.max(0, levels.coin[key] - source.enhancementLevel)`
 *
 *   DELTA      ADDED to the lab level that already carries the account's state
 *                `lab.attackSpeedMastery + levels.coin.attackSpeedMastery`
 *                `levels.lab.assistSubstatCore + levels.coin.assistSubstatCore`
 *
 * The sheet prints every column of the band as an absolute level, so seeding
 * all 25 from the capture double-counts every DELTA field -- the account's
 * masteries and substats get counted once as labs and again as coin levels.
 * Doing exactly that moved three accounts' first divergence EARLIER (step 33 to
 * 31) and introduced two more, which is how this partition got measured rather
 * than assumed.
 *
 * So {@link effectiveDamageCoinLevelsFromSheet} returns both, and callers
 * seeding from a captured band want `absolute`.
 */
export const COIN_BAND_DELTA_FIELDS: ReadonlySet<keyof EffectiveDamageCoinLevels> = new Set([
  'damageMastery', 'demonModeMastery', 'criticalChanceMastery',
  'attackSpeedMastery', 'rangeMastery', 'superTowerMastery', 'ultimateCritMastery',
  'assistSubstatCannon', 'assistSubstatArmor', 'assistSubstatCore',
  'assistBonusCannon', 'assistBonusCore',
  'dissonantEchoAttack', 'dissonantEchoUltimateWeapons',
])

export interface CoinLevelsResult {
  /** Every column of the band, as the sheet prints it. */
  levels: EffectiveDamageCoinLevels
  /**
   * The same, with every {@link COIN_BAND_DELTA_FIELDS} entry left at zero.
   * This is what to seed `levels.coin` with from a captured band.
   */
  absolute: EffectiveDamageCoinLevels
  /** Headers present in the capture that this reader deliberately does not map. */
  dropped: string[]
  /** Headers present in the capture that it does not RECOGNISE. Should be empty. */
  unknown: string[]
  /** Fields of the type that the capture did not supply. Should be empty. */
  missing: Array<keyof EffectiveDamageCoinLevels>
}

/**
 * Read a captured `satLevels` map into the coin band.
 *
 * Reports what it dropped and what it did not recognise rather than swallowing
 * either. A capture that gains or loses a column is a real change to the sheet
 * and has to surface as a test failure, not as a quietly-zero field -- which is
 * the exact failure this whole file is repairing.
 */
export function effectiveDamageCoinLevelsFromSheet(
  satLevels: Record<string, unknown>,
): CoinLevelsResult {
  const levels = { ...ZERO_EFFECTIVE_DAMAGE_LEVELS.coin }
  const missing: Array<keyof EffectiveDamageCoinLevels> = []

  for (const [header, field] of COIN_BAND_HEADERS) {
    const raw = satLevels[header]
    const value = typeof raw === 'number'
      ? raw
      : typeof raw === 'string' && raw.trim() !== '' ? Number(raw) : Number.NaN
    if (!Number.isFinite(value)) {
      missing.push(field)
      continue
    }
    levels[field] = value
  }

  const mapped = new Set(COIN_BAND_HEADERS.map(([header]) => header))
  const dropped: string[] = []
  const unknown: string[] = []
  for (const header of Object.keys(satLevels)) {
    if (mapped.has(header)) continue
    if (COIN_BAND_NON_LEVELS.has(header)) dropped.push(header)
    else unknown.push(header)
  }

  const absolute = { ...levels }
  for (const field of COIN_BAND_DELTA_FIELDS) absolute[field] = 0

  return { levels, absolute, dropped, unknown, missing }
}
