/**
 * Elite spawn chance lookup — same table as the site Elite Spawn Chance chart
 * (`chart-data.ts` / `ELITE_SPAWN_CHANCE_ROWS`).
 */
/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    EliteSpawnChanceAtWave, eliteSpawnChanceAtWave, WaveInfoEliteSpawnOptions, waveInfoEliteSpawnChancePct, waveInfoEliteChartDoubleSpawnPct, waveInfoEliteEffectiveDoubleSpawnPct, WaveInfoBossWaveIntervalInput, computeWaveInfoBossWaveInterval (+15 more)
 * depends    src/data/chart-tables, src/data/enemies, src/data/index, src/mechanics/card-effect-lookup, src/mechanics/enemy-drops-simulation, src/mechanics/tournament-heat-bc
 * used by    src/mechanics/calculators/run, src/mechanics/calculators/specs-generated, src/mechanics/index, src/mechanics/wave-info-panel-stats
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
import { ELITE_SPAWN_CHANCE_ROWS } from '../data/chart-tables'
import { clampCampaignTier } from '../data/index'
import { FLEET_SPAWN_ROWS } from '../data/enemies'
import type { TournamentLeague } from '../data/index'
import { enemyBalanceMasteryDoubleSpawnChancePct } from './card-effect-lookup'
import { computeBossWaveIntervalFromTier } from './enemy-drops-simulation'
import { getTournamentHeatProfile } from './tournament-heat-bc'

export type EliteSpawnChanceAtWave = {
  singleSpawnPct: number
  doubleSpawnPct: number
  /** Wave threshold from the chart row that applies at this tier/wave. */
  waveThreshold: number
  rowIndex: number
}

const ELITE_TYPES = new Set(['Vampire', 'Scatter', 'Ray'])
const FLEET_TYPES = new Set(['Saboteur', 'Commander', 'Overcharge'])

function parsePctCell(cell: string | undefined): number {
  const n = Number.parseInt(String(cell ?? '').replace('%', ''), 10)
  return Number.isFinite(n) ? n : 0
}

function tierColumnIndex(tier: number): number {
  const t = clampCampaignTier(tier)
  return 2 + (t - 1)
}

/**
 * Highest chart row whose tier wave threshold is <= `wave`.
 * Matches Elite Spawn Chance chart footer: wave values = round(modifier × leftRef).
 */
export function eliteSpawnChanceAtWave(tier: number, wave: number): EliteSpawnChanceAtWave {
  const w = Math.max(1, Math.floor(wave))
  const col = tierColumnIndex(tier)

  let rowIndex = 0
  let waveThreshold = 0
  for (let i = 0; i < ELITE_SPAWN_CHANCE_ROWS.length; i += 1) {
    const threshold = Number.parseInt(ELITE_SPAWN_CHANCE_ROWS[i]?.[col] ?? '', 10)
    if (!Number.isFinite(threshold) || threshold > w) continue
    rowIndex = i
    waveThreshold = threshold
  }

  const row = ELITE_SPAWN_CHANCE_ROWS[rowIndex] ?? ELITE_SPAWN_CHANCE_ROWS[0]
  return {
    singleSpawnPct: parsePctCell(row?.[1]),
    doubleSpawnPct: parsePctCell(row?.[0]),
    waveThreshold,
    rowIndex,
  }
}

export type WaveInfoEliteSpawnOptions = {
  /** Enemy Balance mastery — adds double-elite spawn chance from card template. */
  enemyBalanceMastery?: number | null
}

/** Display % for Wave Info elite rows — chart `Single%` column (lookup table). */
export function waveInfoEliteSpawnChancePct(
  tier: number,
  wave: number,
  _options: WaveInfoEliteSpawnOptions = {},
): number {
  return eliteSpawnChanceAtWave(tier, wave).singleSpawnPct
}

/** Chart `Double%` column for elite spawn parentheses (lookup table; excludes EB mastery). */
export function waveInfoEliteChartDoubleSpawnPct(tier: number, wave: number): number {
  return eliteSpawnChanceAtWave(tier, wave).doubleSpawnPct
}

/**
 * Chart `Double%` after EB mastery — EB chance applies on top of the chart double lookup.
 * `Y = eb + (1 − eb) × chartDouble` (each in 0–1).
 */
export function waveInfoEliteEffectiveDoubleSpawnPct(
  tier: number,
  wave: number,
  options: WaveInfoEliteSpawnOptions = {},
): number {
  const chartDouble = spawnChanceUnit(eliteSpawnChanceAtWave(tier, wave).doubleSpawnPct)
  const ebPct = options.enemyBalanceMastery != null && options.enemyBalanceMastery >= 0
    ? enemyBalanceMasteryDoubleSpawnChancePct(options.enemyBalanceMastery)
    : 0
  if (ebPct <= 0) {
    return Math.min(100, Math.round(chartDouble * 1000) / 10)
  }

  const eb = spawnChanceUnit(ebPct)
  const combined = eb + (1 - eb) * chartDouble
  return Math.min(100, Math.round(combined * 1000) / 10)
}

export type WaveInfoBossWaveIntervalInput = {
  tier: number
  tournament?: boolean
  league?: TournamentLeague | null
}

/** Boss cadence from tier More Bosses BC or tournament league profile (every N waves). */
export function computeWaveInfoBossWaveInterval(input: WaveInfoBossWaveIntervalInput): number {
  if (input.tournament && input.league) {
    const profile = getTournamentHeatProfile(input.league)
    if (profile) return Math.max(1, profile.moreBossesEveryWaves)
  }
  return computeBossWaveIntervalFromTier(input.tier)
}

export function isBossSpawnWave(wave: number, bossInterval: number): boolean {
  const w = Math.max(1, Math.floor(wave))
  const interval = Math.max(1, Math.floor(bossInterval))
  return w % interval === 0
}

/** Waves until the next boss spawn wave (same cadence as uptime / enemy drops). */
export function wavesUntilNextBossSpawn(wave: number, bossInterval: number): WavesUntilNextSpawn {
  const w = Math.max(1, Math.floor(wave))
  const interval = Math.max(1, Math.floor(bossInterval))
  if (w % interval === 0) return { waves: 0, onSpawnWave: true }
  return { waves: interval - (w % interval), onSpawnWave: false }
}

function spawnChanceUnit(pct: number): number {
  return Math.max(0, Math.min(1, pct / 100))
}

/**
 * Chance that **2+ elites** spawn this wave — Elite Spawn Chance chart + EB mastery.
 *
 * Chart footer: single cap is 1 until 100% single, then chart double% unlocks a 2nd slot.
 * EB mastery doubles each spawn independently (can yield 2–4 elites at max).
 */
export function waveInfoEliteTwoOrMoreSpawnChancePct(
  tier: number,
  wave: number,
  options: WaveInfoEliteSpawnOptions = {},
): number {
  const { singleSpawnPct, doubleSpawnPct } = eliteSpawnChanceAtWave(tier, wave)
  const chartDouble = spawnChanceUnit(doubleSpawnPct)
  const ebDouble =
    options.enemyBalanceMastery != null && options.enemyBalanceMastery >= 0
      ? spawnChanceUnit(enemyBalanceMasteryDoubleSpawnChancePct(options.enemyBalanceMastery))
      : 0

  let twoPlus: number
  if (singleSpawnPct >= 100) {
    // First elite guaranteed; chart double% rolls a 2nd slot; EB can double either slot.
    twoPlus = ebDouble + (1 - ebDouble) * chartDouble
  } else {
    // Cap still 1 — only EB doubling the single roll can produce 2+.
    twoPlus = spawnChanceUnit(singleSpawnPct) * ebDouble
  }

  return Math.min(100, Math.round(twoPlus * 1000) / 10)
}

/** @deprecated Use {@link waveInfoEliteTwoOrMoreSpawnChancePct} — kept for export stability. */
export const waveInfoEliteDoubleSpawnChancePct = waveInfoEliteTwoOrMoreSpawnChancePct

function fleetSpawnRow(tier: number) {
  return FLEET_SPAWN_ROWS.find(row => row.tier === tier)
}

/** Tier 14+ fleet cadence from `FLEET_SPAWN_ROWS`; below T14 uses 15000 − 250×(tier−1) step 100. */
export function isFleetSpawnWave(tier: number, wave: number): boolean {
  const t = clampCampaignTier(tier)
  const w = Math.max(1, Math.floor(wave))

  const row = fleetSpawnRow(t)
  if (row) {
    if (w < row.firstWave) return false
    return (w - row.firstWave) % row.repeatEveryWaves === 0
  }

  if (t >= 14) return false
  const firstWave = 15000 - (t - 1) * 250
  if (w < firstWave) return false
  return (w - firstWave) % 100 === 0
}

export function isEliteEnemyType(enemyType: string): boolean {
  return ELITE_TYPES.has(enemyType)
}

export function isFleetEnemyType(enemyType: string): boolean {
  return FLEET_TYPES.has(enemyType)
}

export type FleetSpawnSchedule = {
  firstWave: number
  repeatEveryWaves: number
  fleetsPerSpawn: number
}

/** Fleet spawning behavior chart (T14+) + low-tier 15000 − 250×(tier−1) every 100 waves. */
export function fleetSpawnSchedule(tier: number): FleetSpawnSchedule | null {
  const t = clampCampaignTier(tier)
  const row = fleetSpawnRow(t)
  if (row) {
    return {
      firstWave: row.firstWave,
      repeatEveryWaves: row.repeatEveryWaves,
      fleetsPerSpawn: row.fleetsPerSpawn,
    }
  }
  if (t >= 14) return null
  return {
    firstWave: 15000 - (t - 1) * 250,
    repeatEveryWaves: 100,
    fleetsPerSpawn: 1,
  }
}

export type WavesUntilNextSpawn = {
  waves: number
  /** True on the exact wave a fleet spawns (or elite chance tier unlock wave). */
  onSpawnWave: boolean
}

/** Waves until the next fleet spawn wave (Spawning Behavior chart / `FLEET_SPAWN_ROWS`). */
export function wavesUntilNextFleetSpawn(tier: number, wave: number): WavesUntilNextSpawn {
  const schedule = fleetSpawnSchedule(tier)
  const w = Math.max(1, Math.floor(wave))
  if (!schedule) return { waves: 0, onSpawnWave: false }

  const { firstWave, repeatEveryWaves } = schedule
  if (w < firstWave) {
    return { waves: firstWave - w, onSpawnWave: false }
  }

  const offset = (w - firstWave) % repeatEveryWaves
  if (offset === 0) return { waves: 0, onSpawnWave: true }
  return { waves: repeatEveryWaves - offset, onSpawnWave: false }
}

/** Waves until the next elite spawn-chance tier unlock (Elite Spawn Chance chart). */
export function wavesUntilNextEliteSpawnTier(tier: number, wave: number): WavesUntilNextSpawn | null {
  const w = Math.max(1, Math.floor(wave))
  const col = tierColumnIndex(tier)
  const current = eliteSpawnChanceAtWave(tier, w)

  if (current.singleSpawnPct >= 100 || current.doubleSpawnPct >= 100) {
    return null
  }

  for (let i = 0; i < ELITE_SPAWN_CHANCE_ROWS.length; i += 1) {
    const threshold = Number.parseInt(ELITE_SPAWN_CHANCE_ROWS[i]?.[col] ?? '', 10)
    if (!Number.isFinite(threshold) || threshold <= w) continue
    return { waves: threshold - w, onSpawnWave: false }
  }

  return null
}

export type WaveInfoSpawnColumn =
  | {
    kind: 'percent'
    pct: number
    /** Elite effective double spawn % for parentheses. */
    doublePct?: number
    /** When set, parentheses render as `(2x Y%)` instead of `(Y%)`. */
    eliteDoublePrefix?: '2x'
  }
  | { kind: 'wavesUntil', waves: number, onSpawnWave: boolean }

/** Boss row — 100% on boss waves, otherwise waves until the next boss spawn. */
export function waveInfoBossSpawnColumn(wave: number, bossInterval: number): WaveInfoSpawnColumn {
  const next = wavesUntilNextBossSpawn(wave, bossInterval)
  if (next.onSpawnWave) return { kind: 'percent', pct: 100 }
  return { kind: 'wavesUntil', waves: next.waves, onSpawnWave: false }
}

/** Fleet rows only — waves until next spawn (`FLEET_SPAWN_ROWS` / Spawning Behavior chart). */
export function waveInfoFleetSpawnColumn(tier: number, wave: number): WaveInfoSpawnColumn {
  const next = wavesUntilNextFleetSpawn(tier, wave)
  if (next.onSpawnWave) return { kind: 'wavesUntil', waves: 0, onSpawnWave: true }
  return { kind: 'wavesUntil', waves: next.waves, onSpawnWave: false }
}
