/**
 * ELS vs ELS+ upgrade path — coin ROI from skip-chance simulation.
 *
 * Standard utility ELS (`upgradeWorkshopUtilityLevel[11|12]`):
 *   workshop base rises +0.0005 per level (0.05% display step)
 *
 * Enhancement ELS+ (workshop key `WSP_ENEMY_LEVEL_SKIP`):
 *   mult = 1 + enhancementLevel × 0.01 on `(workshop + module cluster)` for both tracks.
 *
 * ROI % ranks upgrades by coin efficiency at the reference wave:
 *   (Δ skip levels × relative skip boost %) / (wave × coin cost), scaled to %.
 * Skip levels use `simulateEnemyLevelSkips` in-run counter simulation.
 */
/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    ELS_ATTACK_WORKSHOP_KEY, ELS_HEALTH_WORKSHOP_KEY, ELS_ENHANCEMENT_KEY, ELS_ENHANCEMENT_TRACKER_ALIASES, computeElsEnhancementLevel, ElsWorkshopTrackerLead, ElsBudgetAllocationRow, formatElsSkipPct (+32 more)
 * depends    src/data/workshop, src/data/workshop-costs, src/data/workshop-tracker-definitions, src/mechanics/els-module-cluster, src/mechanics/enemy-level-skip, src/mechanics/roi-scaling
 * used by    src/internal/game-input-data/workshop-stat-dropdown-math, src/internal/shared-tool-inputs-field-sync, src/mechanics/calculators/specs-generated, src/mechanics/els-calculator-options, src/mechanics/index, src/save/shared-tool-inputs-from-save-extended
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */

import {
  computeElsTrackSkipChance,
  type ElsSkipSourceInput,
} from './els-module-cluster'
import {
  applyTierBattleConditionsToSkipChance,
  deterministicSkipLevelsFromChance,
  LEVEL_SKIP_WORKSHOP_PER_LEVEL,
  simulateEnemyLevelSkips,
  type TierSkipChanceAdjustments,
} from './enemy-level-skip'
import {
  computeDiscountedWorkshopCost,
  computeWorkshopTotalDiscountPercent,
} from '../data/workshop'
import { getWorkshopCostByKeyAndLevel, getWorkshopMaxLevelByKey } from '../data/workshop-costs'
import { getWorkshopStatDefinitions } from '../data/workshop-tracker-definitions'
import { computeRoiReferenceCost, formatAdaptiveRoiPct } from './roi-scaling'

export const ELS_ATTACK_WORKSHOP_KEY = 'Enemy Attack Level Skip'
export const ELS_HEALTH_WORKSHOP_KEY = 'Enemy Health Level Skip'
export const ELS_ENHANCEMENT_KEY = 'WSP_ENEMY_LEVEL_SKIP'

/** Save import / legacy workshop tracker keys for utility ELS+ enhancement. */
export const ELS_ENHANCEMENT_TRACKER_ALIASES = [
  'Enemy Level Skip +',
  'Enemy Level Skips +',
] as const

/** Read ELS+ enhancement level from workshop tracker keys (canonical + import aliases). */
export function computeElsEnhancementLevel(
  enhancementLevels: Record<string, number> | null | undefined,
): number {
  if (!enhancementLevels || typeof enhancementLevels !== 'object') return 0

  const canonical = Number(enhancementLevels[ELS_ENHANCEMENT_KEY])
  if (Number.isFinite(canonical) && canonical > 0) {
    return Math.max(0, Math.floor(canonical))
  }

  for (const alias of ELS_ENHANCEMENT_TRACKER_ALIASES) {
    const value = Number(enhancementLevels[alias])
    if (Number.isFinite(value) && value > 0) {
      return Math.max(0, Math.floor(value))
    }
  }

  return Number.isFinite(canonical) ? Math.max(0, Math.floor(canonical)) : 0
}

export type ElsWorkshopTrackerLead = {
  attackUtilityLevel?: number
  healthUtilityLevel?: number
  enhancementLevel?: number
  utilityDiscountPct?: number
  enhancementDiscountPct?: number
  enhancementVaultDiscountPct?: number
}

export interface ElsBudgetAllocationRow {
  kind: ElsUpgradeKind
  label: string
  levels: number
  totalCoinCost: number
  endingLevel: number
}

/** Format an absolute skip chance percentage (e.g. 1.15%). */
export function formatElsSkipPct(valuePct: number): string {
  if (!Number.isFinite(valuePct)) return '0%'
  return `${valuePct.toFixed(2)}%`
}

/** Skip chance shown for a path row — the track that upgrade affects. */
export function elsRowSkipChancePct(
  kind: ElsUpgradeKind,
  attackPct: number,
  healthPct: number,
): number {
  if (kind === 'health') return healthPct
  return attackPct
}

export function formatElsRowSkipChance(
  kind: ElsUpgradeKind,
  attackPct: number,
  healthPct: number,
): string {
  return formatElsSkipPct(elsRowSkipChancePct(kind, attackPct, healthPct))
}

/** Relative skip % improvement from one level: (Δ skip / skip before) × 100. */
export function computeElsRoiPerLevel(
  kind: ElsUpgradeKind,
  before: ElsSkipChanceSnapshot,
  attackSkipPctDelta: number,
  healthSkipPctDelta: number,
  focus: ElsUpgradeFocus,
): number {
  if (kind === 'attack') {
    return before.attackPct > 0 ? (attackSkipPctDelta / before.attackPct) * 100 : 0
  }
  if (kind === 'health') {
    return before.healthPct > 0 ? (healthSkipPctDelta / before.healthPct) * 100 : 0
  }
  const attackRoi = before.attackPct > 0 ? (attackSkipPctDelta / before.attackPct) * 100 : 0
  const healthRoi = before.healthPct > 0 ? (healthSkipPctDelta / before.healthPct) * 100 : 0
  if (focus === 'attack') return attackRoi
  if (focus === 'health') return healthRoi
  return attackRoi + healthRoi
}

export function formatElsRoiPerLevel(roiPct: number): string {
  return formatAdaptiveRoiPct(roiPct)
}

/**
 * Coin ROI as a percentage — combines skip-chance boost, skip levels at the
 * reference wave, and coin cost, normalized by the player's reference upgrade cost:
 *   (marginalSkipLevels × relativeSkipBoost% × referenceCost) / (wave × coinCost)
 */
export function computeElsRoiPct(
  referenceWave: number,
  marginalSkipLevels: number,
  relativeSkipBoostPct: number,
  coinCost: number,
  referenceCost: number,
): number {
  const wave = Math.max(1, Math.floor(referenceWave))
  if (!Number.isFinite(marginalSkipLevels) || marginalSkipLevels <= 0) return 0
  if (!Number.isFinite(relativeSkipBoostPct) || relativeSkipBoostPct <= 0) return 0
  if (!Number.isFinite(coinCost) || coinCost <= 0) return 0
  const ref = Number.isFinite(referenceCost) && referenceCost > 0 ? referenceCost : 1
  return (marginalSkipLevels * relativeSkipBoostPct * ref) / (wave * coinCost)
}

export const formatElsRoiPct = formatElsRoiPerLevel

export function formatElsMarginalSkipLevels(levels: number): string {
  if (!Number.isFinite(levels) || levels <= 0) return '0'
  if (levels >= 10) return `+${levels.toFixed(1)}`
  if (levels >= 1) return `+${levels.toFixed(2)}`
  return `+${levels.toFixed(3)}`
}

/** Format a skip-chance change in percentage points (e.g. +0.05%). */
export function formatElsSkipPctDelta(deltaPct: number, options?: { signed?: boolean }): string {
  if (!Number.isFinite(deltaPct)) return '0%'
  const signed = options?.signed !== false
  if (deltaPct === 0) return '0%'
  const prefix = signed && deltaPct > 0 ? '+' : ''
  const abs = Math.abs(deltaPct)
  if (abs >= 10) return `${prefix}${deltaPct.toFixed(1)}%`
  if (abs >= 1) return `${prefix}${deltaPct.toFixed(2)}%`
  if (abs >= 0.1) return `${prefix}${deltaPct.toFixed(3)}%`
  return `${prefix}${deltaPct.toFixed(4)}%`
}

export function aggregateElsUpgradeStepsByKind(steps: ElsUpgradeStep[]): ElsBudgetAllocationRow[] {
  const order: ElsUpgradeKind[] = ['attack', 'health', 'enhancement']
  const grouped = new Map<ElsUpgradeKind, ElsBudgetAllocationRow>()

  for (const step of steps) {
    const existing = grouped.get(step.kind)
    if (!existing) {
      grouped.set(step.kind, {
        kind: step.kind,
        label: step.label,
        levels: 1,
        totalCoinCost: step.coinCost,
        endingLevel: step.toLevel,
      })
      continue
    }

    existing.levels += 1
    existing.totalCoinCost += step.coinCost
    existing.endingLevel = step.toLevel
  }

  return order
    .map(kind => grouped.get(kind))
    .filter((row): row is ElsBudgetAllocationRow => row != null)
}

function readNumberRecordValue(record: Record<string, unknown> | undefined, key: string): number | undefined {
  if (!record) return undefined
  const value = Number(record[key])
  if (!Number.isFinite(value) || value < 0) return undefined
  return Math.floor(value)
}

function readDiscount(record: Record<string, unknown> | undefined, key: string): number | undefined {
  if (!record) return undefined
  const value = Number(record[key])
  if (!Number.isFinite(value)) return undefined
  return Math.max(0, Math.min(100, value))
}

/** Resolve ELS calculator defaults from a workshop tracker cloud/local blob when present. */
export function findElsLeadFromWorkshopTrackerBlob(blob: Record<string, unknown> | null | undefined): ElsWorkshopTrackerLead | null {
  if (!blob || typeof blob !== 'object') return null

  const progress = blob.progress && typeof blob.progress === 'object'
    ? blob.progress as Record<string, unknown>
    : undefined
  const settings = blob.settings && typeof blob.settings === 'object'
    ? blob.settings as Record<string, unknown>
    : undefined
  const ui = settings?.ui && typeof settings.ui === 'object'
    ? settings.ui as Record<string, unknown>
    : undefined
  const levels = progress?.levels && typeof progress.levels === 'object'
    ? progress.levels as Record<string, unknown>
    : blob.levels && typeof blob.levels === 'object'
      ? blob.levels as Record<string, unknown>
      : undefined
  const enhancementLevels = progress?.enhancementLevels && typeof progress.enhancementLevels === 'object'
    ? progress.enhancementLevels as Record<string, unknown>
    : blob.enhancementLevels && typeof blob.enhancementLevels === 'object'
      ? blob.enhancementLevels as Record<string, unknown>
      : undefined

  const lead: ElsWorkshopTrackerLead = {
    attackUtilityLevel: readNumberRecordValue(levels, ELS_ATTACK_WORKSHOP_KEY),
    healthUtilityLevel: readNumberRecordValue(levels, ELS_HEALTH_WORKSHOP_KEY),
    enhancementLevel: computeElsEnhancementLevel(enhancementLevels as Record<string, number> | undefined),
    utilityDiscountPct: readDiscount(ui, 'discountUtility'),
    enhancementDiscountPct: readDiscount(ui, 'enhancementDiscountUtility'),
    enhancementVaultDiscountPct: readDiscount(ui, 'enhancementDiscountVault'),
  }

  const hasData = Object.values(lead).some(value => value != null)
  return hasData ? lead : null
}

/** Workshop enhancement level → enhancement multiplier contribution (level × 0.01). */
export const ELS_ENHANCEMENT_FIELD_SCALE = 0.01

export type ElsUpgradeKind = 'attack' | 'health' | 'enhancement'
export type ElsUpgradeFocus = 'combined' | 'attack' | 'health'

export interface ElsWorkshopLevels {
  attackUtilityLevel: number
  healthUtilityLevel: number
  enhancementLevel: number
}

export interface ElsUpgradeDiscounts {
  utilityDiscountPct?: number
  enhancementDiscountPct?: number
  enhancementVaultDiscountPct?: number
}

export interface ElsUpgradePathInput extends ElsWorkshopLevels, ElsUpgradeDiscounts, ElsSkipSourceInput {
  referenceWave: number
  /** Max greedy steps (default 25). */
  maxSteps?: number
  /** Stop when cumulative coin spend reaches this (optional). */
  coinBudget?: number | null
  focus?: ElsUpgradeFocus
  /** Fixed reference upgrade cost for economy-scaled ROI (set at path start). */
  roiReferenceCost?: number
  /** Tier battle conditions applied to in-run skip chance (ELS Reduction, multiply, etc.). */
  tierSkipAdjustments?: TierSkipChanceAdjustments
  /**
   * Pre-resolved vault/module/lab skip sources. When set, path math uses this directly
   * instead of re-resolving from flattened input fields.
   */
  resolvedSkipSources?: ElsSkipSourceInput
  /** @deprecated Use vault + module slot fields. */
  moduleClusterAttack?: number
  /** @deprecated Use vault + module slot fields. */
  moduleClusterHealth?: number
  /** @deprecated Use {@link ElsModuleSlotBonusesPct.primaryAttackPct}. */
  modulePrimaryAttackPct?: number
  /** @deprecated Use {@link ElsModuleSlotBonusesPct.assistAttackPct}. */
  moduleAssistAttackPct?: number
  /** @deprecated Use {@link ElsModuleSlotBonusesPct.primaryHealthPct}. */
  modulePrimaryHealthPct?: number
  /** @deprecated Use {@link ElsModuleSlotBonusesPct.assistHealthPct}. */
  moduleAssistHealthPct?: number
}

export interface ElsSkipChanceSnapshot {
  attack: number
  health: number
  attackPct: number
  healthPct: number
}

export interface ElsUpgradeStep {
  step: number
  kind: ElsUpgradeKind
  label: string
  fromLevel: number
  toLevel: number
  coinCost: number
  cumulativeCoinCost: number
  attackSkipPct: number
  healthSkipPct: number
  /** Relative skip % improvement from this level (Δ / before × 100). */
  roiPerLevel: number
  /** Coin ROI percentage (skip levels × skip boost % / wave / coins). */
  roiPct: number
  /** Extra skip levels at the reference wave from this click. */
  marginalSkipLevels: number
}

export interface ElsUpgradePathResult {
  referenceWave: number
  focus: ElsUpgradeFocus
  /** Workshop / stored skip at path start (matches level dropdown %). */
  starting: ElsSkipChanceSnapshot
  /** Workshop / stored skip after the last path step. */
  ending: ElsSkipChanceSnapshot
  /** Workshop levels after the last path step. */
  endingLevels: ElsWorkshopLevels
  steps: ElsUpgradeStep[]
  totalCoinCost: number
  nextBest: ElsUpgradeStep | null
}

export interface ElsMarginalUpgradeOption {
  kind: ElsUpgradeKind
  label: string
  fromLevel: number
  toLevel: number
  coinCost: number
  roiPerLevel: number
  roiPct: number
  marginalSkipLevels: number
  attackSkipPct: number
  healthSkipPct: number
}

function clampLevel(value: number, min: number, max: number): number {
  const n = Math.floor(Number(value) || 0)
  return Math.max(min, Math.min(max, n))
}

/** Normalize module/vault/lab skip inputs (supports legacy `modulePrimary*` aliases). */
export function getElsSkipSources(input: ElsSkipSourceInput & {
  moduleClusterAttack?: number
  moduleClusterHealth?: number
  modulePrimaryAttackPct?: number
  moduleAssistAttackPct?: number
  modulePrimaryHealthPct?: number
  moduleAssistHealthPct?: number
}): ElsSkipSourceInput {
  const primaryAttackPct = input.modulePrimaryAttackPct ?? input.primaryAttackPct
  const assistAttackPct = input.moduleAssistAttackPct ?? input.assistAttackPct
  const primaryHealthPct = input.modulePrimaryHealthPct ?? input.primaryHealthPct
  const assistHealthPct = input.moduleAssistHealthPct ?? input.assistHealthPct
  const vaultAttackStars = input.vaultAttackStars
  const vaultHealthStars = input.vaultHealthStars

  const hasModuleSlots = primaryAttackPct != null
    || assistAttackPct != null
    || primaryHealthPct != null
    || assistHealthPct != null
  const hasVault = vaultAttackStars != null || vaultHealthStars != null
  const hasLegacyCluster = (input.moduleClusterAttack ?? 0) > 0
    || (input.moduleClusterHealth ?? 0) > 0

  const labFields = {
    labAttackBenefitIncrease: input.labAttackBenefitIncrease ?? 0,
    labHealthBenefitIncrease: input.labHealthBenefitIncrease ?? 0,
  }

  if (hasModuleSlots || hasVault || hasLegacyCluster) {
    return {
      vaultAttackStars: vaultAttackStars ?? 0,
      vaultHealthStars: vaultHealthStars ?? 0,
      primaryAttackPct: primaryAttackPct ?? (input.moduleClusterAttack ?? 0) * 100,
      assistAttackPct: assistAttackPct ?? 0,
      primaryHealthPct: primaryHealthPct ?? (input.moduleClusterHealth ?? 0) * 100,
      assistHealthPct: assistHealthPct ?? 0,
      ...labFields,
    }
  }

  return {
    vaultAttackStars: 0,
    vaultHealthStars: 0,
    primaryAttackPct: 0,
    assistAttackPct: 0,
    primaryHealthPct: 0,
    assistHealthPct: 0,
    ...labFields,
  }
}

export function computeWorkshopSkipChances(
  levels: ElsWorkshopLevels,
  sources: ElsSkipSourceInput = {} as ElsSkipSourceInput,
): ElsSkipChanceSnapshot {
  const resolved = getElsSkipSources(sources)
  const attack = computeElsTrackSkipChance(
    'attack',
    levels.attackUtilityLevel,
    levels.enhancementLevel,
    resolved,
  )
  const health = computeElsTrackSkipChance(
    'health',
    levels.healthUtilityLevel,
    levels.enhancementLevel,
    resolved,
  )
  return {
    attack,
    health,
    attackPct: attack * 100,
    healthPct: health * 100,
  }
}

/**
 * Sources for in-run effective BC (matches the utility % shown during a run).
 * The workshop dropdown keeps the full module cluster plus labs; the in-run display applies
 * battle conditions to the stored primary only, without the research-lab addition.
 */
export function elsSkipSourcesForInRunEffectiveBc(
  sources: ElsSkipSourceInput,
): ElsSkipSourceInput {
  const resolved = getElsSkipSources(sources)
  return {
    ...resolved,
    assistAttackPct: 0,
    assistHealthPct: 0,
    labAttackBenefitIncrease: 0,
    labHealthBenefitIncrease: 0,
  }
}

/**
 * In-run effective skip shown during an active tier run (after BC + counter labs).
 * Dropdown / workshop preview uses the full module cluster; game run UI applies tier BC
 * to the primary-module stored chance (@ `enemyAttackLevelSkipChance` / `enemyHealthLevelSkipChance`).
 */
export function computeElsInRunEffectiveSkipChances(
  levels: ElsWorkshopLevels,
  sources: ElsSkipSourceInput = {} as ElsSkipSourceInput,
  adjustments?: TierSkipChanceAdjustments,
): ElsSkipChanceSnapshot {
  if (!adjustments) {
    return computeWorkshopSkipChances(levels, getElsSkipSources(sources))
  }
  const stored = computeWorkshopSkipChances(levels, elsSkipSourcesForInRunEffectiveBc(sources))
  return applyElsTierSkipAdjustments(stored, adjustments)
}

/** Apply tier BC adjustments to stored workshop skip chances for in-run effective values. */
export function applyElsTierSkipAdjustments(
  snapshot: ElsSkipChanceSnapshot,
  adjustments?: TierSkipChanceAdjustments,
): ElsSkipChanceSnapshot {
  if (!adjustments) return snapshot
  const attack = applyTierBattleConditionsToSkipChance(snapshot.attack, adjustments)
  const health = applyTierBattleConditionsToSkipChance(snapshot.health, adjustments)
  return {
    attack,
    health,
    attackPct: attack * 100,
    healthPct: health * 100,
  }
}

function workshopSkipSnapshot(
  levels: ElsWorkshopLevels,
  skipSources: ElsSkipSourceInput,
): ElsSkipChanceSnapshot {
  return computeWorkshopSkipChances(levels, skipSources)
}

/** Path table + summary display — stored workshop skip (matches level dropdown parentheses). */
function pathDisplaySkipSnapshot(
  levels: ElsWorkshopLevels,
  skipSources: ElsSkipSourceInput,
): ElsSkipChanceSnapshot {
  return workshopSkipSnapshot(levels, skipSources)
}

function resolvePathSkipSources(input: ElsUpgradePathInput): ElsSkipSourceInput {
  return input.resolvedSkipSources ?? getElsSkipSources(input)
}

/** Additional enemy levels skipped at `referenceWave` from a skip-chance delta. */
export function marginalSkipLevelsAtWave(
  referenceWave: number,
  beforeChance: number,
  afterChance: number,
): number {
  const wave = Math.max(1, Math.floor(referenceWave))
  const before = Math.max(0, Math.min(1, beforeChance))
  const after = Math.max(0, Math.min(1, afterChance))
  if (after <= before) return 0

  const counterDelta = simulateEnemyLevelSkips(wave, after).totalSkips
    - simulateEnemyLevelSkips(wave, before).totalSkips
  if (counterDelta > 0) return counterDelta

  const roundedDelta = deterministicSkipLevelsFromChance(wave, after).totalSkips
    - deterministicSkipLevelsFromChance(wave, before).totalSkips
  if (roundedDelta > 0) return roundedDelta

  return (after - before) * wave
}

function utilityDiscountTotal(discounts: ElsUpgradeDiscounts): number {
  return computeWorkshopTotalDiscountPercent(discounts.utilityDiscountPct ?? 0, 0)
}

function enhancementDiscountTotal(discounts: ElsUpgradeDiscounts): number {
  return computeWorkshopTotalDiscountPercent(
    discounts.enhancementDiscountPct ?? 0,
    discounts.enhancementVaultDiscountPct ?? 0,
  )
}

function findStandardElsStat(key: string) {
  return getWorkshopStatDefinitions().find(stat => stat.key === key) ?? null
}

/** Coin cost to upgrade standard utility ELS from `fromLevel` → `fromLevel + 1`. */
export function standardElsCoinUpgradeCost(
  statKey: string,
  fromLevel: number,
  utilityDiscountPct = 0,
): number | null {
  const stat = findStandardElsStat(statKey)
  if (!stat) return null
  const nextLevel = Math.floor(fromLevel) + 1
  if (nextLevel > stat.maxLevel) return null
  const entry = stat.levels.find(row => row.level === nextLevel)
  if (!entry || entry.coins <= 0) return null
  return computeDiscountedWorkshopCost(entry.coins, utilityDiscountTotal({ utilityDiscountPct }))
}

/** Coin cost to upgrade enhancement ELS+ from `fromLevel` → `fromLevel + 1`. */
export function enhancementElsCoinUpgradeCost(
  fromLevel: number,
  enhancementDiscountPct = 0,
  enhancementVaultDiscountPct = 0,
): number | null {
  const maxLevel = (getWorkshopMaxLevelByKey(ELS_ENHANCEMENT_KEY) ?? -1) + 1
  if (fromLevel >= maxLevel) return null
  const base = getWorkshopCostByKeyAndLevel(ELS_ENHANCEMENT_KEY, fromLevel)
  if (base == null || base <= 0) return null
  return computeDiscountedWorkshopCost(
    base,
    enhancementDiscountTotal({ enhancementDiscountPct, enhancementVaultDiscountPct }),
  )
}

function scoreMarginalSkipLevels(
  referenceWave: number,
  before: ElsSkipChanceSnapshot,
  after: ElsSkipChanceSnapshot,
  focus: ElsUpgradeFocus,
): number {
  const attackGain = marginalSkipLevelsAtWave(referenceWave, before.attack, after.attack)
  const healthGain = marginalSkipLevelsAtWave(referenceWave, before.health, after.health)
  if (focus === 'attack') return attackGain
  if (focus === 'health') return healthGain
  return attackGain + healthGain
}

function compareMarginalUpgrades(a: ElsMarginalUpgradeOption, b: ElsMarginalUpgradeOption): number {
  const roiDiff = b.roiPct - a.roiPct
  if (roiDiff !== 0) return roiDiff
  const skipDiff = b.marginalSkipLevels - a.marginalSkipLevels
  if (skipDiff !== 0) return skipDiff
  return a.coinCost - b.coinCost
}

function kindLabel(kind: ElsUpgradeKind): string {
  if (kind === 'attack') return 'Attack ELS'
  if (kind === 'health') return 'Health ELS'
  return 'ELS+ Enhancement'
}

function levelsAfterUpgrade(
  levels: ElsWorkshopLevels,
  kind: ElsUpgradeKind,
): ElsWorkshopLevels {
  if (kind === 'attack') {
    return { ...levels, attackUtilityLevel: levels.attackUtilityLevel + 1 }
  }
  if (kind === 'health') {
    return { ...levels, healthUtilityLevel: levels.healthUtilityLevel + 1 }
  }
  return { ...levels, enhancementLevel: levels.enhancementLevel + 1 }
}

function canUpgradeStandard(statKey: string, fromLevel: number): boolean {
  const stat = findStandardElsStat(statKey)
  if (!stat) return false
  return fromLevel < stat.maxLevel
}

function canUpgradeEnhancement(fromLevel: number): boolean {
  const maxLevel = (getWorkshopMaxLevelByKey(ELS_ENHANCEMENT_KEY) ?? -1) + 1
  return fromLevel < maxLevel
}

function resolveElsRoiReferenceCostAtLevels(
  levels: ElsWorkshopLevels,
  input: ElsUpgradePathInput,
): number {
  const costs: number[] = []
  if (canUpgradeStandard(ELS_ATTACK_WORKSHOP_KEY, levels.attackUtilityLevel)) {
    const cost = standardElsCoinUpgradeCost(
      ELS_ATTACK_WORKSHOP_KEY,
      levels.attackUtilityLevel,
      input.utilityDiscountPct,
    )
    if (cost != null && cost > 0) costs.push(cost)
  }
  if (canUpgradeStandard(ELS_HEALTH_WORKSHOP_KEY, levels.healthUtilityLevel)) {
    const cost = standardElsCoinUpgradeCost(
      ELS_HEALTH_WORKSHOP_KEY,
      levels.healthUtilityLevel,
      input.utilityDiscountPct,
    )
    if (cost != null && cost > 0) costs.push(cost)
  }
  if (canUpgradeEnhancement(levels.enhancementLevel)) {
    const cost = enhancementElsCoinUpgradeCost(
      levels.enhancementLevel,
      input.enhancementDiscountPct,
      input.enhancementVaultDiscountPct,
    )
    if (cost != null && cost > 0) costs.push(cost)
  }
  return computeRoiReferenceCost(costs)
}

export function listElsMarginalUpgrades(
  input: ElsUpgradePathInput,
): ElsMarginalUpgradeOption[] {
  const focus = input.focus ?? 'combined'
  const wave = Math.max(1, Math.floor(input.referenceWave))
  const skipSources = resolvePathSkipSources(input)
  const levels: ElsWorkshopLevels = {
    attackUtilityLevel: clampLevel(input.attackUtilityLevel, 0, 999_999),
    healthUtilityLevel: clampLevel(input.healthUtilityLevel, 0, 999_999),
    enhancementLevel: clampLevel(input.enhancementLevel, 0, 999_999),
  }
  const referenceCost = input.roiReferenceCost ?? resolveElsRoiReferenceCostAtLevels(levels, input)
  const storedBefore = workshopSkipSnapshot(levels, skipSources)
  const options: ElsMarginalUpgradeOption[] = []

  const pushOption = (
    kind: ElsUpgradeKind,
    coinCost: number | null,
    afterLevels: ElsWorkshopLevels,
    fromLevel: number,
  ) => {
    if (coinCost == null || coinCost <= 0) return
    const storedAfter = workshopSkipSnapshot(afterLevels, skipSources)
    const attackSkipPctDelta = storedAfter.attackPct - storedBefore.attackPct
    const healthSkipPctDelta = storedAfter.healthPct - storedBefore.healthPct
    const roiPerLevel = computeElsRoiPerLevel(kind, storedBefore, attackSkipPctDelta, healthSkipPctDelta, focus)
    const marginalSkipLevels = scoreMarginalSkipLevels(wave, storedBefore, storedAfter, focus)
    const roiPct = computeElsRoiPct(wave, marginalSkipLevels, roiPerLevel, coinCost, referenceCost)
    if (marginalSkipLevels <= 0 || roiPct <= 0) return
    options.push({
      kind,
      label: kindLabel(kind),
      fromLevel,
      toLevel: fromLevel + 1,
      coinCost,
      roiPerLevel,
      roiPct,
      marginalSkipLevels,
      attackSkipPct: storedAfter.attackPct,
      healthSkipPct: storedAfter.healthPct,
    })
  }

  if (canUpgradeStandard(ELS_ATTACK_WORKSHOP_KEY, levels.attackUtilityLevel)) {
    pushOption(
      'attack',
      standardElsCoinUpgradeCost(
        ELS_ATTACK_WORKSHOP_KEY,
        levels.attackUtilityLevel,
        input.utilityDiscountPct,
      ),
      levelsAfterUpgrade(levels, 'attack'),
      levels.attackUtilityLevel,
    )
  }

  if (canUpgradeStandard(ELS_HEALTH_WORKSHOP_KEY, levels.healthUtilityLevel)) {
    pushOption(
      'health',
      standardElsCoinUpgradeCost(
        ELS_HEALTH_WORKSHOP_KEY,
        levels.healthUtilityLevel,
        input.utilityDiscountPct,
      ),
      levelsAfterUpgrade(levels, 'health'),
      levels.healthUtilityLevel,
    )
  }

  if (canUpgradeEnhancement(levels.enhancementLevel)) {
    pushOption(
      'enhancement',
      enhancementElsCoinUpgradeCost(
        levels.enhancementLevel,
        input.enhancementDiscountPct,
        input.enhancementVaultDiscountPct,
      ),
      levelsAfterUpgrade(levels, 'enhancement'),
      levels.enhancementLevel,
    )
  }

  return options.sort(compareMarginalUpgrades)
}

export function buildElsBudgetAllocation(input: ElsUpgradePathInput): ElsBudgetAllocationRow[] {
  const budget = input.coinBudget != null && Number.isFinite(input.coinBudget)
    ? Math.max(0, Number(input.coinBudget))
    : null
  if (budget == null || budget <= 0) return []

  const path = buildElsUpgradePath({
    ...input,
    maxSteps: 1_000_000,
    coinBudget: budget,
  })
  return aggregateElsUpgradeStepsByKind(path.steps)
}

export function buildElsUpgradePath(input: ElsUpgradePathInput): ElsUpgradePathResult {
  const focus = input.focus ?? 'combined'
  const wave = Math.max(1, Math.floor(input.referenceWave))
  const budget = input.coinBudget != null && Number.isFinite(input.coinBudget)
    ? Math.max(0, Number(input.coinBudget))
    : null
  const maxSteps = budget != null
    ? 1_000_000
    : Math.max(1, Math.min(200, Math.floor(input.maxSteps ?? 25)))

  let levels: ElsWorkshopLevels = {
    attackUtilityLevel: clampLevel(input.attackUtilityLevel, 0, 999_999),
    healthUtilityLevel: clampLevel(input.healthUtilityLevel, 0, 999_999),
    enhancementLevel: clampLevel(input.enhancementLevel, 0, 999_999),
  }

  const skipSources = resolvePathSkipSources(input)
  const starting = pathDisplaySkipSnapshot(levels, skipSources)
  const roiReferenceCost = resolveElsRoiReferenceCostAtLevels(levels, input)

  const steps: ElsUpgradeStep[] = []
  let cumulativeCoin = 0
  let nextBest: ElsUpgradeStep | null = null

  for (let stepIndex = 0; stepIndex < maxSteps; stepIndex += 1) {
    const marginal = listElsMarginalUpgrades({
      ...input,
      ...levels,
      referenceWave: wave,
      focus,
      roiReferenceCost,
    })
    const best = marginal[0]
    if (!best) break
    if (budget != null && cumulativeCoin + best.coinCost > budget) break

    if (nextBest == null) {
      nextBest = {
        step: 1,
        kind: best.kind,
        label: best.label,
        fromLevel: best.fromLevel,
        toLevel: best.toLevel,
        coinCost: best.coinCost,
        cumulativeCoinCost: best.coinCost,
        attackSkipPct: best.attackSkipPct,
        healthSkipPct: best.healthSkipPct,
        roiPerLevel: best.roiPerLevel,
        roiPct: best.roiPct,
        marginalSkipLevels: best.marginalSkipLevels,
      }
    }

    cumulativeCoin += best.coinCost
    levels = levelsAfterUpgrade(levels, best.kind)
    const after = pathDisplaySkipSnapshot(levels, skipSources)

    steps.push({
      step: stepIndex + 1,
      kind: best.kind,
      label: best.label,
      fromLevel: best.fromLevel,
      toLevel: best.toLevel,
      coinCost: best.coinCost,
      cumulativeCoinCost: cumulativeCoin,
      attackSkipPct: after.attackPct,
      healthSkipPct: after.healthPct,
      roiPerLevel: best.roiPerLevel,
      roiPct: best.roiPct,
      marginalSkipLevels: best.marginalSkipLevels,
    })
  }

  const ending = pathDisplaySkipSnapshot(levels, skipSources)

  return {
    referenceWave: wave,
    focus,
    starting,
    ending,
    endingLevels: { ...levels },
    steps,
    totalCoinCost: cumulativeCoin,
    nextBest,
  }
}

/** Per-level skip increment metadata for display and tests. */
export const ELS_UPGRADE_SKIP_METADATA = {
  standardPerLevel: LEVEL_SKIP_WORKSHOP_PER_LEVEL,
  enhancementMultPerLevel: ELS_ENHANCEMENT_FIELD_SCALE,
  enhancementAppliesToBothTracks: true,
  simulateModel: 'simulateEnemyLevelSkips (counterEHLS / counterEALS)',
} as const
