/**
 * Enemy stats for a wave, and the band helper the level-skip maths uses.
 *
 * Previously two files: the implementation under `internal/` and a re-export
 * here. The shim added nothing but a second name for the same module and a
 * collision that stopped the implementation moving, so they are one file.
 */
/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    EnemyWaveEnemyType, EnemyWaveBaseStats, EnemyWaveStats, ENEMY_TYPE_MULT, EnemyWaveScalingContext, getBasicEnemyWaveStats, getWaveBaseStats, getEnemyWaveStats (+1 more)
 * depends    src/data/campaign-tier, src/mechanics/enemy-type-mults, src/mechanics/wave-base-scaling
 * used by    src/internal/enemy-stats-calcs-local-state, src/mechanics/calculators/specs-generated, src/mechanics/enemy-level-skip, src/mechanics/enemy-stat-display, src/mechanics/enemy-stats-simplified, src/mechanics/enemy-wave-info-labs (+4 more)
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
import { clampCampaignTier } from '../data/campaign-tier'
import {
  computeWaveBaseDamage,
  computeWaveBaseHealth,
} from './wave-base-scaling'
import { ENEMY_TYPE_MULT_TABLE } from './enemy-type-mults'

export type EnemyWaveEnemyType = keyof typeof ENEMY_TYPE_MULT_TABLE

export interface EnemyWaveBaseStats {
  hp: number
  damage: number
}

export interface EnemyWaveStats extends EnemyWaveBaseStats {
  tier: number
  wave: number
  enemyType: EnemyWaveEnemyType
  tournament: boolean
}

export const ENEMY_TYPE_MULT = ENEMY_TYPE_MULT_TABLE

export interface EnemyWaveScalingContext {
  tournament?: boolean
  /** CustomizeGame.isTestingTournamentConditions — dev BC test mode only. */
  isTestingTournamentConditions?: boolean
  /** @deprecated Use isTestingTournamentConditions */
  tournamentLeague?: boolean
}

function resolveWaveInput(
  tier: number,
  wave: number,
  context: boolean | EnemyWaveScalingContext = false,
) {
  const t = clampCampaignTier(tier)
  const w = Math.max(1, Math.floor(wave))
  const tournament = typeof context === 'boolean' ? context : (context.tournament ?? false)
  const tournamentLeague = typeof context === 'boolean'
    ? undefined
    : context.tournamentLeague
  const isTesting = typeof context === 'boolean'
    ? undefined
    : context.isTestingTournamentConditions
  return {
    wave: w,
    tier: t,
    tournament,
    ...(isTesting != null ? { isTestingTournamentConditions: isTesting } : {}),
    ...(tournamentLeague != null && isTesting == null
      ? { tournamentLeague }
      : {}),
  }
}

export function getBasicEnemyWaveStats(
  tier: number,
  wave: number,
  context: boolean | EnemyWaveScalingContext = false,
): EnemyWaveBaseStats {
  const input = resolveWaveInput(tier, wave, context)
  return {
    hp: computeWaveBaseHealth(input),
    damage: computeWaveBaseDamage(input),
  }
}

export function getWaveBaseStats(wave: number): EnemyWaveBaseStats {
  return getBasicEnemyWaveStats(1, wave, false)
}

export function getEnemyWaveStats(
  tier: number,
  wave: number,
  enemyType: EnemyWaveEnemyType = 'Basic',
  context: boolean | EnemyWaveScalingContext = false,
): EnemyWaveStats | null {
  const input = resolveWaveInput(tier, wave, context)
  const typeMult = ENEMY_TYPE_MULT[enemyType]
  if (!typeMult) return null

  const base = getBasicEnemyWaveStats(input.tier, input.wave, context)

  return {
    tier: input.tier,
    wave: input.wave,
    enemyType,
    tournament: input.tournament,
    hp: Math.floor(base.hp * typeMult.hp),
    damage: Math.floor(base.damage * typeMult.damage),
  }
}

/** Legacy band helper used by enemy-level-skip.ts (not GetWaveBaseHealth bands). */
export function waveBands(wave: number) {
  const w = Math.max(1, Math.floor(wave))
  return {
    over1024: Math.floor(w / 1024),
    over5: Math.floor(w / 5),
    over10: Math.floor(w / 10),
    over6: Math.floor(w / 6),
    over15: Math.floor(w / 15),
    over25: Math.floor(w / 25),
    over37: Math.floor(w / 37),
    over38: Math.floor(w / 38),
    over50: Math.floor(w / 50),
    over75: Math.floor(w / 75),
    over100: Math.floor(w / 100),
    over200: Math.floor(w / 200),
    over300: Math.floor(w / 300),
    overHigh: Math.floor(w / 500),
    overLate: Math.floor(w / 1000),
    overAdj: Math.floor(Math.floor(w / 10) / 64),
  }
}
