/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    GUARDIAN_TYPE_HALF_DAMAGE, GuardianTickDamageInput, guardianTickDamage, GuardianDamagePool, depleteGuardianPool, GUARDIAN_SAVE_KEYS
 * depends    —
 * used by    src/mechanics/calculators/specs-generated, src/mechanics/index
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
export const GUARDIAN_TYPE_HALF_DAMAGE = 3

export interface GuardianTickDamageInput {
  startTime: number
  endTime: number
  damageMultiplier: number
  guardianType: number
}

export function guardianTickDamage(input: GuardianTickDamageInput): number {
  const delta = Math.max(0, input.endTime - input.startTime)
  let dmg = delta * input.damageMultiplier
  if (input.guardianType === GUARDIAN_TYPE_HALF_DAMAGE) {
    dmg *= 0.5
  }
  return dmg
}

export interface GuardianDamagePool {
  start: number
  end: number
}

export function depleteGuardianPool(
  pool: GuardianDamagePool,
  tickDamage: number,
): { pool: GuardianDamagePool, overflow: number } {
  const remaining = pool.end - pool.start
  if (tickDamage <= remaining) {
    return {
      pool: { start: pool.start + tickDamage, end: pool.end },
      overflow: 0,
    }
  }
  return {
    pool: { start: pool.end, end: pool.end },
    overflow: tickDamage - remaining,
  }
}

export const GUARDIAN_SAVE_KEYS = [
  'guardianChipLevel',
  'guardianChipUnlocked',
  'guardianCooldownTimers',
  'totalDamageByGuardian',
] as const
