/**
 * CustomizeGame.heatLevel[] indices — finalized from curated v28.3 native extraction.
 * @see packages/platform/src/game-data/v28.3/
 */
/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    HEAT_BC_INDEX_ELS_REDUCTION_NATIVE, HEAT_BC_INDEX_NATIVE, V283_HEAT_BC_INDEX, HeatBcIndexKey
 * depends    src/data/generated/index
 * used by    src/mechanics/index
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
export {
  V283_HEAT_BC_INDEX as HEAT_BC_INDEX_NATIVE,
  V283_HEAT_BC_INDEX,
  type V283HeatBcIndexKey as HeatBcIndexKey,
} from '../data/generated/index'

import { V283_HEAT_BC_INDEX } from '../data/generated/index'

/** @deprecated Use {@link V283_HEAT_BC_INDEX.elsReduction}. */
export const HEAT_BC_INDEX_ELS_REDUCTION_NATIVE = V283_HEAT_BC_INDEX.elsReduction
