/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    IlmHitMultiplierBreakdown, IlmDamageChainBreakdown, computeIlmCannonModuleMult, computeIlmTowerDamage, computeIlmDetonationModuleMult, computeIlmDamageSubstatAdditive, computeIlmUwDamageMult, computeIlmUwModuleBonus (+15 more)
 * depends    src/data/index, src/data/module-bonus, src/mechanics/assist-module-efficiency, src/mechanics/bot-hit-multiplier, src/mechanics/ilm-calculator-options, src/mechanics/ilm-charge
 * used by    src/mechanics/calculators/specs-generated, src/mechanics/index
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
import { clampAssistMultiplierEfficiencyPct } from './assist-module-efficiency'
import { computeModuleStat, type ModuleCalcType } from '../data/module-bonus'
import { computeLabValueAtLevel, getSharedToolLabs } from '../data/index'
import {
  chainLightningShockMultiplier,
  enemyHitMultiplier,
  type EnemyHitMultiplierInput,
} from './bot-hit-multiplier'
import {
  computeAmplifyBotBonusMultiplier,
  computeIlmUniqueModuleRarityBonus,
  ILM_MODULE_SUBSTAT_NONE,
  ILM_UNIQUE_MODULE_IDS,
  ilmModuleSubstatBonusFromRarity,
  type IlmUniqueModuleRarityChoice,
} from './ilm-calculator-options'
import type {
  IlmCalcsScenarioSettings,
  IlmCalcsSettings,
  IlmCalcsStaticSettings,
  IlmCalculatorInput,
  IlmModuleLevelRarity,
} from './ilm-charge'
import {
  computeInnerLandMinesDamageMult,
  computeMineAgeSecondsFromWaves,
  computeTowerDamageFromAttackLevel,
  DEFAULT_PROTECTOR_DAMAGE_REDUCTION_MULT,
  PROTECTOR_DAMAGE_REDUCTION_LAB_SLUG,
  SHOCK_MULTIPLIER_LAB_SLUG,
} from './ilm-charge'

export type { IlmCoreModuleLevelRarity, IlmModuleLevelRarity } from './ilm-charge'

export interface IlmHitMultiplierBreakdown {
  total: number
  shockMultiplier: number
  shockStack: number
  effectiveShockLabMultiplier: number
  dimensionCoreDoublesShock: boolean
  dimensionCoreMaxShockStack: number
  amplifyBotMultiplier: number
  singularityHarnessActive: boolean
  acpShockwaveMultiplier: number
  protectorDamageReduction: number
}

export interface IlmDamageChainBreakdown {
  towerDamageBase: number
  cannonModuleMult: number
  towerDamage: number
  uwDamageMultBase: number
  uwDamageSubstatAdditive: number
  uwDamageMult: number
  coreModuleMult: number
  charge: number
  hitMultiplier: number
}

function clampPct(value: unknown, fallback: number): number {
  const n = Math.floor(Number(value))
  if (!Number.isFinite(n)) return fallback
  return clampAssistMultiplierEfficiencyPct(n)
}

function assistEffectiveBonus(baseMult: number, assistEffPct: number): number {
  const efficiency = clampPct(assistEffPct, 0) / 100
  return 1 + (baseMult - 1) * efficiency
}

function resolveModuleMult(type: ModuleCalcType, slot: IlmModuleLevelRarity): number {
  return computeModuleStat({
    type,
    rarityLabel: slot.rarity || 'Common',
    level: Math.max(1, slot.level),
  })
}

function resolveCombinedModuleMult(
  primary: IlmModuleLevelRarity,
  assist: IlmModuleLevelRarity,
  assistEffPct: number,
  type: ModuleCalcType,
): number {
  const primaryMult = resolveModuleMult(type, primary)
  const assistBase = resolveModuleMult(type, assist)
  return primaryMult * assistEffectiveBonus(assistBase, assistEffPct)
}

function isDimensionCoreEquipped(rarity: IlmUniqueModuleRarityChoice): boolean {
  return rarity !== ILM_MODULE_SUBSTAT_NONE
}

function isAcpEquipped(rarity: IlmUniqueModuleRarityChoice): boolean {
  return rarity !== ILM_MODULE_SUBSTAT_NONE
}

/** Attack (Cannon) modules scale tower damage before ILM detonation. */
export function computeIlmCannonModuleMult(staticSettings: IlmCalcsStaticSettings): number {
  return resolveCombinedModuleMult(
    staticSettings.primaryCannon,
    staticSettings.assistCannon,
    staticSettings.assistEffPct,
    'cannon',
  )
}

export function computeIlmTowerDamage(staticSettings: IlmCalcsStaticSettings): number {
  const base = computeTowerDamageFromAttackLevel(staticSettings.attackDamageLevel)
  return base * computeIlmCannonModuleMult(staticSettings)
}

/** Core modules supply GetModuleBonus at ILM detonation. */
export function computeIlmDetonationModuleMult(staticSettings: IlmCalcsStaticSettings): number {
  return resolveCombinedModuleMult(
    staticSettings.primaryCore,
    staticSettings.assistCore,
    staticSettings.assistEffPct,
    'core',
  )
}

export function computeIlmDamageSubstatAdditive(staticSettings: IlmCalcsStaticSettings): number {
  const primary = ilmModuleSubstatBonusFromRarity(staticSettings.primaryCore.ilmDamageSubstatRarity)
  const assist = ilmModuleSubstatBonusFromRarity(staticSettings.assistCore.ilmDamageSubstatRarity)
  const efficiency = clampPct(staticSettings.assistEffPct, 0) / 100
  return primary + assist * efficiency
}

export function computeIlmUwDamageMult(staticSettings: IlmCalcsStaticSettings): number {
  const base = computeInnerLandMinesDamageMult(staticSettings.damageLevel)
  return base + computeIlmDamageSubstatAdditive(staticSettings)
}

export function computeIlmUwModuleBonus(staticSettings: IlmCalcsStaticSettings): number {
  const mult = computeIlmDetonationModuleMult(staticSettings)
  return Math.max(0, mult - 1)
}

export function computeShockMultiplierFromLabLevel(level: number): number {
  const lab = getSharedToolLabs().find(entry => entry.name === SHOCK_MULTIPLIER_LAB_SLUG)
  if (!lab) return 1
  return Math.max(1, computeLabValueAtLevel(lab, Math.max(0, Math.floor(level))))
}

export function computeProtectorDamageReductionMult(labLevel: number): number {
  const lab = getSharedToolLabs().find(entry => entry.name === PROTECTOR_DAMAGE_REDUCTION_LAB_SLUG)
  if (!lab) return DEFAULT_PROTECTOR_DAMAGE_REDUCTION_MULT
  const benefit = computeLabValueAtLevel(lab, Math.max(0, Math.floor(labLevel)))
  return Math.min(1, Math.max(0, DEFAULT_PROTECTOR_DAMAGE_REDUCTION_MULT + benefit))
}

export function computeDimensionCoreMaxShockStack(
  dimensionCoreRarity: IlmUniqueModuleRarityChoice,
): number {
  if (!isDimensionCoreEquipped(dimensionCoreRarity)) return 0
  return computeIlmUniqueModuleRarityBonus(ILM_UNIQUE_MODULE_IDS.dimensionCore, dimensionCoreRarity)
}

export function computeEffectiveShockMultiplier(
  shockMultiplierLabLevel: number,
  dimensionCoreRarity: IlmUniqueModuleRarityChoice,
): number {
  const labMult = computeShockMultiplierFromLabLevel(shockMultiplierLabLevel)
  return isDimensionCoreEquipped(dimensionCoreRarity) ? labMult * 2 : labMult
}

export function computeAcpShockwaveMultiplier(
  acpRarity: IlmUniqueModuleRarityChoice,
): number {
  if (!isAcpEquipped(acpRarity)) return 0
  return computeIlmUniqueModuleRarityBonus(ILM_UNIQUE_MODULE_IDS.antiCubePortal, acpRarity)
}

export function buildEnemyHitMultiplierInput(
  staticSettings: IlmCalcsStaticSettings,
  scenario: IlmCalcsScenarioSettings,
): EnemyHitMultiplierInput {
  const dcMaxStack = computeDimensionCoreMaxShockStack(staticSettings.dimensionCoreRarity)
  const shockStack = scenario.enemyShocked
    ? (dcMaxStack > 0
      ? Math.min(dcMaxStack, Math.max(0, Math.floor(scenario.shockStack)))
      : Math.max(0, Math.floor(scenario.shockStack)))
    : 0

  const shActive = staticSettings.singularityHarnessEquipped && scenario.enemyFlameTagged

  const acpMult = scenario.acpShockwaveActive
    ? computeAcpShockwaveMultiplier(staticSettings.acpRarity)
    : 0

  return {
    chainLightningShock: scenario.enemyShocked
      ? {
        active: true,
        shockMultiplier: computeEffectiveShockMultiplier(
          staticSettings.shockMultiplierLabLevel,
          staticSettings.dimensionCoreRarity,
        ),
        shockStack,
      }
      : undefined,
    amplifyBot: scenario.amplifyBotOnEnemy
      ? {
        active: true,
        amplifyBonusMultiplier: computeAmplifyBotBonusMultiplier(
          staticSettings.amplifyBotBonusLevel,
        ),
      }
      : undefined,
    flameModuleDebuff: shActive ? { active: true } : undefined,
    shockwaveMultiplier: acpMult > 0 ? acpMult : undefined,
    protectorDamageReduction: scenario.protectorAuraActive
      ? computeProtectorDamageReductionMult(staticSettings.protectorReductionLabLevel)
      : undefined,
  }
}

export function getIlmHitMultiplierBreakdown(
  staticSettings: IlmCalcsStaticSettings,
  scenario: IlmCalcsScenarioSettings,
): IlmHitMultiplierBreakdown {
  const input = buildEnemyHitMultiplierInput(staticSettings, scenario)
  const effectiveShockLabMultiplier = computeEffectiveShockMultiplier(
    staticSettings.shockMultiplierLabLevel,
    staticSettings.dimensionCoreRarity,
  )
  const dcMaxStack = computeDimensionCoreMaxShockStack(staticSettings.dimensionCoreRarity)
  const shockStack = input.chainLightningShock?.active
    ? (input.chainLightningShock.shockStack ?? 0)
    : 0
  const shockMultiplier = input.chainLightningShock?.active
    ? chainLightningShockMultiplier(effectiveShockLabMultiplier, shockStack)
    : 1

  return {
    total: enemyHitMultiplier(input),
    shockMultiplier,
    shockStack,
    effectiveShockLabMultiplier,
    dimensionCoreDoublesShock: isDimensionCoreEquipped(staticSettings.dimensionCoreRarity),
    dimensionCoreMaxShockStack: dcMaxStack,
    amplifyBotMultiplier: scenario.amplifyBotOnEnemy
      ? computeAmplifyBotBonusMultiplier(staticSettings.amplifyBotBonusLevel)
      : 1,
    singularityHarnessActive: Boolean(input.flameModuleDebuff?.active),
    acpShockwaveMultiplier: input.shockwaveMultiplier ?? 0,
    protectorDamageReduction: input.protectorDamageReduction ?? 1,
  }
}

export function computeEnemyHitMultiplier(settings: IlmCalcsSettings): number {
  return enemyHitMultiplier(buildEnemyHitMultiplierInput(settings.static, settings.scenario))
}

export function buildIlmCalculatorInputFromSettings(
  settings: IlmCalcsSettings,
  waveTimeSeconds: number,
): IlmCalculatorInput {
  const hitMultiplier = computeEnemyHitMultiplier(settings)
  return {
    towerDamage: computeIlmTowerDamage(settings.static),
    ilmDamageMult: computeIlmUwDamageMult(settings.static),
    mineAgeSeconds: computeMineAgeSecondsFromWaves(
      settings.scenario.mineAgeWaves,
      waveTimeSeconds,
    ),
    chargedMinesLevel: settings.static.chargedMinesLevel,
    chronoJumpLabLevel: settings.static.chronoJumpLabLevel,
    timesHitByIlm: settings.scenario.timesHitByIlm,
    chargedMinesActive: settings.static.chargedMinesActive,
    moduleBonus: computeIlmUwModuleBonus(settings.static),
    hitMultiplier,
    ultimateCritDisplayFactor: 1,
  }
}

export function getIlmDamageChainBreakdown(
  settings: IlmCalcsSettings,
  waveTimeSeconds: number,
): IlmDamageChainBreakdown {
  const input = buildIlmCalculatorInputFromSettings(settings, waveTimeSeconds)
  const staticSettings = settings.static
  return {
    towerDamageBase: computeTowerDamageFromAttackLevel(staticSettings.attackDamageLevel),
    cannonModuleMult: computeIlmCannonModuleMult(staticSettings),
    towerDamage: input.towerDamage,
    uwDamageMultBase: computeInnerLandMinesDamageMult(staticSettings.damageLevel),
    uwDamageSubstatAdditive: computeIlmDamageSubstatAdditive(staticSettings),
    uwDamageMult: input.ilmDamageMult,
    coreModuleMult: computeIlmDetonationModuleMult(staticSettings),
    charge: 1,
    hitMultiplier: input.hitMultiplier ?? 1,
  }
}

export function computeIlmCoreModuleCombinedMult(staticSettings: IlmCalcsStaticSettings): number {
  return computeIlmDetonationModuleMult(staticSettings)
}

export function computeIlmDamageSubstatBonus(staticSettings: IlmCalcsStaticSettings): number {
  return computeIlmDamageSubstatAdditive(staticSettings)
}

// Back-compat: callers pass full static settings
export function computeDimensionCoreMaxShockStackFromSettings(
  staticSettings: IlmCalcsStaticSettings,
): number {
  return computeDimensionCoreMaxShockStack(staticSettings.dimensionCoreRarity)
}

export function computeEffectiveShockMultiplierFromSettings(
  shockMultiplierLabLevel: number,
  staticSettings: IlmCalcsStaticSettings,
): number {
  return computeEffectiveShockMultiplier(shockMultiplierLabLevel, staticSettings.dimensionCoreRarity)
}

export function computeAcpShockwaveMultiplierFromSettings(
  staticSettings: IlmCalcsStaticSettings,
): number {
  return computeAcpShockwaveMultiplier(staticSettings.acpRarity)
}
