/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    SHOCK_MULTIPLIER_LAB_SLUG, PROTECTOR_DAMAGE_REDUCTION_LAB_SLUG, DEFAULT_PROTECTOR_DAMAGE_REDUCTION_MULT, WORKSHOP_ATTACK_DAMAGE_STAT_KEY, ILM_WEAPON_INDEX, ILM_CHARGE_INITIAL, ILM_COOLDOWN_FLOOR_SEC, ILM_MINE_LIFETIME_SEC (+33 more)
 * depends    src/data/index, src/internal/game-input-data/workshop-stat-dropdown-math, src/mechanics/assist-module-efficiency, src/mechanics/ilm-calculator-options, src/mechanics/ultimates
 * used by    src/mechanics/calculators/run, src/mechanics/calculators/specs-generated, src/mechanics/ilm-calculator-resolve, src/mechanics/index
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
import { clampAssistMultiplierEfficiencyPct } from './assist-module-efficiency'
import { computeLabValueAtLevel, getSharedToolLabs } from '../data/index'
import { computeWorkshopStatNumericValueAtLevel } from '../internal/game-input-data/workshop-stat-dropdown-math'
import { uwStoneChartData } from '../data/index'
import { ultimateModuleMultiplier } from './ultimates'
import {
  ILM_MODULE_SUBSTAT_NONE,
  ILM_UNIQUE_MODULE_IDS,
  type IlmModuleSubstatRarityChoice,
  type IlmUniqueModuleRarityChoice,
} from './ilm-calculator-options'

export const SHOCK_MULTIPLIER_LAB_SLUG = 'shock_multiplier'
export const PROTECTOR_DAMAGE_REDUCTION_LAB_SLUG = 'protector_damage_reduction'
export const DEFAULT_PROTECTOR_DAMAGE_REDUCTION_MULT = 0.55
export const WORKSHOP_ATTACK_DAMAGE_STAT_KEY = 'Damage'

export const ILM_WEAPON_INDEX = 4
export const ILM_CHARGE_INITIAL = 1
export const ILM_COOLDOWN_FLOOR_SEC = 37
export const ILM_MINE_LIFETIME_SEC = 25
export const INNER_LAND_MINE_CHRONO_JUMP_LAB_SLUG = 'inner_land_mine_chrono_jump'

/** Charged Mines UW+ rate table (/s per level), parity `uw-stone-chart-data`. */
export const CHARGED_MINES_RATE_PER_SECOND: readonly number[] = [
  0.5, 1.5, 2.9, 4.7, 6.9, 9.5, 12.5, 15.9, 19.7, 23.9, 28.5, 33.5, 38.9, 44.7, 50.9,
] as const

export type InnerLandMinesUwStatName = 'Damage' | 'Quantity' | 'Cooldown' | 'Charged Mines'

export function parseUwDisplayMultiplier(raw: string | number): number {
  if (typeof raw === 'number') return Number.isFinite(raw) ? raw : 0
  const parsed = Number.parseFloat(String(raw).replace(/[^\d.]/g, ''))
  return Number.isFinite(parsed) ? parsed : 0
}

export function parseUwCooldownSeconds(raw: string | number): number {
  if (typeof raw === 'number') return Number.isFinite(raw) ? raw : 0
  const parsed = Number.parseFloat(String(raw).replace(/[^\d.]/g, ''))
  return Number.isFinite(parsed) ? parsed : 0
}

function innerLandMinesStatRow(stat: InnerLandMinesUwStatName, level: number) {
  const weapon = uwStoneChartData.inner_land_mines
  const statEntry = weapon?.stats.find(entry => entry.name === stat)
  return statEntry?.levels.find(entry => entry.level === level) ?? null
}

export function computeInnerLandMinesDamageMult(level: number): number {
  const row = innerLandMinesStatRow('Damage', level)
  return row ? parseUwDisplayMultiplier(row.value) : 0
}

export function computeInnerLandMinesQuantity(level: number): number {
  const row = innerLandMinesStatRow('Quantity', level)
  return row ? parseUwDisplayMultiplier(row.value) : 0
}

export function computeInnerLandMinesCooldownSeconds(level: number): number {
  const row = innerLandMinesStatRow('Cooldown', level)
  const raw = row ? parseUwCooldownSeconds(row.value) : 0
  if (raw <= 0) return raw
  return Math.max(ILM_COOLDOWN_FLOOR_SEC, raw)
}

export function computeChargedMinesRatePerSecond(level: number): number {
  const clamped = Math.max(0, Math.min(CHARGED_MINES_RATE_PER_SECOND.length - 1, Math.floor(level)))
  return CHARGED_MINES_RATE_PER_SECOND[clamped] ?? 0
}

export function computeChronoJumpLabBenefit(level: number): number {
  const lab = getSharedToolLabs().find(entry => entry.name === INNER_LAND_MINE_CHRONO_JUMP_LAB_SLUG)
  if (!lab || level <= 0) return 0
  return computeLabValueAtLevel(lab, level)
}

export interface IlmChargeInput {
  mineAgeSeconds: number
  chargedMinesLevel: number
  chronoJumpLabLevel: number
  timesHitByIlm: number
  /** ILM+ unlocked and active — Chrono Jump and charge tick require this. */
  chargedMinesActive: boolean
}

export interface IlmChargeBreakdown {
  charge: number
  chargedGrowth: number
  chronoGrowth: number
  chargedRatePerSecond: number
  chronoJumpLabBenefit: number
}

export function computeIlmChargeMultiplier(input: IlmChargeInput): IlmChargeBreakdown {
  const age = Math.max(0, input.mineAgeSeconds)
  const rate = input.chargedMinesActive
    ? computeChargedMinesRatePerSecond(input.chargedMinesLevel)
    : 0
  const chargedGrowth = rate * age

  let chronoGrowth = 0
  const chronoBenefit = computeChronoJumpLabBenefit(input.chronoJumpLabLevel)
  const hits = Math.max(0, Math.floor(input.timesHitByIlm))
  if (input.chargedMinesActive && input.chronoJumpLabLevel > 0 && hits > 0 && rate > 0) {
    chronoGrowth = chronoBenefit * rate * hits
  }

  return {
    charge: ILM_CHARGE_INITIAL + chargedGrowth + chronoGrowth,
    chargedGrowth,
    chronoGrowth,
    chargedRatePerSecond: rate,
    chronoJumpLabBenefit: chronoBenefit,
  }
}

export interface IlmHitDamageInput {
  towerDamage: number
  ilmDamageMult: number
  charge: number
  /** Module UW bonus (not including the +1). */
  moduleBonus?: number
  hitMultiplier?: number
  /**
   * Workshop UW screen crit factor (Ultimate Crit card + mastery baked).
   * Defaults to 1 when omitted.
   */
  ultimateCritDisplayFactor?: number
}

export interface IlmHitDamageBreakdown {
  hitDamage: number
  towerDamage: number
  ilmDamageMult: number
  moduleMult: number
  charge: number
  hitMultiplier: number
  ultimateCritDisplayFactor: number
}

export function computeIlmHitDamage(input: IlmHitDamageInput): IlmHitDamageBreakdown {
  const towerDamage = Math.max(0, input.towerDamage)
  const ilmDamageMult = Math.max(0, input.ilmDamageMult)
  const charge = Math.max(0, input.charge)
  const moduleMult = ultimateModuleMultiplier(input.moduleBonus ?? 0)
  const hitMultiplier = Math.max(0, input.hitMultiplier ?? 1)
  const ultimateCritDisplayFactor = Math.max(0, input.ultimateCritDisplayFactor ?? 1)

  const hitDamage = towerDamage
    * ilmDamageMult
    * moduleMult
    * charge
    * hitMultiplier
    * ultimateCritDisplayFactor

  return {
    hitDamage,
    towerDamage,
    ilmDamageMult,
    moduleMult,
    charge,
    hitMultiplier,
    ultimateCritDisplayFactor,
  }
}

export interface IlmCalculatorInput extends IlmChargeInput, Omit<IlmHitDamageInput, 'charge'> {}

export interface IlmCalculatorResult {
  charge: IlmChargeBreakdown
  hit: IlmHitDamageBreakdown
}

export function computeIlmCalculatorResult(input: IlmCalculatorInput): IlmCalculatorResult {
  const charge = computeIlmChargeMultiplier(input)
  const hit = computeIlmHitDamage({ ...input, charge: charge.charge })
  return { charge, hit }
}

export interface IlmModuleLevelRarity {
  rarity: string
  level: number
}

export interface IlmCoreModuleLevelRarity extends IlmModuleLevelRarity {
  ilmDamageSubstatRarity: IlmModuleSubstatRarityChoice
}

export interface IlmCalcsStaticSettings {
  attackDamageLevel: number
  primaryCannon: IlmModuleLevelRarity
  assistCannon: IlmModuleLevelRarity
  primaryCore: IlmCoreModuleLevelRarity
  assistCore: IlmCoreModuleLevelRarity
  assistEffPct: number
  dimensionCoreRarity: IlmUniqueModuleRarityChoice
  acpRarity: IlmUniqueModuleRarityChoice
  singularityHarnessEquipped: boolean
  damageLevel: number
  quantityLevel: number
  cooldownLevel: number
  chargedMinesLevel: number
  chronoJumpLabLevel: number
  chargedMinesActive: boolean
  shockMultiplierLabLevel: number
  protectorReductionLabLevel: number
  amplifyBotBonusLevel: number
}

export interface IlmCalcsScenarioSettings {
  mineAgeWaves: number
  timesHitByIlm: number
  enemyShocked: boolean
  shockStack: number
  enemyFlameTagged: boolean
  amplifyBotOnEnemy: boolean
  acpShockwaveActive: boolean
  protectorAuraActive: boolean
}

export interface IlmCalcsSettings {
  static: IlmCalcsStaticSettings
  scenario: IlmCalcsScenarioSettings
}

function defaultModuleLevelRarity(): IlmModuleLevelRarity {
  return { rarity: 'Common', level: 1 }
}

function defaultCoreModuleLevelRarity(): IlmCoreModuleLevelRarity {
  return {
    rarity: 'Common',
    level: 1,
    ilmDamageSubstatRarity: ILM_MODULE_SUBSTAT_NONE,
  }
}

export function defaultIlmCalcsStaticSettings(): IlmCalcsStaticSettings {
  return {
    attackDamageLevel: 1,
    primaryCannon: defaultModuleLevelRarity(),
    assistCannon: defaultModuleLevelRarity(),
    primaryCore: defaultCoreModuleLevelRarity(),
    assistCore: defaultCoreModuleLevelRarity(),
    assistEffPct: 0,
    dimensionCoreRarity: ILM_MODULE_SUBSTAT_NONE,
    acpRarity: ILM_MODULE_SUBSTAT_NONE,
    singularityHarnessEquipped: false,
    damageLevel: 0,
    quantityLevel: 0,
    cooldownLevel: 0,
    chargedMinesLevel: 0,
    chronoJumpLabLevel: 0,
    chargedMinesActive: true,
    shockMultiplierLabLevel: 0,
    protectorReductionLabLevel: 0,
    amplifyBotBonusLevel: 0,
  }
}

export function defaultIlmCalcsScenarioSettings(): IlmCalcsScenarioSettings {
  return {
    mineAgeWaves: 1,
    timesHitByIlm: 1,
    enemyShocked: false,
    shockStack: 0,
    enemyFlameTagged: false,
    amplifyBotOnEnemy: false,
    acpShockwaveActive: false,
    protectorAuraActive: false,
  }
}

export function defaultIlmCalcsSettings(): IlmCalcsSettings {
  return {
    static: defaultIlmCalcsStaticSettings(),
    scenario: defaultIlmCalcsScenarioSettings(),
  }
}

export function computeTowerDamageFromAttackLevel(level: number): number {
  return Math.max(0, computeWorkshopStatNumericValueAtLevel(WORKSHOP_ATTACK_DAMAGE_STAT_KEY, level))
}

export function computeMineAgeSecondsFromWaves(mineAgeWaves: number, waveTimeSeconds: number): number {
  const waves = Math.max(0, Number(mineAgeWaves) || 0)
  const waveTime = Math.max(0, Number(waveTimeSeconds) || 0)
  return waves * waveTime
}

function normalizeUniqueModuleRarity(
  value: unknown,
  fallback: IlmUniqueModuleRarityChoice,
): IlmUniqueModuleRarityChoice {
  if (value === ILM_MODULE_SUBSTAT_NONE) return ILM_MODULE_SUBSTAT_NONE
  if (value === 'Epic' || value === 'Legendary' || value === 'Mythic' || value === 'Ancestral') {
    return value
  }
  if (typeof value === 'string' && value.startsWith('Ancestral')) return 'Ancestral'
  return fallback
}

function normalizeModuleLevelRarity(
  input: Partial<IlmModuleLevelRarity> | null | undefined,
  fallback: IlmModuleLevelRarity,
): IlmModuleLevelRarity {
  const src = input ?? {}
  return {
    rarity: String(src.rarity ?? fallback.rarity),
    level: Math.max(1, Math.floor(Number(src.level) || fallback.level)),
  }
}

function normalizeCoreModuleLevelRarity(
  input: Partial<IlmCoreModuleLevelRarity> | null | undefined,
  fallback: IlmCoreModuleLevelRarity,
): IlmCoreModuleLevelRarity {
  const base = normalizeModuleLevelRarity(input, fallback)
  const src = input ?? {}
  return {
    ...base,
    ilmDamageSubstatRarity: (src.ilmDamageSubstatRarity
      ?? fallback.ilmDamageSubstatRarity) as IlmModuleSubstatRarityChoice,
  }
}

function clampPct(value: unknown, fallback: number): number {
  const n = Math.floor(Number(value))
  if (!Number.isFinite(n)) return fallback
  return clampAssistMultiplierEfficiencyPct(n)
}

function normalizeStaticSettings(
  input: Partial<IlmCalcsStaticSettings> | null | undefined,
  fallback: IlmCalcsStaticSettings,
): IlmCalcsStaticSettings {
  const src = (input ?? {}) as Partial<IlmCalcsStaticSettings> & Record<string, unknown>
  let dimensionCoreRarity = normalizeUniqueModuleRarity(
    src.dimensionCoreRarity,
    fallback.dimensionCoreRarity,
  )
  let acpRarity = normalizeUniqueModuleRarity(src.acpRarity, fallback.acpRarity)
  let singularityHarnessEquipped = src.singularityHarnessEquipped ?? fallback.singularityHarnessEquipped

  const primaryCoreRaw = (src.primaryCore ?? {}) as Record<string, unknown>
  if (primaryCoreRaw.templateId === ILM_UNIQUE_MODULE_IDS.dimensionCore) {
    dimensionCoreRarity = normalizeUniqueModuleRarity(primaryCoreRaw.rarity, dimensionCoreRarity)
  }
  const armorModule = src.armorModule as { templateId?: string; rarity?: string } | undefined
  if (armorModule?.templateId === ILM_UNIQUE_MODULE_IDS.antiCubePortal) {
    acpRarity = normalizeUniqueModuleRarity(armorModule.rarity, acpRarity)
  }
  const generatorModule = src.generatorModule as { templateId?: string } | undefined
  if (generatorModule?.templateId === ILM_UNIQUE_MODULE_IDS.singularityHarness) {
    singularityHarnessEquipped = true
  }

  const dcLegacy = src.dimensionCore as { equipped?: boolean; rarity?: string } | undefined
  if (dcLegacy?.equipped) {
    dimensionCoreRarity = normalizeUniqueModuleRarity(dcLegacy.rarity, 'Epic')
  }
  const acpLegacy = src.antiCubePortal as { equipped?: boolean; rarity?: string } | undefined
  if (acpLegacy?.equipped) {
    acpRarity = normalizeUniqueModuleRarity(acpLegacy.rarity, 'Epic')
  }
  const shLegacy = src.singularityHarness as { equipped?: boolean } | undefined
  if (shLegacy?.equipped) singularityHarnessEquipped = true

  return {
    attackDamageLevel: Math.max(1, clampLevel(src.attackDamageLevel, fallback.attackDamageLevel, 99999)),
    primaryCannon: normalizeModuleLevelRarity(
      src.primaryCannon as Partial<IlmModuleLevelRarity> | undefined,
      fallback.primaryCannon,
    ),
    assistCannon: normalizeModuleLevelRarity(
      src.assistCannon as Partial<IlmModuleLevelRarity> | undefined,
      fallback.assistCannon,
    ),
    primaryCore: normalizeCoreModuleLevelRarity(
      primaryCoreRaw as Partial<IlmCoreModuleLevelRarity>,
      fallback.primaryCore,
    ),
    assistCore: normalizeCoreModuleLevelRarity(
      src.assistCore as Partial<IlmCoreModuleLevelRarity> | undefined,
      fallback.assistCore,
    ),
    assistEffPct: clampPct(src.assistEffPct, fallback.assistEffPct),
    dimensionCoreRarity,
    acpRarity,
    singularityHarnessEquipped: Boolean(singularityHarnessEquipped),
    damageLevel: clampLevel(src.damageLevel, fallback.damageLevel, 30),
    quantityLevel: clampLevel(src.quantityLevel, fallback.quantityLevel, 3),
    cooldownLevel: clampLevel(src.cooldownLevel, fallback.cooldownLevel, 15),
    chargedMinesLevel: clampLevel(src.chargedMinesLevel, fallback.chargedMinesLevel, 14),
    chronoJumpLabLevel: clampLevel(src.chronoJumpLabLevel, fallback.chronoJumpLabLevel, 10),
    chargedMinesActive: src.chargedMinesActive ?? fallback.chargedMinesActive,
    shockMultiplierLabLevel: clampLevel(src.shockMultiplierLabLevel, fallback.shockMultiplierLabLevel, 30),
    protectorReductionLabLevel: clampLevel(
      src.protectorReductionLabLevel,
      fallback.protectorReductionLabLevel,
      20,
    ),
    amplifyBotBonusLevel: clampLevel(src.amplifyBotBonusLevel, fallback.amplifyBotBonusLevel, 30),
  }
}

function normalizeScenarioSettings(
  input: Partial<IlmCalcsScenarioSettings> | null | undefined,
  fallback: IlmCalcsScenarioSettings,
  legacyMineAgeWaves?: number,
): IlmCalcsScenarioSettings {
  const src = input ?? {}
  const mineAgeWaves = src.mineAgeWaves != null
    ? clampNonNegative(src.mineAgeWaves, fallback.mineAgeWaves)
    : (legacyMineAgeWaves ?? fallback.mineAgeWaves)

  return {
    mineAgeWaves,
    timesHitByIlm: clampLevel(src.timesHitByIlm, fallback.timesHitByIlm, 999999),
    enemyShocked: src.enemyShocked ?? fallback.enemyShocked,
    shockStack: clampLevel(src.shockStack, fallback.shockStack, 999),
    enemyFlameTagged: src.enemyFlameTagged ?? fallback.enemyFlameTagged,
    amplifyBotOnEnemy: src.amplifyBotOnEnemy ?? fallback.amplifyBotOnEnemy,
    acpShockwaveActive: src.acpShockwaveActive ?? fallback.acpShockwaveActive,
    protectorAuraActive: src.protectorAuraActive ?? fallback.protectorAuraActive,
  }
}

function migrateLegacyStaticSettings(
  legacy: Record<string, unknown>,
  fallback: IlmCalcsStaticSettings,
): IlmCalcsStaticSettings {
  const coreUw = legacy.coreUwModule as Record<string, unknown> | undefined
  return normalizeStaticSettings({
    attackDamageLevel: legacy.attackDamageLevel as number | undefined,
    damageLevel: legacy.damageLevel as number | undefined,
    quantityLevel: legacy.quantityLevel as number | undefined,
    cooldownLevel: legacy.cooldownLevel as number | undefined,
    chargedMinesLevel: legacy.chargedMinesLevel as number | undefined,
    chronoJumpLabLevel: legacy.chronoJumpLabLevel as number | undefined,
    chargedMinesActive: legacy.chargedMinesActive as boolean | undefined,
    primaryCore: {
      rarity: coreUw?.primaryRarity,
      level: coreUw?.primaryLevel,
      ilmDamageSubstatRarity: coreUw?.primaryIlmDamageSubstatRarity,
    } as unknown as IlmCalcsStaticSettings['primaryCore'],
    assistCore: {
      rarity: coreUw?.assistRarity,
      level: coreUw?.assistLevel,
      ilmDamageSubstatRarity: coreUw?.assistIlmDamageSubstatRarity,
    } as unknown as IlmCalcsStaticSettings['assistCore'],
    assistEffPct: coreUw?.assistEffPct as number | undefined,
    antiCubePortal: legacy.antiCubePortal,
    singularityHarness: legacy.singularityHarness,
    armorModule: legacy.armorModule,
    generatorModule: legacy.generatorModule,
    shockMultiplierLabLevel: legacy.shockMultiplierLabLevel as number | undefined,
    protectorReductionLabLevel: legacy.protectorReductionLabLevel as number | undefined,
    amplifyBotBonusLevel: legacy.amplifyBotBonusLevel as number | undefined,
  } as unknown as Partial<IlmCalcsStaticSettings>, fallback)
}

function isLegacyStaticShape(input: Record<string, unknown>): boolean {
  return input.coreUwModule != null
}

function clampLevel(value: unknown, fallback: number, max: number): number {
  const n = Math.floor(Number(value))
  if (!Number.isFinite(n)) return fallback
  return Math.max(0, Math.min(max, n))
}

function clampNonNegative(value: unknown, fallback: number): number {
  const n = Number(value)
  if (!Number.isFinite(n)) return fallback
  return Math.max(0, n)
}

export function normalizeIlmCalcsSettings(
  input: Partial<IlmCalcsSettings> | null | undefined,
  fallback: IlmCalcsSettings = defaultIlmCalcsSettings(),
): IlmCalcsSettings {
  const src = (input ?? {}) as Partial<IlmCalcsSettings> & Record<string, unknown>

  if (src.static || src.scenario) {
    const staticSrc = (src.static ?? {}) as Partial<IlmCalcsStaticSettings> & Record<string, unknown>
    const staticSettings = isLegacyStaticShape(staticSrc)
      ? migrateLegacyStaticSettings(staticSrc, fallback.static)
      : normalizeStaticSettings(staticSrc, fallback.static)
    return {
      static: staticSettings,
      scenario: normalizeScenarioSettings(src.scenario, fallback.scenario),
    }
  }

  if (isLegacyStaticShape(src) || src.mineAgeWaves != null || src.shockActive != null) {
    let mineAgeWaves = Number(src.mineAgeWaves)
    if (!Number.isFinite(mineAgeWaves) && src.mineAgeSeconds != null) {
      mineAgeWaves = Math.round(Number(src.mineAgeSeconds) / 30)
    }
    return {
      static: migrateLegacyStaticSettings(src, fallback.static),
      scenario: normalizeScenarioSettings({
        mineAgeWaves: Number.isFinite(mineAgeWaves) ? mineAgeWaves : undefined,
        timesHitByIlm: src.timesHitByIlm as number | undefined,
        enemyShocked: src.shockActive as boolean | undefined,
        shockStack: src.shockStack as number | undefined,
        enemyFlameTagged: src.enemyFlameTagged as boolean | undefined
          ?? (src.singularityHarness as boolean | undefined),
        amplifyBotOnEnemy: src.amplifyBotActive as boolean | undefined,
        acpShockwaveActive: src.acpActive as boolean | undefined,
        protectorAuraActive: src.protectorActive as boolean | undefined,
      }, fallback.scenario),
    }
  }

  return fallback
}

export interface IlmCalcsLocalState {
  settings: IlmCalcsSettings
}

export function normalizeIlmCalcsLocalState(
  input: Partial<IlmCalcsLocalState> | null | undefined,
  fallback: IlmCalcsLocalState = { settings: defaultIlmCalcsSettings() },
): IlmCalcsLocalState {
  const settings = normalizeIlmCalcsSettings(
    (input?.settings ?? input) as Partial<IlmCalcsSettings>,
    fallback.settings,
  )
  return { settings }
}

export function patchIlmCalcsSettings(
  current: IlmCalcsSettings,
  patch: Partial<IlmCalcsSettings> & {
    static?: Partial<IlmCalcsStaticSettings>
    scenario?: Partial<IlmCalcsScenarioSettings>
  },
): IlmCalcsSettings {
  return normalizeIlmCalcsSettings({
    static: { ...current.static, ...patch.static },
    scenario: { ...current.scenario, ...patch.scenario },
  }, current)
}
