/**
 * Impetus damage multiplier — `BonusDamageFromImpetus`.
 *
 * ## Base formula
 *
 *   damageMultiplier =
 *     impetus × 0.01 × distanceMeters × extraMultiplier × distanceMultiplier + 1.0
 *
 * - `impetus` = raw impetus stat (the UI shows it ÷100, as ×/m)
 * - `distanceMeters` = **display meters** at call site (not internal dm field)
 * - `extraMultiplier` = card/module context factor
 * - `distanceMultiplier` = secondary distance scaling (often 1.0)
 *
 * ## Distance tier table (internal dm before caller conversion)
 *
 * Piecewise linear segments on distance `d` (internal dm; ×10 = display meters):
 *
 * | d (internal) | Tier base |
 * |--------------|-----------|
 * | d ≤ 20       | 0.01 × d |
 * | 21–30        | (d − 20) × 0.015 + 0.20 |
 * | 31–40        | (d − 30) × 0.02 + 0.35 |
 * | 41–80        | (d − 40) × 0.025 + 0.55 |
 * | 81–100       | (d − 80) × 0.05 + 1.65 |
 * | 101–120      | (d − 100) × 0.08 + 2.65 |
 * | 121–140      | (d − 120) × 0.12 + 4.25 |
 * | 141–160      | (d − 140) × 0.15 + 6.65 |
 * | d > 160      | quadratic tail |
 *
 * ## Impetus stat tier multiplier
 *
 *   if impetus ≥ 11:
 *     damageMultiplier ×= IMPETUS_STAT_TIER_MULT[impetus − 11]
 */
/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    IMPETUS_STAT_TIER_MULT, ImpetusDamageInput, impetusDistanceTierBase, impetusStatTierMultiplier, bonusDamageFromImpetus, bonusDamageFromImpetusWithTiers
 * depends    src/mechanics/constants
 * used by    src/mechanics/calculators/specs-generated, src/mechanics/index, src/mechanics/projectile-damage
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */

import { IMPETUS_DISTANCE_SCALE, IMPETUS_STAT_TIER_START } from './constants'

/** Extra multiplier when impetus stat ≥ 11 + index. Index 0 = impetus 11. */
export const IMPETUS_STAT_TIER_MULT = [1.04, 1.08, 1.12, 1.16, 1.20] as const

export interface ImpetusDamageInput {
  impetus: number
  /** Display meters passed into BonusDamageFromImpetus at runtime. */
  distanceMeters: number
  extraMultiplier?: number
  distanceMultiplier?: number
}

export function impetusDistanceTierBase(distanceInternal: number): number {
  const d = distanceInternal
  if (d <= 20) return 0.01 * d
  if (d <= 30) return (d - 20) * 0.015 + 0.20
  if (d <= 40) return (d - 30) * 0.02 + 0.35
  if (d <= 80) return (d - 40) * 0.025 + 0.55
  if (d <= 100) return (d - 80) * 0.05 + 1.65
  if (d <= 120) return (d - 100) * 0.08 + 2.65
  if (d <= 140) return (d - 120) * 0.12 + 4.25
  if (d <= 160) return (d - 140) * 0.15 + 6.65
  // Quadratic tail for very long range
  return ((d - 160) ** 2 / 4) * 9.65
}

export function impetusStatTierMultiplier(impetusTierLevel: number): number {
  if (impetusTierLevel < IMPETUS_STAT_TIER_START) return 1
  const idx = Math.min(
    impetusTierLevel - IMPETUS_STAT_TIER_START,
    IMPETUS_STAT_TIER_MULT.length - 1,
  )
  return IMPETUS_STAT_TIER_MULT[idx] ?? 1
}

/** Primary runtime formula (simple path). */
export function bonusDamageFromImpetus(input: ImpetusDamageInput): number {
  const extra = input.extraMultiplier ?? 1
  const distMult = input.distanceMultiplier ?? 1
  return input.impetus * IMPETUS_DISTANCE_SCALE * input.distanceMeters * extra * distMult + 1
}

/** Full dispatcher path — applies stat tier level (11–15) after base mult. */
export function bonusDamageFromImpetusWithTiers(
  input: ImpetusDamageInput & { impetusTierLevel?: number },
): number {
  let mult = bonusDamageFromImpetus(input)
  if (input.impetusTierLevel != null) {
    mult *= impetusStatTierMultiplier(input.impetusTierLevel)
  }
  return mult
}
