/**
 * Game formulas.
 *
 * These model how the game behaves rather than reading stored values. Many are
 * **approximations** fitted to observed behaviour — close, but not exact,
 * especially at very high waves and tiers. Don't use them where you need to
 * match the game to the last digit.
 *
 * @example
 * import { computeWaveBaseHealth, abilityDamage } from 'thetowersdk/mechanics'
 *
 * const hp = computeWaveBaseHealth({ tier: 10, wave: 4200, tournament: false })
 */

export * from './battle-condition-config'
export * from './battle-conditions'
export * from './bc-counter-labs'
export * from './bonuses'
export * from './bot-bot-overlap'
export * from './bot-coin-bonus'
export * from './bot-get-benefit'
export * from './bot-hit-multiplier'
export * from './bot-medal-hit-signal'
export * from './bot-medal-planner-insights'
export * from './bot-medal-planner-scoring'
export * from './bot-medal-plus-effects'
export * from './bot-medal-simulation'
export * from './bot-medal-sync-scoring'
export * from './bot-movement'
export * from './bots'
export * from './card-effect-lookup'
export * from './chrono-field'
export * from './constants'
export * from './crowd-control'
export * from './damage'
export * from './damage-reduction'
export * from './damage-redux-calculator'
export * from './damage-redux-constants'
export * from './damage-redux-layers'
export * from './damage-redux-wave-stats'
export * from './distances'
export * from './effective-paths-coin-costs'
export * from './effective-paths-credits'
export * from './effective-paths-currencies'
export * from './effective-paths-aliases'
export * from './effective-paths-assist-efficiency'
export * from './effective-paths-edamage-candidates'
export * from './effective-paths-edamage-costs'
export * from './effective-paths-edamage-levels'
export * from './effective-paths-edamage-model'
export * from './effective-paths-ehp-model'
export * from './effective-paths-enhancement-costs'
export * from './effective-paths-ehp-plan'
export * from './effective-paths-formula'
export * from './effective-paths-damage-base'
export * from './effective-paths-damage-stats'
export * from './effective-paths-damage-substats'
export * from './effective-paths-generics'
export * from './effective-paths-hp'
export * from './effective-paths-ultimate-weapons'
export * from './effective-paths-regen-plan'
export * from './effective-paths-lab-costs'
export * from './effective-paths-planner'
export * from './effective-paths-schema'
export * from './effective-paths-stone-costs'
export * from './effective-paths-workbook'
export * from './effective-paths-workshop-values'
export * from './elite-spawn-chance'
export * from './els-module-cluster'
export * from './els-upgrade-path'
export * from './enemy-drops-context'
export * from './enemy-drops-game-data'
export * from './enemy-drops-simulation'
export * from './enemy-level-skip'
export * from './enemy-overcharge-hit-scaling'
export * from './enemy-stat-display'
export * from './enemy-stats-simplified'
export * from './enemy-type-mults'
export * from './enemy-wave-info-labs'
export * from './enemy-wave-info-pipeline'
export * from './enemy-wave-stats'
export * from './get-resistance-level'
export * from './guardians'
export * from './heat-bc-index-native'
export * from './ilm-calculator-resolve'
export * from './ilm-charge'
export * from './impetus'
export * from './knockback'
export * from './lab-research'
export * from './lab-workshop-calculations'
export * from './lab-workshop-constants'
export * from './land-mines'
export * from './math'
export * from './multishot-bounce'
export * from './poison-swamp'
export * from './projectile-damage'
export * from './rend-armor'
export * from './resource-drops-coin-context'
export * from './resource-drops-coin-fetch'
export * from './resource-drops-coin-generator-modules'
export * from './resource-drops-coin-iap'
export * from './resource-drops-coin-intro-sprint'
export * from './resource-drops-coin-module-cpk'
export * from './resource-drops-coin-perks'
export * from './resource-drops-coin-simulation'
export * from './resource-drops-coin-trade-off'
export * from './shockwave'
export * from './thorns'
export * from './tournament-heat-bc'
export * from './tower-fire'
export * from './tower-range'
export * from './ultimates'
export * from './units'
export * from './wave-accelerator-spawn-rate-cap'
export * from './wave-base-empirical-scaling'
export * from './wave-base-scaling'
export * from './wave-info-enemy-constants'
export * from './wave-info-enemy-stats'
export * from './wave-info-panel-constants'
export * from './wave-info-panel-stats'
export * from './wave-info-panel-timing'
export * from './wave-scaling-regression-profile'
export * from './wave-skip'
export * from './wildfire'
export * from './workshop-attack-stats'
export * from './workshop-defense-stats'
export * from './workshop-stats'
export * from './workshop-table-build'
export * from './workshop-utility-stats'
export * from './bot-medal-planner-types'
export * from './coverage'
export * from './els-calculator-options'
export * from './ilm-calculator-options'
export * from './effective-paths-uw-dps'
export * from './effective-paths-edamage-config'
export * from './effective-paths-edamage-compute'
export * from './effective-paths-edamage-plan'
