/**
 * Game formulas.
 *
 * These model how the game behaves rather than reading stored values. Many are
 * **approximations** fitted to observed behaviour — close, but not exact,
 * especially at very high waves and tiers. Don't use them where you need to
 * match the game to the last digit.
 *
 * @example
 * import { computeWaveBaseHealth, abilityDamage } from 'thetowersdk/mechanics'
 *
 * const hp = computeWaveBaseHealth({ tier: 10, wave: 4200, tournament: false })
 */
/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    —
 * depends    src/mechanics/battle-conditions, src/mechanics/bots, src/mechanics/calculators, src/mechanics/calculators/types, src/mechanics/cards, src/mechanics/combat (+18 more)
 * used by    —
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */

export * from './modules'
export * from './planning/roi-scaling'
export * from './primitives/unity-random'
export * from './uptime/compute'
export * from './combat'
export * from './battle-conditions'
export * from './labs'
export * from './combat/bonuses'
export * from './bots'
export * from './cards'
export * from './primitives/constants'
export * from './effective-paths'
export * from './enemies'
export * from './ep-controls'
export * from './guardians/compute'
export * from './workshop'
export * from './primitives/math'
export * from './resource-drops'
export * from './primitives/units'
export * from './waves'
export * from './planning/formula-coverage'
// Browser-safe public barrel ends here.
// Node/AGS surfaces (coverage, debug-graph, ep-graph, mcp-contract, planner-engine,
// repo-root, save-graph, sdk-graph, builders, doctor, kernel, …) import via
// packages/sdk/src/mechanics/<path> — they must not be export* from this file or
// Vite/CJS loads node:fs into the browser and blanks the showcase site.
export * from './perks/benefit'
/*
 * TYPES ONLY. `./calculators` re-exports `specs-generated.ts`, which is
 * generated to declare the SDK's whole exported surface for coverage -- and
 * that surface includes the doctor modules, which import `node:fs` and tooling that is
 * not part of the published package.
 *
 * So `export * from './calculators'` dragged Node-only code into the browser
 * barrel, in breach of the contract stated a few lines above. That tooling ships
 * CommonJS, browser ESM cannot named-import from it, and the route chunk that reached
 * it died with "does not provide an export named ..." -- taking every calculator page
 * with it.
 *
 * `calculators/types.ts` has no imports at all, so this keeps `CalculatorSpec`
 * -- the only thing the app uses -- without the chain. Runtime calculator
 * surfaces are Node/AGS and import via `thetowersdk/mechanics/calculators`,
 * exactly like the other Node surfaces listed above.
 */
export * from './calculators/types'
