/**
 * Game formulas.
 *
 * These model how the game behaves rather than reading stored values. Many are
 * **approximations** fitted to observed behaviour — close, but not exact,
 * especially at very high waves and tiers. Don't use them where you need to
 * match the game to the last digit.
 *
 * @example
 * import { computeWaveBaseHealth, abilityDamage } from 'thetowersdk/mechanics'
 *
 * const hp = computeWaveBaseHealth({ tier: 10, wave: 4200, tournament: false })
 */

export * from './assist-module-efficiency'
export * from './roi-scaling'
export * from './unity-random'
export * from './uptime-core'
export * from './uw-stat-values'
export * from './battle-condition-config'
export * from './battle-conditions'
export * from './bc-counter-labs'
export * from './bonuses'
export * from './bot-bot-overlap'
export * from './bot-coin-bonus'
export * from './bot-get-benefit'
export * from './bot-hit-multiplier'
export * from './bot-medal-hit-signal'
export * from './bot-medal-planner-insights'
export * from './bot-medal-planner-scoring'
export * from './bot-medal-plus-effects'
export * from './bot-medal-simulation'
export * from './bot-medal-sync-scoring'
export * from './bot-movement'
export * from './bots'
export * from './card-effect-lookup'
export * from './card-costs'
export * from './chrono-field'
export * from './constants'
export * from './crowd-control'
export * from './damage'
export * from './damage-reduction'
export * from './damage-redux-calculator'
export * from './damage-redux-constants'
export * from './damage-redux-layers'
export * from './damage-redux-wave-stats'
export * from './distances'
export * from './effective-paths-coin-costs'
export * from './effective-paths-credits'
export * from './effective-paths-currencies'
export * from './effective-paths-aliases'
export * from './effective-paths-assist-efficiency'
export * from './effective-paths-edamage-candidates'
export * from './effective-paths-edamage-costs'
export * from './effective-paths-edamage-coin-levels'
export * from './effective-paths-edamage-levels'
export * from './effective-paths-edamage-model'
export * from './effective-paths-ehp-from-sheet'
export * from './effective-paths-ehp-model'
export * from './effective-paths-enhancement-costs'
export * from './effective-paths-ehp-plan'
export * from './effective-paths-formula'
export * from './effective-paths-damage-base'
export * from './effective-paths-damage-stats'
export * from './effective-paths-damage-substats'
export * from './effective-paths-generics'
export * from './effective-paths-hp'
export * from './effective-paths-levels-schema'
export * from './effective-paths-ultimate-weapons'
export * from './effective-paths-regen-plan'
export * from './effective-paths-input-ranges'
export * from './effective-paths-lab-costs'
export * from './effective-paths-path-display'
export * from './effective-paths-planner'
export * from './effective-paths-schema'
export * from './effective-paths-stone-costs'
export * from './effective-paths-workbook'
export * from './effective-paths-workshop-values'
export * from './elite-spawn-chance'
export * from './els-module-cluster'
export * from './els-upgrade-path'
export * from './enemy-drops-context'
export * from './enemy-type-mix'
export * from './ep-controls'
export * from './enemy-drops-game-data'
export * from './enemy-drops-simulation'
export * from './enemy-level-skip'
export * from './enemy-overcharge-hit-scaling'
export * from './enemy-stat-display'
export * from './enemy-stats-simplified'
export * from './enemy-type-mults'
export * from './enemy-wave-info-labs'
export * from './enemy-wave-info-pipeline'
export * from './enemy-wave-stats'
export * from './get-resistance-level'
export * from './golden-combo'
export * from './guardians'
export * from './heat-bc-index-native'
export * from './ilm-calculator-resolve'
export * from './ilm-charge'
export * from './impetus'
export * from './knockback'
export * from './lab-research'
export * from './lab-workshop-calculations'
export * from './lab-workshop-constants'
export * from './land-mines'
export * from './math'
export * from './multishot-bounce'
export * from './poison-swamp'
export * from './projectile-damage'
export * from './rend-armor'
export * from './resource-drops-coin-context'
export * from './resource-drops-coin-fetch'
export * from './resource-drops-coin-generator-modules'
export * from './resource-drops-coin-iap'
export * from './resource-drops-coin-intro-sprint'
export * from './resource-drops-coin-module-cpk'
export * from './resource-drops-coin-perks'
export * from './resource-drops-coin-simulation'
export * from './resource-drops-coin-trade-off'
export * from './shockwave'
export * from './thorns'
export * from './thorns-calculator'
export * from './tournament-heat-bc'
export * from './tower-fire'
export * from './tower-range'
export * from './ultimates'
export * from './units'
export * from './wave-accelerator-spawn-rate-cap'
export * from './wave-base-empirical-scaling'
export * from './wave-base-scaling'
export * from './wave-info-enemy-constants'
export * from './wave-info-enemy-stats'
export * from './wave-info-panel-constants'
export * from './wave-info-panel-stats'
export * from './wave-info-panel-timing'
export * from './wave-scaling-regression-profile'
export * from './wave-skip'
export * from './wildfire'
export * from './workshop-attack-stats'
export * from './workshop-defense-stats'
export * from './workshop-stats'
export * from './workshop-table-build'
export * from './workshop-utility-stats'
export * from './bot-medal-planner-types'
export * from './formula-coverage'
export * from './els-calculator-options'
export * from './ilm-calculator-options'
export * from './effective-paths-uw-dps'
export * from './effective-paths-edamage-config'
export * from './effective-paths-edamage-compute'
export * from './effective-paths-edamage-plan'
export * from './effective-paths-edamage-schema'
export * from './effective-paths-eecon-candidates'
export * from './effective-paths-eecon-stats'
export * from './effective-paths-eecon-discount'
export * from './effective-paths-eecon-levels'
export * from './effective-paths-eecon-compute'
export * from './effective-paths-eecon-plan'
export * from './effective-paths-eecon-stone-mastery'
export * from './effective-paths-eecon-uw-cd'
// Browser-safe public barrel ends here.
// Node/AGS surfaces (coverage, debug-graph, ep-graph, mcp-contract, planner-engine,
// repo-root, save-graph, sdk-graph, builders, doctor, kernel, …) import via
// packages/sdk/src/mechanics/<path> — they must not be export* from this file or
// Vite/CJS loads node:fs into the browser and blanks the showcase site.
export * from './perk-benefit'
export * from './workshop-damage'
/*
 * TYPES ONLY. `./calculators` re-exports `specs-generated.ts`, which is
 * generated to declare the SDK's whole exported surface for coverage -- and
 * that surface includes the doctor modules, which import `node:fs` and tooling that is
 * not part of the published package.
 *
 * So `export * from './calculators'` dragged Node-only code into the browser
 * barrel, in breach of the contract stated a few lines above. That tooling ships
 * CommonJS, browser ESM cannot named-import from it, and the route chunk that reached
 * it died with "does not provide an export named ..." -- taking every calculator page
 * with it.
 *
 * `calculators/types.ts` has no imports at all, so this keeps `CalculatorSpec`
 * -- the only thing the app uses -- without the chain. Runtime calculator
 * surfaces are Node/AGS and import via `thetowersdk/mechanics/calculators`,
 * exactly like the other Node surfaces listed above.
 */
export * from './calculators/types'
