/** Land mine drop damage and detonation scaling. */
/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    MINE_DAMAGE_CAP, MINE_DAMAGE_SCALE, DropLandmineDamageInput, getDropLandmineDamage, dropLandMineDamage
 * depends    src/mechanics/ultimates
 * used by    src/mechanics/calculators/specs-generated, src/mechanics/index
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */

import { ultimateModuleMultiplier } from './ultimates'

export const MINE_DAMAGE_CAP = 100
export const MINE_DAMAGE_SCALE = 0.01

export interface DropLandmineDamageInput {
  mineDamage: number
  mineDamageAux: number
  mineField: number
  mineScalar: number
  workshopMineBase: number
  storedCoeff: number
}

export function getDropLandmineDamage(input: DropLandmineDamageInput): number {
  const scaledBase = Math.min(input.mineDamage, MINE_DAMAGE_CAP) * MINE_DAMAGE_SCALE
  const termA = input.mineDamageAux * scaledBase + 1
  const termB = (input.mineField * MINE_DAMAGE_SCALE) * (input.mineScalar * scaledBase) + 1
  const core = input.workshopMineBase * input.storedCoeff
  return core * termA * termB
}

export function dropLandMineDamage(
  baseDamage: number,
  moduleBonus: number,
  absorbPool: number,
): number {
  const moduleMult = ultimateModuleMultiplier(moduleBonus)
  const absorbed = Math.min(baseDamage, absorbPool)
  return (baseDamage - absorbed) * moduleMult
}
