/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    isMonorepoCheckout, resolveMechanicsRepoRoot
 * depends    —
 * used by    mcp/every-tool, src/mechanics/kernel/load, src/mechanics/planner-engine/codegen
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
import fs from 'node:fs'
import path from 'node:path'

/**
 * Walk up from this package until the monorepo root (or fall back to package parent).
 * Deliberately dependency-free, so any build can import it.
 */
/**
 * Whether this checkout is the monorepo, rather than the standalone `thetowersdk` repository.
 *
 * The mechanics registry and the graph tooling describe files by their MONOREPO path
 * (`packages/sdk/src/...`) and read them from a repo root discovered by walking up to
 * `scripts/mechanics-trust/`. Neither exists in the published repository, where this package IS
 * the root — so `resolveMechanicsRepoRoot()` falls back three levels up, lands somewhere above
 * the checkout, and every read becomes `<somewhere>/packages/sdk/src/...` which is not a path.
 *
 * Six test files failed that way in a clone while passing here. They assert things about
 * monorepo tooling, so outside the monorepo there is nothing for them to assert: they skip on
 * this rather than being excluded, which keeps them enforcing where they can.
 */
export function isMonorepoCheckout(explicit?: string): boolean {
  const root = resolveMechanicsRepoRoot(explicit)
  return fs.existsSync(path.join(root, 'scripts', 'mechanics-trust'))
    && fs.existsSync(path.join(root, 'packages', 'sdk', 'src'))
}

export function resolveMechanicsRepoRoot(explicit?: string): string {
  if (explicit) return explicit
  if (process.env.TOWER_MONOREPO_ROOT) return process.env.TOWER_MONOREPO_ROOT
  let dir = __dirname
  for (let i = 0; i < 10; i++) {
    if (fs.existsSync(path.join(dir, 'scripts', 'mechanics-trust', 'check.mjs'))) return dir
    const parent = path.dirname(dir)
    if (parent === dir) break
    dir = parent
  }
  return path.join(__dirname, '../../..')
}
