/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    introSprintZeroCoinWaveCap, introSprintZeroCoinFraction
 * depends    src/data/index, src/mechanics/math
 * used by    src/mechanics/calculators/specs-generated, src/mechanics/index, src/mechanics/resource-drops-coin-context, src/mechanics/resource-drops-coin-simulation
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
import { CARD_TEMPLATES } from '../data/index'
import { clamp } from './math'

const INTRO_SPRINT_CARD_ID = 'is'

function readIntroSprintBaseWaveCap(cardLevel: number): number {
  const card = CARD_TEMPLATES.find(entry => entry.id === INTRO_SPRINT_CARD_ID)
  if (!card || card.levelType !== 'flat') return 0
  const idx = clamp(Math.floor(cardLevel) - 1, 0, card.levelValues.length - 1)
  const raw = card.levelValues[idx]
  return typeof raw === 'number' && Number.isFinite(raw) ? Math.floor(raw) : 0
}

function readIntroSprintMasteryMult(masteryLevel: number): number {
  const card = CARD_TEMPLATES.find(entry => entry.id === INTRO_SPRINT_CARD_ID)
  if (!card?.masteryValues?.length) return 1
  const idx = clamp(Math.floor(masteryLevel), 0, card.masteryValues.length - 1)
  const raw = card.masteryValues[idx]
  return typeof raw === 'number' && raw > 0 ? raw : 1
}

/** Waves at run start that earn zero coins when Intro Sprint is active. */
export function introSprintZeroCoinWaveCap(input: {
  cardLevel: number
  cardMastery: number
  active: boolean
}): number {
  if (!input.active) return 0
  const level = Math.floor(Number(input.cardLevel) || 0)
  if (level <= 0) return 0
  const base = readIntroSprintBaseWaveCap(level)
  if (base <= 0) return 0
  const mastery = Math.floor(Number(input.cardMastery) || 0)
  const mult = mastery >= 0 && level >= 7 ? readIntroSprintMasteryMult(mastery) : 1
  return Math.floor(base * mult)
}

/** Fraction of modeled waves that earn zero coin income (kills + CPW). */
export function introSprintZeroCoinFraction(
  zeroCoinWaveCap: number,
  targetWave: number,
): number {
  const cap = Math.max(0, Math.floor(Number(zeroCoinWaveCap) || 0))
  const waves = Math.max(1, Math.floor(Number(targetWave) || 0))
  if (cap <= 0) return 0
  return Math.min(1, cap / waves)
}
