/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    RESOURCE_DROPS_COIN_IAP_MULTIPLIERS, ResourceDropsCoinIapToggles, computePackCoinMultFromIapToggles, iapTogglesFromLegacyMults
 * depends    —
 * used by    src/internal/enemy-drops-calcs-local-state, src/mechanics/calculators/specs-generated, src/mechanics/index, src/mechanics/resource-drops-coin-context, src/mechanics/resource-drops-coin-simulation
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
/** Fixed coin multipliers for real-money packs (product of all owned = up to 9×). */

export const RESOURCE_DROPS_COIN_IAP_MULTIPLIERS = {
  starterPack: 2,
  disableAds: 1.5,
  epicPack: 3,
} as const

export interface ResourceDropsCoinIapToggles {
  hasStarterPack: boolean
  hasEpicPack: boolean
  hasDisableAds: boolean
}

export function computePackCoinMultFromIapToggles(toggles: ResourceDropsCoinIapToggles): number {
  let mult = 1
  if (toggles.hasStarterPack) mult *= RESOURCE_DROPS_COIN_IAP_MULTIPLIERS.starterPack
  if (toggles.hasEpicPack) mult *= RESOURCE_DROPS_COIN_IAP_MULTIPLIERS.epicPack
  if (toggles.hasDisableAds) mult *= RESOURCE_DROPS_COIN_IAP_MULTIPLIERS.disableAds
  return mult
}

/** Migrate legacy numeric mult inputs to toggles. */
export function iapTogglesFromLegacyMults(source: {
  starterPackCoinMult?: number
  epicPackCoinMult?: number
  disableAdsCoinMult?: number
  hasStarterPack?: boolean
  hasEpicPack?: boolean
  hasDisableAds?: boolean
}): ResourceDropsCoinIapToggles {
  return {
    hasStarterPack: source.hasStarterPack === true
      || (Number(source.starterPackCoinMult) || 1) > 1,
    hasEpicPack: source.hasEpicPack === true
      || (Number(source.epicPackCoinMult) || 1) > 1,
    hasDisableAds: source.hasDisableAds === true
      || (Number(source.disableAdsCoinMult) || 1) > 1,
  }
}
