/**
 * Wave Info panel footer timing — wave combat duration and inter-wave cooldown.
 *
 * Cooldown: WA card level (uptime-core model; floor 4s at max WA), halved in tournament.
 * Wave time: 26s standard / 13s tournament; not WA-modified.
 */
/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    WAVE_INFO_PANEL_WAVE_TIME_SECONDS, WaveInfoPanelTimingInput, waveInfoPanelWaveTimeSeconds, waveInfoPanelWaveCooldownSeconds
 * depends    src/mechanics/uptime-core
 * used by    src/mechanics/calculators/specs-generated, src/mechanics/index, src/mechanics/wave-info-panel-stats
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
import {
  computeWaveCombatDurationSeconds,
  computeWaveInterCooldownSeconds,
  UPTIME_WAVE_COMBAT_DURATION_SECONDS,
} from './uptime-core'

/** Standard-tier combat wave timer (26s). */
export const WAVE_INFO_PANEL_WAVE_TIME_SECONDS = UPTIME_WAVE_COMBAT_DURATION_SECONDS

export type WaveInfoPanelTimingInput = {
  /** Wave Accelerator card level 1–7; null/omitted = card not equipped (no WA reduction). */
  waveAcceleratorLevel?: number | null
  /** Tournament run (tier+ / league selection). */
  tournament?: boolean
}

/** Combat wave timer shown in Wave Info — tournament halves duration; not WA-modified. */
export function waveInfoPanelWaveTimeSeconds(
  input: Pick<WaveInfoPanelTimingInput, 'tournament'> = {},
): number {
  return computeWaveCombatDurationSeconds(Boolean(input.tournament))
}

/** Inter-wave cooldown after Wave Accelerator card level (min 4s at level 7; halved in tournament). */
export function waveInfoPanelWaveCooldownSeconds(
  input: WaveInfoPanelTimingInput = {},
): number {
  const waLevel =
    input.waveAcceleratorLevel != null && input.waveAcceleratorLevel > 0
      ? input.waveAcceleratorLevel
      : 0
  return computeWaveInterCooldownSeconds(waLevel, { tournament: Boolean(input.tournament) })
}
