/**
 * Wave-base enemy scaler.
 *
 * Models base enemy health and damage as polynomial × milestone × growth ×
 * tier-pressure terms.
 *
 * ## Accuracy: exact, not approximate
 *
 * This docstring used to say the coefficients were "fitted to observed in-game
 * values rather than derived" and should be treated as "a close approximation
 * and not an exact reproduction". That is wrong, and wrong in the expensive
 * direction: it tells anyone building on this that the foundation is
 * approximate, which is a reason not to build.
 *
 * The chain, verified 2026-08-18:
 *
 *   The game's own wave-base health and damage values, with every constant
 *   exact rather than fitted
 *     -> wave/_reference/wave-base-constants.ts  (all 12 health polynomial
 *        terms and every body coefficient compared: zero mismatches)
 *     -> wave/_reference/wave-base-scaling-legacy.ts
 *     -> THIS FILE, held to it by wave-base-empirical-parity.test.ts, which
 *        asserts `toBe` — exact equality, not a tolerance — across 21 tiers,
 *        34 waves and 8 contexts.
 *
 * So "empirical" describes how the STRUCTURE was first discovered, not the
 * fidelity of the result. The numbers are the game's own.
 *
 * The decoded dump itself is gitignored and unavailable in CI, which is why the
 * chain is recorded here rather than pinned by a test that would silently skip.
 * The RVAs above are what makes it re-checkable when the binary changes.
 *
 * Derived from `statFormula.ts` in tower-idle-toolkit by skye (ISC) —
 * https://github.com/tower-idle-toolkit/tower-idle-toolkit
 * That project established this structure and several of the constants.
 * See NOTICE at the package root.
 */
/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    empiricalTierPressure, empiricalTierCoinMultiplier, computeEmpiricalWaveBaseHealthRaw, computeEmpiricalWaveBaseHealth, computeEmpiricalWaveBaseDamage, WaveBaseScalingInput, tierDifficultyMultiplier, damageTierDifficultyMultiplier (+8 more)
 * depends    src/data/campaign-tier, src/mechanics/wave-scaling-regression-profile
 * used by    src/mechanics/calculators/run, src/mechanics/calculators/specs-generated, src/mechanics/index, src/mechanics/resource-drops-coin-simulation, src/mechanics/wave-base-scaling
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
import { clampCampaignTier } from '../data/campaign-tier'
import {
  CAMPAIGN_COIN_REWARD_CURVE,
  CAMPAIGN_TIER_PRESSURE,
  DAMAGE_TIER_ATTENUATION,
  type EmpiricalWaveScalingInput,
  REGRESSION_DAMAGE_PROFILE,
  REGRESSION_HP_PROFILE,
} from './wave-scaling-regression-profile'

const HP = REGRESSION_HP_PROFILE
const DMG = REGRESSION_DAMAGE_PROFILE

type ProfileTerm = {
  coeff?: number
  base?: number
  divisor?: number
  crossBand?: true
  exponentFromWaveShift10?: true
  skipWhenTier?: number
}

/** Completed wave brackets at a fixed milestone interval. */
function milestoneBracketCount(wave: number, milestoneInterval: number): number {
  return Math.floor(Math.max(1, Math.floor(wave)) / milestoneInterval)
}

/** Mid-game damage compression index — rational blend fitted from T7+ samples. */
function midGameDamageCompressionIndex(wave: number): number {
  const w = Math.max(1, Math.floor(wave)) >>> 0
  const blendNumerator = 842937507
  const rationalBlend = Math.floor((w * blendNumerator) / 2 ** 32)
  return (rationalBlend + ((w - rationalBlend) >> 1)) >> 6
}

/** Super-late campaign exponent (waves beyond ~1k). */
function superLateCampaignExponent(wave: number): number {
  return (Math.max(1, Math.floor(wave)) >> 10) & 0x3fffff
}

type MilestoneSlope = { slopePerBracket: number, bracketWidth: number }

function piecewiseMilestoneSum(wave: number, segments: readonly MilestoneSlope[]): number {
  let sum = 0
  for (const seg of segments) {
    sum += seg.slopePerBracket * milestoneBracketCount(wave, seg.bracketWidth)
  }
  return sum
}

/** Early campaign milestone offsets — legacy ENEMYHP used 0.04·floor(w/5) … 0.08·floor(w/50). */
const HP_EARLY_ERA: readonly MilestoneSlope[] = [
  // OLD: 0.04 × floor(w/5)  → fitted 0.03999999910593033
  { slopePerBracket: 0.03999999910593033, bracketWidth: 5 },
  // OLD: 0.05 × floor(w/10)
  { slopePerBracket: 0.05000000074505806, bracketWidth: 10 },
  // OLD: 0.06 × floor(w/25)
  { slopePerBracket: 0.05999999865889549, bracketWidth: 25 },
  // OLD: 0.08 × floor(w/50)
  { slopePerBracket: 0.07999999821186066, bracketWidth: 50 },
]

/** Mid campaign — legacy had 0.1·floor(w/60), 0.12·floor(w/100), 0.15·floor(w/200), 0.35·floor(w/900). */
const HP_MID_ERA: readonly MilestoneSlope[] = [
  { slopePerBracket: 0.10000000149011612, bracketWidth: 60 },
  { slopePerBracket: 0.11999999731779099, bracketWidth: 100 },
  { slopePerBracket: 0.15000000596046448, bracketWidth: 200 },
  { slopePerBracket: 0.3499999940395355, bracketWidth: 900 },
]

/** Late campaign — legacy 0.18·floor(w/72) … 0.1·floor(w/107); modern adds f32-refined slopes. */
const HP_LATE_ERA: readonly MilestoneSlope[] = [
  { slopePerBracket: 0.18000000715255737, bracketWidth: 72 },
  { slopePerBracket: 0.20000000298023224, bracketWidth: 83 },
  { slopePerBracket: 0.20999999344348907, bracketWidth: 94 },
  { slopePerBracket: 0.10000000149011612, bracketWidth: 107 },
]

function regressionOffsetEnvelope(
  wave: number,
  terms: readonly ProfileTerm[],
  includeUnitBaseline: boolean,
): number {
  let sum = includeUnitBaseline ? 1 : 0
  for (const term of terms) {
    sum += (term.coeff ?? 0) * milestoneBracketCount(wave, term.divisor ?? 1)
  }
  return sum
}

function applyProfilePowChain(wave: number, terms: readonly ProfileTerm[]): number {
  const wi = Math.max(1, Math.floor(wave))
  let product = 1
  for (const term of terms) {
    let exponent = 0
    if (term.crossBand) exponent = midGameDamageCompressionIndex(wi)
    else if (term.exponentFromWaveShift10) exponent = superLateCampaignExponent(wi)
    else exponent = milestoneBracketCount(wi, term.divisor ?? 1)
    if (exponent > 0) product *= (term.base ?? 1) ** exponent
  }
  return product
}

function healthPolynomialEnvelope(wave: number): number {
  return 1
    + piecewiseMilestoneSum(wave, HP_EARLY_ERA)
    + piecewiseMilestoneSum(wave, HP_MID_ERA)
    + piecewiseMilestoneSum(wave, HP_LATE_ERA)
}

function healthCompoundMultiplier(wave: number): number {
  // OLD FRAMEWORK: Math.pow(1.035,floor(w/30)) * Math.pow(1.02,floor(w/60)) * … * pow(1.15,floor(w/1024))
  // Modern profile: same chain layout; super-late /1024 → wave>>10 exponent; rates f32-fitted.
  return applyProfilePowChain(wave, HP.powChain)
}

/** Independent damage envelope — legacy ENEMYDMG path; never reads HP. */
function independentDamageEnvelope(wave: number, tier: number): number {
  const t = clampCampaignTier(tier)
  // OLD: innerPoly (floor w/5…900) × earlyGrowth (1.005^floor(w/30)…) × midGrowth × tierBranch × NewDMG × TierDiff
  // Modern: regressionOffsetEnvelope × pow chains × DAMAGE_TIER_ATTENUATION (TierDiff+NewDMG tabulated)
  let envelope = regressionOffsetEnvelope(wave, DMG.polynomialTerms, DMG.polyPlusOne)
    * applyProfilePowChain(wave, DMG.powChain)
  if (t > 6) {
    for (const term of DMG.powChainTierGt6) {
      if ('skipWhenTier' in term && term.skipWhenTier != null && t === term.skipWhenTier) continue
      const exponent = milestoneBracketCount(wave, term.divisor ?? 1)
      if (exponent > 0) envelope *= (term.base ?? 1) ** exponent
    }
  }
  return envelope * applyProfilePowChain(wave, DMG.powChainLate)
}

function tierExponentAddon(tier: number, table: readonly number[], cap: number): number {
  const t = clampCampaignTier(tier)
  if (t <= 9) return 0
  if (t <= 14) return table[t - 10] ?? 0
  return cap
}

function centuryMilestoneStack(wave: number, perCenturyRate: number, active: boolean): number {
  if (!active) return 1
  const w = Math.max(1, Math.floor(wave))
  if (w < 100) return 1
  let m = 1
  let threshold = 100
  while (threshold < w) {
    m *= perCenturyRate
    threshold += 100
  }
  return m
}

function resolveTournamentTestMode(input: EmpiricalWaveScalingInput): boolean {
  if (input.isTestingTournamentConditions != null) return input.isTestingTournamentConditions
  if (input.tournamentLeague != null) return input.tournamentLeague
  return false
}

function resolveHealthExponent(input: EmpiricalWaveScalingInput): number {
  const body = HP.body
  const addon = tierExponentAddon(input.tier, body.tierExpAddon_t10_14, body.tierExpCap_t15plus)
  if (input.highestWaveThisTierAltBody) return HP.tournamentAltExp + addon
  if (!input.tournament) return body.baseExp + addon
  if (resolveTournamentTestMode(input)) return body.tournamentBaseExpNoLeague + addon
  return body.tournamentBaseExp + addon
}

function resolveDamageExponent(input: EmpiricalWaveScalingInput): number {
  const body = DMG.body
  const addon = tierExponentAddon(input.tier, body.tierExpAddon_t10_14, body.tierExpCap_t15plus)
  if (!input.tournament) return body.baseExp + addon
  if (resolveTournamentTestMode(input)) return body.tournamentBaseExp + addon
  return body.tournamentBaseExpNoLeague + addon
}

function resolveHealthLinearCoeffs(input: EmpiricalWaveScalingInput): { slope: number, intercept: number } {
  const body = HP.body
  if (input.tournament) return { slope: body.a, intercept: body.b }
  return { slope: body.aNonTournament, intercept: body.bNonTournament }
}

function resolveDamageLinearCoeffs(input: EmpiricalWaveScalingInput): { slope: number, intercept: number } {
  const body = DMG.body
  if (!input.tournament) return { slope: body.aNonTournament, intercept: body.bNonTournament }
  return { slope: body.a, intercept: body.b }
}

function damageTierAttenuationFactor(tier: number, tierPressure: number): number {
  const t = clampCampaignTier(tier)
  if (t < 4) return tierPressure * DMG.tierBranchLt4
  if (t < 7) return tierPressure * DMG.tierBranchLt7
  if (t < 10) return tierPressure * DMG.tierScale
  const div = DAMAGE_TIER_ATTENUATION[t] || DMG.tierCapDivisor
  return (tierPressure * DMG.tierScale) / div
}

export function empiricalTierPressure(tier: number): number {
  const t = clampCampaignTier(tier)
  return CAMPAIGN_TIER_PRESSURE[t] ?? 1
}

export function empiricalTierCoinMultiplier(tier: number): number {
  const t = clampCampaignTier(tier)
  return CAMPAIGN_COIN_REWARD_CURVE[t] ?? 1
}

function healthCore(input: EmpiricalWaveScalingInput): number {
  const w = Math.max(1, Math.floor(input.wave))
  const t = clampCampaignTier(input.tier)
  const tierPressure = input.tierDifficultyMultiplier ?? empiricalTierPressure(t)
  const envelope = healthPolynomialEnvelope(w) * healthCompoundMultiplier(w)
  const { slope, intercept } = resolveHealthLinearCoeffs(input)
  const exponent = resolveHealthExponent(input)
  // OLD: 0.05·w^HPexp + 0.8·w + 1.5  (tournament: baseMod/scalingMod on coeffs)
  const linearTerm = w ** exponent * slope + intercept * w + HP.body.c
  const centuryStack = centuryMilestoneStack(w, HP.wave100Mult, !!input.tournament)
  let value = envelope * linearTerm * centuryStack
  // OLD: Math.pow(expMod, wave) when tourn — modern uses tournamentWavePowBase**w + century stack
  if (input.tournament && !input.highestWaveThisTierAltBody) {
    value *= HP.tournamentWavePowBase ** w
  }
  // OLD: × TierDiff(tier) — modern: CAMPAIGN_TIER_PRESSURE lookup
  return value * tierPressure
}

/** Unfloored HP from the empirical regression model. */
export function computeEmpiricalWaveBaseHealthRaw(input: EmpiricalWaveScalingInput): number {
  return healthCore(input)
}

export function computeEmpiricalWaveBaseHealth(input: EmpiricalWaveScalingInput): number {
  return Math.floor(healthCore(input))
}

/** Independent damage curve — never references computed HP. */
export function computeEmpiricalWaveBaseDamage(input: EmpiricalWaveScalingInput): number {
  const w = Math.max(1, Math.floor(input.wave))
  const t = clampCampaignTier(input.tier)
  const tierPressure = input.tierDifficultyMultiplier ?? empiricalTierPressure(t)
  const envelope = independentDamageEnvelope(w, t)
  const { slope, intercept } = resolveDamageLinearCoeffs(input)
  const exponent = resolveDamageExponent(input)
  const linearTerm = w ** exponent * slope + intercept * w + DMG.body.c
  const centuryStack = centuryMilestoneStack(w, DMG.wave100Mult, !!input.tournament)
  const raw = envelope * linearTerm * centuryStack * damageTierAttenuationFactor(t, tierPressure)
  return Math.floor(raw)
}

export type WaveBaseScalingInput = EmpiricalWaveScalingInput

export const tierDifficultyMultiplier = empiricalTierPressure
export const damageTierDifficultyMultiplier = empiricalTierPressure
export const healthTierDifficultyMultiplier = empiricalTierPressure
export const tierCoinMultiplier = empiricalTierCoinMultiplier

export const computeWaveBaseHealthRaw = computeEmpiricalWaveBaseHealthRaw
export const computeWaveBaseHealth = computeEmpiricalWaveBaseHealth
export const computeWaveBaseDamage = computeEmpiricalWaveBaseDamage

export const healthWave100Multiplier = (w: number, tournament = false) =>
  centuryMilestoneStack(w, HP.wave100Mult, tournament)
export const damageWave100Multiplier = (w: number, tournament = false) =>
  centuryMilestoneStack(w, DMG.wave100Mult, tournament)
export const wave100Multiplier = healthWave100Multiplier

export type { EmpiricalWaveScalingInput }
