/**
 * Workshop attack preview stats.
 *
 * ## Damage — `GetOutOfRoundDamage`
 *
 * Workshop upgrade level `L` (attack damage slot):
 *
 *   core(L) = L × 2.8 + L² × 1e-6 + 3
 *
 * For each tier threshold Tᵢ, when L > Tᵢ add:
 *
 *   (L − Tᵢ)^pᵢ × cᵢ
 *
 * | Threshold | Exponent p | Coeff c |
 * |-----------|------------|---------|
 * | 999       | 2.10       | 0.08    |
 * | 1499      | 2.12       | 0.09    |
 * | 1999      | 2.18       | 0.10    |
 * | 2499      | 2.25       | 0.10    |
 * | 2999      | 2.30       | 0.10    |
 * | 3499      | 2.33       | 0.20    |
 * | 3999      | 2.34       | 0.20    |
 *
 * Final getter multiplies `core + Σ tiers` by catalog table row, workshop
 * card mult, and relic chain.
 *
 * ## Critical multiplier (workshop preview)
 *
 *   levelTerm   = workshopLevel × 0.1 + 1.2
 *   moduleCrit  = module critical multiplier bonus
 *   upgradeCrit = workshop upgrade in the crit slot + 1.0
 *   cardMult    = card critical mult
 *   relicMult   = relic critical mult
 *
 *   critMult = (levelTerm × workshopStat28 + moduleCrit) × cardMult × upgradeCrit × relicMult
 *
 * Live probe anchor: CriticalMultiplier ≈ 969.95 at reference build.
 */
/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    WorkshopDamageTier, WORKSHOP_DAMAGE_TIERS, workshopDamageCurve, WorkshopDamagePreviewInput, getOutOfRoundDamagePreview, CriticalMultiplierPreviewInput, getOutOfRoundCriticalMultiplier
 * depends    src/mechanics/constants
 * used by    src/mechanics/calculators/specs-generated, src/mechanics/index
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */

import {
  CRIT_MULT_LEVEL_BASE,
  CRIT_MULT_LEVEL_SCALE,
  WORKSHOP_DAMAGE_BASE_OFFSET,
  WORKSHOP_DAMAGE_LINEAR_COEFF,
  WORKSHOP_DAMAGE_QUAD_COEFF,
} from './constants'

export interface WorkshopDamageTier {
  threshold: number
  exponent: number
  coefficient: number
}

/** Tier pow terms above threshold levels. */
export const WORKSHOP_DAMAGE_TIERS: readonly WorkshopDamageTier[] = [
  { threshold: 999, exponent: 2.1, coefficient: 0.08 },
  { threshold: 1499, exponent: 2.12, coefficient: 0.09 },
  { threshold: 1999, exponent: 2.18, coefficient: 0.1 },
  { threshold: 2499, exponent: 2.25, coefficient: 0.1 },
  { threshold: 2999, exponent: 2.3, coefficient: 0.1 },
  { threshold: 3499, exponent: 2.33, coefficient: 0.2 },
  { threshold: 3999, exponent: 2.34, coefficient: 0.2 },
]

/** Polynomial + tier pow sum before catalog × card × relic. */
export function workshopDamageCurve(workshopLevel: number): number {
  const L = Math.max(0, workshopLevel)
  let sum = L * WORKSHOP_DAMAGE_LINEAR_COEFF + L * L * WORKSHOP_DAMAGE_QUAD_COEFF + WORKSHOP_DAMAGE_BASE_OFFSET
  for (const tier of WORKSHOP_DAMAGE_TIERS) {
    if (L > tier.threshold) {
      const excess = L - tier.threshold
      sum += excess ** tier.exponent * tier.coefficient
    }
  }
  return sum
}

export interface WorkshopDamagePreviewInput {
  workshopLevel: number
  /** Catalog table multiplier from GetWorkshopUpgrade row. */
  catalogMult: number
  cardMult?: number
  relicMult?: number
}

export function getOutOfRoundDamagePreview(input: WorkshopDamagePreviewInput): number {
  let raw = workshopDamageCurve(input.workshopLevel) * input.catalogMult
  if (input.cardMult != null) raw *= input.cardMult
  if (input.relicMult != null) raw *= input.relicMult
  return raw
}

export interface CriticalMultiplierPreviewInput {
  workshopLevel: number
  /** Workshop stat @ +0x28 on workshop damage object. */
  workshopStat28: number
  moduleCriticalMultiplier: number
  /** GetWorkshopUpgrade(0x12) raw value. */
  upgradeSlot18: number
  cardMult?: number
  relicMult?: number
}

/** GetOutOfRoundCriticalMultiplier preview. */
export function getOutOfRoundCriticalMultiplier(input: CriticalMultiplierPreviewInput): number {
  const levelTerm = input.workshopLevel * CRIT_MULT_LEVEL_SCALE + CRIT_MULT_LEVEL_BASE
  let raw = levelTerm * input.workshopStat28 + input.moduleCriticalMultiplier
  if (input.cardMult != null) raw *= input.cardMult
  raw *= input.upgradeSlot18 + 1
  if (input.relicMult != null) raw *= input.relicMult
  return raw
}
