/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    MAX_CAMPAIGN_TIER, MIN_CAMPAIGN_TIER, clampCampaignTier, campaignTierTableLength
 * depends    src/data/generated/index
 * used by    src/data/enemies, src/data/index, src/data/tournaments, src/internal/calculator-local-state-schemas, src/internal/dissonance-calcs-local-state, src/knowledge/compartments/daily-missions (+5 more)
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
import { V283_MAX_CAMPAIGN_TIER } from './generated/index'

/** Max standard campaign tier (v28.3+). */
export const MAX_CAMPAIGN_TIER = V283_MAX_CAMPAIGN_TIER

export const MIN_CAMPAIGN_TIER = 1 as const

/** Clamp a numeric tier to the supported campaign range. */
export function clampCampaignTier(tier: number): number {
  if (!Number.isFinite(tier)) return MIN_CAMPAIGN_TIER
  return Math.min(MAX_CAMPAIGN_TIER, Math.max(MIN_CAMPAIGN_TIER, Math.round(tier)))
}

/** `Array.from` length helper for tier-indexed tables (includes tier 0 slot when `includeZero` is true). */
export function campaignTierTableLength(includeZero = false): number {
  return MAX_CAMPAIGN_TIER + (includeZero ? 1 : 0)
}
