/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    DailyMissionTierReward, DailyMissionWeeklyReward, DailyMissionLabLevel, DAILY_MISSION_TIER_REWARDS, DAILY_MISSION_WEEKLY_REWARDS, DAILY_MISSION_WEEKLY_TOTALS, DAILY_MISSION_REROLL_LAB_LEVELS
 * depends    —
 * used by    src/data/index, src/knowledge/compartments/daily-missions
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
/**
 * Daily missions — reward tables.
 *
 * Game numbers, not presentation: what each mission pays and at what tier. Prose
 * describing how missions are handed out lives in `thetowersdk/knowledge`.
 */

export interface DailyMissionTierReward {
  tier: number
  coins: string
  shards: string
}

export interface DailyMissionWeeklyReward {
  missionsCompleted: number
  coinsMultiplier: string
  gems: number
  medals: number
  stones: number
  tokens: number
}

export interface DailyMissionLabLevel {
  level: number
  time: string
  cost: string
  value: string
}

/** Per-mission coins and shards, by the highest tier the player has unlocked. */
export const DAILY_MISSION_TIER_REWARDS: readonly DailyMissionTierReward[] = [
  { tier: 1, coins: '25', shards: 'N/A' },
  { tier: 2, coins: '100', shards: '3' },
  { tier: 3, coins: '1000', shards: '5' },
  { tier: 4, coins: '10,000', shards: '8' },
  { tier: 5, coins: '25,000', shards: '12' },
  { tier: 6, coins: '80,000', shards: '15' },
  { tier: 7, coins: '250,000', shards: '20' },
  { tier: 8, coins: '500,000', shards: '25' },
  { tier: 9, coins: '1.00 Mil', shards: '30' },
  { tier: 10, coins: '3.00 Mil', shards: '34' },
  { tier: 11, coins: '5.00 Mil', shards: '38' },
  { tier: 12, coins: '8.00 Mil', shards: '42' },
  { tier: 13, coins: '15.00 Mil', shards: '48' },
  { tier: 14, coins: '30.00 Mil', shards: '55' },
  { tier: 15, coins: '75.00 Mil', shards: '60' },
  { tier: 16, coins: '150.00 Mil', shards: '65' },
  { tier: 17, coins: '300.00 Mil', shards: '70' },
  { tier: 18, coins: '500 Mil', shards: '75' },
  { tier: 19, coins: '750 Mil', shards: '80' },
  { tier: 20, coins: '1.25 Bil', shards: '85' },
  { tier: 21, coins: '2.00 Bil', shards: '90' },
  { tier: 22, coins: '3.25 Bil', shards: '95' },
  { tier: 23, coins: '5.00 Bil', shards: '100' },
  { tier: 24, coins: '7.50 Bil', shards: '105' },
] as const

/** Weekly reward tiers, keyed by how many missions were completed that week. */
export const DAILY_MISSION_WEEKLY_REWARDS: readonly DailyMissionWeeklyReward[] = [
  { missionsCompleted: 5, coinsMultiplier: 'x3', gems: 10, medals: 0, stones: 0, tokens: 5 },
  { missionsCompleted: 10, coinsMultiplier: 'x4', gems: 15, medals: 10, stones: 0, tokens: 5 },
  { missionsCompleted: 15, coinsMultiplier: 'x5', gems: 20, medals: 15, stones: 0, tokens: 5 },
  { missionsCompleted: 20, coinsMultiplier: 'x7', gems: 25, medals: 20, stones: 0, tokens: 5 },
  { missionsCompleted: 25, coinsMultiplier: 'x10', gems: 30, medals: 25, stones: 10, tokens: 5 },
  { missionsCompleted: 30, coinsMultiplier: 'x15', gems: 35, medals: 30, stones: 15, tokens: 5 },
  { missionsCompleted: 35, coinsMultiplier: 'x20', gems: 50, medals: 35, stones: 20, tokens: 5 },
] as const

function sumWeekly(field: 'gems' | 'medals' | 'stones' | 'tokens'): number {
  return DAILY_MISSION_WEEKLY_REWARDS.reduce((sum, row) => sum + row[field], 0)
}

/**
 * Everything a full week pays out.
 *
 * Derived from the rows above rather than transcribed alongside them. The
 * previous hand-written copy happened to be correct, but a table and its own
 * total kept as separate literals is a value with two owners — add a tier and
 * only one of them moves.
 */
export const DAILY_MISSION_WEEKLY_TOTALS = {
  coinsMultiplier: `x${DAILY_MISSION_WEEKLY_REWARDS.reduce(
    (sum, row) => sum + Number(row.coinsMultiplier.replace(/^x/i, '')),
    0,
  )}`,
  gems: sumWeekly('gems'),
  medals: sumWeekly('medals'),
  stones: sumWeekly('stones'),
  tokens: sumWeekly('tokens'),
} as const

/** The Reroll Daily Mission lab — one level, unlocked at Tier 4 Wave 30. */
export const DAILY_MISSION_REROLL_LAB_LEVELS: readonly DailyMissionLabLevel[] = [
  {
    level: 1,
    time: '1d 15h 59m',
    cost: '20,000,000',
    value: 'Unlocked',
  },
] as const

