/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    FleetRewardRow, FleetSpawnRow, EnemyTypeSummary, ENEMIES_OVERVIEW_FACTS, NORMAL_AND_BOSS_ENEMY_FACTS, ELITE_ENEMY_FACTS, FLEET_ENEMY_FACTS, FLEET_ENEMY_TYPE_FACTS (+8 more)
 * depends    src/data/campaign-tier
 * used by    src/data/index, src/knowledge/compartments/enemies, src/mechanics/calculators/run, src/mechanics/elite-spawn-chance, src/mechanics/enemy-drops-simulation
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
import { clampCampaignTier } from './campaign-tier'

export interface FleetRewardRow {
  tier: number
  rerollShards: number
  moduleShardsPerType: number
}

export interface FleetSpawnRow {
  tier: number
  firstWave: number
  repeatEveryWaves: number
  fleetsPerSpawn: number
}

export interface EnemyTypeSummary {
  name: string
  summary: string
}

export const ENEMIES_OVERVIEW_FACTS = [
  'Enemy categories are Normal, Elite, Fleet, and Boss.',
  'Spawn caps at one time are 150 total: 120 normal, 20 elites, and 10 bosses. Fleet enemies use normal spawn-cap slots.',
  'Shared mechanics include a 4% damage heat-up per hit, 50% coin decay after more than 3 waves alive, and 4% mass growth for each wave an enemy survives.',
] as const

export const NORMAL_AND_BOSS_ENEMY_FACTS = [
  'Normal enemies include Basic, Fast, Ranged, Tank, and Protector, and their spawn percentages sum to 100% each wave.',
  'Protectors have special spawn limits and cooldown behavior with a limited concurrent count.',
  'Bosses spawn at 100% on boss waves, usually every 10 waves unless battle conditions change that cadence.',
  'Bosses are immune to orbs except boss orb hit lab effects, death ray, shockwave, and Black Hole, and they can drop module shards and reroll shards.',
] as const

export const ELITE_ENEMY_FACTS = [
  'Elite enemies are Vampire, Ray, and Scatter.',
  'Elite spawn is limited to one per wave early and up to two at higher waves. The UI can show 33% when one elite is guaranteed plus a possible second, and 100% when two are guaranteed.',
  'Elites are immune to orbs, death ray, shockwave, and Black Hole.',
  'Elite enemies drop elite cells on defeat, and Scatter children do not count toward the elite on-screen cap.',
] as const

export const FLEET_ENEMY_FACTS = [
  'Fleet enemies appear naturally at Tier 14 and above and at very high waves on lower tiers.',
  'Fleet enemies are immune to orbs, death ray, shockwave, knockback, Black Hole damage, and Black Hole pull.',
  'They have 85% thorns resistance, 50% resistance to several stun and slow effects, and can be targeted by tower attacks (v28.3+).',
  'On lower tiers they begin at wave 15000 on Tier 1 and arrive 250 waves earlier for each higher tier, then repeat every 100 waves after their first appearance.',
] as const

export const FLEET_ENEMY_TYPE_FACTS = [
  'Saboteur has 2x speed and 20x health and disables a random ultimate weapon when it hits the tower, although the wall can block that debuff behavior.',
  'Commander has 0.5x speed and 20x health and applies a 2x nearby enemy health aura.',
  'Overcharge has 1x speed and 20x health and fires a returning projectile that doubles damage with each later hit.',
] as const

export const FLEET_REWARD_ROWS: readonly FleetRewardRow[] = [
  { tier: 14, rerollShards: 1080, moduleShardsPerType: 5 },
  { tier: 15, rerollShards: 1200, moduleShardsPerType: 6 },
  { tier: 16, rerollShards: 1350, moduleShardsPerType: 7 },
  { tier: 17, rerollShards: 1500, moduleShardsPerType: 8 },
  { tier: 18, rerollShards: 1650, moduleShardsPerType: 9 },
  { tier: 19, rerollShards: 1800, moduleShardsPerType: 10 },
  { tier: 20, rerollShards: 1950, moduleShardsPerType: 11 },
  { tier: 21, rerollShards: 2100, moduleShardsPerType: 12 },
  { tier: 22, rerollShards: 2250, moduleShardsPerType: 13 },
  { tier: 23, rerollShards: 2400, moduleShardsPerType: 14 },
  { tier: 24, rerollShards: 2550, moduleShardsPerType: 15 },
] as const

export interface BossWaveSpawnRow {
  tier: number
  /** Boss wave every N waves — smaller N at higher tiers (bosses spawn more often). */
  everyWaves: number
}

/**
 * Standard-run boss cadence by tier (More Bosses BC).
 * T1–13: every 10 waves. T14+ steps 9→8→7→6, then every 5 waves at T18+.
 */
export const BOSS_WAVE_SPAWN_ROWS: readonly BossWaveSpawnRow[] = [
  { tier: 14, everyWaves: 9 },
  { tier: 15, everyWaves: 8 },
  { tier: 16, everyWaves: 7 },
  { tier: 17, everyWaves: 6 },
  { tier: 18, everyWaves: 5 },
  { tier: 19, everyWaves: 5 },
  { tier: 20, everyWaves: 5 },
  { tier: 21, everyWaves: 5 },
  { tier: 22, everyWaves: 5 },
  { tier: 23, everyWaves: 5 },
  { tier: 24, everyWaves: 5 },
] as const

export const DEFAULT_BOSS_WAVE_INTERVAL = 10

export function bossWaveIntervalForTier(tier: number): number {
  const t = clampCampaignTier(tier)
  const row = BOSS_WAVE_SPAWN_ROWS.find(entry => entry.tier === t)
  return row?.everyWaves ?? DEFAULT_BOSS_WAVE_INTERVAL
}

export const FLEET_SPAWN_ROWS: readonly FleetSpawnRow[] = [
  { tier: 14, firstWave: 2495, repeatEveryWaves: 1000, fleetsPerSpawn: 1 },
  { tier: 15, firstWave: 1495, repeatEveryWaves: 750, fleetsPerSpawn: 1 },
  { tier: 16, firstWave: 995, repeatEveryWaves: 500, fleetsPerSpawn: 1 },
  { tier: 17, firstWave: 495, repeatEveryWaves: 250, fleetsPerSpawn: 1 },
  { tier: 18, firstWave: 95, repeatEveryWaves: 100, fleetsPerSpawn: 1 },
  { tier: 19, firstWave: 45, repeatEveryWaves: 50, fleetsPerSpawn: 1 },
  { tier: 20, firstWave: 5, repeatEveryWaves: 10, fleetsPerSpawn: 1 },
  { tier: 21, firstWave: 5, repeatEveryWaves: 10, fleetsPerSpawn: 2 },
  { tier: 22, firstWave: 5, repeatEveryWaves: 10, fleetsPerSpawn: 2 },
  { tier: 23, firstWave: 5, repeatEveryWaves: 10, fleetsPerSpawn: 3 },
  { tier: 24, firstWave: 5, repeatEveryWaves: 10, fleetsPerSpawn: 3 },
] as const

export const ENEMY_TYPE_SUMMARIES: readonly EnemyTypeSummary[] = [
  { name: 'Basic', summary: 'baseline enemy with no special behavior' },
  { name: 'Fast', summary: '2x basic speed and worth 2 base coins' },
  { name: 'Tank', summary: '0.5x basic speed, 5x basic health, worth 4 base coins' },
  { name: 'Ranged', summary: 'ranged attacker worth 2 base coins' },
  { name: 'Protector', summary: 'aura blocks insta-kills and reduces nearby damage taken' },
  { name: 'Boss', summary: '0.3x speed and 20x health versus basic baseline, appears on boss waves' },
  { name: 'Vampire', summary: '2x basic health, drains 2% tower max health per second, suppresses regen effects' },
  { name: 'Ray', summary: 'basic health, charges 30 seconds then fires for 2x basic enemy damage, immune to knockback' },
  { name: 'Scatter', summary: '2x basic health and repeatedly splits with halved health' },
  { name: 'Saboteur', summary: '20x basic health and disables a random ultimate weapon on tower impact' },
  { name: 'Commander', summary: '20x basic health and buffs nearby enemies' },
  { name: 'Overcharge', summary: '20x basic health and uses escalating projectile damage behavior' },
] as const

export const ENEMY_LAB_FACTS = [
  'Common, Fast, Tank, Ranged, Boss, and Protector enemy labs can alter the baseline assumptions behind simple x-multiplier comparisons.',
  'Elite-related labs include Vampire attack and health reductions, Ray attack and health reductions, Scatter attack and health reductions, Garlic Thorns, and Lightning Amplifier interactions with Scatter.',
] as const
