/**
 * Game data — every table the game uses, as typed arrays and records.
 *
 * No I/O and no side effects: import a table and read it.
 *
 * @example
 * import { LAB_CATALOG } from 'thetowersdk/data'
 *
 * const totalCost = (lab) => (lab.levels ?? []).reduce((sum, l) => sum + (l.cost ?? 0), 0)
 */
/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    DAILY_MISSION_GOALS, DAILY_MISSION_GOALS_BY_INDEX, DailyMissionGoal, VAULT_V29_ENEMY, VAULT_V29_HARMONY, VAULT_V29_POWER, VAULT_V29_PROVENANCE, VAULT_V29_VERIFIED (+14 more)
 * depends    src/data/assets/data, src/data/battle-conditions/names, src/data/bots/data, src/data/cards/data, src/data/charts/data, src/data/currency/data (+25 more)
 * used by    —
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */

// Labs and research
export * from './labs'
export * from './labs/research-level'

// Workshop
export * from './workshop'

// Modules
export * from './modules'

// Cards, perks, relics, guardians, bots
export * from './cards/data'
export * from './perks/data'
export * from './relics/data'
export * from './daily-missions/data'
export * from './themes'
export * from './guardians'
export * from './bots/data'

// Ultimate weapons
export * from './ultimate-weapons'

// Vault
export * from './vault'

// Tabular data backing charts and calculators
export * from './charts/data'
export * from './reference/validate'
export * from './reference/data'

// Progression, economy and enemy reference data
export * from './milestones'
export * from './battle-conditions/names'
export * from './guild/data'
export * from './player-stats/recompute-order'
export * from './enemies/data'
export * from './currency/data'

// Player, assets, progression
export * from './player-stats/data'
export * from './assets/data'
export * from './tiers/data'
export * from './tournaments/data'
export * from './tiers/campaign'
export * from './glossary'

/*
 * What each daily mission ASKS for, named explicitly for the same reason the vault is: this
 * entry point does not re-export all of `generated`.
 *
 * The rewards a mission PAYS come from './daily-missions/data' above. These are the goals it
 * sets, which this package could not state at all until the game's static goal blobs resolved.
 */
export {
  DAILY_MISSION_GOALS,
  DAILY_MISSION_GOALS_BY_INDEX,
  type DailyMissionGoal,
} from './generated/daily-mission-goals.generated'

/*
 * The v29 vault, named explicitly rather than by re-exporting all of `generated`.
 *
 * That folder also holds the v28.3 game-data tables, which are imported directly by the modules
 * that need them and are deliberately not part of this entry point. Widening the barrel to reach
 * one dataset would publish a dozen others by accident.
 *
 * This data is UNVERIFIED — a developer-supplied workbook recorded ahead of the release so the
 * numbers can be checked against a v29 build. `VAULT_V29_VERIFIED` is false and stays false until
 * they have been.
 */
export {
  VAULT_V29_ENEMY,
  VAULT_V29_HARMONY,
  VAULT_V29_POWER,
  VAULT_V29_PROVENANCE,
  VAULT_V29_VERIFIED,
  type VaultV29Category,
  type VaultV29EnemyUpgrade,
  type VaultV29Status,
  type VaultV29Tree,
  type VaultV29Upgrade,
} from './generated/vault-v29.generated'

export {
  TOURNAMENT_PRIZES_V29_PROVENANCE,
  MYTHIC_TOURNAMENT_PRIZES_V29,
  PRE29_PLATINUM_TOURNAMENT_PRIZES_V29,
  PRE29_CHAMPION_TOURNAMENT_PRIZES_V29,
  PRE29_GRAND_CHAMPION_TOURNAMENT_PRIZES_V29,
  PLATINUM_TOURNAMENT_PRIZES_V29,
  CHAMPION_TOURNAMENT_PRIZES_V29,
  GRAND_CHAMPION_TOURNAMENT_PRIZES_V29,
  type TournamentPrizeEntryV29,
} from './generated/tournament-prizes-v29.generated'
