/**
 * Game data — every table the game uses, as typed arrays and records.
 *
 * No I/O and no side effects: import a table and read it.
 *
 * @example
 * import { LAB_CATALOG } from 'thetowersdk/data'
 *
 * const totalCost = (lab) => (lab.levels ?? []).reduce((sum, l) => sum + (l.cost ?? 0), 0)
 */
/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    expandAcronym, GLOSSARY, GLOSSARY_CONCEPTS, GLOSSARY_NAMES, listAmbiguousGlossaryTerms, listGlossaryByDomain, lookupGlossary, GlossaryDomain (+2 more)
 * depends    src/data/assets, src/data/battle-condition-names, src/data/bots, src/data/campaign-tier, src/data/cards, src/data/chart-tables (+47 more)
 * used by    —
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */

// Labs and research
export * from './labs'
export * from './labs-catalog'
export * from './labs-research'
export * from './labs-unlocks'
export * from './labs-categories'
export * from './labs-display-overrides'
export * from './research-lab-level'

// Workshop
export * from './workshop'
export * from './workshop-table'
export * from './workshop-costs'
export * from './workshop-tracker-definitions'
export * from './workshop-enhancement-tracker-definitions'
export * from './workshop-discount-normalize'

// Modules
export * from './modules'
export * from './module-enums'
export * from './module-levels'
export * from './module-info-catalog'
export * from './module-substats'
export * from './module-effect-resolver'

// Cards, perks, relics, guardians, bots
export * from './cards'
export * from './perks'
export * from './relics'
export * from './daily-missions'
export * from './module-pull-simulator'
export * from './themes-catalog'
export * from './themes-bonus-catalog'
export * from './guardians'
export * from './guardian-upgrades'
export * from './bots'

// Ultimate weapons
export * from './ultimate-weapons'
export * from './ultimate-weapon-stones'

// Vault
export * from './vault-tree'
export * from './vault-tree-traversal'

// Tabular data backing charts and calculators
export * from './chart-tables'
export * from './schemas'
export * from './reference-tables'

// Progression, economy and enemy reference data
export * from './milestones'
export * from './battle-condition-names'
export * from './guild'
export * from './milestone-unlocks'
export * from './tower-stat-recompute-order'
export * from './enemies'
export * from './currency'
export * from './module-costs'
export * from './module-merge'
export * from './module-bonus'

// Player, assets, progression
export * from './player-stats'
export * from './assets'
export * from './tiers'
export * from './tournaments'
export * from './campaign-tier'
export * from './tools-catalog'
export {
  expandAcronym,
  GLOSSARY,
  GLOSSARY_CONCEPTS,
  GLOSSARY_NAMES,
  listAmbiguousGlossaryTerms,
  listGlossaryByDomain,
  lookupGlossary,
  type GlossaryDomain,
  type GlossaryEntry,
  type GlossaryKind,
} from './glossary'
