/**
 * Which milestone first makes each system available.
 *
 * `MILESTONE_KEY_UNLOCK_ROWS` holds all 141 unlock rewards, but it is a flat
 * list of reward strings — good for "what does tier 12 give me", useless for
 * "when do I get modules". This is the other direction.
 *
 * ## Why only nine entries for 141 rows
 *
 * Most unlock rewards are individual LABS — Swamp Radius, Shock Chance, Missile
 * Despawn Time. The knowledge graph models `lab` as one system rather than as
 * 227 entities, so mapping each of those to a node would mean inventing 100+
 * thin nodes whose only content is a name. What matters for planning is when a
 * SYSTEM opens, and that is what this answers.
 *
 * The full per-lab detail is already in `LAB_RESEARCH_BY_INDEX`, where each lab
 * carries its own `tierUnlock` and `milestoneUnlock`.
 *
 * ## Matching
 *
 * The patterns are explicit rather than resolved by search, because search gets
 * them wrong: `Range` resolves to bot range when the reward is the tower's Range
 * lab, and `Card Presets` resolves to the card system rather than the preset
 * feature. An explicit map is checkable; a fuzzy one is a source of quiet errors.
 */
/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    MilestoneSystemUnlock, MILESTONE_SYSTEM_UNLOCKS, findMilestoneUnlockFor, NON_MILESTONE_GATES
 * depends    src/data/milestones
 * used by    src/data/index, src/knowledge/compartments/guild, src/knowledge/compartments/progression, src/mechanics/calculators/specs-generated
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
import { MILESTONE_KEY_UNLOCK_ROWS } from './milestones'

export interface MilestoneSystemUnlock {
  /** Knowledge-graph entity id, where one exists. */
  readonly system: string
  /** The reward string as the milestone table writes it. */
  readonly reward: string
  readonly tier: number
  readonly wave: number
}

/** Reward patterns that identify a system's FIRST unlock. Explicit by design. */
const SYSTEM_PATTERNS: readonly (readonly [string, RegExp])[] = [
  ['lab', /^Labs$/],
  ['tournament', /^Tournaments$/],
  ['event', /^Events$/],
  ['module', /^Modules$/],
  ['perk', /^Unlock Perks$/],
  ['guild', /^Guilds$/],
  ['workshopEnhancement', /^Workshop Enhancement$/],
  ['cardMastery', /^Card Mastery Unlock$/],
  ['assistModule', /^Assist Module$/],
]

type UnlockRow = { tier: number, wave: number, reward: string, track: string }

/**
 * The earliest milestone that unlocks each system, ordered by tier then wave.
 *
 * Every entry is on the standard track, because all 141 unlocks are — the
 * premium track pays more but gates nothing.
 */
export const MILESTONE_SYSTEM_UNLOCKS: readonly MilestoneSystemUnlock[] = SYSTEM_PATTERNS
  .map(([system, pattern]) => {
    const matches = (MILESTONE_KEY_UNLOCK_ROWS as readonly UnlockRow[])
      .filter(row => pattern.test(row.reward))
      .sort((a, b) => a.tier - b.tier || a.wave - b.wave)
    const first = matches[0]
    return first ? { system, reward: first.reward, tier: first.tier, wave: first.wave } : null
  })
  .filter((entry): entry is MilestoneSystemUnlock => entry !== null)
  .sort((a, b) => a.tier - b.tier || a.wave - b.wave)

/** When a system opens, or `null` when nothing in the table gates it. */
export function findMilestoneUnlockFor(system: string): MilestoneSystemUnlock | null {
  return MILESTONE_SYSTEM_UNLOCKS.find(entry => entry.system === system) ?? null
}

/**
 * Systems that are NOT gated by a milestone, and what gates them instead.
 *
 * Recorded because concluding "not in the milestone table, therefore available"
 * is as wrong as concluding a listed feature is available before its wave.
 */
export const NON_MILESTONE_GATES: Readonly<Record<string, string>> = {
  guardian: 'guild membership, bought with bits',
  vault: 'promotion to Legend league',
}
