/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    MODULE_SUBSTATS_CLUSTER, MODULE_EFFECT_RARITY_ROWS, MODULE_TYPE_ROWS, MODULE_EFFECT_RARITY_LABELS, MODULE_EFFECT_SLOT_INDEX_NOTE
 * depends    —
 * used by    src/data/index, src/data/module-effect-resolver, src/save/module-effects-registry
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
// Tower player-data field catalog.
// Source: tower player-data schema

export const MODULE_SUBSTATS_CLUSTER = [
  {
    'cluster': 'Attack_Speed',
    'clusterValue': 1,
    'category': 'Cannon',
    'label': 'Attack Speed',
  },
  {
    'cluster': 'Critical_Chance',
    'clusterValue': 2,
    'category': 'Cannon',
    'label': 'Critical Chance',
  },
  {
    'cluster': 'Critical_Factor',
    'clusterValue': 3,
    'category': 'Cannon',
    'label': 'Critical Factor',
  },
  {
    'cluster': 'Attack_Range',
    'clusterValue': 4,
    'category': 'Cannon',
    'label': 'Attack Range',
  },
  {
    'cluster': 'Attack_Per_Meter',
    'clusterValue': 5,
    'category': 'Cannon',
    'label': 'Damage / Meter',
  },
  {
    'cluster': 'Multishot_Chance',
    'clusterValue': 6,
    'category': 'Cannon',
    'label': 'Multishot Chance',
  },
  {
    'cluster': 'Multishot_Targets',
    'clusterValue': 7,
    'category': 'Cannon',
    'label': 'Multishot Targets',
  },
  {
    'cluster': 'Rapid_Fire_Chance',
    'clusterValue': 8,
    'category': 'Cannon',
    'label': 'Rapid Fire Chance',
  },
  {
    'cluster': 'Rapid_Fire_Duration',
    'clusterValue': 9,
    'category': 'Cannon',
    'label': 'Rapid Fire Duration',
  },
  {
    'cluster': 'Bounce_Shot_Chance',
    'clusterValue': 10,
    'category': 'Cannon',
    'label': 'Bounce Shot Chance',
  },
  {
    'cluster': 'Bounce_Shot_Targets',
    'clusterValue': 11,
    'category': 'Cannon',
    'label': 'Bounce Shot Targets',
  },
  {
    'cluster': 'Bounce_Shot_Range',
    'clusterValue': 12,
    'category': 'Cannon',
    'label': 'Bounce Shot Range',
  },
  {
    'cluster': 'Super_Critical_Chance',
    'clusterValue': 13,
    'category': 'Cannon',
    'label': 'Super Crit Chance',
  },
  {
    'cluster': 'Super_Critical_Factor',
    'clusterValue': 14,
    'category': 'Cannon',
    'label': 'Super Crit Multi',
  },
  {
    'cluster': 'Rend_Armor_Chance',
    'clusterValue': 15,
    'category': 'Cannon',
    'label': 'Rend Armor Chance',
  },
  {
    'cluster': 'Rend_Armor_Mult',
    'clusterValue': 16,
    'category': 'Cannon',
    'label': 'Rend Armor Mult',
  },
  {
    'cluster': 'Rend_Armor_Max',
    'clusterValue': 17,
    'category': 'Cannon',
    'label': 'Max Rend Armor Multi',
  },
  {
    'cluster': 'Health_Regen',
    'clusterValue': 18,
    'category': 'Armor',
    'label': 'Health Regen',
  },
  {
    'cluster': 'Defense_Percent',
    'clusterValue': 19,
    'category': 'Armor',
    'label': 'Defense',
  },
  {
    'cluster': 'Defense_Absolute',
    'clusterValue': 20,
    'category': 'Armor',
    'label': 'Defense Absolute',
  },
  {
    'cluster': 'Thorn_Damage',
    'clusterValue': 21,
    'category': 'Armor',
    'label': 'Thorns Damage',
  },
  {
    'cluster': 'Lifesteal',
    'clusterValue': 22,
    'category': 'Armor',
    'label': 'Lifesteal',
  },
  {
    'cluster': 'Knockback_Chance',
    'clusterValue': 23,
    'category': 'Armor',
    'label': 'Knockback Chance',
  },
  {
    'cluster': 'Knockback_Force',
    'clusterValue': 24,
    'category': 'Armor',
    'label': 'Knockback Force',
  },
  {
    'cluster': 'Orb_Speed',
    'clusterValue': 25,
    'category': 'Armor',
    'label': 'Orb Speed',
  },
  {
    'cluster': 'Orbs',
    'clusterValue': 26,
    'category': 'Armor',
    'label': 'Orbs',
  },
  {
    'cluster': 'Shockwave_Size',
    'clusterValue': 27,
    'category': 'Armor',
    'label': 'Shockwave Size',
  },
  {
    'cluster': 'Shockwave_Frequency',
    'clusterValue': 28,
    'category': 'Armor',
    'label': 'Shockwave Frequency',
  },
  {
    'cluster': 'Land_Mine_Chance',
    'clusterValue': 29,
    'category': 'Armor',
    'label': 'Land Mine Chance',
  },
  {
    'cluster': 'Land_Mine_Damage',
    'clusterValue': 30,
    'category': 'Armor',
    'label': 'Land Mine Damage',
  },
  {
    'cluster': 'Land_Mine_Radius',
    'clusterValue': 31,
    'category': 'Armor',
    'label': 'Land Mine Radius',
  },
  {
    'cluster': 'Death_Defy',
    'clusterValue': 32,
    'category': 'Armor',
    'label': 'Death Defy',
  },
  {
    'cluster': 'Wall_Health',
    'clusterValue': 33,
    'category': 'Armor',
    'label': 'Wall Health',
  },
  {
    'cluster': 'Wall_Rebuild',
    'clusterValue': 34,
    'category': 'Armor',
    'label': 'Wall Rebuild',
  },
  {
    'cluster': 'Cash_Bonus',
    'clusterValue': 35,
    'category': 'Generator',
    'label': 'Cash Bonus',
  },
  {
    'cluster': 'Cash_Per_Wave',
    'clusterValue': 36,
    'category': 'Generator',
    'label': 'Cash / Wave',
  },
  {
    'cluster': 'Coins_Per_Kill',
    'clusterValue': 37,
    'category': 'Generator',
    'label': 'Coins / Kill Bonus',
  },
  {
    'cluster': 'Coins_Per_Wave',
    'clusterValue': 38,
    'category': 'Generator',
    'label': 'Coins / Wave',
  },
  {
    'cluster': 'Free_Attack_Upgrade',
    'clusterValue': 39,
    'category': 'Generator',
    'label': 'Free Attack Upgrade',
  },
  {
    'cluster': 'Free_Defense_Upgrade',
    'clusterValue': 40,
    'category': 'Generator',
    'label': 'Free Defense Upgrade',
  },
  {
    'cluster': 'Free_Utility_Upgrade',
    'clusterValue': 41,
    'category': 'Generator',
    'label': 'Free Utility Upgrade',
  },
  {
    'cluster': 'Interest_Per_Wave',
    'clusterValue': 42,
    'category': 'Generator',
    'label': 'Interest / Wave',
  },
  {
    'cluster': 'Recovery_Amount',
    'clusterValue': 43,
    'category': 'Generator',
    'label': 'Recovery Amount',
  },
  {
    'cluster': 'Max_Recovery',
    'clusterValue': 44,
    'category': 'Generator',
    'label': 'Max Recovery',
  },
  {
    'cluster': 'Package_Chance',
    'clusterValue': 45,
    'category': 'Generator',
    'label': 'Package Chance',
  },
  {
    'cluster': 'Enemy_Attack_Level_Skip',
    'clusterValue': 46,
    'category': 'Generator',
    'label': 'Enemy Attack Level Skip',
  },
  {
    'cluster': 'Enemy_Health_Level_Skip',
    'clusterValue': 47,
    'category': 'Generator',
    'label': 'Enemy Health Level Skip',
  },
  {
    'cluster': 'Chain_Lightning_Damage',
    'clusterValue': 48,
    'category': 'Core',
    'label': 'Chain Lightning - Damage',
  },
  {
    'cluster': 'Chain_Lightning_Quantity',
    'clusterValue': 49,
    'category': 'Core',
    'label': 'Chain Lightning - Quantity',
  },
  {
    'cluster': 'Chain_Lightning_Chance',
    'clusterValue': 50,
    'category': 'Core',
    'label': 'Chain Lightning - Chance',
  },
  {
    'cluster': 'Smart_Missiles_Damage',
    'clusterValue': 51,
    'category': 'Core',
    'label': 'Smart Missiles - Damage',
  },
  {
    'cluster': 'Smart_Missiles_Quantity',
    'clusterValue': 52,
    'category': 'Core',
    'label': 'Smart Missiles - Quantity',
  },
  {
    'cluster': 'Smart_Missiles_Cooldown',
    'clusterValue': 53,
    'category': 'Core',
    'label': 'Smart Missiles - Cooldown',
  },
  {
    'cluster': 'Death_Wave_Damage',
    'clusterValue': 54,
    'category': 'Core',
    'label': 'Death Wave - Damage',
  },
  {
    'cluster': 'Death_Wave_Quantity',
    'clusterValue': 55,
    'category': 'Core',
    'label': 'Death Wave - Quantity',
  },
  {
    'cluster': 'Death_Wave_Cooldown',
    'clusterValue': 56,
    'category': 'Core',
    'label': 'Death Wave - Cooldown',
  },
  {
    'cluster': 'Chrono_Field_Duration',
    'clusterValue': 57,
    'category': 'Core',
    'label': 'Chrono Field - Duration',
  },
  {
    'cluster': 'Chrono_Field_Speed_Reduction',
    'clusterValue': 58,
    'category': 'Core',
    'label': 'Chrono Field - Speed Reduction',
  },
  {
    'cluster': 'Chrono_Field_Cooldown',
    'clusterValue': 59,
    'category': 'Core',
    'label': 'Chrono Field - Cooldown',
  },
  {
    'cluster': 'Inner_Land_Mines_Damage',
    'clusterValue': 60,
    'category': 'Core',
    'label': 'Inner Land Mines - Damage',
  },
  {
    'cluster': 'Inner_Land_Mines_Quantity',
    'clusterValue': 61,
    'category': 'Core',
    'label': 'Inner Land Mines - Quantity',
  },
  {
    'cluster': 'Inner_Land_Mines_Cooldown',
    'clusterValue': 62,
    'category': 'Core',
    'label': 'Inner Land Mines - Cooldown',
  },
  {
    'cluster': 'Golden_Tower_Bonus',
    'clusterValue': 63,
    'category': 'Core',
    'label': 'Golden Tower - Bonus',
  },
  {
    'cluster': 'Golden_Tower_Duration',
    'clusterValue': 64,
    'category': 'Core',
    'label': 'Golden Tower - Duration',
  },
  {
    'cluster': 'Golden_Tower_Cooldown',
    'clusterValue': 65,
    'category': 'Core',
    'label': 'Golden Tower - Cooldown',
  },
  {
    'cluster': 'Poison_Swamp_Damage',
    'clusterValue': 66,
    'category': 'Core',
    'label': 'Poison Swamp - Damage',
  },
  {
    'cluster': 'Poison_Swamp_Duration',
    'clusterValue': 67,
    'category': 'Core',
    'label': 'Poison Swamp - Duration',
  },
  {
    'cluster': 'Poison_Swamp_Cooldown',
    'clusterValue': 68,
    'category': 'Core',
    'label': 'Poison Swamp - Cooldown',
  },
  {
    'cluster': 'Black_Hole_Size',
    'clusterValue': 69,
    'category': 'Core',
    'label': 'Black Hole - Size',
  },
  {
    'cluster': 'Black_Hole_Duration',
    'clusterValue': 70,
    'category': 'Core',
    'label': 'Black Hole - Duration',
  },
  {
    'cluster': 'Black_Hole_Cooldown',
    'clusterValue': 71,
    'category': 'Core',
    'label': 'Black Hole - Cooldown',
  },
  {
    'cluster': 'Spotlight_Bonus',
    'clusterValue': 72,
    'category': 'Core',
    'label': 'Spotlight - Bonus',
  },
  {
    'cluster': 'Spotlight_Angle',
    'clusterValue': 73,
    'category': 'Core',
    'label': 'Spotlight - Angle',
  },
  {
    'cluster': 'Spotlight_Quantity',
    'clusterValue': 74,
    'category': 'Core',
    'label': 'Spotlight Quantity',
  },
] as const

export const MODULE_EFFECT_RARITY_ROWS = [
  {
    'name': 'Common',
    'value': 1,
  },
  {
    'name': 'Rare',
    'value': 2,
  },
  {
    'name': 'Epic',
    'value': 4,
  },
  {
    'name': 'Legendary',
    'value': 6,
  },
  {
    'name': 'Mythic',
    'value': 8,
  },
  {
    'name': 'Ancestral',
    'value': 10,
  },
] as const

export const MODULE_TYPE_ROWS = [
  {
    'name': 'Cannon',
    'value': 0,
  },
  {
    'name': 'Armor',
    'value': 1,
  },
  {
    'name': 'Generator',
    'value': 2,
  },
  {
    'name': 'Core',
    'value': 3,
  },
] as const

/** Map effect rarity enum value to tracker substat rarity labels. */
export const MODULE_EFFECT_RARITY_LABELS: Record<number, string> = {
  1: 'Common',
  2: 'Rare',
  4: 'Epic',
  6: 'Legendary',
  8: 'Mythic',
  10: 'Ancestral',
}

/**
 * Module effect slots store an index into the module effects catalog,
 * NOT a SubstatsCluster value directly. Each table row is a ModuleEffect:
 * { type, rarity: EffectRarity, benefit, benefitType, clusterIndex: SubstatsCluster }.
 */
export const MODULE_EFFECT_SLOT_INDEX_NOTE =
  'Effect slot indexes the module effects catalog (cluster + rarity per row).'
