/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    ThemeItem, ThemeBonusGroup, THEME_CATEGORY_BONUS, TOWER, BACKGROUND, MILESTONE, SONGS, GUARDIAN (+5 more)
 * depends    —
 * used by    src/data/index, src/knowledge/compartments/themes, src/mechanics/calculators/specs-generated
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
/**
 * Tower theme catalog — every cosmetic that pays a passive coin bonus.
 *
 * Game data, sourced from `tower-asset-tables.json`.
 *
 * The per-item `bonus` literal is gone. Every entry in a category carried the
 * same string — 169 of them encoding 7 numbers — so changing a category's rate
 * left the rest silently wrong. The rate lives once per category in
 * `THEME_CATEGORY_BONUS` and each item's bonus is derived from it.
 */

export type ThemeItem = { name: string, event?: string, pass?: string }

/**
 * How themes are grouped for bonus purposes.
 *
 * Three related types exist and they are not interchangeable — check which one
 * you want before importing:
 *
 * - **`ThemeBonusGroup`** (here) — the seven catalog groups a theme is listed
 *   under, each with one passive coin rate. Includes `MILESTONE`, which is how
 *   a tower theme was earned rather than a separate cosmetic slot.
 * - **`ThemeCategoryKey`** (`themes-catalog.ts`) — the four categories the coin
 *   formula multiplies over. No milestone: those themes count as tower.
 * - **`ThemeCatalogCategory`** (`save/catalogs/themes.ts`) — the categories a
 *   save file stores unlocks under, including `song` and `profileBanner`.
 *
 * A test asserts the four overlapping rates agree with the coin formula.
 * Unifying all three is worthwhile but would change save parsing, so it has
 * not been attempted here.
 */
export type ThemeBonusGroup =
  | 'TOWER'
  | 'BACKGROUND'
  | 'MILESTONE'
  | 'SONGS'
  | 'GUARDIAN'
  | 'MENU'
  | 'PROFILE_BANNER'

/**
 * Passive coin bonus per owned theme, by catalog category.
 *
 * The four that overlap `THEME_CATEGORY_DEFINITIONS` (tower, background, menu,
 * guardian) must agree with it; a test asserts that rather than trusting it.
 */
export const THEME_CATEGORY_BONUS = {
  TOWER: '+0.4%',
  BACKGROUND: '+0.8%',
  MILESTONE: '+0.4%',
  SONGS: '+0.6%',
  GUARDIAN: '+0.6%',
  MENU: '+0.6%',
  PROFILE_BANNER: '+0.6%',
} as const satisfies Record<ThemeBonusGroup, string>

export const TOWER: ThemeItem[] = [
  { name: 'Star', event: 'Interstellar' },
  { name: 'Eye of the Lord', event: 'Volcano' },
  { name: 'Plasma Ball', event: 'Plasma Returns' },
  { name: 'Bee', event: 'Honey' },
  { name: 'North Spirit', event: 'Aurora' },
  { name: 'Alien', event: 'Aliens' },
  { name: 'Water Droplet', event: 'Ocean Night' },
  { name: 'Cherry Blossom', event: 'Sakura' },
  { name: 'Bunny', event: 'Easter' },
  { name: 'Neo Turbo', event: 'Retrowave' },
  { name: 'Prisma', event: 'Prismatic Lines' },
  { name: 'Spider', event: 'Cobweb' },
  { name: 'Sentinel', event: 'Into the Matrix' },
  { name: 'Howling Wolf', event: 'Full Moon' },
  { name: 'Virus', event: 'Viral Outbreak' },
  { name: 'Hourglass', event: 'Sands of Time' },
  { name: 'Pumpkin', event: 'Halloween' },
  { name: 'Autumn Leaf', event: 'Autumn' },
  { name: 'Invader', event: 'Retro Arcade' },
  { name: 'Toast Glass', event: 'New Year' },
  { name: 'Dark Tower', event: 'Dark Strands' },
  { name: 'Dive Helmet', event: 'Deep Blue Sea' },
  { name: 'Starship', event: 'Faster Than Light' },
  { name: 'Elite Tower', event: 'Invaders' },
  { name: 'Fisherman', event: 'Sunset Fishing' },
  { name: 'Storm Eye', event: 'Into The Storm' },
  { name: 'Umbrella', event: 'Rainfall' },
  { name: 'Noise Tower', event: "Tower's Channel" },
  { name: 'Unlucky Cow', event: 'Abduction' },
  { name: 'Snowman', event: 'Snowstorm' },
  { name: 'Black Cat', event: 'Meowy Night' },
  { name: 'Black Hole', event: 'Gravity' },
  { name: 'Pocket Watch', event: 'What Time Is It?' },
  { name: 'Crown', event: 'Guild Season 1' },
  { name: 'Neon π' },
  { name: 'Mech Warrior', event: 'Guild Season 2' },
  { name: 'Marshmallow', event: 'Camping' },
  { name: 'Cthulhu', event: 'Cthulhu' },
  { name: 'Frog', event: 'Koi Pond' },
  { name: 'DJ' },
  { name: '4th Anniversary' },
  { name: 'Pixel Soldier', event: 'Guild Season 4' },
  { name: 'Flying Car', event: 'Cyberpunk' },
  { name: 'Crystal', event: 'Crystal Cave' },
  { name: 'Balloon', event: 'Amusement Park' },
  { name: 'Restless Eye', event: 'Guild Season 5' },
  { name: 'Shining Star', event: 'Guild Season 6' },
  { name: 'Heart' },
  { name: 'Glitch' },
  { name: 'Space Telescope', event: 'Guild Season 7' },
  { name: 'Bear' },
  { name: 'Brain' },
  { name: 'Rabbit In Hat' },
  { name: 'Cake' },
]

export const BACKGROUND: ThemeItem[] = [
  { name: 'Interstellar', event: 'Interstellar' },
  { name: 'Volcano', event: 'Volcano' },
  { name: 'Plasma Field', event: 'Plasma Returns' },
  { name: 'Honeycomb', event: 'Honey' },
  { name: 'Aurora', event: 'Aurora' },
  { name: 'Alien Ship', event: 'Aliens' },
  { name: 'Ocean Night', event: 'Ocean Night' },
  { name: 'Sakura', event: 'Sakura' },
  { name: 'Easter', event: 'Easter' },
  { name: 'Retrowave', event: 'Retrowave' },
  { name: 'Prismatic Lines', event: 'Prismatic Lines' },
  { name: 'Cobweb', event: 'Cobweb' },
  { name: 'Matrix', event: 'Into the Matrix' },
  { name: 'Mountain Night', event: 'Full Moon' },
  { name: 'Virus Field', event: 'Viral Outbreak' },
  { name: 'Sand Storm' },
  { name: 'Haunted House', event: 'Halloween' },
  { name: 'Autumn Forest', event: 'Autumn' },
  { name: 'Arcade', event: 'Retro Arcade' },
  { name: 'New Year', event: 'New Year' },
  { name: 'Dark Strands', event: 'Dark Strands' },
  { name: 'Deep Sea', event: 'Deep Blue Sea' },
  { name: 'Hyper Space', event: 'Faster Than Light' },
  { name: 'Invasion', event: 'Invaders' },
  { name: 'Sunset River', event: 'Sunset Fishing' },
  { name: 'Hurricane', event: 'Into The Storm' },
  { name: 'Rainfall', event: 'Rainfall' },
  { name: 'TV Wall', event: "Tower's Channel" },
  { name: 'Abduction', event: 'Abduction' },
  { name: 'Snowstorm', event: 'Snowstorm' },
  { name: 'Forest of Cats', event: 'Meowy Night' },
  { name: 'Event Horizon', event: 'Gravity' },
  { name: 'Clock Tower', event: 'What Time Is It?' },
  { name: 'Throne Room', event: 'Guild Season 1' },
  { name: 'π Disk' },
  { name: 'Mech World', event: 'Guild Season 2' },
  { name: 'Camping', event: 'Camping' },
  { name: 'Cthulhu', event: 'Cthulhu' },
  { name: 'Koi Pond', event: 'Koi Pond' },
  { name: 'Party', event: 'Guild Season 3' },
  { name: 'Pixel Alien War', event: 'Guild Season 4' },
  { name: 'Cyberpunk', event: 'Cyberpunk' },
  { name: 'Crystal Cave', event: 'Crystal Cave' },
  { name: 'Amusement Park', event: 'Amusement Park' },
  { name: 'Crimson Horror', event: 'Guild Season 5' },
  { name: 'Cozy Cosmos', event: 'Guild Season 6' },
  { name: 'Valentine' },
  { name: 'Glitch' },
  { name: 'Supernova', event: 'Guild Season 7' },
  { name: 'Claw Machine' },
  { name: 'Neuron' },
  { name: 'Magician' },
  { name: '5th Anniversary' },
]

export const MILESTONE: ThemeItem[] = [
  { name: 'Shuriken', event: 'Tier 1', pass: 'Free' },
  { name: 'Donut', event: 'Tier 2', pass: 'Pass 1' },
  { name: 'Yin-Yang', event: 'Tier 3', pass: 'Free' },
  { name: 'Smile', event: 'Tier 4', pass: 'Free' },
  { name: 'Butterfly', event: 'Tier 5', pass: 'Pass 2' },
  { name: 'Sheep', event: 'Tier 6', pass: 'Free' },
  { name: 'Fried Egg', event: 'Tier 7', pass: 'Free' },
  { name: 'Mush-mush', event: 'Tier 8', pass: 'Pass 3' },
  { name: 'Turtle', event: 'Tier 9', pass: 'Free' },
  { name: 'Cheese', event: 'Tier 10', pass: 'Free' },
  { name: 'Creepy Clown', event: 'Tier 13', pass: 'Free' },
  { name: 'Cat', event: 'Tier 11', pass: 'Pass 4' },
  { name: 'Skull', event: 'Tier 12', pass: 'Free' },
  { name: 'Panda', event: 'Tier 14', pass: 'Pass 5' },
  { name: 'Tech Tree', event: 'Tier 15', pass: 'Free' },
  { name: 'Cactus', event: 'Tier 16', pass: 'Free' },
  { name: 'Dragon', event: 'Tier 17', pass: 'Pass 6' },
  { name: 'Rhino', event: 'Tier 18', pass: 'Free' },
  { name: 'Atomic', event: 'Tier 19', pass: 'Free' },
  { name: 'Cyber', event: 'Tier 20', pass: 'Pass 7' },
  { name: 'Eclipse', event: 'Tier 21', pass: 'Free' },
]

export const SONGS: ThemeItem[] = [
  { name: 'Krisu - Oceans Sings', event: 'Event Store' },
  { name: 'Krisu - Hiding in Himalaya', event: 'Event Store' },
  { name: 'Krisu - Forest Bathing', event: 'Event Store' },
]

export const GUARDIAN: ThemeItem[] = [
  { name: 'Orbie' },
  { name: 'Butter', event: 'Guild Season 1' },
  { name: 'Muse', event: 'Guild Season 2' },
  { name: 'Harriot' },
  { name: 'Finn', event: 'Guild Season 2' },
  { name: 'Nyra', event: 'Guild Season 3' },
  { name: 'Rolo', event: 'Guild Season 3' },
  { name: 'Glenn', event: 'Guild Season 4' },
  { name: 'Zepe', event: 'Guild Season 4' },
  { name: 'Iris', event: 'Guild Season 5' },
  { name: 'Silk', event: 'Guild Season 5' },
  { name: 'Mickey', event: 'Guild Season 6' },
  { name: 'Gaia', event: 'Guild Season 6' },
  { name: 'Arwing', event: 'Guild Season 7' },
  { name: 'Frank', event: 'Guild Season 7' },
  { name: 'Earl' },
  { name: 'Mei' },
  { name: 'Shelly' },
  { name: 'Disco' },
]

export const MENU: ThemeItem[] = [
  { name: 'Dark Being', event: 'Guild Season 1' },
  { name: 'Mech World', event: 'Guild Season 2' },
  { name: 'Party', event: 'Guild Season 3' },
  { name: 'Pixel Alien War', event: 'Guild Season 4' },
  { name: 'Crimson Horror', event: 'Guild Season 5' },
  { name: 'Cozy Cosmos' },
  { name: 'Supernova', event: 'Guild Season 7' },
  { name: 'Claw Machine' },
  { name: 'Magician' },
]

export const PROFILE_BANNER: ThemeItem[] = [
  { name: 'Arcade Banner' },
  { name: 'What Time Is It Banner' },
  { name: 'Mech World', event: 'Guild Season 2' },
  { name: 'Party', event: 'Guild Season 3' },
  { name: 'Pixel Alien War', event: 'Guild Season 4' },
  { name: 'Crimson Horror', event: 'Guild Season 5' },
  { name: 'Cozy Cosmos' },
  { name: 'Supernova', event: 'Guild Season 7' },
  { name: 'Claw Machine' },
  { name: 'Magician' },
]

export const THEMES = {
  TOWER,
  BACKGROUND,
  MILESTONE,
  SONGS,
  GUARDIAN,
  MENU,
  PROFILE_BANNER,
} as const

export type ThemeBonusCatalogEntry = {
  name: string
  category: ThemeBonusGroup
  bonus: string
}

/** Flat theme/song catalog for passive bonus aggregation. */
export function listThemeBonusCatalogEntries(): readonly ThemeBonusCatalogEntry[] {
  const rows: ThemeBonusCatalogEntry[] = []
  for (const [category, group] of Object.entries(THEMES) as [ThemeBonusGroup, ThemeItem[]][]) {
    for (const item of group) {
      rows.push({ name: item.name, category, bonus: THEME_CATEGORY_BONUS[category] })
    }
  }
  return rows
}
