/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    VaultTreeChildSort, POWER_VAULT_TIER_UNLOCK_NODE_IDS, buildVaultTreeChildrenMap, buildVaultTreeBfsOrder, buildVaultTreeBfsSlotIndexById, buildVaultPowerLevelSlotIndexById
 * depends    src/data/vault-tree
 * used by    src/data/index, src/mechanics/calculators/specs-generated, src/save/catalogs/vault, src/save/catalogs/vault-power, src/save/vault
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
import type { VaultTreeNode } from './vault-tree'

export type VaultTreeChildSort = 'col-row' | 'row-col'

/** Tier unlock rows exist in the tree graph but levels come from tier unlock flags in save import. */
export const POWER_VAULT_TIER_UNLOCK_NODE_IDS: ReadonlySet<string> = new Set(['tier2', 'tier3'])

export function buildVaultTreeChildrenMap(nodes: readonly VaultTreeNode[]): Map<string, string[]> {
  const children = new Map<string, string[]>()
  for (const node of nodes) {
    for (const parentId of node.parents) {
      const list = children.get(parentId) ?? []
      list.push(node.id)
      children.set(parentId, list)
    }
  }
  return children
}

function sortVaultTreeChildIds(
  ids: string[],
  byId: ReadonlyMap<string, VaultTreeNode>,
  childSort: VaultTreeChildSort,
): string[] {
  return ids.slice().sort((leftId, rightId) => {
    const left = byId.get(leftId)!
    const right = byId.get(rightId)!
    if (childSort === 'col-row') {
      return left.col - right.col || left.row - right.row || leftId.localeCompare(rightId)
    }
    return left.row - right.row || left.col - right.col || leftId.localeCompare(rightId)
  })
}

function sortVaultTreeRoots(nodes: readonly VaultTreeNode[], childSort: VaultTreeChildSort): VaultTreeNode[] {
  return nodes
    .filter(node => node.parents.length === 0)
    .slice()
    .sort((left, right) => {
      if (childSort === 'col-row') {
        return left.col - right.col || left.row - right.row || left.id.localeCompare(right.id)
      }
      return left.row - right.row || left.col - right.col || left.id.localeCompare(right.id)
    })
}

/**
 * Breadth-first walk of the vault tree using parent links and grid position for sibling order.
 * This is the save serialization order — not chart document row order.
 */
export function buildVaultTreeBfsOrder(
  nodes: readonly VaultTreeNode[],
  childSort: VaultTreeChildSort = 'col-row',
): string[] {
  const byId = new Map(nodes.map(node => [node.id, node]))
  const children = buildVaultTreeChildrenMap(nodes)
  const roots = sortVaultTreeRoots(nodes, childSort)
  const order: string[] = []
  const seen = new Set<string>()
  const queue = roots.map(node => node.id)

  while (queue.length > 0) {
    const id = queue.shift()!
    if (seen.has(id)) continue
    seen.add(id)
    order.push(id)
    queue.push(...sortVaultTreeChildIds(children.get(id) ?? [], byId, childSort))
  }

  for (const node of nodes) {
    if (!seen.has(node.id)) order.push(node.id)
  }
  return order
}

export function buildVaultTreeBfsSlotIndexById(
  nodes: readonly VaultTreeNode[],
  childSort: VaultTreeChildSort = 'col-row',
): Record<string, number> {
  const order = buildVaultTreeBfsOrder(nodes, childSort)
  return Object.fromEntries(order.map((id, index) => [id, index]))
}

function countPriorTier2UnlockNodes(bfsOrder: readonly string[], bfsIndex: number): number {
  let count = 0
  for (let i = 0; i < bfsIndex; i++) {
    if (bfsOrder[i] === 'tier2') count++
  }
  return count
}

/**
 * Power `powerNodesLevel` / `powerNodesUnlocked` slot per node.
 * BFS parent-child walk: tier unlock rows use tier2Unlock / tier3Unlock flags.
 * Pre-tier3 branch skips only the tier2 row from level slots; post-tier3 uses full BFS indices.
 */
export function buildVaultPowerLevelSlotIndexById(
  nodes: readonly VaultTreeNode[],
  childSort: VaultTreeChildSort = 'col-row',
): Record<string, number> {
  const bfsOrder = buildVaultTreeBfsOrder(nodes, childSort)
  const tier3BfsIndex = bfsOrder.indexOf('tier3')
  const indexById: Record<string, number> = {}
  for (let bfsIndex = 0; bfsIndex < bfsOrder.length; bfsIndex++) {
    const id = bfsOrder[bfsIndex]!
    if (POWER_VAULT_TIER_UNLOCK_NODE_IDS.has(id)) {
      indexById[id] = bfsIndex
      continue
    }
    if (tier3BfsIndex >= 0 && bfsIndex > tier3BfsIndex) {
      indexById[id] = bfsIndex
      continue
    }
    indexById[id] = bfsIndex - countPriorTier2UnlockNodes(bfsOrder, bfsIndex)
  }
  return indexById
}
