/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    WorkshopCategory, WorkshopLevelEntry, WorkshopStatDefinition, getWorkshopStatDefinitions, getWorkshopStatDefinitionByKey, getWorkshopUtilityLevelSkipChance
 * depends    src/data/workshop.json, src/mechanics/enemy-level-skip
 * used by    src/data/index, src/data/workshop-enhancement-tracker-definitions, src/mechanics/calculators/run, src/mechanics/calculators/specs-generated, src/mechanics/els-calculator-options, src/mechanics/els-upgrade-path (+5 more)
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
import { LEVEL_SKIP_WORKSHOP_BASE } from '../mechanics/enemy-level-skip'
import workshopData from './workshop.json'

export type WorkshopCategory = 'attack' | 'defense' | 'utility'

export interface WorkshopLevelEntry {
  level: number
  value: number
  cash: number
  coins: number
}

export interface WorkshopStatDefinition {
  key: string
  label: string
  category: WorkshopCategory
  levels: WorkshopLevelEntry[]
  minLevel: number
  maxLevel: number
}

const CATEGORY_STATS: Record<WorkshopCategory, Array<{ label: string; key: string }>> = {
  attack: [
    { label: 'Damage', key: 'Damage' },
    { label: 'Attack Speed', key: 'Attack Speed' },
    { label: 'Critical Chance', key: 'Critical Chance' },
    { label: 'Critical Factor', key: 'Critical Factor' },
    { label: 'Range', key: 'Range' },
    { label: 'Damage / Meter', key: 'Damage / Meter' },
    { label: 'Multishot Chance', key: 'Multishot Chance' },
    { label: 'Multishot Targets', key: 'Multishot Targets' },
    { label: 'Rapid Fire Chance', key: 'Rapid Fire Chance' },
    { label: 'Rapid Fire Duration', key: 'Rapid Fire Duration' },
    { label: 'Bounce Shot Chance', key: 'Bounce Shot Chance' },
    { label: 'Bounce Shot Targets', key: 'Bounce Shot Targets' },
    { label: 'Bounce Shot Range', key: 'Bounce Shot Range' },
    { label: 'Super Crit Chance', key: 'Super Crit Chance' },
    { label: 'Super Crit Mult', key: 'Super Crit Mult' },
    { label: 'Rend Armor Chance', key: 'Rend Armor Chance' },
    { label: 'Rend Armor Mult', key: 'Rend Armor Mult' },
  ],
  defense: [
    { label: 'Health', key: 'Health' },
    { label: 'Health Regen', key: 'Health Regen' },
    { label: 'Defense %', key: 'Defense Percent' },
    { label: 'Defense Absolute', key: 'Defense Absolute' },
    { label: 'Thorn Damage', key: 'Thorns' },
    { label: 'Lifesteal', key: 'Lifesteal' },
    { label: 'Knockback Chance', key: 'Knockback Chance' },
    { label: 'Knockback Force', key: 'Knockback Force' },
    { label: 'Orb Speed', key: 'Orb Speed' },
    { label: 'Orbs', key: 'Orbs' },
    { label: 'Shockwave Size', key: 'Shockwave Size' },
    { label: 'Shockwave Frequency', key: 'Shockwave Frequency' },
    { label: 'Land Mine Chance', key: 'Land Mine Chance' },
    { label: 'Land Mine Damage', key: 'Land Mine Damage' },
    { label: 'Land Mine Radius', key: 'Land Mine Radius' },
    { label: 'Wall Health', key: 'Wall Health' },
    { label: 'Wall Rebuild', key: 'Wall Rebuild' },
  ],
  utility: [
    { label: 'Cash Bonus', key: 'Cash Bonus' },
    { label: 'Cash / Wave', key: 'Cash / Wave' },
    { label: 'Coins / Kill Bonus', key: 'Coins / Kill Bonus' },
    { label: 'Coins / Wave', key: 'Coins / Wave' },
    { label: 'Free Attack Upgrade', key: 'Free Attack Upgrade' },
    { label: 'Free Defense Upgrade', key: 'Free Defense Upgrade' },
    { label: 'Free Utility Upgrade', key: 'Free Utility Upgrade' },
    { label: 'Interest / Wave', key: 'Interest / Wave' },
    { label: 'Recovery Amount', key: 'Recovery Amount' },
    { label: 'Max Recovery', key: 'Max Recovery' },
    { label: 'Package Chance', key: 'Package Chance' },
    { label: 'Enemy Attack Level Skip', key: 'Enemy Attack Level Skip' },
    { label: 'Enemy Health Level Skip', key: 'Enemy Health Level Skip' },
  ],
}

function toNumber(value: unknown): number {
  const next = Number(value)
  return Number.isFinite(next) ? next : 0
}

function buildStatDefinition(category: WorkshopCategory, label: string, key: string): WorkshopStatDefinition | null {
  const raw = (workshopData as Record<string, unknown>)[key]
  if (!raw || typeof raw !== 'object') return null

  const entries = Object.entries(raw as Record<string, unknown>)
    .map(([levelKey, payload]) => {
      const level = Number(levelKey)
      const obj = payload && typeof payload === 'object' ? payload as Record<string, unknown> : {}
      return {
        level,
        value: toNumber(obj['value']),
        cash: toNumber(obj['cash']),
        coins: toNumber(obj['coins']),
      }
    })
    .filter(entry => Number.isFinite(entry.level))
    .sort((a, b) => a.level - b.level)

  if (entries.length === 0) return null

  return {
    key,
    label,
    category,
    levels: entries,
    minLevel: entries[0].level,
    maxLevel: entries[entries.length - 1].level,
  }
}

const WORKSHOP_STAT_DEFINITIONS: WorkshopStatDefinition[] = (Object.entries(CATEGORY_STATS) as Array<[WorkshopCategory, Array<{ label: string; key: string }>]> )
  .flatMap(([category, stats]) => stats
    .map(stat => buildStatDefinition(category, stat.label, stat.key))
    .filter((value): value is WorkshopStatDefinition => Boolean(value)))

export function getWorkshopStatDefinitions(): WorkshopStatDefinition[] {
  return WORKSHOP_STAT_DEFINITIONS
}

export function getWorkshopStatDefinitionByKey(key: string): WorkshopStatDefinition | null {
  return WORKSHOP_STAT_DEFINITIONS.find(stat => stat.key === key) ?? null
}

/**
 * Out-of-round level skip chance for utility ELS stats from `workshop.json`.
 * Preview chance = workshop.json `value` at level L (= 0.0005 + L × 0.0005 for utility ELS).
 */
export function getWorkshopUtilityLevelSkipChance(statKey: string, utilityLevel: number): number | null {
  const stat = getWorkshopStatDefinitionByKey(statKey)
  if (!stat || stat.levels.length === 0) return null

  const level = Math.max(0, Math.floor(utilityLevel))
  const clampedLevel = Math.min(level, stat.maxLevel)
  const row = stat.levels.find(entry => entry.level === clampedLevel)
  const baseRow = stat.levels.find(entry => entry.level === stat.minLevel) ?? stat.levels[0]
  if (!row || !baseRow) return null

  return LEVEL_SKIP_WORKSHOP_BASE + row.value - baseRow.value
}
