/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    PACKAGE_ROOT, SRC, MECHANICS, SAVE, TOOLING, MONOREPO_ROOT
 * depends    —
 * used by    tooling/coverage/build-inventories, tooling/coverage/ep-citations, tooling/coverage/oracle-links, tooling/debug-graph/session, tooling/debug-graph/trace, tooling/sdk-graph/sheet-drift-mutate
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
import path from 'node:path'

/**
 * Where things are, for tooling that reads the repository it lives in.
 *
 * These modules used to sit under `src/mechanics/` and count `'..'` from there — five of them to
 * reach the monorepo, two to reach the source tree. Moving them one level up made every one of
 * those counts wrong at once, and wrong in a way that reads as missing data rather than as a bad
 * path: `scandir 'packages/src/mechanics'` and `looked in packages/src/save`.
 *
 * Naming the roots once means the next move edits this file and nothing else. It is the same
 * arrangement `tests/helpers/paths.ts` uses, for the same reason.
 */
const HERE = __dirname

/** `packages/sdk` — the package this tooling belongs to. */
export const PACKAGE_ROOT = path.resolve(HERE, '..')

/** The shipped source tree. Tooling reads it; nothing in it may read tooling. */
export const SRC = path.join(PACKAGE_ROOT, 'src')
export const MECHANICS = path.join(SRC, 'mechanics')
export const SAVE = path.join(SRC, 'save')
export const TOOLING = HERE

/**
 * The development monorepo, which is not there when this package stands alone.
 *
 * `resolveMechanicsRepoRoot` walks up looking for a marker and is the right answer when the
 * checkout might be either. This is the answer when it is known to be the monorepo.
 */
export const MONOREPO_ROOT = path.resolve(PACKAGE_ROOT, '..', '..')
