import { describe, expect, it } from 'vitest'
import {
  BOT_BASE_UNLOCK_COSTS,
  BOT_UPGRADES_DATA,
  botStatValueAt,
} from '../../src/data/bots/data'
import {
  BOT_BASE_COST_LADDER,
  BOT_PLUS_ABILITIES,
  BOT_PLUS_IRREGULAR,
  BOT_STAT_MAX_LEVEL,
  BOT_UPGRADE_BASE_MEDAL_COST,
  BOT_UPGRADE_MEDAL_COST_STEP,
} from '../../src/knowledge/compartments/bots'

type Tier = { statOrder: string[], costs: number[], stats: Record<string, { base: string, levels: Record<number, string> }> }
const BOTS = BOT_UPGRADES_DATA as unknown as (Tier & { name: string, plus?: Tier })[]

const maxLevel = (tier: Tier, stat: string): number =>
  tier.stats[stat]?.maxLevel ?? 0

describe('bot base upgrade ladder', () => {
  it('is the same array on every bot', () => {
    for (const bot of BOTS) expect(bot.costs, bot.name).toEqual([...BOT_BASE_COST_LADDER])
  })

  it('is generated by the documented first cost and step', () => {
    for (let n = 0; n < BOT_BASE_COST_LADDER.length; n += 1) {
      const want = n === 0 ? 0 : BOT_UPGRADE_BASE_MEDAL_COST + BOT_UPGRADE_MEDAL_COST_STEP * (n - 1)
      expect(BOT_BASE_COST_LADDER[n], `entry ${n}`).toBe(want)
    }
  })

  it('is longer than every stat that pays from it', () => {
    for (const bot of BOTS) {
      for (const stat of bot.statOrder) {
        expect(maxLevel(bot, stat), `${bot.name}.${stat}`).toBeLessThan(BOT_BASE_COST_LADDER.length)
      }
    }
  })

  it('records a different ceiling for stats within the same bot', () => {
    for (const bot of BOTS) {
      const ceilings = new Set(Object.values(BOT_STAT_MAX_LEVEL[bot.name]!))
      expect(ceilings.size, `${bot.name} ceilings should not be uniform`).toBeGreaterThan(1)
    }
  })

  it('matches the shipped tables stat for stat', () => {
    for (const bot of BOTS) {
      for (const stat of bot.statOrder) {
        expect(BOT_STAT_MAX_LEVEL[bot.name]?.[stat], `${bot.name}.${stat}`).toBe(maxLevel(bot, stat))
      }
    }
  })

  it('treats base as the level-0 value, not an extra', () => {
    for (const bot of BOTS) {
      for (const stat of bot.statOrder) {
        // `base` IS the level-0 value by construction now, not by coincidence.
        expect(bot.stats[stat]!.base, `${bot.name}.${stat}`).toBe(botStatValueAt(bot.stats[stat]!, 0))
      }
    }
  })
})

describe('bot plus ladders', () => {
  it('covers every bot that has one', () => {
    expect(BOT_PLUS_ABILITIES).toHaveLength(BOTS.filter(b => b.plus).length)
    expect(BOT_PLUS_ABILITIES.length).toBe(BOTS.length)
  })

  it('names exactly one bot whose ladder step differs from the rest', () => {
    expect(BOT_PLUS_IRREGULAR).toEqual(['Amplify Bot'])
    const steps = new Set(BOT_PLUS_ABILITIES.map(e => e.costStep))
    expect(steps.size, 'more than two distinct steps would break the singular claim').toBe(2)
  })

  it('makes the irregular ladder shorter, steeper and dearer at the top', () => {
    const odd = BOT_PLUS_ABILITIES.find(e => e.bot === BOT_PLUS_IRREGULAR[0])!
    const rest = BOT_PLUS_ABILITIES.filter(e => e.bot !== odd.bot)
    for (const other of rest) {
      expect(odd.costEntries, other.bot).toBeLessThan(other.costEntries)
      expect(odd.costStep, other.bot).toBeGreaterThan(other.costStep)
      expect(odd.topCost, other.bot).toBeGreaterThan(other.topCost)
    }
  })

  it('leaves unused tail on exactly three ladders', () => {
    const withTail = BOT_PLUS_ABILITIES.filter(e => e.maxLevel < e.costEntries - 1)
    expect(withTail.map(e => e.bot).sort())
      .toEqual(['Bot Bot', 'Flame Bot', 'Thunder Bot'])
  })

  it('matches the shipped plus tables', () => {
    for (const entry of BOT_PLUS_ABILITIES) {
      const plus = BOTS.find(b => b.name === entry.bot)!.plus!
      expect(entry.ability).toBe(plus.statOrder[0])
      expect(entry.maxLevel).toBe(maxLevel(plus, entry.ability))
      expect(entry.costEntries).toBe(plus.costs.length)
    }
  })
})

describe('bot unlock costs', () => {
  it('still has one more entry than there are bots', () => {
    // Documented on the `bot` node as an unexplained spare. If a sixth bot ever
    // lands, this fails and the note needs revisiting rather than deleting.
    expect(BOT_BASE_UNLOCK_COSTS).toHaveLength(BOTS.length + 1)
  })
})
