/* ── file map ─────────────────────────────────────────────────────────────────
 * exports    SaveImportExecutionOutcome, SaveImportPersistencePort, executeSaveImportTarget, executeSaveImports, planSaveImportTarget, planSaveImports
 * depends    src/save/import/discovery, src/save/import/planner
 * used by    src/mechanics/calculators/specs-generated, src/save/import/index
 * ─────────────────────────────────────────────── generated by `npm run map` ──
 */
import type { SaveImportTargetKey } from './discovery'
import {
  planSaveImportTarget,
  planSaveImports,
  type SaveImportPlannerResult,
  type SaveImportTargetPayload,
} from './planner'

export type SaveImportExecutionOutcome = {
  key: SaveImportTargetKey
  label: string
  status: 'imported' | 'skipped' | 'failed'
  message?: string
  importedCount?: number
}

export type SaveImportPersistencePort = {
  persistBattleReports: (
    plan: Extract<SaveImportTargetPayload, { key: 'battleReports' }>['plan'],
  ) => Promise<{ added: number; updated: number }>
  persistLifetime: (
    payload: Extract<SaveImportTargetPayload, { key: 'lifetime' }>['payload'],
  ) => Promise<void>
  persistWorkshop: (
    payload: Extract<SaveImportTargetPayload, { key: 'workshop' }>['payload'],
  ) => Promise<void>
  persistLabs: (
    payload: Extract<SaveImportTargetPayload, { key: 'labs' }>['payload'],
  ) => Promise<void>
  persistUltimateWeapons: (
    payload: Extract<SaveImportTargetPayload, { key: 'ultimateWeapons' }>['payload'],
  ) => Promise<void>
  persistModules: (
    payload: Extract<SaveImportTargetPayload, { key: 'modules' }>['payload'],
  ) => Promise<void>
  persistCards: (
    payload: Extract<SaveImportTargetPayload, { key: 'cards' }>['payload'],
  ) => Promise<void>
  persistVault: (
    payload: Extract<SaveImportTargetPayload, { key: 'vault' }>['payload'],
  ) => Promise<void>
  persistBots: (
    payload: Extract<SaveImportTargetPayload, { key: 'bots' }>['payload'],
  ) => Promise<void>
  persistGuardians: (
    payload: Extract<SaveImportTargetPayload, { key: 'guardians' }>['payload'],
  ) => Promise<void>
  persistRelics: (
    payload: Extract<SaveImportTargetPayload, { key: 'relics' }>['payload'],
  ) => Promise<void>
  persistDissonance: (
    payload: Extract<SaveImportTargetPayload, { key: 'dissonance' }>['payload'],
    parsedRoot: unknown,
  ) => Promise<void>
}

async function persistPayload(
  payload: SaveImportTargetPayload,
  parsedRoot: unknown,
  port: SaveImportPersistencePort,
): Promise<Pick<SaveImportExecutionOutcome, 'message' | 'importedCount'>> {
  switch (payload.key) {
    case 'battleReports': {
      const result = await port.persistBattleReports(payload.plan)
      return {
        message: `${result.added} added, ${result.updated} updated`,
        importedCount: payload.plan.importable.length,
      }
    }
    case 'lifetime':
      await port.persistLifetime(payload.payload)
      return { message: 'Lifetime stats imported.', importedCount: 1 }
    case 'workshop':
      await port.persistWorkshop(payload.payload)
      return { message: 'Workshop imported.' }
    case 'labs':
      await port.persistLabs(payload.payload)
      return { message: 'Labs imported.' }
    case 'ultimateWeapons':
      await port.persistUltimateWeapons(payload.payload)
      return { message: 'Ultimate weapons imported.' }
    case 'modules':
      await port.persistModules(payload.payload)
      return { message: 'Modules imported.' }
    case 'cards':
      await port.persistCards(payload.payload)
      return { message: 'Cards imported.' }
    case 'vault':
      await port.persistVault(payload.payload)
      return { message: 'Vault imported.' }
    case 'bots':
      await port.persistBots(payload.payload)
      return { message: 'Bots imported.' }
    case 'guardians':
      await port.persistGuardians(payload.payload)
      return { message: 'Guardians imported.' }
    case 'relics':
      await port.persistRelics(payload.payload)
      return { message: 'Relics imported.' }
    case 'dissonance':
      await port.persistDissonance(payload.payload, parsedRoot)
      return {
        message: payload.payload.hasWaveData
          ? 'Dissonance wave data imported.'
          : 'Shared calculator inputs synced from save.',
      }
    default: {
      const _exhaustive: never = payload
      throw new Error(`Unsupported import payload: ${(_exhaustive as SaveImportTargetPayload).key}`)
    }
  }
}

export async function executeSaveImportTarget(
  planner: SaveImportPlannerResult,
  parsedRoot: unknown,
  port: SaveImportPersistencePort,
): Promise<SaveImportExecutionOutcome> {
  if (!planner.canImport || !planner.payload) {
    return {
      key: planner.key,
      label: planner.label,
      status: 'skipped',
      message: planner.skipReason ?? 'No importable data in save.',
    }
  }

  try {
    const result = await persistPayload(planner.payload, parsedRoot, port)
    return {
      key: planner.key,
      label: planner.label,
      status: 'imported',
      ...result,
    }
  } catch (error) {
    return {
      key: planner.key,
      label: planner.label,
      status: 'failed',
      message: error instanceof Error ? error.message : 'Import failed',
    }
  }
}

export async function executeSaveImports(args: {
  parsedRoot: unknown
  selectedKeys: readonly SaveImportTargetKey[]
  port: SaveImportPersistencePort
  existingRuns?: Array<Record<string, unknown>>
  onProgress?: (event: { key: SaveImportTargetKey; label: string; index: number; total: number }) => Promise<void> | void
}): Promise<SaveImportExecutionOutcome[]> {
  const planners = planSaveImports(args.parsedRoot, args.selectedKeys, {
    existingRuns: args.existingRuns,
  })
  const outcomes: SaveImportExecutionOutcome[] = []
  const total = planners.length

  for (let index = 0; index < planners.length; index += 1) {
    const planner = planners[index]!
    await args.onProgress?.({
      key: planner.key,
      label: planner.label,
      index: index + 1,
      total,
    })
    outcomes.push(await executeSaveImportTarget(planner, args.parsedRoot, args.port))
  }

  return outcomes
}

export { planSaveImportTarget, planSaveImports }
